/*
 * sajben_diffuser.java
 */

import com.comsol.model.*;
import com.comsol.model.util.*;

/** Model exported on Apr 29 2026, 18:31 by COMSOL 6.3.0.290. */
public class sajben_diffuser {

  public static Model run() {
    Model model = ModelUtil.create("Model");

    model
         .modelPath("D:\\Program Files\\COMSOL\\COMSOL63\\Multiphysics\\applications\\CFD_Module\\High_Mach_Number_Flow");

    model.component().create("comp1", true);

    model.component("comp1").geom().create("geom1", 2);

    model.component("comp1").mesh().create("mesh1");

    model.component("comp1").physics().create("hmnf", "HighMachNumberFlowTurbulentSpalartAllmaras", "geom1");

    model.study().create("std1");
    model.study("std1").create("wdi", "WallDistanceInitialization");
    model.study("std1").feature("wdi").set("solnum", "auto");
    model.study("std1").feature("wdi").set("notsolnum", "auto");
    model.study("std1").feature("wdi").set("outputmap", new String[]{});
    model.study("std1").feature("wdi").set("ngenAUX", "1");
    model.study("std1").feature("wdi").set("goalngenAUX", "1");
    model.study("std1").feature("wdi").set("ngenAUX", "1");
    model.study("std1").feature("wdi").set("goalngenAUX", "1");
    model.study("std1").feature("wdi").setSolveFor("/physics/hmnf", true);
    model.study("std1").create("stat", "Stationary");
    model.study("std1").feature("stat").set("solnum", "auto");
    model.study("std1").feature("stat").set("notsolnum", "auto");
    model.study("std1").feature("stat").set("outputmap", new String[]{});
    model.study("std1").feature("stat").set("ngenAUX", "1");
    model.study("std1").feature("stat").set("goalngenAUX", "1");
    model.study("std1").feature("stat").set("ngenAUX", "1");
    model.study("std1").feature("stat").set("goalngenAUX", "1");
    model.study("std1").feature("stat").setSolveFor("/physics/hmnf", true);

    model.param().set("x0", "-6.99809[in]");
    model.param().descr("x0", "\u5165\u53e3 x \u4f4d\u7f6e");
    model.param().set("xEnd", "14.98353[in]");
    model.param().descr("xEnd", "\u51fa\u53e3 x \u4f4d\u7f6e");
    model.param().set("h_in", "2.44483[in]");
    model.param().descr("h_in", "\u6269\u5f20\u5668\u5165\u53e3\u9ad8\u5ea6");
    model.param().set("h_out", "2.59830[in]");
    model.param().descr("h_out", "\u6269\u5f20\u5668\u51fa\u53e3\u9ad8\u5ea6");
    model.param().set("h_th", "1.732[in]");
    model.param().descr("h_th", "\u5589\u90e8\u9ad8\u5ea6");
    model.param().label("\u51e0\u4f55\u53c2\u6570");
    model.param().create("par2");
    model.param("par2").label("\u6d41\u4f53\u6d41\u52a8\u53c2\u6570");
    model.param("par2").set("Rein", "7e5");
    model.param("par2").descr("Rein", "\u5165\u53e3\u96f7\u8bfa\u6570");
    model.param("par2").set("case", "1");
    model.param("par2").descr("case", "\u6848\u4f8b\u53f7\uff1a1 = \u5f31\u6fc0\u6ce2, 2 = \u5f3a\u6fc0\u6ce2");
    model.param("par2").set("Min", "0.46");
    model.param("par2").descr("Min", "\u5165\u53e3\u9a6c\u8d6b\u6570");
    model.param("par2").set("gamma", "1.4");
    model.param("par2").descr("gamma", "\u6bd4\u70ed\u7387");
    model.param("par2").set("Pr", "0.72");
    model.param("par2").descr("Pr", "\u666e\u6717\u7279\u6570");
    model.param("par2").set("Rs", "287[J/kg/K]");
    model.param("par2").descr("Rs", "\u6bd4\u6c14\u4f53\u5e38\u6570");
    model.param("par2").set("Tin_tot", "500[R]");
    model.param("par2").descr("Tin_tot", "\u5165\u53e3\u603b\u6e29\u5ea6");
    model.param("par2").set("Tin_stat", "Tin_tot/(1+0.5*Min^2*(-1+gamma))");
    model.param("par2").descr("Tin_stat", "\u5165\u53e3\u9759\u6001\u6e29\u5ea6");
    model.param("par2").set("pin_tot", "19.58[psi]");
    model.param("par2").descr("pin_tot", "\u5165\u53e3\u603b\u538b\u529b");
    model.param("par2").set("pin_stat", "pin_tot/(1+0.5*Min^2*(-1+gamma))^(gamma/(-1+gamma))");
    model.param("par2").descr("pin_stat", "\u5165\u53e3\u9759\u6001\u538b\u529b");
    model.param("par2").set("rhoin", "pin_stat/Rs/Tin_stat");
    model.param("par2").descr("rhoin", "\u5165\u53e3\u5bc6\u5ea6");
    model.param("par2").set("mu_ref", "rhoin*u_in*h_in/Rein");
    model.param("par2").descr("mu_ref", "\u53c2\u8003\u52a8\u529b\u9ecf\u5ea6");
    model.param("par2").set("u_in", "Min*sqrt(gamma*Rs*Tin_stat+eps)");
    model.param("par2").descr("u_in", "\u5165\u53e3\u901f\u5ea6");
    model.param("par2").set("pOut", "if(case==1,16.05,0)[psi]+if(case==2,14.1,0)[psi]");
    model.param("par2").descr("pOut", "\u51fa\u53e3\u538b\u529b");

    model.func().create("int1", "Interpolation");
    model.func("int1").set("source", "file");
    model.func("int1").set("filename", "sajben_diffuser_upper_wall.txt");
    model.func("int1").setEntry("funcnames", "col2", "top_pos");
    model.func("int1").setIndex("fununit", "in", 0);
    model.func("int1").importData();
    model.func().create("int2", "Interpolation");
    model.func("int2").set("source", "file");
    model.func("int2").set("filename", "sajben_diffuser_ptop_weak.txt");
    model.func("int2").setEntry("funcnames", "col2", "ptop_weak");
    model.func("int2").importData();
    model.func().create("int3", "Interpolation");
    model.func("int3").set("source", "file");
    model.func("int3").set("filename", "sajben_diffuser_ptop_strong.txt");
    model.func("int3").setEntry("funcnames", "col2", "ptop_strong");
    model.func("int3").importData();
    model.func().create("int4", "Interpolation");
    model.func("int4").set("source", "file");
    model.func("int4").set("filename", "sajben_diffuser_u-xh4611.txt");
    model.func("int4").setEntry("funcnames", "col2", "u_at4611");
    model.func("int4").importData();
    model.func().create("int5", "Interpolation");
    model.func("int5").set("source", "file");
    model.func("int5").set("filename", "sajben_diffuser_u-xh6340.txt");
    model.func("int5").setEntry("funcnames", "col2", "u_at6340");
    model.func("int5").importData();

    model.component("comp1").geom("geom1").create("pc1", "ParametricCurve");
    model.component("comp1").geom("geom1").feature("pc1").set("parmin", "x0[1/in]");
    model.component("comp1").geom("geom1").feature("pc1").set("parmax", "xEnd[1/in]");
    model.component("comp1").geom("geom1").feature("pc1").set("coord", new String[]{"s[in]", "top_pos(s)"});
    model.component("comp1").geom("geom1").run("pc1");
    model.component("comp1").geom("geom1").create("pol1", "Polygon");
    model.component("comp1").geom("geom1").feature("pol1").set("source", "table");
    model.component("comp1").geom("geom1").feature("pol1").set("type", "open");
    model.component("comp1").geom("geom1").feature("pol1").set("source", "vectors");
    model.component("comp1").geom("geom1").feature("pol1").set("x", "x0 x0 x0 xEnd xEnd xEnd");
    model.component("comp1").geom("geom1").feature("pol1").set("y", "h_in 0 0 0 0 h_out");
    model.component("comp1").geom("geom1").run("pol1");
    model.component("comp1").geom("geom1").create("csol1", "ConvertToSolid");
    model.component("comp1").geom("geom1").feature("csol1").selection("input").set("pc1", "pol1");
    model.component("comp1").geom("geom1").run("csol1");
    model.component("comp1").geom("geom1").create("r1", "Rectangle");
    model.component("comp1").geom("geom1").feature("r1").set("size", new double[]{0.16, 0.1});
    model.component("comp1").geom("geom1").feature("r1").set("pos", new double[]{0.025, 0});
    model.component("comp1").geom("geom1").run("r1");
    model.component("comp1").geom("geom1").create("par1", "Partition");
    model.component("comp1").geom("geom1").feature("par1").selection("input").set("csol1");
    model.component("comp1").geom("geom1").feature("par1").selection("tool").set("r1");
    model.component("comp1").geom("geom1").run("par1");
    model.component("comp1").geom("geom1").run("fin");
    model.component("comp1").geom("geom1").create("mce1", "MeshControlEdges");
    model.component("comp1").geom("geom1").feature("mce1").selection("input").set("fin", 3, 5);
    model.component("comp1").geom("geom1").run("mce1");

    model.component("comp1").physics("hmnf").feature("fluid1").set("k_mat", "userdef");
    model.component("comp1").physics("hmnf").feature("fluid1")
         .set("k", new String[]{"hmnf.Cp*hmnf.mu/Pr", "0", "0", "0", "hmnf.Cp*hmnf.mu/Pr", "0", "0", "0", "hmnf.Cp*hmnf.mu/Pr"});
    model.component("comp1").physics("hmnf").feature("fluid1").set("Rs_mat", "userdef");
    model.component("comp1").physics("hmnf").feature("fluid1").set("Rs", "Rs");
    model.component("comp1").physics("hmnf").feature("fluid1").set("CpOrGammaOption", "gamma");
    model.component("comp1").physics("hmnf").feature("fluid1").set("gamma_mat", "userdef");
    model.component("comp1").physics("hmnf").feature("fluid1").set("gamma", "gamma");
    model.component("comp1").physics("hmnf").feature("fluid1").set("mu_ref", "mu_ref");
    model.component("comp1").physics("hmnf").feature("fluid1").set("Tmu_ref", "Tin_stat");
    model.component("comp1").physics("hmnf").feature("init1").set("u_init", new String[]{"u_in", "0", "0"});
    model.component("comp1").physics("hmnf").feature("init1").set("p_init", "pin_stat");
    model.component("comp1").physics("hmnf").feature("init1")
         .set("nutilde_init", "subst(hmnf.nutildeinit,p,pin_stat)");
    model.component("comp1").physics("hmnf").feature("init1").set("Tinit", "Tin_stat");
    model.component("comp1").physics("hmnf").create("hminl1", "HighMachNumberFlowInlet", 1);
    model.component("comp1").physics("hmnf").feature("hminl1").selection().set(1);
    model.component("comp1").physics("hmnf").feature("hminl1").set("InputState", "TotalConditions");
    model.component("comp1").physics("hmnf").feature("hminl1").set("p0tot", "pin_tot");
    model.component("comp1").physics("hmnf").feature("hminl1").set("T0tot", "Tin_tot");
    model.component("comp1").physics("hmnf").feature("hminl1").set("Ma0", "Min");
    model.component("comp1").physics("hmnf").create("hmout1", "HighMachNumberFlowOutlet", 1);
    model.component("comp1").physics("hmnf").feature("hmout1").selection().set(3);
    model.component("comp1").physics("hmnf").feature("hmout1").set("FlowCondition", "Subsonic");
    model.component("comp1").physics("hmnf").feature("hmout1").set("BoundaryCondition", "Pressure");
    model.component("comp1").physics("hmnf").feature("hmout1").set("p0", "pOut");

    model.component("comp1").mesh("mesh1").create("map1", "Map");
    model.component("comp1").mesh("mesh1").feature("map1").create("dis1", "Distribution");
    model.component("comp1").mesh("mesh1").feature("map1").feature("dis1").selection().set(4, 6);
    model.component("comp1").mesh("mesh1").feature("map1").feature("dis1").set("type", "predefined");
    model.component("comp1").mesh("mesh1").feature("map1").feature("dis1").set("elemcount", 40);
    model.component("comp1").mesh("mesh1").feature("map1").feature("dis1").set("elemratio", "1/4");
    model.component("comp1").mesh("mesh1").feature("map1").create("dis2", "Distribution");
    model.component("comp1").mesh("mesh1").feature("map1").feature("dis2").selection().set(5, 7);
    model.component("comp1").mesh("mesh1").feature("map1").feature("dis2").set("type", "predefined");
    model.component("comp1").mesh("mesh1").feature("map1").feature("dis2").set("elemcount", 90);
    model.component("comp1").mesh("mesh1").feature("map1").create("dis3", "Distribution");
    model.component("comp1").mesh("mesh1").feature("map1").feature("dis3").selection().set(2, 8);
    model.component("comp1").mesh("mesh1").feature("map1").feature("dis3").set("type", "predefined");
    model.component("comp1").mesh("mesh1").feature("map1").feature("dis3").set("elemcount", 50);
    model.component("comp1").mesh("mesh1").feature("map1").feature("dis3").set("elemratio", 3);
    model.component("comp1").mesh("mesh1").feature("map1").feature("dis3").set("reverse", true);
    model.component("comp1").mesh("mesh1").feature("map1").create("dis4", "Distribution");
    model.component("comp1").mesh("mesh1").feature("map1").feature("dis4").selection().set(1, 3);
    model.component("comp1").mesh("mesh1").feature("map1").feature("dis4").set("type", "predefined");
    model.component("comp1").mesh("mesh1").feature("map1").feature("dis4").set("elemcount", 25);
    model.component("comp1").mesh("mesh1").feature("map1").feature("dis4").set("elemratio", 2.5);
    model.component("comp1").mesh("mesh1").feature("map1").feature("dis4").set("symmetric", true);
    model.component("comp1").mesh("mesh1").run();
    model.component("comp1").mesh("mesh1").create("bl1", "BndLayer");
    model.component("comp1").mesh("mesh1").feature("bl1").create("blp", "BndLayerProp");
    model.component("comp1").mesh("mesh1").feature("bl1").set("smoothtransition", false);
    model.component("comp1").mesh("mesh1").feature("bl1").feature("blp").selection().set(2, 4, 6, 8, 9, 10);
    model.component("comp1").mesh("mesh1").feature("bl1").feature("blp").set("blnlayers", 20);
    model.component("comp1").mesh("mesh1").feature("bl1").feature("blp").set("blhminfact", 0.11);
    model.component("comp1").mesh("mesh1").run();

    model.study("std1").create("param", "Parametric");
    model.study("std1").feature("param").setIndex("pname", "case", 0);
    model.study("std1").feature("param").setIndex("plistarr", "", 0);
    model.study("std1").feature("param").setIndex("punit", "", 0);
    model.study("std1").feature("param").setIndex("pname", "case", 0);
    model.study("std1").feature("param").setIndex("plistarr", "", 0);
    model.study("std1").feature("param").setIndex("punit", "", 0);
    model.study("std1").feature("param").setIndex("plistarr", 1, 0);
    model.study("std1").feature("stat").set("useparam", true);
    model.study("std1").feature("stat").setIndex("pname", "case", 0);
    model.study("std1").feature("stat").setIndex("plistarr", "", 0);
    model.study("std1").feature("stat").setIndex("punit", "", 0);
    model.study("std1").feature("stat").setIndex("pname", "case", 0);
    model.study("std1").feature("stat").setIndex("plistarr", "", 0);
    model.study("std1").feature("stat").setIndex("punit", "", 0);
    model.study("std1").feature("stat").setIndex("pname", "Rein", 0);
    model.study("std1").feature("stat").setIndex("plistarr", "5e3 5e4 2e5 7e5", 0);
    model.study("std1").createAutoSequences("all");

    model.sol().create("sol3");
    model.sol("sol3").study("std1");
    model.sol("sol3").label("\u53c2\u6570\u5316\u89e3 1");

    model.batch("p1").feature("so1").set("psol", "sol3");
    model.batch("p1").run("compute");

    model.result().dataset("dset3").set("geom", "geom1");
    model.result().create("pg1", "PlotGroup2D");
    model.result("pg1").label("\u901f\u5ea6 (hmnf)");
    model.result("pg1").set("data", "dset3");
    model.result("pg1").setIndex("looplevel", 4, 0);
    model.result("pg1").setIndex("looplevel", 1, 1);
    model.result("pg1").set("frametype", "spatial");
    model.result("pg1").feature().create("surf1", "Surface");
    model.result("pg1").feature("surf1").label("\u8868\u9762");
    model.result("pg1").feature("surf1").set("showsolutionparams", "on");
    model.result("pg1").feature("surf1").set("smooth", "internal");
    model.result("pg1").feature("surf1").set("showsolutionparams", "on");
    model.result("pg1").feature("surf1").set("data", "parent");
    model.result().create("pg2", "PlotGroup2D");
    model.result("pg2").label("\u538b\u529b (hmnf)");
    model.result("pg2").set("data", "dset3");
    model.result("pg2").setIndex("looplevel", 4, 0);
    model.result("pg2").setIndex("looplevel", 1, 1);
    model.result("pg2").set("frametype", "spatial");
    model.result("pg2").feature().create("con1", "Contour");
    model.result("pg2").feature("con1").label("\u7b49\u503c\u7ebf");
    model.result("pg2").feature("con1").set("showsolutionparams", "on");
    model.result("pg2").feature("con1").set("expr", "p");
    model.result("pg2").feature("con1").set("number", 40);
    model.result("pg2").feature("con1").set("levelrounding", false);
    model.result("pg2").feature("con1").set("smooth", "internal");
    model.result("pg2").feature("con1").set("showsolutionparams", "on");
    model.result("pg2").feature("con1").set("data", "parent");
    model.result().dataset().create("edg1", "Edge2D");
    model.result().dataset("edg1").label("\u5916\u58c1");
    model.result().dataset("edg1").set("data", "dset3");
    model.result().dataset("edg1").selection().geom("geom1", 1);
    model.result().dataset("edg1").selection().set(2, 4);
    model.result().create("pg3", "PlotGroup2D");
    model.result("pg3").label("\u58c1\u5206\u8fa8\u7387 (hmnf)");
    model.result("pg3").set("data", "dset3");
    model.result("pg3").setIndex("looplevel", 4, 0);
    model.result("pg3").setIndex("looplevel", 1, 1);
    model.result("pg3").set("frametype", "spatial");
    model.result("pg3").feature().create("line1", "Line");
    model.result("pg3").feature("line1").label("\u58c1\u5206\u8fa8\u7387");
    model.result("pg3").feature("line1").set("showsolutionparams", "on");
    model.result("pg3").feature("line1").set("expr", "hmnf.Delta_wPlus");
    model.result("pg3").feature("line1").set("linetype", "tube");
    model.result("pg3").feature("line1").set("smooth", "internal");
    model.result("pg3").feature("line1").set("showsolutionparams", "on");
    model.result("pg3").feature("line1").set("data", "parent");
    model.result("pg3").feature("line1").feature().create("hght1", "Height");
    model.result("pg3").feature("line1").feature("hght1").label("\u9ad8\u5ea6\u8868\u8fbe\u5f0f");
    model.result("pg3").feature("line1").feature("hght1").set("heightdata", "expr");
    model.result("pg3").feature("line1").feature("hght1").set("expr", "hmnf.WRHeightExpr");
    model.result().create("pg4", "PlotGroup2D");
    model.result("pg4").label("\u6e29\u5ea6 (hmnf)");
    model.result("pg4").set("data", "dset3");
    model.result("pg4").setIndex("looplevel", 4, 0);
    model.result("pg4").setIndex("looplevel", 1, 1);
    model.result("pg4").feature().create("surf1", "Surface");
    model.result("pg4").feature("surf1").set("showsolutionparams", "on");
    model.result("pg4").feature("surf1").set("solutionparams", "parent");
    model.result("pg4").feature("surf1").set("expr", "T");
    model.result("pg4").feature("surf1").set("colortable", "HeatCameraLight");
    model.result("pg4").feature("surf1").set("showsolutionparams", "on");
    model.result("pg4").feature("surf1").set("data", "parent");
    model.result().create("pg5", "PlotGroup2D");
    model.result("pg5").label("\u9a6c\u8d6b\u6570 (hmnf)");
    model.result("pg5").set("data", "dset3");
    model.result("pg5").setIndex("looplevel", 4, 0);
    model.result("pg5").setIndex("looplevel", 1, 1);
    model.result("pg5").feature().create("surf1", "Surface");
    model.result("pg5").feature("surf1").set("expr", "hmnf.Ma");
    model.result("pg5").feature("surf1").set("smooth", "internal");
    model.result("pg5").feature("surf1").set("data", "parent");
    model.result("pg1").run();
    model.result("pg5").run();
    model.result("pg5").run();
    model.result("pg5").feature("surf1").set("colortable", "JupiterAuroraBorealis");
    model.result("pg5").feature("surf1").set("colortabletrans", "reverse");
    model.result("pg5").run();
    model.result("pg5").create("str1", "Streamline");
    model.result("pg5").feature("str1").selection().set(1);
    model.result("pg5").feature("str1").set("selnumber", 9);
    model.result("pg5").run();
    model.result("pg5").create("con1", "Contour");
    model.result("pg5").feature("con1").set("expr", "u");
    model.result("pg5").feature("con1").set("levelmethod", "levels");
    model.result("pg5").feature("con1").set("coloring", "uniform");
    model.result("pg5").feature("con1").set("colorlegend", false);
    model.result("pg5").run();
    model.result("pg1").run();

    model.nodeGroup().create("grp1", "Results");
    model.nodeGroup("grp1").set("type", "plotgroup");
    model.nodeGroup("grp1").add("plotgroup", "pg1");
    model.nodeGroup("grp1").add("plotgroup", "pg2");
    model.nodeGroup("grp1").add("plotgroup", "pg3");
    model.nodeGroup("grp1").add("plotgroup", "pg4");
    model.nodeGroup("grp1").add("plotgroup", "pg5");
    model.nodeGroup("grp1").label("\u5f31\u6fc0\u6ce2");

    model.study().create("std2");
    model.study("std2").create("wdi", "WallDistanceInitialization");
    model.study("std2").feature("wdi").set("plotgroup", "Default");
    model.study("std2").feature("wdi").set("solnum", "auto");
    model.study("std2").feature("wdi").set("notsolnum", "auto");
    model.study("std2").feature("wdi").set("outputmap", new String[]{});
    model.study("std2").feature("wdi").set("ngenAUX", "1");
    model.study("std2").feature("wdi").set("goalngenAUX", "1");
    model.study("std2").feature("wdi").set("ngenAUX", "1");
    model.study("std2").feature("wdi").set("goalngenAUX", "1");
    model.study("std2").feature("wdi").setSolveFor("/physics/hmnf", true);
    model.study("std2").create("stat", "Stationary");
    model.study("std2").feature("stat").set("plotgroup", "Default");
    model.study("std2").feature("stat").set("solnum", "auto");
    model.study("std2").feature("stat").set("notsolnum", "auto");
    model.study("std2").feature("stat").set("outputmap", new String[]{});
    model.study("std2").feature("stat").set("ngenAUX", "1");
    model.study("std2").feature("stat").set("goalngenAUX", "1");
    model.study("std2").feature("stat").set("ngenAUX", "1");
    model.study("std2").feature("stat").set("goalngenAUX", "1");
    model.study("std2").feature("stat").setSolveFor("/physics/hmnf", true);
    model.study("std2").create("param", "Parametric");
    model.study("std2").feature("param").setIndex("pname", "case", 0);
    model.study("std2").feature("param").setIndex("plistarr", "", 0);
    model.study("std2").feature("param").setIndex("punit", "", 0);
    model.study("std2").feature("param").setIndex("pname", "case", 0);
    model.study("std2").feature("param").setIndex("plistarr", "", 0);
    model.study("std2").feature("param").setIndex("punit", "", 0);
    model.study("std2").feature("param").setIndex("plistarr", 2, 0);
    model.study("std2").feature("wdi").set("usesol", true);
    model.study("std2").feature("wdi").set("notsolmethod", "sol");
    model.study("std2").feature("wdi").set("notstudy", "std1");
    model.study("std2").feature("wdi").set("notsolnum", "last");
    model.study("std2").showAutoSequences("all");

    model.sol("sol5").feature("s2").feature("se1").set("subcfltol", 0.02);

    model.study("std2").createAutoSequences("all");

    model.sol().create("sol7");
    model.sol("sol7").study("std2");
    model.sol("sol7").label("\u53c2\u6570\u5316\u89e3 2");

    model.batch("p2").feature("so1").set("psol", "sol7");
    model.batch("p2").run("compute");

    model.result().dataset("dset6").set("geom", "geom1");
    model.result().create("pg6", "PlotGroup2D");
    model.result("pg6").label("\u901f\u5ea6 (hmnf) 1");
    model.result("pg6").set("data", "dset6");
    model.result("pg6").setIndex("looplevel", 1, 0);
    model.result("pg6").set("frametype", "spatial");
    model.result("pg6").feature().create("surf1", "Surface");
    model.result("pg6").feature("surf1").label("\u8868\u9762");
    model.result("pg6").feature("surf1").set("showsolutionparams", "on");
    model.result("pg6").feature("surf1").set("smooth", "internal");
    model.result("pg6").feature("surf1").set("showsolutionparams", "on");
    model.result("pg6").feature("surf1").set("data", "parent");
    model.result().create("pg7", "PlotGroup2D");
    model.result("pg7").label("\u538b\u529b (hmnf) 1");
    model.result("pg7").set("data", "dset6");
    model.result("pg7").setIndex("looplevel", 1, 0);
    model.result("pg7").set("frametype", "spatial");
    model.result("pg7").feature().create("con1", "Contour");
    model.result("pg7").feature("con1").label("\u7b49\u503c\u7ebf");
    model.result("pg7").feature("con1").set("showsolutionparams", "on");
    model.result("pg7").feature("con1").set("expr", "p");
    model.result("pg7").feature("con1").set("number", 40);
    model.result("pg7").feature("con1").set("levelrounding", false);
    model.result("pg7").feature("con1").set("smooth", "internal");
    model.result("pg7").feature("con1").set("showsolutionparams", "on");
    model.result("pg7").feature("con1").set("data", "parent");
    model.result().dataset().create("edg2", "Edge2D");
    model.result().dataset("edg2").label("\u5916\u58c1 1");
    model.result().dataset("edg2").set("data", "dset6");
    model.result().dataset("edg2").selection().geom("geom1", 1);
    model.result().dataset("edg2").selection().set(2, 4);
    model.result().create("pg8", "PlotGroup2D");
    model.result("pg8").label("\u58c1\u5206\u8fa8\u7387 (hmnf) 1");
    model.result("pg8").set("data", "dset6");
    model.result("pg8").setIndex("looplevel", 1, 0);
    model.result("pg8").set("frametype", "spatial");
    model.result("pg8").feature().create("line1", "Line");
    model.result("pg8").feature("line1").label("\u58c1\u5206\u8fa8\u7387");
    model.result("pg8").feature("line1").set("showsolutionparams", "on");
    model.result("pg8").feature("line1").set("expr", "hmnf.Delta_wPlus");
    model.result("pg8").feature("line1").set("linetype", "tube");
    model.result("pg8").feature("line1").set("smooth", "internal");
    model.result("pg8").feature("line1").set("showsolutionparams", "on");
    model.result("pg8").feature("line1").set("data", "parent");
    model.result("pg8").feature("line1").feature().create("hght1", "Height");
    model.result("pg8").feature("line1").feature("hght1").label("\u9ad8\u5ea6\u8868\u8fbe\u5f0f");
    model.result("pg8").feature("line1").feature("hght1").set("heightdata", "expr");
    model.result("pg8").feature("line1").feature("hght1").set("expr", "hmnf.WRHeightExpr");
    model.result().create("pg9", "PlotGroup2D");
    model.result("pg9").label("\u6e29\u5ea6 (hmnf) 1");
    model.result("pg9").set("data", "dset6");
    model.result("pg9").setIndex("looplevel", 1, 0);
    model.result("pg9").feature().create("surf1", "Surface");
    model.result("pg9").feature("surf1").set("showsolutionparams", "on");
    model.result("pg9").feature("surf1").set("solutionparams", "parent");
    model.result("pg9").feature("surf1").set("expr", "T");
    model.result("pg9").feature("surf1").set("colortable", "HeatCameraLight");
    model.result("pg9").feature("surf1").set("showsolutionparams", "on");
    model.result("pg9").feature("surf1").set("data", "parent");
    model.result().create("pg10", "PlotGroup2D");
    model.result("pg10").label("\u9a6c\u8d6b\u6570 (hmnf) 1");
    model.result("pg10").set("data", "dset6");
    model.result("pg10").setIndex("looplevel", 1, 0);
    model.result("pg10").feature().create("surf1", "Surface");
    model.result("pg10").feature("surf1").set("expr", "hmnf.Ma");
    model.result("pg10").feature("surf1").set("smooth", "internal");
    model.result("pg10").feature("surf1").set("data", "parent");
    model.result("pg6").run();
    model.result("pg10").run();
    model.result("pg10").run();
    model.result("pg10").feature("surf1").set("colortable", "JupiterAuroraBorealis");
    model.result("pg10").feature("surf1").set("colortabletrans", "reverse");
    model.result("pg10").run();
    model.result("pg10").create("str1", "Streamline");
    model.result("pg10").feature("str1").set("expr", new String[]{"u", "v"});
    model.result("pg10").feature("str1").set("descr", "\u901f\u5ea6\u573a");
    model.result("pg10").feature("str1").selection().set(1);
    model.result("pg10").feature("str1").set("selnumber", 9);
    model.result("pg10").run();
    model.result("pg10").create("con1", "Contour");
    model.result("pg10").feature("con1").set("expr", "u");
    model.result("pg10").feature("con1").set("descr", "\u901f\u5ea6\u573a\uff0cx \u5206\u91cf");
    model.result("pg10").feature("con1").set("levelmethod", "levels");
    model.result("pg10").feature("con1").set("coloring", "uniform");
    model.result("pg10").feature("con1").set("colorlegend", false);
    model.result("pg10").run();
    model.result("pg6").run();

    model.nodeGroup().create("grp2", "Results");
    model.nodeGroup("grp2").set("type", "plotgroup");
    model.nodeGroup().move("grp2", 1);
    model.nodeGroup("grp2").add("plotgroup", "pg6");
    model.nodeGroup("grp2").add("plotgroup", "pg7");
    model.nodeGroup("grp2").add("plotgroup", "pg8");
    model.nodeGroup("grp2").add("plotgroup", "pg9");
    model.nodeGroup("grp2").add("plotgroup", "pg10");
    model.nodeGroup("grp2").label("\u5f3a\u6fc0\u6ce2");

    model.result().dataset().create("cln1", "CutLine2D");
    model.result().dataset("cln1").set("data", "dset4");
    model.result().dataset("cln1").setIndex("genpoints", "4.611*h_th", 0, 0);
    model.result().dataset("cln1").setIndex("genpoints", "4.611*h_th", 1, 0);
    model.result().dataset("cln1").setIndex("genpoints", "2*h_th", 1, 1);
    model.result().dataset().create("cln2", "CutLine2D");
    model.result().dataset("cln2").set("data", "dset4");
    model.result().dataset("cln2").setIndex("genpoints", "6.340*h_th", 0, 0);
    model.result().dataset("cln2").setIndex("genpoints", "6.340*h_th", 1, 0);
    model.result().dataset("cln2").setIndex("genpoints", "2*h_th", 1, 1);
    model.result().create("pg11", "PlotGroup1D");
    model.result("pg11").run();
    model.result("pg11").setIndex("looplevelinput", "last", 0);
    model.result("pg11").create("lngr1", "LineGraph");
    model.result("pg11").feature("lngr1").set("markerpos", "datapoints");
    model.result("pg11").feature("lngr1").set("linewidth", "preference");
    model.result("pg11").feature("lngr1").selection().set(4);
    model.result("pg11").feature("lngr1").set("expr", "p/pin_tot");
    model.result("pg11").feature("lngr1").set("xdataexpr", "x");
    model.result("pg11").feature("lngr1").set("xdatadescr", "x \u5750\u6807");
    model.result("pg11").feature().duplicate("lngr2", "lngr1");
    model.result("pg11").run();
    model.result("pg11").feature("lngr2").set("expr", "ptop_weak(x/h_th)");
    model.result("pg11").feature("lngr2").set("linestyle", "none");
    model.result("pg11").feature("lngr2").set("linecolor", "black");
    model.result("pg11").feature("lngr2").set("linemarker", "diamond");
    model.result("pg11").feature("lngr2").set("markerpos", "interp");
    model.result("pg11").feature("lngr2").set("markers", 30);
    model.result("pg11").run();
    model.result("pg11").set("titletype", "manual");
    model.result("pg11").set("title", "\u5f31\u6fc0\u6ce2");
    model.result("pg11").set("axislimits", true);
    model.result("pg11").set("xmin", -0.2);
    model.result("pg11").set("xmax", 0.4);
    model.result("pg11").set("ymin", 0.25);
    model.result("pg11").set("ymax", 1);
    model.result("pg11").set("manualgrid", true);
    model.result("pg11").set("xspacing", 0.05);
    model.result("pg11").set("yspacing", 0.1);
    model.result("pg11").run();
    model.result().duplicate("pg12", "pg11");
    model.result("pg12").run();
    model.result("pg12").set("data", "dset4");
    model.result("pg12").set("title", "\u5f3a\u6fc0\u6ce2");
    model.result("pg12").run();
    model.result("pg12").feature("lngr2").set("expr", "ptop_strong(x/h_th)");
    model.result("pg12").run();
    model.result("pg12").run();
    model.result("pg12").run();
    model.result().create("pg13", "PlotGroup1D");
    model.result("pg13").run();
    model.result("pg13").set("data", "cln1");
    model.result("pg13").create("lngr1", "LineGraph");
    model.result("pg13").feature("lngr1").set("markerpos", "datapoints");
    model.result("pg13").feature("lngr1").set("linewidth", "preference");
    model.result("pg13").feature("lngr1").set("expr", "u");
    model.result("pg13").feature("lngr1").set("descr", "\u901f\u5ea6\u573a\uff0cx \u5206\u91cf");

    return model;
  }

  public static Model run2(Model model) {
    model.result("pg13").feature("lngr1").set("xdata", "expr");
    model.result("pg13").feature("lngr1").set("xdataexpr", "y/0.0617");
    model.result("pg13").run();
    model.result("pg13").create("lngr2", "LineGraph");
    model.result("pg13").feature("lngr2").set("markerpos", "datapoints");
    model.result("pg13").feature("lngr2").set("linewidth", "preference");
    model.result("pg13").feature("lngr2").set("expr", "u_at4611(y/0.0617)");
    model.result("pg13").feature("lngr2").set("xdata", "expr");
    model.result("pg13").feature("lngr2").set("xdataexpr", "y/0.0617");
    model.result("pg13").feature("lngr2").set("linestyle", "none");
    model.result("pg13").feature("lngr2").set("linecolor", "black");
    model.result("pg13").feature("lngr2").set("linemarker", "diamond");
    model.result("pg13").feature("lngr2").set("markerpos", "interp");
    model.result("pg13").feature("lngr2").set("markers", 30);
    model.result("pg13").run();
    model.result("pg13").set("titletype", "manual");
    model.result("pg13").set("title", "x/h_th = 4.611");
    model.result("pg13").set("ylabelactive", true);
    model.result("pg13").set("ylabel", "u (m/s)");
    model.result("pg13").set("axislimits", true);
    model.result("pg13").set("xmin", -0.1);
    model.result("pg13").set("xmax", 1.1);
    model.result("pg13").set("ymin", -80);
    model.result("pg13").set("ymax", 320);
    model.result("pg13").set("manualgrid", true);
    model.result("pg13").set("xspacing", 0.05);
    model.result("pg13").set("yspacing", 20);
    model.result("pg13").run();
    model.result().duplicate("pg14", "pg13");
    model.result("pg14").run();
    model.result("pg14").set("data", "cln2");
    model.result("pg14").set("title", "x/h_th = 6.340");
    model.result("pg14").run();
    model.result("pg14").feature("lngr1").set("xdataexpr", "y/0.066");
    model.result("pg14").run();
    model.result("pg14").feature("lngr2").set("expr", "u_at6340(y/0.066)");
    model.result("pg14").feature("lngr2").set("xdataexpr", "y/0.066");
    model.result("pg14").run();

    model.title("Sajben \u6269\u538b\u5668\u4e2d\u7684\u8de8\u97f3\u901f\u6d41\u52a8");

    model
         .description("\u8fd9\u662f\u4e00\u4e2a\u7528\u4e8e\u6e4d\u6d41\u53ef\u538b\u7f29\u6d41\u52a8\u7684\u57fa\u51c6\u6848\u4f8b\uff0c\u7814\u7a76\u7684\u662f\u4e8c\u7ef4\u6536\u655b-\u53d1\u6563\u55b7\u5634\uff08Sajben \u6269\u538b\u5668\uff09\u4e2d\u7684\u6d41\u52a8\u7279\u6027\u3002\u6d41\u4f53\u4ee5 Ma = 0.46 \u7684\u901f\u5ea6\u8fdb\u5165\u6269\u538b\u5668\uff0c\u901a\u8fc7\u6536\u655b\u90e8\u5206\u52a0\u901f\uff0c\u5728\u55b7\u5634\u5589\u90e8\u8fbe\u5230\u97f3\u901f\u72b6\u6001\u3002\u8d85\u97f3\u901f\u6d41\u5728\u53d1\u6563\u90e8\u5206\u88ab\u6fc0\u6ce2\u7ec8\u6b62\u3002\u6a21\u578b\u9488\u5bf9\u4e24\u79cd\u4e0d\u540c\u51fa\u53e3\u538b\u529b\u503c\u7684\u60c5\u51b5\uff0c\u8ba1\u7b97\u4e86\u6fc0\u6ce2\u7684\u7a33\u5b9a\u4f4d\u7f6e\u3002");

    model.mesh().clearMeshes();

    model.sol("sol1").clearSolutionData();
    model.sol("sol2").clearSolutionData();
    model.sol("sol3").clearSolutionData();
    model.sol("sol4").clearSolutionData();
    model.sol("sol5").clearSolutionData();
    model.sol("sol6").clearSolutionData();
    model.sol("sol7").clearSolutionData();
    model.sol("sol8").clearSolutionData();

    model.label("sajben_diffuser.mph");

    return model;
  }

  public static void main(String[] args) {
    Model model = run();
    run2(model);
  }

}
