/*
 * electronic_enclosure_cooling_geom_sequence.java
 */

import com.comsol.model.*;
import com.comsol.model.util.*;

/** Model exported on Apr 30 2026, 10:27 by COMSOL 6.3.0.290. */
public class electronic_enclosure_cooling_geom_sequence {

  public static Model run() {
    Model model = ModelUtil.create("Model");

    model
         .modelPath("D:\\Program Files\\COMSOL\\COMSOL63\\Multiphysics\\applications\\Heat_Transfer_Module\\Power_Electronics_and_Electronic_Cooling");

    model.component().create("comp1", true);

    model.component("comp1").geom().create("geom1", 3);
    model.component("comp1").geom("geom1").geomRep("comsol");

    model.component("comp1").mesh().create("mesh1");
    model.component("comp1").mesh("mesh1").contribute("geom/detail", true);

    model.geom().create("part1", "Part", 3);
    model.geom("part1").geomRep("comsol");
    model.geom("part1").label("\u7535\u5bb9\u5668");
    model.geom("part1").lengthUnit("mm");
    model.geom("part1").inputParam().set("height", "38");
    model.geom("part1").inputParam().set("radius", "12");
    model.geom("part1").localParam().set("fillet", "2/38*height");
    model.geom("part1").create("wp1", "WorkPlane");
    model.geom("part1").feature("wp1").set("unite", true);
    model.geom("part1").feature("wp1").set("quickplane", "yz");
    model.geom("part1").feature("wp1").geom().create("r1", "Rectangle");
    model.geom("part1").feature("wp1").geom().feature("r1").set("size", new String[]{"radius", "height"});
    model.geom("part1").feature("wp1").geom().run("r1");
    model.geom("part1").feature("wp1").geom().create("fil1", "Fillet");
    model.geom("part1").feature("wp1").geom().feature("fil1").selection("pointinsketch").set("r1", 3);
    model.geom("part1").feature("wp1").geom().feature("fil1").set("radius", "fillet");
    model.geom("part1").run("wp1");
    model.geom("part1").feature().create("rev1", "Revolve");
    model.geom("part1").feature("rev1").set("workplane", "wp1");
    model.geom("part1").feature("rev1").selection("input").set("wp1");
    model.geom("part1").feature("rev1").set("angtype", "full");
    model.geom("part1").run("rev1");
    model.geom("part1").create("del1", "Delete");
    model.geom("part1").feature("del1").selection("input").set("rev1", 13);
    model.geom().create("part2", "Part", 3);
    model.geom("part2").geomRep("comsol");
    model.geom("part2").label("\u98ce\u6247");
    model.geom("part2").lengthUnit("mm");
    model.geom("part2").inputParam().set("size", "8[cm]");
    model.geom("part2").localParam().set("fillet", "7");
    model.geom("part2").localParam().set("base_thick", "4");
    model.geom("part2").localParam().set("canal_base_gap", "1");
    model.geom("part2").localParam().set("canal_fillet", "0.5");
    model.geom("part2").localParam().set("canal_thick", "2");
    model.geom("part2").localParam().set("canal_height", "21");
    model.geom("part2").localParam().set("screw_radius", "3");
    model.geom("part2").localParam().set("screw_chamfer", "1");
    model.geom("part2").create("wp1", "WorkPlane");
    model.geom("part2").feature("wp1").set("unite", true);
    model.geom("part2").feature("wp1").geom().create("sq1", "Square");
    model.geom("part2").feature("wp1").geom().feature("sq1").set("size", "size");
    model.geom("part2").feature("wp1").geom().feature("sq1").set("base", "center");
    model.geom("part2").feature("wp1").geom().run("sq1");
    model.geom("part2").feature("wp1").geom().create("fil1", "Fillet");
    model.geom("part2").feature("wp1").geom().feature("fil1").selection("pointinsketch").set("sq1", 1, 2, 3, 4);
    model.geom("part2").feature("wp1").geom().feature("fil1").set("radius", "fillet");
    model.geom("part2").run("wp1");
    model.geom("part2").feature().create("ext1", "Extrude");
    model.geom("part2").feature("ext1").set("workplane", "wp1");
    model.geom("part2").feature("ext1").selection("input").set("wp1");
    model.geom("part2").feature("ext1").setIndex("distance", "base_thick", 0);
    model.geom("part2").run("ext1");
    model.geom("part2").create("wp2", "WorkPlane");
    model.geom("part2").feature("wp2").set("unite", true);
    model.geom("part2").feature("wp2").set("quickplane", "yz");
    model.geom("part2").feature("wp2").geom().create("r1", "Rectangle");
    model.geom("part2").feature("wp2").geom().feature("r1").set("size", new String[]{"canal_thick", "1"});
    model.geom("part2").feature("wp2").geom().feature("r1").setIndex("size", "canal_height", 1);
    model.geom("part2").feature("wp2").geom().feature("r1").set("pos", new String[]{"-size/2+canal_base_gap", "0"});
    model.geom("part2").feature("wp2").geom().feature("r1").setIndex("pos", "base_thick", 1);
    model.geom("part2").feature("wp2").geom().run("r1");
    model.geom("part2").feature("wp2").geom().create("fil1", "Fillet");
    model.geom("part2").feature("wp2").geom().feature("fil1").selection("pointinsketch").set("r1", 3, 4);
    model.geom("part2").feature("wp2").geom().feature("fil1").set("radius", "canal_fillet");
    model.geom("part2").run("wp2");
    model.geom("part2").feature().create("rev1", "Revolve");
    model.geom("part2").feature("rev1").set("workplane", "wp2");
    model.geom("part2").feature("rev1").selection("input").set("wp2");
    model.geom("part2").feature("rev1").set("angtype", "full");
    model.geom("part2").run("rev1");
    model.geom("part2").create("cyl1", "Cylinder");
    model.geom("part2").feature("cyl1").set("r", "size/2-canal_thick");
    model.geom("part2").feature("cyl1").set("h", "canal_height+base_thick-1");
    model.geom("part2").run("cyl1");
    model.geom("part2").create("wp3", "WorkPlane");
    model.geom("part2").feature("wp3").set("unite", true);
    model.geom("part2").feature("wp3").set("quickplane", "yz");
    model.geom("part2").feature("wp3").set("quickx", "size/2-fillet");
    model.geom("part2").feature("wp3").geom().create("r1", "Rectangle");
    model.geom("part2").feature("wp3").geom().feature("r1").set("size", new String[]{"screw_radius", "1"});
    model.geom("part2").feature("wp3").geom().feature("r1").setIndex("size", "canal_height", 1);
    model.geom("part2").feature("wp3").geom().feature("r1").set("pos", new String[]{"size/2-fillet", "0"});
    model.geom("part2").feature("wp3").geom().feature("r1").setIndex("pos", "base_thick", 1);
    model.geom("part2").feature("wp3").geom().run("r1");
    model.geom("part2").feature("wp3").geom().create("cha1", "Chamfer");
    model.geom("part2").feature("wp3").geom().feature("cha1").selection("pointinsketch").set("r1", 3);
    model.geom("part2").feature("wp3").geom().feature("cha1").set("dist", "screw_chamfer");
    model.geom("part2").run("wp3");
    model.geom("part2").feature().create("rev2", "Revolve");
    model.geom("part2").feature("rev2").set("workplane", "wp3");
    model.geom("part2").feature("rev2").selection("input").set("wp3");
    model.geom("part2").feature("rev2").set("angtype", "full");
    model.geom("part2").feature("rev2").set("pos", new String[]{"size/2-fillet", "0"});
    model.geom("part2").feature("rev2").setIndex("pos", "size/2-fillet", 1);
    model.geom("part2").run("rev2");
    model.geom("part2").create("arr1", "Array");
    model.geom("part2").feature("arr1").selection("input").set("rev2");
    model.geom("part2").feature("arr1").set("fullsize", new int[]{2, 2, 1});
    model.geom("part2").feature("arr1").set("displ", new String[]{"-size+2*fillet", "0", "0"});
    model.geom("part2").feature("arr1").setIndex("displ", "-size+2*fillet", 1);
    model.geom("part2").run("arr1");
    model.geom("part2").create("del1", "Delete");
    model.geom("part2").feature("del1").selection("input").set("arr1(1,1,1)", 13);
    model.geom("part2").feature("del1").selection("input").set("arr1(1,2,1)", 13);
    model.geom("part2").feature("del1").selection("input").set("arr1(2,1,1)", 13);
    model.geom("part2").feature("del1").selection("input").set("arr1(2,2,1)", 13);
    model.geom("part2").feature("del1").selection("input").set("rev1", 13);
    model.geom("part2").run("del1");
    model.geom("part2").create("uni1", "Union");
    model.geom("part2").feature("uni1").selection("input").set("cyl1", "del1", "ext1");
    model.geom().create("part3", "Part", 3);
    model.geom("part3").geomRep("comsol");
    model.geom("part3").label("\u7fc5\u7247");
    model.geom("part3").lengthUnit("mm");
    model.geom("part3").localParam().set("width", "75");
    model.geom("part3").localParam().set("height", "60");
    model.geom("part3").localParam().set("fin_width", "10");
    model.geom("part3").localParam().set("fin_height", "80");
    model.geom("part3").localParam().set("fin_spacing", "6");
    model.geom("part3").create("wp1", "WorkPlane");
    model.geom("part3").feature("wp1").set("unite", true);
    model.geom("part3").feature("wp1").set("quickplane", "zx");
    model.geom("part3").feature("wp1").geom().create("r1", "Rectangle");
    model.geom("part3").feature("wp1").geom().feature("r1").set("size", new String[]{"height", "width"});
    model.geom("part3").feature("wp1").geom().feature("r1").set("pos", new String[]{"height/2", "0"});
    model.geom("part3").feature("wp1").geom().feature("r1").set("base", "center");
    model.geom("part3").run("wp1");
    model.geom("part3").create("wp2", "WorkPlane");
    model.geom("part3").feature("wp2").set("unite", true);
    model.geom("part3").feature("wp2").set("quickz", "height");
    model.geom("part3").feature("wp2").geom().create("r1", "Rectangle");
    model.geom("part3").feature("wp2").geom().feature("r1").set("size", new String[]{"fin_height", "fin_width"});
    model.geom("part3").feature("wp2").geom().feature("r1").set("base", "center");
    model.geom("part3").run("wp2");
    model.geom("part3").create("arr1", "Array");
    model.geom("part3").feature("arr1").selection("input").set("wp2");
    model.geom("part3").feature("arr1").set("fullsize", new int[]{1, 1, 6});
    model.geom("part3").feature("arr1").set("displ", new String[]{"0", "0", "-fin_spacing"});
    model.geom("part3").run("arr1");
    model.geom().create("part4", "Part", 3);
    model.geom("part4").geomRep("comsol");
    model.geom("part4").label("\u7535\u611f");
    model.geom("part4").lengthUnit("mm");
    model.geom("part4").inputParam().set("inner_radius", "5");
    model.geom("part4").inputParam().set("outer_radius", "18");
    model.geom("part4").inputParam().set("thick", "10");
    model.geom("part4").localParam().set("chamfer", "1/18*outer_radius");
    model.geom("part4").create("wp1", "WorkPlane");
    model.geom("part4").feature("wp1").set("unite", true);
    model.geom("part4").feature("wp1").set("quickplane", "yz");
    model.geom("part4").feature("wp1").geom().create("r1", "Rectangle");
    model.geom("part4").feature("wp1").geom().feature("r1")
         .set("size", new String[]{"thick", "outer_radius-inner_radius"});
    model.geom("part4").feature("wp1").geom().feature("r1").set("pos", new String[]{"0", "inner_radius"});
    model.geom("part4").feature("wp1").geom().run("r1");
    model.geom("part4").feature("wp1").geom().create("cha1", "Chamfer");
    model.geom("part4").feature("wp1").geom().feature("cha1").selection("pointinsketch").set("r1", 1, 2, 3, 4);
    model.geom("part4").feature("wp1").geom().feature("cha1").set("dist", "chamfer");
    model.geom("part4").run("wp1");
    model.geom("part4").feature().create("rev1", "Revolve");
    model.geom("part4").feature("rev1").set("workplane", "wp1");
    model.geom("part4").feature("rev1").selection("input").set("wp1");
    model.geom("part4").feature("rev1").set("angtype", "full");
    model.geom("part4").feature("rev1").set("axis", new int[]{1, 0});
    model.geom("part4").run("rev1");
    model.geom("part4").create("del1", "Delete");
    model.geom("part4").feature("del1").selection("input").set("rev1", 20);
    model.geom().create("part5", "Part", 3);
    model.geom("part5").geomRep("comsol");
    model.geom("part5").label("\u7535\u6e90\u8fde\u63a5\u5668");
    model.geom("part5").lengthUnit("mm");
    model.geom("part5").localParam().set("base_thick", "4");
    model.geom("part5").create("wp1", "WorkPlane");
    model.geom("part5").feature("wp1").set("unite", true);
    model.geom("part5").feature("wp1").set("quickplane", "yz");
    model.geom("part5").feature("wp1").geom().create("pol1", "Polygon");
    model.geom("part5").feature("wp1").geom().feature("pol1").set("source", "table");
    model.geom("part5").feature("wp1").geom().feature("pol1").setIndex("table", -14, 0, 0);
    model.geom("part5").feature("wp1").geom().feature("pol1").setIndex("table", 10, 0, 1);
    model.geom("part5").feature("wp1").geom().feature("pol1").setIndex("table", 14, 1, 0);
    model.geom("part5").feature("wp1").geom().feature("pol1").setIndex("table", 10, 1, 1);
    model.geom("part5").feature("wp1").geom().feature("pol1").setIndex("table", 24, 2, 0);
    model.geom("part5").feature("wp1").geom().feature("pol1").setIndex("table", 0, 2, 1);
    model.geom("part5").feature("wp1").geom().feature("pol1").setIndex("table", 14, 3, 0);
    model.geom("part5").feature("wp1").geom().feature("pol1").setIndex("table", -10, 3, 1);
    model.geom("part5").feature("wp1").geom().feature("pol1").setIndex("table", -14, 4, 0);
    model.geom("part5").feature("wp1").geom().feature("pol1").setIndex("table", -10, 4, 1);
    model.geom("part5").feature("wp1").geom().feature("pol1").setIndex("table", -24, 5, 0);
    model.geom("part5").feature("wp1").geom().feature("pol1").setIndex("table", 0, 5, 1);
    model.geom("part5").feature("wp1").geom().run("pol1");
    model.geom("part5").feature("wp1").geom().create("fil1", "Fillet");
    model.geom("part5").feature("wp1").geom().feature("fil1").set("radius", 4);
    model.geom("part5").feature("wp1").geom().feature("fil1").selection("pointinsketch").set("pol1", 3, 6);
    model.geom("part5").feature("wp1").geom().run("fil1");
    model.geom("part5").feature("wp1").geom().create("fil2", "Fillet");
    model.geom("part5").feature("wp1").geom().feature("fil2").set("radius", 2);
    model.geom("part5").feature("wp1").geom().feature("fil2").selection("pointinsketch").set("fil1", 3, 4, 5, 6);
    model.geom("part5").run("wp1");
    model.geom("part5").feature().create("ext1", "Extrude");
    model.geom("part5").feature("ext1").set("workplane", "wp1");
    model.geom("part5").feature("ext1").selection("input").set("wp1");
    model.geom("part5").feature("ext1").setIndex("distance", "base_thick", 0);
    model.geom("part5").run("ext1");
    model.geom("part5").create("wp2", "WorkPlane");
    model.geom("part5").feature("wp2").set("unite", true);
    model.geom("part5").feature("wp2").set("quickplane", "yz");
    model.geom("part5").feature("wp2").set("quickx", "base_thick");
    model.geom("part5").feature("wp2").geom().create("r1", "Rectangle");
    model.geom("part5").feature("wp2").geom().feature("r1").set("size", new int[]{24, 16});
    model.geom("part5").feature("wp2").geom().feature("r1").set("base", "center");
    model.geom("part5").feature("wp2").geom().run("r1");
    model.geom("part5").feature("wp2").geom().create("fil1", "Fillet");
    model.geom("part5").feature("wp2").geom().feature("fil1").selection("pointinsketch").set("r1", 1, 2, 3, 4);
    model.geom("part5").feature("wp2").geom().feature("fil1").set("radius", 2);
    model.geom("part5").run("wp2");
    model.geom("part5").feature().create("ext2", "Extrude");
    model.geom("part5").feature("ext2").set("workplane", "wp2");
    model.geom("part5").feature("ext2").selection("input").set("wp2");
    model.geom("part5").feature("ext2").setIndex("distance", 12, 0);
    model.geom("part5").run("ext2");
    model.geom("part5").create("uni1", "Union");
    model.geom("part5").feature("uni1").selection("input").set("ext1", "ext2");
    model.geom().create("part6", "Part", 3);
    model.geom("part6").geomRep("comsol");
    model.geom("part6").label("\u5f00\u5173");
    model.geom("part6").lengthUnit("mm");
    model.geom("part6").inputParam().set("length", "20");
    model.geom("part6").inputParam().set("width", "15");
    model.geom("part6").inputParam().set("depth", "15");
    model.geom("part6").localParam().set("fillet", "length/10");
    model.geom("part6").create("wp1", "WorkPlane");
    model.geom("part6").feature("wp1").set("unite", true);
    model.geom("part6").feature("wp1").geom().create("r1", "Rectangle");
    model.geom("part6").feature("wp1").geom().feature("r1").set("size", new String[]{"depth", "length"});
    model.geom("part6").feature("wp1").geom().feature("r1").set("base", "center");
    model.geom("part6").feature("wp1").geom().feature("r1").set("pos", new String[]{"0", "length/2"});
    model.geom("part6").feature("wp1").geom().run("r1");
    model.geom("part6").feature("wp1").geom().create("fil1", "Fillet");
    model.geom("part6").feature("wp1").geom().feature("fil1").selection("pointinsketch").set("r1", 2, 3);
    model.geom("part6").feature("wp1").geom().feature("fil1").set("radius", "fillet");
    model.geom("part6").run("wp1");
    model.geom("part6").feature().create("ext1", "Extrude");
    model.geom("part6").feature("ext1").set("workplane", "wp1");
    model.geom("part6").feature("ext1").selection("input").set("wp1");
    model.geom("part6").feature("ext1").setIndex("distance", "width", 0);
    model.geom("part6").run("ext1");
    model.geom("part6").create("wp2", "WorkPlane");
    model.geom("part6").feature("wp2").set("unite", true);
    model.geom("part6").feature("wp2").set("quickplane", "zx");
    model.geom("part6").feature("wp2").geom().create("r1", "Rectangle");
    model.geom("part6").feature("wp2").geom().feature("r1").set("size", new String[]{"width", "depth"});
    model.geom("part6").feature("wp2").geom().feature("r1").set("pos", new String[]{"width/2", "0"});
    model.geom("part6").feature("wp2").geom().feature("r1").set("base", "center");
    model.geom("part6").feature("wp2").geom().run("r1");
    model.geom("part6").feature("wp2").geom().create("fil1", "Fillet");
    model.geom("part6").feature("wp2").geom().feature("fil1").selection("pointinsketch").set("r1", 3, 4);
    model.geom("part6").feature("wp2").geom().feature("fil1").set("radius", "fillet");
    model.geom("part6").run("wp2");
    model.geom("part6").feature().create("ext2", "Extrude");
    model.geom("part6").feature("ext2").set("workplane", "wp2");
    model.geom("part6").feature("ext2").selection("input").set("wp2");
    model.geom("part6").feature("ext2").setIndex("distance", "length", 0);
    model.geom("part6").run("ext2");
    model.geom("part6").create("wp3", "WorkPlane");
    model.geom("part6").feature("wp3").set("unite", true);
    model.geom("part6").feature("wp3").set("quickplane", "yz");
    model.geom("part6").feature("wp3").set("quickx", "-depth/2");
    model.geom("part6").feature("wp3").geom().create("r1", "Rectangle");
    model.geom("part6").feature("wp3").geom().feature("r1").set("size", new String[]{"length", "width"});
    model.geom("part6").feature("wp3").geom().feature("r1").set("pos", new String[]{"length/2", "width/2"});
    model.geom("part6").feature("wp3").geom().feature("r1").set("base", "center");
    model.geom("part6").feature("wp3").geom().run("r1");
    model.geom("part6").feature("wp3").geom().create("fil1", "Fillet");
    model.geom("part6").feature("wp3").geom().feature("fil1").selection("pointinsketch").set("r1", 1, 2, 3, 4);
    model.geom("part6").feature("wp3").geom().feature("fil1").set("radius", "fillet");
    model.geom("part6").run("wp3");
    model.geom("part6").feature().create("ext3", "Extrude");
    model.geom("part6").feature("ext3").set("workplane", "wp3");
    model.geom("part6").feature("ext3").selection("input").set("wp3");
    model.geom("part6").feature("ext3").setIndex("distance", "depth", 0);
    model.geom("part6").run("ext3");
    model.geom("part6").create("int1", "Intersection");
    model.geom("part6").feature("int1").selection("input").set("ext1", "ext2", "ext3");
    model.geom("part6").run("int1");
    model.geom().create("part7", "Part", 3);
    model.geom("part7").geomRep("comsol");
    model.geom("part7").label("\u53d8\u538b\u5668");
    model.geom("part7").lengthUnit("mm");
    model.geom("part7").inputParam().set("size", "35");
    model.geom("part7").localParam().set("soft_iron_thick", "size/3.5");
    model.geom("part7").localParam().set("soft_iron_hole_width", "20/35*size");
    model.geom("part7").localParam().set("soft_iron_hole_height", "16/35*size");
    model.geom("part7").localParam().set("coil_radius", "9/35*size");
    model.geom("part7").localParam().set("cap_square_side", "2/35*size");
    model.geom("part7").localParam().set("cap_square_chamfer", "1/35*size");
    model.geom("part7").localParam().set("cap_square_thick", "2/35*size");
    model.geom("part7").create("blk1", "Block");
    model.geom("part7").feature("blk1").set("size", new String[]{"size", "soft_iron_thick", "1"});
    model.geom("part7").feature("blk1").setIndex("size", "size", 2);
    model.geom("part7").feature("blk1").set("base", "center");
    model.geom("part7").run("blk1");
    model.geom("part7").create("blk2", "Block");
    model.geom("part7").feature("blk2").set("size", new String[]{"soft_iron_hole_width", "1", "1"});
    model.geom("part7").feature("blk2").setIndex("size", "soft_iron_thick", 1);
    model.geom("part7").feature("blk2").setIndex("size", "soft_iron_hole_height", 2);
    model.geom("part7").feature("blk2").set("base", "center");
    model.geom("part7").run("blk2");
    model.geom("part7").create("dif1", "Difference");
    model.geom("part7").feature("dif1").selection("input").set("blk1");
    model.geom("part7").feature("dif1").selection("input2").set("blk2");
    model.geom("part7").run("dif1");
    model.geom("part7").create("cyl1", "Cylinder");
    model.geom("part7").feature("cyl1").set("r", "coil_radius");
    model.geom("part7").feature("cyl1").set("h", "soft_iron_hole_height");
    model.geom("part7").feature("cyl1").set("pos", new String[]{"0", "0", "-soft_iron_hole_height/2"});
    model.geom("part7").run("cyl1");
    model.geom("part7").create("wp1", "WorkPlane");
    model.geom("part7").feature("wp1").set("unite", true);
    model.geom("part7").feature("wp1").set("quickz", "soft_iron_hole_height/2");
    model.geom("part7").feature("wp1").geom().create("sq1", "Square");
    model.geom("part7").feature("wp1").geom().feature("sq1").set("size", "soft_iron_hole_width");
    model.geom("part7").feature("wp1").geom().feature("sq1").set("base", "center");
    model.geom("part7").feature("wp1").geom().run("sq1");
    model.geom("part7").feature("wp1").geom().create("sq2", "Square");
    model.geom("part7").feature("wp1").geom().feature("sq2").set("size", "cap_square_side");
    model.geom("part7").feature("wp1").geom().feature("sq2").set("base", "center");
    model.geom("part7").feature("wp1").geom().feature("sq2")
         .set("pos", new String[]{"0", "(soft_iron_hole_height+cap_square_side)/2"});
    model.geom("part7").feature("wp1").geom().run("sq2");
    model.geom("part7").feature("wp1").geom().create("mir1", "Mirror");
    model.geom("part7").feature("wp1").geom().feature("mir1").selection("input").set("sq2");
    model.geom("part7").feature("wp1").geom().feature("mir1").set("axis", new int[]{0, 1});
    model.geom("part7").feature("wp1").geom().feature("mir1").set("keep", true);
    model.geom("part7").feature("wp1").geom().run("mir1");
    model.geom("part7").feature("wp1").geom().create("dif1", "Difference");
    model.geom("part7").feature("wp1").geom().feature("dif1").selection("input").set("sq1");
    model.geom("part7").feature("wp1").geom().feature("dif1").selection("input2").set("mir1", "sq2");
    model.geom("part7").feature("wp1").geom().run("dif1");
    model.geom("part7").feature("wp1").geom().create("cha1", "Chamfer");
    model.geom("part7").feature("wp1").geom().feature("cha1").selection("point").set("dif1", 1, 2, 11, 12);
    model.geom("part7").feature("wp1").geom().feature("cha1").set("dist", "cap_square_chamfer");
    model.geom("part7").run("wp1");
    model.geom("part7").feature().create("ext1", "Extrude");
    model.geom("part7").feature("ext1").set("workplane", "wp1");
    model.geom("part7").feature("ext1").selection("input").set("wp1");
    model.geom("part7").feature("ext1").setIndex("distance", "cap_square_thick", 0);
    model.geom("part7").run("ext1");
    model.geom("part7").create("mir1", "Mirror");
    model.geom("part7").feature("mir1").selection("input").set("ext1");
    model.geom("part7").feature("mir1").set("keep", true);
    model.geom("part7").run("mir1");
    model.geom("part7").create("uni1", "Union");
    model.geom("part7").feature("uni1").selection("input").set("cyl1", "dif1", "ext1", "mir1");
    model.geom().create("part8", "Part", 3);
    model.geom("part8").geomRep("comsol");
    model.geom("part8").label("\u6676\u4f53\u7ba1");
    model.geom("part8").lengthUnit("mm");
    model.geom("part8").localParam().set("box_width", "15");
    model.geom("part8").localParam().set("box_depth", "4");
    model.geom("part8").localParam().set("box_height", "10");
    model.geom("part8").localParam().set("core_width", "4");
    model.geom("part8").localParam().set("core_depth", "1");
    model.geom("part8").localParam().set("core_height", "4");
    model.geom("part8").create("blk1", "Block");
    model.geom("part8").feature("blk1").set("size", new String[]{"box_width", "box_depth", "1"});
    model.geom("part8").feature("blk1").setIndex("size", "box_height", 2);
    model.geom("part8").feature("blk1").set("base", "center");
    model.geom("part8").run("blk1");
    model.geom("part8").create("blk2", "Block");
    model.geom("part8").feature("blk2").set("size", new String[]{"core_width", "1", "1"});
    model.geom("part8").feature("blk2").setIndex("size", "core_depth", 1);
    model.geom("part8").feature("blk2").setIndex("size", "core_height", 2);
    model.geom("part8").feature("blk2").set("base", "center");
    model.geom("part8").feature("blk2").set("pos", new String[]{"0", "(box_depth-core_depth)/2", "0"});
    model.geom("part8").run("blk2");
    model.geom("part8").create("uni1", "Union");
    model.geom("part8").feature("uni1").selection("input").set("blk1", "blk2");
    model.component("comp1").geom("geom1").lengthUnit("cm");
    model.component("comp1").geom("geom1").create("blk1", "Block");
    model.component("comp1").geom("geom1").feature("blk1").label("\u5916\u58f3");
    model.component("comp1").geom("geom1").feature("blk1").set("size", new double[]{14, 15, 8.6});
    model.component("comp1").geom("geom1").run("blk1");
    model.component("comp1").geom("geom1").create("pi1", "PartInstance");
    model.component("comp1").geom("geom1").feature("pi1").set("selkeepnoncontr", false);
    model.component("comp1").geom("geom1").feature("pi1").label("\u98ce\u6247");
    model.component("comp1").geom("geom1").feature("pi1").set("part", "part2");
    model.component("comp1").geom("geom1").feature("pi1").set("displ", new double[]{0, 10, 4.3});
    model.component("comp1").geom("geom1").feature("pi1").set("axistype", "y");
    model.component("comp1").geom("geom1").feature("pi1").set("rot", 90);
    model.component("comp1").geom("geom1").run("pi1");
    model.component("comp1").geom("geom1").create("pi2", "PartInstance");
    model.component("comp1").geom("geom1").feature("pi2").set("selkeepnoncontr", false);
    model.component("comp1").geom("geom1").feature("pi2").label("\u7535\u6e90\u8fde\u63a5\u5668");
    model.component("comp1").geom("geom1").feature("pi2").set("part", "part5");
    model.component("comp1").geom("geom1").feature("pi2").set("displ", new double[]{0, 3.2, 6.1});
    model.component("comp1").geom("geom1").run("pi2");
    model.component("comp1").geom("geom1").create("pi3", "PartInstance");
    model.component("comp1").geom("geom1").feature("pi3").set("selkeepnoncontr", false);
    model.component("comp1").geom("geom1").feature("pi3").label("\u7535\u6e90\u5f00\u5173");
    model.component("comp1").geom("geom1").feature("pi3").set("part", "part6");
    model.component("comp1").geom("geom1").feature("pi3").set("displ", new double[]{0.75, 2.2, 1.6});
    model.component("comp1").geom("geom1").feature().duplicate("pi4", "pi3");
    model.component("comp1").geom("geom1").feature("pi3").set("selcontributetoobj", new String[]{});
    model.component("comp1").geom("geom1").feature("pi3").set("selkeepobj", new String[]{});
    model.component("comp1").geom("geom1").feature("pi3").set("selcontributetopnt", new String[]{});
    model.component("comp1").geom("geom1").feature("pi3").set("selkeeppnt", new String[]{});
    model.component("comp1").geom("geom1").feature("pi3").set("selshowpnt", new String[]{});
    model.component("comp1").geom("geom1").feature("pi3").set("selcontributetoedg", new String[]{});
    model.component("comp1").geom("geom1").feature("pi3").set("selkeepedg", new String[]{});
    model.component("comp1").geom("geom1").feature("pi3").set("selshowedg", new String[]{});
    model.component("comp1").geom("geom1").feature("pi3").set("selcontributetobnd", new String[]{});
    model.component("comp1").geom("geom1").feature("pi3").set("selkeepbnd", new String[]{});
    model.component("comp1").geom("geom1").feature("pi3").set("selshowbnd", new String[]{});
    model.component("comp1").geom("geom1").feature("pi3").set("selcontributetodom", new String[]{});
    model.component("comp1").geom("geom1").feature("pi3").set("selkeepdom", new String[]{});
    model.component("comp1").geom("geom1").feature("pi3").set("selshowdom", new String[]{});
    model.component("comp1").geom("geom1").feature("pi4").label("\u7535\u538b\u5f00\u5173");
    model.component("comp1").geom("geom1").feature("pi4").setEntry("inputexpr", "length", 10);
    model.component("comp1").geom("geom1").feature("pi4").setEntry("inputexpr", "width", 7.5);
    model.component("comp1").geom("geom1").feature("pi4").setEntry("inputexpr", "depth", 7.5);
    model.component("comp1").geom("geom1").feature("pi4").set("displ", new double[]{0.375, 2.6, 3.8});
    model.component("comp1").geom("geom1").run("pi4");
    model.component("comp1").geom("geom1").create("pi5", "PartInstance");
    model.component("comp1").geom("geom1").feature("pi5").set("selkeepnoncontr", false);
    model.component("comp1").geom("geom1").feature("pi5").label("\u53d8\u538b\u5668 1");
    model.component("comp1").geom("geom1").feature("pi5").set("part", "part7");
    model.component("comp1").geom("geom1").feature("pi5").set("displ", new double[]{11.05, 8.5, 1.75});
    model.component("comp1").geom("geom1").feature().duplicate("pi6", "pi5");
    model.component("comp1").geom("geom1").feature("pi5").set("selcontributetoobj", new String[]{});
    model.component("comp1").geom("geom1").feature("pi5").set("selkeepobj", new String[]{});
    model.component("comp1").geom("geom1").feature("pi5").set("selcontributetopnt", new String[]{});
    model.component("comp1").geom("geom1").feature("pi5").set("selkeeppnt", new String[]{});
    model.component("comp1").geom("geom1").feature("pi5").set("selshowpnt", new String[]{});
    model.component("comp1").geom("geom1").feature("pi5").set("selcontributetoedg", new String[]{});
    model.component("comp1").geom("geom1").feature("pi5").set("selkeepedg", new String[]{});
    model.component("comp1").geom("geom1").feature("pi5").set("selshowedg", new String[]{});
    model.component("comp1").geom("geom1").feature("pi5").set("selcontributetobnd", new String[]{});
    model.component("comp1").geom("geom1").feature("pi5").set("selkeepbnd", new String[]{});
    model.component("comp1").geom("geom1").feature("pi5").set("selshowbnd", new String[]{});
    model.component("comp1").geom("geom1").feature("pi5").set("selcontributetodom", new String[]{});
    model.component("comp1").geom("geom1").feature("pi5").set("selkeepdom", new String[]{});

    return model;
  }

  public static Model run2(Model model) {
    model.component("comp1").geom("geom1").feature("pi5").set("selshowdom", new String[]{});
    model.component("comp1").geom("geom1").feature("pi6").setEntry("inputexpr", "size", 17.5);
    model.component("comp1").geom("geom1").feature("pi6").set("displ", new double[]{7.775, 9.25, 0.875});
    model.component("comp1").geom("geom1").run("pi6");
    model.component("comp1").geom("geom1").create("copy1", "Copy");
    model.component("comp1").geom("geom1").feature("copy1").label("\u53d8\u538b\u5668 3");
    model.component("comp1").geom("geom1").feature("copy1").selection("input").set("pi6");
    model.component("comp1").geom("geom1").feature("copy1").set("displx", -2);
    model.component("comp1").geom("geom1").feature("copy1").set("disply", -0.5);
    model.component("comp1").geom("geom1").run("copy1");
    model.component("comp1").geom("geom1").create("pi7", "PartInstance");
    model.component("comp1").geom("geom1").feature("pi7").set("selkeepnoncontr", false);
    model.component("comp1").geom("geom1").feature("pi7").label("\u5927\u578b\u7535\u5bb9\u5668 1");
    model.component("comp1").geom("geom1").feature("pi7").set("displ", new double[]{12, 13.5, 0});
    model.component("comp1").geom("geom1").run("pi7");
    model.component("comp1").geom("geom1").create("copy2", "Copy");
    model.component("comp1").geom("geom1").feature("copy2").label("\u5927\u578b\u7535\u5bb9\u5668 2");
    model.component("comp1").geom("geom1").feature("copy2").selection("input").set("pi7");
    model.component("comp1").geom("geom1").feature("copy2").set("displx", -4);
    model.component("comp1").geom("geom1").feature("copy2").set("disply", -0.25);
    model.component("comp1").geom("geom1").run("copy2");
    model.component("comp1").geom("geom1").create("pi8", "PartInstance");
    model.component("comp1").geom("geom1").feature("pi8").set("selkeepnoncontr", false);
    model.component("comp1").geom("geom1").feature("pi8").label("\u4e2d\u578b\u7535\u5bb9\u5668 1");
    model.component("comp1").geom("geom1").feature("pi8").setEntry("inputexpr", "height", 25);
    model.component("comp1").geom("geom1").feature("pi8").setEntry("inputexpr", "radius", 5);
    model.component("comp1").geom("geom1").feature("pi8").set("displ", new double[]{7, 2.8, 0});
    model.component("comp1").geom("geom1").run("pi8");
    model.component("comp1").geom("geom1").create("copy3", "Copy");
    model.component("comp1").geom("geom1").feature("copy3").label("\u4e2d\u578b\u7535\u5bb9\u5668 2");
    model.component("comp1").geom("geom1").feature("copy3").selection("input").set("pi8");
    model.component("comp1").geom("geom1").feature("copy3").set("displx", 3);
    model.component("comp1").geom("geom1").run("copy3");
    model.component("comp1").geom("geom1").create("pi9", "PartInstance");
    model.component("comp1").geom("geom1").feature("pi9").set("selkeepnoncontr", false);
    model.component("comp1").geom("geom1").feature("pi9").label("\u4e2d\u578b\u7535\u5bb9\u5668 3");
    model.component("comp1").geom("geom1").feature("pi9").setEntry("inputexpr", "height", 15);
    model.component("comp1").geom("geom1").feature("pi9").setEntry("inputexpr", "radius", 5);
    model.component("comp1").geom("geom1").feature("pi9").set("displ", new double[]{11.5, 2.8, 0});
    model.component("comp1").geom("geom1").run("pi9");
    model.component("comp1").geom("geom1").create("copy4", "Copy");
    model.component("comp1").geom("geom1").feature("copy4").label("\u4e2d\u578b\u7535\u5bb9\u5668 4");
    model.component("comp1").geom("geom1").feature("copy4").selection("input").set("pi9");
    model.component("comp1").geom("geom1").run("copy4");
    model.component("comp1").geom("geom1").feature("copy4").set("displx", -0.8);
    model.component("comp1").geom("geom1").feature("copy4").set("disply", -1.1);
    model.component("comp1").geom("geom1").run("copy4");
    model.component("comp1").geom("geom1").create("copy5", "Copy");
    model.component("comp1").geom("geom1").feature("copy5").label("\u4e2d\u578b\u7535\u5bb9\u5668 5");
    model.component("comp1").geom("geom1").feature("copy5").selection("input").set("copy4");
    model.component("comp1").geom("geom1").feature("copy5").set("displx", -2.4);
    model.component("comp1").geom("geom1").run("copy5");
    model.component("comp1").geom("geom1").create("copy6", "Copy");
    model.component("comp1").geom("geom1").feature("copy6").label("\u4e2d\u578b\u7535\u5bb9\u5668 6");
    model.component("comp1").geom("geom1").feature("copy6").selection("input").set("pi8");
    model.component("comp1").geom("geom1").feature("copy6").set("displx", -1.5);
    model.component("comp1").geom("geom1").feature("copy6").set("disply", 2.5);
    model.component("comp1").geom("geom1").run("copy6");
    model.component("comp1").geom("geom1").create("pi10", "PartInstance");
    model.component("comp1").geom("geom1").feature("pi10").set("selkeepnoncontr", false);
    model.component("comp1").geom("geom1").feature("pi10").label("\u5c0f\u578b\u7535\u5bb9\u5668 1");
    model.component("comp1").geom("geom1").feature("pi10").setEntry("inputexpr", "height", 10);
    model.component("comp1").geom("geom1").feature("pi10").setEntry("inputexpr", "radius", 2.5);
    model.component("comp1").geom("geom1").feature("pi10").set("displ", new double[]{6, 0.4, 0});
    model.component("comp1").geom("geom1").run("pi10");
    model.component("comp1").geom("geom1").create("copy7", "Copy");
    model.component("comp1").geom("geom1").feature("copy7").label("\u5c0f\u578b\u7535\u5bb9\u5668 2");
    model.component("comp1").geom("geom1").feature("copy7").selection("input").set("pi10");
    model.component("comp1").geom("geom1").feature("copy7").set("displx", -1);
    model.component("comp1").geom("geom1").run("copy7");
    model.component("comp1").geom("geom1").create("pi11", "PartInstance");
    model.component("comp1").geom("geom1").feature("pi11").set("selkeepnoncontr", false);
    model.component("comp1").geom("geom1").feature("pi11").label("\u5c0f\u578b\u7535\u5bb9\u5668 3");
    model.component("comp1").geom("geom1").feature("pi11").setEntry("inputexpr", "height", 12);
    model.component("comp1").geom("geom1").feature("pi11").setEntry("inputexpr", "radius", 2.5);
    model.component("comp1").geom("geom1").feature("pi11").set("displ", new double[]{10, 10.5, 0});
    model.component("comp1").geom("geom1").run("pi11");
    model.component("comp1").geom("geom1").create("copy8", "Copy");
    model.component("comp1").geom("geom1").feature("copy8").label("\u5c0f\u578b\u7535\u5bb9\u5668 4");
    model.component("comp1").geom("geom1").feature("copy8").selection("input").set("pi11");
    model.component("comp1").geom("geom1").feature("copy8").set("displx", -1.2);
    model.component("comp1").geom("geom1").run("copy8");
    model.component("comp1").geom("geom1").create("pi12", "PartInstance");
    model.component("comp1").geom("geom1").feature("pi12").set("selkeepnoncontr", false);
    model.component("comp1").geom("geom1").feature("pi12").label("\u7535\u611f\u5668 1");
    model.component("comp1").geom("geom1").feature("pi12").set("part", "part4");
    model.component("comp1").geom("geom1").feature("pi12").set("displ", new double[]{7, 3.6, 2});
    model.component("comp1").geom("geom1").run("pi12");
    model.component("comp1").geom("geom1").create("copy9", "Copy");
    model.component("comp1").geom("geom1").feature("copy9").label("\u7535\u611f\u5668 2");
    model.component("comp1").geom("geom1").feature("copy9").selection("input").set("pi12");
    model.component("comp1").geom("geom1").feature("copy9").set("displx", 4);
    model.component("comp1").geom("geom1").run("copy9");
    model.component("comp1").geom("geom1").create("pi13", "PartInstance");
    model.component("comp1").geom("geom1").feature("pi13").set("selkeepnoncontr", false);
    model.component("comp1").geom("geom1").feature("pi13").label("\u7535\u611f\u5668 3");
    model.component("comp1").geom("geom1").feature("pi13").set("part", "part4");
    model.component("comp1").geom("geom1").feature("pi13").setEntry("inputexpr", "inner_radius", 2.5);
    model.component("comp1").geom("geom1").feature("pi13").setEntry("inputexpr", "outer_radius", 9);
    model.component("comp1").geom("geom1").feature("pi13").setEntry("inputexpr", "thick", 5);
    model.component("comp1").geom("geom1").feature("pi13").set("displ", new double[]{8, 7.3, 1});
    model.component("comp1").geom("geom1").run("pi13");
    model.component("comp1").geom("geom1").create("pi14", "PartInstance");
    model.component("comp1").geom("geom1").feature("pi14").set("selkeepnoncontr", false);
    model.component("comp1").geom("geom1").feature("pi14").label("\u6676\u4f53\u7ba1 1");
    model.component("comp1").geom("geom1").feature("pi14").set("part", "part8");
    model.component("comp1").geom("geom1").feature("pi14").set("displ", new double[]{6.75, 6, 1.5});
    model.component("comp1").geom("geom1").run("pi14");
    model.component("comp1").geom("geom1").create("arr1", "Array");
    model.component("comp1").geom("geom1").feature("arr1").label("\u6676\u4f53\u7ba1\u9635\u5217 1");
    model.component("comp1").geom("geom1").feature("arr1").selection("input").set("pi14");
    model.component("comp1").geom("geom1").feature("arr1").set("fullsize", new int[]{3, 1, 1});
    model.component("comp1").geom("geom1").feature("arr1").set("displ", new double[]{2.2, 0, 0});
    model.component("comp1").geom("geom1").run("arr1");
    model.component("comp1").geom("geom1").create("pi15", "PartInstance");
    model.component("comp1").geom("geom1").feature("pi15").set("selkeepnoncontr", false);
    model.component("comp1").geom("geom1").feature("pi15").label("\u6676\u4f53\u7ba1 2");
    model.component("comp1").geom("geom1").feature("pi15").set("part", "part8");
    model.component("comp1").geom("geom1").feature("pi15").set("displ", new double[]{7.95, 11.2, 1.5});
    model.component("comp1").geom("geom1").run("pi15");
    model.component("comp1").geom("geom1").create("arr2", "Array");
    model.component("comp1").geom("geom1").feature("arr2").label("\u6676\u4f53\u7ba1\u9635\u5217 2");
    model.component("comp1").geom("geom1").feature("arr2").selection("input").set("pi15");
    model.component("comp1").geom("geom1").feature("arr2").set("fullsize", new int[]{2, 1, 1});
    model.component("comp1").geom("geom1").feature("arr2").set("displ", new int[]{3, 0, 0});
    model.component("comp1").geom("geom1").run("arr2");
    model.component("comp1").geom("geom1").create("pi16", "PartInstance");
    model.component("comp1").geom("geom1").feature("pi16").set("selkeepnoncontr", false);
    model.component("comp1").geom("geom1").feature("pi16").label("\u7fc5\u7247 1");
    model.component("comp1").geom("geom1").feature("pi16").set("part", "part3");
    model.component("comp1").geom("geom1").feature("pi16").set("displ", new double[]{8.75, 6.2, 0});
    model.component("comp1").geom("geom1").run("pi16");
    model.component("comp1").geom("geom1").create("pi17", "PartInstance");
    model.component("comp1").geom("geom1").feature("pi17").set("selkeepnoncontr", false);
    model.component("comp1").geom("geom1").feature("pi17").label("\u7fc5\u7247 2");
    model.component("comp1").geom("geom1").feature("pi17").set("part", "part3");
    model.component("comp1").geom("geom1").feature("pi17").set("displ", new double[]{8.75, 11.4, 0});
    model.component("comp1").geom("geom1").run("pi17");
    model.component("comp1").geom("geom1").create("wp1", "WorkPlane");
    model.component("comp1").geom("geom1").feature("wp1").set("unite", true);
    model.component("comp1").geom("geom1").feature("wp1").label("\u683c\u6805");
    model.component("comp1").geom("geom1").feature("wp1").set("planetype", "faceparallel");
    model.component("comp1").geom("geom1").feature("wp1").selection("face").set("blk1", 5);
    model.component("comp1").geom("geom1").feature("wp1").geom().create("r1", "Rectangle");
    model.component("comp1").geom("geom1").feature("wp1").geom().feature("r1").set("size", new double[]{12, 4.5});
    model.component("comp1").geom("geom1").feature("wp1").geom().feature("r1").set("pos", new int[]{-6, -1});
    model.component("comp1").geom("geom1").run("wp1");
    model.component("comp1").geom("geom1").create("ic1", "InterpolationCurve");
    model.component("comp1").geom("geom1").feature("ic1").label("\u5bfc\u7ebf\u7ec4\u8def\u5f84");
    model.component("comp1").geom("geom1").feature("ic1").setIndex("table", 9.5, 0, 0);
    model.component("comp1").geom("geom1").feature("ic1").setIndex("table", 0.8, 0, 1);
    model.component("comp1").geom("geom1").feature("ic1").setIndex("table", -0.5, 0, 2);
    model.component("comp1").geom("geom1").feature("ic1").setIndex("table", 9.5, 1, 0);
    model.component("comp1").geom("geom1").feature("ic1").setIndex("table", 0.8, 1, 1);
    model.component("comp1").geom("geom1").feature("ic1").setIndex("table", 1.5, 1, 2);
    model.component("comp1").geom("geom1").feature("ic1").setIndex("table", 13, 2, 0);
    model.component("comp1").geom("geom1").feature("ic1").setIndex("table", 2.5, 2, 1);
    model.component("comp1").geom("geom1").feature("ic1").setIndex("table", 7, 2, 2);
    model.component("comp1").geom("geom1").feature("ic1").setIndex("table", 14, 3, 0);
    model.component("comp1").geom("geom1").feature("ic1").setIndex("table", 2.5, 3, 1);
    model.component("comp1").geom("geom1").feature("ic1").setIndex("table", 7, 3, 2);
    model.component("comp1").geom("geom1").feature("ic1").setIndex("table", 16, 4, 0);
    model.component("comp1").geom("geom1").feature("ic1").setIndex("table", 2.5, 4, 1);
    model.component("comp1").geom("geom1").feature("ic1").setIndex("table", 7, 4, 2);
    model.component("comp1").geom("geom1").feature("ic1").set("startcond", "zerocurv");
    model.component("comp1").geom("geom1").feature("ic1").set("endcond", "zerocurv");
    model.component("comp1").geom("geom1").run("ic1");
    model.component("comp1").geom("geom1").create("wp2", "WorkPlane");
    model.component("comp1").geom("geom1").feature("wp2").set("unite", true);
    model.component("comp1").geom("geom1").feature("wp2").label("\u5bfc\u7ebf\u7ec4\u622a\u9762");
    model.component("comp1").geom("geom1").feature("wp2").set("planetype", "faceparallel");
    model.component("comp1").geom("geom1").feature("wp2").selection("face").set("blk1", 1);
    model.component("comp1").geom("geom1").feature("wp2").set("offset", -0.5);
    model.component("comp1").geom("geom1").feature("wp2").set("reverse", true);
    model.component("comp1").geom("geom1").feature("wp2").set("origin", "boxcorner");
    model.component("comp1").geom("geom1").feature("wp2").geom().create("c1", "Circle");
    model.component("comp1").geom("geom1").feature("wp2").geom().feature("c1").set("r", 0.6);
    model.component("comp1").geom("geom1").feature("wp2").geom().feature("c1").set("pos", new double[]{9.5, 0.8});
    model.component("comp1").geom("geom1").run("wp2");
    model.component("comp1").geom("geom1").create("swe1", "Sweep");
    model.component("comp1").geom("geom1").feature("swe1").set("includefinal", false);
    model.component("comp1").geom("geom1").feature("swe1").set("crossfaces", true);
    model.component("comp1").geom("geom1").feature("swe1").set("manualdir", false);
    model.component("comp1").geom("geom1").feature("swe1").label("\u5bfc\u7ebf\u7ec4\u626b\u63cf");
    model.component("comp1").geom("geom1").feature("swe1").selection("enttosweep").set("wp2", 1);
    model.component("comp1").geom("geom1").feature("swe1").selection("edge").set("ic1", 1);
    model.component("comp1").geom("geom1").feature("swe1").set("keep", false);
    model.component("comp1").geom("geom1").run("swe1");
    model.component("comp1").geom("geom1").create("wp3", "WorkPlane");
    model.component("comp1").geom("geom1").feature("wp3").set("unite", true);
    model.component("comp1").geom("geom1").feature("wp3").label("\u5bfc\u7ebf\u7ec4\u8fde\u63a5\u5668\u7fc5\u7247");
    model.component("comp1").geom("geom1").feature("wp3").set("quickplane", "zx");
    model.component("comp1").geom("geom1").feature("wp3").set("quicky", 2.5);
    model.component("comp1").geom("geom1").feature("wp3").geom().create("r1", "Rectangle");
    model.component("comp1").geom("geom1").feature("wp3").geom().feature("r1").set("size", new double[]{1.25, 1.5});
    model.component("comp1").geom("geom1").feature("wp3").geom().feature("r1").set("pos", new double[]{5.75, 12.5});
    model.component("comp1").geom("geom1").feature("wp3").geom().run("r1");
    model.component("comp1").geom("geom1").feature("wp3").geom().create("fil1", "Fillet");
    model.component("comp1").geom("geom1").feature("wp3").geom().feature("fil1").selection("pointinsketch")
         .set("r1", 1);
    model.component("comp1").geom("geom1").feature("wp3").geom().feature("fil1").set("radius", 0.3);
    model.component("comp1").geom("geom1").run("wp3");
    model.component("comp1").geom("geom1").feature().create("rev1", "Revolve");
    model.component("comp1").geom("geom1").feature("rev1").set("workplane", "wp3");
    model.component("comp1").geom("geom1").feature("rev1").selection("input").set("wp3");
    model.component("comp1").geom("geom1").feature("rev1").set("angtype", "full");
    model.component("comp1").geom("geom1").feature("rev1").label("\u5bfc\u7ebf\u7ec4\u8fde\u63a5\u5668\u7ed5\u7ec4");
    model.component("comp1").geom("geom1").feature("rev1").set("pos", new double[]{7, 2.5});
    model.component("comp1").geom("geom1").run("rev1");
    model.component("comp1").geom("geom1").create("ic2", "InterpolationCurve");
    model.component("comp1").geom("geom1").feature("ic2").label("\u7535\u6e90\u5f00\u5173\u5bfc\u7ebf\u8def\u5f84");
    model.component("comp1").geom("geom1").feature("ic2").setIndex("table", 10, 0, 0);
    model.component("comp1").geom("geom1").feature("ic2").setIndex("table", 14.45, 0, 1);
    model.component("comp1").geom("geom1").feature("ic2").setIndex("table", 0, 0, 2);
    model.component("comp1").geom("geom1").feature("ic2").setIndex("table", 4, 1, 0);
    model.component("comp1").geom("geom1").feature("ic2").setIndex("table", 10, 1, 1);
    model.component("comp1").geom("geom1").feature("ic2").setIndex("table", 4, 1, 2);
    model.component("comp1").geom("geom1").feature("ic2").setIndex("table", 3, 2, 0);
    model.component("comp1").geom("geom1").feature("ic2").setIndex("table", 4, 2, 1);
    model.component("comp1").geom("geom1").feature("ic2").setIndex("table", 3, 2, 2);
    model.component("comp1").geom("geom1").feature("ic2").setIndex("table", 1, 3, 0);
    model.component("comp1").geom("geom1").feature("ic2").setIndex("table", 3, 3, 1);
    model.component("comp1").geom("geom1").feature("ic2").setIndex("table", 2, 3, 2);
    model.component("comp1").geom("geom1").feature("ic2").setIndex("table", 0.2, 4, 0);
    model.component("comp1").geom("geom1").feature("ic2").setIndex("table", 3, 4, 1);
    model.component("comp1").geom("geom1").feature("ic2").setIndex("table", 2, 4, 2);
    model.component("comp1").geom("geom1").feature("ic2").set("startcond", "zerocurv");
    model.component("comp1").geom("geom1").feature("ic2").set("endcond", "zerocurv");
    model.component("comp1").geom("geom1").run("ic2");
    model.component("comp1").geom("geom1").create("wp4", "WorkPlane");
    model.component("comp1").geom("geom1").feature("wp4").set("unite", true);
    model.component("comp1").geom("geom1").feature("wp4").label("\u7535\u6e90\u5f00\u5173\u5bfc\u7ebf\u622a\u9762");
    model.component("comp1").geom("geom1").feature("wp4").geom().create("c1", "Circle");
    model.component("comp1").geom("geom1").feature("wp4").geom().feature("c1").set("r", "1.2[mm]");
    model.component("comp1").geom("geom1").feature("wp4").geom().feature("c1").set("pos", new double[]{10, 14.45});
    model.component("comp1").geom("geom1").run("wp4");
    model.component("comp1").geom("geom1").create("swe2", "Sweep");
    model.component("comp1").geom("geom1").feature("swe2").set("includefinal", false);
    model.component("comp1").geom("geom1").feature("swe2").set("crossfaces", true);
    model.component("comp1").geom("geom1").feature("swe2").set("manualdir", false);
    model.component("comp1").geom("geom1").feature("swe2").selection("enttosweep").set("wp4", 1);
    model.component("comp1").geom("geom1").feature("swe2").selection("edge").set("ic2", 1);
    model.component("comp1").geom("geom1").feature("swe2").set("keep", false);
    model.component("comp1").geom("geom1").feature("swe2").set("spineperpstart", true);
    model.component("comp1").geom("geom1").feature("swe2").set("adjustlen", 2);
    model.component("comp1").geom("geom1").run("fin");

    model.title(null);

    model.description("");

    model.label("electronic_enclosure_cooling_geom_sequence.mph");

    return model;
  }

  public static void main(String[] args) {
    Model model = run();
    run2(model);
  }

}
