/*
 * anode_film_resistance_geom_sequence.java
 */

import com.comsol.model.*;
import com.comsol.model.util.*;

/** Model exported on Apr 30 2026, 09:41 by COMSOL 6.3.0.290. */
public class anode_film_resistance_geom_sequence {

  public static Model run() {
    Model model = ModelUtil.create("Model");

    model
         .modelPath("D:\\Program Files\\COMSOL\\COMSOL63\\Multiphysics\\applications\\Corrosion_Module\\Cathodic_Protection");

    model.component().create("comp1", true);

    model.component("comp1").geom().create("geom1", 3);
    model.component("comp1").geom("geom1").geomRep("comsol");

    model.component("comp1").mesh().create("mesh1");
    model.component("comp1").mesh("mesh1").contribute("geom/detail", true);

    model.component("comp1").geom("geom1").create("cyl1", "Cylinder");
    model.component("comp1").geom("geom1").feature("cyl1").set("r", "3[m]");
    model.component("comp1").geom("geom1").feature("cyl1").set("h", "0.5[m]");
    model.component("comp1").geom("geom1").feature("cyl1").set("pos", new String[]{"-19[m]", "0", "0"});
    model.component("comp1").geom("geom1").selection().create("csel1", "CumulativeSelection");
    model.component("comp1").geom("geom1").selection("csel1").label("\u94a2");
    model.component("comp1").geom("geom1").feature("cyl1").set("contributeto", "csel1");
    model.component("comp1").geom("geom1").run("cyl1");
    model.component("comp1").geom("geom1").create("cyl2", "Cylinder");
    model.component("comp1").geom("geom1").feature("cyl2").set("r", "1.5[m]");
    model.component("comp1").geom("geom1").feature("cyl2").set("h", "20[m]");
    model.component("comp1").geom("geom1").feature("cyl2").set("pos", new String[]{"-19[m]", "0", "0.5[m]"});
    model.component("comp1").geom("geom1").feature("cyl2").set("contributeto", "csel1");
    model.component("comp1").geom("geom1").run("cyl2");
    model.component("comp1").geom("geom1").create("cone1", "Cone");
    model.component("comp1").geom("geom1").feature("cone1").set("specifytop", "radius");
    model.component("comp1").geom("geom1").feature("cone1").set("r", "1.5[m]");
    model.component("comp1").geom("geom1").feature("cone1").set("h", "1.6[m]");
    model.component("comp1").geom("geom1").feature("cone1").set("specifytop", "angle");
    model.component("comp1").geom("geom1").feature("cone1").set("ang", "-30[deg]");
    model.component("comp1").geom("geom1").feature("cone1").set("pos", new String[]{"-19[m]", "0", "20.5[m]"});
    model.component("comp1").geom("geom1").feature("cone1").set("contributeto", "csel1");
    model.component("comp1").geom("geom1").run("cone1");
    model.component("comp1").geom("geom1").create("cyl3", "Cylinder");
    model.component("comp1").geom("geom1").feature("cyl3").set("r", "0.5[m]");
    model.component("comp1").geom("geom1").feature("cyl3").set("h", "27[m]");
    model.component("comp1").geom("geom1").feature("cyl3").set("pos", new String[]{"-19[m]", "0", "4.2[m]"});
    model.component("comp1").geom("geom1").feature("cyl3").set("axistype", "cartesian");
    model.component("comp1").geom("geom1").feature("cyl3").set("ax3", new int[]{1, -1, 0});
    model.component("comp1").geom("geom1").feature("cyl3").set("contributeto", "csel1");
    model.component("comp1").geom("geom1").run("cyl3");
    model.component("comp1").geom("geom1").create("cyl4", "Cylinder");
    model.component("comp1").geom("geom1").feature("cyl4").set("r", "0.3[m]");
    model.component("comp1").geom("geom1").feature("cyl4").set("h", "19[m]");
    model.component("comp1").geom("geom1").feature("cyl4").set("pos", new String[]{"-9.5[m]", "-9.75[m]", "0"});
    model.component("comp1").geom("geom1").feature("cyl4").setIndex("pos", "4.2[m]", 2);
    model.component("comp1").geom("geom1").feature("cyl4").set("axistype", "x");
    model.component("comp1").geom("geom1").feature("cyl4").set("contributeto", "csel1");
    model.component("comp1").geom("geom1").run("cyl4");
    model.component("comp1").geom("geom1").create("cyl5", "Cylinder");
    model.component("comp1").geom("geom1").feature("cyl5").set("r", "0.65[m]");
    model.component("comp1").geom("geom1").feature("cyl5").set("h", "28[m]");
    model.component("comp1").geom("geom1").feature("cyl5").set("pos", new String[]{"-20[m]", "0", "1[m]"});
    model.component("comp1").geom("geom1").feature("cyl5").set("selresult", true);
    model.component("comp1").geom("geom1").feature("cyl5").set("selresultshow", false);
    model.component("comp1").geom("geom1").run("cyl5");
    model.component("comp1").geom("geom1").create("rot1", "Rotate");
    model.component("comp1").geom("geom1").feature("rot1").selection("input").named("cyl5");
    model.component("comp1").geom("geom1").feature("rot1").set("specify", "eulerang");
    model.component("comp1").geom("geom1").feature("rot1").set("eulerang", new String[]{"60[deg]", "30[deg]", "0"});
    model.component("comp1").geom("geom1").feature("rot1").set("pos", new String[]{"-20[m]", "0", "0"});
    model.component("comp1").geom("geom1").feature("rot1").set("contributeto", "csel1");
    model.component("comp1").geom("geom1").run("rot1");
    model.component("comp1").geom("geom1").create("mir1", "Mirror");
    model.component("comp1").geom("geom1").feature("mir1").selection("input").named("cyl5");
    model.component("comp1").geom("geom1").feature("mir1").set("keep", true);
    model.component("comp1").geom("geom1").feature("mir1").set("axis", new int[]{0, 1, 0});
    model.component("comp1").geom("geom1").feature("mir1").set("contributeto", "csel1");
    model.component("comp1").geom("geom1").run("mir1");
    model.component("comp1").geom("geom1").create("cyl6", "Cylinder");
    model.component("comp1").geom("geom1").feature("cyl6").set("r", "0.3[m]");
    model.component("comp1").geom("geom1").feature("cyl6").set("h", "10[m]");
    model.component("comp1").geom("geom1").feature("cyl6").set("pos", new String[]{"-20[m]", "0", "10[m]"});
    model.component("comp1").geom("geom1").feature("cyl6").set("selresult", true);
    model.component("comp1").geom("geom1").feature("cyl6").set("selresultshow", false);
    model.component("comp1").geom("geom1").run("cyl6");
    model.component("comp1").geom("geom1").create("rot2", "Rotate");
    model.component("comp1").geom("geom1").feature("rot2").selection("input").named("cyl6");
    model.component("comp1").geom("geom1").feature("rot2").set("specify", "eulerang");
    model.component("comp1").geom("geom1").feature("rot2").set("eulerang", new String[]{"60[deg]", "60[deg]", "0"});
    model.component("comp1").geom("geom1").feature("rot2").set("pos", new String[]{"-20[m]", "0", "10[m]"});
    model.component("comp1").geom("geom1").feature("rot2").set("contributeto", "csel1");
    model.component("comp1").geom("geom1").run("rot2");
    model.component("comp1").geom("geom1").create("mir2", "Mirror");
    model.component("comp1").geom("geom1").feature("mir2").selection("input").named("cyl6");
    model.component("comp1").geom("geom1").feature("mir2").set("keep", true);
    model.component("comp1").geom("geom1").feature("mir2").set("axis", new int[]{0, 1, 0});
    model.component("comp1").geom("geom1").feature("mir2").set("contributeto", "csel1");
    model.component("comp1").geom("geom1").run("mir2");
    model.component("comp1").geom("geom1").create("cyl7", "Cylinder");
    model.component("comp1").geom("geom1").feature("cyl7").set("r", "0.3[m]");
    model.component("comp1").geom("geom1").feature("cyl7").set("h", "10[m]");
    model.component("comp1").geom("geom1").feature("cyl7").set("pos", new String[]{"-12[m]", "-5[m]", "0"});
    model.component("comp1").geom("geom1").feature("cyl7").setIndex("pos", "16[m]", 2);
    model.component("comp1").geom("geom1").feature("cyl7").set("axistype", "y");
    model.component("comp1").geom("geom1").feature("cyl7").set("selresult", true);
    model.component("comp1").geom("geom1").feature("cyl7").set("selresultshow", false);
    model.component("comp1").geom("geom1").run("cyl7");
    model.component("comp1").geom("geom1").create("rot3", "Rotate");
    model.component("comp1").geom("geom1").feature("rot3").selection("input").named("cyl7");
    model.component("comp1").geom("geom1").feature("rot3").set("rot", "0[deg] 225[deg]");
    model.component("comp1").geom("geom1").feature("rot3").set("pos", new String[]{"-12[m]", "-5[m]", "0"});
    model.component("comp1").geom("geom1").feature("rot3").setIndex("pos", "16[m]", 2);
    model.component("comp1").geom("geom1").feature("rot3").set("contributeto", "csel1");
    model.component("comp1").geom("geom1").run("rot3");
    model.component("comp1").geom("geom1").create("cyl8", "Cylinder");
    model.component("comp1").geom("geom1").feature("cyl8").set("r", "0.3[m]");
    model.component("comp1").geom("geom1").feature("cyl8").set("h", "16[m]");
    model.component("comp1").geom("geom1").feature("cyl8").set("pos", new String[]{"-9[m]", "-8[m]", "16[m]"});
    model.component("comp1").geom("geom1").feature("cyl8").set("axistype", "y");
    model.component("comp1").geom("geom1").feature("cyl8").set("contributeto", "csel1");
    model.component("comp1").geom("geom1").run("cyl8");
    model.component("comp1").geom("geom1").create("cyl9", "Cylinder");
    model.component("comp1").geom("geom1").feature("cyl9").set("r", "0.3[m]");
    model.component("comp1").geom("geom1").feature("cyl9").set("h", "12.5[m]");
    model.component("comp1").geom("geom1").feature("cyl9").set("pos", new String[]{"-9.7[m]", "-9.5[m]", "0"});
    model.component("comp1").geom("geom1").feature("cyl9").setIndex("pos", "4.2[m]", 2);
    model.component("comp1").geom("geom1").feature("cyl9").set("selresult", true);
    model.component("comp1").geom("geom1").feature("cyl9").set("selresultshow", false);
    model.component("comp1").geom("geom1").run("cyl9");
    model.component("comp1").geom("geom1").create("rot4", "Rotate");
    model.component("comp1").geom("geom1").feature("rot4").selection("input").named("cyl9");
    model.component("comp1").geom("geom1").feature("rot4").set("specify", "eulerang");
    model.component("comp1").geom("geom1").feature("rot4").set("eulerang", new String[]{"30[deg]", "-30[deg]", "0"});
    model.component("comp1").geom("geom1").feature("rot4").set("pos", new String[]{"-9.7[m]", "-9.5[m]", "0"});
    model.component("comp1").geom("geom1").feature("rot4").setIndex("pos", "4.2[m]", 2);
    model.component("comp1").geom("geom1").feature("rot4").set("contributeto", "csel1");
    model.component("comp1").geom("geom1").run("rot4");
    model.component("comp1").geom("geom1").create("mir3", "Mirror");
    model.component("comp1").geom("geom1").feature("mir3").selection("input").named("cyl9");
    model.component("comp1").geom("geom1").feature("mir3").set("keep", true);
    model.component("comp1").geom("geom1").feature("mir3").set("axis", new int[]{-1, 1, 0});
    model.component("comp1").geom("geom1").feature("mir3").set("contributeto", "csel1");
    model.component("comp1").geom("geom1").run("mir3");
    model.component("comp1").geom("geom1").create("uni1", "Union");
    model.component("comp1").geom("geom1").feature("uni1").selection("input").named("csel1");
    model.component("comp1").geom("geom1").feature("uni1").set("intbnd", false);
    model.component("comp1").geom("geom1").run("uni1");
    model.component("comp1").geom("geom1").create("rot5", "Rotate");
    model.component("comp1").geom("geom1").feature("rot5").selection("input").named("csel1");
    model.component("comp1").geom("geom1").feature("rot5").set("rot", "range(90[deg],90[deg],360[deg])");
    model.component("comp1").geom("geom1").run("rot5");
    model.component("comp1").geom("geom1").create("uni2", "Union");
    model.component("comp1").geom("geom1").feature("uni2").selection("input").named("csel1");
    model.component("comp1").geom("geom1").feature("uni2").set("intbnd", false);
    model.component("comp1").geom("geom1").run("uni2");
    model.component("comp1").geom("geom1").create("cyl10", "Cylinder");
    model.component("comp1").geom("geom1").feature("cyl10").set("r", "0.8[m]");
    model.component("comp1").geom("geom1").feature("cyl10").set("h", "70[m]");
    model.component("comp1").geom("geom1").feature("cyl10").set("pos", new String[]{"-7.3[m]", "7.3[m]", "0"});
    model.component("comp1").geom("geom1").feature("cyl10").setIndex("pos", "22[m]", 2);
    model.component("comp1").geom("geom1").selection().create("csel2", "CumulativeSelection");
    model.component("comp1").geom("geom1").selection("csel2").label("\u9876\u90e8\u7ed3\u6784");
    model.component("comp1").geom("geom1").feature("cyl10").set("contributeto", "csel2");
    model.component("comp1").geom("geom1").run("cyl10");
    model.component("comp1").geom("geom1").create("cyl11", "Cylinder");
    model.component("comp1").geom("geom1").feature("cyl11").set("r", "0.5[m]");
    model.component("comp1").geom("geom1").feature("cyl11").set("h", "14[m]");
    model.component("comp1").geom("geom1").feature("cyl11").set("pos", new String[]{"-7.3[m]", "-7[m]", "0"});
    model.component("comp1").geom("geom1").feature("cyl11").setIndex("pos", "28[m]", 2);
    model.component("comp1").geom("geom1").feature("cyl11").set("axistype", "y");
    model.component("comp1").geom("geom1").feature("cyl11").set("selresult", true);
    model.component("comp1").geom("geom1").feature("cyl11").set("selresultshow", false);
    model.component("comp1").geom("geom1").run("cyl11");
    model.component("comp1").geom("geom1").create("arr1", "Array");
    model.component("comp1").geom("geom1").feature("arr1").selection("input").named("cyl11");
    model.component("comp1").geom("geom1").feature("arr1").set("fullsize", new int[]{1, 1, 5});
    model.component("comp1").geom("geom1").feature("arr1").set("displ", new String[]{"0", "0", "15[m]"});
    model.component("comp1").geom("geom1").feature("arr1").set("contributeto", "csel2");
    model.component("comp1").geom("geom1").run("arr1");
    model.component("comp1").geom("geom1").create("cyl12", "Cylinder");
    model.component("comp1").geom("geom1").feature("cyl12").set("r", "0.3[m]");
    model.component("comp1").geom("geom1").feature("cyl12").set("h", "9[m]");
    model.component("comp1").geom("geom1").feature("cyl12").set("pos", new String[]{"-7.3[m]", "1[m]", "0"});
    model.component("comp1").geom("geom1").feature("cyl12").setIndex("pos", "28[m]", 2);
    model.component("comp1").geom("geom1").feature("cyl12").set("axistype", "cartesian");
    model.component("comp1").geom("geom1").feature("cyl12").set("ax3", new int[]{1, 1, 0});
    model.component("comp1").geom("geom1").feature("cyl12").set("selresult", true);
    model.component("comp1").geom("geom1").feature("cyl12").set("selresultshow", false);
    model.component("comp1").geom("geom1").run("cyl12");
    model.component("comp1").geom("geom1").create("mov1", "Move");
    model.component("comp1").geom("geom1").feature("mov1").selection("input").named("cyl12");
    model.component("comp1").geom("geom1").feature("mov1").set("displz", "0[m] 30[m]");
    model.component("comp1").geom("geom1").feature("mov1").set("contributeto", "csel2");
    model.component("comp1").geom("geom1").run("mov1");
    model.component("comp1").geom("geom1").create("cyl13", "Cylinder");
    model.component("comp1").geom("geom1").feature("cyl13").set("r", "0.3[m]");
    model.component("comp1").geom("geom1").feature("cyl13").set("h", "19[m]");
    model.component("comp1").geom("geom1").feature("cyl13").set("pos", new String[]{"-7.3[m]", "-7.3[m]", "0"});
    model.component("comp1").geom("geom1").feature("cyl13").setIndex("pos", "29[m]", 2);
    model.component("comp1").geom("geom1").feature("cyl13").set("selresult", true);
    model.component("comp1").geom("geom1").feature("cyl13").set("selresultshow", false);
    model.component("comp1").geom("geom1").run("cyl13");
    model.component("comp1").geom("geom1").create("rot6", "Rotate");
    model.component("comp1").geom("geom1").feature("rot6").selection("input").named("cyl13");
    model.component("comp1").geom("geom1").feature("rot6").set("axistype", "x");
    model.component("comp1").geom("geom1").feature("rot6").set("rot", "-48[deg]");
    model.component("comp1").geom("geom1").feature("rot6").set("pos", new String[]{"0", "-7.3[m]", "29[m]"});
    model.component("comp1").geom("geom1").run("rot6");
    model.component("comp1").geom("geom1").create("mir4", "Mirror");
    model.component("comp1").geom("geom1").feature("mir4").selection("input").named("cyl13");
    model.component("comp1").geom("geom1").feature("mir4").set("keep", true);
    model.component("comp1").geom("geom1").feature("mir4").set("axis", new int[]{0, 1, 0});
    model.component("comp1").geom("geom1").run("mir4");
    model.component("comp1").geom("geom1").create("mov2", "Move");
    model.component("comp1").geom("geom1").feature("mov2").selection("input").named("cyl13");
    model.component("comp1").geom("geom1").feature("mov2").set("displz", "0[m] 45[m]");
    model.component("comp1").geom("geom1").feature("mov2").set("contributeto", "csel2");
    model.component("comp1").geom("geom1").run("mov2");
    model.component("comp1").geom("geom1").create("uni3", "Union");
    model.component("comp1").geom("geom1").feature("uni3").selection("input").named("csel2");
    model.component("comp1").geom("geom1").feature("uni3").set("intbnd", false);
    model.component("comp1").geom("geom1").run("uni3");
    model.component("comp1").geom("geom1").create("rot7", "Rotate");
    model.component("comp1").geom("geom1").feature("rot7").selection("input").named("csel2");
    model.component("comp1").geom("geom1").feature("rot7").set("rot", "range(90[deg],90[deg],360[eg])");
    model.component("comp1").geom("geom1").run("rot7");
    model.component("comp1").geom("geom1").create("uni4", "Union");
    model.component("comp1").geom("geom1").feature("uni4").selection("input").named("csel2");
    model.component("comp1").geom("geom1").feature("uni4").set("intbnd", false);
    model.component("comp1").geom("geom1").run("uni4");
    model.component("comp1").geom("geom1").create("cyl14", "Cylinder");
    model.component("comp1").geom("geom1").feature("cyl14").set("r", "0.3[m]");
    model.component("comp1").geom("geom1").feature("cyl14").set("h", "19[m]");
    model.component("comp1").geom("geom1").feature("cyl14").set("pos", new String[]{"-7.3[m]", "0", "41[m]"});
    model.component("comp1").geom("geom1").feature("cyl14").set("selresult", true);
    model.component("comp1").geom("geom1").feature("cyl14").set("selresultshow", false);
    model.component("comp1").geom("geom1").feature("cyl14").set("contributeto", "csel2");
    model.component("comp1").geom("geom1").run("cyl14");
    model.component("comp1").geom("geom1").create("rot8", "Rotate");
    model.component("comp1").geom("geom1").feature("rot8").selection("input").named("cyl14");
    model.component("comp1").geom("geom1").feature("rot8").set("axistype", "x");
    model.component("comp1").geom("geom1").feature("rot8").set("rot", "48[deg]");
    model.component("comp1").geom("geom1").feature("rot8").set("pos", new String[]{"0", "0", "50.5[m]"});
    model.component("comp1").geom("geom1").run("rot8");
    model.component("comp1").geom("geom1").create("mir5", "Mirror");
    model.component("comp1").geom("geom1").feature("mir5").selection("input").named("cyl14");
    model.component("comp1").geom("geom1").feature("mir5").set("keep", true);
    model.component("comp1").geom("geom1").feature("mir5").set("pos", new String[]{"0", "0", "58[m]"});
    model.component("comp1").geom("geom1").run("mir5");
    model.component("comp1").geom("geom1").create("mir6", "Mirror");
    model.component("comp1").geom("geom1").feature("mir6").selection("input").named("cyl14");
    model.component("comp1").geom("geom1").feature("mir6").set("keep", true);
    model.component("comp1").geom("geom1").feature("mir6").set("pos", new String[]{"1[m]", "1[m]", "0"});
    model.component("comp1").geom("geom1").feature("mir6").set("axis", new int[]{1, -1, 0});
    model.component("comp1").geom("geom1").run("mir6");
    model.component("comp1").geom("geom1").create("rot9", "Rotate");
    model.component("comp1").geom("geom1").feature("rot9").selection("input").named("cyl14");
    model.component("comp1").geom("geom1").feature("rot9").set("rot", "0[deg] 180[deg]");
    model.component("comp1").geom("geom1").run("rot9");
    model.component("comp1").geom("geom1").create("uni5", "Union");
    model.component("comp1").geom("geom1").feature("uni5").selection("input").named("csel2");
    model.component("comp1").geom("geom1").feature("uni5").set("intbnd", false);
    model.component("comp1").geom("geom1").feature("uni5").set("contributeto", "csel1");
    model.component("comp1").geom("geom1").run("uni5");
    model.component("comp1").geom("geom1").create("uni6", "Union");
    model.component("comp1").geom("geom1").feature("uni6").selection("input").named("csel1");
    model.component("comp1").geom("geom1").feature("uni6").set("intbnd", false);
    model.component("comp1").geom("geom1").run("uni6");
    model.component("comp1").geom("geom1").create("cyl15", "Cylinder");
    model.component("comp1").geom("geom1").feature("cyl15").set("r", "0.8[m]");
    model.component("comp1").geom("geom1").feature("cyl15").set("h", "4[m]");
    model.component("comp1").geom("geom1").feature("cyl15").set("pos", new String[]{"-14[m]", "14[m]", "0"});
    model.component("comp1").geom("geom1").feature("cyl15").setIndex("pos", "4[m]", 2);
    model.component("comp1").geom("geom1").feature("cyl15").set("selresult", true);
    model.component("comp1").geom("geom1").feature("cyl15").set("selresultshow", false);
    model.component("comp1").geom("geom1").selection().create("csel3", "CumulativeSelection");
    model.component("comp1").geom("geom1").selection("csel3").label("\u950c");
    model.component("comp1").geom("geom1").feature("cyl15").set("contributeto", "csel3");
    model.component("comp1").geom("geom1").run("cyl15");
    model.component("comp1").geom("geom1").create("arr2", "Array");
    model.component("comp1").geom("geom1").feature("arr2").selection("input").named("cyl15");
    model.component("comp1").geom("geom1").feature("arr2").set("fullsize", new int[]{2, 2, 3});
    model.component("comp1").geom("geom1").feature("arr2").set("displ", new String[]{"28[m]", "-28[m]", "0"});
    model.component("comp1").geom("geom1").feature("arr2").setIndex("displ", "10[m]", 2);
    model.component("comp1").geom("geom1").run("arr2");
    model.component("comp1").geom("geom1").create("cyl16", "Cylinder");
    model.component("comp1").geom("geom1").feature("cyl16").set("r", "0.8[m]");
    model.component("comp1").geom("geom1").feature("cyl16").set("h", "4[m]");
    model.component("comp1").geom("geom1").feature("cyl16").set("pos", new String[]{"-14[m]", "0", "21[m]"});
    model.component("comp1").geom("geom1").feature("cyl16").set("selresult", true);
    model.component("comp1").geom("geom1").feature("cyl16").set("selresultshow", false);
    model.component("comp1").geom("geom1").run("cyl16");
    model.component("comp1").geom("geom1").create("rot10", "Rotate");
    model.component("comp1").geom("geom1").feature("rot10").selection("input").named("cyl16");
    model.component("comp1").geom("geom1").feature("rot10").set("rot", "range(90[deg],90[deg],360[deg])");
    model.component("comp1").geom("geom1").run("rot10");
    model.component("comp1").geom("geom1").create("arr3", "Array");
    model.component("comp1").geom("geom1").feature("arr3").selection("input").named("cyl16");
    model.component("comp1").geom("geom1").feature("arr3").set("fullsize", new int[]{1, 1, 7});
    model.component("comp1").geom("geom1").feature("arr3").set("displ", new String[]{"28[m]", "-28[m]", "0"});
    model.component("comp1").geom("geom1").feature("arr3").setIndex("displ", "10[m]", 2);
    model.component("comp1").geom("geom1").feature("arr3").set("selresult", true);
    model.component("comp1").geom("geom1").feature("arr3").set("selresultshow", false);
    model.component("comp1").geom("geom1").feature("arr3").set("contributeto", "csel3");
    model.component("comp1").geom("geom1").run("arr3");
    model.component("comp1").geom("geom1").create("unisel1", "UnionSelection");
    model.component("comp1").geom("geom1").feature("unisel1").label("\u6240\u6709\u7535\u6781");
    model.component("comp1").geom("geom1").feature("unisel1").set("entitydim", -1);
    model.component("comp1").geom("geom1").feature("unisel1").set("input", new String[]{"csel1", "csel3"});
    model.component("comp1").geom("geom1").feature("unisel1").set("selshow", "bnd");
    model.component("comp1").geom("geom1").run("unisel1");
    model.component("comp1").geom("geom1").create("wp1", "WorkPlane");
    model.component("comp1").geom("geom1").feature("wp1").set("unite", true);
    model.component("comp1").geom("geom1").feature("wp1").geom().create("c1", "Circle");
    model.component("comp1").geom("geom1").feature("wp1").geom().feature("c1").set("r", "50[m]");
    model.component("comp1").geom("geom1").feature("wp1").geom().feature("c1").set("angle", "90[deg]");
    model.component("comp1").geom("geom1").feature("wp1").geom().feature("c1").set("rot", "180[deg]");
    model.component("comp1").geom("geom1").run("wp1");
    model.component("comp1").geom("geom1").feature().create("ext1", "Extrude");
    model.component("comp1").geom("geom1").feature("ext1").set("workplane", "wp1");
    model.component("comp1").geom("geom1").feature("ext1").selection("input").set("wp1");
    model.component("comp1").geom("geom1").feature("ext1").setIndex("distance", "92[m]", 0);
    model.component("comp1").geom("geom1").run("ext1");
    model.component("comp1").geom("geom1").create("dif1", "Difference");
    model.component("comp1").geom("geom1").feature("dif1").selection("input").set("ext1");
    model.component("comp1").geom("geom1").feature("dif1").selection("input2").named("unisel1");
    model.component("comp1").geom("geom1").run("dif1");

    model.component("comp1").view("view1").set("renderwireframe", true);

    model.component("comp1").geom("geom1").run("fin");
    model.component("comp1").geom("geom1").create("rmd1", "RemoveDetails");
    model.component("comp1").geom("geom1").run("rmd1");

    model.title(null);

    model.description("");

    model.label("anode_film_resistance_geom_sequence.mph");

    return model;
  }

  public static void main(String[] args) {
    run();
  }

}
