/*
 * micromixer_geom_sequence.java
 */

import com.comsol.model.*;
import com.comsol.model.util.*;

/** Model exported on Apr 29 2026, 18:34 by COMSOL 6.3.0.290. */
public class micromixer_geom_sequence {

  public static Model run() {
    Model model = ModelUtil.create("Model");

    model
         .modelPath("D:\\Program Files\\COMSOL\\COMSOL63\\Multiphysics\\applications\\COMSOL_Multiphysics\\Fluid_Dynamics");

    model.component().create("comp1", true);

    model.component("comp1").geom().create("geom1", 3);
    model.component("comp1").geom("geom1").geomRep("comsol");

    model.component("comp1").mesh().create("mesh1");
    model.component("comp1").mesh("mesh1").contribute("geom/detail", true);

    model.component("comp1").geom("geom1").lengthUnit("mm");
    model.component("comp1").geom("geom1").create("blk1", "Block");
    model.component("comp1").geom("geom1").feature("blk1").set("size", new double[]{1, 1.4, 1.4});
    model.component("comp1").geom("geom1").feature("blk1").set("pos", new double[]{-3.5, -0.7, -0.7});
    model.component("comp1").geom("geom1").run("blk1");
    model.component("comp1").geom("geom1").create("blk2", "Block");
    model.component("comp1").geom("geom1").feature("blk2").set("size", new double[]{1, 1.4, 1.4});
    model.component("comp1").geom("geom1").feature("blk2").set("pos", new double[]{7, -0.7, -0.7});
    model.component("comp1").geom("geom1").run("blk2");
    model.component("comp1").geom("geom1").create("blk3", "Block");
    model.component("comp1").geom("geom1").feature("blk3").set("size", new double[]{0.5, 1, 1});
    model.component("comp1").geom("geom1").feature("blk3").set("pos", new double[]{-0.5, -1.5, -0.5});
    model.component("comp1").geom("geom1").run("blk3");
    model.component("comp1").geom("geom1").create("blk4", "Block");
    model.component("comp1").geom("geom1").feature("blk4").set("size", new double[]{0.5, 1, 1});
    model.component("comp1").geom("geom1").feature("blk4").set("pos", new double[]{2, -1.5, -0.5});
    model.component("comp1").geom("geom1").run("blk4");
    model.component("comp1").geom("geom1").create("blk5", "Block");
    model.component("comp1").geom("geom1").feature("blk5").set("size", new double[]{0.5, 1, 1});
    model.component("comp1").geom("geom1").feature("blk5").set("pos", new double[]{4.5, -1.5, -0.5});
    model.component("comp1").geom("geom1").run("blk5");
    model.component("comp1").geom("geom1").create("hex1", "Hexahedron");
    model.component("comp1").geom("geom1").feature("hex1").setIndex("p", -2.5, 0, 0);
    model.component("comp1").geom("geom1").feature("hex1").setIndex("p", -0.7, 1, 0);
    model.component("comp1").geom("geom1").feature("hex1").setIndex("p", -0.7, 2, 0);
    model.component("comp1").geom("geom1").feature("hex1").setIndex("p", -0.5, 0, 1);
    model.component("comp1").geom("geom1").feature("hex1").setIndex("p", -1.5, 1, 1);
    model.component("comp1").geom("geom1").feature("hex1").setIndex("p", -0.5, 2, 1);
    model.component("comp1").geom("geom1").feature("hex1").setIndex("p", -0.5, 0, 2);
    model.component("comp1").geom("geom1").feature("hex1").setIndex("p", -0.5, 1, 2);
    model.component("comp1").geom("geom1").feature("hex1").setIndex("p", -0.5, 2, 2);
    model.component("comp1").geom("geom1").feature("hex1").setIndex("p", -2.5, 0, 3);
    model.component("comp1").geom("geom1").feature("hex1").setIndex("p", -0.7, 2, 3);
    model.component("comp1").geom("geom1").feature("hex1").setIndex("p", -2.5, 0, 4);
    model.component("comp1").geom("geom1").feature("hex1").setIndex("p", -0.7, 1, 4);
    model.component("comp1").geom("geom1").feature("hex1").setIndex("p", 0.7, 2, 4);
    model.component("comp1").geom("geom1").feature("hex1").setIndex("p", -0.5, 0, 5);
    model.component("comp1").geom("geom1").feature("hex1").setIndex("p", -1.5, 1, 5);
    model.component("comp1").geom("geom1").feature("hex1").setIndex("p", 0.5, 2, 5);
    model.component("comp1").geom("geom1").feature("hex1").setIndex("p", -0.5, 0, 6);
    model.component("comp1").geom("geom1").feature("hex1").setIndex("p", -0.5, 1, 6);
    model.component("comp1").geom("geom1").feature("hex1").setIndex("p", 0.5, 2, 6);
    model.component("comp1").geom("geom1").feature("hex1").setIndex("p", -2.5, 0, 7);
    model.component("comp1").geom("geom1").feature("hex1").setIndex("p", 0.7, 2, 7);
    model.component("comp1").geom("geom1").run("hex1");
    model.component("comp1").geom("geom1").create("hex2", "Hexahedron");
    model.component("comp1").geom("geom1").feature("hex2").setIndex("p", 5, 0, 0);
    model.component("comp1").geom("geom1").feature("hex2").setIndex("p", -1.5, 1, 0);
    model.component("comp1").geom("geom1").feature("hex2").setIndex("p", -0.5, 2, 0);
    model.component("comp1").geom("geom1").feature("hex2").setIndex("p", 6, 0, 1);
    model.component("comp1").geom("geom1").feature("hex2").setIndex("p", -1.1, 1, 1);
    model.component("comp1").geom("geom1").feature("hex2").setIndex("p", -0.8, 2, 1);
    model.component("comp1").geom("geom1").feature("hex2").setIndex("p", 6, 0, 2);
    model.component("comp1").geom("geom1").feature("hex2").setIndex("p", -0.1, 1, 2);
    model.component("comp1").geom("geom1").feature("hex2").setIndex("p", -0.8, 2, 2);
    model.component("comp1").geom("geom1").feature("hex2").setIndex("p", 5, 0, 3);
    model.component("comp1").geom("geom1").feature("hex2").setIndex("p", -0.5, 1, 3);
    model.component("comp1").geom("geom1").feature("hex2").setIndex("p", -0.5, 2, 3);
    model.component("comp1").geom("geom1").feature("hex2").setIndex("p", 5, 0, 4);
    model.component("comp1").geom("geom1").feature("hex2").setIndex("p", -1.5, 1, 4);
    model.component("comp1").geom("geom1").feature("hex2").setIndex("p", 0.5, 2, 4);
    model.component("comp1").geom("geom1").feature("hex2").setIndex("p", 6, 0, 5);
    model.component("comp1").geom("geom1").feature("hex2").setIndex("p", -1.1, 1, 5);
    model.component("comp1").geom("geom1").feature("hex2").setIndex("p", -0.1, 2, 5);
    model.component("comp1").geom("geom1").feature("hex2").setIndex("p", 6, 0, 6);
    model.component("comp1").geom("geom1").feature("hex2").setIndex("p", -0.1, 1, 6);
    model.component("comp1").geom("geom1").feature("hex2").setIndex("p", -0.1, 2, 6);
    model.component("comp1").geom("geom1").feature("hex2").setIndex("p", 5, 0, 7);
    model.component("comp1").geom("geom1").feature("hex2").setIndex("p", -0.5, 1, 7);
    model.component("comp1").geom("geom1").feature("hex2").setIndex("p", 0.5, 2, 7);
    model.component("comp1").geom("geom1").run("hex2");
    model.component("comp1").geom("geom1").create("hex3", "Hexahedron");
    model.component("comp1").geom("geom1").feature("hex3").setIndex("p", 6, 0, 0);
    model.component("comp1").geom("geom1").feature("hex3").setIndex("p", -1.1, 1, 0);
    model.component("comp1").geom("geom1").feature("hex3").setIndex("p", -0.8, 2, 0);
    model.component("comp1").geom("geom1").feature("hex3").setIndex("p", 7, 0, 1);
    model.component("comp1").geom("geom1").feature("hex3").setIndex("p", -0.7, 1, 1);
    model.component("comp1").geom("geom1").feature("hex3").setIndex("p", -0.7, 2, 1);
    model.component("comp1").geom("geom1").feature("hex3").setIndex("p", 7, 0, 2);
    model.component("comp1").geom("geom1").feature("hex3").setIndex("p", 0.7, 1, 2);
    model.component("comp1").geom("geom1").feature("hex3").setIndex("p", -0.7, 2, 2);
    model.component("comp1").geom("geom1").feature("hex3").setIndex("p", 6, 0, 3);
    model.component("comp1").geom("geom1").feature("hex3").setIndex("p", -0.1, 1, 3);
    model.component("comp1").geom("geom1").feature("hex3").setIndex("p", -0.8, 2, 3);
    model.component("comp1").geom("geom1").feature("hex3").setIndex("p", 6, 0, 4);
    model.component("comp1").geom("geom1").feature("hex3").setIndex("p", -1.1, 1, 4);
    model.component("comp1").geom("geom1").feature("hex3").setIndex("p", -0.1, 2, 4);
    model.component("comp1").geom("geom1").feature("hex3").setIndex("p", 7, 0, 5);
    model.component("comp1").geom("geom1").feature("hex3").setIndex("p", -0.7, 1, 5);
    model.component("comp1").geom("geom1").feature("hex3").setIndex("p", 0, 2, 5);
    model.component("comp1").geom("geom1").feature("hex3").setIndex("p", 7, 0, 6);
    model.component("comp1").geom("geom1").feature("hex3").setIndex("p", 0.7, 1, 6);
    model.component("comp1").geom("geom1").feature("hex3").setIndex("p", 0, 2, 6);
    model.component("comp1").geom("geom1").feature("hex3").setIndex("p", 6, 0, 7);
    model.component("comp1").geom("geom1").feature("hex3").setIndex("p", -0.1, 1, 7);
    model.component("comp1").geom("geom1").feature("hex3").setIndex("p", -0.1, 2, 7);
    model.component("comp1").geom("geom1").run("hex3");
    model.component("comp1").geom("geom1").create("hex4", "Hexahedron");
    model.component("comp1").geom("geom1").feature("hex4").setIndex("p", -1.5, 1, 0);
    model.component("comp1").geom("geom1").feature("hex4").setIndex("p", -0.5, 2, 0);
    model.component("comp1").geom("geom1").feature("hex4").setIndex("p", 0.7, 0, 1);
    model.component("comp1").geom("geom1").feature("hex4").setIndex("p", -1.7, 1, 1);
    model.component("comp1").geom("geom1").feature("hex4").setIndex("p", -0.7, 2, 1);
    model.component("comp1").geom("geom1").feature("hex4").setIndex("p", 0.7, 0, 2);
    model.component("comp1").geom("geom1").feature("hex4").setIndex("p", -1.07, 1, 2);
    model.component("comp1").geom("geom1").feature("hex4").setIndex("p", -0.7, 2, 2);
    model.component("comp1").geom("geom1").feature("hex4").setIndex("p", 0, 0, 3);
    model.component("comp1").geom("geom1").feature("hex4").setIndex("p", -1, 1, 3);
    model.component("comp1").geom("geom1").feature("hex4").setIndex("p", -0.5, 2, 3);
    model.component("comp1").geom("geom1").feature("hex4").setIndex("p", -1.5, 1, 4);
    model.component("comp1").geom("geom1").feature("hex4").setIndex("p", 0.5, 2, 4);
    model.component("comp1").geom("geom1").feature("hex4").setIndex("p", 0.7, 0, 5);
    model.component("comp1").geom("geom1").feature("hex4").setIndex("p", -1.7, 1, 5);
    model.component("comp1").geom("geom1").feature("hex4").setIndex("p", 0.08, 2, 5);
    model.component("comp1").geom("geom1").feature("hex4").setIndex("p", 0.7, 0, 6);
    model.component("comp1").geom("geom1").feature("hex4").setIndex("p", -1.07, 1, 6);
    model.component("comp1").geom("geom1").feature("hex4").setIndex("p", 0.08, 2, 6);
    model.component("comp1").geom("geom1").feature("hex4").setIndex("p", 0, 0, 7);
    model.component("comp1").geom("geom1").feature("hex4").setIndex("p", -1, 1, 7);
    model.component("comp1").geom("geom1").feature("hex4").setIndex("p", 0.5, 2, 7);
    model.component("comp1").geom("geom1").run("hex4");
    model.component("comp1").geom("geom1").create("hex5", "Hexahedron");
    model.component("comp1").geom("geom1").feature("hex5").setIndex("p", 0.7, 0, 0);
    model.component("comp1").geom("geom1").feature("hex5").setIndex("p", -1.7, 1, 0);
    model.component("comp1").geom("geom1").feature("hex5").setIndex("p", -0.7, 2, 0);
    model.component("comp1").geom("geom1").feature("hex5").setIndex("p", 1, 0, 1);
    model.component("comp1").geom("geom1").feature("hex5").setIndex("p", -1.7, 1, 1);
    model.component("comp1").geom("geom1").feature("hex5").setIndex("p", -0.7, 2, 1);
    model.component("comp1").geom("geom1").feature("hex5").setIndex("p", 0.7, 0, 3);
    model.component("comp1").geom("geom1").feature("hex5").setIndex("p", 0.7, 0, 4);
    model.component("comp1").geom("geom1").feature("hex5").setIndex("p", 1, 0, 5);
    model.component("comp1").geom("geom1").feature("hex5").setIndex("p", 0.7, 0, 7);
    model.component("comp1").geom("geom1").feature("hex5").setIndex("p", -1.1, 1, 2);
    model.component("comp1").geom("geom1").feature("hex5").setIndex("p", -1.07, 1, 3);
    model.component("comp1").geom("geom1").feature("hex5").setIndex("p", -1.7, 1, 4);
    model.component("comp1").geom("geom1").feature("hex5").setIndex("p", -1.7, 1, 5);
    model.component("comp1").geom("geom1").feature("hex5").setIndex("p", -1.1, 1, 6);
    model.component("comp1").geom("geom1").feature("hex5").setIndex("p", -1.07, 1, 7);
    model.component("comp1").geom("geom1").feature("hex5").setIndex("p", -0.7, 2, 2);
    model.component("comp1").geom("geom1").feature("hex5").setIndex("p", -0.7, 2, 3);
    model.component("comp1").geom("geom1").feature("hex5").setIndex("p", 0.08, 2, 4);
    model.component("comp1").geom("geom1").feature("hex5").setIndex("p", -0.1, 2, 5);
    model.component("comp1").geom("geom1").feature("hex5").setIndex("p", -0.1, 2, 6);
    model.component("comp1").geom("geom1").feature("hex5").setIndex("p", 0.08, 2, 7);
    model.component("comp1").geom("geom1").run("hex5");
    model.component("comp1").geom("geom1").create("hex6", "Hexahedron");
    model.component("comp1").geom("geom1").feature("hex6").setIndex("p", 1, 0, 0);
    model.component("comp1").geom("geom1").feature("hex6").setIndex("p", 1.3, 0, 1);
    model.component("comp1").geom("geom1").feature("hex6").setIndex("p", 1.3, 0, 2);
    model.component("comp1").geom("geom1").feature("hex6").setIndex("p", 1, 0, 4);
    model.component("comp1").geom("geom1").feature("hex6").setIndex("p", 1.3, 0, 5);
    model.component("comp1").geom("geom1").feature("hex6").setIndex("p", 1.3, 0, 6);
    model.component("comp1").geom("geom1").feature("hex6").setIndex("p", -1.7, 1, 0);
    model.component("comp1").geom("geom1").feature("hex6").setIndex("p", -0.7, 2, 0);
    model.component("comp1").geom("geom1").feature("hex6").setIndex("p", -1.7, 1, 1);
    model.component("comp1").geom("geom1").feature("hex6").setIndex("p", -1.7, 1, 4);
    model.component("comp1").geom("geom1").feature("hex6").setIndex("p", -1.7, 1, 5);
    model.component("comp1").geom("geom1").feature("hex6").setIndex("p", -0.7, 2, 1);
    model.component("comp1").geom("geom1").feature("hex6").setIndex("p", -0.7, 2, 2);
    model.component("comp1").geom("geom1").feature("hex6").setIndex("p", -0.7, 2, 3);
    model.component("comp1").geom("geom1").feature("hex6").setIndex("p", -0.1, 2, 4);
    model.component("comp1").geom("geom1").feature("hex6").setIndex("p", -0.07, 2, 5);
    model.component("comp1").geom("geom1").feature("hex6").setIndex("p", -0.07, 2, 6);
    model.component("comp1").geom("geom1").feature("hex6").setIndex("p", -0.1, 2, 7);
    model.component("comp1").geom("geom1").feature("hex6").setIndex("p", -1.1, 1, 7);
    model.component("comp1").geom("geom1").feature("hex6").setIndex("p", -0.92, 1, 6);
    model.component("comp1").geom("geom1").feature("hex6").setIndex("p", -0.92, 1, 2);
    model.component("comp1").geom("geom1").feature("hex6").setIndex("p", -1.1, 1, 3);
    model.component("comp1").geom("geom1").run("hex6");
    model.component("comp1").geom("geom1").create("hex7", "Hexahedron");
    model.component("comp1").geom("geom1").feature("hex7").setIndex("p", 1.3, 0, 0);
    model.component("comp1").geom("geom1").feature("hex7").setIndex("p", 2, 0, 1);
    model.component("comp1").geom("geom1").feature("hex7").setIndex("p", 2, 0, 2);
    model.component("comp1").geom("geom1").feature("hex7").setIndex("p", 1.3, 0, 3);
    model.component("comp1").geom("geom1").feature("hex7").setIndex("p", 1.3, 0, 4);
    model.component("comp1").geom("geom1").feature("hex7").setIndex("p", 2, 0, 5);
    model.component("comp1").geom("geom1").feature("hex7").setIndex("p", 2, 0, 6);
    model.component("comp1").geom("geom1").feature("hex7").setIndex("p", 1.3, 0, 7);
    model.component("comp1").geom("geom1").feature("hex7").setIndex("p", -1.7, 1, 0);
    model.component("comp1").geom("geom1").feature("hex7").setIndex("p", -0.7, 2, 0);
    model.component("comp1").geom("geom1").feature("hex7").setIndex("p", -0.5, 2, 1);
    model.component("comp1").geom("geom1").feature("hex7").setIndex("p", -0.5, 2, 2);
    model.component("comp1").geom("geom1").feature("hex7").setIndex("p", -0.7, 2, 3);
    model.component("comp1").geom("geom1").feature("hex7").setIndex("p", -0.07, 2, 4);
    model.component("comp1").geom("geom1").feature("hex7").setIndex("p", 0, 2, 5);
    model.component("comp1").geom("geom1").feature("hex7").setIndex("p", 0, 2, 6);
    model.component("comp1").geom("geom1").feature("hex7").setIndex("p", -0.07, 2, 7);
    model.component("comp1").geom("geom1").feature("hex7").setIndex("p", -1.5, 1, 1);
    model.component("comp1").geom("geom1").feature("hex7").setIndex("p", -0.5, 1, 2);
    model.component("comp1").geom("geom1").feature("hex7").setIndex("p", -0.92, 1, 3);
    model.component("comp1").geom("geom1").feature("hex7").setIndex("p", -1.7, 1, 4);
    model.component("comp1").geom("geom1").feature("hex7").setIndex("p", -1.5, 1, 5);
    model.component("comp1").geom("geom1").feature("hex7").setIndex("p", -0.5, 1, 6);
    model.component("comp1").geom("geom1").feature("hex7").setIndex("p", -0.92, 1, 7);
    model.component("comp1").geom("geom1").run("hex7");
    model.component("comp1").geom("geom1").create("hex8", "Hexahedron");
    model.component("comp1").geom("geom1").feature("hex8").setIndex("p", 2.5, 0, 0);
    model.component("comp1").geom("geom1").feature("hex8").setIndex("p", 3.2, 0, 1);
    model.component("comp1").geom("geom1").feature("hex8").setIndex("p", 3.2, 0, 2);
    model.component("comp1").geom("geom1").feature("hex8").setIndex("p", 3.2, 0, 6);
    model.component("comp1").geom("geom1").feature("hex8").setIndex("p", 3.2, 0, 5);
    model.component("comp1").geom("geom1").feature("hex8").setIndex("p", 2.5, 0, 3);
    model.component("comp1").geom("geom1").feature("hex8").setIndex("p", 2.5, 0, 4);
    model.component("comp1").geom("geom1").feature("hex8").setIndex("p", 2.5, 0, 7);
    model.component("comp1").geom("geom1").feature("hex8").setIndex("p", -1.5, 1, 0);
    model.component("comp1").geom("geom1").feature("hex8").setIndex("p", -1.7, 1, 1);
    model.component("comp1").geom("geom1").feature("hex8").setIndex("p", -1.07, 1, 2);
    model.component("comp1").geom("geom1").feature("hex8").setIndex("p", -1, 1, 3);
    model.component("comp1").geom("geom1").feature("hex8").setIndex("p", -1.5, 1, 4);
    model.component("comp1").geom("geom1").feature("hex8").setIndex("p", -1.7, 1, 5);
    model.component("comp1").geom("geom1").feature("hex8").setIndex("p", -1.07, 1, 6);
    model.component("comp1").geom("geom1").feature("hex8").setIndex("p", -1, 1, 7);
    model.component("comp1").geom("geom1").feature("hex8").setIndex("p", -0.5, 2, 0);
    model.component("comp1").geom("geom1").feature("hex8").setIndex("p", -0.08, 2, 1);
    model.component("comp1").geom("geom1").feature("hex8").setIndex("p", -0.08, 2, 2);
    model.component("comp1").geom("geom1").feature("hex8").setIndex("p", -0.5, 2, 3);
    model.component("comp1").geom("geom1").feature("hex8").setIndex("p", 0.5, 2, 4);
    model.component("comp1").geom("geom1").feature("hex8").setIndex("p", 0.7, 2, 5);
    model.component("comp1").geom("geom1").feature("hex8").setIndex("p", 0.7, 2, 6);
    model.component("comp1").geom("geom1").feature("hex8").setIndex("p", 0.5, 2, 7);
    model.component("comp1").geom("geom1").run("hex8");
    model.component("comp1").geom("geom1").create("hex9", "Hexahedron");
    model.component("comp1").geom("geom1").feature("hex9").setIndex("p", 3.2, 0, 0);
    model.component("comp1").geom("geom1").feature("hex9").setIndex("p", 3.5, 0, 1);
    model.component("comp1").geom("geom1").feature("hex9").setIndex("p", 3.5, 0, 2);
    model.component("comp1").geom("geom1").feature("hex9").setIndex("p", 3.5, 0, 6);
    model.component("comp1").geom("geom1").feature("hex9").setIndex("p", 3.5, 0, 5);
    model.component("comp1").geom("geom1").feature("hex9").setIndex("p", 3.2, 0, 3);
    model.component("comp1").geom("geom1").feature("hex9").setIndex("p", 3.2, 0, 4);
    model.component("comp1").geom("geom1").feature("hex9").setIndex("p", 3.2, 0, 7);
    model.component("comp1").geom("geom1").feature("hex9").setIndex("p", -1.7, 1, 0);
    model.component("comp1").geom("geom1").feature("hex9").setIndex("p", -1.7, 1, 1);
    model.component("comp1").geom("geom1").feature("hex9").setIndex("p", -1.7, 1, 5);
    model.component("comp1").geom("geom1").feature("hex9").setIndex("p", -1.7, 1, 4);
    model.component("comp1").geom("geom1").feature("hex9").setIndex("p", -1.1, 1, 2);
    model.component("comp1").geom("geom1").feature("hex9").setIndex("p", -1.07, 1, 3);
    model.component("comp1").geom("geom1").feature("hex9").setIndex("p", -1.1, 1, 6);
    model.component("comp1").geom("geom1").feature("hex9").setIndex("p", -1.07, 1, 7);
    model.component("comp1").geom("geom1").feature("hex9").setIndex("p", -0.08, 2, 0);
    model.component("comp1").geom("geom1").feature("hex9").setIndex("p", 0.1, 2, 1);
    model.component("comp1").geom("geom1").feature("hex9").setIndex("p", 0.1, 2, 2);
    model.component("comp1").geom("geom1").feature("hex9").setIndex("p", -0.08, 2, 3);
    model.component("comp1").geom("geom1").feature("hex9").setIndex("p", 0.7, 2, 4);
    model.component("comp1").geom("geom1").feature("hex9").setIndex("p", 0.7, 2, 5);
    model.component("comp1").geom("geom1").feature("hex9").setIndex("p", 0.7, 2, 6);
    model.component("comp1").geom("geom1").feature("hex9").setIndex("p", 0.7, 2, 7);
    model.component("comp1").geom("geom1").run("hex9");
    model.component("comp1").geom("geom1").create("hex10", "Hexahedron");
    model.component("comp1").geom("geom1").feature("hex10").setIndex("p", 3.5, 0, 0);
    model.component("comp1").geom("geom1").feature("hex10").setIndex("p", 3.5, 0, 7);
    model.component("comp1").geom("geom1").feature("hex10").setIndex("p", 3.5, 0, 4);
    model.component("comp1").geom("geom1").feature("hex10").setIndex("p", 3.5, 0, 3);
    model.component("comp1").geom("geom1").feature("hex10").setIndex("p", 3.8, 0, 1);
    model.component("comp1").geom("geom1").feature("hex10").setIndex("p", 3.8, 0, 2);
    model.component("comp1").geom("geom1").feature("hex10").setIndex("p", 3.8, 0, 5);
    model.component("comp1").geom("geom1").feature("hex10").setIndex("p", 3.8, 0, 6);
    model.component("comp1").geom("geom1").feature("hex10").setIndex("p", -1.7, 1, 0);
    model.component("comp1").geom("geom1").feature("hex10").setIndex("p", -1.7, 1, 1);
    model.component("comp1").geom("geom1").feature("hex10").setIndex("p", -1.7, 1, 5);
    model.component("comp1").geom("geom1").feature("hex10").setIndex("p", -1.7, 1, 4);
    model.component("comp1").geom("geom1").feature("hex10").setIndex("p", -0.92, 1, 2);
    model.component("comp1").geom("geom1").feature("hex10").setIndex("p", -1.1, 1, 3);
    model.component("comp1").geom("geom1").feature("hex10").setIndex("p", -0.92, 1, 6);
    model.component("comp1").geom("geom1").feature("hex10").setIndex("p", -1.1, 1, 7);
    model.component("comp1").geom("geom1").feature("hex10").setIndex("p", 0.1, 2, 0);
    model.component("comp1").geom("geom1").feature("hex10").setIndex("p", 0.07, 2, 1);
    model.component("comp1").geom("geom1").feature("hex10").setIndex("p", 0.07, 2, 2);
    model.component("comp1").geom("geom1").feature("hex10").setIndex("p", 0.1, 2, 3);
    model.component("comp1").geom("geom1").feature("hex10").setIndex("p", 0.7, 2, 4);
    model.component("comp1").geom("geom1").feature("hex10").setIndex("p", 0.7, 2, 5);
    model.component("comp1").geom("geom1").feature("hex10").setIndex("p", 0.7, 2, 6);
    model.component("comp1").geom("geom1").feature("hex10").setIndex("p", 0.7, 2, 7);
    model.component("comp1").geom("geom1").run("hex10");
    model.component("comp1").geom("geom1").create("hex11", "Hexahedron");
    model.component("comp1").geom("geom1").feature("hex11").setIndex("p", 3.8, 0, 0);
    model.component("comp1").geom("geom1").feature("hex11").setIndex("p", 4.5, 0, 1);
    model.component("comp1").geom("geom1").feature("hex11").setIndex("p", 4.5, 0, 2);
    model.component("comp1").geom("geom1").feature("hex11").setIndex("p", 4.5, 0, 5);
    model.component("comp1").geom("geom1").feature("hex11").setIndex("p", 4.5, 0, 6);
    model.component("comp1").geom("geom1").feature("hex11").setIndex("p", 3.8, 0, 3);
    model.component("comp1").geom("geom1").feature("hex11").setIndex("p", 3.8, 0, 4);
    model.component("comp1").geom("geom1").feature("hex11").setIndex("p", 3.8, 0, 7);
    model.component("comp1").geom("geom1").feature("hex11").setIndex("p", -1.7, 1, 0);
    model.component("comp1").geom("geom1").feature("hex11").setIndex("p", -1.5, 1, 1);
    model.component("comp1").geom("geom1").feature("hex11").setIndex("p", -0.5, 1, 2);
    model.component("comp1").geom("geom1").feature("hex11").setIndex("p", -0.92, 1, 3);
    model.component("comp1").geom("geom1").feature("hex11").setIndex("p", -1.7, 1, 4);
    model.component("comp1").geom("geom1").feature("hex11").setIndex("p", -1.5, 1, 5);
    model.component("comp1").geom("geom1").feature("hex11").setIndex("p", -0.5, 1, 6);
    model.component("comp1").geom("geom1").feature("hex11").setIndex("p", -0.92, 1, 7);
    model.component("comp1").geom("geom1").feature("hex11").setIndex("p", 0.07, 2, 0);
    model.component("comp1").geom("geom1").feature("hex11").setIndex("p", 0.07, 2, 3);
    model.component("comp1").geom("geom1").feature("hex11").setIndex("p", 0.7, 2, 4);
    model.component("comp1").geom("geom1").feature("hex11").setIndex("p", 0.7, 2, 7);
    model.component("comp1").geom("geom1").feature("hex11").setIndex("p", 0.5, 2, 5);
    model.component("comp1").geom("geom1").feature("hex11").setIndex("p", 0.5, 2, 6);
    model.component("comp1").geom("geom1").run("hex11");
    model.component("comp1").geom("geom1").create("mir1", "Mirror");
    model.component("comp1").geom("geom1").feature("mir1").selection("input")
         .set("hex10", "hex11", "hex4", "hex5", "hex6", "hex7", "hex8", "hex9");
    model.component("comp1").geom("geom1").feature("mir1").set("keep", true);
    model.component("comp1").geom("geom1").run("mir1");
    model.component("comp1").geom("geom1").create("mir2", "Mirror");
    model.component("comp1").geom("geom1").feature("mir2").selection("input").set("mir1");
    model.component("comp1").geom("geom1").feature("mir2").set("pos", new int[]{0, -1, 0});
    model.component("comp1").geom("geom1").feature("mir2").set("axis", new int[]{0, 1, 0});
    model.component("comp1").geom("geom1").run("mir2");
    model.component("comp1").geom("geom1").create("mir3", "Mirror");
    model.component("comp1").geom("geom1").feature("mir3").selection("input").set("hex2", "hex3");
    model.component("comp1").geom("geom1").feature("mir3").set("keep", true);
    model.component("comp1").geom("geom1").run("mir3");
    model.component("comp1").geom("geom1").create("mir4", "Mirror");
    model.component("comp1").geom("geom1").feature("mir4").selection("input").set("mir3");
    model.component("comp1").geom("geom1").feature("mir4").set("axis", new int[]{0, 1, 0});
    model.component("comp1").geom("geom1").run("mir4");
    model.component("comp1").geom("geom1").create("mir5", "Mirror");
    model.component("comp1").geom("geom1").feature("mir5").selection("input")
         .set("blk2", "blk3", "blk4", "blk5", "hex1", "hex10", "hex11", "hex4", "hex5", "hex6", "hex7", "hex8", "hex9", "mir2");
    model.component("comp1").geom("geom1").feature("mir5").set("axis", new int[]{0, 1, 0});
    model.component("comp1").geom("geom1").feature("mir5").set("keep", true);
    model.component("comp1").geom("geom1").run("mir5");
    model.component("comp1").geom("geom1").create("uni1", "Union");
    model.component("comp1").geom("geom1").feature("uni1").selection("input")
         .set("blk1", "blk2", "blk3", "blk4", "blk5", "hex1", "hex10", "hex11", "hex2", "hex3", "hex4", "hex5", "hex6", "hex7", "hex8", "hex9", "mir2", "mir4", "mir5");
    model.component("comp1").geom("geom1").feature("uni1").set("intbnd", false);
    model.component("comp1").geom("geom1").run("fin");
    model.component("comp1").geom("geom1").create("sel1", "ExplicitSelection");
    model.component("comp1").geom("geom1").feature("sel1").label("\u5165\u53e3");
    model.component("comp1").geom("geom1").feature("sel1").selection("selection").init(2);
    model.component("comp1").geom("geom1").feature("sel1").selection("selection").set("fin", 1);
    model.component("comp1").geom("geom1").run("sel1");
    model.component("comp1").geom("geom1").create("sel2", "ExplicitSelection");
    model.component("comp1").geom("geom1").feature("sel2").label("\u51fa\u53e3");
    model.component("comp1").geom("geom1").feature("sel2").selection("selection").init(2);
    model.component("comp1").geom("geom1").feature("sel2").selection("selection").set("fin", 186);
    model.component("comp1").geom("geom1").run("sel2");
    model.component("comp1").geom("geom1").create("boxsel1", "BoxSelection");
    model.component("comp1").geom("geom1").feature("boxsel1").set("entitydim", 2);
    model.component("comp1").geom("geom1").feature("boxsel1").set("xmin", -3.4);
    model.component("comp1").geom("geom1").feature("boxsel1").set("xmax", 7.9);
    model.component("comp1").geom("geom1").feature("boxsel1").label("\u58c1");
    model.component("comp1").geom("geom1").run("boxsel1");

    model.title(null);

    model.description("");

    model.label("micromixer_geom_sequence.mph");

    return model;
  }

  public static void main(String[] args) {
    run();
  }

}
