/*
 * electrodeless_lamp.java
 */

import com.comsol.model.*;
import com.comsol.model.util.*;

/** Model exported on Apr 30 2026, 12:05 by COMSOL 6.3.0.290. */
public class electrodeless_lamp {

  public static Model run() {
    Model model = ModelUtil.create("Model");

    model.component().create("comp1", true);

    model.component("comp1").geom().create("geom1", 2);
    model.component("comp1").geom("geom1").axisymmetric(true);

    model.component("comp1").mesh().create("mesh1");

    model.component("comp1").physics().create("plas", "ColdPlasma", "geom1");
    model.component("comp1").physics().create("mf", "InductionCurrents", "geom1");
    model.component("comp1").physics("mf").prop("ShapeProperty").set("order_magneticvectorpotential", "1");
    model.component("comp1").physics("mf").create("alf1", "AmperesLawFluid");
    model.component("comp1").physics("mf").feature("alf1").selection().all();

    model.component("comp1").multiphysics().create("pcc1", "PlasmaConductivityMultiphysicsCoupling", 2);
    model.component("comp1").multiphysics("pcc1").set("elm_physics", "mf");
    model.component("comp1").multiphysics("pcc1").set("plas_physics", "plas");
    model.component("comp1").multiphysics().create("ehs1", "ElectronHeatSourceMultiphysicsCoupling", 2);
    model.component("comp1").multiphysics("ehs1").set("elm_physics", "mf");
    model.component("comp1").multiphysics("ehs1").set("plas_physics", "plas");

    model.study().create("std1");
    model.study("std1").create("ftrans", "FrequencyTransient");
    model.study("std1").feature("ftrans").set("initialtime", "0");
    model.study("std1").feature("ftrans").set("freq", "1000");
    model.study("std1").feature("ftrans").set("solnum", "auto");
    model.study("std1").feature("ftrans").set("notsolnum", "auto");
    model.study("std1").feature("ftrans").set("outputmap", new String[]{});
    model.study("std1").feature("ftrans").setSolveFor("/physics/plas", true);
    model.study("std1").feature("ftrans").setSolveFor("/physics/mf", true);
    model.study("std1").feature("ftrans").setSolveFor("/multiphysics/pcc1", true);
    model.study("std1").feature("ftrans").setSolveFor("/multiphysics/ehs1", true);

    model.component("comp1").geom("geom1").create("ls1", "LineSegment");
    model.component("comp1").geom("geom1").feature("ls1").set("specify1", "coord");
    model.component("comp1").geom("geom1").feature("ls1").set("specify2", "coord");
    model.component("comp1").geom("geom1").feature("ls1").set("coord2", new double[]{0.015, 0});
    model.component("comp1").geom("geom1").run("ls1");
    model.component("comp1").geom("geom1").create("cb1", "CubicBezier");
    model.component("comp1").geom("geom1").feature("cb1").setIndex("p", 0.015, 0, 0);
    model.component("comp1").geom("geom1").feature("cb1").setIndex("p", 0.015, 0, 1);
    model.component("comp1").geom("geom1").feature("cb1").setIndex("p", 0.03, 0, 2);
    model.component("comp1").geom("geom1").feature("cb1").setIndex("p", 0.03, 0, 3);
    model.component("comp1").geom("geom1").feature("cb1").setIndex("p", 0.025, 1, 1);
    model.component("comp1").geom("geom1").feature("cb1").setIndex("p", 0.025, 1, 2);
    model.component("comp1").geom("geom1").feature("cb1").setIndex("p", 0.045, 1, 3);
    model.component("comp1").geom("geom1").run("cb1");
    model.component("comp1").geom("geom1").create("qb1", "QuadraticBezier");
    model.component("comp1").geom("geom1").feature("qb1").setIndex("p", 0.03, 0, 0);
    model.component("comp1").geom("geom1").feature("qb1").setIndex("p", 0.03, 0, 1);
    model.component("comp1").geom("geom1").feature("qb1").setIndex("p", 0.045, 1, 0);
    model.component("comp1").geom("geom1").feature("qb1").setIndex("p", 0.07, 1, 1);
    model.component("comp1").geom("geom1").feature("qb1").setIndex("p", 0.07, 1, 2);
    model.component("comp1").geom("geom1").run("qb1");
    model.component("comp1").geom("geom1").create("ls2", "LineSegment");
    model.component("comp1").geom("geom1").feature("ls2").set("specify1", "coord");
    model.component("comp1").geom("geom1").feature("ls2").set("specify2", "coord");
    model.component("comp1").geom("geom1").feature("ls2").set("coord1", new double[]{0, 0.07});
    model.component("comp1").geom("geom1").runPre("fin");
    model.component("comp1").geom("geom1").create("csol1", "ConvertToSolid");
    model.component("comp1").geom("geom1").feature("csol1").selection("input").set("cb1", "ls1", "ls2", "qb1");
    model.component("comp1").geom("geom1").runPre("fin");
    model.component("comp1").geom("geom1").create("r1", "Rectangle");
    model.component("comp1").geom("geom1").feature("r1").set("size", new double[]{0.004, 0.05});
    model.component("comp1").geom("geom1").run("r1");
    model.component("comp1").geom("geom1").create("r2", "Rectangle");
    model.component("comp1").geom("geom1").feature("r2").set("size", new double[]{0.006, 0.052});
    model.component("comp1").geom("geom1").run("r2");
    model.component("comp1").geom("geom1").create("r3", "Rectangle");
    model.component("comp1").geom("geom1").feature("r3").set("size", new double[]{0.007, 0.053});
    model.component("comp1").geom("geom1").run("r3");
    model.component("comp1").geom("geom1").create("cha1", "Chamfer");
    model.component("comp1").geom("geom1").feature("cha1").selection("point").set("r2", 3);
    model.component("comp1").geom("geom1").feature("cha1").set("dist", "1.5e-3");
    model.component("comp1").geom("geom1").runPre("fin");
    model.component("comp1").geom("geom1").create("cha2", "Chamfer");
    model.component("comp1").geom("geom1").feature("cha2").selection("point").set("r3", 3);
    model.component("comp1").geom("geom1").feature("cha2").set("dist", "2e-3");
    model.component("comp1").geom("geom1").runPre("fin");
    model.component("comp1").geom("geom1").create("sq1", "Square");
    model.component("comp1").geom("geom1").feature("sq1").set("size", 0.001);
    model.component("comp1").geom("geom1").feature("sq1").set("pos", new double[]{0.0045, 0.025});
    model.component("comp1").geom("geom1").runPre("fin");
    model.component("comp1").geom("geom1").create("arr1", "Array");
    model.component("comp1").geom("geom1").feature("arr1").selection("input").set("sq1");
    model.component("comp1").geom("geom1").feature("arr1").set("type", "linear");
    model.component("comp1").geom("geom1").feature("arr1").set("linearsize", 5);
    model.component("comp1").geom("geom1").feature("arr1").set("displ", new String[]{"0", "5e-3"});
    model.component("comp1").geom("geom1").runPre("fin");

    model.component("comp1").variable().create("var1");

    model.component("comp1").geom("geom1").run();

    model.component("comp1").variable("var1").set("Tinit", "350[K]");
    model.component("comp1").variable("var1").descr("Tinit", "\u6c14\u4f53\u6e29\u5ea6");
    model.component("comp1").variable("var1").set("pinit", "101325*(500E-3/760)[Pa]");
    model.component("comp1").variable("var1").descr("pinit", "\u521d\u59cb\u603b\u538b");
    model.component("comp1").variable("var1").set("lamp_power", "80[W]");
    model.component("comp1").variable("var1").descr("lamp_power", "\u706f\u529f\u7387");
    model.component("comp1").variable("var1").set("tf1", "10");
    model.component("comp1").variable("var1").descr("tf1", "\u9677\u9631\u56e0\u5b50");
    model.component("comp1").variable("var1").set("tf2", "1000");
    model.component("comp1").variable("var1").descr("tf2", "\u9677\u9631\u56e0\u5b50");

    model.component("comp1").selection().create("sel1", "Explicit");
    model.component("comp1").selection("sel1").set(5, 6, 7, 8, 9);
    model.component("comp1").selection("sel1").geom("geom1", 2, 1, new String[]{"exterior"});
    model.component("comp1").selection("sel1").set(5, 6, 7, 8, 9);
    model.component("comp1").selection("sel1").label("\u7ebf\u5708\u8fb9\u754c");
    model.component("comp1").selection().create("sel2", "Explicit");
    model.component("comp1").selection("sel2").set(5, 6, 7, 8, 9);
    model.component("comp1").selection("sel2").label("\u7ebf\u5708\u57df");
    model.component("comp1").selection().create("sel3", "Explicit");
    model.component("comp1").selection("sel3").geom(1);
    model.component("comp1").selection("sel3").set(8, 27, 35, 36, 37, 38);
    model.component("comp1").selection("sel3").label("\u8fb9\u754c\u5c42");
    model.component("comp1").selection().create("sel4", "Explicit");
    model.component("comp1").selection("sel4").set(4);
    model.component("comp1").selection("sel4").label("\u653e\u7535");

    model.component("comp1").physics("plas").prop("TransportSettings").set("MixtureDiffusionCorrection", true);
    model.component("comp1").physics("plas").selection().set(4);

    model.modelPath("${LIBRARYDIRPATH}");

    model.component("comp1").physics("plas").create("rg1", "ReactionGroup", 2);
    model.component("comp1").physics("plas").feature("rg1").set("reactionGroupType", "ElectronImpactReactions");
    model.component("comp1").physics("plas").feature("rg1").set("Filepath", "Ar_Hg_plasma_chemistry_import_Ar.txt");
    model.component("comp1").physics("plas").feature("rg1").runCommand("importData");
    model.component("comp1").physics("plas").feature("rg1").label("Ar - Electron Impact Reactions");
    model.component("comp1").physics("plas").create("rg2", "ReactionGroup", 2);
    model.component("comp1").physics("plas").feature("rg2").set("reactionGroupType", "HeavySpeciesReactions");
    model.component("comp1").physics("plas").feature("rg2").set("Filepath", "Ar_Hg_plasma_chemistry_import_Ar.txt");
    model.component("comp1").physics("plas").feature("rg2").runCommand("importData");
    model.component("comp1").physics("plas").feature("rg2").label("Ar - Heavy Species Reactions");
    model.component("comp1").physics("plas").create("rg3", "ReactionGroup", 2);
    model.component("comp1").physics("plas").feature("rg3").set("reactionGroupType", "ElectronImpactReactions");
    model.component("comp1").physics("plas").feature("rg3").set("Filepath", "Ar_Hg_plasma_chemistry_import_Hg.txt");
    model.component("comp1").physics("plas").feature("rg3").runCommand("importData");
    model.component("comp1").physics("plas").feature("rg3").label("Hg - Electron Impact Reactions");
    model.component("comp1").physics("plas").create("rg4", "ReactionGroup", 2);
    model.component("comp1").physics("plas").feature("rg4").set("reactionGroupType", "HeavySpeciesReactions");
    model.component("comp1").physics("plas").feature("rg4").set("Filepath", "Ar_Hg_plasma_chemistry_import_Hg.txt");
    model.component("comp1").physics("plas").feature("rg4").runCommand("importData");
    model.component("comp1").physics("plas").feature("rg4").label("Hg - Heavy Species Reactions");
    model.component("comp1").physics("plas").create("rg5", "ReactionGroup", 2);
    model.component("comp1").physics("plas").feature("rg5").set("reactionGroupType", "ElectronImpactReactions");
    model.component("comp1").physics("plas").feature("rg5")
         .set("Filepath", "Ar_Hg_plasma_chemistry_import_mixed.txt");
    model.component("comp1").physics("plas").feature("rg5").runCommand("importData");
    model.component("comp1").physics("plas").feature().remove("rg5");
    model.component("comp1").physics("plas").create("rg5", "ReactionGroup", 2);
    model.component("comp1").physics("plas").feature("rg5").set("reactionGroupType", "HeavySpeciesReactions");
    model.component("comp1").physics("plas").feature("rg5")
         .set("Filepath", "Ar_Hg_plasma_chemistry_import_mixed.txt");
    model.component("comp1").physics("plas").feature("rg5").runCommand("importData");
    model.component("comp1").physics("plas").feature("rg5").label("Mixed - Heavy Species Reactions");
    model.component("comp1").physics("plas").create("sr1", "SurfaceReaction", 1);
    model.component("comp1").physics("plas").feature("sr1").set("formula", "Ars=>Ar");
    model.component("comp1").physics("plas").feature("sr1").set("gammaf", "1");
    model.component("comp1").physics("plas").feature("sr1").set("gammai", "0");
    model.component("comp1").physics("plas").feature("sr1").set("ebari", "0");
    model.component("comp1").physics("plas").create("sr2", "SurfaceReaction", 1);
    model.component("comp1").physics("plas").feature("sr2").set("formula", "Ar+=>Ar");
    model.component("comp1").physics("plas").feature("sr2").set("gammaf", "1");
    model.component("comp1").physics("plas").feature("sr2").set("gammai", "0");
    model.component("comp1").physics("plas").feature("sr2").set("ebari", "0");
    model.component("comp1").physics("plas").create("sr3", "SurfaceReaction", 1);
    model.component("comp1").physics("plas").feature("sr3").set("formula", "Hg1=>Hg");
    model.component("comp1").physics("plas").feature("sr3").set("gammaf", "1");
    model.component("comp1").physics("plas").feature("sr3").set("gammai", "0");
    model.component("comp1").physics("plas").feature("sr3").set("ebari", "0");
    model.component("comp1").physics("plas").create("sr4", "SurfaceReaction", 1);
    model.component("comp1").physics("plas").feature("sr4").set("formula", "Hg2=>Hg");
    model.component("comp1").physics("plas").feature("sr4").set("gammaf", "1");
    model.component("comp1").physics("plas").feature("sr4").set("gammai", "0");
    model.component("comp1").physics("plas").feature("sr4").set("ebari", "0");
    model.component("comp1").physics("plas").create("sr5", "SurfaceReaction", 1);
    model.component("comp1").physics("plas").feature("sr5").set("formula", "Hg3=>Hg");
    model.component("comp1").physics("plas").feature("sr5").set("gammaf", "1");
    model.component("comp1").physics("plas").feature("sr5").set("gammai", "0");
    model.component("comp1").physics("plas").feature("sr5").set("ebari", "0");
    model.component("comp1").physics("plas").create("sr6", "SurfaceReaction", 1);
    model.component("comp1").physics("plas").feature("sr6").set("formula", "Hg4=>Hg");
    model.component("comp1").physics("plas").feature("sr6").set("gammaf", "1");
    model.component("comp1").physics("plas").feature("sr6").set("gammai", "0");
    model.component("comp1").physics("plas").feature("sr6").set("ebari", "0");
    model.component("comp1").physics("plas").create("sr7", "SurfaceReaction", 1);
    model.component("comp1").physics("plas").feature("sr7").set("formula", "Hg5=>Hg");
    model.component("comp1").physics("plas").feature("sr7").set("gammaf", "1");
    model.component("comp1").physics("plas").feature("sr7").set("gammai", "0");
    model.component("comp1").physics("plas").feature("sr7").set("ebari", "0");
    model.component("comp1").physics("plas").create("sr8", "SurfaceReaction", 1);
    model.component("comp1").physics("plas").feature("sr8").set("formula", "Hg6=>Hg");
    model.component("comp1").physics("plas").feature("sr8").set("gammaf", "1");
    model.component("comp1").physics("plas").feature("sr8").set("gammai", "0");
    model.component("comp1").physics("plas").feature("sr8").set("ebari", "0");
    model.component("comp1").physics("plas").create("sr9", "SurfaceReaction", 1);
    model.component("comp1").physics("plas").feature("sr9").set("formula", "Hg+=>Hg");
    model.component("comp1").physics("plas").feature("sr9").set("gammaf", "1");
    model.component("comp1").physics("plas").feature("sr9").set("gammai", "0");
    model.component("comp1").physics("plas").feature("sr9").set("ebari", "0");
    model.component("comp1").physics("plas").feature("Hg").set("M", "0.2006");
    model.component("comp1").physics("plas").feature("Hg").set("sigma", "2.969[angstrom]");
    model.component("comp1").physics("plas").feature("Hg").set("epsilonkb", "750");
    model.component("comp1").physics("plas").feature("Hg").set("mu", "0.000");
    model.component("comp1").physics("plas").feature("Hg1").set("M", "0.2006");
    model.component("comp1").physics("plas").feature("Hg1").set("sigma", "2.969[angstrom]");
    model.component("comp1").physics("plas").feature("Hg1").set("epsilonkb", "750");
    model.component("comp1").physics("plas").feature("Hg1").set("mu", "0.000");
    model.component("comp1").physics("plas").feature("Hg2").set("M", "0.2006");
    model.component("comp1").physics("plas").feature("Hg2").set("sigma", "2.969[angstrom]");
    model.component("comp1").physics("plas").feature("Hg2").set("epsilonkb", "750");
    model.component("comp1").physics("plas").feature("Hg2").set("mu", "0.000");
    model.component("comp1").physics("plas").feature("Hg3").set("M", "0.2006");
    model.component("comp1").physics("plas").feature("Hg3").set("sigma", "2.969[angstrom]");
    model.component("comp1").physics("plas").feature("Hg3").set("epsilonkb", "750");
    model.component("comp1").physics("plas").feature("Hg3").set("mu", "0.000");
    model.component("comp1").physics("plas").feature("Hg4").set("M", "0.2006");
    model.component("comp1").physics("plas").feature("Hg4").set("sigma", "2.969[angstrom]");
    model.component("comp1").physics("plas").feature("Hg4").set("epsilonkb", "750");
    model.component("comp1").physics("plas").feature("Hg4").set("mu", "0.000");
    model.component("comp1").physics("plas").feature("Hg5").set("M", "0.2006");
    model.component("comp1").physics("plas").feature("Hg5").set("sigma", "2.969[angstrom]");
    model.component("comp1").physics("plas").feature("Hg5").set("epsilonkb", "750");
    model.component("comp1").physics("plas").feature("Hg5").set("mu", "0.000");
    model.component("comp1").physics("plas").feature("Hg6").set("M", "0.2006");
    model.component("comp1").physics("plas").feature("Hg6").set("sigma", "2.969[angstrom]");
    model.component("comp1").physics("plas").feature("Hg6").set("epsilonkb", "750");
    model.component("comp1").physics("plas").feature("Hg6").set("mu", "0.000");
    model.component("comp1").physics("plas").feature("Hg_1p").set("M", "0.2006");
    model.component("comp1").physics("plas").feature("Hg_1p").set("sigma", "2.969[angstrom]");
    model.component("comp1").physics("plas").feature("Hg_1p").set("epsilonkb", "750");
    model.component("comp1").physics("plas").feature("Hg_1p").set("mu", "0.000");

    model.nodeGroup().create("grp1", "Physics", "plas");
    model.nodeGroup("grp1").placeAfter("rg5");
    model.nodeGroup("grp1").add("e");
    model.nodeGroup("grp1").add("Ar");
    model.nodeGroup("grp1").add("Ars");
    model.nodeGroup("grp1").add("Ar_1p");
    model.nodeGroup("grp1").add("Hg");
    model.nodeGroup("grp1").add("Hg1");
    model.nodeGroup("grp1").add("Hg2");
    model.nodeGroup("grp1").add("Hg3");
    model.nodeGroup("grp1").add("Hg4");
    model.nodeGroup("grp1").add("Hg5");
    model.nodeGroup("grp1").add("Hg6");
    model.nodeGroup("grp1").add("Hg_1p");
    model.nodeGroup("grp1").label("\u7269\u8d28");
    model.nodeGroup().create("grp2", "Physics", "plas");
    model.nodeGroup("grp2").placeAfter("rg5");
    model.nodeGroup("grp2").add("sr1");
    model.nodeGroup("grp2").add("sr2");
    model.nodeGroup("grp2").add("sr3");
    model.nodeGroup("grp2").add("sr4");
    model.nodeGroup("grp2").add("sr5");
    model.nodeGroup("grp2").add("sr6");
    model.nodeGroup("grp2").add("sr7");
    model.nodeGroup("grp2").add("sr8");
    model.nodeGroup("grp2").add("sr9");
    model.nodeGroup("grp2").label("\u8868\u9762\u53cd\u5e94");

    model.component("comp1").physics("plas").feature("sr1").selection().named("sel3");
    model.component("comp1").physics("plas").feature("sr2").selection().named("sel3");
    model.component("comp1").physics("plas").feature("sr3").selection().named("sel3");
    model.component("comp1").physics("plas").feature("sr4").selection().named("sel3");
    model.component("comp1").physics("plas").feature("sr5").selection().named("sel3");
    model.component("comp1").physics("plas").feature("sr6").selection().named("sel3");
    model.component("comp1").physics("plas").feature("sr7").selection().named("sel3");
    model.component("comp1").physics("plas").feature("sr8").selection().named("sel3");
    model.component("comp1").physics("plas").feature("sr9").selection().named("sel3");
    model.component("comp1").physics("plas").feature("Hg").set("x0", 0.05);
    model.component("comp1").physics("plas").feature("Hg1").set("x0", "2E-6");
    model.component("comp1").physics("plas").feature("Hg2").set("x0", "1E-6");
    model.component("comp1").physics("plas").feature("Hg3").set("x0", "5E-6");
    model.component("comp1").physics("plas").feature("Hg4").set("x0", "1E-6");
    model.component("comp1").physics("plas").feature("Hg5").set("x0", "5E-6");
    model.component("comp1").physics("plas").feature("Hg6").set("x0", "1E-6");
    model.component("comp1").physics("plas").feature("Ar").set("FromMassConstraint", true);
    model.component("comp1").physics("plas").feature("Ar_1p").set("n0", "1E16");
    model.component("comp1").physics("plas").feature("Hg_1p").set("InitIon", true);
    model.component("comp1").physics("plas").feature("pes1")
         .set("SpecifyElectronDensityAndEnergy", "FromElectronImpact");
    model.component("comp1").physics("plas").feature("pes1").set("T", "Tinit");
    model.component("comp1").physics("plas").feature("pes1").set("pA", "pinit");
    model.component("comp1").physics("plas").create("gnd1", "Ground", 1);
    model.component("comp1").physics("plas").feature("gnd1").selection().named("sel3");
    model.component("comp1").physics("plas").create("wall1", "WallDriftDiffusion", 1);
    model.component("comp1").physics("plas").feature("wall1").selection().named("sel3");
    model.component("comp1").physics("plas").feature("init1").set("neinit", "1E17");
    model.component("comp1").physics("plas").feature("init1").set("ebarinit", 2);
    model.component("comp1").physics("mf").create("coil1", "Coil", 2);
    model.component("comp1").physics("mf").feature("coil1").selection().named("sel2");
    model.component("comp1").physics("mf").feature("coil1").set("coilGroup", true);
    model.component("comp1").physics("mf").feature("coil1").set("CoilExcitation", "Power");
    model.component("comp1").physics("mf").feature("coil1").set("PCoil", "lamp_power");

    model.component("comp1").material().create("mat1", "Common");
    model.component("comp1").material("mat1").selection().set(5, 6, 7, 8, 9);
    model.component("comp1").material("mat1").propertyGroup("def").set("electricconductivity", new String[]{"6e7"});
    model.component("comp1").material("mat1").propertyGroup("def").set("relpermeability", new String[]{"1"});
    model.component("comp1").material("mat1").propertyGroup("def").set("relpermittivity", new String[]{"1"});
    model.component("comp1").material("mat1").label("\u7ebf\u5708");
    model.component("comp1").material().create("mat2", "Common");
    model.component("comp1").material("mat2").selection().set(1);
    model.component("comp1").material("mat2").propertyGroup("def").set("relpermeability", new String[]{"1e3"});
    model.component("comp1").material("mat2").propertyGroup("def").set("electricconductivity", new String[]{"0"});
    model.component("comp1").material("mat2").propertyGroup("def").set("relpermittivity", new String[]{"1"});
    model.component("comp1").material("mat2").label("\u94c1\u6c27\u4f53");
    model.component("comp1").material().create("mat3", "Common");
    model.component("comp1").material("mat3").selection().set(2);
    model.component("comp1").material("mat3").propertyGroup("def").set("relpermeability", new String[]{"1"});
    model.component("comp1").material("mat3").propertyGroup("def").set("electricconductivity", new String[]{"0"});
    model.component("comp1").material("mat3").propertyGroup("def").set("relpermittivity", new String[]{"1"});
    model.component("comp1").material("mat3").label("\u7a7a\u6c14");
    model.component("comp1").material().create("mat4", "Common");
    model.component("comp1").material("mat4").selection().set(3);
    model.component("comp1").material("mat4").propertyGroup("def").set("relpermeability", new String[]{"1"});
    model.component("comp1").material("mat4").propertyGroup("def").set("electricconductivity", new String[]{"0"});
    model.component("comp1").material("mat4").propertyGroup("def").set("relpermittivity", new String[]{"4.2"});
    model.component("comp1").material("mat4").label("\u7535\u4ecb\u8d28");

    model.component("comp1").mesh("mesh1").autoMeshSize(2);
    model.component("comp1").mesh("mesh1").create("edg1", "Edge");
    model.component("comp1").mesh("mesh1").feature("edg1").selection().named("sel1");
    model.component("comp1").mesh("mesh1").feature("edg1").create("dis1", "Distribution");
    model.component("comp1").mesh("mesh1").feature("edg1").feature("dis1").selection().named("sel1");
    model.component("comp1").mesh("mesh1").feature("edg1").feature("dis1").set("type", "predefined");
    model.component("comp1").mesh("mesh1").feature("edg1").feature("dis1").set("elemcount", 30);
    model.component("comp1").mesh("mesh1").feature("edg1").feature("dis1").set("elemratio", 6);
    model.component("comp1").mesh("mesh1").feature("edg1").feature("dis1").set("growthrate", "exponential");
    model.component("comp1").mesh("mesh1").feature("edg1").feature("dis1").set("symmetric", true);
    model.component("comp1").mesh("mesh1").create("map1", "Map");
    model.component("comp1").mesh("mesh1").feature("map1").selection().geom("geom1", 2);
    model.component("comp1").mesh("mesh1").feature("map1").selection().named("sel2");
    model.component("comp1").mesh("mesh1").create("edg2", "Edge");
    model.component("comp1").mesh("mesh1").feature("edg2").selection().set(8, 27, 35);
    model.component("comp1").mesh("mesh1").feature("edg2").create("size1", "Size");
    model.component("comp1").mesh("mesh1").feature("edg2").feature("size1").set("custom", true);
    model.component("comp1").mesh("mesh1").feature("edg2").feature("size1").set("hmaxactive", true);
    model.component("comp1").mesh("mesh1").feature("edg2").feature("size1").set("hmax", "5e-4");
    model.component("comp1").mesh("mesh1").create("edg3", "Edge");
    model.component("comp1").mesh("mesh1").feature("edg3").selection().set(36, 37, 38);
    model.component("comp1").mesh("mesh1").feature("edg3").create("size1", "Size");
    model.component("comp1").mesh("mesh1").feature("edg3").feature("size1").set("custom", true);
    model.component("comp1").mesh("mesh1").feature("edg3").feature("size1").set("hmaxactive", true);
    model.component("comp1").mesh("mesh1").feature("edg3").feature("size1").set("hmax", "1e-3");
    model.component("comp1").mesh("mesh1").create("bl1", "BndLayer");
    model.component("comp1").mesh("mesh1").feature("bl1").create("blp", "BndLayerProp");
    model.component("comp1").mesh("mesh1").feature("bl1").selection().geom("geom1", 2);
    model.component("comp1").mesh("mesh1").feature("bl1").selection().set(4);
    model.component("comp1").mesh("mesh1").feature("bl1").set("smoothtransition", false);
    model.component("comp1").mesh("mesh1").feature("bl1").feature("blp").selection().named("sel3");
    model.component("comp1").mesh("mesh1").feature("bl1").feature("blp").set("blstretch", 1.1);
    model.component("comp1").mesh("mesh1").feature("bl1").feature("blp").set("inittype", "blhmin");
    model.component("comp1").mesh("mesh1").feature("bl1").feature("blp").set("blhmin", "2E-5");
    model.component("comp1").mesh("mesh1").create("ftri1", "FreeTri");
    model.component("comp1").mesh("mesh1").run();

    model.study("std1").feature("ftrans").set("freq", "2[MHz]");
    model.study("std1").feature("ftrans").set("tlist", "0 10^{range(-8,2.6505149978319906,-2.6989700043360187)}");
    model.study("std1").createAutoSequences("all");

    model.sol("sol1").runAll();

    model.result().create("pg1", "PlotGroup2D");
    model.result("pg1").set("data", "dset1");
    model.result("pg1").setIndex("looplevel", 4, 0);
    model.result("pg1").create("surf1", "Surface");
    model.result("pg1").feature("surf1").set("expr", new String[]{"plas.ne"});
    model.result().create("pg2", "PlotGroup2D");
    model.result("pg2").set("data", "dset1");
    model.result("pg2").setIndex("looplevel", 4, 0);
    model.result("pg2").create("surf1", "Surface");
    model.result("pg2").feature("surf1").set("expr", new String[]{"plas.Te"});
    model.result().create("pg3", "PlotGroup2D");
    model.result("pg3").set("data", "dset1");
    model.result("pg3").setIndex("looplevel", 4, 0);
    model.result("pg3").create("surf1", "Surface");
    model.result("pg3").feature("surf1").set("expr", new String[]{"V"});
    model.result("pg1").feature("surf1").set("colortable", "Prism");
    model.result("pg2").feature("surf1").set("colortable", "Prism");
    model.result("pg3").feature("surf1").set("colortable", "Dipole");
    model.result("pg1").label("\u7535\u5b50\u5bc6\u5ea6 (plas)");
    model.result("pg2").label("\u7535\u5b50\u6e29\u5ea6 (plas)");
    model.result("pg3").label("\u7535\u52bf (plas)");
    model.result().create("pg4", "PlotGroup2D");
    model.result("pg4").label("\u78c1\u901a\u5bc6\u5ea6 (mf)");
    model.result("pg4").set("dataisaxisym", "off");
    model.result("pg4").set("frametype", "spatial");
    model.result("pg4").set("showlegendsmaxmin", true);
    model.result("pg4").feature().create("surf1", "Surface");
    model.result("pg4").feature("surf1").set("showsolutionparams", "on");
    model.result("pg4").feature("surf1").set("solutionparams", "parent");
    model.result("pg4").feature("surf1").set("expr", "mf.normB");
    model.result("pg4").feature("surf1").set("colortabletrans", "nonlinear");
    model.result("pg4").feature("surf1").set("colorcalibration", -0.8);
    model.result("pg4").feature("surf1").set("showsolutionparams", "on");
    model.result("pg4").feature("surf1").set("data", "parent");
    model.result("pg4").feature().create("str1", "Streamline");
    model.result("pg4").feature("str1").set("showsolutionparams", "on");
    model.result("pg4").feature("str1").set("solutionparams", "parent");
    model.result("pg4").feature("str1").set("expr", new String[]{"mf.Br", "mf.Bz"});
    model.result("pg4").feature("str1").set("titletype", "none");
    model.result("pg4").feature("str1").set("posmethod", "uniform");
    model.result("pg4").feature("str1").set("udist", 0.03);
    model.result("pg4").feature("str1").set("maxlen", 0.4);
    model.result("pg4").feature("str1").set("maxsteps", 5000);
    model.result("pg4").feature("str1").set("maxtime", Double.POSITIVE_INFINITY);
    model.result("pg4").feature("str1").set("inheritcolor", false);
    model.result("pg4").feature("str1").set("showsolutionparams", "on");
    model.result("pg4").feature("str1").set("maxtime", Double.POSITIVE_INFINITY);
    model.result("pg4").feature("str1").set("showsolutionparams", "on");
    model.result("pg4").feature("str1").set("maxtime", Double.POSITIVE_INFINITY);
    model.result("pg4").feature("str1").set("showsolutionparams", "on");
    model.result("pg4").feature("str1").set("maxtime", Double.POSITIVE_INFINITY);
    model.result("pg4").feature("str1").set("showsolutionparams", "on");
    model.result("pg4").feature("str1").set("maxtime", Double.POSITIVE_INFINITY);
    model.result("pg4").feature("str1").set("data", "parent");
    model.result("pg4").feature("str1").selection().geom("geom1", 1);
    model.result("pg4").feature("str1").selection()
         .set(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38);
    model.result("pg4").feature("str1").set("inheritplot", "surf1");
    model.result("pg4").feature("str1").feature().create("col1", "Color");
    model.result("pg4").feature("str1").feature("col1").set("expr", "mf.normB");
    model.result("pg4").feature("str1").feature("col1").set("colortable", "PrismDark");
    model.result("pg4").feature("str1").feature("col1").set("colorlegend", false);
    model.result("pg4").feature("str1").feature("col1").set("colortabletrans", "nonlinear");

    return model;
  }

  public static Model run2(Model model) {
    model.result("pg4").feature("str1").feature("col1").set("colorcalibration", -0.8);
    model.result("pg4").feature("str1").feature().create("filt1", "Filter");
    model.result("pg4").feature("str1").feature("filt1").set("expr", "!isScalingSystemDomain");
    model.result("pg4").feature().create("con1", "Contour");
    model.result("pg4").feature("con1").set("showsolutionparams", "on");
    model.result("pg4").feature("con1").set("solutionparams", "parent");
    model.result("pg4").feature("con1").set("expr", "mf.Psi");
    model.result("pg4").feature("con1").set("titletype", "none");
    model.result("pg4").feature("con1").set("number", 10);
    model.result("pg4").feature("con1").set("levelrounding", false);
    model.result("pg4").feature("con1").set("coloring", "uniform");
    model.result("pg4").feature("con1").set("colorlegend", false);
    model.result("pg4").feature("con1").set("color", "custom");
    model.result("pg4").feature("con1")
         .set("customcolor", new double[]{0.3764705955982208, 0.3764705955982208, 0.3764705955982208});
    model.result("pg4").feature("con1").set("resolution", "fine");
    model.result("pg4").feature("con1").set("inheritcolor", false);
    model.result("pg4").feature("con1").set("showsolutionparams", "on");
    model.result("pg4").feature("con1").set("data", "parent");
    model.result("pg4").feature("con1").set("inheritplot", "surf1");
    model.result("pg4").feature("con1").feature().create("filt1", "Filter");
    model.result("pg4").feature("con1").feature("filt1").set("expr", "!isScalingSystemDomain");
    model.result().dataset().create("rev1", "Revolve2D");
    model.result().dataset("rev1").set("data", "none");
    model.result().dataset("rev1").set("startangle", -90);
    model.result().dataset("rev1").set("revangle", 225);
    model.result().dataset("rev1").set("data", "dset1");
    model.result().create("pg5", "PlotGroup3D");
    model.result("pg5").label("\u78c1\u901a\u5bc6\u5ea6\uff0c\u56de\u8f6c\u51e0\u4f55 (mf)");
    model.result("pg5").set("frametype", "spatial");
    model.result("pg5").set("showlegendsmaxmin", true);
    model.result("pg5").feature().create("vol1", "Volume");
    model.result("pg5").feature("vol1").set("showsolutionparams", "on");
    model.result("pg5").feature("vol1").set("solutionparams", "parent");
    model.result("pg5").feature("vol1").set("expr", "mf.normB");
    model.result("pg5").feature("vol1").set("colortabletrans", "nonlinear");
    model.result("pg5").feature("vol1").set("colorcalibration", -0.8);
    model.result("pg5").feature("vol1").set("showsolutionparams", "on");
    model.result("pg5").feature("vol1").set("data", "parent");
    model.result("pg5").feature().create("con1", "Contour");
    model.result("pg5").feature("con1").set("showsolutionparams", "on");
    model.result("pg5").feature("con1").set("solutionparams", "parent");
    model.result("pg5").feature("con1").set("expr", "mf.Psi");
    model.result("pg5").feature("con1").set("titletype", "none");
    model.result("pg5").feature("con1").set("number", 10);
    model.result("pg5").feature("con1").set("levelrounding", false);
    model.result("pg5").feature("con1").set("coloring", "uniform");
    model.result("pg5").feature("con1").set("colorlegend", false);
    model.result("pg5").feature("con1").set("color", "custom");
    model.result("pg5").feature("con1")
         .set("customcolor", new double[]{0.3764705955982208, 0.3764705955982208, 0.3764705955982208});
    model.result("pg5").feature("con1").set("resolution", "fine");
    model.result("pg5").feature("con1").set("inheritcolor", false);
    model.result("pg5").feature("con1").set("showsolutionparams", "on");
    model.result("pg5").feature("con1").set("data", "parent");
    model.result("pg5").feature("con1").set("inheritplot", "vol1");
    model.result("pg5").feature("con1").feature().create("filt1", "Filter");
    model.result("pg5").feature("con1").feature("filt1").set("expr", "!isScalingSystemDomain");
    model.result("pg5").feature("con1").feature("filt1").set("shownodespec", "on");
    model.result("pg1").run();
    model.result("pg2").run();
    model.result("pg3").run();
    model.result().create("pg6", "PlotGroup2D");
    model.result("pg6").run();
    model.result("pg6").label("\u529f\u7387\u6c89\u79ef");
    model.result("pg6").create("surf1", "Surface");
    model.result("pg6").feature("surf1").set("expr", "mf.Qrh");
    model.result("pg6").feature("surf1").set("descr", "\u4f53\u79ef\u635f\u8017\u5bc6\u5ea6\uff0c\u7535");
    model.result("pg6").feature("surf1").set("colortable", "ThermalWave");
    model.result("pg6").feature("surf1").create("sel1", "Selection");
    model.result("pg6").feature("surf1").feature("sel1").selection().set(4);
    model.result("pg6").run();
    model.result().create("pg7", "PlotGroup2D");
    model.result("pg7").run();
    model.result("pg7").label("\u57fa\u6001\u6c5e\u6469\u5c14\u5206\u6570");
    model.result("pg7").create("surf1", "Surface");
    model.result("pg7").feature("surf1").set("expr", "plas.x_wHg");
    model.result("pg7").feature("surf1").set("descr", "\u6469\u5c14\u5206\u6570");
    model.result("pg7").run();
    model.result().create("pg8", "PlotGroup2D");
    model.result("pg8").run();
    model.result("pg8").label("\u6c5e\u79bb\u5b50\u6570\u5bc6\u5ea6");
    model.result("pg8").create("surf1", "Surface");
    model.result("pg8").feature("surf1").set("expr", "plas.n_wHg_1p");
    model.result("pg8").feature("surf1").set("descr", "\u6570\u5bc6\u5ea6");
    model.result("pg8").run();
    model.result().create("pg9", "PlotGroup2D");
    model.result("pg9").run();
    model.result("pg9").label("\u6fc0\u53d1\u6c5e\u7684\u6469\u5c14\u5206\u6570 2");
    model.result("pg9").create("surf1", "Surface");
    model.result("pg9").feature("surf1").set("expr", "plas.x_wHg2");
    model.result("pg9").feature("surf1").set("descr", "\u6469\u5c14\u5206\u6570");
    model.result("pg9").run();
    model.result().create("pg10", "PlotGroup2D");
    model.result("pg10").run();
    model.result("pg10").label("\u6fc0\u53d1\u6c5e\u7684\u6469\u5c14\u5206\u6570 4");
    model.result("pg10").create("surf1", "Surface");
    model.result("pg10").feature("surf1").set("expr", "plas.x_wHg4");
    model.result("pg10").feature("surf1").set("descr", "\u6469\u5c14\u5206\u6570");
    model.result("pg10").run();

    model.title("\u65e0\u6781\u706f");

    model
         .description("\u672c\u4f8b\u7814\u7a76\u65e0\u6781\u706f\u7684\u53d1\u5c04\u5149\u8c31\u4ee5\u53ca\u7535\u80fd\u8f6c\u5316\u4e3a\u5149\u80fd\u7684\u673a\u5236\u3002\u8be5\u6a21\u578b\u672c\u8d28\u4e0a\u662f\u4e00\u4e2a\u53d8\u538b\u5668\uff0c\u5176\u4e2d\u4f7f\u7528\u7b49\u79bb\u5b50\u4f53\u5145\u5f53\u6b21\u7ea7\u7ebf\u5708\uff0c\u6db5\u76d6\u4e86 96\u00a0\u4e2a\u53cd\u5e94\u548c 12\u00a0\u79cd\u7269\u8d28\u3002");

    model.mesh().clearMeshes();

    model.sol("sol1").clearSolutionData();

    model.label("electrodeless_lamp.mph");

    return model;
  }

  public static void main(String[] args) {
    Model model = run();
    run2(model);
  }

}
