/*
 * icp_coil_optimization.java
 */

import com.comsol.model.*;
import com.comsol.model.util.*;

/** Model exported on Apr 30 2026, 12:06 by COMSOL 6.3.0.290. */
public class icp_coil_optimization {

  public static Model run() {
    Model model = ModelUtil.create("Model");

    model
         .modelPath("D:\\Program Files\\COMSOL\\COMSOL63\\Multiphysics\\applications\\Plasma_Module\\Inductively_Coupled_Plasmas");

    model.component().create("comp1", true);

    model.component("comp1").geom().create("geom1", 2);
    model.component("comp1").geom("geom1").axisymmetric(true);

    model.component("comp1").mesh().create("mesh1");

    model.component("comp1").physics().create("plas", "ColdPlasma", "geom1");
    model.component("comp1").physics().create("mf", "InductionCurrents", "geom1");
    model.component("comp1").physics("mf").prop("ShapeProperty").set("order_magneticvectorpotential", "1");
    model.component("comp1").physics("mf").create("alf1", "AmperesLawFluid");
    model.component("comp1").physics("mf").feature("alf1").selection().all();

    model.component("comp1").multiphysics().create("pcc1", "PlasmaConductivityMultiphysicsCoupling", 2);
    model.component("comp1").multiphysics("pcc1").set("elm_physics", "mf");
    model.component("comp1").multiphysics("pcc1").set("plas_physics", "plas");
    model.component("comp1").multiphysics().create("ehs1", "ElectronHeatSourceMultiphysicsCoupling", 2);
    model.component("comp1").multiphysics("ehs1").set("elm_physics", "mf");
    model.component("comp1").multiphysics("ehs1").set("plas_physics", "plas");

    model.study().create("std1");
    model.study("std1").create("fstat", "FrequencyStationary");
    model.study("std1").feature("fstat").set("freq", "1000000");
    model.study("std1").feature("fstat").set("solnum", "auto");
    model.study("std1").feature("fstat").set("notsolnum", "auto");
    model.study("std1").feature("fstat").set("outputmap", new String[]{});
    model.study("std1").feature("fstat").set("ngenAUX", "1");
    model.study("std1").feature("fstat").set("goalngenAUX", "1");
    model.study("std1").feature("fstat").set("ngenAUX", "1");
    model.study("std1").feature("fstat").set("goalngenAUX", "1");
    model.study("std1").feature("fstat").setSolveFor("/physics/plas", true);
    model.study("std1").feature("fstat").setSolveFor("/physics/mf", true);
    model.study("std1").feature("fstat").setSolveFor("/multiphysics/pcc1", true);
    model.study("std1").feature("fstat").setSolveFor("/multiphysics/ehs1", true);

//    To import content from file, use:
//    model.param().loadFile("FILENAME");
    model.param().set("Psp", "1500[W]", "\u529f\u7387\u8f93\u5165");
    model.param().set("mueN", "4E24[1/(m*V*s)]", "\u7ea6\u5316\u7535\u5b50\u8fc1\u79fb\u7387");
    model.param().set("T0", "300[K]", "\u6c14\u4f53\u6e29\u5ea6");
    model.param().set("p0", "0.02[torr]", "\u6c14\u538b");
    model.param().set("Wc", "30[cm]", "\u8154\u5bbd\u5ea6");
    model.param().set("Hc", "22[cm]", "\u8154\u9ad8\u5ea6");
    model.param().set("Ws", "15[cm]", "\u57fa\u677f\u5bbd\u5ea6");
    model.param().set("Hs", "2[cm]", "\u57fa\u677f\u9ad8\u5ea6");
    model.param().set("Wd", "5[cm]", "\u4ecb\u8d28\u5757\u5bbd\u5ea6");
    model.param().set("Hd", "Hs", "\u4ecb\u8d28\u5757\u9ad8\u5ea6");
    model.param().set("Ww", "Wc", "\u4ecb\u7535\u7a97\u5bbd\u5ea6");
    model.param().set("Hw", "2[cm]", "\u4ecb\u7535\u7a97\u9ad8\u5ea6");
    model.param().set("dplasma", "10[cm]", "\u57fa\u677f\u4e0e\u7a97\u4e4b\u95f4\u7684\u8ddd\u79bb");
    model.param().set("Lcoil", "0.7[cm]", "\u7ebf\u5708\u6a2a\u622a\u9762\u957f\u5ea6");
    model.param().set("rc", "5[cm]", "\u7ebf\u5708\u534a\u5f84");
    model.param().set("Zcoil", "dplasma+Hw+Hs", "\u7ebf\u5708\u9ad8\u5ea6");
    model.param().set("nCoil", "4", "\u7ebf\u5708\u6570");
    model.param().set("coilSpace", "5[cm]", "\u7ebf\u5708\u95f4\u8ddd");

    model.component("comp1").geom("geom1").lengthUnit("cm");
    model.component("comp1").geom("geom1").create("r1", "Rectangle");
    model.component("comp1").geom("geom1").feature("r1").set("size", new String[]{"Wc", "Hc"});
    model.component("comp1").geom("geom1").run("r1");
    model.component("comp1").geom("geom1").create("r2", "Rectangle");
    model.component("comp1").geom("geom1").feature("r2").set("size", new String[]{"Ws", "Hs"});
    model.component("comp1").geom("geom1").feature("r2").set("selresult", true);
    model.component("comp1").geom("geom1").run("r2");
    model.component("comp1").geom("geom1").create("r3", "Rectangle");
    model.component("comp1").geom("geom1").feature("r3").set("size", new String[]{"Wd", "Hd"});
    model.component("comp1").geom("geom1").feature("r3").set("pos", new String[]{"Ws", "0"});
    model.component("comp1").geom("geom1").feature("r3").set("selresult", true);
    model.component("comp1").geom("geom1").run("r3");
    model.component("comp1").geom("geom1").create("r4", "Rectangle");
    model.component("comp1").geom("geom1").feature("r4").set("size", new String[]{"Ww", "Hw"});
    model.component("comp1").geom("geom1").feature("r4").set("pos", new String[]{"0", "Hs+dplasma"});
    model.component("comp1").geom("geom1").feature("r4").set("selresult", true);
    model.component("comp1").geom("geom1").run("r4");
    model.component("comp1").geom("geom1").create("r5", "Rectangle");
    model.component("comp1").geom("geom1").feature("r5").set("size", new String[]{"Ww", "Hs+dplasma"});
    model.component("comp1").geom("geom1").feature("r5").set("selresult", true);
    model.component("comp1").geom("geom1").run("r5");
    model.component("comp1").geom("geom1").create("r6", "Rectangle");
    model.component("comp1").geom("geom1").feature("r6").set("size", new String[]{"Ww", "Hc-dplasma-Hw-Hs"});
    model.component("comp1").geom("geom1").feature("r6").set("pos", new String[]{"0", "Hs+dplasma+Hw"});
    model.component("comp1").geom("geom1").feature("r6").set("selresult", true);
    model.component("comp1").geom("geom1").run("r6");
    model.component("comp1").geom("geom1").create("r7", "Rectangle");
    model.component("comp1").geom("geom1").feature("r7").label("\u7ebf\u5708");
    model.component("comp1").geom("geom1").feature("r7").set("size", new String[]{"Lcoil", "Lcoil"});
    model.component("comp1").geom("geom1").feature("r7").set("pos", new String[]{"rc", "Zcoil"});
    model.component("comp1").geom("geom1").feature("r7").set("selresult", true);
    model.component("comp1").geom("geom1").run("r7");
    model.component("comp1").geom("geom1").create("ls1", "LineSegment");
    model.component("comp1").geom("geom1").feature("ls1").set("specify1", "coord");
    model.component("comp1").geom("geom1").feature("ls1").set("coord1", new int[]{0, 7});
    model.component("comp1").geom("geom1").feature("ls1").set("specify2", "coord");
    model.component("comp1").geom("geom1").feature("ls1").set("coord2", new int[]{18, 7});
    model.component("comp1").geom("geom1").run("ls1");
    model.component("comp1").geom("geom1").create("arr1", "Array");
    model.component("comp1").geom("geom1").feature("arr1").selection("input").named("r7");
    model.component("comp1").geom("geom1").feature("arr1").set("fullsize", new String[]{"nCoil", "1"});
    model.component("comp1").geom("geom1").feature("arr1").set("displ", new String[]{"coilSpace", "0"});
    model.component("comp1").geom("geom1").run("fin");
    model.component("comp1").geom("geom1").create("difsel1", "DifferenceSelection");
    model.component("comp1").geom("geom1").feature("difsel1").label("\u7b49\u79bb\u5b50\u4f53");
    model.component("comp1").geom("geom1").feature("difsel1").set("add", new String[]{"r5"});
    model.component("comp1").geom("geom1").feature("difsel1").set("subtract", new String[]{"r2", "r3"});
    model.component("comp1").geom("geom1").run("difsel1");
    model.component("comp1").geom("geom1").create("boxsel1", "BoxSelection");
    model.component("comp1").geom("geom1").feature("boxsel1").set("entitydim", 1);
    model.component("comp1").geom("geom1").feature("boxsel1").set("xmax", "eps");
    model.component("comp1").geom("geom1").feature("boxsel1").set("condition", "inside");
    model.component("comp1").geom("geom1").feature("boxsel1").label("\u8f74");
    model.component("comp1").geom("geom1").run("boxsel1");
    model.component("comp1").geom("geom1").create("adjsel1", "AdjacentSelection");
    model.component("comp1").geom("geom1").feature("adjsel1").set("input", new String[]{"difsel1"});
    model.component("comp1").geom("geom1").run("adjsel1");
    model.component("comp1").geom("geom1").create("difsel2", "DifferenceSelection");
    model.component("comp1").geom("geom1").feature("difsel2").label("\u58c1");
    model.component("comp1").geom("geom1").feature("difsel2").set("entitydim", 1);
    model.component("comp1").geom("geom1").feature("difsel2").set("add", new String[]{"adjsel1"});
    model.component("comp1").geom("geom1").feature("difsel2").set("subtract", new String[]{"boxsel1"});
    model.component("comp1").geom("geom1").run("difsel2");
    model.component("comp1").geom("geom1").create("adjsel2", "AdjacentSelection");
    model.component("comp1").geom("geom1").feature("adjsel2").label("\u7ebf\u5708\u7684\u76f8\u90bb\u57df");
    model.component("comp1").geom("geom1").feature("adjsel2").set("input", new String[]{"r7"});
    model.component("comp1").geom("geom1").feature("adjsel2").set("outputdim", 2);
    model.component("comp1").geom("geom1").run("adjsel2");
    model.component("comp1").geom("geom1").create("adjsel3", "AdjacentSelection");
    model.component("comp1").geom("geom1").feature("adjsel3").label("\u7ebf\u5708\u8fb9\u754c");
    model.component("comp1").geom("geom1").feature("adjsel3").set("input", new String[]{"r7"});
    model.component("comp1").geom("geom1").run("adjsel3");
    model.component("comp1").geom("geom1").create("unisel1", "UnionSelection");
    model.component("comp1").geom("geom1").feature("unisel1").label("\u78c1\u573a");
    model.component("comp1").geom("geom1").feature("unisel1")
         .set("input", new String[]{"r4", "r7", "difsel1", "adjsel2"});
    model.component("comp1").geom("geom1").run("unisel1");
    model.component("comp1").geom("geom1").create("intsel1", "IntersectionSelection");
    model.component("comp1").geom("geom1").feature("intsel1").set("entitydim", 1);
    model.component("comp1").geom("geom1").feature("intsel1").set("input", new String[]{"r4", "r6"});
    model.component("comp1").geom("geom1").feature("intsel1").label("\u9876\u90e8\u7535\u4ecb\u8d28");
    model.component("comp1").geom("geom1").run("intsel1");
    model.component("comp1").geom("geom1").create("difsel3", "DifferenceSelection");
    model.component("comp1").geom("geom1").feature("difsel3").set("entitydim", 1);
    model.component("comp1").geom("geom1").feature("difsel3").set("add", new String[]{"intsel1"});
    model.component("comp1").geom("geom1").feature("difsel3").set("subtract", new String[]{"r7"});
    model.component("comp1").geom("geom1").feature("difsel3").label("\u8f8a\u652f\u627f");
    model.component("comp1").geom("geom1").run("difsel3");

    model.component("comp1").material().create("mat1", "Common");
    model.component("comp1").material("mat1").selection().named("geom1_r7_dom");
    model.component("comp1").material("mat1").propertyGroup("def").set("relpermeability", new String[]{"1"});
    model.component("comp1").material("mat1").propertyGroup("def").set("electricconductivity", new String[]{"6e7"});
    model.component("comp1").material("mat1").propertyGroup("def").set("relpermittivity", new String[]{"1"});
    model.component("comp1").material().create("mat2", "Common");
    model.component("comp1").material("mat2").selection().set(2, 4);
    model.component("comp1").material("mat2").propertyGroup("def").set("relpermeability", new String[]{"1"});
    model.component("comp1").material("mat2").propertyGroup("def").set("electricconductivity", new String[]{"0"});
    model.component("comp1").material("mat2").propertyGroup("def").set("relpermittivity", new String[]{"1"});
    model.component("comp1").material().create("mat3", "Common");
    model.component("comp1").material("mat3").selection().set(3);
    model.component("comp1").material("mat3").propertyGroup("def").set("relpermeability", new String[]{"1"});
    model.component("comp1").material("mat3").propertyGroup("def").set("electricconductivity", new String[]{"0"});
    model.component("comp1").material("mat3").propertyGroup("def").set("relpermittivity", new String[]{"4.2"});

    model.component("comp1").physics("plas").selection().named("geom1_difsel1");
    model.component("comp1").physics("plas").prop("ElectronProperties").set("ReducedProps", true);
    model.component("comp1").physics("plas").create("xsec1", "CrossSectionImport", -1);
    model.component("comp1").physics("plas").feature("xsec1").set("Filepath", "Ar_xsecs.txt");
    model.component("comp1").physics("plas").feature("xsec1").runCommand("importData");
    model.component("comp1").physics("plas").create("rxn1", "Reaction", 2);
    model.component("comp1").physics("plas").feature("rxn1").set("formula", "Ars+Ars=>e+Ar+Ar+");
    model.component("comp1").physics("plas").feature("rxn1").set("kf", "3.734E8");
    model.component("comp1").physics("plas").feature().duplicate("rxn2", "rxn1");
    model.component("comp1").physics("plas").feature("rxn2").set("formula", "Ars+Ar=>Ar+Ar");
    model.component("comp1").physics("plas").feature("rxn2").set("kf", 1807);
    model.component("comp1").physics("plas").feature("Ar").set("FromMassConstraint", true);
    model.component("comp1").physics("plas").feature("Ar").set("PresetSpeciesData", "Ar");
    model.component("comp1").physics("plas").feature("Ars").set("PresetSpeciesData", "Ar");
    model.component("comp1").physics("plas").feature("Ar_1p").set("InitIon", true);
    model.component("comp1").physics("plas").feature("Ar_1p").set("PresetSpeciesData", "Ar");
    model.component("comp1").physics("plas").feature("pes1").set("T", "T0");
    model.component("comp1").physics("plas").feature("pes1").set("pA", "p0");
    model.component("comp1").physics("plas").feature("pes1")
         .set("muN", new String[]{"mueN", "0", "0", "0", "mueN", "0", "0", "0", "mueN"});
    model.component("comp1").physics("plas").feature("init1").set("neinit", "1E16[1/m^3]");
    model.component("comp1").physics("plas").feature("init1").set("ebarinit", "2[V]");
    model.component("comp1").physics("plas").create("wall1", "WallDriftDiffusion", 1);
    model.component("comp1").physics("plas").feature("wall1").selection().named("geom1_difsel2");
    model.component("comp1").physics("plas").feature("wall1").set("re", 0.2);
    model.component("comp1").physics("plas").create("gnd1", "Ground", 1);
    model.component("comp1").physics("plas").feature("gnd1").selection().named("geom1_difsel2");
    model.component("comp1").physics("plas").create("sr1", "SurfaceReaction", 1);
    model.component("comp1").physics("plas").feature("sr1").set("formula", "Ars=>Ar");
    model.component("comp1").physics("plas").feature("sr1").selection().named("geom1_difsel2");
    model.component("comp1").physics("plas").feature().duplicate("sr2", "sr1");
    model.component("comp1").physics("plas").feature("sr2").set("formula", "Ar+=>Ar");
    model.component("comp1").physics("mf").selection().named("geom1_unisel1");
    model.component("comp1").physics("mf").create("coil1", "Coil", 2);
    model.component("comp1").physics("mf").feature("coil1").selection().named("geom1_r7_dom");
    model.component("comp1").physics("mf").feature("coil1").set("coilGroup", true);
    model.component("comp1").physics("mf").feature("coil1").set("CoilExcitation", "Power");
    model.component("comp1").physics("mf").feature("coil1").set("PCoil", "Psp");

    model.component("comp1").mesh("mesh1").contribute("physics/plas", false);
    model.component("comp1").mesh("mesh1").contribute("physics/mf", false);
    model.component("comp1").mesh("mesh1").contribute("multiphysics/pcc1", false);
    model.component("comp1").mesh("mesh1").contribute("multiphysics/ehs1", false);
    model.component("comp1").mesh("mesh1").automatic(false);
    model.component("comp1").mesh("mesh1").feature("size").set("hauto", 3);
    model.component("comp1").mesh("mesh1").feature("ftri1").selection().geom("geom1", 2);
    model.component("comp1").mesh("mesh1").feature("ftri1").selection().named("geom1_difsel1");
    model.component("comp1").mesh("mesh1").feature("ftri1").create("size1", "Size");
    model.component("comp1").mesh("mesh1").feature("ftri1").feature("size1").set("hauto", 3);
    model.component("comp1").mesh("mesh1").create("edg1", "Edge");
    model.component("comp1").mesh("mesh1").feature("edg1").selection().named("geom1_difsel2");
    model.component("comp1").mesh("mesh1").feature("edg1").create("size1", "Size");
    model.component("comp1").mesh("mesh1").feature("edg1").feature("size1").set("custom", true);
    model.component("comp1").mesh("mesh1").feature("edg1").feature("size1").set("hmaxactive", true);
    model.component("comp1").mesh("mesh1").feature("edg1").feature("size1").set("hmax", "2E-3[m]");
    model.component("comp1").mesh("mesh1").create("bl1", "BndLayer");
    model.component("comp1").mesh("mesh1").feature("bl1").create("blp", "BndLayerProp");
    model.component("comp1").mesh("mesh1").feature("bl1").selection().geom("geom1", 2);
    model.component("comp1").mesh("mesh1").feature("bl1").selection().named("geom1_difsel1");
    model.component("comp1").mesh("mesh1").feature("bl1").set("smoothtransition", false);
    model.component("comp1").mesh("mesh1").feature("bl1").feature("blp").selection().named("geom1_difsel2");
    model.component("comp1").mesh("mesh1").feature("bl1").feature("blp").set("blnlayers", 5);
    model.component("comp1").mesh("mesh1").feature("bl1").feature("blp").set("blstretch", 1.4);
    model.component("comp1").mesh("mesh1").create("map1", "Map");
    model.component("comp1").mesh("mesh1").feature("map1").selection().geom("geom1", 2);
    model.component("comp1").mesh("mesh1").feature("map1").selection().named("geom1_r7_dom");
    model.component("comp1").mesh("mesh1").feature("map1").create("dis1", "Distribution");
    model.component("comp1").mesh("mesh1").feature("map1").feature("dis1").selection().named("geom1_adjsel3");
    model.component("comp1").mesh("mesh1").feature("map1").feature("dis1").set("type", "predefined");
    model.component("comp1").mesh("mesh1").feature("map1").feature("dis1").set("elemcount", 25);
    model.component("comp1").mesh("mesh1").feature("map1").feature("dis1").set("elemratio", 20);
    model.component("comp1").mesh("mesh1").feature("map1").feature("dis1").set("symmetric", true);
    model.component("comp1").mesh("mesh1").create("ftri2", "FreeTri");
    model.component("comp1").mesh("mesh1").feature().move("edg1", 1);
    model.component("comp1").mesh("mesh1").run();

    model.study("std1").createAutoSequences("sol");
    model.study("std1").createAutoSequences("jobs");

    model.sol("sol1").runFromTo("st1", "v1");

    model.result().create("pg1", "PlotGroup2D");
    model.result("pg1").set("data", "dset1");
    model.result("pg1").setIndex("looplevel", 1, 0);
    model.result("pg1").create("surf1", "Surface");
    model.result("pg1").feature("surf1").set("expr", new String[]{"plas.ne"});
    model.result().create("pg2", "PlotGroup2D");
    model.result("pg2").set("data", "dset1");
    model.result("pg2").setIndex("looplevel", 1, 0);
    model.result("pg2").create("surf1", "Surface");
    model.result("pg2").feature("surf1").set("expr", new String[]{"plas.Te"});
    model.result().create("pg3", "PlotGroup2D");
    model.result("pg3").set("data", "dset1");
    model.result("pg3").setIndex("looplevel", 1, 0);
    model.result("pg3").create("surf1", "Surface");
    model.result("pg3").feature("surf1").set("expr", new String[]{"V"});
    model.result("pg1").feature("surf1").set("colortable", "Prism");
    model.result("pg2").feature("surf1").set("colortable", "Prism");
    model.result("pg3").feature("surf1").set("colortable", "Dipole");
    model.result("pg1").label("\u7535\u5b50\u5bc6\u5ea6 (plas)");
    model.result("pg2").label("\u7535\u5b50\u6e29\u5ea6 (plas)");
    model.result("pg3").label("\u7535\u52bf (plas)");
    model.result().create("pg4", "PlotGroup2D");
    model.result("pg4").label("\u78c1\u901a\u5bc6\u5ea6 (mf)");
    model.result("pg4").set("dataisaxisym", "off");
    model.result("pg4").set("frametype", "spatial");
    model.result("pg4").set("showlegendsmaxmin", true);
    model.result("pg4").feature().create("surf1", "Surface");
    model.result("pg4").feature("surf1").set("showsolutionparams", "on");
    model.result("pg4").feature("surf1").set("solutionparams", "parent");
    model.result("pg4").feature("surf1").set("expr", "mf.normB");
    model.result("pg4").feature("surf1").set("colortabletrans", "nonlinear");
    model.result("pg4").feature("surf1").set("colorcalibration", -0.8);
    model.result("pg4").feature("surf1").set("showsolutionparams", "on");
    model.result("pg4").feature("surf1").set("data", "parent");
    model.result("pg4").feature().create("str1", "Streamline");
    model.result("pg4").feature("str1").set("showsolutionparams", "on");
    model.result("pg4").feature("str1").set("solutionparams", "parent");
    model.result("pg4").feature("str1").set("expr", new String[]{"mf.Br", "mf.Bz"});
    model.result("pg4").feature("str1").set("titletype", "none");
    model.result("pg4").feature("str1").set("posmethod", "uniform");
    model.result("pg4").feature("str1").set("udist", 0.03);
    model.result("pg4").feature("str1").set("maxlen", 0.4);
    model.result("pg4").feature("str1").set("maxsteps", 5000);
    model.result("pg4").feature("str1").set("maxtime", Double.POSITIVE_INFINITY);
    model.result("pg4").feature("str1").set("inheritcolor", false);
    model.result("pg4").feature("str1").set("showsolutionparams", "on");
    model.result("pg4").feature("str1").set("maxtime", Double.POSITIVE_INFINITY);
    model.result("pg4").feature("str1").set("showsolutionparams", "on");
    model.result("pg4").feature("str1").set("maxtime", Double.POSITIVE_INFINITY);
    model.result("pg4").feature("str1").set("showsolutionparams", "on");
    model.result("pg4").feature("str1").set("maxtime", Double.POSITIVE_INFINITY);
    model.result("pg4").feature("str1").set("showsolutionparams", "on");
    model.result("pg4").feature("str1").set("maxtime", Double.POSITIVE_INFINITY);
    model.result("pg4").feature("str1").set("data", "parent");
    model.result("pg4").feature("str1").selection().geom("geom1", 1);
    model.result("pg4").feature("str1").selection()
         .set(3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39);
    model.result("pg4").feature("str1").set("inheritplot", "surf1");
    model.result("pg4").feature("str1").feature().create("col1", "Color");
    model.result("pg4").feature("str1").feature("col1").set("expr", "mf.normB");
    model.result("pg4").feature("str1").feature("col1").set("colortable", "PrismDark");
    model.result("pg4").feature("str1").feature("col1").set("colorlegend", false);
    model.result("pg4").feature("str1").feature("col1").set("colortabletrans", "nonlinear");
    model.result("pg4").feature("str1").feature("col1").set("colorcalibration", -0.8);
    model.result("pg4").feature("str1").feature().create("filt1", "Filter");
    model.result("pg4").feature("str1").feature("filt1").set("expr", "!isScalingSystemDomain");
    model.result("pg4").feature().create("con1", "Contour");
    model.result("pg4").feature("con1").set("showsolutionparams", "on");
    model.result("pg4").feature("con1").set("solutionparams", "parent");
    model.result("pg4").feature("con1").set("expr", "mf.Psi");
    model.result("pg4").feature("con1").set("titletype", "none");
    model.result("pg4").feature("con1").set("number", 10);
    model.result("pg4").feature("con1").set("levelrounding", false);
    model.result("pg4").feature("con1").set("coloring", "uniform");
    model.result("pg4").feature("con1").set("colorlegend", false);
    model.result("pg4").feature("con1").set("color", "custom");
    model.result("pg4").feature("con1")
         .set("customcolor", new double[]{0.3764705955982208, 0.3764705955982208, 0.3764705955982208});
    model.result("pg4").feature("con1").set("resolution", "fine");
    model.result("pg4").feature("con1").set("inheritcolor", false);
    model.result("pg4").feature("con1").set("showsolutionparams", "on");
    model.result("pg4").feature("con1").set("data", "parent");
    model.result("pg4").feature("con1").set("inheritplot", "surf1");
    model.result("pg4").feature("con1").feature().create("filt1", "Filter");
    model.result("pg4").feature("con1").feature("filt1").set("expr", "!isScalingSystemDomain");
    model.result().dataset().create("rev1", "Revolve2D");
    model.result().dataset("rev1").set("data", "none");
    model.result().dataset("rev1").set("startangle", -90);
    model.result().dataset("rev1").set("revangle", 225);
    model.result().dataset("rev1").set("data", "dset1");
    model.result().create("pg5", "PlotGroup3D");
    model.result("pg5").label("\u78c1\u901a\u5bc6\u5ea6\uff0c\u56de\u8f6c\u51e0\u4f55 (mf)");
    model.result("pg5").set("frametype", "spatial");
    model.result("pg5").set("showlegendsmaxmin", true);
    model.result("pg5").feature().create("vol1", "Volume");
    model.result("pg5").feature("vol1").set("showsolutionparams", "on");
    model.result("pg5").feature("vol1").set("solutionparams", "parent");
    model.result("pg5").feature("vol1").set("expr", "mf.normB");
    model.result("pg5").feature("vol1").set("colortabletrans", "nonlinear");
    model.result("pg5").feature("vol1").set("colorcalibration", -0.8);
    model.result("pg5").feature("vol1").set("showsolutionparams", "on");
    model.result("pg5").feature("vol1").set("data", "parent");
    model.result("pg5").feature().create("con1", "Contour");
    model.result("pg5").feature("con1").set("showsolutionparams", "on");
    model.result("pg5").feature("con1").set("solutionparams", "parent");
    model.result("pg5").feature("con1").set("expr", "mf.Psi");
    model.result("pg5").feature("con1").set("titletype", "none");
    model.result("pg5").feature("con1").set("number", 10);
    model.result("pg5").feature("con1").set("levelrounding", false);
    model.result("pg5").feature("con1").set("coloring", "uniform");
    model.result("pg5").feature("con1").set("colorlegend", false);
    model.result("pg5").feature("con1").set("color", "custom");
    model.result("pg5").feature("con1")
         .set("customcolor", new double[]{0.3764705955982208, 0.3764705955982208, 0.3764705955982208});
    model.result("pg5").feature("con1").set("resolution", "fine");
    model.result("pg5").feature("con1").set("inheritcolor", false);
    model.result("pg5").feature("con1").set("showsolutionparams", "on");
    model.result("pg5").feature("con1").set("data", "parent");
    model.result("pg5").feature("con1").set("inheritplot", "vol1");
    model.result("pg5").feature("con1").feature().create("filt1", "Filter");
    model.result("pg5").feature("con1").feature("filt1").set("expr", "!isScalingSystemDomain");
    model.result("pg5").feature("con1").feature("filt1").set("shownodespec", "on");
    model.result("pg1").run();

    model.nodeGroup().create("grp1", "Results");
    model.nodeGroup("grp1").set("type", "plotgroup");
    model.nodeGroup("grp1").add("plotgroup", "pg1");
    model.nodeGroup("grp1").add("plotgroup", "pg2");
    model.nodeGroup("grp1").add("plotgroup", "pg3");
    model.nodeGroup("grp1").add("plotgroup", "pg4");
    model.nodeGroup("grp1").add("plotgroup", "pg5");
    model.nodeGroup("grp1").label("\u521d\u59cb\u8bbe\u8ba1");

    model.study("std1").feature("fstat").set("freq", "13.56[MHz]");

    model.sol("sol1").feature("s1").feature("fc1").set("plot", true);

    model.study("std1").createAutoSequences("all");

    model.sol("sol1").runAll();

    model.result("pg1").run();

    model.study("std1").label("\u521d\u59cb\u8bbe\u8ba1");

    model.component("comp1").probe().create("bnd1", "Boundary");
    model.component("comp1").probe("bnd1").set("intsurface", true);
    model.component("comp1").probe("bnd1").label("\u68af\u5ea6\u6700\u5c0f\u5316");
    model.component("comp1").probe("bnd1").set("probename", "int_grad_ne");
    model.component("comp1").probe("bnd1").selection().set(6);
    model.component("comp1").probe("bnd1").set("type", "integral");
    model.component("comp1").probe("bnd1").set("expr", "sqrt(d(plas.ne,r)^2)");
    model.component("comp1").probe("bnd1").set("intsurface", false);
    model.component("comp1").probe().create("point1", "Point");
    model.component("comp1").probe("point1").label("\u4e2d\u5fc3\u7535\u5b50\u5bc6\u5ea6\u7684\u7ea6\u675f");
    model.component("comp1").probe("point1").set("probename", "ne_center");
    model.component("comp1").probe("point1").selection().set(3);
    model.component("comp1").probe("point1").set("expr", "plas.ne/ne0");

    model.component("comp1").common().create("fsd1", "FreeShapeDomain");
    model.component("comp1").common("fsd1").selection().all();
    model.component("comp1").common("fsd1").selection().named("geom1_adjsel2");
    model.component("comp1").common().create("tsf1", "Transformation");
    model.component("comp1").common("tsf1").setIndex("move_lock", false, 0);
    model.component("comp1").common("tsf1").setIndex("move_lBound", "-3[cm]", 0);
    model.component("comp1").common("tsf1").setIndex("move_uBound", "3[cm]", 0);
    model.component("comp1").common("tsf1").set("scalingType", "No_scaling");
    model.component("comp1").common("tsf1").selection().named("geom1_r7_dom");
    model.component("comp1").common().create("fsr1", "FreeShapeSymmetry");
    model.component("comp1").common("fsr1").selection().named("geom1_difsel3");

    model.component("comp1").variable().create("var1");
    model.component("comp1").variable("var1").set("ne0", "3.5E17[m^-3]");
    model.component("comp1").variable("var1").set("obj_negrad", "int_grad_ne/ne0");
    model.component("comp1").variable("var1").descr("obj_negrad", "\u76ee\u6807\u68af\u5ea6");

    model.study().create("std2");
    model.study("std2").create("fstat", "FrequencyStationary");
    model.study("std2").feature("fstat").set("plotgroup", "Default");
    model.study("std2").feature("fstat").set("freq", "1000000");
    model.study("std2").feature("fstat").set("solnum", "auto");
    model.study("std2").feature("fstat").set("notsolnum", "auto");
    model.study("std2").feature("fstat").set("outputmap", new String[]{});
    model.study("std2").feature("fstat").set("ngenAUX", "1");
    model.study("std2").feature("fstat").set("goalngenAUX", "1");
    model.study("std2").feature("fstat").set("ngenAUX", "1");
    model.study("std2").feature("fstat").set("goalngenAUX", "1");
    model.study("std2").feature("fstat").setSolveFor("/physics/plas", true);
    model.study("std2").feature("fstat").setSolveFor("/physics/mf", true);
    model.study("std2").feature("fstat").setSolveFor("/multiphysics/pcc1", true);
    model.study("std2").feature("fstat").setSolveFor("/multiphysics/ehs1", true);
    model.study("std2").feature("fstat").set("freq", "13.56[MHz]");
    model.study("std2").label("\u4f18\u5316");
    model.study("std2").create("opt", "Optimization");
    model.study("std2").feature("opt").set("optsolver", "ipopt");
    model.study("std2").feature("opt").set("opttolinner", "0.0005");
    model.study("std2").feature("opt").set("nsolvemax", 20);
    model.study("std2").feature("opt").set("optobj", new String[]{"comp1.obj_negrad"});
    model.study("std2").feature("opt").set("descr", new String[]{"\u76ee\u6807\u68af\u5ea6"});
    model.study("std2").feature("opt").setIndex("pname", "Psp", 0);

    return model;
  }

  public static Model run2(Model model) {
    model.study("std2").feature("opt").setIndex("initval", "1500[W]", 0);
    model.study("std2").feature("opt").setIndex("scale", 1, 0);
    model.study("std2").feature("opt").setIndex("lbound", "", 0);
    model.study("std2").feature("opt").setIndex("ubound", "", 0);
    model.study("std2").feature("opt").setIndex("pname", "Psp", 0);
    model.study("std2").feature("opt").setIndex("initval", "1500[W]", 0);
    model.study("std2").feature("opt").setIndex("scale", 1, 0);
    model.study("std2").feature("opt").setIndex("lbound", "", 0);
    model.study("std2").feature("opt").setIndex("ubound", "", 0);
    model.study("std2").feature("opt").setIndex("scale", "1000[W]", 0);
    model.study("std2").feature("opt").setIndex("lbound", "500[W]", 0);
    model.study("std2").feature("opt").setIndex("ubound", "5000[W]", 0);
    model.study("std2").feature("opt").setIndex("constraintExpression", "comp1.ne_center", 0);
    model.study("std2").feature("opt").setIndex("constraintLbound", 1, 0);
    model.study("std2").feature("opt").setIndex("constraintUbound", 1.1, 0);
    model.study("std2").createAutoSequences("sol");
    model.study("std2").createAutoSequences("jobs");

    model.component("comp1").probe("bnd1").genResult("none");
    model.component("comp1").probe("point1").genResult("none");

    model.sol("sol2").runFromTo("st1", "v1");

    model.result().create("pg7", "PlotGroup2D");
    model.result("pg7").set("data", "dset2");
    model.result("pg7").create("surf1", "Surface");
    model.result("pg7").feature("surf1").set("expr", new String[]{"plas.ne"});
    model.result().create("pg8", "PlotGroup2D");
    model.result("pg8").set("data", "dset2");
    model.result("pg8").create("surf1", "Surface");
    model.result("pg8").feature("surf1").set("expr", new String[]{"plas.Te"});
    model.result().create("pg9", "PlotGroup2D");
    model.result("pg9").set("data", "dset2");
    model.result("pg9").create("surf1", "Surface");
    model.result("pg9").feature("surf1").set("expr", new String[]{"V"});
    model.result("pg7").feature("surf1").set("colortable", "Prism");
    model.result("pg8").feature("surf1").set("colortable", "Prism");
    model.result("pg9").feature("surf1").set("colortable", "Dipole");
    model.result("pg7").label("\u7535\u5b50\u5bc6\u5ea6 (plas) 1");
    model.result("pg8").label("\u7535\u5b50\u6e29\u5ea6 (plas) 1");
    model.result("pg9").label("\u7535\u52bf (plas) 1");
    model.result().create("pg10", "PlotGroup2D");
    model.result("pg10").label("\u78c1\u901a\u5bc6\u5ea6 (mf) 1");
    model.result("pg10").set("data", "dset2");
    model.result("pg10").set("dataisaxisym", "off");
    model.result("pg10").set("frametype", "spatial");
    model.result("pg10").set("showlegendsmaxmin", true);
    model.result("pg10").feature().create("surf1", "Surface");
    model.result("pg10").feature("surf1").set("showsolutionparams", "on");
    model.result("pg10").feature("surf1").set("solutionparams", "parent");
    model.result("pg10").feature("surf1").set("expr", "mf.normB");
    model.result("pg10").feature("surf1").set("colortabletrans", "nonlinear");
    model.result("pg10").feature("surf1").set("colorcalibration", -0.8);
    model.result("pg10").feature("surf1").set("showsolutionparams", "on");
    model.result("pg10").feature("surf1").set("data", "parent");
    model.result("pg10").feature().create("str1", "Streamline");
    model.result("pg10").feature("str1").set("showsolutionparams", "on");
    model.result("pg10").feature("str1").set("solutionparams", "parent");
    model.result("pg10").feature("str1").set("expr", new String[]{"mf.Br", "mf.Bz"});
    model.result("pg10").feature("str1").set("titletype", "none");
    model.result("pg10").feature("str1").set("posmethod", "uniform");
    model.result("pg10").feature("str1").set("udist", 0.03);
    model.result("pg10").feature("str1").set("maxlen", 0.4);
    model.result("pg10").feature("str1").set("maxsteps", 5000);
    model.result("pg10").feature("str1").set("maxtime", Double.POSITIVE_INFINITY);
    model.result("pg10").feature("str1").set("inheritcolor", false);
    model.result("pg10").feature("str1").set("showsolutionparams", "on");
    model.result("pg10").feature("str1").set("maxtime", Double.POSITIVE_INFINITY);
    model.result("pg10").feature("str1").set("showsolutionparams", "on");
    model.result("pg10").feature("str1").set("maxtime", Double.POSITIVE_INFINITY);
    model.result("pg10").feature("str1").set("showsolutionparams", "on");
    model.result("pg10").feature("str1").set("maxtime", Double.POSITIVE_INFINITY);
    model.result("pg10").feature("str1").set("showsolutionparams", "on");
    model.result("pg10").feature("str1").set("maxtime", Double.POSITIVE_INFINITY);
    model.result("pg10").feature("str1").set("data", "parent");
    model.result("pg10").feature("str1").selection().geom("geom1", 1);
    model.result("pg10").feature("str1").selection()
         .set(3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39);
    model.result("pg10").feature("str1").set("inheritplot", "surf1");
    model.result("pg10").feature("str1").feature().create("col1", "Color");
    model.result("pg10").feature("str1").feature("col1").set("expr", "mf.normB");
    model.result("pg10").feature("str1").feature("col1").set("colortable", "PrismDark");
    model.result("pg10").feature("str1").feature("col1").set("colorlegend", false);
    model.result("pg10").feature("str1").feature("col1").set("colortabletrans", "nonlinear");
    model.result("pg10").feature("str1").feature("col1").set("colorcalibration", -0.8);
    model.result("pg10").feature("str1").feature().create("filt1", "Filter");
    model.result("pg10").feature("str1").feature("filt1").set("expr", "!isScalingSystemDomain");
    model.result("pg10").feature().create("con1", "Contour");
    model.result("pg10").feature("con1").set("showsolutionparams", "on");
    model.result("pg10").feature("con1").set("solutionparams", "parent");
    model.result("pg10").feature("con1").set("expr", "mf.Psi");
    model.result("pg10").feature("con1").set("titletype", "none");
    model.result("pg10").feature("con1").set("number", 10);
    model.result("pg10").feature("con1").set("levelrounding", false);
    model.result("pg10").feature("con1").set("coloring", "uniform");
    model.result("pg10").feature("con1").set("colorlegend", false);
    model.result("pg10").feature("con1").set("color", "custom");
    model.result("pg10").feature("con1")
         .set("customcolor", new double[]{0.3764705955982208, 0.3764705955982208, 0.3764705955982208});
    model.result("pg10").feature("con1").set("resolution", "fine");
    model.result("pg10").feature("con1").set("inheritcolor", false);
    model.result("pg10").feature("con1").set("showsolutionparams", "on");
    model.result("pg10").feature("con1").set("data", "parent");
    model.result("pg10").feature("con1").set("inheritplot", "surf1");
    model.result("pg10").feature("con1").feature().create("filt1", "Filter");
    model.result("pg10").feature("con1").feature("filt1").set("expr", "!isScalingSystemDomain");
    model.result().dataset().create("rev2", "Revolve2D");
    model.result().dataset("rev2").set("data", "none");
    model.result().dataset("rev2").set("startangle", -90);
    model.result().dataset("rev2").set("revangle", 225);
    model.result().dataset("rev2").set("data", "dset2");
    model.result().create("pg11", "PlotGroup3D");
    model.result("pg11").label("\u78c1\u901a\u5bc6\u5ea6\uff0c\u56de\u8f6c\u51e0\u4f55 (mf) 1");
    model.result("pg11").set("data", "rev2");
    model.result("pg11").set("frametype", "spatial");
    model.result("pg11").set("showlegendsmaxmin", true);
    model.result("pg11").feature().create("vol1", "Volume");
    model.result("pg11").feature("vol1").set("showsolutionparams", "on");
    model.result("pg11").feature("vol1").set("solutionparams", "parent");
    model.result("pg11").feature("vol1").set("expr", "mf.normB");
    model.result("pg11").feature("vol1").set("colortabletrans", "nonlinear");
    model.result("pg11").feature("vol1").set("colorcalibration", -0.8);
    model.result("pg11").feature("vol1").set("showsolutionparams", "on");
    model.result("pg11").feature("vol1").set("data", "parent");
    model.result("pg11").feature().create("con1", "Contour");
    model.result("pg11").feature("con1").set("showsolutionparams", "on");
    model.result("pg11").feature("con1").set("solutionparams", "parent");
    model.result("pg11").feature("con1").set("expr", "mf.Psi");
    model.result("pg11").feature("con1").set("titletype", "none");
    model.result("pg11").feature("con1").set("number", 10);
    model.result("pg11").feature("con1").set("levelrounding", false);
    model.result("pg11").feature("con1").set("coloring", "uniform");
    model.result("pg11").feature("con1").set("colorlegend", false);
    model.result("pg11").feature("con1").set("color", "custom");
    model.result("pg11").feature("con1")
         .set("customcolor", new double[]{0.3764705955982208, 0.3764705955982208, 0.3764705955982208});
    model.result("pg11").feature("con1").set("resolution", "fine");
    model.result("pg11").feature("con1").set("inheritcolor", false);
    model.result("pg11").feature("con1").set("showsolutionparams", "on");
    model.result("pg11").feature("con1").set("data", "parent");
    model.result("pg11").feature("con1").set("inheritplot", "vol1");
    model.result("pg11").feature("con1").feature().create("filt1", "Filter");
    model.result("pg11").feature("con1").feature("filt1").set("expr", "!isScalingSystemDomain");
    model.result("pg11").feature("con1").feature("filt1").set("shownodespec", "on");
    model.result().create("pg12", "PlotGroup2D");
    model.result().dataset().duplicate("dset2g1", "dset2");
    model.result().dataset("dset2g1").label("\u4f18\u5316/\u89e3 2 (2) - \u51e0\u4f55");
    model.result().dataset("dset2g1").set("frametype", "geometry");
    model.result("pg12").label("\u5f62\u72b6\u4f18\u5316");
    model.result("pg12").set("data", "dset2");
    model.result("pg12").set("frametype", "geometry");
    model.result("pg12").set("edgecolor", "gray");
    model.result("pg12").set("titletype", "none");
    model.result("pg12").create("line1", "Line");
    model.result("pg12").feature("line1").set("expr", "1");
    model.result("pg12").feature("line1").set("coloring", "uniform");
    model.result("pg12").feature("line1").set("color", "fromtheme");
    model.result("pg12").create("arwp1", "ArrowPoint");
    model.result("pg12").feature("arwp1").label("\u5e73\u79fb (\u53d8\u6362 1)");
    model.result("pg12").feature("arwp1").set("expr", new String[]{"tsf1.moveRg", "tsf1.moveZg"});
    model.result("pg12").feature("arwp1").set("arrowbase", "head");
    model.result("pg12").feature("arwp1").set("scaleactive", true);
    model.result("pg12").feature("arwp1").set("scale", "1");
    model.result("pg12").feature("arwp1").create("def1", "Deform");
    model.result("pg12").feature("arwp1").feature("def1")
         .set("expr", new String[]{"-tsf1.scaleRg-tsf1.rotateRg", "-tsf1.scaleZg-tsf1.rotateZg"});
    model.result("pg12").feature("arwp1").feature("def1").set("scaleactive", true);
    model.result("pg12").feature("arwp1").feature("def1").set("scale", "1");
    model.result("pg12").feature("arwp1").create("col1", "Color");
    model.result("pg12").feature("arwp1").feature("col1").set("expr", "tsf1.rel_move");
    model.result("pg12").feature("arwp1").feature("col1").set("rangecoloractive", "on");
    model.result("pg12").feature("arwp1").feature("col1").set("rangecolormin", 0);
    model.result("pg12").feature("arwp1").feature("col1").set("rangecolormax", 1);
    model.result("pg12").create("arwp2", "ArrowPoint");
    model.result("pg12").feature("arwp2").label("\u7f29\u653e (\u53d8\u6362 1)");
    model.result("pg12").feature("arwp2").set("expr", new String[]{"tsf1.scaleRg", "tsf1.scaleZg"});
    model.result("pg12").feature("arwp2").set("arrowbase", "head");
    model.result("pg12").feature("arwp2").set("scaleactive", true);
    model.result("pg12").feature("arwp2").set("scale", "1");
    model.result("pg12").feature("arwp2").set("inheritplot", "arwp1");
    model.result("pg12").feature("arwp2").create("def1", "Deform");
    model.result("pg12").feature("arwp2").feature("def1")
         .set("expr", new String[]{"-tsf1.rotateRg", "-tsf1.rotateZg"});
    model.result("pg12").feature("arwp2").feature("def1").set("scaleactive", true);
    model.result("pg12").feature("arwp2").feature("def1").set("scale", "1");
    model.result("pg12").feature("arwp2").create("col1", "Color");
    model.result("pg12").feature("arwp2").feature("col1").set("expr", "tsf1.rel_scale");
    model.result("pg12").feature("arwp2").feature("col1").set("rangecoloractive", "on");
    model.result("pg12").feature("arwp2").feature("col1").set("rangecolormin", 0);
    model.result("pg12").feature("arwp2").feature("col1").set("rangecolormax", 1);
    model.result("pg12").create("arwp3", "ArrowPoint");
    model.result("pg12").feature("arwp3").label("\u65cb\u8f6c (\u53d8\u6362 1)");
    model.result("pg12").feature("arwp3").set("expr", new String[]{"tsf1.rotateRg", "tsf1.rotateZg"});
    model.result("pg12").feature("arwp3").set("arrowbase", "head");
    model.result("pg12").feature("arwp3").set("scaleactive", true);
    model.result("pg12").feature("arwp3").set("scale", "1");
    model.result("pg12").feature("arwp3").set("inheritplot", "arwp1");
    model.result("pg12").feature("arwp3").create("col1", "Color");
    model.result("pg12").feature("arwp3").feature("col1").set("expr", "tsf1.rel_rotate");
    model.result("pg12").feature("arwp3").feature("col1").set("rangecoloractive", "on");
    model.result("pg12").feature("arwp3").feature("col1").set("rangecolormin", 0);
    model.result("pg12").feature("arwp3").feature("col1").set("rangecolormax", 1);
    model.result("pg7").run();
    model.result("pg6").set("window", "window1");
    model.result("pg6").run();

    model.nodeGroup().create("grp2", "Results");
    model.nodeGroup("grp2").set("type", "plotgroup");
    model.nodeGroup().move("grp2", 1);
    model.nodeGroup("grp2").add("plotgroup", "pg6");
    model.nodeGroup("grp2").add("plotgroup", "pg7");
    model.nodeGroup("grp2").add("plotgroup", "pg8");
    model.nodeGroup("grp2").add("plotgroup", "pg9");
    model.nodeGroup("grp2").add("plotgroup", "pg10");
    model.nodeGroup("grp2").add("plotgroup", "pg11");
    model.nodeGroup("grp2").add("plotgroup", "pg12");
    model.nodeGroup("grp2").label("\u4f18\u5316");

    model.study("std2").feature("opt").set("plot", true);
    model.study("std2").feature("opt").set("plotgroup", "pg12");
    model.study("std2").feature("opt").set("probesel", "none");

    model.sol("sol2").feature("o1").feature("s1").feature("d1").set("errorchk", false);

    model.study("std2").createAutoSequences("all");
    model.study("std2").feature("opt").set("continuecontrolparams", new String[]{});
    model.study("std2").feature("opt").set("continuecontrolvals", new double[]{});
    model.study("std2").feature("opt").set("continuelagrangevals", new double[]{});
    model.study("std2").feature("opt").set("continuelagrangeparams", new String[]{});

    model.sol("sol2").runAll();

    model.result("pg7").run();

    model.study("std2").feature("opt").set("probewindow", "");

    model.result().dataset("dset2").createDeformedConfig("deform1", "mesh2");

    model.component("comp1").mesh("mesh2").run();

    model.study().create("std3");
    model.study("std3").create("fstat", "FrequencyStationary");
    model.study("std3").feature("fstat").set("plotgroup", "Default");
    model.study("std3").feature("fstat").set("freq", "1000000");
    model.study("std3").feature("fstat").set("solnum", "auto");
    model.study("std3").feature("fstat").set("notsolnum", "auto");
    model.study("std3").feature("fstat").set("outputmap", new String[]{});
    model.study("std3").feature("fstat").set("ngenAUX", "1");
    model.study("std3").feature("fstat").set("goalngenAUX", "1");
    model.study("std3").feature("fstat").set("ngenAUX", "1");
    model.study("std3").feature("fstat").set("goalngenAUX", "1");
    model.study("std3").feature("fstat").setSolveFor("/physics/plas", true);
    model.study("std3").feature("fstat").setSolveFor("/physics/mf", true);
    model.study("std3").feature("fstat").setSolveFor("/multiphysics/pcc1", true);
    model.study("std3").feature("fstat").setSolveFor("/multiphysics/ehs1", true);
    model.study("std3").feature("fstat").set("freq", "13.56[MHz]");
    model.study("std3").feature("fstat").setSolveFor("/frame/material1", false);
    model.study("std3").feature("fstat").set("useinitsol", true);
    model.study("std3").feature("fstat").set("initmethod", "sol");
    model.study("std3").feature("fstat").set("initstudy", "std2");
    model.study("std3").feature("fstat").set("usesol", true);
    model.study("std3").feature("fstat").set("notsolmethod", "sol");
    model.study("std3").feature("fstat").set("notstudy", "std2");
    model.study("std3").label("\u9a8c\u8bc1");
    model.study("std3").createAutoSequences("all");

    model.component("comp1").probe("bnd1").genResult("none");
    model.component("comp1").probe("point1").genResult("none");

    model.sol("sol3").runAll();

    model.result().create("pg13", "PlotGroup2D");
    model.result("pg13").set("data", "dset4");
    model.result("pg13").create("surf1", "Surface");
    model.result("pg13").feature("surf1").set("expr", new String[]{"plas.ne"});
    model.result().create("pg14", "PlotGroup2D");
    model.result("pg14").set("data", "dset4");
    model.result("pg14").create("surf1", "Surface");
    model.result("pg14").feature("surf1").set("expr", new String[]{"plas.Te"});
    model.result().create("pg15", "PlotGroup2D");
    model.result("pg15").set("data", "dset4");
    model.result("pg15").create("surf1", "Surface");
    model.result("pg15").feature("surf1").set("expr", new String[]{"V"});
    model.result("pg13").feature("surf1").set("colortable", "Prism");
    model.result("pg14").feature("surf1").set("colortable", "Prism");
    model.result("pg15").feature("surf1").set("colortable", "Dipole");
    model.result("pg13").label("\u7535\u5b50\u5bc6\u5ea6 (plas) 2");
    model.result("pg14").label("\u7535\u5b50\u6e29\u5ea6 (plas) 2");
    model.result("pg15").label("\u7535\u52bf (plas) 2");
    model.result().create("pg16", "PlotGroup2D");
    model.result("pg16").label("\u78c1\u901a\u5bc6\u5ea6 (mf) 2");
    model.result("pg16").set("data", "dset4");
    model.result("pg16").set("dataisaxisym", "off");
    model.result("pg16").set("frametype", "spatial");
    model.result("pg16").set("showlegendsmaxmin", true);
    model.result("pg16").feature().create("surf1", "Surface");
    model.result("pg16").feature("surf1").set("showsolutionparams", "on");
    model.result("pg16").feature("surf1").set("solutionparams", "parent");
    model.result("pg16").feature("surf1").set("expr", "mf.normB");
    model.result("pg16").feature("surf1").set("colortabletrans", "nonlinear");
    model.result("pg16").feature("surf1").set("colorcalibration", -0.8);
    model.result("pg16").feature("surf1").set("showsolutionparams", "on");
    model.result("pg16").feature("surf1").set("data", "parent");
    model.result("pg16").feature().create("str1", "Streamline");
    model.result("pg16").feature("str1").set("showsolutionparams", "on");
    model.result("pg16").feature("str1").set("solutionparams", "parent");
    model.result("pg16").feature("str1").set("expr", new String[]{"mf.Br", "mf.Bz"});
    model.result("pg16").feature("str1").set("titletype", "none");
    model.result("pg16").feature("str1").set("posmethod", "uniform");
    model.result("pg16").feature("str1").set("udist", 0.03);
    model.result("pg16").feature("str1").set("maxlen", 0.4);
    model.result("pg16").feature("str1").set("maxsteps", 5000);
    model.result("pg16").feature("str1").set("maxtime", Double.POSITIVE_INFINITY);
    model.result("pg16").feature("str1").set("inheritcolor", false);
    model.result("pg16").feature("str1").set("showsolutionparams", "on");
    model.result("pg16").feature("str1").set("maxtime", Double.POSITIVE_INFINITY);
    model.result("pg16").feature("str1").set("showsolutionparams", "on");
    model.result("pg16").feature("str1").set("maxtime", Double.POSITIVE_INFINITY);
    model.result("pg16").feature("str1").set("showsolutionparams", "on");
    model.result("pg16").feature("str1").set("maxtime", Double.POSITIVE_INFINITY);
    model.result("pg16").feature("str1").set("showsolutionparams", "on");
    model.result("pg16").feature("str1").set("maxtime", Double.POSITIVE_INFINITY);
    model.result("pg16").feature("str1").set("data", "parent");
    model.result("pg16").feature("str1").selection().geom("geom1", 1);
    model.result("pg16").feature("str1").selection()
         .set(3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39);
    model.result("pg16").feature("str1").set("inheritplot", "surf1");
    model.result("pg16").feature("str1").feature().create("col1", "Color");
    model.result("pg16").feature("str1").feature("col1").set("expr", "mf.normB");
    model.result("pg16").feature("str1").feature("col1").set("colortable", "PrismDark");
    model.result("pg16").feature("str1").feature("col1").set("colorlegend", false);
    model.result("pg16").feature("str1").feature("col1").set("colortabletrans", "nonlinear");
    model.result("pg16").feature("str1").feature("col1").set("colorcalibration", -0.8);
    model.result("pg16").feature("str1").feature().create("filt1", "Filter");
    model.result("pg16").feature("str1").feature("filt1").set("expr", "!isScalingSystemDomain");
    model.result("pg16").feature().create("con1", "Contour");
    model.result("pg16").feature("con1").set("showsolutionparams", "on");
    model.result("pg16").feature("con1").set("solutionparams", "parent");
    model.result("pg16").feature("con1").set("expr", "mf.Psi");
    model.result("pg16").feature("con1").set("titletype", "none");
    model.result("pg16").feature("con1").set("number", 10);
    model.result("pg16").feature("con1").set("levelrounding", false);
    model.result("pg16").feature("con1").set("coloring", "uniform");
    model.result("pg16").feature("con1").set("colorlegend", false);
    model.result("pg16").feature("con1").set("color", "custom");
    model.result("pg16").feature("con1")
         .set("customcolor", new double[]{0.3764705955982208, 0.3764705955982208, 0.3764705955982208});
    model.result("pg16").feature("con1").set("resolution", "fine");
    model.result("pg16").feature("con1").set("inheritcolor", false);
    model.result("pg16").feature("con1").set("showsolutionparams", "on");
    model.result("pg16").feature("con1").set("data", "parent");
    model.result("pg16").feature("con1").set("inheritplot", "surf1");
    model.result("pg16").feature("con1").feature().create("filt1", "Filter");
    model.result("pg16").feature("con1").feature("filt1").set("expr", "!isScalingSystemDomain");
    model.result().dataset().create("rev3", "Revolve2D");
    model.result().dataset("rev3").set("data", "none");
    model.result().dataset("rev3").set("startangle", -90);
    model.result().dataset("rev3").set("revangle", 225);
    model.result().dataset("rev3").set("data", "dset4");
    model.result().create("pg17", "PlotGroup3D");
    model.result("pg17").label("\u78c1\u901a\u5bc6\u5ea6\uff0c\u56de\u8f6c\u51e0\u4f55 (mf) 2");
    model.result("pg17").set("data", "rev3");
    model.result("pg17").set("frametype", "spatial");
    model.result("pg17").set("showlegendsmaxmin", true);
    model.result("pg17").feature().create("vol1", "Volume");
    model.result("pg17").feature("vol1").set("showsolutionparams", "on");
    model.result("pg17").feature("vol1").set("solutionparams", "parent");
    model.result("pg17").feature("vol1").set("expr", "mf.normB");
    model.result("pg17").feature("vol1").set("colortabletrans", "nonlinear");
    model.result("pg17").feature("vol1").set("colorcalibration", -0.8);
    model.result("pg17").feature("vol1").set("showsolutionparams", "on");
    model.result("pg17").feature("vol1").set("data", "parent");
    model.result("pg17").feature().create("con1", "Contour");
    model.result("pg17").feature("con1").set("showsolutionparams", "on");
    model.result("pg17").feature("con1").set("solutionparams", "parent");
    model.result("pg17").feature("con1").set("expr", "mf.Psi");
    model.result("pg17").feature("con1").set("titletype", "none");
    model.result("pg17").feature("con1").set("number", 10);
    model.result("pg17").feature("con1").set("levelrounding", false);
    model.result("pg17").feature("con1").set("coloring", "uniform");
    model.result("pg17").feature("con1").set("colorlegend", false);
    model.result("pg17").feature("con1").set("color", "custom");
    model.result("pg17").feature("con1")
         .set("customcolor", new double[]{0.3764705955982208, 0.3764705955982208, 0.3764705955982208});
    model.result("pg17").feature("con1").set("resolution", "fine");
    model.result("pg17").feature("con1").set("inheritcolor", false);
    model.result("pg17").feature("con1").set("showsolutionparams", "on");
    model.result("pg17").feature("con1").set("data", "parent");
    model.result("pg17").feature("con1").set("inheritplot", "vol1");
    model.result("pg17").feature("con1").feature().create("filt1", "Filter");
    model.result("pg17").feature("con1").feature("filt1").set("expr", "!isScalingSystemDomain");
    model.result("pg17").feature("con1").feature("filt1").set("shownodespec", "on");
    model.result().create("pg18", "PlotGroup2D");
    model.result().dataset().duplicate("dset4g1", "dset4");
    model.result().dataset("dset4g1").label("\u9a8c\u8bc1/\u89e3 3 (4) - \u51e0\u4f55");
    model.result().dataset("dset4g1").set("frametype", "geometry");
    model.result("pg18").label("\u5f62\u72b6\u4f18\u5316 1");
    model.result("pg18").set("data", "dset4");
    model.result("pg18").set("frametype", "geometry");
    model.result("pg18").set("edgecolor", "gray");
    model.result("pg18").set("titletype", "none");
    model.result("pg18").create("line1", "Line");
    model.result("pg18").feature("line1").set("expr", "1");
    model.result("pg18").feature("line1").set("coloring", "uniform");
    model.result("pg18").feature("line1").set("color", "fromtheme");
    model.result("pg18").create("arwp1", "ArrowPoint");
    model.result("pg18").feature("arwp1").label("\u5e73\u79fb (\u53d8\u6362 1)");
    model.result("pg18").feature("arwp1").set("expr", new String[]{"tsf1.moveRg", "tsf1.moveZg"});
    model.result("pg18").feature("arwp1").set("arrowbase", "head");
    model.result("pg18").feature("arwp1").set("scaleactive", true);
    model.result("pg18").feature("arwp1").set("scale", "1");
    model.result("pg18").feature("arwp1").create("def1", "Deform");
    model.result("pg18").feature("arwp1").feature("def1")
         .set("expr", new String[]{"-tsf1.scaleRg-tsf1.rotateRg", "-tsf1.scaleZg-tsf1.rotateZg"});
    model.result("pg18").feature("arwp1").feature("def1").set("scaleactive", true);
    model.result("pg18").feature("arwp1").feature("def1").set("scale", "1");
    model.result("pg18").feature("arwp1").create("col1", "Color");
    model.result("pg18").feature("arwp1").feature("col1").set("expr", "tsf1.rel_move");
    model.result("pg18").feature("arwp1").feature("col1").set("rangecoloractive", "on");
    model.result("pg18").feature("arwp1").feature("col1").set("rangecolormin", 0);
    model.result("pg18").feature("arwp1").feature("col1").set("rangecolormax", 1);
    model.result("pg18").create("arwp2", "ArrowPoint");
    model.result("pg18").feature("arwp2").label("\u7f29\u653e (\u53d8\u6362 1)");
    model.result("pg18").feature("arwp2").set("expr", new String[]{"tsf1.scaleRg", "tsf1.scaleZg"});
    model.result("pg18").feature("arwp2").set("arrowbase", "head");
    model.result("pg18").feature("arwp2").set("scaleactive", true);
    model.result("pg18").feature("arwp2").set("scale", "1");
    model.result("pg18").feature("arwp2").set("inheritplot", "arwp1");
    model.result("pg18").feature("arwp2").create("def1", "Deform");
    model.result("pg18").feature("arwp2").feature("def1")
         .set("expr", new String[]{"-tsf1.rotateRg", "-tsf1.rotateZg"});
    model.result("pg18").feature("arwp2").feature("def1").set("scaleactive", true);
    model.result("pg18").feature("arwp2").feature("def1").set("scale", "1");
    model.result("pg18").feature("arwp2").create("col1", "Color");
    model.result("pg18").feature("arwp2").feature("col1").set("expr", "tsf1.rel_scale");
    model.result("pg18").feature("arwp2").feature("col1").set("rangecoloractive", "on");
    model.result("pg18").feature("arwp2").feature("col1").set("rangecolormin", 0);
    model.result("pg18").feature("arwp2").feature("col1").set("rangecolormax", 1);
    model.result("pg18").create("arwp3", "ArrowPoint");
    model.result("pg18").feature("arwp3").label("\u65cb\u8f6c (\u53d8\u6362 1)");
    model.result("pg18").feature("arwp3").set("expr", new String[]{"tsf1.rotateRg", "tsf1.rotateZg"});
    model.result("pg18").feature("arwp3").set("arrowbase", "head");
    model.result("pg18").feature("arwp3").set("scaleactive", true);
    model.result("pg18").feature("arwp3").set("scale", "1");
    model.result("pg18").feature("arwp3").set("inheritplot", "arwp1");
    model.result("pg18").feature("arwp3").create("col1", "Color");
    model.result("pg18").feature("arwp3").feature("col1").set("expr", "tsf1.rel_rotate");
    model.result("pg18").feature("arwp3").feature("col1").set("rangecoloractive", "on");
    model.result("pg18").feature("arwp3").feature("col1").set("rangecolormin", 0);
    model.result("pg18").feature("arwp3").feature("col1").set("rangecolormax", 1);
    model.result("pg13").run();

    model.nodeGroup().create("grp3", "Results");
    model.nodeGroup("grp3").set("type", "plotgroup");
    model.nodeGroup().move("grp3", 2);
    model.nodeGroup("grp3").add("plotgroup", "pg13");
    model.nodeGroup("grp3").add("plotgroup", "pg14");
    model.nodeGroup("grp3").add("plotgroup", "pg15");
    model.nodeGroup("grp3").add("plotgroup", "pg16");
    model.nodeGroup("grp3").add("plotgroup", "pg17");
    model.nodeGroup("grp3").add("plotgroup", "pg18");
    model.nodeGroup("grp3").label("\u9a8c\u8bc1");

    model.result().create("pg19", "PlotGroup1D");
    model.result("pg19").run();
    model.result("pg19")
         .label("\u7535\u5b50\u5bc6\u5ea6\uff1a\u521d\u59cb\u8bbe\u8ba1 vs. \u4f18\u5316 vs. \u9a8c\u8bc1");
    model.result("pg19").set("titletype", "label");
    model.result("pg19").create("lngr1", "LineGraph");
    model.result("pg19").feature("lngr1").set("markerpos", "datapoints");
    model.result("pg19").feature("lngr1").set("linewidth", "preference");
    model.result("pg19").feature("lngr1").selection().set(6);
    model.result("pg19").feature("lngr1").set("legend", true);
    model.result("pg19").feature("lngr1").set("legendmethod", "manual");
    model.result("pg19").feature("lngr1").setIndex("legends", "\u521d\u59cb\u8bbe\u8ba1", 0);
    model.result("pg19").run();
    model.result("pg19").feature().duplicate("lngr2", "lngr1");
    model.result("pg19").run();
    model.result("pg19").feature("lngr2").set("data", "dset2");
    model.result("pg19").feature("lngr2").setIndex("legends", "\u4f18\u5316", 0);
    model.result("pg19").feature().duplicate("lngr3", "lngr2");
    model.result("pg19").run();
    model.result("pg19").feature("lngr3").set("data", "dset4");

    return model;
  }

  public static Model run3(Model model) {
    model.result("pg19").feature("lngr3").setIndex("legends", "\u9a8c\u8bc1", 0);
    model.result("pg19").run();
    model.result("pg19").run();
    model.result("pg19").set("axislimits", true);
    model.result("pg19").set("ymin", 0);
    model.result("pg19").set("ymax", "7e17");
    model.result("pg19").run();
    model.result().duplicate("pg20", "pg19");
    model.result("pg20").run();
    model.result("pg20")
         .label("\u79bb\u5b50\u901a\u91cf\uff1a\u521d\u59cb\u8bbe\u8ba1 vs. \u4f18\u5316 vs. \u9a8c\u8bc1");
    model.result("pg20").run();
    model.result("pg20").feature("lngr1").selection().set(4);
    model.result("pg20").feature("lngr1").set("expr", "plas.nJi_wAr_1p");
    model.result("pg20").feature("lngr1").set("recover", "pprint");
    model.result("pg20").run();
    model.result("pg20").feature("lngr2").selection().set(4);
    model.result("pg20").feature("lngr2").set("expr", "plas.nJi_wAr_1p");
    model.result("pg20").feature("lngr2").set("recover", "pprint");
    model.result("pg20").run();
    model.result("pg20").feature("lngr3").selection().set(4);
    model.result("pg20").feature("lngr3").set("expr", "plas.nJi_wAr_1p");
    model.result("pg20").feature("lngr3").set("recover", "pprint");
    model.result("pg20").run();
    model.result("pg20").set("ymax", 150);
    model.result("pg20").set("ymin", 50);
    model.result("pg20").set("xmax", 15.5);
    model.result("pg20").run();
    model.result().create("pg21", "PlotGroup2D");
    model.result("pg21").run();
    model.result("pg21").label("\u7535\u5b50\u5bc6\u5ea6\uff1a\u521d\u59cb\u8bbe\u8ba1 vs. \u4f18\u5316");
    model.result("pg21").set("titletype", "label");
    model.result("pg21").create("surf1", "Surface");
    model.result("pg21").feature("surf1").set("data", "dset1");
    model.result("pg21").run();
    model.result("pg21").create("surf2", "Surface");
    model.result("pg21").feature("surf2").set("data", "dset4");
    model.result("pg21").feature("surf2").set("inheritplot", "surf1");
    model.result("pg21").feature("surf2").create("def1", "Deform");
    model.result("pg21").run();
    model.result("pg21").feature("surf2").feature("def1").set("expr", new String[]{"", "-25"});
    model.result("pg21").feature("surf2").feature("def1").set("scaleactive", true);
    model.result("pg21").feature("surf2").feature("def1").set("scale", 1);
    model.result("pg21").run();
    model.result("pg21").create("line1", "Line");
    model.result("pg21").feature("line1").set("data", "dset4");
    model.result("pg21").feature("line1").set("expr", "1");
    model.result("pg21").feature("line1").set("coloring", "uniform");
    model.result("pg21").feature("line1").set("color", "black");
    model.result("pg21").feature("line1").create("def1", "Deform");
    model.result("pg21").run();
    model.result("pg21").feature("line1").feature("def1").set("expr", new String[]{"", "-25"});
    model.result("pg21").feature("line1").feature("def1").set("scaleactive", true);
    model.result("pg21").feature("line1").feature("def1").set("scale", 1);
    model.result("pg21").run();
    model.result("pg21").run();
    model.result().duplicate("pg22", "pg21");
    model.result("pg22").run();
    model.result("pg22")
         .label("\u5438\u6536\u529f\u7387\u5bc6\u5ea6\uff1a\u521d\u59cb\u8bbe\u8ba1 vs. \u4f18\u5316");
    model.result("pg22").run();
    model.result("pg22").feature("surf1").set("expr", "mf.Qrh");
    model.result("pg22").feature("surf1").set("colortable", "ThermalWave");
    model.result("pg22").run();
    model.result("pg22").feature("surf2").set("expr", "mf.Qrh");
    model.result("pg22").feature("surf2").create("sel1", "Selection");
    model.result("pg22").feature("surf2").feature("sel1").selection().set(2);
    model.result("pg22").run();
    model.result("pg22").feature("surf1").create("sel1", "Selection");
    model.result("pg22").feature("surf1").feature("sel1").selection().set(2);
    model.result("pg22").run();
    model.result("pg19").run();
    model.result("pg20").run();
    model.result("pg21").run();
    model.result("pg22").run();

    model.title("ICP \u53cd\u5e94\u5668\u7684\u7ebf\u5708\u4f18\u5316");

    model
         .description("\u672c\u6a21\u578b\u6f14\u793a\u5982\u4f55\u4f7f\u7528\u5f62\u72b6\u4f18\u5316\u6765\u8bbe\u8ba1 ICP \u53cd\u5e94\u5668\u7684\u7ebf\u5708\u4ee5\u83b7\u5f97\u7b49\u79bb\u5b50\u4f53\u5747\u5300\u6027\u3002\u7814\u7a76\u4e2d\u7684\u53cd\u5e94\u5668\u662f\u5e73\u9762 ICP\uff0c\u7ebf\u5708\u6cbf\u5f84\u5411\u5206\u5e03\u3002\u5176\u4e2d\u4f7f\u7528\u201c\u4f18\u5316\u201d\u7814\u7a76\u6b65\u9aa4\u6765\u67e5\u627e\u6700\u4f73\u7ebf\u5708\u5e03\u7f6e\uff0c\u4ee5\u5c3d\u53ef\u80fd\u5730\u51cf\u5c0f\u53cd\u5e94\u5668\u4e2d\u5fc3\u7684\u7535\u5b50\u5bc6\u5ea6\u68af\u5ea6\u3002\u6b64\u5916\uff0c\u8fd8\u53ef\u4ee5\u901a\u8fc7\u6539\u53d8\u7ebf\u5708\u529f\u7387\u5728\u53cd\u5e94\u5668\u4e2d\u5fc3\u65bd\u52a0\u76ee\u6807\u7535\u5b50\u5bc6\u5ea6\u3002");

    model.mesh().clearMeshes();

    model.sol("sol1").clearSolutionData();
    model.sol("sol2").clearSolutionData();
    model.sol("sol3").clearSolutionData();

    model.label("icp_coil_optimization.mph");

    return model;
  }

  public static void main(String[] args) {
    Model model = run();
    model = run2(model);
    run3(model);
  }

}
