/*
 * lamb_waves_ndt_plate.java
 */

import com.comsol.model.*;
import com.comsol.model.util.*;

/** Model exported on Apr 29 2026, 17:40 by COMSOL 6.3.0.290. */
public class lamb_waves_ndt_plate {

  public static Model run() {
    Model model = ModelUtil.create("Model");

    model.modelPath("D:\\Program Files\\COMSOL\\COMSOL63\\Multiphysics\\applications\\Acoustics_Module\\Ultrasound");

//    To import content from file, use:
//    model.param().loadFile("FILENAME");
    model.param().set("D_plate", "5[mm]", "\u677f\u539a");
    model.param().set("W_plate", "15[mm]", "\u677f\u5bbd");
    model.param().set("L_plate", "50[cm]", "\u677f\u957f");
    model.param().set("H_wedge", "20[mm]", "\u6954\u5757\u9ad8\u5ea6");
    model.param().set("W_wedge", "20[mm]", "\u6954\u5757\u5bbd\u5ea6");
    model.param().set("L_wedge", "40[mm]", "\u6954\u5757\u957f\u5ea6");
    model.param().set("L_slope", "16[mm]", "\u6954\u5757\u5761\u5ea6\u957f\u5ea6");
    model.param().set("alpha", "70[deg]", "\u6954\u5757\u89d2\u5ea6");
    model.param().set("R_source", "6.25[mm]", "\u6fc0\u52b1\u533a\u534a\u5f84");
    model.param().label("\u53c2\u6570\uff1a\u51e0\u4f55\u53c2\u6570");
    model.param().create("par2");

//    To import content from file, use:
//    model.param("par2").loadFile("FILENAME");
    model.param("par2").set("cp_plast", "2080[m/s]", "\u5851\u6599\u4e2d\u7684\u7eb5\u5411\u6ce2\u901f");
    model.param("par2").set("cs_plast", "1000[m/s]", "\u5851\u6599\u4e2d\u7684\u526a\u5207\u6ce2\u901f");
    model.param("par2").set("rho_plast", "1190[kg/m^3]", "\u5851\u6599\u5bc6\u5ea6");
    model.param("par2").set("cp_steel", "5800[m/s]", "\u94a2\u4e2d\u7684\u7eb5\u5411\u6ce2\u901f");
    model.param("par2").set("cs_steel", "3160[m/s]", "\u94a2\u4e2d\u7684\u526a\u5207\u6ce2\u901f");
    model.param("par2").set("rho_steel", "7800[kg/m^3]", "\u94a2\u5bc6\u5ea6");
    model.param("par2").set("fmax", "500[kHz]", "\u6700\u5927\u9891\u7387");
    model.param("par2").set("omegamax", "2*pi*fmax", "\u6700\u5927\u89d2\u9891\u7387");
    model.param("par2").set("f0", "200[kHz]", "\u5de5\u4f5c\u9891\u7387");
    model.param("par2").set("omega0", "2*pi*f0", "\u5de5\u4f5c\u89d2\u9891\u7387");
    model.param("par2").set("T0", "1/f0", "\u5468\u671f");
    model.param("par2").set("kp", "omega0/cp_steel", "\u94a2\u7684\u7eb5\u5411\u6ce2\u6570");
    model.param("par2").set("ks", "omega0/cs_steel", "\u94a2\u7684\u526a\u5207\u6ce2\u6570");
    model.param("par2")
         .set("v_lamb", "0.728*cs_steel", "\u5de5\u4f5c\u9891\u7387\u7684\u9884\u671f A0 \u5170\u59c6\u6a21\u5f0f\u901f\u5ea6");
    model.param("par2").label("\u53c2\u6570\uff1a\u6a21\u578b\u53c2\u6570");

    model.material().create("mat1", "Common", "");
    model.material("mat1").label("\u94a2");
    model.material("mat1").propertyGroup("def").set("density", new String[]{"rho_steel"});
    model.material("mat1").propertyGroup().create("CpCs", "CpCs", "Pressure_wave_and_shear_wave_speeds");
    model.material("mat1").propertyGroup("CpCs").set("cp", new String[]{"cp_steel"});
    model.material("mat1").propertyGroup("CpCs").set("cs", new String[]{"cs_steel"});
    model.material().create("mat2", "Common", "");
    model.material("mat2").label("\u5851\u6599");
    model.material("mat2").propertyGroup("def").set("density", new String[]{"rho_plast"});
    model.material("mat2").propertyGroup().create("CpCs", "CpCs", "Pressure_wave_and_shear_wave_speeds");
    model.material("mat2").propertyGroup("CpCs").set("cp", new String[]{"cp_plast"});
    model.material("mat2").propertyGroup("CpCs").set("cs", new String[]{"cs_plast"});

    model.component().create("comp1", true);

    model.component("comp1").geom().create("geom1", 2);

    model.component("comp1").mesh().create("mesh1");

    model.component("comp1").geom("geom1").create("r1", "Rectangle");
    model.component("comp1").geom("geom1").feature("r1").set("size", new String[]{"W_plate", "D_plate"});
    model.component("comp1").geom("geom1").feature("r1").set("base", "center");
    model.component("comp1").geom("geom1").runPre("fin");
    model.component("comp1").geom("geom1").run();

    model.component("comp1").material().create("matlnk1", "Link");
    model.component("comp1").material("matlnk1").label("\u94a2");

    model.component("comp1").physics().create("solid", "SolidMechanics", "geom1");
    model.component("comp1").physics("solid").feature("lemm1").set("IsotropicOption", "CpCs");

    model.component("comp1").mesh("mesh1").create("map1", "Map");
    model.component("comp1").mesh("mesh1").feature("size").set("hauto", 2);
    model.component("comp1").mesh("mesh1").run();

    model.result().setOnlyPlotWhenRequested(true);

    model.study().create("std1");
    model.study("std1").create("mode", "ModeAnalysis");
    model.study("std1").feature("mode").set("modeFreq", "100[Hz]");
    model.study("std1").feature("mode").set("eigunit", "");
    model.study("std1").feature("mode").set("chkeigregion", true);
    model.study("std1").feature("mode").set("storefact", false);
    model.study("std1").feature("mode").set("solnum", "auto");
    model.study("std1").feature("mode").set("notsolnum", "auto");
    model.study("std1").feature("mode").set("outputmap", new String[]{});
    model.study("std1").feature("mode").set("ngenAUX", "1");
    model.study("std1").feature("mode").set("goalngenAUX", "1");
    model.study("std1").feature("mode").set("ngenAUX", "1");
    model.study("std1").feature("mode").set("goalngenAUX", "1");
    model.study("std1").feature("mode").setSolveFor("/physics/solid", true);
    model.study("std1").label("\u7814\u7a76 1 - \u6a21\u5f0f\u5206\u6790");
    model.study("std1").setGenPlots(false);
    model.study("std1").feature("mode").set("modeFreq", "f0");
    model.study("std1").feature("mode").set("neigsactive", true);
    model.study("std1").feature("mode").set("neigs", 20);
    model.study("std1").feature("mode").set("eigunit", "rad/m");
    model.study("std1").feature("mode").set("shiftactive", true);
    model.study("std1").feature("mode").set("shift", "ks");
    model.study("std1").create("param", "Parametric");
    model.study("std1").feature("param").setIndex("pname", "alpha", 0);
    model.study("std1").feature("param").setIndex("plistarr", "", 0);
    model.study("std1").feature("param").setIndex("punit", "rad", 0);
    model.study("std1").feature("param").setIndex("pname", "alpha", 0);
    model.study("std1").feature("param").setIndex("plistarr", "", 0);
    model.study("std1").feature("param").setIndex("punit", "rad", 0);
    model.study("std1").feature("param").setIndex("pname", "f0", 0);
    model.study("std1").feature("param").setIndex("plistarr", "range(fmax/250, fmax/250, fmax)", 0);
    model.study("std1").createAutoSequences("all");

    model.sol().create("sol2");
    model.sol("sol2").study("std1");
    model.sol("sol2").label("\u53c2\u6570\u5316\u89e3 1");

    model.batch("p1").feature("so1").set("psol", "sol2");
    model.batch("p1").run("compute");

    model.result().create("pg1", "PlotGroup1D");
    model.result("pg1").label("\u8272\u6563\u66f2\u7ebf\uff0c\u76f8\u901f\u5ea6");
    model.result("pg1").set("data", "dset2");
    model.result("pg1").set("titletype", "label");
    model.result("pg1").set("xlabelactive", true);
    model.result("pg1").set("xlabel", "f (Hz)");
    model.result("pg1").set("ylabelactive", true);
    model.result("pg1").set("ylabel", "v/cs (1)");
    model.result("pg1").set("axislimits", true);
    model.result("pg1").set("xmin", 0);
    model.result("pg1").set("xmax", "fmax");
    model.result("pg1").set("ymin", 0);
    model.result("pg1").set("ymax", "2*cp_steel/cs_steel");
    model.result("pg1").set("showlegends", false);
    model.result("pg1").create("glob1", "Global");
    model.result("pg1").feature("glob1").set("markerpos", "datapoints");
    model.result("pg1").feature("glob1").set("linewidth", "preference");
    model.result("pg1").feature("glob1").set("data", "dset2");
    model.result("pg1").feature("glob1").setIndex("looplevelinput", "first", 0);
    model.result("pg1").feature("glob1").setIndex("expr", "cp_steel/cs_steel", 0);
    model.result("pg1").feature("glob1").setIndex("descr", "\u76f8\u5bf9\u7eb5\u5411\u6ce2\u901f", 0);
    model.result("pg1").feature("glob1").setIndex("expr", 1, 1);
    model.result("pg1").feature("glob1").setIndex("descr", "\u76f8\u5bf9\u526a\u5207\u6ce2\u901f", 1);
    model.result("pg1").feature("glob1").set("xdata", "expr");
    model.result("pg1").feature("glob1").set("xdataexpr", "f0");
    model.result("pg1").feature("glob1").set("linestyle", "none");
    model.result("pg1").feature("glob1").set("linecolor", "red");
    model.result("pg1").feature("glob1").set("linemarker", "circle");
    model.result("pg1").create("glob2", "Global");
    model.result("pg1").feature("glob2").set("markerpos", "datapoints");
    model.result("pg1").feature("glob2").set("linewidth", "preference");
    model.result("pg1").feature("glob2").setIndex("expr", "omega0/solid.kn/cs_steel", 0);
    model.result("pg1").feature("glob2").setIndex("unit", 1, 0);
    model.result("pg1").feature("glob2").setIndex("descr", "\u76f8\u5bf9\u9762\u5916\u6ce2\u901f", 0);
    model.result("pg1").feature("glob2").set("xdata", "expr");
    model.result("pg1").feature("glob2").set("xdataexpr", "f0");
    model.result("pg1").feature("glob2").set("linestyle", "none");
    model.result("pg1").feature("glob2").set("linecolor", "black");
    model.result("pg1").feature("glob2").set("linemarker", "point");
    model.result("pg1").feature("glob2").create("filt1", "GlobalFilter");
    model.result("pg1").feature("glob2").feature("filt1").set("expr", "(abs(imag(solid.kn))<1)&&(real(solid.kn)>0)");
    model.result("pg1").run();
    model.result().duplicate("pg2", "pg1");
    model.result("pg2").label("\u8272\u6563\u66f2\u7ebf\uff0c\u9762\u5916\u6ce2\u6570");
    model.result("pg2").set("ylabel", "kn (1/m)");
    model.result("pg2").set("ymax", "omegamax/cs_steel");
    model.result("pg2").feature("glob1").setIndex("expr", "kp", 0);
    model.result("pg2").feature("glob1").setIndex("descr", "\u94a2\u4e2d\u7684\u7eb5\u5411\u6ce2\u6570", 0);
    model.result("pg2").feature("glob1").setIndex("expr", "ks", 1);
    model.result("pg2").feature("glob1").setIndex("descr", "\u94a2\u4e2d\u7684\u526a\u5207\u6ce2\u6570", 1);
    model.result("pg2").feature("glob2").setIndex("expr", "solid.kn", 0);
    model.result("pg2").feature("glob2").setIndex("unit", "1/m", 0);
    model.result("pg2").feature("glob2").setIndex("descr", "\u9762\u5916\u6ce2\u6570", 0);
    model.result("pg2").run();
    model.result().dataset().create("extr1", "Extrude2D");
    model.result().dataset("extr1").set("data", "dset2");
    model.result().dataset("extr1").set("zmax", "10[cm]");
    model.result().dataset("extr1").set("res", 100);
    model.result().dataset("extr1").set("wavenumber", "solid.kn");
    model.result().create("pg3", "PlotGroup3D");
    model.result("pg3").label("\u632f\u578b");
    model.result("pg3").set("looplevel", new int[]{15, 100});
    model.result("pg3").set("titletype", "manual");
    model.result("pg3")
         .set("paramindicator", "kn = eval(real(solid.kn)) [1/m], v/cs = eval(omega0/real(solid.kn)/cs_steel)");
    model.result("pg3").create("surf1", "Surface");
    model.result("pg3").feature("surf1").set("colortable", "Prism");
    model.result("pg3").feature("surf1").create("def1", "Deform");
    model.result("pg3").set("view", "new");
    model.result("pg3").set("looplevel", new int[]{17, 100});
    model.result("pg3").run();
    model.result("pg3").set("looplevel", new int[]{16, 100});
    model.result("pg3").run();
    model.result("pg3").set("looplevel", new int[]{15, 100});
    model.result("pg3").run();
    model.result("pg3").set("looplevel", new int[]{20, 100});
    model.result("pg3").run();

    model.component().create("comp2", true);

    model.component("comp2").geom().create("geom2", 3);
    model.component("comp2").geom("geom2").geomRep("comsol");

    model.component("comp2").mesh().create("mesh2");
    model.component("comp2").mesh("mesh2").contribute("geom/detail", true);

    model.component("comp2").geom("geom2").insertFile("lamb_waves_ndt_plate_geom_sequence.mph", "geom1");
    model.component("comp2").geom("geom2").run("igf1");

    model.component("comp2").func().create("rect1", "Rectangle");
    model.component("comp2").func("rect1").set("lower", 0);
    model.component("comp2").func("rect1").set("upper", "4*T0");
    model.component("comp2").func("rect1").set("smoothactive", false);
    model.component("comp2").func().create("an1", "Analytic");
    model.component("comp2").func("an1").label("\u6cd5\u5411\u901f\u5ea6\u6e90");
    model.component("comp2").func("an1").set("funcname", "vn");
    model.component("comp2").func("an1").set("expr", "sin(omega0*t)*(1 - cos(omega0*t/4))*rect1(t)");
    model.component("comp2").func("an1").set("args", "t");
    model.component("comp2").func("an1").set("fununit", "m/s");
    model.component("comp2").func("an1").setIndex("argunit", "s", 0);
    model.component("comp2").func("an1").setIndex("plotargs", "10*T0", 0, 2);

    model.component("comp2").selection().create("sel1", "Explicit");
    model.component("comp2").selection("sel1").label("\u6954\u5757");
    model.component("comp2").selection("sel1").set(1);
    model.component("comp2").selection().create("sel2", "Explicit");
    model.component("comp2").selection("sel2").label("\u677f");
    model.component("comp2").selection("sel2").set(2, 3, 4);
    model.component("comp2").selection().create("sel3", "Explicit");
    model.component("comp2").selection("sel3").label("AL");
    model.component("comp2").selection("sel3").set(2, 4);
    model.component("comp2").selection().create("sel4", "Explicit");
    model.component("comp2").selection("sel4").geom(0);
    model.component("comp2").selection("sel4").set(27, 28, 42, 44);
    model.component("comp2").selection("sel4").label("\u63a2\u9488");
    model.component("comp2").selection().create("adj1", "Adjacent");
    model.component("comp2").selection("adj1").label("\u5916\u90e8\u8fb9\u754c");
    model.component("comp2").selection("adj1").set("input", new String[]{"sel1", "sel2"});

    model.component("comp2").pair().create("p1", "Identity");
    model.component("comp2").pair("p1").source().set(23);
    model.component("comp2").pair("p1").destination().set(7);

    model.component("comp2").material().create("matlnk2", "Link");
    model.component("comp2").material("matlnk2").selection().named("sel2");
    model.component("comp2").material("matlnk2").label("\u94a2");
    model.component("comp2").material().create("matlnk3", "Link");
    model.component("comp2").material("matlnk3").selection().named("sel1");
    model.component("comp2").material("matlnk3").set("link", "mat2");
    model.component("comp2").material("matlnk3").label("\u5851\u6599");

    model.component("comp2").physics().create("elte", "ElasticWavesTimeExplicit", "geom2");

    model.study("std1").feature("mode").setSolveFor("/physics/elte", false);

    model.component("comp2").physics("elte").feature("eltem1").create("cdisp1", "ComputeDisplacement", 0);
    model.component("comp2").physics("elte").feature("eltem1").feature("cdisp1").selection().named("sel4");
    model.component("comp2").physics("elte").create("vel1", "PrescribedVelocity", 2);
    model.component("comp2").physics("elte").feature("vel1").selection().set(8);
    model.component("comp2").physics("elte").feature("vel1").set("coordinateSystem", "sys2");
    model.component("comp2").physics("elte").feature("vel1").set("v", new String[]{"0", "0", "vn(t)"});
    model.component("comp2").physics("elte").create("lrb1", "LowReflectingBoundary", 2);
    model.component("comp2").physics("elte").feature("lrb1").selection().set(1, 4, 6, 10, 13, 20);
    model.component("comp2").physics("elte").create("frac1", "Fracture", 2);
    model.component("comp2").physics("elte").feature("frac1").selection().set(26);

    model.component("comp2").probe().create("point1", "Point");
    model.component("comp2").probe("point1").selection().set(42);
    model.component("comp2").probe("point1").set("expr", "elte.uy");
    model.component("comp2").probe("point1").set("descractive", true);
    model.component("comp2").probe("point1").set("descr", "uy");
    model.component("comp2").probe().duplicate("point2", "point1");
    model.component("comp2").probe("point2").selection().set(27);
    model.component("comp2").probe().duplicate("point3", "point2");
    model.component("comp2").probe("point3").selection().set(44);
    model.component("comp2").probe().duplicate("point4", "point3");
    model.component("comp2").probe("point4").selection().set(28);

    model.nodeGroup().create("grp1", "Definitions", "comp2");
    model.nodeGroup("grp1").set("type", "probe");
    model.nodeGroup("grp1").add("probe", "point1");
    model.nodeGroup("grp1").add("probe", "point2");
    model.nodeGroup("grp1").add("probe", "point3");
    model.nodeGroup("grp1").add("probe", "point4");
    model.nodeGroup("grp1").label("y \u65b9\u5411\u4f4d\u79fb");

    model.component("comp2").coordSystem().create("ab1", "AbsorbingLayer");
    model.component("comp2").coordSystem("ab1").selection().named("sel3");

    model.component("comp2").mesh("mesh2").create("map1", "Map");
    model.component("comp2").mesh("mesh2").feature("map1").selection().set(13);
    model.component("comp2").mesh("mesh2").create("swe1", "Sweep");
    model.component("comp2").mesh("mesh2").feature("swe1").selection().geom("geom2", 3);
    model.component("comp2").mesh("mesh2").feature("swe1").selection().named("sel2");
    model.component("comp2").mesh("mesh2").feature("size").set("custom", true);
    model.component("comp2").mesh("mesh2").feature("size").set("hmax", "v_lamb/(1.5*2*f0)");
    model.component("comp2").mesh("mesh2").create("ftet1", "FreeTet");
    model.component("comp2").mesh("mesh2").feature("ftet1").create("size1", "Size");
    model.component("comp2").mesh("mesh2").feature("ftet1").feature("size1").set("custom", true);
    model.component("comp2").mesh("mesh2").feature("ftet1").feature("size1").set("hmaxactive", true);
    model.component("comp2").mesh("mesh2").feature("ftet1").feature("size1").set("hmax", "cp_plast/(1.5*2*f0)");
    model.component("comp2").mesh("mesh2").feature("ftet1").set("optlevel", "high");
    model.component("comp2").mesh("mesh2").feature("ftet1").set("optsmall", true);
    model.component("comp2").mesh("mesh2").run();

    model.study().create("std2");
    model.study("std2").create("time", "Transient");
    model.study("std2").feature("time").setSolveFor("/physics/solid", false);
    model.study("std2").feature("time").setSolveFor("/physics/elte", true);
    model.study("std2").label("\u7814\u7a76 2 - \u6ce2\u4f20\u64ad");
    model.study("std2").feature("time").set("tlist", "range(0, T0, 45*T0)");
    model.study("std2").feature("time").setEntry("outputmap", "elte", "selection");
    model.study("std2").feature("time").setEntry("outputselectionmap", "elte", "adj1");
    model.study("std2").createAutoSequences("all");

    model.component("comp2").probe("point1").genResult("none");
    model.component("comp2").probe("point2").genResult("none");
    model.component("comp2").probe("point3").genResult("none");
    model.component("comp2").probe("point4").genResult("none");

    model.sol("sol253").runAll();

    model.result().create("pg5", "PlotGroup3D");
    model.result("pg5").label("\u901f\u5ea6\u5927\u5c0f (elte)");
    model.result("pg5").set("showlegendsunit", true);
    model.result("pg5").feature().create("surf1", "Surface");
    model.result("pg5").feature("surf1").set("resolution", "custom");
    model.result("pg5").feature("surf1").set("refine", 6);
    model.result("pg5").feature("surf1").set("smooth", "internal");
    model.result("pg5").feature("surf1").set("data", "parent");
    model.result().create("pg6", "PlotGroup3D");
    model.result("pg6").label("\u538b\u529b (elte)");
    model.result("pg6").set("showlegendsunit", true);
    model.result("pg6").feature().create("surf1", "Surface");
    model.result("pg6").feature("surf1").set("expr", "elte.p");
    model.result("pg6").feature("surf1").set("colortable", "Wave");
    model.result("pg6").feature("surf1").set("colorscalemode", "linearsymmetric");
    model.result("pg6").feature("surf1").set("resolution", "custom");
    model.result("pg6").feature("surf1").set("refine", 6);
    model.result("pg6").feature("surf1").set("smooth", "internal");
    model.result("pg6").feature("surf1").set("data", "parent");
    model.result("pg5").feature("surf1").create("sel1", "Selection");
    model.result("pg5").feature("surf1").feature("sel1").selection().geom("geom2", 3);
    model.result("pg5").feature("surf1").feature("sel1").selection().named("sel2");
    model.result("pg5").feature("surf1").set("colortable", "Prism");
    model.result("pg5").set("view", "new");
    model.result("pg5").setIndex("looplevel", 23, 0);
    model.result("pg5").run();
    model.result("pg5").setIndex("looplevel", 29, 0);
    model.result("pg5").run();
    model.result("pg5").setIndex("looplevel", 35, 0);
    model.result("pg5").run();
    model.result("pg5").setIndex("looplevel", 17, 0);
    model.result("pg5").run();
    model.result("pg4").set("window", "window2");
    model.result("pg4").set("windowtitle", "\u63a2\u9488\u56fe\u201c2\u201d");
    model.result("pg4").label("\u63a2\u9488\u56fe\u4f4d\u79fb");
    model.result("pg4").set("ylabelactive", true);
    model.result("pg4").set("ylabel", "\u5782\u76f4\u4f4d\u79fb (m)");
    model.result("pg4").set("legendlayout", "outside");
    model.result("pg4").set("legendposoutside", "bottom");
    model.result("pg4").set("legendrowcount", 2);
    model.result("pg4").set("window", "window2");
    model.result("pg4").set("windowtitle", "\u63a2\u9488\u56fe\u201c2\u201d");
    model.result("pg4").feature("tblp1").set("plotcolumns", new int[]{2, 3});
    model.result().create("pg7", "PlotGroup1D");
    model.result("pg7").label("\u901f\u5ea6\uff0cy \u5206\u91cf");
    model.result("pg7").set("data", "dset4");
    model.result("pg7").setIndex("looplevelinput", "manual", 0);
    model.result("pg7").setIndex("looplevel", new int[]{17}, 0);
    model.result("pg7").set("titletype", "label");
    model.result("pg7").create("lngr1", "LineGraph");
    model.result("pg7").feature("lngr1").set("markerpos", "datapoints");
    model.result("pg7").feature("lngr1").set("linewidth", "preference");
    model.result("pg7").feature("lngr1").selection().set(43, 45, 46);
    model.result("pg7").feature("lngr1").set("expr", "v2y");
    model.result("pg7").feature("lngr1").set("xdata", "expr");
    model.result("pg7").feature("lngr1").set("xdataexpr", "z");
    model.result("pg7").feature("lngr1").set("legend", true);
    model.result("pg7").feature("lngr1").set("legendmethod", "manual");
    model.result("pg7").feature("lngr1").setIndex("legends", "\u4e0a\u4fa7", 0);
    model.result("pg7").feature().duplicate("lngr2", "lngr1");
    model.result("pg7").feature("lngr2").selection().set(29);
    model.result("pg7").feature("lngr2").setIndex("legends", "\u4e0b\u4fa7", 0);
    model.result("pg7").run();
    model.result().duplicate("pg8", "pg7");
    model.result("pg8").label("\u901f\u5ea6\uff0cz \u5206\u91cf");
    model.result("pg8").feature("lngr1").set("expr", "v2z");
    model.result("pg8").feature("lngr2").set("expr", "v2z");
    model.result("pg8").run();

    model.title("\u4ea7\u751f\u5170\u59c6\u6ce2\u7528\u4e8e\u677f\u6750\u8bd5\u6837\u7684\u65e0\u635f\u68c0\u6d4b");

    model
         .description("\u5170\u59c6\u6ce2\u4f5c\u4e3a\u4e00\u79cd\u5bfc\u6ce2\uff0c\u5176\u6570\u503c\u5efa\u6a21\u5bf9\u4e8e\u5206\u6790\u548c\u8bbe\u8ba1\u7528\u4e8e\u957f\u8ddd\u79bb\u8d85\u58f0\u68c0\u6d4b\u7684\u7ed3\u6784\u5065\u5eb7\u76d1\u6d4b (SHM) \u7cfb\u7edf\u81f3\u5173\u91cd\u8981\u3002\u57fa\u4e8e\u5bfc\u6ce2\u7684 SHM \u7cfb\u7edf\u8bbe\u8ba1\u4e3b\u8981\u5305\u542b\u4e24\u4e2a\u90e8\u5206\u3002\u9996\u5148\uff0c\u9700\u8981\u4e86\u89e3\u7279\u5b9a\u622a\u9762\u6ce2\u5bfc\u4e2d\u53ef\u4f20\u64ad\u6a21\u5f0f\u7684\u9891\u6563\u66f2\u7ebf\u3002\u5176\u6b21\uff0c\u5728\u65f6\u57df\u5185\u5206\u6790\u6240\u9009\u6a21\u5f0f\u901a\u8fc7\u6ce2\u5bfc\u7684\u4f20\u64ad\uff0c\u53ca\u5176\u4ece\u622a\u9762\u533a\u57df\u4e2d\u53ef\u80fd\u5b58\u5728\u7684\u4e0d\u89c4\u5219\u6027\uff08\u88c2\u9699\u6216\u8150\u8680\u7f3a\u9677\uff09\u5904\u7684\u53cd\u5c04\u3002\n\n\u672c\u6559\u7a0b\u7814\u7a76\u4e86\u5bfc\u6ce2\u5728\u5177\u6709\u6709\u9650\u5bbd\u5ea6\u548c\u539a\u5ea6\u7684\u94a2\u677f\u4e2d\u7684\u4f20\u64ad\u3002\u901a\u8fc7\u5bf9\u677f\u6750\u4e8c\u7ef4\u6a2a\u622a\u9762\u5e94\u7528\u7684\u201c\u56fa\u4f53\u529b\u5b66\u201d\u7269\u7406\u573a\u63a5\u53e3\u7684\u201c\u6a21\u5f0f\u5206\u6790\u201d\u7814\u7a76\u6765\u8ba1\u7b97\u4f20\u64ad\u6a21\u5f0f\u3002\u8fd9\u79cd\u65b9\u6cd5\u6709\u65f6\u4e5f\u79f0\u4e3a\u534a\u89e3\u6790\u6709\u9650\u5143 (SAFE) \u6cd5\u3002\u672c\u4f8b\u4f7f\u7528\u6954\u5757\u5f15\u5165\u89d2\u675f\u6ce2\u5728\u5e26\u6709\u7f3a\u9677\u7684\u677f\u4e2d\u6fc0\u53d1\u6240\u9700\u7684\u6a21\u5f0f\uff0c\u8fd9\u4e00\u8fc7\u7a0b\u901a\u8fc7\u201c\u5f39\u6027\u6ce2\uff0c\u65f6\u57df\u663e\u5f0f\u201d\u7269\u7406\u573a\u63a5\u53e3\u5728\u4e09\u7ef4\u4e2d\u8fdb\u884c\u5efa\u6a21\u3002");

    model.mesh().clearMeshes();

    model.sol("sol1").clearSolutionData();
    model.sol("sol2").clearSolutionData();
    model.sol("sol3").clearSolutionData();
    model.sol("sol4").clearSolutionData();
    model.sol("sol5").clearSolutionData();
    model.sol("sol6").clearSolutionData();
    model.sol("sol7").clearSolutionData();
    model.sol("sol8").clearSolutionData();
    model.sol("sol9").clearSolutionData();
    model.sol("sol10").clearSolutionData();
    model.sol("sol11").clearSolutionData();
    model.sol("sol12").clearSolutionData();
    model.sol("sol13").clearSolutionData();
    model.sol("sol14").clearSolutionData();
    model.sol("sol15").clearSolutionData();
    model.sol("sol16").clearSolutionData();
    model.sol("sol17").clearSolutionData();
    model.sol("sol18").clearSolutionData();
    model.sol("sol19").clearSolutionData();
    model.sol("sol20").clearSolutionData();
    model.sol("sol21").clearSolutionData();
    model.sol("sol22").clearSolutionData();
    model.sol("sol23").clearSolutionData();
    model.sol("sol24").clearSolutionData();
    model.sol("sol25").clearSolutionData();
    model.sol("sol26").clearSolutionData();
    model.sol("sol27").clearSolutionData();
    model.sol("sol28").clearSolutionData();
    model.sol("sol29").clearSolutionData();
    model.sol("sol30").clearSolutionData();
    model.sol("sol31").clearSolutionData();
    model.sol("sol32").clearSolutionData();
    model.sol("sol33").clearSolutionData();
    model.sol("sol34").clearSolutionData();
    model.sol("sol35").clearSolutionData();
    model.sol("sol36").clearSolutionData();
    model.sol("sol37").clearSolutionData();
    model.sol("sol38").clearSolutionData();
    model.sol("sol39").clearSolutionData();
    model.sol("sol40").clearSolutionData();
    model.sol("sol41").clearSolutionData();
    model.sol("sol42").clearSolutionData();
    model.sol("sol43").clearSolutionData();
    model.sol("sol44").clearSolutionData();
    model.sol("sol45").clearSolutionData();
    model.sol("sol46").clearSolutionData();
    model.sol("sol47").clearSolutionData();
    model.sol("sol48").clearSolutionData();
    model.sol("sol49").clearSolutionData();
    model.sol("sol50").clearSolutionData();
    model.sol("sol51").clearSolutionData();
    model.sol("sol52").clearSolutionData();
    model.sol("sol53").clearSolutionData();
    model.sol("sol54").clearSolutionData();
    model.sol("sol55").clearSolutionData();
    model.sol("sol56").clearSolutionData();
    model.sol("sol57").clearSolutionData();
    model.sol("sol58").clearSolutionData();
    model.sol("sol59").clearSolutionData();
    model.sol("sol60").clearSolutionData();
    model.sol("sol61").clearSolutionData();
    model.sol("sol62").clearSolutionData();
    model.sol("sol63").clearSolutionData();
    model.sol("sol64").clearSolutionData();
    model.sol("sol65").clearSolutionData();
    model.sol("sol66").clearSolutionData();
    model.sol("sol67").clearSolutionData();
    model.sol("sol68").clearSolutionData();
    model.sol("sol69").clearSolutionData();
    model.sol("sol70").clearSolutionData();
    model.sol("sol71").clearSolutionData();
    model.sol("sol72").clearSolutionData();
    model.sol("sol73").clearSolutionData();
    model.sol("sol74").clearSolutionData();
    model.sol("sol75").clearSolutionData();
    model.sol("sol76").clearSolutionData();
    model.sol("sol77").clearSolutionData();
    model.sol("sol78").clearSolutionData();
    model.sol("sol79").clearSolutionData();
    model.sol("sol80").clearSolutionData();
    model.sol("sol81").clearSolutionData();
    model.sol("sol82").clearSolutionData();
    model.sol("sol83").clearSolutionData();
    model.sol("sol84").clearSolutionData();
    model.sol("sol85").clearSolutionData();
    model.sol("sol86").clearSolutionData();
    model.sol("sol87").clearSolutionData();
    model.sol("sol88").clearSolutionData();
    model.sol("sol89").clearSolutionData();
    model.sol("sol90").clearSolutionData();
    model.sol("sol91").clearSolutionData();
    model.sol("sol92").clearSolutionData();
    model.sol("sol93").clearSolutionData();
    model.sol("sol94").clearSolutionData();
    model.sol("sol95").clearSolutionData();
    model.sol("sol96").clearSolutionData();
    model.sol("sol97").clearSolutionData();
    model.sol("sol98").clearSolutionData();
    model.sol("sol99").clearSolutionData();
    model.sol("sol100").clearSolutionData();
    model.sol("sol101").clearSolutionData();
    model.sol("sol102").clearSolutionData();
    model.sol("sol103").clearSolutionData();
    model.sol("sol104").clearSolutionData();
    model.sol("sol105").clearSolutionData();
    model.sol("sol106").clearSolutionData();
    model.sol("sol107").clearSolutionData();
    model.sol("sol108").clearSolutionData();
    model.sol("sol109").clearSolutionData();
    model.sol("sol110").clearSolutionData();
    model.sol("sol111").clearSolutionData();
    model.sol("sol112").clearSolutionData();
    model.sol("sol113").clearSolutionData();
    model.sol("sol114").clearSolutionData();
    model.sol("sol115").clearSolutionData();
    model.sol("sol116").clearSolutionData();
    model.sol("sol117").clearSolutionData();
    model.sol("sol118").clearSolutionData();
    model.sol("sol119").clearSolutionData();
    model.sol("sol120").clearSolutionData();
    model.sol("sol121").clearSolutionData();
    model.sol("sol122").clearSolutionData();
    model.sol("sol123").clearSolutionData();
    model.sol("sol124").clearSolutionData();
    model.sol("sol125").clearSolutionData();
    model.sol("sol126").clearSolutionData();
    model.sol("sol127").clearSolutionData();
    model.sol("sol128").clearSolutionData();
    model.sol("sol129").clearSolutionData();
    model.sol("sol130").clearSolutionData();
    model.sol("sol131").clearSolutionData();
    model.sol("sol132").clearSolutionData();
    model.sol("sol133").clearSolutionData();
    model.sol("sol134").clearSolutionData();
    model.sol("sol135").clearSolutionData();
    model.sol("sol136").clearSolutionData();
    model.sol("sol137").clearSolutionData();
    model.sol("sol138").clearSolutionData();
    model.sol("sol139").clearSolutionData();
    model.sol("sol140").clearSolutionData();
    model.sol("sol141").clearSolutionData();
    model.sol("sol142").clearSolutionData();
    model.sol("sol143").clearSolutionData();
    model.sol("sol144").clearSolutionData();
    model.sol("sol145").clearSolutionData();

    return model;
  }

  public static Model run2(Model model) {
    model.sol("sol146").clearSolutionData();
    model.sol("sol147").clearSolutionData();
    model.sol("sol148").clearSolutionData();
    model.sol("sol149").clearSolutionData();
    model.sol("sol150").clearSolutionData();
    model.sol("sol151").clearSolutionData();
    model.sol("sol152").clearSolutionData();
    model.sol("sol153").clearSolutionData();
    model.sol("sol154").clearSolutionData();
    model.sol("sol155").clearSolutionData();
    model.sol("sol156").clearSolutionData();
    model.sol("sol157").clearSolutionData();
    model.sol("sol158").clearSolutionData();
    model.sol("sol159").clearSolutionData();
    model.sol("sol160").clearSolutionData();
    model.sol("sol161").clearSolutionData();
    model.sol("sol162").clearSolutionData();
    model.sol("sol163").clearSolutionData();
    model.sol("sol164").clearSolutionData();
    model.sol("sol165").clearSolutionData();
    model.sol("sol166").clearSolutionData();
    model.sol("sol167").clearSolutionData();
    model.sol("sol168").clearSolutionData();
    model.sol("sol169").clearSolutionData();
    model.sol("sol170").clearSolutionData();
    model.sol("sol171").clearSolutionData();
    model.sol("sol172").clearSolutionData();
    model.sol("sol173").clearSolutionData();
    model.sol("sol174").clearSolutionData();
    model.sol("sol175").clearSolutionData();
    model.sol("sol176").clearSolutionData();
    model.sol("sol177").clearSolutionData();
    model.sol("sol178").clearSolutionData();
    model.sol("sol179").clearSolutionData();
    model.sol("sol180").clearSolutionData();
    model.sol("sol181").clearSolutionData();
    model.sol("sol182").clearSolutionData();
    model.sol("sol183").clearSolutionData();
    model.sol("sol184").clearSolutionData();
    model.sol("sol185").clearSolutionData();
    model.sol("sol186").clearSolutionData();
    model.sol("sol187").clearSolutionData();
    model.sol("sol188").clearSolutionData();
    model.sol("sol189").clearSolutionData();
    model.sol("sol190").clearSolutionData();
    model.sol("sol191").clearSolutionData();
    model.sol("sol192").clearSolutionData();
    model.sol("sol193").clearSolutionData();
    model.sol("sol194").clearSolutionData();
    model.sol("sol195").clearSolutionData();
    model.sol("sol196").clearSolutionData();
    model.sol("sol197").clearSolutionData();
    model.sol("sol198").clearSolutionData();
    model.sol("sol199").clearSolutionData();
    model.sol("sol200").clearSolutionData();
    model.sol("sol201").clearSolutionData();
    model.sol("sol202").clearSolutionData();
    model.sol("sol203").clearSolutionData();
    model.sol("sol204").clearSolutionData();
    model.sol("sol205").clearSolutionData();
    model.sol("sol206").clearSolutionData();
    model.sol("sol207").clearSolutionData();
    model.sol("sol208").clearSolutionData();
    model.sol("sol209").clearSolutionData();
    model.sol("sol210").clearSolutionData();
    model.sol("sol211").clearSolutionData();
    model.sol("sol212").clearSolutionData();
    model.sol("sol213").clearSolutionData();
    model.sol("sol214").clearSolutionData();
    model.sol("sol215").clearSolutionData();
    model.sol("sol216").clearSolutionData();
    model.sol("sol217").clearSolutionData();
    model.sol("sol218").clearSolutionData();
    model.sol("sol219").clearSolutionData();
    model.sol("sol220").clearSolutionData();
    model.sol("sol221").clearSolutionData();
    model.sol("sol222").clearSolutionData();
    model.sol("sol223").clearSolutionData();
    model.sol("sol224").clearSolutionData();
    model.sol("sol225").clearSolutionData();
    model.sol("sol226").clearSolutionData();
    model.sol("sol227").clearSolutionData();
    model.sol("sol228").clearSolutionData();
    model.sol("sol229").clearSolutionData();
    model.sol("sol230").clearSolutionData();
    model.sol("sol231").clearSolutionData();
    model.sol("sol232").clearSolutionData();
    model.sol("sol233").clearSolutionData();
    model.sol("sol234").clearSolutionData();
    model.sol("sol235").clearSolutionData();
    model.sol("sol236").clearSolutionData();
    model.sol("sol237").clearSolutionData();
    model.sol("sol238").clearSolutionData();
    model.sol("sol239").clearSolutionData();
    model.sol("sol240").clearSolutionData();
    model.sol("sol241").clearSolutionData();
    model.sol("sol242").clearSolutionData();
    model.sol("sol243").clearSolutionData();
    model.sol("sol244").clearSolutionData();
    model.sol("sol245").clearSolutionData();
    model.sol("sol246").clearSolutionData();
    model.sol("sol247").clearSolutionData();
    model.sol("sol248").clearSolutionData();
    model.sol("sol249").clearSolutionData();
    model.sol("sol250").clearSolutionData();
    model.sol("sol251").clearSolutionData();
    model.sol("sol252").clearSolutionData();
    model.sol("sol253").clearSolutionData();

    model.label("lamb_waves_ndt_plate.mph");

    return model;
  }

  public static void main(String[] args) {
    Model model = run();
    run2(model);
  }

}
