/*
 * diesel_filter.java
 */

import com.comsol.model.*;
import com.comsol.model.util.*;

/** Model exported on Apr 30 2026, 09:26 by COMSOL 6.3.0.290. */
public class diesel_filter {

  public static Model run() {
    Model model = ModelUtil.create("Model");

    model
         .modelPath("D:\\Program Files\\COMSOL\\COMSOL63\\Multiphysics\\applications\\Chemical_Reaction_Engineering_Module\\Reactors_with_Porous_Catalysts");

    model.component().create("comp1", true);

    model.component("comp1").physics().create("re", "ReactionEng");

    model.study().create("std1");
    model.study("std1").create("spf", "StationaryPlugflow");
    model.study("std1").feature("spf").set("solnum", "auto");
    model.study("std1").feature("spf").set("notsolnum", "auto");
    model.study("std1").feature("spf").set("outputmap", new String[]{});
    model.study("std1").feature("spf").setSolveFor("/physics/re", true);

//    To import content from file, use:
//    model.param().loadFile("FILENAME");
    model.param().set("L", "0.15[m]", "\u53cd\u5e94\u5668\u901a\u9053\u957f\u5ea6");
    model.param().set("v_inlet", "2.5[m^3/s]", "\u5165\u53e3\u4f53\u79ef\u6d41\u91cf");
    model.param().set("ku", "-2.5[m/s]/L", "\u6bd4\u4f8b\u5e38\u6570");
    model.param().set("H", "1.27e-3[m]", "\u901a\u9053\u9ad8\u5ea6");
    model.param().set("Hf", "4.5e-4[m]", "\u6ee4\u6e05\u5668\u58c1\u539a");
    model.param().set("dHs", "50[um]", "\u521d\u59cb\u70df\u7070\u5c42\u539a\u5ea6");
    model.param()
         .set("uf", "2.5[m/s]*H/L", "\u6c14\u6001\u7269\u8d28\u6d41\u8fc7\u6ee4\u6e05\u5668\u7684\u901f\u5ea6");
    model.param().set("Sa", "5e-5/H", "\u8868\u9762\u79ef\u56e0\u5b50");
    model.param().set("C_inlet", "1[mol/m^3]", "\u5165\u53e3\u6d53\u5ea6\uff0c\u78b3");
    model.param().set("cs_total", "1[mol/m^3]", "\u603b\u6d53\u5ea6\uff0c\u56fa\u4f53\u50ac\u5316\u7269\u8d28");
    model.param().set("x_CeO2", "1", "\u6469\u5c14\u5206\u6570\uff0c\u50ac\u5316\u7269\u8d28 ceo2");
    model.param().set("x_Ce2O3", "0", "\u6469\u5c14\u5206\u6570\uff0c\u50ac\u5316\u7269\u8d28 ce2o3");
    model.param().set("CeO2_inlet", "cs_total*x_CeO2", "\u5165\u53e3\u6d53\u5ea6\uff0cceo2");
    model.param().set("Ce2O3_inlet", "cs_total*x_Ce2O3", "\u5165\u53e3\u6d53\u5ea6\uff0cce2o3");
    model.param().set("F_CO_inlet", "0[mol/s]", "\u5165\u53e3\u6d53\u5ea6\uff0cCO");
    model.param().set("F_CO2_inlet", "3.812[mol/s]", "\u5165\u53e3\u6d53\u5ea6\uff0cCO2");
    model.param().set("F_N2_inlet", "68.525[mol/s]", "\u5165\u53e3\u6d53\u5ea6\uff0cN2");
    model.param().set("F_O2_inlet", "7.625[mol/s]", "\u5165\u53e3\u6d53\u5ea6\uff0cO2");
    model.param().set("T0", "653[K]", "\u521d\u59cb\u6e29\u5ea6");
    model.param().set("kappa_m", "1e-11[m^2]", "\u6ee4\u6e05\u5668\u58c1\u7684\u6e17\u900f\u7387");
    model.param().set("kappa_s", "1e-13[m^2]", "\u70df\u7070\u5c42\u7684\u6e17\u900f\u7387");
    model.param().set("Tin", "550[K]", "\u6ee4\u6e05\u5668\u4e2d\u7684\u521d\u59cb\u6e29\u5ea6");
    model.param().set("poro", "0.5", "\u5b54\u9699\u7387");
    model.param().set("paco", "5e-4[kg/m^3]", "\u6d41\u52a8\u65f6\u7684\u9897\u7c92\u5bc6\u5ea6");
    model.param().set("Mc", "12e-3[kg/mol]", "\u6469\u5c14\u8d28\u91cf\uff0c\u70df\u7070\uff08\u78b3\uff09");
    model.param().set("dHsoot", "5e-5[m]", "\u521d\u59cb\u70df\u7070\u5c42\u539a\u5ea6");
    model.param().set("Cp_s", "1510[J/kg/K]", "\u6df7\u5408\u7269\u70ed\u5bb9\uff0c\u70df\u7070");
    model.param().set("Cp_m", "1120[J/kg/K]", "\u6df7\u5408\u7269\u70ed\u5bb9\uff0c\u6ee4\u6e05\u5668\u58c1");
    model.param().set("k_s", "2.1[W/m/K]", "\u6df7\u5408\u7269\u5bfc\u70ed\u7cfb\u6570\uff0c\u70df\u7070\u5c42");
    model.param()
         .set("k_m", "0.85[W/m/K]", "\u6df7\u5408\u7269\u5bfc\u70ed\u7cfb\u6570\uff0c\u6ee4\u6e05\u5668\u58c1");
    model.param().set("rho_s", "1920[kg/m^3]", "\u70df\u7070\u5c42\u5bc6\u5ea6");
    model.param().set("rho_m", "1400[kg/m^3]", "\u6df7\u5408\u7269\u5bc6\u5ea6\uff0c\u6ee4\u6e05\u5668\u58c1");

    model.component("comp1").variable().create("var1");
    model.component("comp1").variable("var1").set("v1", "v_inlet+ku*re.Vr");
    model.component("comp1").variable("var1")
         .descr("v1", "\u7ba1\u5f0f\u53cd\u5e94\u5668\u4e2d\u7684\u4f53\u79ef\u6d41\u573a");

    model.component("comp1").physics("re").prop("reactor").set("reactor", "plugflow");
    model.component("comp1").physics("re").prop("energybalance").set("T", "T0");
    model.component("comp1").physics("re").prop("mixture").set("psource", "idealGas");
    model.component("comp1").physics("re").prop("calcTransport").set("calcTransport", true);
    model.component("comp1").physics("re").prop("reactor").set("vplug", "v1");
    model.component("comp1").physics("re").create("rch1", "ReactionChem", -1);
    model.component("comp1").physics("re").feature("rch1").set("formula", "C(s)+O2=>CO2");
    model.component("comp1").physics("re").feature("rch1").set("useArrhenius", true);
    model.component("comp1").physics("re").feature("rch1").set("Af", "1e13[m/s]*Sa");
    model.component("comp1").physics("re").feature("rch1").set("Ef", "165e3[J/mol]");
    model.component("comp1").physics("re").feature("rch1").set("ReactionExpression", "UserDefined");
    model.component("comp1").physics("re").feature("rch1").set("r", "re.kf_1*re.c_O2");
    model.component("comp1").physics("re").feature("rch1").set("bulkFwdOrder", 1);
    model.component("comp1").physics("re").create("rch2", "ReactionChem", -1);
    model.component("comp1").physics("re").feature("rch2").set("formula", "C(s)+0.5O2=>CO");
    model.component("comp1").physics("re").feature("rch2").set("useArrhenius", true);
    model.component("comp1").physics("re").feature("rch2").set("Af", "5.5e10[m/s]*Sa");
    model.component("comp1").physics("re").feature("rch2").set("Ef", "150e3[J/mol]");
    model.component("comp1").physics("re").feature("rch2").set("r", "re.kf_2*re.c_O2");
    model.component("comp1").physics("re").feature("rch2").set("bulkFwdOrder", 1);
    model.component("comp1").physics("re").create("rch3", "ReactionChem", -1);
    model.component("comp1").physics("re").feature("rch3").set("formula", "C(s)+4CeO2(s)=>2Ce2O3(s)+CO2");
    model.component("comp1").physics("re").feature("rch3").set("useArrhenius", true);
    model.component("comp1").physics("re").feature("rch3").set("Af", "4.5e11[m/s]*Sa");
    model.component("comp1").physics("re").feature("rch3").set("Ef", "120e3[J/mol]");
    model.component("comp1").physics("re").feature("rch3").set("ReactionExpression", "UserDefined");
    model.component("comp1").physics("re").feature("rch3").set("r", "re.kf_3*re.c_CeO2_solid");
    model.component("comp1").physics("re").feature("rch3").set("bulkFwdOrder", 1);
    model.component("comp1").physics("re").create("rch4", "ReactionChem", -1);
    model.component("comp1").physics("re").feature("rch4").set("formula", "C(s)+2CeO2(s)=>Ce2O3(s)+CO");
    model.component("comp1").physics("re").feature("rch4").set("useArrhenius", true);
    model.component("comp1").physics("re").feature("rch4").set("Af", "4e8[m/s]*Sa");
    model.component("comp1").physics("re").feature("rch4").set("Ef", "80e3[J/mol]");
    model.component("comp1").physics("re").feature("rch4").set("ReactionExpression", "UserDefined");
    model.component("comp1").physics("re").feature("rch4").set("r", "re.kf_4*re.c_CeO2_solid");
    model.component("comp1").physics("re").feature("rch4").set("bulkFwdOrder", 1);
    model.component("comp1").physics("re").create("rch5", "ReactionChem", -1);
    model.component("comp1").physics("re").feature("rch5").set("formula", "Ce2O3(s)+0.5O2=>2CeO2(s)");
    model.component("comp1").physics("re").feature("rch5").set("useArrhenius", true);
    model.component("comp1").physics("re").feature("rch5").set("Af", "1e12[m^4/(mol*s)]*Sa");
    model.component("comp1").physics("re").feature("rch5").set("Ef", "80e3[J/mol]");
    model.component("comp1").physics("re").feature("rch5").set("r", "re.kf_5*re.c_O2*re.c_Ce2O3_solid");
    model.component("comp1").physics("re").feature("rch5").set("bulkFwdOrder", 2);
    model.component("comp1").physics("re").feature("C_solid").set("cLock", true);
    model.component("comp1").physics("re").create("spec1", "SpeciesChem", -1);
    model.component("comp1").physics("re").feature("spec1").set("specName", "N2");
    model.component("comp1").physics("re").feature("inits1").setIndex("F0", "C_inlet*v_inlet", 0, 0);
    model.component("comp1").physics("re").feature("inits1").setIndex("F0", "F_CO_inlet", 1, 0);
    model.component("comp1").physics("re").feature("inits1").setIndex("F0", "F_CO2_inlet", 2, 0);
    model.component("comp1").physics("re").feature("inits1").setIndex("F0", "Ce2O3_inlet*v_inlet", 3, 0);
    model.component("comp1").physics("re").feature("inits1").setIndex("F0", "CeO2_inlet*v_inlet", 4, 0);
    model.component("comp1").physics("re").feature("inits1").setIndex("F0", "F_N2_inlet", 5, 0);
    model.component("comp1").physics("re").feature("inits1").setIndex("F0", "F_O2_inlet", 6, 0);
    model.component("comp1").physics("re").create("add1", "AdditionalSourceFeature", -1);
    model.component("comp1").physics("re").feature("add1").setIndex("AddR", "-uf/H*re.c_CO", 1, 0);
    model.component("comp1").physics("re").feature("add1").setIndex("AddR", "-uf/H*re.c_CO2", 2, 0);
    model.component("comp1").physics("re").feature("add1").setIndex("AddR", "-uf/H*re.c_Ce2O3_solid", 3, 0);
    model.component("comp1").physics("re").feature("add1").setIndex("AddR", "-uf/H*re.c_CeO2_solid", 4, 0);
    model.component("comp1").physics("re").feature("add1").setIndex("AddR", "-uf/H*re.c_N2", 5, 0);
    model.component("comp1").physics("re").feature("add1").setIndex("AddR", "-uf/H*re.c_O2", 6, 0);

    model.study("std1").feature("spf").set("tlist", 0.149);
    model.study("std1").create("param", "Parametric");
    model.study("std1").feature("param").setIndex("pname", "L", 0);
    model.study("std1").feature("param").setIndex("plistarr", "", 0);
    model.study("std1").feature("param").setIndex("punit", "m", 0);
    model.study("std1").feature("param").setIndex("pname", "L", 0);
    model.study("std1").feature("param").setIndex("plistarr", "", 0);
    model.study("std1").feature("param").setIndex("punit", "m", 0);
    model.study("std1").feature("param").setIndex("pname", "T0", 0);
    model.study("std1").feature("param").setIndex("plistarr", "653 703", 0);
    model.study("std1").createAutoSequences("all");

    model.sol().create("sol2");
    model.sol("sol2").study("std1");
    model.sol("sol2").label("\u53c2\u6570\u5316\u89e3 1");

    model.batch("p1").feature("so1").set("psol", "sol2");
    model.batch("p1").run("compute");

    model.result().create("pg1", "PlotGroup1D");
    model.result("pg1").set("data", "dset2");
    model.result("pg1").create("glob1", "Global");
    model.result("pg1").feature("glob1").set("unit", new String[]{"", "", "", "", "", ""});
    model.result("pg1").feature("glob1")
         .set("expr", new String[]{"re.F_O2", "re.F_CO2", "re.F_CO", "re.F_CeO2_solid", "re.F_Ce2O3_solid", "re.F_N2"});
    model.result("pg1").feature("glob1")
         .set("descr", new String[]{"\u6469\u5c14\u6d41\u7387", "\u6469\u5c14\u6d41\u7387", "\u6469\u5c14\u6d41\u7387", "\u6469\u5c14\u6d41\u7387", "\u6469\u5c14\u6d41\u7387", "\u6469\u5c14\u6d41\u7387"});
    model.result("pg1").set("xlabel", "Reactor volume (m<sup>3</sup>)");
    model.result("pg1").label("\u6469\u5c14\u6d41\u7387 (re)");
    model.result("pg1").feature("glob1").set("xdatasolnumtype", "level1");
    model.result("pg1").run();
    model.result("pg1").label("\u6d53\u5ea6\u5e73\u63a8\u6d41\u6a21\u578b");
    model.result("pg1").set("titletype", "none");
    model.result("pg1").set("xlabel", "L (m)");
    model.result("pg1").run();
    model.result("pg1").feature("glob1").set("data", "dset2");
    model.result("pg1").feature("glob1").setIndex("expr", "re.c_O2", 0);
    model.result("pg1").feature("glob1").setIndex("expr", "re.c_CO2", 1);
    model.result("pg1").feature("glob1").setIndex("expr", "re.c_CO", 2);
    model.result("pg1").feature("glob1").setIndex("expr", "re.c_CeO2_solid", 3);
    model.result("pg1").feature("glob1").setIndex("expr", "re.c_Ce2O3_solid", 4);
    model.result("pg1").feature("glob1").remove("unit", 4);
    model.result("pg1").feature("glob1").remove("descr", 4);
    model.result("pg1").feature("glob1").remove("expr", new int[]{4});
    model.result("pg1").feature("glob1").remove("unit", 4);
    model.result("pg1").feature("glob1").remove("descr", 4);
    model.result("pg1").feature("glob1").remove("expr", new int[]{4});
    model.result("pg1").feature("glob1").set("linewidth", 2);
    model.result("pg1").feature("glob1").set("legendmethod", "manual");
    model.result("pg1").feature("glob1").setIndex("legends", "O<sub>2</sub>", 0);
    model.result("pg1").feature("glob1").setIndex("legends", "CO<sub>2</sub>", 1);
    model.result("pg1").feature("glob1").setIndex("legends", "CO", 2);
    model.result("pg1").feature("glob1").setIndex("legends", "CeO<sub>2</sub>", 3);
    model.result("pg1").feature("glob1").setIndex("legends", "Ce<sub>2</sub>O<sub>3</sub>", 4);
    model.result("pg1").feature("glob1").setIndex("looplevelinput", "first", 1);
    model.result("pg1").run();
    model.result("pg1").feature("glob1").setIndex("looplevelinput", "last", 1);
    model.result("pg1").run();
    model.result("pg1").run();
    model.result().duplicate("pg2", "pg1");
    model.result("pg2").run();
    model.result("pg2").label("\u901f\u7387\u6bd4\u8f83\uff0c\u5e73\u63a8\u6d41\u6a21\u578b");
    model.result("pg2").set("ylabelactive", true);
    model.result("pg2").set("ylabel", "\u6bd4\u7387\u6bd4\u8f83 (-)");
    model.result("pg2").run();
    model.result("pg2").feature("glob1").setIndex("looplevelinput", "first", 1);
    model.result("pg2").feature("glob1").set("expr", new String[]{"re.r_1"});
    model.result("pg2").feature("glob1").set("descr", new String[]{"\u53cd\u5e94\u901f\u7387"});
    model.result("pg2").feature("glob1").set("unit", new String[]{"mol/(m^3*s)"});
    model.result("pg2").feature("glob1").setIndex("expr", "re.r_1/re.r_3", 0);
    model.result("pg2").feature("glob1").setIndex("expr", "re.r_2/re.r_4", 1);
    model.result("pg2").feature("glob1").setIndex("legends", "r_1/r_3 at 653 K", 0);
    model.result("pg2").feature("glob1").setIndex("legends", "r_2/r_4 at 653 K", 1);
    model.result("pg2").feature().duplicate("glob2", "glob1");
    model.result("pg2").run();
    model.result("pg2").feature("glob2").setIndex("looplevelinput", "last", 1);
    model.result("pg2").feature("glob2").setIndex("legends", "r_1/r_3 at 703 K", 0);
    model.result("pg2").feature("glob2").setIndex("legends", "r_2/r_4 at 703 K", 1);
    model.result("pg2").run();

    model.component("comp1").physics("re").create("sync1", "ReactionToMph", -1);
    model.component("comp1").physics("re").feature("sync1").set("geomToUse", "2D");
    model.component("comp1").physics("re").feature("sync1").set("energybalance", "HeatTransferInFluids");
    model.component("comp1").physics("re").feature("sync1").set("momentumbalance", "FreeAndPorousMediaFlow");
    model.component("comp1").physics("re").prop("synchronize").set("synchronize", "1");

    model.component().create("comp2", true);

    model.component("comp2").geom().create("geom1", 2);
    model.component("comp2").geom("geom1").axisymmetric(false);
    model.component("comp2").geom("geom1").label("\u51e0\u4f55 1(2D)");

    model.component("comp2").mesh().create("mesh1");

    model.study().create("std2");
    model.study("std2").create("stat", "Stationary");

    model.component("comp1").physics("re").feature("sync1").set("genom", new String[]{"comp2:geom1"});
    model.component("comp1").physics("re").feature("sync1").set("studyname", new String[]{"comp2:std2"});
    model.component("comp2").physics().create("chem", "Chemistry", "geom1");
    model.component("comp2").physics().move("chem", 0);
    model.component("comp2").physics().create("tds", "DilutedSpecies", "geom1");
    model.component("comp2").physics("chem").prop("TPFeatureInput").set("T_src", "userdef");
    model.component("comp2").physics("chem").prop("TPFeatureInput").set("T", "T0");
    model.component("comp2").physics("chem").prop("mixture").set("mixture", "gas");
    model.component("comp2").physics("chem").prop("mixture").set("gasDensitySel", "Automatic");
    model.component("comp2").physics("chem").prop("Activity").set("useActivity", "0");
    model.component("comp2").physics("chem").prop("chemkin").set("chemkin", "0");
    model.component("comp2").physics("chem").prop("ChemistryCommonProperty")
         .set("VolumetricConcentrationGlobalActivityStandardState", "1[mol/m^3]");
    model.component("comp2").physics("chem").prop("ChemistryCommonProperty")
         .set("SurfaceSpeciesConcentrationType", "SurfaceConcentration");
    model.component("comp2").physics("chem").prop("ChemistryCommonProperty")
         .set("SurfaceGlobalActivityStandardState", "1[mol/m^2]");
    model.component("comp2").physics("chem").prop("ChemistryCommonProperty")
         .set("SpeciesrateUserDefinedList", new String[]{"C_solid"});
    model.component("comp2").physics("chem").prop("ChemistryCommonProperty").set("AdditionalSourceFeature", "1");
    model.component("comp2").physics("chem").prop("ActiveSpecies").set("SumActiveSpecies", "7");
    model.component("comp2").physics("chem").prop("ActiveSpecies").set("NumActiveVolumeSpecies", "7");
    model.component("comp2").physics("chem").prop("ActiveSpecies").set("NumActiveSurfaceSpecies", "0");
    model.component("comp2").physics("chem").prop("ActiveSpecies").set("NumActiveSurfaceSpeciesVariable", "0");
    model.component("comp2").physics("chem").prop("ActiveSpecies").set("surface", "0");
    model.component("comp2").physics("chem").prop("solventIsSet").set("solventIsSet", "0");
    model.component("comp2").physics("chem").create("rch1", "ReactionChem");
    model.component("comp2").physics("chem").feature("rch1").set("rSequenceNo", "1");
    model.component("comp2").physics("chem").feature("rch1").set("formula", "C(s) + O2 => CO2");
    model.component("comp2").physics("chem").feature("rch1").set("updatechem", "0");
    model.component("comp2").physics("chem").feature("rch1").set("useArrhenius", "1");
    model.component("comp2").physics("chem").feature("rch1").set("ReactionExpression", "UserDefined");
    model.component("comp2").physics("chem").feature("rch1").set("r", "chem.kf_1*chem.c_O2");
    model.component("comp2").physics("chem").feature("rch1").set("kf", "1");
    model.component("comp2").physics("chem").feature("rch1").set("Af", "1e13[m/s]*Sa");
    model.component("comp2").physics("chem").feature("rch1").set("nf", "0");
    model.component("comp2").physics("chem").feature("rch1").set("Ef", "165e3[J/mol]");
    model.component("comp2").physics("chem").feature("rch1").set("bulkFwdOrder", "1");
    model.component("comp2").physics("chem").feature("rch1").set("surfFwdOrder", "0");
    model.component("comp2").physics("chem").feature("rch1").label("1: C(s) + O2 => CO2");
    model.component("comp2").physics("chem").feature("rch1").set("rClass", "volumetric");
    model.component("comp2").physics("chem").create("rch2", "ReactionChem");
    model.component("comp2").physics("chem").feature("rch2").set("rSequenceNo", "2");
    model.component("comp2").physics("chem").feature("rch2").set("formula", "C(s) + 0.5 O2 => CO");
    model.component("comp2").physics("chem").feature("rch2").set("updatechem", "0");
    model.component("comp2").physics("chem").feature("rch2").set("useArrhenius", "1");
    model.component("comp2").physics("chem").feature("rch2").set("ReactionExpression", "UserDefined");
    model.component("comp2").physics("chem").feature("rch2").set("r", "chem.kf_2*chem.c_O2");
    model.component("comp2").physics("chem").feature("rch2").set("kf", "1");
    model.component("comp2").physics("chem").feature("rch2").set("Af", "5.5e10[m/s]*Sa");
    model.component("comp2").physics("chem").feature("rch2").set("nf", "0");
    model.component("comp2").physics("chem").feature("rch2").set("Ef", "150e3[J/mol]");
    model.component("comp2").physics("chem").feature("rch2").set("bulkFwdOrder", "1");
    model.component("comp2").physics("chem").feature("rch2").set("surfFwdOrder", "0");
    model.component("comp2").physics("chem").feature("rch2").label("2: C(s) + 0.5 O2 => CO");
    model.component("comp2").physics("chem").feature("rch2").set("rClass", "volumetric");
    model.component("comp2").physics("chem").create("rch3", "ReactionChem");
    model.component("comp2").physics("chem").feature("rch3").set("rSequenceNo", "3");
    model.component("comp2").physics("chem").feature("rch3").set("formula", "C(s) + 4 CeO2(s) => 2 Ce2O3(s) + CO2");
    model.component("comp2").physics("chem").feature("rch3").set("updatechem", "0");
    model.component("comp2").physics("chem").feature("rch3").set("useArrhenius", "1");
    model.component("comp2").physics("chem").feature("rch3").set("ReactionExpression", "UserDefined");
    model.component("comp2").physics("chem").feature("rch3").set("r", "chem.kf_3*chem.c_CeO2_solid");
    model.component("comp2").physics("chem").feature("rch3").set("kf", "1");
    model.component("comp2").physics("chem").feature("rch3").set("Af", "4.5e11[m/s]*Sa");
    model.component("comp2").physics("chem").feature("rch3").set("nf", "0");
    model.component("comp2").physics("chem").feature("rch3").set("Ef", "120e3[J/mol]");
    model.component("comp2").physics("chem").feature("rch3").set("bulkFwdOrder", "1");
    model.component("comp2").physics("chem").feature("rch3").set("surfFwdOrder", "0");
    model.component("comp2").physics("chem").feature("rch3").label("3: C(s) + 4 CeO2(s) => 2 Ce2O3(s) + CO2");
    model.component("comp2").physics("chem").feature("rch3").set("rClass", "volumetric");
    model.component("comp2").physics("chem").create("rch4", "ReactionChem");
    model.component("comp2").physics("chem").feature("rch4").set("rSequenceNo", "4");
    model.component("comp2").physics("chem").feature("rch4").set("formula", "C(s) + 2 CeO2(s) => Ce2O3(s) + CO");
    model.component("comp2").physics("chem").feature("rch4").set("updatechem", "0");
    model.component("comp2").physics("chem").feature("rch4").set("useArrhenius", "1");
    model.component("comp2").physics("chem").feature("rch4").set("ReactionExpression", "UserDefined");
    model.component("comp2").physics("chem").feature("rch4").set("r", "chem.kf_4*chem.c_CeO2_solid");
    model.component("comp2").physics("chem").feature("rch4").set("kf", "1");
    model.component("comp2").physics("chem").feature("rch4").set("Af", "4e8[m/s]*Sa");
    model.component("comp2").physics("chem").feature("rch4").set("nf", "0");
    model.component("comp2").physics("chem").feature("rch4").set("Ef", "80e3[J/mol]");
    model.component("comp2").physics("chem").feature("rch4").set("bulkFwdOrder", "1");
    model.component("comp2").physics("chem").feature("rch4").set("surfFwdOrder", "0");
    model.component("comp2").physics("chem").feature("rch4").label("4: C(s) + 2 CeO2(s) => Ce2O3(s) + CO");
    model.component("comp2").physics("chem").feature("rch4").set("rClass", "volumetric");
    model.component("comp2").physics("chem").create("rch5", "ReactionChem");
    model.component("comp2").physics("chem").feature("rch5").set("rSequenceNo", "5");
    model.component("comp2").physics("chem").feature("rch5").set("formula", "Ce2O3(s) + 0.5 O2 => 2 CeO2(s)");
    model.component("comp2").physics("chem").feature("rch5").set("updatechem", "0");
    model.component("comp2").physics("chem").feature("rch5").set("useArrhenius", "1");
    model.component("comp2").physics("chem").feature("rch5").set("ReactionExpression", "UserDefined");
    model.component("comp2").physics("chem").feature("rch5").set("r", "chem.kf_5*chem.c_O2*chem.c_Ce2O3_solid");
    model.component("comp2").physics("chem").feature("rch5").set("kf", "1");
    model.component("comp2").physics("chem").feature("rch5").set("Af", "1e12[m^4/(mol*s)]*Sa");
    model.component("comp2").physics("chem").feature("rch5").set("nf", "0");
    model.component("comp2").physics("chem").feature("rch5").set("Ef", "80e3[J/mol]");
    model.component("comp2").physics("chem").feature("rch5").set("bulkFwdOrder", "2");
    model.component("comp2").physics("chem").feature("rch5").set("surfFwdOrder", "0");
    model.component("comp2").physics("chem").feature("rch5").label("5: Ce2O3(s) + 0.5 O2 => 2 CeO2(s)");
    model.component("comp2").physics("chem").feature("rch5").set("rClass", "volumetric");
    model.component("comp2").physics("chem").feature("C_solid").set("SpeciesSource", "Reaction");
    model.component("comp2").physics("chem").feature("C_solid").set("sisDef", "1");
    model.component("comp2").physics("chem").feature("C_solid").set("specLabel", "C(s)");
    model.component("comp2").physics("chem").feature("C_solid").set("speciesNameInput", "C(s)");
    model.component("comp2").physics("chem").feature("C_solid").set("specName", "C(s)");
    model.component("comp2").physics("chem").feature("C_solid").set("enableChemicalFormulaCheckbox", "1");
    model.component("comp2").physics("chem").feature("C_solid").set("chemicalFormula", "C(s)");
    model.component("comp2").physics("chem").feature("C_solid").set("sType", "volumetric");
    model.component("comp2").physics("chem").feature("C_solid").set("M", "12.0106[g/mol]");
    model.component("comp2").physics("chem").feature("C_solid").set("z", "0");
    model.component("comp2").physics("chem").feature("C_solid").set("sigma", "3.458[angstrom]");
    model.component("comp2").physics("chem").feature("C_solid").set("epsilonkb", "107.4[K]");
    model.component("comp2").physics("chem").feature("C_solid").set("mu", "0[C*m]");
    model.component("comp2").physics("chem").feature("C_solid").set("rho", "1000[kg/m^3]");
    model.component("comp2").physics("chem").feature("C_solid").set("k", "0.02[W/(m*K)]");
    model.component("comp2").physics("chem").feature("C_solid").set("ActivityCoefficient", "1");
    model.component("comp2").physics("chem").feature("C_solid").set("cLock", "1");
    model.component("comp2").physics("chem").feature("C_solid").set("Dependent", "0");
    model.component("comp2").physics("chem").feature("C_solid").set("dependent", "0");
    model.component("comp2").physics("chem").feature("C_solid").set("SpeciesrateSelection", "Automatic");
    model.component("comp2").physics("chem").feature("C_solid").set("speciesEnthalpy", "NASA");
    model.component("comp2").physics("chem").feature("C_solid").set("Tlo", "300[K]");
    model.component("comp2").physics("chem").feature("C_solid").set("Tmid", "1000[K]");
    model.component("comp2").physics("chem").feature("C_solid").set("Thi", "5000[K]");
    model.component("comp2").physics("chem").feature("C_solid").set("SpeciesThermoaLo1", new String[]{"0"});
    model.component("comp2").physics("chem").feature("C_solid").set("SpeciesThermoaLo2", new String[]{"0"});
    model.component("comp2").physics("chem").feature("C_solid").set("SpeciesThermoaLo3", new String[]{"0"});
    model.component("comp2").physics("chem").feature("C_solid").set("SpeciesThermoaLo4", new String[]{"0"});
    model.component("comp2").physics("chem").feature("C_solid").set("SpeciesThermoaLo5", new String[]{"0"});
    model.component("comp2").physics("chem").feature("C_solid").set("SpeciesThermoaLo6", new String[]{"0"});
    model.component("comp2").physics("chem").feature("C_solid").set("SpeciesThermoaLo7", new String[]{"0"});
    model.component("comp2").physics("chem").feature("C_solid").set("SpeciesThermoaHi1", new String[]{"0"});
    model.component("comp2").physics("chem").feature("C_solid").set("SpeciesThermoaHi2", new String[]{"0"});
    model.component("comp2").physics("chem").feature("C_solid").set("SpeciesThermoaHi3", new String[]{"0"});
    model.component("comp2").physics("chem").feature("C_solid").set("SpeciesThermoaHi4", new String[]{"0"});
    model.component("comp2").physics("chem").feature("C_solid").set("SpeciesThermoaHi5", new String[]{"0"});
    model.component("comp2").physics("chem").feature("C_solid").set("SpeciesThermoaHi6", new String[]{"0"});
    model.component("comp2").physics("chem").feature("C_solid").set("SpeciesThermoaHi7", new String[]{"0"});
    model.component("comp2").physics("chem").feature("O2").set("SpeciesSource", "Reaction");
    model.component("comp2").physics("chem").feature("O2").set("sisDef", "1");
    model.component("comp2").physics("chem").feature("O2").set("specLabel", "O2");
    model.component("comp2").physics("chem").feature("O2").set("speciesNameInput", "O2");
    model.component("comp2").physics("chem").feature("O2").set("specName", "O2");
    model.component("comp2").physics("chem").feature("O2").set("enableChemicalFormulaCheckbox", "1");
    model.component("comp2").physics("chem").feature("O2").set("chemicalFormula", "O2");
    model.component("comp2").physics("chem").feature("O2").set("sType", "volumetric");
    model.component("comp2").physics("chem").feature("O2").set("M", "31.9988[g/mol]");
    model.component("comp2").physics("chem").feature("O2").set("z", "0");
    model.component("comp2").physics("chem").feature("O2").set("sigma", "3.458[angstrom]");
    model.component("comp2").physics("chem").feature("O2").set("epsilonkb", "107.4[K]");
    model.component("comp2").physics("chem").feature("O2").set("mu", "0[C*m]");
    model.component("comp2").physics("chem").feature("O2").set("rho", "1000[kg/m^3]");
    model.component("comp2").physics("chem").feature("O2").set("k", "0.02[W/(m*K)]");
    model.component("comp2").physics("chem").feature("O2").set("ActivityCoefficient", "1");
    model.component("comp2").physics("chem").feature("O2").set("cLock", "0");
    model.component("comp2").physics("chem").feature("O2").set("Dependent", "0");
    model.component("comp2").physics("chem").feature("O2").set("dependent", "0");
    model.component("comp2").physics("chem").feature("O2").set("SpeciesrateSelection", "Automatic");
    model.component("comp2").physics("chem").feature("O2").set("AdditionalSource", "1");
    model.component("comp2").physics("chem").feature("O2").set("AddR", "-uf*chem.c_O2/H");
    model.component("comp2").physics("chem").feature("O2").set("speciesEnthalpy", "NASA");
    model.component("comp2").physics("chem").feature("O2").set("Tlo", "300[K]");
    model.component("comp2").physics("chem").feature("O2").set("Tmid", "1000[K]");
    model.component("comp2").physics("chem").feature("O2").set("Thi", "5000[K]");
    model.component("comp2").physics("chem").feature("O2").set("SpeciesThermoaLo1", new String[]{"0"});
    model.component("comp2").physics("chem").feature("O2").set("SpeciesThermoaLo2", new String[]{"0"});
    model.component("comp2").physics("chem").feature("O2").set("SpeciesThermoaLo3", new String[]{"0"});
    model.component("comp2").physics("chem").feature("O2").set("SpeciesThermoaLo4", new String[]{"0"});
    model.component("comp2").physics("chem").feature("O2").set("SpeciesThermoaLo5", new String[]{"0"});
    model.component("comp2").physics("chem").feature("O2").set("SpeciesThermoaLo6", new String[]{"0"});
    model.component("comp2").physics("chem").feature("O2").set("SpeciesThermoaLo7", new String[]{"0"});
    model.component("comp2").physics("chem").feature("O2").set("SpeciesThermoaHi1", new String[]{"0"});
    model.component("comp2").physics("chem").feature("O2").set("SpeciesThermoaHi2", new String[]{"0"});
    model.component("comp2").physics("chem").feature("O2").set("SpeciesThermoaHi3", new String[]{"0"});
    model.component("comp2").physics("chem").feature("O2").set("SpeciesThermoaHi4", new String[]{"0"});
    model.component("comp2").physics("chem").feature("O2").set("SpeciesThermoaHi5", new String[]{"0"});
    model.component("comp2").physics("chem").feature("O2").set("SpeciesThermoaHi6", new String[]{"0"});
    model.component("comp2").physics("chem").feature("O2").set("SpeciesThermoaHi7", new String[]{"0"});

    return model;
  }

  public static Model run2(Model model) {
    model.component("comp2").physics("chem").feature("CO2").set("SpeciesSource", "Reaction");
    model.component("comp2").physics("chem").feature("CO2").set("sisDef", "1");
    model.component("comp2").physics("chem").feature("CO2").set("specLabel", "CO2");
    model.component("comp2").physics("chem").feature("CO2").set("speciesNameInput", "CO2");
    model.component("comp2").physics("chem").feature("CO2").set("specName", "CO2");
    model.component("comp2").physics("chem").feature("CO2").set("enableChemicalFormulaCheckbox", "1");
    model.component("comp2").physics("chem").feature("CO2").set("chemicalFormula", "CO2");
    model.component("comp2").physics("chem").feature("CO2").set("sType", "volumetric");
    model.component("comp2").physics("chem").feature("CO2").set("M", "44.0094[g/mol]");
    model.component("comp2").physics("chem").feature("CO2").set("z", "0");
    model.component("comp2").physics("chem").feature("CO2").set("sigma", "3.458[angstrom]");
    model.component("comp2").physics("chem").feature("CO2").set("epsilonkb", "107.4[K]");
    model.component("comp2").physics("chem").feature("CO2").set("mu", "0[C*m]");
    model.component("comp2").physics("chem").feature("CO2").set("rho", "1000[kg/m^3]");
    model.component("comp2").physics("chem").feature("CO2").set("k", "0.02[W/(m*K)]");
    model.component("comp2").physics("chem").feature("CO2").set("ActivityCoefficient", "1");
    model.component("comp2").physics("chem").feature("CO2").set("cLock", "0");
    model.component("comp2").physics("chem").feature("CO2").set("Dependent", "0");
    model.component("comp2").physics("chem").feature("CO2").set("dependent", "0");
    model.component("comp2").physics("chem").feature("CO2").set("SpeciesrateSelection", "Automatic");
    model.component("comp2").physics("chem").feature("CO2").set("AdditionalSource", "1");
    model.component("comp2").physics("chem").feature("CO2").set("AddR", "-uf*chem.c_CO2/H");
    model.component("comp2").physics("chem").feature("CO2").set("speciesEnthalpy", "NASA");
    model.component("comp2").physics("chem").feature("CO2").set("Tlo", "300[K]");
    model.component("comp2").physics("chem").feature("CO2").set("Tmid", "1000[K]");
    model.component("comp2").physics("chem").feature("CO2").set("Thi", "5000[K]");
    model.component("comp2").physics("chem").feature("CO2").set("SpeciesThermoaLo1", new String[]{"0"});
    model.component("comp2").physics("chem").feature("CO2").set("SpeciesThermoaLo2", new String[]{"0"});
    model.component("comp2").physics("chem").feature("CO2").set("SpeciesThermoaLo3", new String[]{"0"});
    model.component("comp2").physics("chem").feature("CO2").set("SpeciesThermoaLo4", new String[]{"0"});
    model.component("comp2").physics("chem").feature("CO2").set("SpeciesThermoaLo5", new String[]{"0"});
    model.component("comp2").physics("chem").feature("CO2").set("SpeciesThermoaLo6", new String[]{"0"});
    model.component("comp2").physics("chem").feature("CO2").set("SpeciesThermoaLo7", new String[]{"0"});
    model.component("comp2").physics("chem").feature("CO2").set("SpeciesThermoaHi1", new String[]{"0"});
    model.component("comp2").physics("chem").feature("CO2").set("SpeciesThermoaHi2", new String[]{"0"});
    model.component("comp2").physics("chem").feature("CO2").set("SpeciesThermoaHi3", new String[]{"0"});
    model.component("comp2").physics("chem").feature("CO2").set("SpeciesThermoaHi4", new String[]{"0"});
    model.component("comp2").physics("chem").feature("CO2").set("SpeciesThermoaHi5", new String[]{"0"});
    model.component("comp2").physics("chem").feature("CO2").set("SpeciesThermoaHi6", new String[]{"0"});
    model.component("comp2").physics("chem").feature("CO2").set("SpeciesThermoaHi7", new String[]{"0"});
    model.component("comp2").physics("chem").feature("CO").set("SpeciesSource", "Reaction");
    model.component("comp2").physics("chem").feature("CO").set("sisDef", "1");
    model.component("comp2").physics("chem").feature("CO").set("specLabel", "CO");
    model.component("comp2").physics("chem").feature("CO").set("speciesNameInput", "CO");
    model.component("comp2").physics("chem").feature("CO").set("specName", "CO");
    model.component("comp2").physics("chem").feature("CO").set("enableChemicalFormulaCheckbox", "1");
    model.component("comp2").physics("chem").feature("CO").set("chemicalFormula", "CO");
    model.component("comp2").physics("chem").feature("CO").set("sType", "volumetric");
    model.component("comp2").physics("chem").feature("CO").set("M", "28.01[g/mol]");
    model.component("comp2").physics("chem").feature("CO").set("z", "0");
    model.component("comp2").physics("chem").feature("CO").set("sigma", "3.458[angstrom]");
    model.component("comp2").physics("chem").feature("CO").set("epsilonkb", "107.4[K]");
    model.component("comp2").physics("chem").feature("CO").set("mu", "0[C*m]");
    model.component("comp2").physics("chem").feature("CO").set("rho", "1000[kg/m^3]");
    model.component("comp2").physics("chem").feature("CO").set("k", "0.02[W/(m*K)]");
    model.component("comp2").physics("chem").feature("CO").set("ActivityCoefficient", "1");
    model.component("comp2").physics("chem").feature("CO").set("cLock", "0");
    model.component("comp2").physics("chem").feature("CO").set("Dependent", "0");
    model.component("comp2").physics("chem").feature("CO").set("dependent", "0");
    model.component("comp2").physics("chem").feature("CO").set("SpeciesrateSelection", "Automatic");
    model.component("comp2").physics("chem").feature("CO").set("AdditionalSource", "1");
    model.component("comp2").physics("chem").feature("CO").set("AddR", "-uf*chem.c_CO/H");
    model.component("comp2").physics("chem").feature("CO").set("speciesEnthalpy", "NASA");
    model.component("comp2").physics("chem").feature("CO").set("Tlo", "300[K]");
    model.component("comp2").physics("chem").feature("CO").set("Tmid", "1000[K]");
    model.component("comp2").physics("chem").feature("CO").set("Thi", "5000[K]");
    model.component("comp2").physics("chem").feature("CO").set("SpeciesThermoaLo1", new String[]{"0"});
    model.component("comp2").physics("chem").feature("CO").set("SpeciesThermoaLo2", new String[]{"0"});
    model.component("comp2").physics("chem").feature("CO").set("SpeciesThermoaLo3", new String[]{"0"});
    model.component("comp2").physics("chem").feature("CO").set("SpeciesThermoaLo4", new String[]{"0"});
    model.component("comp2").physics("chem").feature("CO").set("SpeciesThermoaLo5", new String[]{"0"});
    model.component("comp2").physics("chem").feature("CO").set("SpeciesThermoaLo6", new String[]{"0"});
    model.component("comp2").physics("chem").feature("CO").set("SpeciesThermoaLo7", new String[]{"0"});
    model.component("comp2").physics("chem").feature("CO").set("SpeciesThermoaHi1", new String[]{"0"});
    model.component("comp2").physics("chem").feature("CO").set("SpeciesThermoaHi2", new String[]{"0"});
    model.component("comp2").physics("chem").feature("CO").set("SpeciesThermoaHi3", new String[]{"0"});
    model.component("comp2").physics("chem").feature("CO").set("SpeciesThermoaHi4", new String[]{"0"});
    model.component("comp2").physics("chem").feature("CO").set("SpeciesThermoaHi5", new String[]{"0"});
    model.component("comp2").physics("chem").feature("CO").set("SpeciesThermoaHi6", new String[]{"0"});
    model.component("comp2").physics("chem").feature("CO").set("SpeciesThermoaHi7", new String[]{"0"});
    model.component("comp2").physics("chem").feature("CeO2_solid").set("SpeciesSource", "Reaction");
    model.component("comp2").physics("chem").feature("CeO2_solid").set("sisDef", "1");
    model.component("comp2").physics("chem").feature("CeO2_solid").set("specLabel", "CeO2(s)");
    model.component("comp2").physics("chem").feature("CeO2_solid").set("speciesNameInput", "CeO2(s)");
    model.component("comp2").physics("chem").feature("CeO2_solid").set("specName", "CeO2(s)");
    model.component("comp2").physics("chem").feature("CeO2_solid").set("enableChemicalFormulaCheckbox", "1");
    model.component("comp2").physics("chem").feature("CeO2_solid").set("chemicalFormula", "CeO2(s)");
    model.component("comp2").physics("chem").feature("CeO2_solid").set("sType", "volumetric");
    model.component("comp2").physics("chem").feature("CeO2_solid").set("M", "172.1148[g/mol]");
    model.component("comp2").physics("chem").feature("CeO2_solid").set("z", "0");
    model.component("comp2").physics("chem").feature("CeO2_solid").set("sigma", "3.458[angstrom]");
    model.component("comp2").physics("chem").feature("CeO2_solid").set("epsilonkb", "107.4[K]");
    model.component("comp2").physics("chem").feature("CeO2_solid").set("mu", "0[C*m]");
    model.component("comp2").physics("chem").feature("CeO2_solid").set("rho", "1000[kg/m^3]");
    model.component("comp2").physics("chem").feature("CeO2_solid").set("k", "0.02[W/(m*K)]");
    model.component("comp2").physics("chem").feature("CeO2_solid").set("ActivityCoefficient", "1");
    model.component("comp2").physics("chem").feature("CeO2_solid").set("cLock", "0");
    model.component("comp2").physics("chem").feature("CeO2_solid").set("Dependent", "0");
    model.component("comp2").physics("chem").feature("CeO2_solid").set("dependent", "0");
    model.component("comp2").physics("chem").feature("CeO2_solid").set("SpeciesrateSelection", "Automatic");
    model.component("comp2").physics("chem").feature("CeO2_solid").set("AdditionalSource", "1");
    model.component("comp2").physics("chem").feature("CeO2_solid").set("AddR", "-uf*chem.c_CeO2_solid/H");
    model.component("comp2").physics("chem").feature("CeO2_solid").set("speciesEnthalpy", "NASA");
    model.component("comp2").physics("chem").feature("CeO2_solid").set("Tlo", "300[K]");
    model.component("comp2").physics("chem").feature("CeO2_solid").set("Tmid", "1000[K]");
    model.component("comp2").physics("chem").feature("CeO2_solid").set("Thi", "5000[K]");
    model.component("comp2").physics("chem").feature("CeO2_solid").set("SpeciesThermoaLo1", new String[]{"0"});
    model.component("comp2").physics("chem").feature("CeO2_solid").set("SpeciesThermoaLo2", new String[]{"0"});
    model.component("comp2").physics("chem").feature("CeO2_solid").set("SpeciesThermoaLo3", new String[]{"0"});
    model.component("comp2").physics("chem").feature("CeO2_solid").set("SpeciesThermoaLo4", new String[]{"0"});
    model.component("comp2").physics("chem").feature("CeO2_solid").set("SpeciesThermoaLo5", new String[]{"0"});
    model.component("comp2").physics("chem").feature("CeO2_solid").set("SpeciesThermoaLo6", new String[]{"0"});
    model.component("comp2").physics("chem").feature("CeO2_solid").set("SpeciesThermoaLo7", new String[]{"0"});
    model.component("comp2").physics("chem").feature("CeO2_solid").set("SpeciesThermoaHi1", new String[]{"0"});
    model.component("comp2").physics("chem").feature("CeO2_solid").set("SpeciesThermoaHi2", new String[]{"0"});
    model.component("comp2").physics("chem").feature("CeO2_solid").set("SpeciesThermoaHi3", new String[]{"0"});
    model.component("comp2").physics("chem").feature("CeO2_solid").set("SpeciesThermoaHi4", new String[]{"0"});
    model.component("comp2").physics("chem").feature("CeO2_solid").set("SpeciesThermoaHi5", new String[]{"0"});
    model.component("comp2").physics("chem").feature("CeO2_solid").set("SpeciesThermoaHi6", new String[]{"0"});
    model.component("comp2").physics("chem").feature("CeO2_solid").set("SpeciesThermoaHi7", new String[]{"0"});
    model.component("comp2").physics("chem").feature("Ce2O3_solid").set("SpeciesSource", "Reaction");
    model.component("comp2").physics("chem").feature("Ce2O3_solid").set("sisDef", "1");
    model.component("comp2").physics("chem").feature("Ce2O3_solid").set("specLabel", "Ce2O3(s)");
    model.component("comp2").physics("chem").feature("Ce2O3_solid").set("speciesNameInput", "Ce2O3(s)");
    model.component("comp2").physics("chem").feature("Ce2O3_solid").set("specName", "Ce2O3(s)");
    model.component("comp2").physics("chem").feature("Ce2O3_solid").set("enableChemicalFormulaCheckbox", "1");
    model.component("comp2").physics("chem").feature("Ce2O3_solid").set("chemicalFormula", "Ce2O3(s)");
    model.component("comp2").physics("chem").feature("Ce2O3_solid").set("sType", "volumetric");
    model.component("comp2").physics("chem").feature("Ce2O3_solid").set("M", "328.2302[g/mol]");
    model.component("comp2").physics("chem").feature("Ce2O3_solid").set("z", "0");
    model.component("comp2").physics("chem").feature("Ce2O3_solid").set("sigma", "3.458[angstrom]");
    model.component("comp2").physics("chem").feature("Ce2O3_solid").set("epsilonkb", "107.4[K]");
    model.component("comp2").physics("chem").feature("Ce2O3_solid").set("mu", "0[C*m]");
    model.component("comp2").physics("chem").feature("Ce2O3_solid").set("rho", "1000[kg/m^3]");
    model.component("comp2").physics("chem").feature("Ce2O3_solid").set("k", "0.02[W/(m*K)]");
    model.component("comp2").physics("chem").feature("Ce2O3_solid").set("ActivityCoefficient", "1");
    model.component("comp2").physics("chem").feature("Ce2O3_solid").set("cLock", "0");
    model.component("comp2").physics("chem").feature("Ce2O3_solid").set("Dependent", "0");
    model.component("comp2").physics("chem").feature("Ce2O3_solid").set("dependent", "0");
    model.component("comp2").physics("chem").feature("Ce2O3_solid").set("SpeciesrateSelection", "Automatic");
    model.component("comp2").physics("chem").feature("Ce2O3_solid").set("AdditionalSource", "1");
    model.component("comp2").physics("chem").feature("Ce2O3_solid").set("AddR", "-uf*chem.c_Ce2O3_solid/H");
    model.component("comp2").physics("chem").feature("Ce2O3_solid").set("speciesEnthalpy", "NASA");
    model.component("comp2").physics("chem").feature("Ce2O3_solid").set("Tlo", "300[K]");
    model.component("comp2").physics("chem").feature("Ce2O3_solid").set("Tmid", "1000[K]");
    model.component("comp2").physics("chem").feature("Ce2O3_solid").set("Thi", "5000[K]");
    model.component("comp2").physics("chem").feature("Ce2O3_solid").set("SpeciesThermoaLo1", new String[]{"0"});
    model.component("comp2").physics("chem").feature("Ce2O3_solid").set("SpeciesThermoaLo2", new String[]{"0"});
    model.component("comp2").physics("chem").feature("Ce2O3_solid").set("SpeciesThermoaLo3", new String[]{"0"});
    model.component("comp2").physics("chem").feature("Ce2O3_solid").set("SpeciesThermoaLo4", new String[]{"0"});
    model.component("comp2").physics("chem").feature("Ce2O3_solid").set("SpeciesThermoaLo5", new String[]{"0"});
    model.component("comp2").physics("chem").feature("Ce2O3_solid").set("SpeciesThermoaLo6", new String[]{"0"});
    model.component("comp2").physics("chem").feature("Ce2O3_solid").set("SpeciesThermoaLo7", new String[]{"0"});
    model.component("comp2").physics("chem").feature("Ce2O3_solid").set("SpeciesThermoaHi1", new String[]{"0"});
    model.component("comp2").physics("chem").feature("Ce2O3_solid").set("SpeciesThermoaHi2", new String[]{"0"});
    model.component("comp2").physics("chem").feature("Ce2O3_solid").set("SpeciesThermoaHi3", new String[]{"0"});
    model.component("comp2").physics("chem").feature("Ce2O3_solid").set("SpeciesThermoaHi4", new String[]{"0"});
    model.component("comp2").physics("chem").feature("Ce2O3_solid").set("SpeciesThermoaHi5", new String[]{"0"});
    model.component("comp2").physics("chem").feature("Ce2O3_solid").set("SpeciesThermoaHi6", new String[]{"0"});
    model.component("comp2").physics("chem").feature("Ce2O3_solid").set("SpeciesThermoaHi7", new String[]{"0"});
    model.component("comp2").physics("chem").create("N2", "SpeciesChem");
    model.component("comp2").physics("chem").feature("N2").set("SpeciesSource", "FreeSpecies");
    model.component("comp2").physics("chem").feature("N2").set("sisDef", "1");
    model.component("comp2").physics("chem").feature("N2").set("specLabel", "N2");
    model.component("comp2").physics("chem").feature("N2").set("speciesNameInput", "N2");
    model.component("comp2").physics("chem").feature("N2").set("specName", "N2");
    model.component("comp2").physics("chem").feature("N2").set("enableChemicalFormulaCheckbox", "1");
    model.component("comp2").physics("chem").feature("N2").set("chemicalFormula", "N2");
    model.component("comp2").physics("chem").feature("N2").label("\u7269\u8d28: N2");
    model.component("comp2").physics("chem").feature("N2").active(true);
    model.component("comp2").physics("chem").feature("N2").set("sType", "volumetric");
    model.component("comp2").physics("chem").feature("N2").set("M", "28.0137[g/mol]");
    model.component("comp2").physics("chem").feature("N2").set("z", "0");
    model.component("comp2").physics("chem").feature("N2").set("sigma", "3.458[angstrom]");
    model.component("comp2").physics("chem").feature("N2").set("epsilonkb", "107.4[K]");
    model.component("comp2").physics("chem").feature("N2").set("mu", "0[C*m]");
    model.component("comp2").physics("chem").feature("N2").set("rho", "1000[kg/m^3]");
    model.component("comp2").physics("chem").feature("N2").set("k", "0.02[W/(m*K)]");
    model.component("comp2").physics("chem").feature("N2").set("ActivityCoefficient", "1");
    model.component("comp2").physics("chem").feature("N2").set("cLock", "0");
    model.component("comp2").physics("chem").feature("N2").set("Dependent", "0");
    model.component("comp2").physics("chem").feature("N2").set("dependent", "0");
    model.component("comp2").physics("chem").feature("N2").set("SpeciesrateSelection", "Automatic");
    model.component("comp2").physics("chem").feature("N2").set("AdditionalSource", "1");
    model.component("comp2").physics("chem").feature("N2").set("AddR", "-uf*chem.c_N2/H");
    model.component("comp2").physics("chem").feature("N2").set("speciesEnthalpy", "NASA");
    model.component("comp2").physics("chem").feature("N2").set("Tlo", "300[K]");
    model.component("comp2").physics("chem").feature("N2").set("Tmid", "1000[K]");
    model.component("comp2").physics("chem").feature("N2").set("Thi", "5000[K]");
    model.component("comp2").physics("chem").feature("N2").set("SpeciesThermoaLo1", new String[]{"0"});
    model.component("comp2").physics("chem").feature("N2").set("SpeciesThermoaLo2", new String[]{"0"});
    model.component("comp2").physics("chem").feature("N2").set("SpeciesThermoaLo3", new String[]{"0"});
    model.component("comp2").physics("chem").feature("N2").set("SpeciesThermoaLo4", new String[]{"0"});
    model.component("comp2").physics("chem").feature("N2").set("SpeciesThermoaLo5", new String[]{"0"});
    model.component("comp2").physics("chem").feature("N2").set("SpeciesThermoaLo6", new String[]{"0"});
    model.component("comp2").physics("chem").feature("N2").set("SpeciesThermoaLo7", new String[]{"0"});
    model.component("comp2").physics("chem").feature("N2").set("SpeciesThermoaHi1", new String[]{"0"});
    model.component("comp2").physics("chem").feature("N2").set("SpeciesThermoaHi2", new String[]{"0"});
    model.component("comp2").physics("chem").feature("N2").set("SpeciesThermoaHi3", new String[]{"0"});
    model.component("comp2").physics("chem").feature("N2").set("SpeciesThermoaHi4", new String[]{"0"});
    model.component("comp2").physics("chem").feature("N2").set("SpeciesThermoaHi5", new String[]{"0"});
    model.component("comp2").physics("chem").feature("N2").set("SpeciesThermoaHi6", new String[]{"0"});
    model.component("comp2").physics("chem").feature("N2").set("SpeciesThermoaHi7", new String[]{"0"});
    model.component("comp2").physics("chem").prop("simpropChem").set("rSequenceNo", "5");
    model.component("comp2").physics("chem").prop("simpropChem").set("sSequenceNo", "7");
    model.component("comp2").physics("chem").prop("mixture").set("hasPropertyPackage", "0");
    model.component("comp2").physics("chem").prop("mixture").set("PropertyPackage", "");
    model.component("comp2").physics("chem").prop("mixture").set("Thermodynamics", "0");
    model.component("comp2").physics("tds").field("concentration")
         .component(new String[]{"cCO", "cCO2", "cN2", "cO2", "cCe2O3_solid", "cCeO2_solid"});
    model.component("comp2").physics("tds").feature("init1")
         .set("initc", new String[]{"F_CO_inlet/v1", "F_CO2_inlet/v1", "F_N2_inlet/v1", "F_O2_inlet/v1", "Ce2O3_inlet*v_inlet/v1", "CeO2_inlet*v_inlet/v1"});
    model.component("comp2").physics("tds").feature().create("reac1", "Reactions");
    model.component("comp2").physics("tds").feature("reac1").selection().all();
    model.component("comp2").physics("tds").feature("reac1").set("ReactingVolumeType", "TotalVolume");
    model.component("comp2").physics("tds").feature().create("in1", "Inflow");
    model.component("comp2").physics("tds").feature("in1").setIndex("c0", "F_CO_inlet/v1", 0);
    model.component("comp2").physics("tds").feature("in1").setIndex("c0", "F_CO2_inlet/v1", 1);
    model.component("comp2").physics("tds").feature("in1").setIndex("c0", "F_N2_inlet/v1", 2);
    model.component("comp2").physics("tds").feature("in1").setIndex("c0", "F_O2_inlet/v1", 3);
    model.component("comp2").physics("tds").feature("in1").setIndex("c0", "Ce2O3_inlet*v_inlet/v1", 4);
    model.component("comp2").physics("tds").feature("in1").setIndex("c0", "CeO2_inlet*v_inlet/v1", 5);
    model.component("comp2").physics("tds").feature().create("out1", "Outflow");
    model.component("comp2").physics("chem").prop("ChemistryModelInputParameter").set("MassTransfer", "tds");
    model.component("comp2").physics("chem").prop("ChemistryModelInputParameter")
         .set("ConcentrationInput", new String[]{"cCO", "cCO2", "cN2", "cO2"});
    model.component("comp2").physics("chem").prop("ChemistryModelInputParameter")
         .set("ConcentrationValue", new String[]{"\u6c42\u89e3\u7684", "\u6c42\u89e3\u7684", "\u6c42\u89e3\u7684", "\u6c42\u89e3\u7684"});
    model.component("comp2").physics("chem").prop("ChemistryModelInputParameter")
         .set("uselog", new String[]{"cCO", "cCO2", "1", "cO2"});
    model.component("comp2").physics("chem").prop("ChemistryModelInputParameter")
         .set("SolidConcentration", new String[]{"C_inlet*v_inlet/v1", "cCe2O3_solid", "cCeO2_solid"});
    model.component("comp2").physics("chem").prop("ChemistryModelInputParameter").set("csurf", new String[]{});
    model.component("comp2").physics("chem").prop("ChemistryModelInputParameter")
         .set("AqueousSpeciesConcentration", new String[]{});
    model.component("comp2").physics("tds").feature("sp1")
         .set("z", new String[]{"root.comp2.chem.z_CO", "root.comp2.chem.z_CO2", "root.comp2.chem.z_N2", "root.comp2.chem.z_O2", "root.comp2.chem.z_Ce2O3_solid", "root.comp2.chem.z_CeO2_solid"});
    model.component("comp2").physics("tds").feature("cdm1").set("Dchem_cCO", "1e-5[m^2/s]");
    model.component("comp2").physics("tds").feature("cdm1").set("D_cCO", "1e-5[m^2/s]");
    model.component("comp2").physics("tds").feature("cdm1").set("Dchem_cCO2", "1e-5[m^2/s]");
    model.component("comp2").physics("tds").feature("cdm1").set("D_cCO2", "1e-5[m^2/s]");
    model.component("comp2").physics("tds").feature("cdm1").set("Dchem_cN2", "1e-5[m^2/s]");
    model.component("comp2").physics("tds").feature("cdm1").set("D_cN2", "1e-5[m^2/s]");
    model.component("comp2").physics("tds").feature("cdm1").set("Dchem_cO2", "1e-5[m^2/s]");
    model.component("comp2").physics("tds").feature("cdm1").set("D_cO2", "1e-5[m^2/s]");
    model.component("comp2").physics("tds").feature("cdm1").set("Dchem_cCe2O3_solid", "1e-5[m^2/s]");
    model.component("comp2").physics("tds").feature("cdm1").set("D_cCe2O3_solid", "1e-5[m^2/s]");
    model.component("comp2").physics("tds").feature("cdm1").set("Dchem_cCeO2_solid", "1e-5[m^2/s]");
    model.component("comp2").physics("tds").feature("cdm1").set("D_cCeO2_solid", "1e-5[m^2/s]");
    model.component("comp2").physics("tds").feature("reac1").setIndex("R_cCO_src", "root.comp2.chem.R_CO", 0);
    model.component("comp2").physics("tds").feature("reac1").setIndex("R_cCO2_src", "root.comp2.chem.R_CO2", 0);
    model.component("comp2").physics("tds").feature("reac1").setIndex("R_cN2_src", "root.comp2.chem.R_N2", 0);
    model.component("comp2").physics("tds").feature("reac1").setIndex("R_cO2_src", "root.comp2.chem.R_O2", 0);
    model.component("comp2").physics("tds").feature("reac1")
         .setIndex("R_cCe2O3_solid_src", "root.comp2.chem.R_Ce2O3_solid", 0);
    model.component("comp2").physics("tds").feature("reac1")
         .setIndex("R_cCeO2_solid_src", "root.comp2.chem.R_CeO2_solid", 0);
    model.component("comp2").physics().create("fp", "FreeAndPorousMediaFlow", "geom1");
    model.component("comp2").physics("fp").prop("PhysicalModelProperty").set("Compressibility", "Incompressible");
    model.component("comp2").physics("fp").feature().create("inl1", "InletBoundary");
    model.component("comp2").physics("fp").feature("inl1").set("BoundaryCondition", "Velocity");
    model.component("comp2").physics("fp").feature("inl1").set("ComponentWise", "NormalInflowVelocity");
    model.component("comp2").physics("fp").feature().create("out1", "OutletBoundary");
    model.component("comp2").physics().create("ht", "HeatTransferInFluids", "geom1");
    model.component("comp2").physics("ht").feature().create("temp1", "TemperatureBoundary");
    model.component("comp2").physics("ht").feature("temp1").set("T0", "T0");
    model.component("comp2").physics("ht").feature().create("ofl1", "ConvectiveOutflow");
    model.component("comp2").physics("ht").feature("init1").set("Tinit", "298.15[K]");
    model.component("comp2").physics("ht").feature().create("hs1", "HeatSource");
    model.component("comp2").physics("ht").feature("hs1").selection().all();
    model.component("comp2").physics("ht").feature("hs1").set("Q0_src", "root.comp2.chem.Qtot");

    model.component("comp2").multiphysics().create("rfd1", "ReactingFlowDS", 2);
    model.component("comp2").multiphysics("rfd1").set("Fluid_physics", "fp");
    model.component("comp2").multiphysics("rfd1").set("Species_physics", "tds");
    model.component("comp2").multiphysics().create("nitf1", "NonIsothermalFlow", 2);
    model.component("comp2").multiphysics("nitf1").set("Fluid_physics", "fp");
    model.component("comp2").multiphysics("nitf1").set("Heat_physics", "ht");

    model.component("comp1").physics("re").feature("sync1").set("geomToUse", "geom1");
    model.component("comp1").physics("re").feature("sync1").set("chemTag", "chem");
    model.component("comp1").physics("re").feature("sync1").set("massbalance", "tds");
    model.component("comp2").physics("tds").feature("cdm1").set("u_src", "root.comp2.u");
    model.component("comp2").physics("tds").feature("cdm1").set("minput_pressure_src", "root.comp2.fp.pA");
    model.component("comp2").physics("tds").feature("cdm1").set("minput_temperature_src", "root.comp2.T");
    model.component("comp1").physics("re").feature("sync1").set("energybalance", "ht");
    model.component("comp2").physics("ht").feature("fluid1").set("minput_pressure_src", "root.comp2.fp.pA");
    model.component("comp2").physics("ht").feature("fluid1").set("molarmass_mat", "root.comp2.chem.M_C_solid");
    model.component("comp2").physics("chem").prop("TPFeatureInput").set("T_src", "root.comp2.T");
    model.component("comp2").physics("ht").feature("fluid1").set("u_src", "root.comp2.u");
    model.component("comp1").physics("re").feature("sync1").set("momentumbalance", "fp");
    model.component("comp2").physics("chem").prop("TPFeatureInput").set("p_src", "root.comp2.fp.pA");

    model.study("std2").feature("stat").setSolveFor("/physics/chem", true);
    model.study("std2").feature("stat").setSolveFor("/physics/tds", true);
    model.study("std2").feature("stat").setSolveFor("/physics/fp", true);
    model.study("std2").feature("stat").setSolveFor("/physics/ht", true);
    model.study("std2").feature("stat").setSolveFor("/multiphysics/rfd1", true);
    model.study("std2").feature("stat").setSolveFor("/multiphysics/nitf1", true);
    model.study("std1").feature("param").setSolveFor("/physics/chem", false);
    model.study("std1").feature("param").setSolveFor("/physics/tds", false);
    model.study("std1").feature("param").setSolveFor("/physics/fp", false);
    model.study("std1").feature("param").setSolveFor("/physics/ht", false);
    model.study("std1").feature("param").setSolveFor("/multiphysics/rfd1", false);
    model.study("std1").feature("param").setSolveFor("/multiphysics/nitf1", false);
    model.study("std1").feature("spf").setSolveFor("/physics/chem", false);
    model.study("std1").feature("spf").setSolveFor("/physics/tds", false);
    model.study("std1").feature("spf").setSolveFor("/physics/fp", false);
    model.study("std1").feature("spf").setSolveFor("/physics/ht", false);
    model.study("std1").feature("spf").setSolveFor("/multiphysics/rfd1", false);
    model.study("std1").feature("spf").setSolveFor("/multiphysics/nitf1", false);

    model.component("comp2").view("view1").axis().set("viewscaletype", "automatic");

    model.component("comp2").geom("geom1").create("r1", "Rectangle");
    model.component("comp2").geom("geom1").feature("r1").set("size", new String[]{"L+1[cm]", "H"});
    model.component("comp2").geom("geom1").run("r1");
    model.component("comp2").geom("geom1").create("r2", "Rectangle");
    model.component("comp2").geom("geom1").feature("r2").set("size", new String[]{"L", "Hf+dHs"});
    model.component("comp2").geom("geom1").feature("r2").set("pos", new String[]{"0", "H"});
    model.component("comp2").geom("geom1").feature("r2").setIndex("layer", "Hf", 0);
    model.component("comp2").geom("geom1").run("r2");
    model.component("comp2").geom("geom1").create("r3", "Rectangle");
    model.component("comp2").geom("geom1").feature("r3").set("size", new String[]{"L", "0.5*dHs"});
    model.component("comp2").geom("geom1").feature("r3").set("pos", new String[]{"0", "H+Hf+dHs"});
    model.component("comp2").geom("geom1").run("r3");
    model.component("comp2").geom("geom1").create("mov1", "Move");
    model.component("comp2").geom("geom1").feature("mov1").selection("input").set("r1");
    model.component("comp2").geom("geom1").feature("mov1").set("keep", true);
    model.component("comp2").geom("geom1").feature("mov1").set("displx", "-1[cm]");
    model.component("comp2").geom("geom1").feature("mov1").set("disply", "H+Hf+1.5*dHs");
    model.component("comp2").geom("geom1").run("fin");
    model.component("comp2").geom("geom1").create("sel1", "ExplicitSelection");
    model.component("comp2").geom("geom1").feature("sel1").label("\u5165\u53e3");
    model.component("comp2").geom("geom1").feature("sel1").selection("selection").init(1);
    model.component("comp2").geom("geom1").feature("sel1").selection("selection").set("fin", 1);
    model.component("comp2").geom("geom1").run("sel1");
    model.component("comp2").geom("geom1").create("sel2", "ExplicitSelection");
    model.component("comp2").geom("geom1").feature("sel2").label("\u51fa\u53e3");
    model.component("comp2").geom("geom1").feature("sel2").selection("selection").init(1);
    model.component("comp2").geom("geom1").feature("sel2").selection("selection").set("fin", 18);
    model.component("comp2").geom("geom1").run("sel2");
    model.component("comp2").geom("geom1").create("sel3", "ExplicitSelection");
    model.component("comp2").geom("geom1").feature("sel3").label("\u901a\u9053 A");
    model.component("comp2").geom("geom1").feature("sel3").selection("selection").set("fin", 1, 5);
    model.component("comp2").geom("geom1").run("sel3");
    model.component("comp2").geom("geom1").create("sel4", "ExplicitSelection");
    model.component("comp2").geom("geom1").feature("sel4").label("\u70df\u7070\u5c42");

    return model;
  }

  public static Model run3(Model model) {
    model.component("comp2").geom("geom1").feature("sel4").selection("selection").set("fin", 4);
    model.component("comp2").geom("geom1").run("sel4");
    model.component("comp2").geom("geom1").create("sel5", "ExplicitSelection");
    model.component("comp2").geom("geom1").feature("sel5").label("\u6ee4\u6e05\u5668\u58c1");
    model.component("comp2").geom("geom1").feature("sel5").selection("selection").set("fin", 3);
    model.component("comp2").geom("geom1").run("sel5");
    model.component("comp2").geom("geom1").create("unisel1", "UnionSelection");
    model.component("comp2").geom("geom1").feature("unisel1").set("input", new String[]{"sel4", "sel5"});
    model.component("comp2").geom("geom1").feature("unisel1").label("\u70df\u7070\u548c\u6ee4\u6e05\u5668\u58c1");
    model.component("comp2").geom("geom1").run("unisel1");
    model.component("comp2").geom("geom1").create("sel6", "ExplicitSelection");
    model.component("comp2").geom("geom1").feature("sel6").label("\u901a\u9053 B");
    model.component("comp2").geom("geom1").feature("sel6").selection("selection").set("fin", 2);

    model.material().create("mat1", "Common", "");
    model.material().create("mat2", "Common", "");

    model.component("comp2").geom("geom1").run();

    model.component("comp2").material().create("pmat1", "PorousMedia");
    model.component("comp2").material("pmat1").selection().set(4);
    model.component("comp2").material("pmat1").feature().create("fluid1", "Fluid", "comp2");
    model.component("comp2").material("pmat1").feature("fluid1").set("link", "none");
    model.component("comp2").material("pmat1").feature().create("solid1", "Solid", "comp2");
    model.component("comp2").material("pmat1").feature("solid1").set("vfrac", "1-poro");
    model.component("comp2").material().duplicate("pmat2", "pmat1");
    model.component("comp2").material("pmat2").selection().set(3);
    model.component("comp2").material("pmat2").feature("solid1").set("link", "mat2");

    model.component("comp2").physics("chem").feature("rch1").set("Af", "1e13");
    model.component("comp2").physics("chem").feature("rch1").set("ReactionEnthalpy", "UserDefined");
    model.component("comp2").physics("chem").feature("rch1").set("H", "-3.96e5[J/mol]");
    model.component("comp2").physics("chem").feature("O2").set("AdditionalSource", false);
    model.component("comp2").physics("chem").feature("O2").set("sigma", "3.467[angstrom]");
    model.component("comp2").physics("chem").feature("O2").set("epsilonkb", "106.7[K]");
    model.component("comp2").physics("chem").feature("CO2").set("AdditionalSource", false);
    model.component("comp2").physics("chem").feature("CO2").set("sigma", "3.941[angstrom]");
    model.component("comp2").physics("chem").feature("CO2").set("epsilonkb", "195.2[K]");
    model.component("comp2").physics("chem").feature("rch2").set("Af", "5.5e10");
    model.component("comp2").physics("chem").feature("rch2").set("ReactionEnthalpy", "UserDefined");
    model.component("comp2").physics("chem").feature("rch2").set("H", "-1.1e5[J/mol]");
    model.component("comp2").physics("chem").feature("CO").set("AdditionalSource", false);
    model.component("comp2").physics("chem").feature("CO").set("sigma", "3.69[angstrom]");
    model.component("comp2").physics("chem").feature("CO").set("epsilonkb", "91.7[K]");
    model.component("comp2").physics("chem").feature("rch3").set("Af", "4.5e11");
    model.component("comp2").physics("chem").feature("rch3").set("ReactionEnthalpy", "UserDefined");
    model.component("comp2").physics("chem").feature("rch3").set("H", "6.72e4[J/mol]");
    model.component("comp2").physics("chem").feature("CeO2_solid").set("cLock", true);
    model.component("comp2").physics("chem").feature("Ce2O3_solid").set("cLock", true);
    model.component("comp2").physics("chem").feature("rch4").set("Af", "4e8");
    model.component("comp2").physics("chem").feature("rch4").set("ReactionEnthalpy", "UserDefined");
    model.component("comp2").physics("chem").feature("rch4").set("H", "1.21e5[J/mol]");
    model.component("comp2").physics("chem").feature("rch5").set("Af", "1e12");
    model.component("comp2").physics("chem").feature("rch5").set("ReactionEnthalpy", "UserDefined");
    model.component("comp2").physics("chem").feature("rch5").set("H", "-2.24e5[J/mol]");
    model.component("comp2").physics("chem").feature("N2").set("sType", "solvent");
    model.component("comp2").physics("chem").feature("N2").set("sigma", "3.798[angstrom]");
    model.component("comp2").physics("chem").feature("N2").set("epsilonkb", "71.4[K]");
    model.component("comp2").physics("chem").feature("N2").set("Tmid", "3000[K]");
    model.component("comp2").physics("chem").feature("N2").set("Thi", "3000[K]");
    model.component("comp2").physics("chem").feature("N2").set("SpeciesThermoaLo1", 3.298677);
    model.component("comp2").physics("chem").feature("N2").set("SpeciesThermoaLo2", "0.14082404e-2");
    model.component("comp2").physics("chem").feature("N2").set("SpeciesThermoaLo3", "-0.03963222e-4");
    model.component("comp2").physics("chem").feature("N2").set("SpeciesThermoaLo4", "0.05641515e-7");
    model.component("comp2").physics("chem").feature("N2").set("SpeciesThermoaLo5", "-0.02444854e-10");
    model.component("comp2").physics("chem").feature("N2").set("SpeciesThermoaLo6", "-0.10208999e4");
    model.component("comp2").physics("chem").feature("N2").set("SpeciesThermoaLo7", 3.950372);
    model.component("comp2").physics("tds").prop("TransportMechanism").set("MassTransferInPorousMedia", true);
    model.component("comp2").physics("tds").field("concentration").component(new String[]{"cCO", "cCO2", "cN2"});
    model.component("comp2").physics("tds").field("concentration").component(1, "cO2");
    model.component("comp2").physics("tds").field("concentration").component(3, "cCO");
    model.component("comp2").physics("chem").prop("ChemistryModelInputParameter")
         .setIndex("ConcentrationInput", "cCO", 0, 0);
    model.component("comp2").physics("chem").prop("ChemistryModelInputParameter")
         .setIndex("ConcentrationValue", "F_N2_inlet/v_inlet", 2, 0);
    model.component("comp2").physics("chem").prop("ChemistryModelInputParameter")
         .setIndex("ConcentrationInput", "cO2", 3, 0);
    model.component("comp2").physics("chem").prop("ChemistryModelInputParameter")
         .setIndex("SolidConcentration", "C_inlet", 0, 0);
    model.component("comp2").physics("chem").prop("ChemistryModelInputParameter")
         .setIndex("SolidConcentration", "Ce2O3_inlet", 1, 0);
    model.component("comp2").physics("chem").prop("ChemistryModelInputParameter")
         .setIndex("SolidConcentration", "CeO2_inlet", 2, 0);
    model.component("comp2").physics("tds").feature("cdm1").set("DiffusionCoefficientSource", "chem");
    model.component("comp2").physics("tds").feature("cdm1").set("Dchem_cO2_src", "root.comp2.chem.DXX_O2");
    model.component("comp2").physics("tds").feature("cdm1").set("Dchem_cCO2_src", "root.comp2.chem.DXX_CO2");
    model.component("comp2").physics("tds").feature("cdm1").set("Dchem_cCO_src", "root.comp2.chem.DXX_CO");
    model.component("comp2").physics("tds").feature("init1").setIndex("initc", 0, 0);
    model.component("comp2").physics("tds").feature("init1").setIndex("initc", 0, 1);
    model.component("comp2").physics("tds").feature("init1").setIndex("initc", 0, 2);
    model.component("comp2").physics("tds").feature("reac1").selection().named("geom1_sel4");
    model.component("comp2").physics("tds").feature("reac1").setIndex("R_cO2_src", "root.comp2.chem.R_O2", 0);
    model.component("comp2").physics("tds").feature("reac1").setIndex("R_cCO_src", "root.comp2.chem.R_CO", 0);
    model.component("comp2").physics("tds").feature("reac1").set("ReactingVolumeType", "PoreVolume");
    model.component("comp2").physics("tds").feature("in1").selection().named("geom1_sel1");
    model.component("comp2").physics("tds").feature("in1").setIndex("c0", "F_O2_inlet/v_inlet", 0);
    model.component("comp2").physics("tds").feature("in1").setIndex("c0", "F_CO2_inlet/v_inlet", 1);
    model.component("comp2").physics("tds").feature("in1").setIndex("c0", "F_CO_inlet/v_inlet", 2);
    model.component("comp2").physics("tds").feature("out1").selection().named("geom1_sel2");
    model.component("comp2").physics("tds").create("porous1", "PorousMedium", 2);
    model.component("comp2").physics("tds").feature("porous1").selection().set(3, 4);
    model.component("comp2").physics("tds").feature("porous1").feature("fluid1")
         .set("DiffusionCoefficientSource", "chem");
    model.component("comp2").physics("tds").feature("porous1").feature("fluid1")
         .set("Dchem_cO2_src", "root.comp2.chem.DXX_O2");
    model.component("comp2").physics("tds").feature("porous1").feature("fluid1")
         .set("Dchem_cCO2_src", "root.comp2.chem.DXX_CO2");
    model.component("comp2").physics("tds").feature("porous1").feature("fluid1")
         .set("Dchem_cCO_src", "root.comp2.chem.DXX_CO");
    model.component("comp2").physics("tds").feature("porous1").feature("fluid1")
         .set("FluidDiffusivityModelType", "UserDefined");
    model.component("comp2").physics("ht").feature("fluid1").set("k_mat", "root.comp2.chem.kxx");
    model.component("comp2").physics("ht").feature("fluid1").set("fluidType", "gasLiquid");
    model.component("comp2").physics("ht").feature("fluid1").set("rho_mat", "root.comp2.chem.rho");
    model.component("comp2").physics("ht").feature("fluid1").set("Cp_mat", "root.comp2.chem.Cptot");
    model.component("comp2").physics("ht").feature("fluid1").set("gamma_not_IG_mat", "root.comp2.chem.gamma");
    model.component("comp2").physics("ht").feature("init1").set("Tinit", "Tin");
    model.component("comp2").physics("ht").feature("hs1").selection().named("geom1_sel4");
    model.component("comp2").physics("ht").feature("temp1").selection().named("geom1_sel1");
    model.component("comp2").physics("ht").feature("temp1").set("T0", "Tin");
    model.component("comp2").physics("ht").feature("ofl1").selection().named("geom1_sel2");
    model.component("comp2").physics("ht").create("porous1", "PorousMediumHeatTransferModel", 2);
    model.component("comp2").physics("ht").feature("porous1").selection().set(3, 4);
    model.component("comp2").physics("ht").feature("porous1").feature("fluid1").set("k_mat", "root.comp2.chem.kxx");
    model.component("comp2").physics("ht").feature("porous1").feature("fluid1")
         .set("rho_mat", "root.comp2.chem.rho");
    model.component("comp2").physics("ht").feature("porous1").feature("fluid1")
         .set("Cp_mat", "root.comp2.chem.Cptot");
    model.component("comp2").physics("ht").feature("porous1").feature("fluid1").set("gamma_not_IG_mat", "userdef");
    model.component("comp2").physics().move("ht", 2);

    model.material("mat1").propertyGroup("def").set("thermalconductivity", new String[]{"k_s"});
    model.material("mat1").propertyGroup("def").set("density", new String[]{"rho_s"});
    model.material("mat1").propertyGroup("def").set("heatcapacity", new String[]{"Cp_s"});
    model.material("mat2").propertyGroup("def").set("thermalconductivity", new String[]{"k_m"});
    model.material("mat2").propertyGroup("def").set("density", new String[]{"rho_m"});
    model.material("mat2").propertyGroup("def").set("heatcapacity", new String[]{"Cp_m"});

    model.component("comp2").physics("fp").feature("fp1").set("mu_mat", "root.comp2.chem.eta");
    model.component("comp2").physics("fp").feature("inl1").selection().named("geom1_sel1");
    model.component("comp2").physics("fp").feature("inl1").set("BoundaryCondition", "FullyDevelopedFlow");
    model.component("comp2").physics("fp").feature("inl1").set("Uavfdf", "2.5[m/s]");
    model.component("comp2").physics("fp").feature("out1").selection().named("geom1_sel2");
    model.component("comp2").physics("fp").feature("out1").set("NormalFlow", true);
    model.component("comp2").physics("fp").create("porous1", "PorousMedium", 2);
    model.component("comp2").physics("fp").feature("porous1").selection().named("geom1_sel4");
    model.component("comp2").physics("fp").feature("porous1").feature("fluid1").set("mu_mat", "root.comp2.chem.eta");
    model.component("comp2").physics("fp").feature().duplicate("porous2", "porous1");
    model.component("comp2").physics("fp").feature("porous2").selection().named("geom1_sel5");

    model.component("comp2").material("pmat1").propertyGroup("def")
         .set("hydraulicpermeability", new String[]{"kappa_s"});
    model.component("comp2").material("pmat2").propertyGroup("def")
         .set("hydraulicpermeability", new String[]{"kappa_m"});

    model.component("comp2").common().create("free1", "DeformingDomain");
    model.component("comp2").common("free1").selection().all();
    model.component("comp2").common("free1").selection().set(4, 5);
    model.component("comp2").common().create("pnmv1", "PrescribedNormalMeshVelocity");
    model.component("comp2").common("pnmv1").selection().set(11);
    model.component("comp2").common("pnmv1")
         .set("prescribedNormalVelocity", "(-paco*(u*fp.nx+v*fp.ny)-Mc*((y-Y)+dHsoot)*(comp2.chem.r_1+comp2.chem.r_2+comp2.chem.r_3+ comp2.chem.r_4))/rho_s");
    model.component("comp2").common().create("pnmd1", "PrescribedNormalMeshDisplacement");
    model.component("comp2").common("pnmd1").selection().set(8, 10, 15, 16);

    model.component("comp2").mesh("mesh1").create("map1", "Map");
    model.component("comp2").mesh("mesh1").feature("map1").selection().geom("geom1", 2);
    model.component("comp2").mesh("mesh1").feature("map1").selection().set(1, 3, 4, 5);
    model.component("comp2").mesh("mesh1").feature("map1").create("dis1", "Distribution");
    model.component("comp2").mesh("mesh1").feature("map1").feature("dis1").selection().set(1, 17);
    model.component("comp2").mesh("mesh1").feature("map1").feature("dis1").set("type", "predefined");
    model.component("comp2").mesh("mesh1").feature("map1").feature("dis1").set("elemcount", 25);
    model.component("comp2").mesh("mesh1").feature("map1").feature("dis1").set("elemratio", 3);
    model.component("comp2").mesh("mesh1").feature("map1").feature("dis1").set("symmetric", true);
    model.component("comp2").mesh("mesh1").feature("map1").create("dis2", "Distribution");
    model.component("comp2").mesh("mesh1").feature("map1").feature("dis2").selection().set(2);
    model.component("comp2").mesh("mesh1").feature("map1").feature("dis2").set("type", "predefined");
    model.component("comp2").mesh("mesh1").feature("map1").feature("dis2").set("elemcount", 10);
    model.component("comp2").mesh("mesh1").feature("map1").feature("dis2").set("elemratio", 3);
    model.component("comp2").mesh("mesh1").feature("map1").create("dis3", "Distribution");
    model.component("comp2").mesh("mesh1").feature("map1").feature("dis3").selection().set(7, 9, 11, 12);
    model.component("comp2").mesh("mesh1").feature("map1").feature("dis3").set("type", "predefined");
    model.component("comp2").mesh("mesh1").feature("map1").feature("dis3").set("elemcount", 90);
    model.component("comp2").mesh("mesh1").feature("map1").feature("dis3").set("elemratio", 10);
    model.component("comp2").mesh("mesh1").feature("map1").feature("dis3").set("symmetric", true);
    model.component("comp2").mesh("mesh1").feature("map1").create("dis4", "Distribution");
    model.component("comp2").mesh("mesh1").feature("map1").feature("dis4").selection().set(8, 10, 15, 16);
    model.component("comp2").mesh("mesh1").feature("map1").create("dis5", "Distribution");
    model.component("comp2").mesh("mesh1").feature("map1").feature("dis5").selection().set(6, 13);
    model.component("comp2").mesh("mesh1").feature("map1").feature("dis5").set("numelem", 15);
    model.component("comp2").mesh("mesh1").run("map1");
    model.component("comp2").mesh("mesh1").create("map2", "Map");
    model.component("comp2").mesh("mesh1").feature("map2").create("dis1", "Distribution");
    model.component("comp2").mesh("mesh1").feature("map2").feature("dis1").selection().set(4, 18);
    model.component("comp2").mesh("mesh1").feature("map2").feature("dis1").set("type", "predefined");
    model.component("comp2").mesh("mesh1").feature("map2").feature("dis1").set("elemcount", 25);
    model.component("comp2").mesh("mesh1").feature("map2").feature("dis1").set("elemratio", 3);
    model.component("comp2").mesh("mesh1").feature("map2").create("dis2", "Distribution");
    model.component("comp2").mesh("mesh1").feature("map2").feature("dis2").selection().set(14);
    model.component("comp2").mesh("mesh1").feature("map2").feature("dis2").set("type", "predefined");
    model.component("comp2").mesh("mesh1").feature("map2").feature("dis2").set("elemcount", 10);
    model.component("comp2").mesh("mesh1").feature("map2").feature("dis2").set("elemratio", 3);
    model.component("comp2").mesh("mesh1").run();

    model.component("comp2").view("view1").hideEntities().create("hide1");
    model.component("comp2").view("view1").hideEntities("hide1").geom("geom1", 1);
    model.component("comp2").view("view1").hideEntities("hide1").set(12);

    model.study("std2").feature("stat").setSolveFor("/physics/chem", false);
    model.study("std2").feature("stat").setSolveFor("/physics/tds", false);
    model.study("std2").feature("stat").setSolveFor("/physics/ht", false);
    model.study("std2").feature("stat").setSolveFor("/physics/fp", false);
    model.study("std2").feature("stat").setSolveFor("/frame/spatial1", false);
    model.study("std2").create("time", "Transient");
    model.study("std2").feature("time").setSolveFor("/physics/re", false);
    model.study("std2").feature("time").set("tlist", "range(0,300,1800)");
    model.study("std2").showAutoSequences("all");

    model.sol("sol5").feature("v2").feature("comp2_cCO").set("scalemethod", "manual");
    model.sol("sol5").feature("v2").feature("comp2_cCO2").set("scalemethod", "manual");
    model.sol("sol5").feature("v2").feature("comp2_cO2").set("scalemethod", "manual");
    model.sol("sol5").feature("v2").feature("comp2_T").set("scalemethod", "init");
    model.sol("sol5").feature("t1").feature("se1").feature().remove("ss4");
    model.sol("sol5").feature("t1").feature("se1").feature("ss2").label("\u6d53\u5ea6\u548c\u6e29\u5ea6");
    model.sol("sol5").feature("t1").feature("se1").feature("ss2")
         .set("segvar", new String[]{"comp2_cO2", "comp2_cCO2", "comp2_cCO", "comp2_T"});

    model.component("comp2").func().create("step1", "Step");
    model.component("comp2").func("step1").set("location", 0.5);
    model.component("comp2").func("step1").set("smooth", 1);

    model.component("comp2").physics("tds").feature("in1").setIndex("c0", "F_O2_inlet/v_inlet*step1(t[1/s])", 0);
    model.component("comp2").physics("tds").feature("in1").setIndex("c0", "F_CO2_inlet/v_inlet*step1(t[1/s])", 1);
    model.component("comp2").physics("tds").feature("in1").setIndex("c0", "F_CO_inlet/v_inlet*step1(t[1/s])", 2);

    model.study("std2").createAutoSequences("all");

    model.sol("sol5").runAll();

    model.result().create("pg3", "PlotGroup2D");
    model.result("pg3").set("data", "dset3");
    model.result("pg3").setIndex("looplevel", 7, 0);
    model.result("pg3").label("\u6d53\u5ea6, O2 (tds)");
    model.result("pg3").set("titletype", "custom");
    model.result("pg3").set("prefixintitle", "");
    model.result("pg3").set("expressionintitle", false);
    model.result("pg3").set("typeintitle", false);
    model.result("pg3").create("surf1", "Surface");
    model.result("pg3").feature("surf1").set("expr", new String[]{"cO2"});
    model.result("pg3").feature("surf1").set("colortable", "Prism");
    model.result("pg3").set("typeintitle", true);
    model.result("pg3").create("arws1", "ArrowSurface");
    model.result("pg3").feature("arws1").set("expr", new String[]{"tds.tflux_cO2x", "tds.tflux_cO2y"});
    model.result("pg3").feature("arws1").set("xnumber", 10);
    model.result("pg3").feature("arws1").set("ynumber", 10);
    model.result("pg3").feature("arws1").set("color", "black");
    model.result("pg3").feature("arws1").create("sel1", "Selection");
    model.result("pg3").feature("arws1").feature("sel1").selection().set(1, 2, 3, 4, 5);
    model.result().create("pg4", "PlotGroup2D");
    model.result("pg4").set("data", "dset3");
    model.result("pg4").setIndex("looplevel", 7, 0);
    model.result("pg4").label("\u6d53\u5ea6, CO2 (tds)");
    model.result("pg4").set("titletype", "custom");
    model.result("pg4").set("prefixintitle", "");
    model.result("pg4").set("expressionintitle", false);
    model.result("pg4").set("typeintitle", false);
    model.result("pg4").create("surf1", "Surface");
    model.result("pg4").feature("surf1").set("expr", new String[]{"cCO2"});
    model.result("pg4").feature("surf1").set("colortable", "Prism");
    model.result("pg4").set("typeintitle", true);
    model.result("pg4").create("arws1", "ArrowSurface");
    model.result("pg4").feature("arws1").set("expr", new String[]{"tds.tflux_cCO2x", "tds.tflux_cCO2y"});
    model.result("pg4").feature("arws1").set("xnumber", 10);
    model.result("pg4").feature("arws1").set("ynumber", 10);
    model.result("pg4").feature("arws1").set("color", "black");
    model.result("pg4").feature("arws1").create("sel1", "Selection");
    model.result("pg4").feature("arws1").feature("sel1").selection().set(1, 2, 3, 4, 5);
    model.result().create("pg5", "PlotGroup2D");
    model.result("pg5").set("data", "dset3");
    model.result("pg5").setIndex("looplevel", 7, 0);
    model.result("pg5").label("\u6d53\u5ea6, CO (tds)");
    model.result("pg5").set("titletype", "custom");
    model.result("pg5").set("prefixintitle", "");
    model.result("pg5").set("expressionintitle", false);
    model.result("pg5").set("typeintitle", false);
    model.result("pg5").create("surf1", "Surface");
    model.result("pg5").feature("surf1").set("expr", new String[]{"cCO"});
    model.result("pg5").feature("surf1").set("colortable", "Prism");
    model.result("pg5").set("typeintitle", true);
    model.result("pg5").create("arws1", "ArrowSurface");
    model.result("pg5").feature("arws1").set("expr", new String[]{"tds.tflux_cCOx", "tds.tflux_cCOy"});
    model.result("pg5").feature("arws1").set("xnumber", 10);
    model.result("pg5").feature("arws1").set("ynumber", 10);
    model.result("pg5").feature("arws1").set("color", "black");
    model.result("pg5").feature("arws1").create("sel1", "Selection");
    model.result("pg5").feature("arws1").feature("sel1").selection().set(1, 2, 3, 4, 5);
    model.result().create("pg6", "PlotGroup2D");
    model.result("pg6").label("\u6e29\u5ea6 (ht)");
    model.result("pg6").feature().create("surf1", "Surface");
    model.result("pg6").feature("surf1").set("showsolutionparams", "on");
    model.result("pg6").feature("surf1").set("solutionparams", "parent");
    model.result("pg6").feature("surf1").set("expr", "T");
    model.result("pg6").feature("surf1").set("colortable", "HeatCameraLight");
    model.result("pg6").feature("surf1").set("showsolutionparams", "on");
    model.result("pg6").feature("surf1").set("data", "parent");
    model.result().dataset("dset3").set("geom", "geom1");
    model.result().create("pg7", "PlotGroup2D");
    model.result("pg7").label("\u901f\u5ea6 (fp)");
    model.result("pg7").set("frametype", "spatial");
    model.result("pg7").feature().create("surf1", "Surface");
    model.result("pg7").feature("surf1").label("\u8868\u9762");
    model.result("pg7").feature("surf1").set("showsolutionparams", "on");
    model.result("pg7").feature("surf1").set("expr", "fp.U");
    model.result("pg7").feature("surf1").set("colortable", "Rainbow");
    model.result("pg7").feature("surf1").set("smooth", "internal");
    model.result("pg7").feature("surf1").set("showsolutionparams", "on");
    model.result("pg7").feature("surf1").set("data", "parent");
    model.result().create("pg8", "PlotGroup2D");
    model.result("pg8").label("\u538b\u529b (fp)");
    model.result("pg8").set("frametype", "spatial");
    model.result("pg8").feature().create("con1", "Contour");
    model.result("pg8").feature("con1").label("\u7b49\u503c\u7ebf");
    model.result("pg8").feature("con1").set("showsolutionparams", "on");
    model.result("pg8").feature("con1").set("expr", "p");
    model.result("pg8").feature("con1").set("number", 40);
    model.result("pg8").feature("con1").set("levelrounding", false);
    model.result("pg8").feature("con1").set("colortable", "Rainbow");
    model.result("pg8").feature("con1").set("smooth", "internal");
    model.result("pg8").feature("con1").set("showsolutionparams", "on");
    model.result("pg8").feature("con1").set("data", "parent");
    model.result().create("pg9", "PlotGroup2D");
    model.result("pg9").label("\u6e29\u5ea6\u548c\u6d41\u4f53\u6d41\u52a8 (nitf1)");
    model.result("pg9").set("showlegendsunit", true);
    model.result("pg9").feature().create("surf1", "Surface");
    model.result("pg9").feature("surf1").label("\u6d41\u4f53\u6e29\u5ea6");
    model.result("pg9").feature("surf1").set("showsolutionparams", "on");
    model.result("pg9").feature("surf1").set("solutionparams", "parent");
    model.result("pg9").feature("surf1").set("expr", "nitf1.T");
    model.result("pg9").feature("surf1").set("colortable", "HeatCameraLight");
    model.result("pg9").feature("surf1").set("smooth", "internal");
    model.result("pg9").feature("surf1").set("showsolutionparams", "on");
    model.result("pg9").feature("surf1").set("data", "parent");
    model.result("pg9").feature("surf1").feature().create("sel1", "Selection");
    model.result("pg9").feature("surf1").feature("sel1").selection().geom("geom1", 2);
    model.result("pg9").feature("surf1").feature("sel1").selection().set(1, 2, 3, 4, 5);
    model.result("pg9").feature().create("arws1", "ArrowSurface");
    model.result("pg9").feature("arws1").label("\u6d41\u4f53\u6d41\u52a8");
    model.result("pg9").feature("arws1").set("showsolutionparams", "on");
    model.result("pg9").feature("arws1").set("solutionparams", "parent");
    model.result("pg9").feature("arws1").set("expr", new String[]{"nitf1.ux", "nitf1.uy"});
    model.result("pg9").feature("arws1").set("xnumber", 30);
    model.result("pg9").feature("arws1").set("ynumber", 30);
    model.result("pg9").feature("arws1").set("arrowtype", "cone");
    model.result("pg9").feature("arws1").set("arrowlength", "logarithmic");
    model.result("pg9").feature("arws1").set("showsolutionparams", "on");
    model.result("pg9").feature("arws1").set("data", "parent");
    model.result("pg9").feature("arws1").feature().create("col1", "Color");
    model.result("pg9").feature("arws1").feature("col1").set("showcolordata", "off");
    model.result("pg9").feature("arws1").feature("col1").set("expr", "fp.U");
    model.result("pg9").feature("arws1").feature("col1").set("colortable", "Rainbow");
    model.result("pg9").feature("arws1").feature().create("filt1", "Filter");
    model.result("pg9").feature("arws1").feature("filt1").set("expr", "fp.U>nitf1.Uave");
    model.result().create("pg10", "PlotGroup2D");
    model.result("pg10").set("data", "dset3");
    model.result("pg10").setIndex("looplevel", 7, 0);
    model.result("pg10").label("\u52a8\u7f51\u683c");
    model.result("pg10").create("mesh1", "Mesh");
    model.result("pg10").feature("mesh1").set("meshdomain", "surface");
    model.result("pg10").feature("mesh1").set("colortable", "TrafficFlow");
    model.result("pg10").feature("mesh1").set("colortabletrans", "nonlinear");
    model.result("pg10").feature("mesh1").set("nonlinearcolortablerev", true);
    model.result("pg10").feature("mesh1").create("sel1", "MeshSelection");
    model.result("pg10").feature("mesh1").feature("sel1").selection().set(4, 5);
    model.result("pg10").feature("mesh1").set("qualmeasure", "custom");
    model.result("pg10").feature("mesh1").set("qualexpr", "comp2.spatial.relVol");
    model.result("pg10").feature("mesh1").set("colorrangeunitinterval", false);
    model.result("pg3").run();
    model.result("pg3").run();
    model.result("pg3").feature("arws1").set("arrowlength", "normalized");
    model.result("pg3").feature("arws1").set("scaleactive", true);
    model.result("pg3").feature("arws1").set("scale", "6e-4");
    model.result("pg3").run();
    model.result("pg4").run();
    model.result("pg4").feature("arws1").set("arrowlength", "normalized");
    model.result("pg4").feature("arws1").set("scaleactive", true);
    model.result("pg4").feature("arws1").set("scale", "1.4e-3");
    model.result("pg4").run();
    model.result("pg5").run();
    model.result("pg5").feature("arws1").set("arrowlength", "normalized");
    model.result("pg5").feature("arws1").set("scaleactive", true);
    model.result("pg5").feature("arws1").set("scale", 0.13);
    model.result("pg5").run();
    model.result("pg7").run();
    model.result("pg7").feature("surf1").set("colortable", "Viridis");
    model.result("pg7").run();
    model.result("pg7").run();
    model.result("pg7").create("str1", "Streamline");
    model.result("pg7").feature("str1").set("selnumber", 16);
    model.result("pg7").feature("str1").set("expr", new String[]{"u", "v"});
    model.result("pg7").feature("str1")
         .set("descr", "\u901f\u5ea6\u573a \uff08\u7a7a\u95f4\u5750\u6807\u7cfb\uff09");
    model.result("pg7").feature("str1").selection().set(1);
    model.result("pg7").feature("str1").set("pointtype", "arrow");
    model.result("pg7").feature("str1").set("arrowdistr", "equaltime");
    model.result("pg7").feature("str1").set("arrowlength", "logarithmic");
    model.result("pg7").feature("str1").set("arrowscaleactive", true);
    model.result("pg7").feature("str1").set("arrowscale", 0.003);
    model.result("pg7").feature("str1").set("color", "white");
    model.result("pg7").run();
    model.result("pg8").run();
    model.result("pg8").run();
    model.result("pg8").feature("con1").active(false);
    model.result("pg8").run();
    model.result("pg8").create("surf1", "Surface");
    model.result("pg8").feature("surf1").set("expr", "p");
    model.result("pg8").run();
    model.result("pg6").run();
    model.result("pg6").run();
    model.result().create("pg11", "PlotGroup1D");
    model.result("pg11").run();
    model.result("pg11").label("\u70df\u7070\u5c42\u539a\u5ea6");
    model.result("pg11").set("data", "dset3");
    model.result("pg11").set("titletype", "none");
    model.result("pg11").set("xlabelactive", true);
    model.result("pg11").set("xlabel", "L (m)");
    model.result("pg11").set("ylabelactive", true);
    model.result("pg11").set("ylabel", "y \u4f4d\u79fb (\\mu m)");
    model.result("pg11").set("legendpos", "lowermiddle");
    model.result("pg11").create("lngr1", "LineGraph");
    model.result("pg11").feature("lngr1").set("markerpos", "datapoints");
    model.result("pg11").feature("lngr1").set("linewidth", "preference");
    model.result("pg11").feature("lngr1").selection().set(11);
    model.result("pg11").feature("lngr1").set("expr", "y-Y+dHsoot");
    model.result("pg11").feature("lngr1").set("unit", "\u00b5m");
    model.result("pg11").feature("lngr1").set("linewidth", 2);
    model.result("pg11").feature("lngr1").set("legend", true);
    model.result("pg11").run();
    model.result().create("pg12", "PlotGroup1D");
    model.result("pg12").run();
    model.result("pg12").set("data", "dset3");
    model.result("pg12").create("glob1", "Global");
    model.result("pg12").feature("glob1").set("markerpos", "datapoints");
    model.result("pg12").feature("glob1").set("linewidth", "preference");
    model.result("pg12").feature("glob1").set("expr", new String[]{"fp.inl1.pAverage"});
    model.result("pg12").feature("glob1")
         .set("descr", new String[]{"\u7279\u5f81\u9009\u62e9\u7684\u5e73\u5747\u538b\u529b"});

    return model;
  }

  public static Model run4(Model model) {
    model.result("pg12").feature("glob1").set("unit", new String[]{"Pa"});
    model.result("pg12").feature("glob1").setIndex("descr", "\u5e73\u5747\u5165\u53e3\u538b\u529b", 0);
    model.result("pg12").feature("glob1").set("linewidth", 2);
    model.result("pg12").run();
    model.result("pg12").run();
    model.result("pg12").label("\u5165\u53e3\u538b\u529b");
    model.result("pg12").set("titletype", "none");
    model.result("pg12").set("legendpos", "middleright");

    model.study("std1").feature("spf").setSolveFor("/frame/spatial1", false);

    model.result("pg7").run();

    model.title("\u67f4\u6cb9\u6ee4\u6e05\u5668\u4e2d\u7684\u5316\u5b66\u53cd\u5e94\u548c\u70df\u7070\u7d2f\u79ef");

    model
         .description("\u672c\u4f8b\u5c06\u67f4\u6cb9\u673a\u8fc7\u6ee4\u7cfb\u7edf\u4f5c\u4e3a\u7406\u60f3\u53cd\u5e94\u5668\u548c\u8be6\u7ec6\u7684\u7a7a\u95f4\u76f8\u5173\u5355\u5143\u8fdb\u884c\u5206\u6790\uff0c\u7814\u7a76\u4e86\u591a\u5b54\u819c\u5c06\u5176\u4e2d\u901a\u8fc7\u7684\u7164\u70df\u9897\u7c92\u4e0e\u5e9f\u6c14\u5206\u79bb\u7684\u539f\u7406\u3002\u50ac\u5316\u548c\u975e\u50ac\u5316\u53cd\u5e94\u90fd\u80fd\u6291\u5236\u70df\u7070\u5c42\u7684\u5f62\u6210\uff1b\u5176\u4e2d\u7684\u78b3\u6c27\u5316\u5f62\u6210\u4e00\u6c27\u5316\u78b3\u548c\u4e8c\u6c27\u5316\u78b3\uff0c\u8fd9\u4e9b\u6c14\u4f53\u90fd\u80fd\u901a\u8fc7\u591a\u5b54\u819c\u3002\u8fd9\u4e00\u7a7a\u95f4\u76f8\u5173\u7684\u6a21\u578b\u4f7f\u7528\u201c\u52a8\u7f51\u683c\u201d\u63a5\u53e3\u6765\u5305\u542b\u819c\u5185\u5f62\u6210\u7684\u70df\u7070\u5c42\u7684\u5f62\u72b6\u53d8\u5316\u3002");

    model.label("diesel_filter.mph");

    return model;
  }

  public static void main(String[] args) {
    Model model = run();
    model = run2(model);
    model = run3(model);
    run4(model);
  }

}
