/*
 * hopping_hoop.java
 */

import com.comsol.model.*;
import com.comsol.model.util.*;

/** Model exported on Apr 30 2026, 11:27 by COMSOL 6.3.0.290. */
public class hopping_hoop {

  public static Model run() {
    Model model = ModelUtil.create("Model");

    model
         .modelPath("D:\\Program Files\\COMSOL\\COMSOL63\\Multiphysics\\applications\\Multibody_Dynamics_Module\\Verification_Examples");

    model.component().create("comp1", true);

    model.component("comp1").geom().create("geom1", 2);

    model.component("comp1").mesh().create("mesh1");

    model.component("comp1").physics().create("mbd", "MultibodyDynamics", "geom1");

    model.study().create("std1");
    model.study("std1").create("time", "Transient");
    model.study("std1").feature("time").setSolveFor("/physics/mbd", true);

//    To import content from file, use:
//    model.param().loadFile("FILENAME");
    model.param().set("Rc", "1[m]", "\u73af\u534a\u5f84");
    model.param().set("Lbase", "10*pi*Rc", "\u5e73\u9762\u957f\u5ea6");
    model.param().set("mtot", "1[kg]", "\u603b\u8d28\u91cf");
    model.param().set("gamma", "0.75", "\u8d28\u91cf\u6bd4");
    model.param().set("v0", "0.1[m/s]", "\u521d\u59cb\u901f\u5ea6");
    model.param().set("omega0", "v0/Rc", "\u521d\u59cb\u89d2\u901f\u5ea6");
    model.param().set("mu", "1", "\u6469\u64e6\u7cfb\u6570");
    model.param().set("Wk0", "mtot*v0^2*(1+gamma)", "\u521d\u59cb\u52a8\u80fd");
    model.param().set("Wgmax", "mtot*gamma*g_const*2*Rc", "\u53ef\u7528\u7684\u52bf\u80fd");
    model.param().set("vmax", "sqrt((Wgmax/mtot+v0^2*(1+gamma))/(1-gamma))", "\u6700\u5927\u901f\u5ea6");
    model.param().set("vchar", "vmax-6[m/s]", "\u4f30\u8ba1\u7684\u5e73\u5747\u901f\u5ea6");
    model.param().set("t_end", "10*pi*Rc/vchar", "\u4eff\u771f\u65f6\u95f4");
    model.param().set("dt", "Rc/vmax/36", "\u65f6\u6b65");

    model.component("comp1").geom("geom1").create("c1", "Circle");
    model.component("comp1").geom("geom1").feature("c1").set("r", "Rc");
    model.component("comp1").geom("geom1").feature("c1").setIndex("layer", "0.1*Rc", 0);
    model.component("comp1").geom("geom1").run("c1");
    model.component("comp1").geom("geom1").create("del1", "Delete");
    model.component("comp1").geom("geom1").feature("del1").selection("input").init(2);
    model.component("comp1").geom("geom1").feature("del1").selection("input").set("c1", 5);
    model.component("comp1").geom("geom1").run("del1");
    model.component("comp1").geom("geom1").create("r1", "Rectangle");
    model.component("comp1").geom("geom1").feature("r1").set("size", new String[]{"Lbase", "0.1"});
    model.component("comp1").geom("geom1").feature("r1").set("pos", new double[]{-0.1, -1.1});
    model.component("comp1").geom("geom1").run("r1");
    model.component("comp1").geom("geom1").feature("fin").set("action", "assembly");
    model.component("comp1").geom("geom1").feature("fin").set("createpairs", false);
    model.component("comp1").geom("geom1").run("fin");

    model.component("comp1").selection().create("sel1", "Explicit");
    model.component("comp1").selection("sel1").label("\u70b9\u8d28\u91cf");
    model.component("comp1").selection("sel1").geom(0);
    model.component("comp1").selection("sel1").set(6);
    model.component("comp1").selection().create("sel2", "Explicit");
    model.component("comp1").selection("sel2").label("\u73af\u8fb9");
    model.component("comp1").selection("sel2").geom(1);
    model.component("comp1").selection("sel2").set(5);
    model.component("comp1").selection("sel2").set("groupcontang", true);

    model.component("comp1").cpl().create("aveop1", "Average");
    model.component("comp1").cpl("aveop1").set("axisym", true);
    model.component("comp1").cpl("aveop1").label("\u5e73\u5747\u503c\uff1a\u70b9\u8d28\u91cf");
    model.component("comp1").cpl("aveop1").selection().geom("geom1", 0);
    model.component("comp1").cpl("aveop1").selection().named("sel1");
    model.component("comp1").cpl().duplicate("aveop2", "aveop1");
    model.component("comp1").cpl("aveop2").label("\u5e73\u5747\u503c\uff1a\u73af\u8fb9");
    model.component("comp1").cpl("aveop2").selection().geom("geom1", 1);
    model.component("comp1").cpl("aveop2").selection().named("sel2");

    model.component("comp1").variable().create("var1");
    model.component("comp1").variable("var1").set("Wg", "g_const*mtot*((aveop1(y)-Rc)*gamma+aveop2(y)*(1-gamma))");
    model.component("comp1").variable("var1").descr("Wg", "\u5f53\u524d\u52bf\u80fd");

    model.component("comp1").physics("mbd").prop("InitialValues").set("ut_Init", new String[]{"v0", "0", "0"});
    model.component("comp1").physics("mbd").prop("InitialValues").set("phit_Init", "-omega0");
    model.component("comp1").physics("mbd").create("rd1", "RigidDomain", 2);
    model.component("comp1").physics("mbd").feature("rd1").label("\u521a\u6027\u6750\u6599\uff1a\u5e73\u9762");
    model.component("comp1").physics("mbd").feature("rd1").selection().set(5);
    model.component("comp1").physics("mbd").feature("rd1").set("rho_mat", "userdef");
    model.component("comp1").physics("mbd").feature("rd1").create("fix1", "FixedConstraint", -1);
    model.component("comp1").physics("mbd").create("rd2", "RigidDomain", 2);
    model.component("comp1").physics("mbd").feature("rd2").label("\u521a\u6027\u6750\u6599\uff1a\u73af");
    model.component("comp1").physics("mbd").feature("rd2").selection().set(1, 2, 3, 4);
    model.component("comp1").physics("mbd").feature("rd2").set("rho_mat", "userdef");
    model.component("comp1").physics("mbd").feature("rd2").create("mmi1", "MassInertia", -1);
    model.component("comp1").physics("mbd").feature("rd2").feature("mmi1")
         .set("CenterOfMassType", "CentroidOfSelectedEntities");
    model.component("comp1").physics("mbd").feature("rd2").feature("mmi1").set("EntityLevel", "Point");
    model.component("comp1").physics("mbd").feature("rd2").feature("mmi1").set("mt", "mtot*gamma");
    model.component("comp1").physics("mbd").feature("rd2").feature("mmi1").feature("cmp1").selection().named("sel1");
    model.component("comp1").physics("mbd").create("adm1", "AddedMass1", 1);
    model.component("comp1").physics("mbd").feature("adm1").label("\u9644\u52a0\u8d28\u91cf\uff1a\u73af");
    model.component("comp1").physics("mbd").feature("adm1").selection().named("sel2");
    model.component("comp1").physics("mbd").feature("adm1").set("MassType", "mTot");
    model.component("comp1").physics("mbd").feature("adm1")
         .set("mTot", new String[]{"mtot*(1-gamma)", "0", "0", "0", "mtot*(1-gamma)", "0", "0", "0", "mtot*(1-gamma)"});
    model.component("comp1").physics("mbd").create("gacc1", "GravityAcceleration", -1);
    model.component("comp1").physics("mbd").create("rbc1", "RigidBodyContact", -1);
    model.component("comp1").physics("mbd").feature("rbc1").set("Source", "rd2");
    model.component("comp1").physics("mbd").feature("rbc1").set("DestinationShape", "Planar");
    model.component("comp1").physics("mbd").feature("rbc1").selection("planarDestinationSelection").set(15);
    model.component("comp1").physics("mbd").feature("rbc1").set("fp", 0.001);
    model.component("comp1").physics("mbd").feature("rbc1").set("taun", "0.05[ms]");
    model.component("comp1").physics("mbd").feature("rbc1").set("storeContactEnergy", true);
    model.component("comp1").physics("mbd").feature("rbc1").create("fric1", "Friction", -1);
    model.component("comp1").physics("mbd").feature("rbc1").feature("fric1").set("mu", "mu");
    model.component("comp1").physics("mbd").feature("rbc1").feature("fric1").set("v0", "1e-4");
    model.component("comp1").physics("mbd").feature("rbc1").feature("fric1").set("storeFrictionEnergy", true);

    model.component("comp1").mesh("mesh1").create("edg1", "Edge");
    model.component("comp1").mesh("mesh1").feature("edg1").selection().named("sel2");
    model.component("comp1").mesh("mesh1").feature("edg1").create("dis1", "Distribution");
    model.component("comp1").mesh("mesh1").feature("edg1").feature("dis1").set("numelem", 10);
    model.component("comp1").mesh("mesh1").create("map1", "Map");
    model.component("comp1").mesh("mesh1").feature("map1").create("dis1", "Distribution");
    model.component("comp1").mesh("mesh1").feature("map1").feature("dis1").selection().set(15);
    model.component("comp1").mesh("mesh1").feature("map1").feature("dis1").set("numelem", 1);
    model.component("comp1").mesh("mesh1").run();

    model.study("std1").create("param", "Parametric");
    model.study("std1").feature("param").setIndex("pname", "Rc", 0);
    model.study("std1").feature("param").setIndex("plistarr", "", 0);
    model.study("std1").feature("param").setIndex("punit", "m", 0);
    model.study("std1").feature("param").setIndex("pname", "Rc", 0);
    model.study("std1").feature("param").setIndex("plistarr", "", 0);
    model.study("std1").feature("param").setIndex("punit", "m", 0);
    model.study("std1").feature("param").setIndex("pname", "v0", 0);
    model.study("std1").feature("param").setIndex("plistarr", "0.1 1 2 2.8 3.1 3.5", 0);
    model.study("std1").feature("time").set("tlist", "range(0,dt,t_end)");
    model.study("std1").feature("time").set("usertol", true);
    model.study("std1").feature("time").set("rtol", "0.0001");
    model.study("std1").showAutoSequences("all");

    model.sol("sol1").feature("t1").set("maxorder", 3);
    model.sol("sol1").feature("t1").set("consistent", false);

    model.study("std1").createAutoSequences("all");

    model.sol().create("sol2");
    model.sol("sol2").study("std1");
    model.sol("sol2").label("\u53c2\u6570\u5316\u89e3 1");

    model.batch("p1").feature("so1").set("psol", "sol2");
    model.batch("p1").run("compute");

    model.result().create("pg1", "PlotGroup2D");
    model.result("pg1").label("\u4f4d\u79fb (mbd)");
    model.result("pg1").set("data", "dset2");
    model.result("pg1").setIndex("looplevel", 2258, 0);
    model.result("pg1").setIndex("looplevel", 6, 1);
    model.result("pg1").set("frametype", "spatial");
    model.result("pg1").feature().create("surf1", "Surface");
    model.result("pg1").feature("surf1").label("\u8868\u9762");
    model.result("pg1").feature("surf1").set("colortable", "SpectrumLight");
    model.result("pg1").feature("surf1").set("data", "parent");
    model.result("pg1").feature("surf1").feature().create("def1", "Deform");
    model.result("pg1").feature("surf1").feature("def1").label("\u53d8\u5f62");
    model.result("pg1").feature("surf1").feature("def1").set("scaleactive", true);
    model.result().create("pg2", "PlotGroup2D");
    model.result("pg2").label("\u901f\u5ea6 (mbd)");
    model.result("pg2").set("data", "dset2");
    model.result("pg2").setIndex("looplevel", 2258, 0);
    model.result("pg2").setIndex("looplevel", 6, 1);
    model.result("pg2").set("frametype", "spatial");
    model.result("pg2").feature().create("surf1", "Surface");
    model.result("pg2").feature("surf1").label("\u57df\u7f16\u53f7");
    model.result("pg2").feature("surf1").set("descractive", true);
    model.result("pg2").feature("surf1").set("expr", "mod(dom,10)");
    model.result("pg2").feature("surf1").set("descr", "\u57df\u7f16\u53f7");
    model.result("pg2").feature("surf1").set("rangecoloractive", "on");
    model.result("pg2").feature("surf1").set("rangecolormin", -0.5);
    model.result("pg2").feature("surf1").set("rangecolormax", 9.5);
    model.result("pg2").feature("surf1").set("colortable", "Cyclic");
    model.result("pg2").feature("surf1").set("colorlegend", false);
    model.result("pg2").feature("surf1").set("colortabletype", "discrete");
    model.result("pg2").feature("surf1").set("smooth", "none");
    model.result("pg2").feature("surf1").set("data", "parent");
    model.result("pg2").feature("surf1").feature().create("def1", "Deform");
    model.result("pg2").feature("surf1").feature("def1").label("\u53d8\u5f62");
    model.result("pg2").feature("surf1").feature("def1").set("scaleactive", true);
    model.result("pg2").feature().create("arwl1", "ArrowLine");
    model.result("pg2").feature("arwl1").label("\u7ebf\u4e0a\u7bad\u5934");
    model.result("pg2").feature("arwl1").set("expr", new String[]{"mbd.u_tX", "mbd.u_tY"});
    model.result("pg2").feature("arwl1").set("placement", "elements");
    model.result("pg2").feature("arwl1").set("data", "parent");
    model.result("pg2").feature("arwl1").feature().create("def1", "Deform");
    model.result("pg2").feature("arwl1").feature("def1").label("\u53d8\u5f62");
    model.result("pg2").feature("arwl1").feature("def1").set("scaleactive", true);
    model.result("pg1").run();
    model.result("pg2").run();
    model.result("pg2").set("titletype", "none");
    model.result("pg2").set("showlegends", false);
    model.result("pg2").run();
    model.result("pg2").feature("surf1").set("expr", "mbd.vel");
    model.result("pg2").feature("surf1").set("colortable", "SpectrumLight");
    model.result("pg2").run();
    model.result("pg2").feature().remove("arwl1");
    model.result("pg2").run();
    model.result("pg2").run();
    model.result("pg2").create("pttraj1", "PointTrajectories");
    model.result("pg2").feature("pttraj1").label("\u70b9\u8f68\u8ff9\uff1a\u70b9\u8d28\u91cf");
    model.result("pg2").feature("pttraj1").selection().named("sel1");
    model.result("pg2").feature("pttraj1").set("linetype", "tube");
    model.result("pg2").feature("pttraj1").set("tuberadiusscaleactive", true);
    model.result("pg2").feature("pttraj1").set("tuberadiusscale", 0.03);
    model.result("pg2").feature("pttraj1").set("pointtype", "point");
    model.result("pg2").feature("pttraj1").set("pointradiusexpr", "0.15");
    model.result("pg2").feature("pttraj1").set("sphereradiusscaleactive", true);
    model.result("pg2").feature("pttraj1").set("pointcolor", "magenta");
    model.result("pg2").feature().duplicate("pttraj2", "pttraj1");
    model.result("pg2").run();
    model.result("pg2").feature("pttraj2").label("\u70b9\u8f68\u8ff9\uff1a\u91cd\u5fc3");
    model.result("pg2").feature("pttraj2").set("plotdata", "global");
    model.result("pg2").feature("pttraj2").set("expr", new String[]{"aveop1(x)*gamma+aveop2(x)*(1-gamma)", "0"});
    model.result("pg2").feature("pttraj2").setIndex("expr", "aveop1(y)*gamma+aveop2(y)*(1-gamma)", 1);
    model.result("pg2").feature("pttraj2").set("pointtype", "none");
    model.result("pg2").feature("pttraj2").create("col1", "Color");
    model.result("pg2").run();
    model.result("pg2").feature("pttraj2").feature("col1").set("expr", "aveop2(y)>1e-3");
    model.result("pg2").feature("pttraj2").feature("col1").set("colortable", "TrafficLight");
    model.result("pg2").run();
    model.result("pg2").feature().duplicate("pttraj3", "pttraj1");
    model.result("pg2").run();
    model.result("pg2").feature("pttraj3").label("\u70b9\u8f68\u8ff9\uff1a\u63a5\u89e6\u529b");
    model.result("pg2").feature("pttraj3").set("plotdata", "global");
    model.result("pg2").feature("pttraj3").set("expr", new String[]{"aveop2(x)", "aveop2(y)-Rc"});
    model.result("pg2").feature("pttraj3").set("linetype", "none");
    model.result("pg2").feature("pttraj3").set("pointtype", "arrow");
    model.result("pg2").feature("pttraj3").set("arrowexpr", new String[]{"0", "-mbd.rbc1.Fny"});
    model.result("pg2").feature("pttraj3").set("arrowscaleactive", true);
    model.result("pg2").feature("pttraj3").set("arrowscale", 0.08);
    model.result("pg2").feature("pttraj3").set("pointcolor", "red");
    model.result("pg2").feature().duplicate("pttraj4", "pttraj3");
    model.result("pg2").run();
    model.result("pg2").feature("pttraj4").label("\u70b9\u8f68\u8ff9\uff1a\u6469\u64e6\u529b");
    model.result("pg2").feature("pttraj4").setIndex("arrowexpr", "mbd.rbc1.Ffx", 0);
    model.result("pg2").feature("pttraj4").setIndex("arrowexpr", 0, 1);
    model.result("pg2").feature("pttraj4").set("inheritplot", "pttraj3");
    model.result("pg2").run();
    model.result("pg2").set("edges", false);
    model.result("pg2").set("view", "new");
    model.result("pg2").set("looplevel", new int[]{2, 6});
    model.result("pg2").run();
    model.result("pg2").run();
    model.result("pg2").feature("surf1").set("data", "dset2");
    model.result("pg2").feature("surf1").set("looplevel", new String[]{"interp", "1"});
    model.result("pg2").feature("surf1").set("interp", new double[]{5.2});
    model.result("pg2").run();
    model.result("pg2").feature("pttraj1").set("data", "dset2");
    model.result("pg2").feature("pttraj1").set("looplevel", new String[]{"interp", "1"});
    model.result("pg2").feature("pttraj1").set("interp", new double[]{5.2});
    model.result("pg2").run();
    model.result("pg2").feature("pttraj2").set("data", "dset2");
    model.result("pg2").feature("pttraj2").set("looplevel", new String[]{"interp", "1"});
    model.result("pg2").feature("pttraj2").set("interp", new double[]{5.2});
    model.result("pg2").run();
    model.result("pg2").feature("pttraj3").set("data", "dset2");
    model.result("pg2").feature("pttraj3").set("looplevel", new String[]{"interp", "1"});
    model.result("pg2").feature("pttraj3").set("interp", new double[]{5.2});
    model.result("pg2").run();
    model.result("pg2").feature("pttraj4").set("data", "dset2");
    model.result("pg2").feature("pttraj4").set("looplevel", new String[]{"interp", "1"});
    model.result("pg2").feature("pttraj4").set("interp", new double[]{5.2});
    model.result("pg2").run();
    model.result("pg2").feature().duplicate("surf2", "surf1");
    model.result("pg2").feature().duplicate("pttraj5", "pttraj1");
    model.result("pg2").feature().duplicate("pttraj6", "pttraj2");
    model.result("pg2").feature().duplicate("pttraj7", "pttraj3");
    model.result("pg2").feature().duplicate("pttraj8", "pttraj4");
    model.result("pg2").run();
    model.result("pg2").feature().duplicate("surf3", "surf2");
    model.result("pg2").feature().duplicate("pttraj9", "pttraj5");
    model.result("pg2").feature().duplicate("pttraj10", "pttraj6");
    model.result("pg2").feature().duplicate("pttraj11", "pttraj7");
    model.result("pg2").feature().duplicate("pttraj12", "pttraj8");
    model.result("pg2").run();
    model.result("pg2").feature().duplicate("surf4", "surf3");
    model.result("pg2").feature().duplicate("pttraj13", "pttraj9");
    model.result("pg2").feature().duplicate("pttraj14", "pttraj10");
    model.result("pg2").feature().duplicate("pttraj15", "pttraj11");
    model.result("pg2").feature().duplicate("pttraj16", "pttraj12");
    model.result("pg2").run();
    model.result("pg2").run();
    model.result("pg2").feature("surf2").set("looplevel", new String[]{"interp", "4"});
    model.result("pg2").run();
    model.result("pg2").feature("pttraj5").set("looplevel", new String[]{"interp", "4"});
    model.result("pg2").run();
    model.result("pg2").feature("pttraj6").set("looplevel", new String[]{"interp", "4"});
    model.result("pg2").run();
    model.result("pg2").feature("pttraj7").set("looplevel", new String[]{"interp", "4"});
    model.result("pg2").run();
    model.result("pg2").feature("pttraj8").set("looplevel", new String[]{"interp", "4"});
    model.result("pg2").run();
    model.result("pg2").feature("surf3").set("looplevel", new String[]{"interp", "5"});
    model.result("pg2").run();
    model.result("pg2").feature("pttraj9").set("looplevel", new String[]{"interp", "5"});
    model.result("pg2").run();
    model.result("pg2").feature("pttraj10").set("looplevel", new String[]{"interp", "5"});
    model.result("pg2").run();
    model.result("pg2").feature("pttraj11").set("looplevel", new String[]{"interp", "5"});
    model.result("pg2").run();
    model.result("pg2").feature("pttraj12").set("looplevel", new String[]{"interp", "5"});
    model.result("pg2").run();
    model.result("pg2").feature("surf4").set("looplevel", new String[]{"interp", "6"});
    model.result("pg2").run();
    model.result("pg2").feature("pttraj13").set("looplevel", new String[]{"interp", "6"});
    model.result("pg2").run();
    model.result("pg2").feature("pttraj14").set("looplevel", new String[]{"interp", "6"});
    model.result("pg2").run();
    model.result("pg2").feature("pttraj15").set("looplevel", new String[]{"interp", "6"});
    model.result("pg2").run();
    model.result("pg2").feature("pttraj16").set("looplevel", new String[]{"interp", "6"});
    model.result("pg2").run();
    model.result("pg2").feature("surf2").create("trn1", "Transformation");
    model.result("pg2").run();
    model.result("pg2").feature("surf2").feature("trn1").set("move", new int[]{0, -5});
    model.result("pg2").run();
    model.result("pg2").run();
    model.result("pg2").feature("surf3").feature().copy("trn1", "pg2/surf2/trn1");
    model.result("pg2").run();
    model.result("pg2").run();
    model.result("pg2").run();
    model.result("pg2").feature("surf4").feature().copy("trn1", "pg2/surf2/trn1");
    model.result("pg2").run();
    model.result("pg2").run();
    model.result("pg2").run();
    model.result("pg2").feature("pttraj5").feature().copy("trn1", "pg2/surf2/trn1");
    model.result("pg2").run();
    model.result("pg2").run();
    model.result("pg2").run();
    model.result("pg2").feature("pttraj6").feature().copy("trn1", "pg2/surf2/trn1");
    model.result("pg2").run();
    model.result("pg2").run();
    model.result("pg2").run();
    model.result("pg2").feature("pttraj7").feature().copy("trn1", "pg2/surf2/trn1");
    model.result("pg2").run();
    model.result("pg2").run();
    model.result("pg2").run();
    model.result("pg2").feature("pttraj8").feature().copy("trn1", "pg2/surf2/trn1");
    model.result("pg2").run();
    model.result("pg2").run();
    model.result("pg2").run();
    model.result("pg2").feature("pttraj9").feature().copy("trn1", "pg2/surf2/trn1");
    model.result("pg2").run();
    model.result("pg2").run();
    model.result("pg2").run();
    model.result("pg2").feature("pttraj10").feature().copy("trn1", "pg2/surf2/trn1");
    model.result("pg2").run();
    model.result("pg2").run();
    model.result("pg2").run();
    model.result("pg2").feature("pttraj11").feature().copy("trn1", "pg2/surf2/trn1");
    model.result("pg2").run();
    model.result("pg2").run();
    model.result("pg2").run();
    model.result("pg2").feature("pttraj12").feature().copy("trn1", "pg2/surf2/trn1");
    model.result("pg2").run();
    model.result("pg2").run();
    model.result("pg2").run();
    model.result("pg2").feature("pttraj13").feature().copy("trn1", "pg2/surf2/trn1");
    model.result("pg2").run();
    model.result("pg2").run();
    model.result("pg2").run();
    model.result("pg2").feature("pttraj14").feature().copy("trn1", "pg2/surf2/trn1");
    model.result("pg2").run();
    model.result("pg2").run();
    model.result("pg2").run();
    model.result("pg2").feature("pttraj15").feature().copy("trn1", "pg2/surf2/trn1");
    model.result("pg2").run();
    model.result("pg2").run();
    model.result("pg2").run();
    model.result("pg2").feature("pttraj16").feature().copy("trn1", "pg2/surf2/trn1");
    model.result("pg2").run();
    model.result("pg2").run();
    model.result("pg2").feature("surf3").feature("trn1").set("move", new int[]{0, -10});
    model.result("pg2").run();
    model.result("pg2").feature("pttraj9").feature("trn1").set("move", new int[]{0, -10});
    model.result("pg2").run();
    model.result("pg2").feature("pttraj10").feature("trn1").set("move", new int[]{0, -10});
    model.result("pg2").run();
    model.result("pg2").feature("pttraj11").feature("trn1").set("move", new int[]{0, -10});
    model.result("pg2").run();
    model.result("pg2").feature("pttraj12").feature("trn1").set("move", new int[]{0, -10});
    model.result("pg2").run();
    model.result("pg2").feature("surf4").feature("trn1").set("move", new int[]{0, -15});
    model.result("pg2").run();
    model.result("pg2").feature("pttraj13").feature("trn1").set("move", new int[]{0, -15});
    model.result("pg2").run();
    model.result("pg2").feature("pttraj14").feature("trn1").set("move", new int[]{0, -15});
    model.result("pg2").run();
    model.result("pg2").feature("pttraj15").feature("trn1").set("move", new int[]{0, -15});
    model.result("pg2").run();
    model.result("pg2").feature("pttraj16").feature("trn1").set("move", new int[]{0, -15});
    model.result("pg2").run();
    model.result("pg2").create("ann1", "Annotation");
    model.result("pg2").feature("ann1").set("text", "v0 = 0.1 (m/s)");
    model.result("pg2").feature("ann1").set("showpoint", false);
    model.result("pg2").feature("ann1").set("posxexpr", 10);
    model.result("pg2").feature("ann1").set("posyexpr", -1.2);
    model.result("pg2").feature().duplicate("ann2", "ann1");
    model.result("pg2").run();
    model.result("pg2").feature().duplicate("ann3", "ann2");
    model.result("pg2").run();
    model.result("pg2").feature().duplicate("ann4", "ann3");
    model.result("pg2").run();
    model.result("pg2").run();
    model.result("pg2").feature("ann2").set("text", "v0 = 2.8 (m/s)");
    model.result("pg2").feature("ann2").set("posyexpr", -6.2);
    model.result("pg2").run();
    model.result("pg2").feature("ann3").set("text", "v0 = 3.1 (m/s)");
    model.result("pg2").feature("ann3").set("posyexpr", -11.2);
    model.result("pg2").run();
    model.result("pg2").feature("ann4").set("text", "v0 = 3.5 (m/s)");
    model.result("pg2").feature("ann4").set("posyexpr", -16.2);
    model.result("pg2").run();
    model.result("pg2").run();
    model.result("pg2").run();
    model.result("pg2").feature().remove("surf2");
    model.result("pg2").feature().remove("pttraj5");
    model.result("pg2").feature().remove("pttraj6");
    model.result("pg2").feature().remove("pttraj7");
    model.result("pg2").feature().remove("pttraj8");
    model.result("pg2").feature().remove("surf3");
    model.result("pg2").feature().remove("pttraj9");
    model.result("pg2").feature().remove("pttraj10");
    model.result("pg2").feature().remove("pttraj11");
    model.result("pg2").feature().remove("pttraj12");
    model.result("pg2").feature().remove("surf4");
    model.result("pg2").feature().remove("pttraj13");
    model.result("pg2").feature().remove("pttraj14");
    model.result("pg2").feature().remove("pttraj15");
    model.result("pg2").feature().remove("pttraj16");
    model.result("pg2").feature().remove("ann1");
    model.result("pg2").feature().remove("ann2");
    model.result("pg2").feature().remove("ann3");
    model.result("pg2").feature().remove("ann4");
    model.result("pg2").run();
    model.result("pg2").run();
    model.result("pg2").feature("surf1").set("data", "parent");
    model.result("pg2").run();
    model.result("pg2").feature("pttraj1").set("data", "parent");
    model.result("pg2").run();
    model.result("pg2").feature("pttraj2").set("data", "parent");
    model.result("pg2").run();
    model.result("pg2").feature("pttraj3").set("data", "parent");
    model.result("pg2").run();
    model.result("pg2").feature("pttraj4").set("data", "parent");
    model.result("pg2").run();
    model.result("pg2").run();
    model.result("pg2").set("looplevel", new int[]{2429, 5});
    model.result("pg2").run();
    model.result().dataset().create("extr1", "Extrude2D");
    model.result().dataset("extr1").set("data", "dset2");
    model.result().dataset("extr1").set("planemap", "xz");
    model.result().create("pg3", "PlotGroup3D");
    model.result("pg3").run();
    model.result("pg3").label("\u901f\u5ea6\uff08\u4e09\u7ef4\uff09");
    model.result("pg3").set("looplevel", new String[]{"last", "5"});
    model.result("pg3").set("frametype", "spatial");
    model.result("pg3").set("showlegends", false);
    model.result("pg3").create("vol1", "Volume");
    model.result("pg3").feature("vol1").set("expr", "mbd.vel");
    model.result("pg3").feature("vol1").set("colortable", "SpectrumLight");
    model.result("pg3").feature("vol1").create("def1", "Deform");
    model.result("pg3").run();
    model.result("pg3").feature("vol1").feature("def1").set("expr", new String[]{"u", "0", "v"});
    model.result("pg3").feature("vol1").feature("def1").set("scaleactive", true);
    model.result("pg3").feature("vol1").feature("def1").set("scale", 1);
    model.result("pg3").run();
    model.result("pg3").create("pttraj1", "PointTrajectories");
    model.result("pg3").feature("pttraj1").set("plotdata", "global");
    model.result("pg3").feature("pttraj1").set("expr", new String[]{"aveop1(x)", "0", "aveop1(y)"});
    model.result("pg3").feature("pttraj1").set("linetype", "tube");
    model.result("pg3").feature("pttraj1").create("col1", "Color");
    model.result("pg3").run();
    model.result("pg3").feature("pttraj1").feature("col1").set("expr", "aveop2(y)>1e-3");
    model.result("pg3").feature("pttraj1").feature("col1").set("colortable", "TrafficLight");
    model.result("pg3").run();
    model.result("pg3").run();
    model.result().create("pg4", "PlotGroup1D");
    model.result("pg4").run();
    model.result("pg4").label("\u901f\u5ea6 vs. \u8f6c\u52a8\u89d2\u5ea6");
    model.result("pg4").set("data", "dset2");
    model.result("pg4").set("titletype", "none");
    model.result("pg4").setIndex("looplevelinput", "manual", 1);
    model.result("pg4").setIndex("looplevel", new int[]{1, 3}, 1);
    model.result("pg4").set("xlabelactive", true);
    model.result("pg4").set("xlabel", "\u8f6c\u52a8\u89d2\u5ea6 (\u00b0)");
    model.result("pg4").set("ylabelactive", true);
    model.result("pg4").set("ylabel", "\u901f\u5ea6 (m/s)");
    model.result("pg4").set("axislimits", true);
    model.result("pg4").set("xmin", 0);
    model.result("pg4").set("xmax", 1080);
    model.result("pg4").set("ymin", -0.1);
    model.result("pg4").set("ymax", 14);
    model.result("pg4").set("manualgrid", true);
    model.result("pg4").set("xspacing", 180);
    model.result("pg4").create("glob1", "Global");
    model.result("pg4").feature("glob1").set("markerpos", "datapoints");
    model.result("pg4").feature("glob1").set("linewidth", "preference");
    model.result("pg4").feature("glob1").setIndex("expr", "aveop2(mbd.u_tX)", 0);
    model.result("pg4").feature("glob1").setIndex("descr", "\u5e73\u79fb\u901f\u5ea6", 0);
    model.result("pg4").feature("glob1").setIndex("expr", "-mbd.rd2.th_tz*Rc", 1);
    model.result("pg4").feature("glob1").setIndex("descr", "\u89d2\u901f\u5ea6\uff08\u5f52\u4e00\u5316\uff09", 1);
    model.result("pg4").feature("glob1").set("xdatasolnumtype", "inner");
    model.result("pg4").feature("glob1").set("xdata", "expr");
    model.result("pg4").feature("glob1").set("xdataexpr", "-mbd.rd2.thz");
    model.result("pg4").feature("glob1").set("xdataunit", "\u00b0");
    model.result("pg4").feature("glob1").set("linestyle", "cycle");
    model.result("pg4").feature("glob1").set("linewidth", 4);
    model.result("pg4").run();
    model.result("pg4").run();
    model.result().duplicate("pg5", "pg4");
    model.result("pg5").run();
    model.result("pg5").label("\u901f\u5ea6 vs. \u65f6\u95f4");
    model.result("pg5").set("xlabel", "\u65f6\u95f4 (s)");
    model.result("pg5").setIndex("looplevel", new int[]{5}, 1);
    model.result("pg5").set("axislimits", false);
    model.result("pg5").set("manualgrid", false);
    model.result("pg5").run();
    model.result("pg5").feature("glob1").set("xdata", "solution");
    model.result("pg5").run();
    model.result("pg4").run();
    model.result().duplicate("pg6", "pg4");
    model.result("pg6").run();
    model.result("pg6").label("\u80fd\u91cf vs. \u8f6c\u52a8\u89d2\u5ea6");
    model.result("pg6").setIndex("looplevel", new int[]{1}, 1);
    model.result("pg6").set("ylabel", "\u80fd\u91cf (J)");
    model.result("pg6").set("yspacing", 5);
    model.result("pg6").set("ymin", -16);
    model.result("pg6").set("ymax", 30);

    return model;
  }

  public static Model run2(Model model) {
    model.result("pg6").run();
    model.result("pg6").feature("glob1").setIndex("expr", "mbd.Wk_tot", 0);
    model.result("pg6").feature("glob1").setIndex("descr", "\u603b\u52a8\u80fd", 0);
    model.result("pg6").feature("glob1").setIndex("expr", "Wg", 1);
    model.result("pg6").feature("glob1").setIndex("descr", "\u5f53\u524d\u52bf\u80fd", 1);
    model.result("pg6").feature("glob1").setIndex("expr", "mbd.Wk_tot+Wg", 2);
    model.result("pg6").feature("glob1").setIndex("descr", "\u603b\u80fd\u91cf", 2);
    model.result("pg6").feature("glob1")
         .set("expr", new String[]{"mbd.Wk_tot", "Wg", "mbd.Wk_tot+Wg", "mbd.rbc1.Wf"});
    model.result("pg6").feature("glob1")
         .set("descr", new String[]{"\u603b\u52a8\u80fd", "\u5f53\u524d\u52bf\u80fd", "\u603b\u80fd\u91cf", "\u6469\u64e6\u80fd\u8017"});
    model.result("pg6").feature("glob1").set("linestyle", "solid");
    model.result("pg6").run();
    model.result("pg6").run();
    model.result().duplicate("pg7", "pg6");
    model.result("pg7").run();
    model.result("pg7").label("\u80fd\u91cf vs. \u65f6\u95f4");
    model.result("pg7").setIndex("looplevel", new int[]{5}, 1);
    model.result("pg7").set("xlabel", "\u65f6\u95f4 (s)");
    model.result("pg7").set("axislimits", false);
    model.result("pg7").set("manualgrid", false);
    model.result("pg7").run();
    model.result("pg7").feature("glob1").set("xdata", "solution");
    model.result("pg7").run();
    model.result("pg4").run();
    model.result().duplicate("pg8", "pg4");
    model.result("pg8").run();
    model.result("pg8").label("\u63a5\u89e6\u529b");
    model.result("pg8").set("ylabel", "\u529b (N)");
    model.result("pg8").set("yspacing", 10);
    model.result("pg8").set("ymax", 115);
    model.result("pg8").set("ymin", -12);
    model.result("pg8").run();
    model.result("pg8").feature("glob1").set("expr", new String[]{});
    model.result("pg8").feature("glob1").set("descr", new String[]{});
    model.result("pg8").feature("glob1").setIndex("expr", "-mbd.rbc1.Fny", 0);
    model.result("pg8").feature("glob1").setIndex("descr", "\u63a5\u89e6\u529b\uff0c\u5782\u76f4", 0);
    model.result("pg8").feature("glob1").setIndex("expr", "mbd.rbc1.Ffx", 1);
    model.result("pg8").feature("glob1").setIndex("descr", "\u6469\u64e6\u529b\uff0c\u6c34\u5e73", 1);
    model.result("pg8").run();
    model.result("pg8").run();
    model.result().duplicate("pg9", "pg8");
    model.result("pg9").run();
    model.result("pg9").set("titletype", "label");
    model.result("pg9").label("\u6469\u64e6\u5229\u7528\u56e0\u5b50");
    model.result("pg9").set("ylabelactive", false);
    model.result("pg9").set("yspacing", 0.2);
    model.result("pg9").set("ymax", 1.6);
    model.result("pg9").set("ymin", -1.1);
    model.result("pg9").run();
    model.result("pg9").feature("glob1").set("expr", new String[]{});
    model.result("pg9").feature("glob1").set("descr", new String[]{});
    model.result("pg9").feature("glob1").setIndex("expr", "mbd.rbc1.Ffx/(mbd.rbc1.Fny+0.001)/mbd.rbc1.fric1.mu", 0);
    model.result("pg9").run();
    model.result("pg4").run();
    model.result("pg4").setIndex("looplevel", new int[]{4}, 1);
    model.result("pg4").set("xmax", 1740);
    model.result("pg4").set("ymax", 13);
    model.result("pg4").set("ymin", 2);
    model.result("pg4").run();
    model.result("pg6").run();
    model.result("pg6").setIndex("looplevel", new int[]{4}, 1);
    model.result("pg6").set("xmax", 1740);
    model.result("pg6").set("ymax", 47);
    model.result("pg6").run();
    model.result("pg8").run();
    model.result("pg8").setIndex("looplevel", new int[]{4}, 1);
    model.result("pg8").set("ymax", 118);
    model.result("pg8").set("ymin", -15);
    model.result("pg8").set("xmax", 1740);
    model.result("pg8").run();
    model.result("pg9").run();
    model.result("pg9").setIndex("looplevel", new int[]{4}, 1);
    model.result("pg9").set("xmax", 1740);
    model.result("pg9").run();
    model.result("pg4").run();
    model.result("pg4").setIndex("looplevel", new int[]{5}, 1);
    model.result("pg4").set("xmax", 1440);
    model.result("pg4").set("ymin", 1);
    model.result("pg4").run();
    model.result("pg6").run();
    model.result("pg6").setIndex("looplevel", new int[]{5}, 1);
    model.result("pg6").set("xmax", 1440);
    model.result("pg6").set("ymax", 46);
    model.result("pg6").run();
    model.result("pg8").run();
    model.result("pg8").setIndex("looplevel", new int[]{5}, 1);
    model.result("pg8").set("xmax", 1440);
    model.result("pg8").set("ymax", 105);
    model.result("pg8").run();
    model.result("pg9").run();
    model.result("pg9").setIndex("looplevel", new int[]{5}, 1);
    model.result("pg9").set("xmax", 1440);
    model.result("pg9").run();
    model.result("pg2").run();

    model.nodeGroup().create("grp1", "Results");
    model.nodeGroup("grp1").set("type", "plotgroup");
    model.nodeGroup("grp1").placeAfter("plotgroup", "pg1");
    model.nodeGroup("grp1").add("plotgroup", "pg2");
    model.nodeGroup("grp1").add("plotgroup", "pg3");
    model.nodeGroup("grp1").add("plotgroup", "pg4");
    model.nodeGroup("grp1").add("plotgroup", "pg5");
    model.nodeGroup("grp1").label("\u901f\u5ea6");

    model.result("pg6").run();

    model.nodeGroup().create("grp2", "Results");
    model.nodeGroup("grp2").set("type", "plotgroup");
    model.nodeGroup("grp2").placeAfter("plotgroup", "pg1");
    model.nodeGroup().move("grp2", 1);
    model.nodeGroup("grp2").add("plotgroup", "pg6");
    model.nodeGroup("grp2").add("plotgroup", "pg7");
    model.nodeGroup("grp2").label("\u80fd\u91cf");

    model.result("pg8").run();

    model.nodeGroup().create("grp3", "Results");
    model.nodeGroup("grp3").set("type", "plotgroup");
    model.nodeGroup("grp3").placeAfter("plotgroup", "pg1");
    model.nodeGroup().move("grp3", 2);
    model.nodeGroup("grp3").add("plotgroup", "pg8");
    model.nodeGroup("grp3").add("plotgroup", "pg9");
    model.nodeGroup("grp3").label("\u63a5\u89e6\u529b");

    model.result().export().create("anim1", "Animation");
    model.result().export("anim1").set("target", "player");
    model.result().export("anim1").set("fontsize", "9");
    model.result().export("anim1").set("colortheme", "globaltheme");
    model.result().export("anim1").set("customcolor", new double[]{1, 1, 1});
    model.result().export("anim1").set("background", "color");
    model.result().export("anim1").set("gltfincludelines", "on");
    model.result().export("anim1").set("title1d", "on");
    model.result().export("anim1").set("legend1d", "on");
    model.result().export("anim1").set("logo1d", "on");
    model.result().export("anim1").set("options1d", "on");
    model.result().export("anim1").set("title2d", "on");
    model.result().export("anim1").set("legend2d", "on");
    model.result().export("anim1").set("logo2d", "on");
    model.result().export("anim1").set("options2d", "off");
    model.result().export("anim1").set("title3d", "on");
    model.result().export("anim1").set("legend3d", "on");
    model.result().export("anim1").set("logo3d", "on");
    model.result().export("anim1").set("options3d", "off");
    model.result().export("anim1").set("axisorientation", "on");
    model.result().export("anim1").set("grid", "on");
    model.result().export("anim1").set("axes1d", "on");
    model.result().export("anim1").set("axes2d", "on");
    model.result().export("anim1").set("showgrid", "on");
    model.result().export("anim1").showFrame();
    model.result().export("anim1").label("\u901f\u5ea6");
    model.result().export("anim1").set("plotgroup", "pg2");
    model.result().export("anim1").setIndex("singlelooplevel", 5, 1);
    model.result().export("anim1").set("maxframes", 100);
    model.result().export().duplicate("anim2", "anim1");
    model.result().export("anim2").showFrame();
    model.result().export("anim2").label("\u901f\u5ea6\uff08\u4e09\u7ef4\uff09");
    model.result().export("anim2").set("plotgroup", "pg3");
    model.result("pg2").run();
    model.result("pg2").set("looplevel", new int[]{2258, 5});
    model.result("pg2").set("view", "auto");
    model.result("pg2").run();
    model.result("pg4").run();
    model.result("pg4").set("axislimits", false);
    model.result("pg6").run();
    model.result("pg6").set("axislimits", false);
    model.result("pg8").run();
    model.result("pg8").set("axislimits", false);
    model.result("pg9").run();
    model.result("pg9").set("axislimits", false);
    model.result("pg3").run();

    model.view("view3").set("showgrid", true);

    model.result("pg3").run();

    model.title("\u8df3\u73af\u7684\u52a8\u529b\u5b66");

    model
         .description("\u672c\u4f8b\u6a21\u62df\u8df3\u73af\u7684\u52a8\u529b\u5b66\uff1a\u5468\u957f\u4e0a\u5177\u6709\u4e00\u4e2a\u70b9\u8d28\u91cf\u7684\u6eda\u52a8\u73af\u5728\u7279\u5b9a\u6761\u4ef6\u4e0b\u53ef\u4ee5\u4ece\u5176\u6eda\u52a8\u7684\u8868\u9762\u4e0a\u8df3\u8d77\u3002");

    model.label("hopping_hoop.mph");

    return model;
  }

  public static void main(String[] args) {
    Model model = run();
    run2(model);
  }

}
