/*
 * evans_droplet.java
 */

import com.comsol.model.*;
import com.comsol.model.util.*;

/** Model exported on Apr 30 2026, 09:40 by COMSOL 6.3.0.290. */
public class evans_droplet {

  public static Model run() {
    Model model = ModelUtil.create("Model");

    model
         .modelPath("D:\\Program Files\\COMSOL\\COMSOL63\\Multiphysics\\applications\\Corrosion_Module\\Atmospheric_Corrosion");

    model.component().create("comp1", true);

    model.component("comp1").geom().create("geom1", 2);
    model.component("comp1").geom("geom1").axisymmetric(true);

    model.component("comp1").mesh().create("mesh1");

    model.component("comp1").physics().create("tcd", "TertiaryCurrentDistributionNernstPlanck", "geom1");
    model.component("comp1").physics("tcd").prop("SpeciesProperties").set("ChargeTransportModel", "WaterBased");
    model.component("comp1").physics("tcd").field("concentration").field("cFe");
    model.component("comp1").physics("tcd").field("concentration")
         .component(new String[]{"cFe", "cFeOH", "cFeCO3", "cO2", "cCO2", "cH2CO3", "cHCO3", "cCO3", "cNa", "cCl"});

    model.study().create("std1");
    model.study("std1").create("cdi", "CurrentDistributionInitialization");
    model.study("std1").feature("cdi").set("ftplistmethod", "manual");
    model.study("std1").feature("cdi").set("solnum", "auto");
    model.study("std1").feature("cdi").set("notsolnum", "auto");
    model.study("std1").feature("cdi").set("outputmap", new String[]{});
    model.study("std1").feature("cdi").set("ngenAUX", "1");
    model.study("std1").feature("cdi").set("goalngenAUX", "1");
    model.study("std1").feature("cdi").set("ngenAUX", "1");
    model.study("std1").feature("cdi").set("goalngenAUX", "1");
    model.study("std1").feature("cdi").setSolveFor("/physics/tcd", true);
    model.study("std1").create("time", "Transient");
    model.study("std1").feature("time").set("ftplistmethod", "manual");
    model.study("std1").feature("time").set("initialtime", "0");
    model.study("std1").feature("time").set("solnum", "auto");
    model.study("std1").feature("time").set("notsolnum", "auto");
    model.study("std1").feature("time").set("outputmap", new String[]{});
    model.study("std1").feature("time").setSolveFor("/physics/tcd", true);

//    To import content from file, use:
//    model.param().loadFile("FILENAME");
    model.param().set("a", "0.0071550[m]", "\u6db2\u6ef4\u534a\u5f84");
    model.param().set("b", "0.0037306[m]", "\u6db2\u6ef4\u9ad8\u5ea6");
    model.param().set("c_unit", "1000[mol/m^3]", "\u5355\u4f4d\u6d3b\u6027\u6d53\u5ea6");
    model.param().set("cCO20", "KCO2*PCO2*1e3*0.7[mol/m^3]", "\u521d\u59cb\u6d53\u5ea6\uff0cCO2");
    model.param().set("cH2CO30", "KCO2H*cCO20", "\u521d\u59cb\u6d53\u5ea6\uff0cH2CO3");
    model.param().set("cHCO30", "sqrt(KH2CO3*c_unit*cH2CO30)", "\u521d\u59cb\u6d53\u5ea6\uff0cHCO3");
    model.param().set("cNaCl0", "0.5[M]", "\u521d\u59cb\u6d53\u5ea6\uff0cNaCl");
    model.param().set("cO2_sol", "1.22[mM]", "\u6c27\u6eb6\u89e3\u5ea6");
    model.param().set("cO20", "cO2s", "\u521d\u59cb\u6c27\u6d53\u5ea6");
    model.param().set("cO2s", "cO2_sol*0.21*0.7", "\u6db2\u6ef4\u8868\u9762\u7684\u6c27\u6d53\u5ea6");
    model.param()
         .set("ctot_mdis", "1e-5[mol/m^2]", "\u91d1\u5c5e\u6eb6\u89e3\u7684\u5355\u4f4d\u8868\u9762\u79ef\u6469\u5c14\u53ef\u7528\u603b\u91cf");
    model.param().set("DCl", "2.03e-9[m^2/s]", "\u6269\u6563\u7cfb\u6570\uff0cCl");
    model.param().set("DCO2", "1.96e-9[m^2/s]", "\u6269\u6563\u7cfb\u6570\uff0cCO2");
    model.param().set("DCO3", "0.92e-9[m^2/s]", "\u6269\u6563\u7cfb\u6570\uff0cCO3");
    model.param().set("DFe", "0.72e-9[m^2/s]", "\u6269\u6563\u7cfb\u6570\uff0cFe2");
    model.param().set("DH", "9.312e-9[m^2/s]", "\u6269\u6563\u7cfb\u6570\uff0cH");
    model.param().set("DH2CO3", "2e-9[m^2/s]", "\u6269\u6563\u7cfb\u6570\uff0cH2CO3");
    model.param().set("DHCO3", "1.105e-9[m^2/s]", "\u6269\u6563\u7cfb\u6570\uff0cHCO3");
    model.param().set("DNa", "1.33e-9[m^2/s]", "\u6269\u6563\u7cfb\u6570\uff0cNa");
    model.param().set("DO2", "1.96e-9[m^2/s]", "\u6269\u6563\u7cfb\u6570\uff0cO2");
    model.param().set("DOH", "5.26e-9[m^2/s]", "\u6269\u6563\u7cfb\u6570\uff0cOH");
    model.param()
         .set("Eeq_ref_Fe", "-0.47[V]", "\u94c1\u6eb6\u89e3\u53cd\u5e94\u7684\u53c2\u8003\u5e73\u8861\u7535\u4f4d");
    model.param()
         .set("Eeq_ref_O2", "0.401[V]", "\u6c27\u8fd8\u539f\u53cd\u5e94\u7684\u53c2\u8003\u5e73\u8861\u7535\u4f4d");
    model.param()
         .set("i0_ref_Fe", "1[A/m^2]", "\u94c1\u6eb6\u89e3\u53cd\u5e94\u7684\u53c2\u8003\u4ea4\u6362\u7535\u6d41\u5bc6\u5ea6");
    model.param()
         .set("i0_ref_O2", "1e-7[A/m^2]", "\u6c27\u8fd8\u539f\u53cd\u5e94\u7684\u53c2\u8003\u4ea4\u6362\u7535\u6d41\u5bc6\u5ea6");
    model.param()
         .set("alphaa_Fe", "1.5", "\u94c1\u6eb6\u89e3\u53cd\u5e94\u7684\u9633\u6781\u4f20\u9012\u7cfb\u6570");
    model.param()
         .set("alphaa_O2", "3.5", "\u6c27\u8fd8\u539f\u53cd\u5e94\u7684\u9633\u6781\u4f20\u9012\u7cfb\u6570");
    model.param()
         .set("KCO2", "0.0454*(1.6616-5.736e-2*(T[1/K]-273)+1.031e-3*(T[1/K]-273)^2-9.68e-6*(T[1/K]-273)^3+4.471e-8*(T[1/K]-273)^4-7.912e-11*(T[1/K]-273)^5)", "\u4ea8\u5229\u5e38\u6570");
    model.param().set("KCO2H", "2.58e-3", "CO2 \u6c34\u5408\u5e73\u8861\u5e38\u6570");
    model.param()
         .set("KFeCO3", "10^-6.57", "\u6c34\u6eb6\u6db2\u4e2d FeCO3 \u7684\u89e3\u79bb\u5e73\u8861\u5e38\u6570");
    model.param().set("KFeOH", "10^-9.5", "FeOH \u751f\u6210\u5e73\u8861\u5e38\u6570");
    model.param().set("kfFeCO3", "1[mol/m^3/s]", "FeCO3 \u6c89\u6dc0\u7684\u53cd\u5e94\u901f\u7387\u5e38\u6570");
    model.param().set("kfFeOH2", "1e6[mol/m^3/s]", "FeOH2 \u6c89\u6dc0\u7684\u53cd\u5e94\u901f\u7387\u5e38\u6570");
    model.param()
         .set("KH2CO3", "387.6*10^(-(6.41-1.594e-3*TF+8.52e-6*(TF)^2))", "H2CO3 \u6eb6\u89e3\u7684\u5e73\u8861\u5e38\u6570");
    model.param()
         .set("KHCO3", "10^(-(10.61-4.97e-3*TF+1.331e-5*(TF)^2))", "HCO3 \u6eb6\u89e3\u7684\u5e73\u8861\u5e38\u6570");
    model.param().set("KspFeCO3", "10^-10.7/KFeCO3", "\u5e73\u8861\u5e38\u6570\uff0cFeCO3 \u6eb6\u89e3");
    model.param().set("KspFeOH2", "8e-16", "\u5e73\u8861\u5e38\u6570\uff0cFeOH2 \u6eb6\u89e3");
    model.param().set("M_FeCO3", "115.854[g/mol]", "\u5206\u5b50\u91cf\uff0cFeCO3");
    model.param().set("M_FeOH2", "89.86[g/mol]", "\u5206\u5b50\u91cf\uff0cFeOH2");
    model.param().set("PCO2", "400[ppm]", "CO2 \u5206\u538b\uff0cbar");
    model.param().set("phil0", "0.5[V]", "\u521d\u59cb\u7535\u89e3\u8d28\u7535\u4f4d");
    model.param().set("rho_FeCO3", "4.03[g/cm^3]", "\u5bc6\u5ea6\uff0cFeCO3");
    model.param().set("rho_FeOH2", "3.4[g/cm^3]", "\u5bc6\u5ea6\uff0cFeOH2");
    model.param().set("T", "298 [K]", "\u6e29\u5ea6");
    model.param().set("TF", "(T-0[degC])/1[K]*1.8+32", "\u5de5\u4f5c\u6e29\u5ea6\uff0c\u534e\u6c0f\u5ea6");
    model.param().set("zCl", "-1", "\u7535\u8377\u6570\uff0cCO3");
    model.param().set("zCO3", "-2", "\u7535\u8377\u6570\uff0cCO3");
    model.param().set("zFe", "2", "\u7535\u8377\u6570\uff0cFe");
    model.param().set("zFeOH", "1", "\u7535\u8377\u6570\uff0cFeOH");
    model.param().set("zHCO3", "-1", "\u7535\u8377\u6570\uff0cHCO3");
    model.param().set("zNa", "1", "\u7535\u8377\u6570\uff0cNa");

    model.component("comp1").geom("geom1").create("e1", "Ellipse");
    model.component("comp1").geom("geom1").feature("e1").set("semiaxes", new String[]{"a", "b"});
    model.component("comp1").geom("geom1").feature("e1").set("angle", 90);
    model.component("comp1").geom("geom1").runPre("fin");

    model.component("comp1").variable().create("var1");

    model.component("comp1").geom("geom1").run();

//    To import content from file, use:
//    model.component("comp1").variable("var1").loadFile("FILENAME");
    model.component("comp1").variable("var1")
         .set("rFeCO3", "kfFeCO3*b*max(cFeCO3[M^-1]-KspFeCO3,0)", "FeCO3 \u6c89\u6dc0\u7684\u53cd\u5e94\u901f\u7387");
    model.component("comp1").variable("var1")
         .set("rFeOH2", "kfFeOH2*b*max(cFe*tcd.cOH^2[M^-3]-KspFeOH2,0)", "FeOH2 \u6c89\u6dc0\u7684\u53cd\u5e94\u901f\u7387");
    model.component("comp1").variable("var1")
         .set("theta", "1-exp(-tcd.cbtot/ctot_mdis)", "\u8150\u8680\u4ea7\u7269\u8986\u76d6\u5ea6");

    model.component("comp1").physics("tcd").prop("SpeciesActivity").set("SpeciesActivity", "DebyeHuckel");
    model.component("comp1").physics("tcd").feature("sp1").setIndex("z", "zFe", 0);
    model.component("comp1").physics("tcd").feature("sp1").setIndex("z", "zFeOH", 1);
    model.component("comp1").physics("tcd").feature("sp1").setIndex("z", "zHCO3", 6);
    model.component("comp1").physics("tcd").feature("sp1").setIndex("z", "zCO3", 7);
    model.component("comp1").physics("tcd").feature("sp1").setIndex("z", "zNa", 8);
    model.component("comp1").physics("tcd").feature("sp1").setIndex("z", "zCl", 9);
    model.component("comp1").physics("tcd").feature("ice1")
         .set("D_cFe", new String[]{"DFe", "0", "0", "0", "DFe", "0", "0", "0", "DFe"});
    model.component("comp1").physics("tcd").feature("ice1")
         .set("D_cFeOH", new String[]{"DFe", "0", "0", "0", "DFe", "0", "0", "0", "DFe"});
    model.component("comp1").physics("tcd").feature("ice1")
         .set("D_cFeCO3", new String[]{"DFe", "0", "0", "0", "DFe", "0", "0", "0", "DFe"});
    model.component("comp1").physics("tcd").feature("ice1")
         .set("D_cO2", new String[]{"DO2", "0", "0", "0", "DO2", "0", "0", "0", "DO2"});
    model.component("comp1").physics("tcd").feature("ice1")
         .set("D_cCO2", new String[]{"DCO2", "0", "0", "0", "DCO2", "0", "0", "0", "DCO2"});
    model.component("comp1").physics("tcd").feature("ice1")
         .set("D_cH2CO3", new String[]{"DH2CO3", "0", "0", "0", "DH2CO3", "0", "0", "0", "DH2CO3"});
    model.component("comp1").physics("tcd").feature("ice1")
         .set("D_cHCO3", new String[]{"DHCO3", "0", "0", "0", "DHCO3", "0", "0", "0", "DHCO3"});
    model.component("comp1").physics("tcd").feature("ice1")
         .set("D_cCO3", new String[]{"DCO3", "0", "0", "0", "DCO3", "0", "0", "0", "DCO3"});
    model.component("comp1").physics("tcd").feature("ice1")
         .set("D_cNa", new String[]{"DNa", "0", "0", "0", "DNa", "0", "0", "0", "DNa"});
    model.component("comp1").physics("tcd").feature("ice1")
         .set("D_cCl", new String[]{"DCl", "0", "0", "0", "DCl", "0", "0", "0", "DCl"});
    model.component("comp1").physics("tcd").feature("ice1")
         .set("DH", new String[]{"DH", "0", "0", "0", "DH", "0", "0", "0", "DH"});
    model.component("comp1").physics("tcd").feature("ice1")
         .set("DOH", new String[]{"DOH", "0", "0", "0", "DOH", "0", "0", "0", "DOH"});
    model.component("comp1").physics("tcd").feature("init1").setIndex("initc", "cO20", 3);
    model.component("comp1").physics("tcd").feature("init1").setIndex("initc", "cCO20", 4);
    model.component("comp1").physics("tcd").feature("init1").setIndex("initc", "cH2CO30", 5);
    model.component("comp1").physics("tcd").feature("init1").setIndex("initc", "cHCO30", 6);
    model.component("comp1").physics("tcd").feature("init1").setIndex("initc", "cNaCl0", 8);
    model.component("comp1").physics("tcd").feature("init1").setIndex("initc", "cNaCl0", 9);
    model.component("comp1").physics("tcd").feature("init1").set("initphil", "phil0");
    model.component("comp1").physics("tcd").create("es1", "ElectrodeSurface", 1);
    model.component("comp1").physics("tcd").feature("es1").selection().set(2);
    model.component("comp1").physics("tcd").feature("es1").setIndex("Species", "s1", 0, 0);
    model.component("comp1").physics("tcd").feature("es1").setIndex("rhos", 8960, 0, 0);
    model.component("comp1").physics("tcd").feature("es1").setIndex("Ms", 0.06355, 0, 0);
    model.component("comp1").physics("tcd").feature("es1").setIndex("Species", "s1", 0, 0);
    model.component("comp1").physics("tcd").feature("es1").setIndex("rhos", 8960, 0, 0);
    model.component("comp1").physics("tcd").feature("es1").setIndex("Ms", 0.06355, 0, 0);
    model.component("comp1").physics("tcd").feature("es1").setIndex("Species", "FeOH2", 0, 0);
    model.component("comp1").physics("tcd").feature("es1").setIndex("rhos", "rho_FeOH2", 0, 0);
    model.component("comp1").physics("tcd").feature("es1").setIndex("Ms", "M_FeOH2", 0, 0);
    model.component("comp1").physics("tcd").feature("es1").setIndex("Species", "s1", 1, 0);
    model.component("comp1").physics("tcd").feature("es1").setIndex("rhos", 8960, 1, 0);
    model.component("comp1").physics("tcd").feature("es1").setIndex("Ms", 0.06355, 1, 0);
    model.component("comp1").physics("tcd").feature("es1").setIndex("rhos", 8960, 1, 0);
    model.component("comp1").physics("tcd").feature("es1").setIndex("Ms", 0.06355, 1, 0);
    model.component("comp1").physics("tcd").feature("es1").setIndex("Species", "s1", 1, 0);
    model.component("comp1").physics("tcd").feature("es1").setIndex("rhos", 8960, 1, 0);
    model.component("comp1").physics("tcd").feature("es1").setIndex("Ms", 0.06355, 1, 0);
    model.component("comp1").physics("tcd").feature("es1").setIndex("Species", "FeCO3", 1, 0);
    model.component("comp1").physics("tcd").feature("es1").setIndex("rhos", "rho_FeCO3", 1, 0);
    model.component("comp1").physics("tcd").feature("es1").setIndex("Ms", "M_FeCO3", 1, 0);
    model.component("comp1").physics("tcd").feature("es1").feature("er1")
         .label("\u7535\u6781\u53cd\u5e94\uff1a\u94c1\u6eb6\u89e3");
    model.component("comp1").physics("tcd").feature("es1").feature("er1").set("nm", 2);
    model.component("comp1").physics("tcd").feature("es1").feature("er1").setIndex("Vi0", -1, 0);
    model.component("comp1").physics("tcd").feature("es1").feature("er1").set("Eeq_ref", "Eeq_ref_Fe");
    model.component("comp1").physics("tcd").feature("es1").feature("er1").set("i0_ref", "i0_ref_Fe*(1-theta)");
    model.component("comp1").physics("tcd").feature("es1").feature("er1").set("alphaa", "alphaa_Fe");
    model.component("comp1").physics("tcd").feature("es1").create("er2", "ElectrodeReaction", 1);
    model.component("comp1").physics("tcd").feature("es1").feature("er2")
         .label("\u7535\u6781\u53cd\u5e94\uff1a\u6c27\u8fd8\u539f");
    model.component("comp1").physics("tcd").feature("es1").feature("er2").set("nm", 4);
    model.component("comp1").physics("tcd").feature("es1").feature("er2").setIndex("Vi0", -1, 3);
    model.component("comp1").physics("tcd").feature("es1").feature("er2").set("Eeq_ref", "Eeq_ref_O2");
    model.component("comp1").physics("tcd").feature("es1").feature("er2").set("WaterBasedReferenceState", "OH");
    model.component("comp1").physics("tcd").feature("es1").feature("er2").setIndex("cref", "cO2_sol", 3, 0);
    model.component("comp1").physics("tcd").feature("es1").feature("er2").set("i0_ref", "i0_ref_O2*(tcd.eta_er2<0)");
    model.component("comp1").physics("tcd").feature("es1").feature("er2").set("alphaa", "alphaa_O2");
    model.component("comp1").physics("tcd").feature("es1").create("nfr1", "NonFaradaicReactions", 1);
    model.component("comp1").physics("tcd").feature("es1").feature("nfr1")
         .label("\u975e\u6cd5\u62c9\u7b2c\u53cd\u5e94\uff1aFeOH2 \u548c FeCO3 \u6c89\u6dc0");
    model.component("comp1").physics("tcd").feature("es1").feature("nfr1").setIndex("species", true, 0);
    model.component("comp1").physics("tcd").feature("es1").feature("nfr1").setIndex("species", true, 2);
    model.component("comp1").physics("tcd").feature("es1").feature("nfr1").setIndex("J0", "-rFeOH2", 0);
    model.component("comp1").physics("tcd").feature("es1").feature("nfr1").setIndex("J0", "-rFeCO3", 2);
    model.component("comp1").physics("tcd").feature("es1").feature("nfr1").setIndex("R", "rFeOH2", 0, 0);
    model.component("comp1").physics("tcd").feature("es1").feature("nfr1").setIndex("R", "rFeCO3", 1, 0);
    model.component("comp1").physics("tcd").create("conc1", "Concentration", 1);
    model.component("comp1").physics("tcd").feature("conc1").selection().set(3);
    model.component("comp1").physics("tcd").feature("conc1").setIndex("species", true, 3);
    model.component("comp1").physics("tcd").feature("conc1").setIndex("species", true, 4);
    model.component("comp1").physics("tcd").feature("conc1").setIndex("c0", "cO2s", 3);
    model.component("comp1").physics("tcd").feature("conc1").setIndex("c0", "cCO20", 4);
    model.component("comp1").physics("tcd").create("eqreac1", "EquilibriumReaction", 2);
    model.component("comp1").physics("tcd").feature("eqreac1")
         .label("\u5e73\u8861\u53cd\u5e94 - H2CO3 \u751f\u6210");
    model.component("comp1").physics("tcd").feature("eqreac1").selection().all();
    model.component("comp1").physics("tcd").feature("eqreac1").set("Keq0", "KCO2H");
    model.component("comp1").physics("tcd").feature("eqreac1").setIndex("nu", -1, 4);
    model.component("comp1").physics("tcd").feature("eqreac1").setIndex("nu", 1, 5);
    model.component("comp1").physics("tcd").create("eqreac2", "EquilibriumReaction", 2);
    model.component("comp1").physics("tcd").feature("eqreac2").label("\u5e73\u8861\u53cd\u5e94 - HCO3 \u751f\u6210");
    model.component("comp1").physics("tcd").feature("eqreac2").selection().all();
    model.component("comp1").physics("tcd").feature("eqreac2").set("Keq0", "KH2CO3");
    model.component("comp1").physics("tcd").feature("eqreac2").setIndex("nu", -1, 5);
    model.component("comp1").physics("tcd").feature("eqreac2").setIndex("nu", 1, 6);
    model.component("comp1").physics("tcd").feature("eqreac2").set("nuH", 1);
    model.component("comp1").physics("tcd").create("eqreac3", "EquilibriumReaction", 2);
    model.component("comp1").physics("tcd").feature("eqreac3").label("\u5e73\u8861\u53cd\u5e94 - CO3 \u751f\u6210");
    model.component("comp1").physics("tcd").feature("eqreac3").selection().all();
    model.component("comp1").physics("tcd").feature("eqreac3").set("Keq0", "KHCO3");
    model.component("comp1").physics("tcd").feature("eqreac3").setIndex("nu", -1, 6);
    model.component("comp1").physics("tcd").feature("eqreac3").setIndex("nu", 1, 7);
    model.component("comp1").physics("tcd").feature("eqreac3").set("nuH", 1);
    model.component("comp1").physics("tcd").create("eqreac4", "EquilibriumReaction", 2);
    model.component("comp1").physics("tcd").feature("eqreac4").label("\u5e73\u8861\u53cd\u5e94 - Fe \u6c34\u89e3");
    model.component("comp1").physics("tcd").feature("eqreac4").selection().all();
    model.component("comp1").physics("tcd").feature("eqreac4").set("Keq0", "KFeOH");
    model.component("comp1").physics("tcd").feature("eqreac4").setIndex("nu", -1, 0);
    model.component("comp1").physics("tcd").feature("eqreac4").setIndex("nu", 1, 1);
    model.component("comp1").physics("tcd").feature("eqreac4").set("nuH", 1);
    model.component("comp1").physics("tcd").create("eqreac5", "EquilibriumReaction", 2);
    model.component("comp1").physics("tcd").feature("eqreac5")
         .label("\u5e73\u8861\u53cd\u5e94 - FeCO3 \u751f\u6210");
    model.component("comp1").physics("tcd").feature("eqreac5").selection().all();
    model.component("comp1").physics("tcd").feature("eqreac5").set("Keq0", "KFeCO3");
    model.component("comp1").physics("tcd").feature("eqreac5").setIndex("nu", 1, 0);
    model.component("comp1").physics("tcd").feature("eqreac5").setIndex("nu", -1, 2);
    model.component("comp1").physics("tcd").feature("eqreac5").setIndex("nu", 1, 7);

    model.component("comp1").mesh("mesh1").automatic(false);
    model.component("comp1").mesh("mesh1").feature("ftri1").create("dis1", "Distribution");
    model.component("comp1").mesh("mesh1").feature("ftri1").feature("dis1").selection().set(2);
    model.component("comp1").mesh("mesh1").feature("ftri1").feature("dis1").set("type", "predefined");
    model.component("comp1").mesh("mesh1").feature("ftri1").feature("dis1").set("elemcount", 200);
    model.component("comp1").mesh("mesh1").feature("ftri1").feature("dis1").set("elemratio", 10);
    model.component("comp1").mesh("mesh1").run();

    model.study("std1").feature("cdi").set("initType", "secondary");
    model.study("std1").feature("time").set("tlist", "range(0,10,300)");
    model.study("std1").createAutoSequences("all");

    model.sol("sol1").runAll();

    model.result().dataset().create("rev1", "Revolve2D");
    model.result().dataset("rev1").set("data", "dset1");
    model.result().dataset("rev1").set("revangle", 225);
    model.result().dataset("rev1").set("startangle", -90);
    model.result().dataset("rev1").set("hasspacevars", true);
    model.result().create("pg1", "PlotGroup2D");
    model.result("pg1").set("data", "dset1");
    model.result("pg1").setIndex("looplevel", 31, 0);
    model.result("pg1").label("\u7535\u89e3\u8d28\u7535\u4f4d (tcd)");
    model.result("pg1").create("surf1", "Surface");
    model.result("pg1").feature("surf1").set("expr", new String[]{"phil"});
    model.result("pg1").create("str1", "Streamline");
    model.result("pg1").feature("str1").set("expr", new String[]{"tcd.Ilr", "tcd.Ilz"});
    model.result("pg1").feature("str1").set("posmethod", "uniform");
    model.result("pg1").feature("str1").set("recover", "pprint");
    model.result("pg1").feature("str1").set("pointtype", "arrow");
    model.result("pg1").feature("str1").set("arrowlength", "logarithmic");
    model.result("pg1").feature("str1").set("color", "gray");
    model.result().create("pg2", "PlotGroup3D");
    model.result("pg2").set("data", "rev1");
    model.result("pg2").setIndex("looplevel", 31, 0);
    model.result("pg2").label("\u7535\u89e3\u8d28\u7535\u4f4d, 3D (tcd)");
    model.result("pg2").create("mslc1", "Multislice");
    model.result("pg2").feature("mslc1").set("expr", new String[]{"phil"});
    model.result("pg2").create("str1", "Streamline");
    model.result("pg2").feature("str1").set("revcoordsys", "cylindrical");
    model.result("pg2").feature("str1").set("expr", new String[]{"tcd.Ilr", "tcd.Ilphi", "tcd.Ilz"});
    model.result("pg2").feature("str1").set("pointtype", "arrow");
    model.result("pg2").feature("str1").set("arrowlength", "logarithmic");
    model.result("pg2").feature("str1").set("color", "gray");
    model.result().create("pg3", "PlotGroup2D");
    model.result("pg3").set("data", "dset1");
    model.result("pg3").setIndex("looplevel", 31, 0);
    model.result("pg3").label("\u7535\u89e3\u8d28\u7535\u6d41\u5bc6\u5ea6 (tcd)");
    model.result("pg3").create("str1", "Streamline");
    model.result("pg3").feature("str1").set("expr", new String[]{"tcd.Ilr", "tcd.Ilz"});
    model.result("pg3").feature("str1").set("posmethod", "uniform");
    model.result("pg3").feature("str1").set("recover", "pprint");
    model.result("pg3").feature("str1").set("pointtype", "arrow");
    model.result("pg3").feature("str1").set("arrowlength", "logarithmic");
    model.result("pg3").feature("str1").set("color", "gray");
    model.result("pg3").feature("str1").create("col1", "Color");
    model.result("pg3").feature("str1").feature("col1").set("expr", "root.comp1.tcd.IlMag");
    model.result().create("pg4", "PlotGroup3D");
    model.result("pg4").set("data", "rev1");
    model.result("pg4").setIndex("looplevel", 31, 0);
    model.result("pg4").label("\u7535\u89e3\u8d28\u7535\u6d41\u5bc6\u5ea6, 3D (tcd)");
    model.result("pg4").create("str1", "Streamline");
    model.result("pg4").feature("str1").set("revcoordsys", "cylindrical");
    model.result("pg4").feature("str1").set("expr", new String[]{"tcd.Ilr", "tcd.Ilphi", "tcd.Ilz"});
    model.result("pg4").feature("str1").set("pointtype", "arrow");
    model.result("pg4").feature("str1").set("arrowlength", "logarithmic");
    model.result("pg4").feature("str1").set("color", "gray");
    model.result("pg4").feature("str1").create("col1", "Color");
    model.result("pg4").feature("str1").feature("col1").set("expr", "root.comp1.tcd.IlMag");
    model.result("pg3").create("line1", "Line");
    model.result("pg3").feature("line1").set("expr", new String[]{"abs(tcd.itot)"});
    model.result("pg3").feature("line1").set("linetype", "tube");
    model.result("pg3").feature("line1").set("inherittubescale", false);
    model.result("pg3").feature("line1").set("inheritplot", "str1");
    model.result("pg4").create("surf1", "Surface");
    model.result("pg4").feature("surf1").set("expr", new String[]{"abs(tcd.itot)"});
    model.result("pg4").feature("surf1").set("inheritplot", "str1");
    model.result().create("pg5", "PlotGroup2D");
    model.result("pg5").set("data", "dset1");
    model.result("pg5").setIndex("looplevel", 31, 0);
    model.result("pg5").label("\u7535\u6781\u7535\u4f4d vs. \u76f8\u90bb\u53c2\u6bd4\u7535\u4f4d (tcd)");
    model.result().create("pg6", "PlotGroup3D");
    model.result("pg6").set("data", "rev1");
    model.result("pg6").setIndex("looplevel", 31, 0);
    model.result("pg6").label("\u7535\u6781\u7535\u4f4d vs. \u76f8\u90bb\u53c2\u6bd4\u7535\u4f4d, 3D (tcd)");
    model.result("pg5").create("str1", "Streamline");
    model.result("pg5").feature("str1").set("expr", new String[]{"tcd.Ilr", "tcd.Ilz"});
    model.result("pg5").feature("str1").set("posmethod", "uniform");
    model.result("pg5").feature("str1").set("recover", "pprint");
    model.result("pg5").feature("str1").set("pointtype", "arrow");
    model.result("pg5").feature("str1").set("arrowlength", "logarithmic");
    model.result("pg5").feature("str1").set("color", "gray");
    model.result("pg6").create("str1", "Streamline");
    model.result("pg6").feature("str1").set("revcoordsys", "cylindrical");
    model.result("pg6").feature("str1").set("expr", new String[]{"tcd.Ilr", "tcd.Ilphi", "tcd.Ilz"});
    model.result("pg6").feature("str1").set("pointtype", "arrow");
    model.result("pg6").feature("str1").set("arrowlength", "logarithmic");
    model.result("pg6").feature("str1").set("color", "gray");
    model.result("pg5").create("line1", "Line");
    model.result("pg5").feature("line1").set("expr", new String[]{"tcd.Evsref"});
    model.result("pg5").feature("line1").set("linetype", "tube");
    model.result("pg5").feature("line1").set("inherittubescale", false);
    model.result("pg6").create("surf1", "Surface");
    model.result("pg6").feature("surf1").set("expr", new String[]{"tcd.Evsref"});
    model.result().create("pg7", "PlotGroup2D");
    model.result("pg7").set("data", "dset1");
    model.result("pg7").setIndex("looplevel", 31, 0);
    model.result("pg7").label("\u7535\u6781\u603b\u539a\u5ea6\u53d8\u5316 (tcd)");
    model.result().create("pg8", "PlotGroup3D");
    model.result("pg8").set("data", "rev1");
    model.result("pg8").setIndex("looplevel", 31, 0);
    model.result("pg8").label("\u7535\u6781\u603b\u539a\u5ea6\u53d8\u5316, 3D (tcd)");
    model.result("pg7").create("line1", "Line");
    model.result("pg7").feature("line1").set("expr", new String[]{"tcd.sbtot"});
    model.result("pg7").feature("line1").set("linetype", "tube");
    model.result("pg7").feature("line1").set("inherittubescale", false);
    model.result("pg7").feature("line1").set("unit", "\u00b5m");
    model.result("pg8").create("surf1", "Surface");
    model.result("pg8").feature("surf1").set("expr", new String[]{"tcd.sbtot"});
    model.result("pg8").feature("surf1").set("unit", "\u00b5m");
    model.result().create("pg9", "PlotGroup2D");
    model.result("pg9").set("data", "dset1");
    model.result("pg9").setIndex("looplevel", 31, 0);
    model.result("pg9").label("\u6d53\u5ea6, Fe (tcd)");
    model.result("pg9").set("titletype", "custom");
    model.result("pg9").set("prefixintitle", "");
    model.result("pg9").set("expressionintitle", false);
    model.result("pg9").set("typeintitle", false);
    model.result("pg9").create("surf1", "Surface");
    model.result("pg9").feature("surf1").set("expr", new String[]{"cFe"});
    model.result("pg9").feature("surf1").set("colortable", "Rainbow");
    model.result("pg9").set("typeintitle", true);
    model.result("pg9").create("str1", "Streamline");
    model.result("pg9").feature("str1").set("expr", new String[]{"tcd.tflux_cFer", "tcd.tflux_cFez"});
    model.result("pg9").feature("str1").set("posmethod", "uniform");
    model.result("pg9").feature("str1").set("recover", "pprint");
    model.result("pg9").feature("str1").set("pointtype", "arrow");
    model.result("pg9").feature("str1").set("arrowlength", "logarithmic");
    model.result("pg9").feature("str1").set("color", "gray");
    model.result().dataset().create("rev2", "Revolve2D");
    model.result().dataset("rev2").set("data", "dset1");
    model.result().dataset("rev2").set("revangle", 225);
    model.result().dataset("rev2").set("startangle", -90);
    model.result().dataset("rev2").set("hasspacevars", false);
    model.result().create("pg10", "PlotGroup3D");
    model.result("pg10").set("data", "rev2");
    model.result("pg10").setIndex("looplevel", 31, 0);
    model.result("pg10").label("\u6d53\u5ea6, Fe, 3D (tcd)");
    model.result("pg10").create("surf1", "Surface");
    model.result("pg10").feature("surf1").set("expr", new String[]{"cFe"});
    model.result("pg10").feature("surf1").set("colortable", "Rainbow");
    model.result("pg10").set("titletype", "custom");
    model.result("pg10").set("typeintitle", false);
    model.result("pg10").set("prefixintitle", "");
    model.result("pg10").set("expressionintitle", false);
    model.result().create("pg11", "PlotGroup2D");
    model.result("pg11").set("data", "dset1");
    model.result("pg11").setIndex("looplevel", 31, 0);
    model.result("pg11").label("\u6d53\u5ea6, FeOH (tcd)");
    model.result("pg11").set("titletype", "custom");
    model.result("pg11").set("prefixintitle", "");
    model.result("pg11").set("expressionintitle", false);
    model.result("pg11").set("typeintitle", false);
    model.result("pg11").create("surf1", "Surface");
    model.result("pg11").feature("surf1").set("expr", new String[]{"cFeOH"});
    model.result("pg11").feature("surf1").set("colortable", "Rainbow");
    model.result("pg11").set("typeintitle", true);
    model.result("pg11").create("str1", "Streamline");
    model.result("pg11").feature("str1").set("expr", new String[]{"tcd.tflux_cFeOHr", "tcd.tflux_cFeOHz"});
    model.result("pg11").feature("str1").set("posmethod", "uniform");
    model.result("pg11").feature("str1").set("recover", "pprint");
    model.result("pg11").feature("str1").set("pointtype", "arrow");
    model.result("pg11").feature("str1").set("arrowlength", "logarithmic");
    model.result("pg11").feature("str1").set("color", "gray");
    model.result().create("pg12", "PlotGroup3D");
    model.result("pg12").set("data", "rev2");
    model.result("pg12").setIndex("looplevel", 31, 0);
    model.result("pg12").label("\u6d53\u5ea6, FeOH, 3D (tcd)");
    model.result("pg12").create("surf1", "Surface");
    model.result("pg12").feature("surf1").set("expr", new String[]{"cFeOH"});
    model.result("pg12").feature("surf1").set("colortable", "Rainbow");
    model.result("pg12").set("titletype", "custom");
    model.result("pg12").set("typeintitle", false);
    model.result("pg12").set("prefixintitle", "");
    model.result("pg12").set("expressionintitle", false);
    model.result().create("pg13", "PlotGroup2D");
    model.result("pg13").set("data", "dset1");
    model.result("pg13").setIndex("looplevel", 31, 0);
    model.result("pg13").label("\u6d53\u5ea6, FeCO3 (tcd)");
    model.result("pg13").set("titletype", "custom");
    model.result("pg13").set("prefixintitle", "");
    model.result("pg13").set("expressionintitle", false);
    model.result("pg13").set("typeintitle", false);
    model.result("pg13").create("surf1", "Surface");
    model.result("pg13").feature("surf1").set("expr", new String[]{"cFeCO3"});
    model.result("pg13").feature("surf1").set("colortable", "Rainbow");
    model.result("pg13").set("typeintitle", true);
    model.result("pg13").create("str1", "Streamline");
    model.result("pg13").feature("str1").set("expr", new String[]{"tcd.tflux_cFeCO3r", "tcd.tflux_cFeCO3z"});
    model.result("pg13").feature("str1").set("posmethod", "uniform");
    model.result("pg13").feature("str1").set("recover", "pprint");

    return model;
  }

  public static Model run2(Model model) {
    model.result("pg13").feature("str1").set("pointtype", "arrow");
    model.result("pg13").feature("str1").set("arrowlength", "logarithmic");
    model.result("pg13").feature("str1").set("color", "gray");
    model.result().create("pg14", "PlotGroup3D");
    model.result("pg14").set("data", "rev2");
    model.result("pg14").setIndex("looplevel", 31, 0);
    model.result("pg14").label("\u6d53\u5ea6, FeCO3, 3D (tcd)");
    model.result("pg14").create("surf1", "Surface");
    model.result("pg14").feature("surf1").set("expr", new String[]{"cFeCO3"});
    model.result("pg14").feature("surf1").set("colortable", "Rainbow");
    model.result("pg14").set("titletype", "custom");
    model.result("pg14").set("typeintitle", false);
    model.result("pg14").set("prefixintitle", "");
    model.result("pg14").set("expressionintitle", false);
    model.result().create("pg15", "PlotGroup2D");
    model.result("pg15").set("data", "dset1");
    model.result("pg15").setIndex("looplevel", 31, 0);
    model.result("pg15").label("\u6d53\u5ea6, O2 (tcd)");
    model.result("pg15").set("titletype", "custom");
    model.result("pg15").set("prefixintitle", "");
    model.result("pg15").set("expressionintitle", false);
    model.result("pg15").set("typeintitle", false);
    model.result("pg15").create("surf1", "Surface");
    model.result("pg15").feature("surf1").set("expr", new String[]{"cO2"});
    model.result("pg15").feature("surf1").set("colortable", "Rainbow");
    model.result("pg15").set("typeintitle", true);
    model.result("pg15").create("str1", "Streamline");
    model.result("pg15").feature("str1").set("expr", new String[]{"tcd.tflux_cO2r", "tcd.tflux_cO2z"});
    model.result("pg15").feature("str1").set("posmethod", "uniform");
    model.result("pg15").feature("str1").set("recover", "pprint");
    model.result("pg15").feature("str1").set("pointtype", "arrow");
    model.result("pg15").feature("str1").set("arrowlength", "logarithmic");
    model.result("pg15").feature("str1").set("color", "gray");
    model.result().create("pg16", "PlotGroup3D");
    model.result("pg16").set("data", "rev2");
    model.result("pg16").setIndex("looplevel", 31, 0);
    model.result("pg16").label("\u6d53\u5ea6, O2, 3D (tcd)");
    model.result("pg16").create("surf1", "Surface");
    model.result("pg16").feature("surf1").set("expr", new String[]{"cO2"});
    model.result("pg16").feature("surf1").set("colortable", "Rainbow");
    model.result("pg16").set("titletype", "custom");
    model.result("pg16").set("typeintitle", false);
    model.result("pg16").set("prefixintitle", "");
    model.result("pg16").set("expressionintitle", false);
    model.result().create("pg17", "PlotGroup2D");
    model.result("pg17").set("data", "dset1");
    model.result("pg17").setIndex("looplevel", 31, 0);
    model.result("pg17").label("\u6d53\u5ea6, CO2 (tcd)");
    model.result("pg17").set("titletype", "custom");
    model.result("pg17").set("prefixintitle", "");
    model.result("pg17").set("expressionintitle", false);
    model.result("pg17").set("typeintitle", false);
    model.result("pg17").create("surf1", "Surface");
    model.result("pg17").feature("surf1").set("expr", new String[]{"cCO2"});
    model.result("pg17").feature("surf1").set("colortable", "Rainbow");
    model.result("pg17").set("typeintitle", true);
    model.result("pg17").create("str1", "Streamline");
    model.result("pg17").feature("str1").set("expr", new String[]{"tcd.tflux_cCO2r", "tcd.tflux_cCO2z"});
    model.result("pg17").feature("str1").set("posmethod", "uniform");
    model.result("pg17").feature("str1").set("recover", "pprint");
    model.result("pg17").feature("str1").set("pointtype", "arrow");
    model.result("pg17").feature("str1").set("arrowlength", "logarithmic");
    model.result("pg17").feature("str1").set("color", "gray");
    model.result().create("pg18", "PlotGroup3D");
    model.result("pg18").set("data", "rev2");
    model.result("pg18").setIndex("looplevel", 31, 0);
    model.result("pg18").label("\u6d53\u5ea6, CO2, 3D (tcd)");
    model.result("pg18").create("surf1", "Surface");
    model.result("pg18").feature("surf1").set("expr", new String[]{"cCO2"});
    model.result("pg18").feature("surf1").set("colortable", "Rainbow");
    model.result("pg18").set("titletype", "custom");
    model.result("pg18").set("typeintitle", false);
    model.result("pg18").set("prefixintitle", "");
    model.result("pg18").set("expressionintitle", false);
    model.result().create("pg19", "PlotGroup2D");
    model.result("pg19").set("data", "dset1");
    model.result("pg19").setIndex("looplevel", 31, 0);
    model.result("pg19").label("\u6d53\u5ea6, H2CO3 (tcd)");
    model.result("pg19").set("titletype", "custom");
    model.result("pg19").set("prefixintitle", "");
    model.result("pg19").set("expressionintitle", false);
    model.result("pg19").set("typeintitle", false);
    model.result("pg19").create("surf1", "Surface");
    model.result("pg19").feature("surf1").set("expr", new String[]{"cH2CO3"});
    model.result("pg19").feature("surf1").set("colortable", "Rainbow");
    model.result("pg19").set("typeintitle", true);
    model.result("pg19").create("str1", "Streamline");
    model.result("pg19").feature("str1").set("expr", new String[]{"tcd.tflux_cH2CO3r", "tcd.tflux_cH2CO3z"});
    model.result("pg19").feature("str1").set("posmethod", "uniform");
    model.result("pg19").feature("str1").set("recover", "pprint");
    model.result("pg19").feature("str1").set("pointtype", "arrow");
    model.result("pg19").feature("str1").set("arrowlength", "logarithmic");
    model.result("pg19").feature("str1").set("color", "gray");
    model.result().create("pg20", "PlotGroup3D");
    model.result("pg20").set("data", "rev2");
    model.result("pg20").setIndex("looplevel", 31, 0);
    model.result("pg20").label("\u6d53\u5ea6, H2CO3, 3D (tcd)");
    model.result("pg20").create("surf1", "Surface");
    model.result("pg20").feature("surf1").set("expr", new String[]{"cH2CO3"});
    model.result("pg20").feature("surf1").set("colortable", "Rainbow");
    model.result("pg20").set("titletype", "custom");
    model.result("pg20").set("typeintitle", false);
    model.result("pg20").set("prefixintitle", "");
    model.result("pg20").set("expressionintitle", false);
    model.result().create("pg21", "PlotGroup2D");
    model.result("pg21").set("data", "dset1");
    model.result("pg21").setIndex("looplevel", 31, 0);
    model.result("pg21").label("\u6d53\u5ea6, HCO3 (tcd)");
    model.result("pg21").set("titletype", "custom");
    model.result("pg21").set("prefixintitle", "");
    model.result("pg21").set("expressionintitle", false);
    model.result("pg21").set("typeintitle", false);
    model.result("pg21").create("surf1", "Surface");
    model.result("pg21").feature("surf1").set("expr", new String[]{"cHCO3"});
    model.result("pg21").feature("surf1").set("colortable", "Rainbow");
    model.result("pg21").set("typeintitle", true);
    model.result("pg21").create("str1", "Streamline");
    model.result("pg21").feature("str1").set("expr", new String[]{"tcd.tflux_cHCO3r", "tcd.tflux_cHCO3z"});
    model.result("pg21").feature("str1").set("posmethod", "uniform");
    model.result("pg21").feature("str1").set("recover", "pprint");
    model.result("pg21").feature("str1").set("pointtype", "arrow");
    model.result("pg21").feature("str1").set("arrowlength", "logarithmic");
    model.result("pg21").feature("str1").set("color", "gray");
    model.result().create("pg22", "PlotGroup3D");
    model.result("pg22").set("data", "rev2");
    model.result("pg22").setIndex("looplevel", 31, 0);
    model.result("pg22").label("\u6d53\u5ea6, HCO3, 3D (tcd)");
    model.result("pg22").create("surf1", "Surface");
    model.result("pg22").feature("surf1").set("expr", new String[]{"cHCO3"});
    model.result("pg22").feature("surf1").set("colortable", "Rainbow");
    model.result("pg22").set("titletype", "custom");
    model.result("pg22").set("typeintitle", false);
    model.result("pg22").set("prefixintitle", "");
    model.result("pg22").set("expressionintitle", false);
    model.result().create("pg23", "PlotGroup2D");
    model.result("pg23").set("data", "dset1");
    model.result("pg23").setIndex("looplevel", 31, 0);
    model.result("pg23").label("\u6d53\u5ea6, CO3 (tcd)");
    model.result("pg23").set("titletype", "custom");
    model.result("pg23").set("prefixintitle", "");
    model.result("pg23").set("expressionintitle", false);
    model.result("pg23").set("typeintitle", false);
    model.result("pg23").create("surf1", "Surface");
    model.result("pg23").feature("surf1").set("expr", new String[]{"cCO3"});
    model.result("pg23").feature("surf1").set("colortable", "Rainbow");
    model.result("pg23").set("typeintitle", true);
    model.result("pg23").create("str1", "Streamline");
    model.result("pg23").feature("str1").set("expr", new String[]{"tcd.tflux_cCO3r", "tcd.tflux_cCO3z"});
    model.result("pg23").feature("str1").set("posmethod", "uniform");
    model.result("pg23").feature("str1").set("recover", "pprint");
    model.result("pg23").feature("str1").set("pointtype", "arrow");
    model.result("pg23").feature("str1").set("arrowlength", "logarithmic");
    model.result("pg23").feature("str1").set("color", "gray");
    model.result().create("pg24", "PlotGroup3D");
    model.result("pg24").set("data", "rev2");
    model.result("pg24").setIndex("looplevel", 31, 0);
    model.result("pg24").label("\u6d53\u5ea6, CO3, 3D (tcd)");
    model.result("pg24").create("surf1", "Surface");
    model.result("pg24").feature("surf1").set("expr", new String[]{"cCO3"});
    model.result("pg24").feature("surf1").set("colortable", "Rainbow");
    model.result("pg24").set("titletype", "custom");
    model.result("pg24").set("typeintitle", false);
    model.result("pg24").set("prefixintitle", "");
    model.result("pg24").set("expressionintitle", false);
    model.result().create("pg25", "PlotGroup2D");
    model.result("pg25").set("data", "dset1");
    model.result("pg25").setIndex("looplevel", 31, 0);
    model.result("pg25").label("\u6d53\u5ea6, Na (tcd)");
    model.result("pg25").set("titletype", "custom");
    model.result("pg25").set("prefixintitle", "");
    model.result("pg25").set("expressionintitle", false);
    model.result("pg25").set("typeintitle", false);
    model.result("pg25").create("surf1", "Surface");
    model.result("pg25").feature("surf1").set("expr", new String[]{"cNa"});
    model.result("pg25").feature("surf1").set("colortable", "Rainbow");
    model.result("pg25").set("typeintitle", true);
    model.result("pg25").create("str1", "Streamline");
    model.result("pg25").feature("str1").set("expr", new String[]{"tcd.tflux_cNar", "tcd.tflux_cNaz"});
    model.result("pg25").feature("str1").set("posmethod", "uniform");
    model.result("pg25").feature("str1").set("recover", "pprint");
    model.result("pg25").feature("str1").set("pointtype", "arrow");
    model.result("pg25").feature("str1").set("arrowlength", "logarithmic");
    model.result("pg25").feature("str1").set("color", "gray");
    model.result().create("pg26", "PlotGroup3D");
    model.result("pg26").set("data", "rev2");
    model.result("pg26").setIndex("looplevel", 31, 0);
    model.result("pg26").label("\u6d53\u5ea6, Na, 3D (tcd)");
    model.result("pg26").create("surf1", "Surface");
    model.result("pg26").feature("surf1").set("expr", new String[]{"cNa"});
    model.result("pg26").feature("surf1").set("colortable", "Rainbow");
    model.result("pg26").set("titletype", "custom");
    model.result("pg26").set("typeintitle", false);
    model.result("pg26").set("prefixintitle", "");
    model.result("pg26").set("expressionintitle", false);
    model.result().create("pg27", "PlotGroup2D");
    model.result("pg27").set("data", "dset1");
    model.result("pg27").setIndex("looplevel", 31, 0);
    model.result("pg27").label("\u6d53\u5ea6, Cl (tcd)");
    model.result("pg27").set("titletype", "custom");
    model.result("pg27").set("prefixintitle", "");
    model.result("pg27").set("expressionintitle", false);
    model.result("pg27").set("typeintitle", false);
    model.result("pg27").create("surf1", "Surface");
    model.result("pg27").feature("surf1").set("expr", new String[]{"cCl"});
    model.result("pg27").feature("surf1").set("colortable", "Rainbow");
    model.result("pg27").set("typeintitle", true);
    model.result("pg27").create("str1", "Streamline");
    model.result("pg27").feature("str1").set("expr", new String[]{"tcd.tflux_cClr", "tcd.tflux_cClz"});
    model.result("pg27").feature("str1").set("posmethod", "uniform");
    model.result("pg27").feature("str1").set("recover", "pprint");
    model.result("pg27").feature("str1").set("pointtype", "arrow");
    model.result("pg27").feature("str1").set("arrowlength", "logarithmic");
    model.result("pg27").feature("str1").set("color", "gray");
    model.result().create("pg28", "PlotGroup3D");
    model.result("pg28").set("data", "rev2");
    model.result("pg28").setIndex("looplevel", 31, 0);
    model.result("pg28").label("\u6d53\u5ea6, Cl, 3D (tcd)");
    model.result("pg28").create("surf1", "Surface");
    model.result("pg28").feature("surf1").set("expr", new String[]{"cCl"});
    model.result("pg28").feature("surf1").set("colortable", "Rainbow");
    model.result("pg28").set("titletype", "custom");
    model.result("pg28").set("typeintitle", false);
    model.result("pg28").set("prefixintitle", "");
    model.result("pg28").set("expressionintitle", false);
    model.result("pg1").run();
    model.result("pg10").run();
    model.result("pg10").setIndex("looplevel", 2, 0);
    model.result("pg10").run();
    model.result("pg10").setIndex("looplevel", 31, 0);
    model.result("pg10").run();
    model.result().create("pg29", "PlotGroup1D");
    model.result("pg29").run();
    model.result("pg29").label("\u5c40\u90e8\u7535\u6d41\u5bc6\u5ea6\u548c\u8986\u76d6\u7a0b\u5ea6");
    model.result("pg29").setIndex("looplevelinput", "last", 0);
    model.result("pg29").set("titletype", "none");
    model.result("pg29").set("legendpos", "middleleft");
    model.result("pg29").create("lngr1", "LineGraph");
    model.result("pg29").feature("lngr1").set("markerpos", "datapoints");
    model.result("pg29").feature("lngr1").set("linewidth", "preference");
    model.result("pg29").feature("lngr1").selection().set(2);
    model.result("pg29").feature("lngr1").set("expr", "tcd.iloc_er1");
    model.result("pg29").feature("lngr1").set("descr", "\u5c40\u90e8\u7535\u6d41\u5bc6\u5ea6");
    model.result("pg29").feature("lngr1").set("xdata", "expr");
    model.result("pg29").feature("lngr1").set("xdataexpr", "r");
    model.result("pg29").feature("lngr1").set("linestyle", "dashed");
    model.result("pg29").feature("lngr1").set("legend", true);
    model.result("pg29").feature("lngr1").set("legendmethod", "manual");
    model.result("pg29").feature("lngr1").setIndex("legends", "\u94c1\u6eb6\u89e3", 0);
    model.result("pg29").feature().duplicate("lngr2", "lngr1");
    model.result("pg29").run();
    model.result("pg29").feature("lngr2").set("expr", "tcd.iloc_er2");
    model.result("pg29").feature("lngr2").set("descr", "\u5c40\u90e8\u7535\u6d41\u5bc6\u5ea6");
    model.result("pg29").feature("lngr2").set("linestyle", "dotted");
    model.result("pg29").feature("lngr2").set("linecolor", "cyclereset");
    model.result("pg29").feature("lngr2").setIndex("legends", "\u6c27\u8fd8\u539f", 0);
    model.result("pg29").feature().duplicate("lngr3", "lngr2");
    model.result("pg29").run();
    model.result("pg29").feature("lngr3").set("expr", "tcd.itot");
    model.result("pg29").feature("lngr3").set("linestyle", "solid");
    model.result("pg29").feature("lngr3").setIndex("legends", "\u603b\u8ba1", 0);
    model.result("pg29").feature().duplicate("lngr4", "lngr3");
    model.result("pg29").run();
    model.result("pg29").feature("lngr4").set("expr", "theta");
    model.result("pg29").feature("lngr4").set("linemarker", "circle");
    model.result("pg29").feature("lngr4").set("markerpos", "interp");
    model.result("pg29").feature("lngr4").setIndex("legends", "\u8986\u76d6\u7a0b\u5ea6", 0);
    model.result("pg29").run();
    model.result("pg29").set("ylabelactive", true);
    model.result("pg29").set("ylabel", "\u5c40\u90e8\u7535\u6d41\u5bc6\u5ea6 (A/m<sup>2</sup>)");
    model.result("pg29").set("twoyaxes", true);
    model.result("pg29").setIndex("plotonsecyaxis", true, 3, 1);
    model.result("pg29").run();
    model.result("pg18").run();
    model.result("pg18").setIndex("looplevel", 2, 0);
    model.result("pg18").run();
    model.result("pg18").setIndex("looplevel", 31, 0);
    model.result("pg18").run();
    model.result().create("pg30", "PlotGroup3D");
    model.result("pg30").run();
    model.result("pg30").label("pH \u503c\uff0c\u4e09\u7ef4 (tcd)");
    model.result("pg30").create("surf1", "Surface");
    model.result("pg30").feature("surf1").set("expr", "tcd.pH");
    model.result("pg30").run();
    model.result("pg30").setIndex("looplevel", 2, 0);
    model.result("pg30").run();
    model.result("pg30").setIndex("looplevel", 31, 0);
    model.result("pg30").run();
    model.result().dataset().create("rev3", "Revolve2D");
    model.result("pg8").run();
    model.result("pg8").label("\u6c89\u6dc0\u7684 FeCO3 \u5206\u6570\uff0c\u4e09\u7ef4 (tcd)");
    model.result("pg8").set("data", "rev3");
    model.result("pg8").set("titletype", "manual");
    model.result("pg8")
         .set("title", "\u8868\u9762\uff1a\u6c89\u6dc0\u7684 FeCO<sub>3</sub> \u5206\u6570 (1) \u6d41\u7ebf\uff1a\u7535\u89e3\u8d28\u7535\u6d41\u5bc6\u5ea6\u77e2\u91cf (A/m<sup>2</sup>)");
    model.result("pg8").set("edges", false);
    model.result("pg8").run();
    model.result("pg8").feature("surf1").set("expr", "tcd.mbtot");
    model.result("pg8").feature("surf1").set("descr", "\u7535\u6781\u603b\u8d28\u91cf\u53d8\u5316");
    model.result("pg8").feature("surf1").set("unit", "mg/m^2");
    model.result("pg8").feature("surf1").set("colortable", "Acanthaster");
    model.result("pg8").run();
    model.result("pg8").create("str1", "Streamline");
    model.result("pg8").feature("str1").set("revcoordsys", "cylindrical");
    model.result("pg8").feature("str1").set("posmethod", "uniform");
    model.result("pg8").feature("str1").set("udist", 0.1);
    model.result("pg8").feature("str1").set("linetype", "tube");
    model.result("pg8").feature("str1").set("tuberadiusscaleactive", true);
    model.result("pg8").feature("str1").set("tuberadiusscale", "2.5e-5");
    model.result("pg8").feature("str1").set("pointtype", "arrow");
    model.result("pg8").feature("str1").set("arrowlength", "logarithmic");
    model.result("pg8").feature("str1").create("col1", "Color");
    model.result("pg8").run();
    model.result("pg8").feature("str1").feature("col1").set("expr", "tcd.IlMag");
    model.result("pg8").feature("str1").feature("col1")
         .set("descr", "\u7535\u89e3\u8d28\u7535\u6d41\u5bc6\u5ea6\u5927\u5c0f");
    model.result("pg8").feature("str1").feature("col1").set("colortable", "Viridis");
    model.result("pg8").feature("str1").feature("col1").set("colortabletrans", "reverse");
    model.result("pg8").feature("str1").feature("col1").set("colorlegend", false);
    model.result("pg8").run();
    model.result("pg8").create("surf2", "Surface");
    model.result("pg8").feature("surf2").set("expr", "1");
    model.result("pg8").feature("surf2").set("colorlegend", false);
    model.result("pg8").feature("surf2").create("sel1", "Selection");
    model.result("pg8").feature("surf2").feature("sel1").selection().set(1);
    model.result("pg8").run();
    model.result("pg8").feature("surf2").create("tran1", "Transparency");
    model.result("pg8").run();
    model.result("pg8").feature("surf2").feature("tran1").set("transparency", 0.85);
    model.result("pg8").run();
    model.result("pg8").feature("surf2").create("mtrl1", "MaterialAppearance");
    model.result("pg8").run();
    model.result("pg8").feature("surf2").feature("mtrl1").set("appearance", "custom");
    model.result("pg8").feature("surf2").feature("mtrl1").set("family", "water");
    model.result("pg8").run();
    model.result("pg8").run();
    model.result("pg7").run();
    model.result("pg7").label("\u8150\u8680\u4ea7\u7269\u6c89\u6dc0\u603b\u91cf (tcd)");
    model.result("pg7").run();
    model.result("pg7").feature("line1").set("expr", "tcd.mbtot");
    model.result("pg7").feature("line1").set("descr", "\u7535\u6781\u603b\u8d28\u91cf\u53d8\u5316");
    model.result("pg7").feature("line1").set("unit", "mg/m^2");
    model.result("pg7").run();
    model.result("pg25").run();
    model.result().remove("pg25");
    model.result().remove("pg26");
    model.result().remove("pg27");
    model.result().remove("pg28");
    model.result("pg29").run();

    model.title("Evans \u6db2\u6ef4\u4e0b\u7684\u8150\u8680");

    model
         .description("\u672c\u4f8b\u6a21\u62df\u94a2\u5728\u6c2f\u5316\u94a0\u6c34\u6eb6\u6db2\u6db2\u6ef4\u4e0b\u7684\u4e00\u822c\u5927\u6c14\u8150\u8680\u8fc7\u7a0b\u3002\u5176\u4e2d\u8003\u8651\u4e86\u8d28\u91cf\u4f20\u9012\u3001\u5747\u76f8\u53cd\u5e94\u4ee5\u53ca\u5927\u6c14\u4e2d\u6c27\u6c14\u548c\u4e8c\u6c27\u5316\u78b3\u7684\u76f8\u4e92\u4f5c\u7528\u3002\u8be5\u6a21\u578b\u8ba1\u7b97\u6db2\u6ef4\u5185\u7269\u8d28\u7684\u77ac\u6001\u548c\u7a7a\u95f4\u5206\u5e03\uff0c\u5305\u62ec\u7535\u6781\u8868\u9762\u901a\u8fc7\u6c89\u6dc0\u53cd\u5e94\u5f62\u6210\u7684\u949d\u5316\u8150\u8680\u4ea7\u7269\u3002");

    model.mesh().clearMeshes();

    model.sol("sol1").clearSolutionData();
    model.sol("sol2").clearSolutionData();

    model.label("evans_droplet.mph");

    return model;
  }

  public static void main(String[] args) {
    Model model = run();
    run2(model);
  }

}
