/*
 * double_barrier_1d.java
 */

import com.comsol.model.*;
import com.comsol.model.util.*;

/** Model exported on Apr 30 2026, 12:57 by COMSOL 6.3.0.290. */
public class double_barrier_1d {

  public static Model run() {
    Model model = ModelUtil.create("Model");

    model
         .modelPath("D:\\Program Files\\COMSOL\\COMSOL63\\Multiphysics\\applications\\Semiconductor_Module\\Verification_Examples");

    model.component().create("comp1", true);

    model.component("comp1").geom().create("geom1", 1);

    model.component("comp1").mesh().create("mesh1");

    model.component("comp1").physics().create("schr", "SchrodingerEquation", "geom1");

    model.study().create("std1");
    model.study("std1").create("eigv", "Eigenvalue");
    model.study("std1").feature("eigv").set("ftplistmethod", "manual");
    model.study("std1").feature("eigv").set("neigs", "3");
    model.study("std1").feature("eigv").set("eigunit", "");
    model.study("std1").feature("eigv").set("shift", "0.1");
    model.study("std1").feature("eigv").set("linpsolnum", "auto");
    model.study("std1").feature("eigv").set("solnum", "auto");
    model.study("std1").feature("eigv").set("notsolnum", "auto");
    model.study("std1").feature("eigv").set("outputmap", new String[]{});
    model.study("std1").feature("eigv").set("ngenAUX", "1");
    model.study("std1").feature("eigv").set("goalngenAUX", "1");
    model.study("std1").feature("eigv").set("ngenAUX", "1");
    model.study("std1").feature("eigv").set("goalngenAUX", "1");
    model.study("std1").feature("eigv").setSolveFor("/physics/schr", true);

    model.component("comp1").geom("geom1").lengthUnit("nm");

//    To import content from file, use:
//    model.param().loadFile("FILENAME");
    model.param().set("lmbd0", "1[eV]", "\u7279\u5f81\u503c\u5c3a\u5ea6");
    model.param().set("x0", "0.32", "AlGaAs \u4e2d Al \u7684\u5206\u6570");
    model.param().set("mw", "0.067*me_const", "\u9631\u533a\u57df\u4e2d\u7684\u6709\u6548\u8d28\u91cf");
    model.param()
         .set("mb", "(0.067+0.083*x0)*me_const", "\u52bf\u5792\u533a\u57df\u4e2d\u7684\u6709\u6548\u8d28\u91cf");
    model.param().set("Vb", "1.247[eV]*x0*0.67", "\u52bf\u5792\u533a\u57df\u4e2d\u7684\u52bf\u80fd");
    model.param().set("lw", "10[nm]", "\u9631\u957f\u5ea6");
    model.param().set("lb", "5[nm]", "\u52bf\u5792\u957f\u5ea6");
    model.param().set("L", "3*lw+2*lb", "\u5efa\u6a21\u57df\u957f\u5ea6");
    model.param()
         .set("reE1anal", "0.03095108621779908[eV]", "\u51c6\u675f\u7f1a\u6001\u7684\u89e3\u6790\u80fd\u91cf\uff0c\u5b9e\u90e8");
    model.param()
         .set("reE2anal", "0.122061164410767[eV]", "\u51c6\u675f\u7f1a\u6001\u7684\u89e3\u6790\u80fd\u91cf\uff0c\u5b9e\u90e8");
    model.param()
         .set("reE3anal", "0.25894903907423716[eV]", "\u51c6\u675f\u7f1a\u6001\u7684\u89e3\u6790\u80fd\u91cf\uff0c\u5b9e\u90e8");
    model.param().set("reE_anal", "reE1anal", "\u51c6\u675f\u7f1a\u6001\u7684\u626b\u63cf\u53c2\u6570");
    model.param()
         .set("imE1anal", "0.000010086285035003605[eV]", "\u51c6\u675f\u7f1a\u6001\u7684\u89e3\u6790\u80fd\u91cf\uff0c\u865a\u90e8");
    model.param()
         .set("imE2anal", "0.0001913257313211308[eV]", "\u51c6\u675f\u7f1a\u6001\u7684\u89e3\u6790\u80fd\u91cf\uff0c\u865a\u90e8");
    model.param()
         .set("imE3anal", "0.0031326022267301064[eV]", "\u51c6\u675f\u7f1a\u6001\u7684\u89e3\u6790\u80fd\u91cf\uff0c\u865a\u90e8");
    model.param().set("imE_anal", "imE1anal", "\u51c6\u675f\u7f1a\u6001\u7684\u626b\u63cf\u53c2\u6570");
    model.param().set("T3", "h_const/reE3anal", "\u77ac\u6001\u7814\u7a76\u7684\u65f6\u95f4\u5c3a\u5ea6");
    model.param().set("tau3", "hbar_const/imE3anal", "\u8870\u51cf\u65f6\u95f4\u5e38\u6570");
    model.param().set("E1anal", "0.0309510912373888[eV]", "transmission=1 \u89e3\u7684\u89e3\u6790\u80fd\u91cf");
    model.param().set("E2anal", "0.12206193797930533[eV]", "transmission=1 \u89e3\u7684\u89e3\u6790\u80fd\u91cf");
    model.param().set("E3anal", "0.2591443427675162[eV]", "transmission=1 \u89e3\u7684\u89e3\u6790\u80fd\u91cf");
    model.param().set("E_anal", "E1anal", "transmission=1 \u89e3\u7684\u626b\u63cf\u53c2\u6570");
    model.param().set("E0", "1[eV]", "\u7a33\u6001\u7814\u7a76\u7684\u80fd\u91cf");
    model.param().set("psi0", "1", "\u5165\u5c04\u6ce2\u632f\u5e45");

    model.component("comp1").geom("geom1").create("i1", "Interval");
    model.component("comp1").geom("geom1").feature("i1").set("specify", "len");
    model.component("comp1").geom("geom1").feature("i1").set("left", "-L/2");
    model.component("comp1").geom("geom1").feature("i1").setIndex("len", "lw", 0);
    model.component("comp1").geom("geom1").feature("i1").setIndex("len", "lb", 1);
    model.component("comp1").geom("geom1").feature("i1").setIndex("len", "L-2*lw-2*lb", 2);
    model.component("comp1").geom("geom1").feature("i1").setIndex("len", "lb", 3);
    model.component("comp1").geom("geom1").feature("i1").setIndex("len", "lw", 4);
    model.component("comp1").geom("geom1").runPre("fin");
    model.component("comp1").geom("geom1").run();

    model.component("comp1").physics("schr").prop("ModelProperties").set("lambda_scale", "lmbd0");
    model.component("comp1").physics("schr").feature("meff1")
         .set("meffe_psi", new String[]{"mw", "0", "0", "0", "mw", "0", "0", "0", "mw"});
    model.component("comp1").physics("schr").feature("ve1").set("Ve_src", "userdef");
    model.component("comp1").physics("schr").feature("ve1").set("Ve", 0);
    model.component("comp1").physics("schr").create("meff2", "EffectiveMass", 1);
    model.component("comp1").physics("schr").feature("meff2").selection().set(2, 4);
    model.component("comp1").physics("schr").feature("meff2")
         .set("meffe_psi", new String[]{"mb", "0", "0", "0", "mb", "0", "0", "0", "mb"});
    model.component("comp1").physics("schr").create("ve2", "ElectronPotentialEnergy", 1);
    model.component("comp1").physics("schr").feature("ve2").selection().set(2, 4);
    model.component("comp1").physics("schr").feature("ve2").set("Ve_src", "userdef");
    model.component("comp1").physics("schr").feature("ve2").set("Ve", "Vb");
    model.component("comp1").physics("schr").create("open1", "OpenBoundary", 0);
    model.component("comp1").physics("schr").feature("open1").selection().all();

    model.component("comp1").mesh("mesh1").create("edg1", "Edge");
    model.component("comp1").mesh("mesh1").feature("edg1").create("dis1", "Distribution");
    model.component("comp1").mesh("mesh1").feature("edg1").feature("dis1").set("numelem", 50);

    model.study("std1").feature("eigv").set("neigs", 1);
    model.study("std1").feature("eigv").set("shift", "reE_anal/lmbd0");
    model.study("std1").showAutoSequences("all");

    model.sol("sol1").feature("e1").set("eigref", "reE_anal/lmbd0");

    model.study("std1").create("param", "Parametric");
    model.study("std1").feature("param").setIndex("pname", "lmbd0", 0);
    model.study("std1").feature("param").setIndex("plistarr", "", 0);
    model.study("std1").feature("param").setIndex("punit", "J", 0);
    model.study("std1").feature("param").setIndex("pname", "lmbd0", 0);
    model.study("std1").feature("param").setIndex("plistarr", "", 0);
    model.study("std1").feature("param").setIndex("punit", "J", 0);
    model.study("std1").feature("param").setIndex("pname", "x0", 1);
    model.study("std1").feature("param").setIndex("plistarr", "", 1);
    model.study("std1").feature("param").setIndex("punit", "", 1);
    model.study("std1").feature("param").setIndex("pname", "x0", 1);
    model.study("std1").feature("param").setIndex("plistarr", "", 1);
    model.study("std1").feature("param").setIndex("punit", "", 1);
    model.study("std1").feature("param").setIndex("pname", "reE_anal", 0);
    model.study("std1").feature("param").setIndex("plistarr", "reE1anal reE2anal reE3anal", 0);
    model.study("std1").feature("param").setIndex("pname", "imE_anal", 1);
    model.study("std1").feature("param").setIndex("plistarr", "imE1anal imE2anal imE3anal", 1);
    model.study("std1").createAutoSequences("all");

    model.sol().create("sol2");
    model.sol("sol2").study("std1");
    model.sol("sol2").label("\u53c2\u6570\u5316\u89e3 1");

    model.batch("p1").feature("so1").set("psol", "sol2");
    model.batch("p1").run("compute");

    model.result().numerical().create("gev1", "EvalGlobal");
    model.result().numerical("gev1").label("\u7279\u5f81\u503c");
    model.result().numerical("gev1").set("data", "dset2");
    model.result().numerical("gev1").set("showlooplevelinput", new String[]{"off", "off", "off"});
    model.result().numerical("gev1").set("hasouter", "off");
    model.result().numerical("gev1").set("expr", new String[]{"schr.Ei", "schr.int(schr.Pr)"});
    model.result().numerical("gev1").setIndex("unit", "eV", 0);
    model.result().numerical("gev1").set("descr", new String[]{"\u7279\u5f81\u80fd\u91cf", "\u603b\u6982\u7387"});
    model.result().numerical("gev1").set("hasouter", "off");
    model.result().numerical("gev1").setIndex("unit", "eV", 0);
    model.result().numerical("gev1").set("hasouter", "off");
    model.result().numerical("gev1").setIndex("unit", "eV", 0);
    model.result().numerical("gev1").set("hasouter", "off");
    model.result().numerical("gev1").setIndex("unit", "eV", 0);
    model.result().numerical("gev1").set("hasouter", "off");
    model.result().numerical("gev1").setIndex("unit", "eV", 0);
    model.result().numerical("gev1").set("data", "dset2");
    model.result().create("pg1", "PlotGroup1D");
    model.result("pg1").label("\u5f52\u4e00\u5316\u6ce2\u51fd\u6570 (schr)");
    model.result("pg1").set("data", "dset2");
    model.result("pg1").set("showlooplevelinput", new String[]{"off", "off", "off"});
    model.result("pg1").feature().create("lngr1", "LineGraph");
    model.result("pg1").feature("lngr1").label("\u5b9e\u90e8");
    model.result("pg1").feature("lngr1").set("expr", "schr.Psi_psi");
    model.result("pg1").feature("lngr1").set("xdata", "expr");
    model.result("pg1").feature("lngr1").set("xdataexpr", "X");
    model.result("pg1").feature("lngr1").set("smooth", "internal");
    model.result("pg1").feature("lngr1").set("data", "parent");
    model.result("pg1").feature("lngr1").selection().geom("geom1", 1);
    model.result("pg1").feature("lngr1").selection().set(1, 2, 3, 4, 5);
    model.result("pg1").feature().create("lngr2", "LineGraph");
    model.result("pg1").feature("lngr2").label("\u865a\u90e8");
    model.result("pg1").feature("lngr2").set("expr", "imag(schr.Psi_psi)");
    model.result("pg1").feature("lngr2").set("xdata", "expr");
    model.result("pg1").feature("lngr2").set("xdataexpr", "X");
    model.result("pg1").feature("lngr2").set("linestyle", "dashed");
    model.result("pg1").feature("lngr2").set("linecolor", "cyclereset");
    model.result("pg1").feature("lngr2").set("smooth", "internal");
    model.result("pg1").feature("lngr2").set("data", "parent");
    model.result("pg1").feature("lngr2").selection().geom("geom1", 1);
    model.result("pg1").feature("lngr2").selection().set(1, 2, 3, 4, 5);
    model.result().create("pg2", "PlotGroup1D");
    model.result("pg2").label("\u52bf\u80fd\u3001\u7279\u5f81\u80fd\u91cf\u548c\u6ce2\u51fd\u6570 (schr)");
    model.result("pg2").set("data", "dset2");
    model.result("pg2").set("showlooplevelinput", new String[]{"off", "off", "off"});
    model.result("pg2").feature().create("lngr1", "LineGraph");
    model.result("pg2").feature("lngr1").label("\u52bf\u80fd");
    model.result("pg2").feature("lngr1").set("expr", "schr.V_psi");
    model.result("pg2").feature("lngr1").set("unit", "eV");
    model.result("pg2").feature("lngr1").set("xdata", "expr");
    model.result("pg2").feature("lngr1").set("xdataexpr", "X");
    model.result("pg2").feature("lngr1").set("linecolor", "black");
    model.result("pg2").feature("lngr1").set("smooth", "everywhere");
    model.result("pg2").feature("lngr1").set("data", "parent");
    model.result("pg2").feature("lngr1").selection().geom("geom1", 1);
    model.result("pg2").feature("lngr1").selection().set(1, 2, 3, 4, 5);
    model.result("pg2").feature().create("lngr2", "LineGraph");
    model.result("pg2").feature("lngr2").label("\u5b9e\u90e8");
    model.result("pg2").feature("lngr2").set("expr", "schr.Psi_psi*0.1[eV]/schr.plot_fac+schr.Ei");
    model.result("pg2").feature("lngr2").set("unit", "eV");
    model.result("pg2").feature("lngr2").set("xdata", "expr");
    model.result("pg2").feature("lngr2").set("xdataexpr", "X");
    model.result("pg2").feature("lngr2").set("legend", true);
    model.result("pg2").feature("lngr2").set("smooth", "internal");
    model.result("pg2").feature("lngr2").set("data", "parent");
    model.result("pg2").feature("lngr2").selection().geom("geom1", 1);
    model.result("pg2").feature("lngr2").selection().set(1, 2, 3, 4, 5);
    model.result("pg2").feature().create("lngr3", "LineGraph");
    model.result("pg2").feature("lngr3").label("\u865a\u90e8");
    model.result("pg2").feature("lngr3").set("expr", "imag(schr.Psi_psi)*0.1[eV]/schr.plot_fac+schr.Ei");
    model.result("pg2").feature("lngr3").set("unit", "eV");
    model.result("pg2").feature("lngr3").set("xdata", "expr");
    model.result("pg2").feature("lngr3").set("xdataexpr", "X");
    model.result("pg2").feature("lngr3").set("linestyle", "dashed");
    model.result("pg2").feature("lngr3").set("linecolor", "cyclereset");
    model.result("pg2").feature("lngr3").set("smooth", "internal");
    model.result("pg2").feature("lngr3").set("data", "parent");
    model.result("pg2").feature("lngr3").selection().geom("geom1", 1);
    model.result("pg2").feature("lngr3").selection().set(1, 2, 3, 4, 5);
    model.result("pg2").feature().create("lngr4", "LineGraph");
    model.result("pg2").feature("lngr4").label("\u7279\u5f81\u80fd\u91cf");
    model.result("pg2").feature("lngr4").set("expr", "schr.Ei");
    model.result("pg2").feature("lngr4").set("unit", "eV");
    model.result("pg2").feature("lngr4").set("xdata", "expr");
    model.result("pg2").feature("lngr4").set("xdataexpr", "X");
    model.result("pg2").feature("lngr4").set("linestyle", "dotted");
    model.result("pg2").feature("lngr4").set("linecolor", "black");
    model.result("pg2").feature("lngr4").set("smooth", "internal");
    model.result("pg2").feature("lngr4").set("data", "parent");
    model.result("pg2").feature("lngr4").selection().geom("geom1", 1);
    model.result("pg2").feature("lngr4").selection().set(1, 2, 3, 4, 5);
    model.result().create("pg3", "PlotGroup1D");
    model.result("pg3").label("\u6982\u7387\u5bc6\u5ea6 (schr)");
    model.result("pg3").set("data", "dset2");
    model.result("pg3").set("showlooplevelinput", new String[]{"off", "off", "off"});
    model.result("pg3").feature().create("lngr1", "LineGraph");
    model.result("pg3").feature("lngr1").set("expr", "schr.Pr");
    model.result("pg3").feature("lngr1").set("xdata", "expr");
    model.result("pg3").feature("lngr1").set("xdataexpr", "X");
    model.result("pg3").feature("lngr1").set("smooth", "internal");
    model.result("pg3").feature("lngr1").set("data", "parent");
    model.result("pg3").feature("lngr1").selection().geom("geom1", 1);
    model.result("pg3").feature("lngr1").selection().set(1, 2, 3, 4, 5);
    model.result().create("pg4", "PlotGroup1D");
    model.result("pg4").label("\u52bf\u80fd (schr)");
    model.result("pg4").set("data", "dset2");
    model.result("pg4").set("showlooplevelinput", new String[]{"off", "off", "off"});
    model.result("pg4").feature().create("lngr1", "LineGraph");
    model.result("pg4").feature("lngr1").set("expr", "schr.V_psi");
    model.result("pg4").feature("lngr1").set("unit", "eV");
    model.result("pg4").feature("lngr1").set("xdata", "expr");
    model.result("pg4").feature("lngr1").set("xdataexpr", "X");
    model.result("pg4").feature("lngr1").set("smooth", "everywhere");
    model.result("pg4").feature("lngr1").set("data", "parent");
    model.result("pg4").feature("lngr1").selection().geom("geom1", 1);
    model.result("pg4").feature("lngr1").selection().set(1, 2, 3, 4, 5);
    model.result().create("pg5", "PlotGroup1D");
    model.result("pg5").label("\u6709\u6548\u8d28\u91cf (schr)");
    model.result("pg5").set("data", "dset2");
    model.result("pg5").set("showlooplevelinput", new String[]{"off", "off", "off"});
    model.result("pg5").feature().create("lngr1", "LineGraph");
    model.result("pg5").feature("lngr1").set("expr", "schr.meff_psiXX/me_const");
    model.result("pg5").feature("lngr1").set("xdata", "expr");
    model.result("pg5").feature("lngr1").set("xdataexpr", "X");
    model.result("pg5").feature("lngr1").set("smooth", "everywhere");
    model.result("pg5").feature("lngr1").set("data", "parent");
    model.result("pg5").feature("lngr1").selection().geom("geom1", 1);
    model.result("pg5").feature("lngr1").selection().set(1, 2, 3, 4, 5);
    model.result("pg1").run();
    model.result("pg2").run();
    model.result("pg2").set("titletype", "manual");
    model.result("pg2").set("xlabelactive", true);
    model.result("pg2").set("xlabel", "X (nm)");
    model.result("pg2").set("ylabelactive", true);
    model.result("pg2").set("ylabel", "\u80fd\u91cf (eV)");
    model.result("pg2").set("showlegends", false);
    model.result("pg2").run();
    model.result().numerical("gev1").setIndex("expr", "real(schr.Ei)/reE_anal-1", 2);
    model.result().numerical("gev1").setIndex("descr", "\u5b9e\u90e8\u8bef\u5dee", 2);
    model.result().numerical("gev1").setIndex("expr", "imag(schr.Ei)/imE_anal-1", 3);
    model.result().numerical("gev1").setIndex("descr", "\u865a\u90e8\u8bef\u5dee", 3);
    model.result().table().create("tbl1", "Table");
    model.result().table("tbl1").comments("\u7279\u5f81\u503c");
    model.result().numerical("gev1").set("table", "tbl1");
    model.result().numerical("gev1").setResult();

    model.study().create("std2");
    model.study("std2").create("time", "Transient");
    model.study("std2").feature("time").setSolveFor("/physics/schr", true);
    model.study("std2").feature("time").set("useinitsol", true);
    model.study("std2").feature("time").set("initstudy", "std1");

    model.component("comp1").physics("schr").create("init2", "init", 1);
    model.component("comp1").physics("schr").feature("init2")
         .label("\u77ac\u6001\u7814\u7a76\u7684\u521d\u59cb\u503c 2");
    model.component("comp1").physics("schr").feature("init2").selection().all();
    model.component("comp1").physics("schr").feature("init2").set("psi", "schr.Psi");

    model.study("std2").feature("time").set("tlist", "range(0,T3/10,tau3/3)");
    model.study("std2").createAutoSequences("all");

    model.sol("sol6").runAll();

    model.result().create("pg6", "PlotGroup1D");
    model.result("pg6").label("\u6ce2\u51fd\u6570 (schr)");
    model.result("pg6").set("data", "dset3");
    model.result("pg6").set("showlooplevelinput", new String[]{"off", "off", "off"});
    model.result("pg6").feature().create("lngr1", "LineGraph");
    model.result("pg6").feature("lngr1").label("\u5b9e\u90e8");
    model.result("pg6").feature("lngr1").set("expr", "psi");
    model.result("pg6").feature("lngr1").set("xdata", "expr");
    model.result("pg6").feature("lngr1").set("xdataexpr", "X");
    model.result("pg6").feature("lngr1").set("smooth", "internal");
    model.result("pg6").feature("lngr1").set("data", "parent");
    model.result("pg6").feature("lngr1").selection().geom("geom1", 1);
    model.result("pg6").feature("lngr1").selection().set(1, 2, 3, 4, 5);
    model.result("pg6").feature().create("lngr2", "LineGraph");
    model.result("pg6").feature("lngr2").label("\u865a\u90e8");
    model.result("pg6").feature("lngr2").set("expr", "imag(psi)");
    model.result("pg6").feature("lngr2").set("xdata", "expr");
    model.result("pg6").feature("lngr2").set("xdataexpr", "X");
    model.result("pg6").feature("lngr2").set("linestyle", "dashed");
    model.result("pg6").feature("lngr2").set("linecolor", "cyclereset");
    model.result("pg6").feature("lngr2").set("smooth", "internal");
    model.result("pg6").feature("lngr2").set("data", "parent");
    model.result("pg6").feature("lngr2").selection().geom("geom1", 1);
    model.result("pg6").feature("lngr2").selection().set(1, 2, 3, 4, 5);
    model.result().create("pg7", "PlotGroup1D");
    model.result("pg7").label("\u6982\u7387\u5bc6\u5ea6 (schr) 1");
    model.result("pg7").set("data", "dset3");
    model.result("pg7").set("showlooplevelinput", new String[]{"off", "off", "off"});
    model.result("pg7").feature().create("lngr1", "LineGraph");
    model.result("pg7").feature("lngr1").set("expr", "schr.Pr");
    model.result("pg7").feature("lngr1").set("xdata", "expr");
    model.result("pg7").feature("lngr1").set("xdataexpr", "X");
    model.result("pg7").feature("lngr1").set("smooth", "internal");
    model.result("pg7").feature("lngr1").set("data", "parent");
    model.result("pg7").feature("lngr1").selection().geom("geom1", 1);
    model.result("pg7").feature("lngr1").selection().set(1, 2, 3, 4, 5);
    model.result().create("pg8", "PlotGroup1D");
    model.result("pg8").label("\u52bf\u80fd (schr) 1");
    model.result("pg8").set("data", "dset3");
    model.result("pg8").set("showlooplevelinput", new String[]{"off", "off", "off"});
    model.result("pg8").feature().create("lngr1", "LineGraph");
    model.result("pg8").feature("lngr1").set("expr", "schr.V_psi");
    model.result("pg8").feature("lngr1").set("unit", "eV");
    model.result("pg8").feature("lngr1").set("xdata", "expr");
    model.result("pg8").feature("lngr1").set("xdataexpr", "X");
    model.result("pg8").feature("lngr1").set("smooth", "everywhere");
    model.result("pg8").feature("lngr1").set("data", "parent");
    model.result("pg8").feature("lngr1").selection().geom("geom1", 1);
    model.result("pg8").feature("lngr1").selection().set(1, 2, 3, 4, 5);
    model.result().create("pg9", "PlotGroup1D");
    model.result("pg9").label("\u6709\u6548\u8d28\u91cf (schr) 1");
    model.result("pg9").set("data", "dset3");
    model.result("pg9").set("showlooplevelinput", new String[]{"off", "off", "off"});
    model.result("pg9").feature().create("lngr1", "LineGraph");
    model.result("pg9").feature("lngr1").set("expr", "schr.meff_psiXX/me_const");
    model.result("pg9").feature("lngr1").set("xdata", "expr");
    model.result("pg9").feature("lngr1").set("xdataexpr", "X");
    model.result("pg9").feature("lngr1").set("smooth", "everywhere");
    model.result("pg9").feature("lngr1").set("data", "parent");
    model.result("pg9").feature("lngr1").selection().geom("geom1", 1);
    model.result("pg9").feature("lngr1").selection().set(1, 2, 3, 4, 5);
    model.result("pg6").run();
    model.result().export().create("anim1", "Animation");
    model.result().export("anim1").set("target", "player");
    model.result().export("anim1").set("plotgroup", "pg6");
    model.result().export("anim1").run();
    model.result().export("anim1").set("framesel", "all");
    model.result().export("anim1").run();
    model.result().export().duplicate("anim2", "anim1");
    model.result().export("anim2").showFrame();
    model.result().export("anim2").set("plotgroup", "pg7");
    model.result().export("anim2").run();
    model.result("pg8").run();
    model.result().remove("pg8");
    model.result("pg9").run();
    model.result().remove("pg9");
    model.result().create("pg8", "PlotGroup1D");
    model.result("pg8").run();
    model.result("pg8").label("\u6bd4\u8f83\u603b\u6982\u7387\u7684\u8870\u51cf");
    model.result("pg8").set("data", "dset3");
    model.result("pg8").set("titletype", "manual");
    model.result("pg8").set("title", "\u603b\u6982\u7387\u8870\u51cf");
    model.result("pg8").set("ylabelactive", true);
    model.result("pg8").set("ylabel", "\u603b\u6982\u7387");
    model.result("pg8").create("glob1", "Global");
    model.result("pg8").feature("glob1").set("markerpos", "datapoints");
    model.result("pg8").feature("glob1").set("linewidth", "preference");
    model.result("pg8").feature("glob1").setIndex("expr", "schr.int(schr.Pr)", 0);
    model.result("pg8").feature("glob1").setIndex("descr", "\u8ba1\u7b97\u51fa\u7684\u8870\u51cf\u66f2\u7ebf", 0);
    model.result("pg8").feature("glob1").setIndex("expr", "exp(-t/tau3)^2", 1);
    model.result("pg8").feature("glob1").setIndex("descr", "\u89e3\u6790\u8870\u51cf\u66f2\u7ebf", 1);
    model.result("pg8").feature("glob1").set("linestyle", "cycle");
    model.result("pg8").run();

    model.component("comp1").physics("schr").create("open2", "OpenBoundary", 0);
    model.component("comp1").physics("schr").feature("open2")
         .label("\u5171\u632f\u96a7\u7a7f\u7814\u7a76\u7684\u5f00\u653e\u8fb9\u754c 2");
    model.component("comp1").physics("schr").feature("open2").selection().set(1);
    model.component("comp1").physics("schr").feature("open2").set("openBoundaryType", "incoming");

    model.study().create("std3");
    model.study("std3").create("eigv", "Eigenvalue");
    model.study("std3").feature("eigv").set("plotgroup", "Default");
    model.study("std3").feature("eigv").set("ftplistmethod", "manual");
    model.study("std3").feature("eigv").set("neigs", "3");
    model.study("std3").feature("eigv").set("eigunit", "");
    model.study("std3").feature("eigv").set("shift", "0.1");
    model.study("std3").feature("eigv").set("linpsolnum", "auto");
    model.study("std3").feature("eigv").set("solnum", "auto");
    model.study("std3").feature("eigv").set("notsolnum", "auto");
    model.study("std3").feature("eigv").set("outputmap", new String[]{});
    model.study("std3").feature("eigv").set("ngenAUX", "1");
    model.study("std3").feature("eigv").set("goalngenAUX", "1");
    model.study("std3").feature("eigv").set("ngenAUX", "1");
    model.study("std3").feature("eigv").set("goalngenAUX", "1");
    model.study("std3").feature("eigv").setSolveFor("/physics/schr", true);
    model.study("std3").feature("eigv").set("neigs", 1);
    model.study("std3").feature("eigv").set("shift", "E_anal/lmbd0");
    model.study("std3").feature("eigv").set("useadvanceddisable", true);
    model.study("std3").feature("eigv").set("disabledphysics", new String[]{"schr/init2"});
    model.study("std3").label("\u7814\u7a76 3 \u5171\u632f\u96a7\u7a7f");
    model.study("std3").showAutoSequences("all");

    model.sol("sol7").feature("e1").set("eigref", "E_anal/lmbd0");

    model.study("std3").create("param", "Parametric");
    model.study("std3").feature("param").setIndex("pname", "lmbd0", 0);
    model.study("std3").feature("param").setIndex("plistarr", "", 0);
    model.study("std3").feature("param").setIndex("punit", "J", 0);
    model.study("std3").feature("param").setIndex("pname", "lmbd0", 0);
    model.study("std3").feature("param").setIndex("plistarr", "", 0);
    model.study("std3").feature("param").setIndex("punit", "J", 0);
    model.study("std3").feature("param").setIndex("pname", "E_anal", 0);
    model.study("std3").feature("param").setIndex("plistarr", "E1anal E2anal E3anal", 0);
    model.study("std3").createAutoSequences("all");

    model.sol().create("sol8");
    model.sol("sol8").study("std3");
    model.sol("sol8").label("\u53c2\u6570\u5316\u89e3 2");

    model.batch("p2").feature("so1").set("psol", "sol8");
    model.batch("p2").run("compute");

    model.result().numerical().create("gev2", "EvalGlobal");
    model.result().numerical("gev2").label("\u7279\u5f81\u503c 1");
    model.result().numerical("gev2").set("data", "dset5");
    model.result().numerical("gev2").set("showlooplevelinput", new String[]{"off", "off", "off"});
    model.result().numerical("gev2").set("hasouter", "off");
    model.result().numerical("gev2").set("expr", new String[]{"schr.Ei", "schr.int(schr.Pr)"});
    model.result().numerical("gev2").setIndex("unit", "eV", 0);
    model.result().numerical("gev2").set("descr", new String[]{"\u7279\u5f81\u80fd\u91cf", "\u603b\u6982\u7387"});
    model.result().numerical("gev2").set("hasouter", "off");
    model.result().numerical("gev2").setIndex("unit", "eV", 0);
    model.result().numerical("gev2").set("hasouter", "off");
    model.result().numerical("gev2").setIndex("unit", "eV", 0);
    model.result().numerical("gev2").set("hasouter", "off");
    model.result().numerical("gev2").setIndex("unit", "eV", 0);
    model.result().numerical("gev2").set("hasouter", "off");
    model.result().numerical("gev2").setIndex("unit", "eV", 0);
    model.result().numerical("gev2").set("data", "dset5");
    model.result().create("pg9", "PlotGroup1D");
    model.result("pg9").label("\u5f52\u4e00\u5316\u6ce2\u51fd\u6570 (schr) 1");
    model.result("pg9").set("data", "dset5");
    model.result("pg9").set("showlooplevelinput", new String[]{"off", "off", "off"});
    model.result("pg9").feature().create("lngr1", "LineGraph");
    model.result("pg9").feature("lngr1").label("\u5b9e\u90e8");
    model.result("pg9").feature("lngr1").set("expr", "schr.Psi_psi");
    model.result("pg9").feature("lngr1").set("xdata", "expr");
    model.result("pg9").feature("lngr1").set("xdataexpr", "X");
    model.result("pg9").feature("lngr1").set("smooth", "internal");
    model.result("pg9").feature("lngr1").set("data", "parent");
    model.result("pg9").feature("lngr1").selection().geom("geom1", 1);
    model.result("pg9").feature("lngr1").selection().set(1, 2, 3, 4, 5);
    model.result("pg9").feature().create("lngr2", "LineGraph");
    model.result("pg9").feature("lngr2").label("\u865a\u90e8");
    model.result("pg9").feature("lngr2").set("expr", "imag(schr.Psi_psi)");
    model.result("pg9").feature("lngr2").set("xdata", "expr");
    model.result("pg9").feature("lngr2").set("xdataexpr", "X");
    model.result("pg9").feature("lngr2").set("linestyle", "dashed");
    model.result("pg9").feature("lngr2").set("linecolor", "cyclereset");
    model.result("pg9").feature("lngr2").set("smooth", "internal");
    model.result("pg9").feature("lngr2").set("data", "parent");
    model.result("pg9").feature("lngr2").selection().geom("geom1", 1);
    model.result("pg9").feature("lngr2").selection().set(1, 2, 3, 4, 5);
    model.result().create("pg10", "PlotGroup1D");
    model.result("pg10").label("\u52bf\u80fd\u3001\u7279\u5f81\u80fd\u91cf\u548c\u6ce2\u51fd\u6570 (schr) 1");
    model.result("pg10").set("data", "dset5");
    model.result("pg10").set("showlooplevelinput", new String[]{"off", "off", "off"});
    model.result("pg10").feature().create("lngr1", "LineGraph");
    model.result("pg10").feature("lngr1").label("\u52bf\u80fd");
    model.result("pg10").feature("lngr1").set("expr", "schr.V_psi");
    model.result("pg10").feature("lngr1").set("unit", "eV");
    model.result("pg10").feature("lngr1").set("xdata", "expr");
    model.result("pg10").feature("lngr1").set("xdataexpr", "X");
    model.result("pg10").feature("lngr1").set("linecolor", "black");
    model.result("pg10").feature("lngr1").set("smooth", "everywhere");
    model.result("pg10").feature("lngr1").set("data", "parent");
    model.result("pg10").feature("lngr1").selection().geom("geom1", 1);
    model.result("pg10").feature("lngr1").selection().set(1, 2, 3, 4, 5);
    model.result("pg10").feature().create("lngr2", "LineGraph");
    model.result("pg10").feature("lngr2").label("\u5b9e\u90e8");
    model.result("pg10").feature("lngr2").set("expr", "schr.Psi_psi*0.1[eV]/schr.plot_fac+schr.Ei");
    model.result("pg10").feature("lngr2").set("unit", "eV");
    model.result("pg10").feature("lngr2").set("xdata", "expr");
    model.result("pg10").feature("lngr2").set("xdataexpr", "X");
    model.result("pg10").feature("lngr2").set("legend", true);
    model.result("pg10").feature("lngr2").set("smooth", "internal");
    model.result("pg10").feature("lngr2").set("data", "parent");
    model.result("pg10").feature("lngr2").selection().geom("geom1", 1);
    model.result("pg10").feature("lngr2").selection().set(1, 2, 3, 4, 5);

    return model;
  }

  public static Model run2(Model model) {
    model.result("pg10").feature().create("lngr3", "LineGraph");
    model.result("pg10").feature("lngr3").label("\u865a\u90e8");
    model.result("pg10").feature("lngr3").set("expr", "imag(schr.Psi_psi)*0.1[eV]/schr.plot_fac+schr.Ei");
    model.result("pg10").feature("lngr3").set("unit", "eV");
    model.result("pg10").feature("lngr3").set("xdata", "expr");
    model.result("pg10").feature("lngr3").set("xdataexpr", "X");
    model.result("pg10").feature("lngr3").set("linestyle", "dashed");
    model.result("pg10").feature("lngr3").set("linecolor", "cyclereset");
    model.result("pg10").feature("lngr3").set("smooth", "internal");
    model.result("pg10").feature("lngr3").set("data", "parent");
    model.result("pg10").feature("lngr3").selection().geom("geom1", 1);
    model.result("pg10").feature("lngr3").selection().set(1, 2, 3, 4, 5);
    model.result("pg10").feature().create("lngr4", "LineGraph");
    model.result("pg10").feature("lngr4").label("\u7279\u5f81\u80fd\u91cf");
    model.result("pg10").feature("lngr4").set("expr", "schr.Ei");
    model.result("pg10").feature("lngr4").set("unit", "eV");
    model.result("pg10").feature("lngr4").set("xdata", "expr");
    model.result("pg10").feature("lngr4").set("xdataexpr", "X");
    model.result("pg10").feature("lngr4").set("linestyle", "dotted");
    model.result("pg10").feature("lngr4").set("linecolor", "black");
    model.result("pg10").feature("lngr4").set("smooth", "internal");
    model.result("pg10").feature("lngr4").set("data", "parent");
    model.result("pg10").feature("lngr4").selection().geom("geom1", 1);
    model.result("pg10").feature("lngr4").selection().set(1, 2, 3, 4, 5);
    model.result().create("pg11", "PlotGroup1D");
    model.result("pg11").label("\u6982\u7387\u5bc6\u5ea6 (schr) 2");
    model.result("pg11").set("data", "dset5");
    model.result("pg11").set("showlooplevelinput", new String[]{"off", "off", "off"});
    model.result("pg11").feature().create("lngr1", "LineGraph");
    model.result("pg11").feature("lngr1").set("expr", "schr.Pr");
    model.result("pg11").feature("lngr1").set("xdata", "expr");
    model.result("pg11").feature("lngr1").set("xdataexpr", "X");
    model.result("pg11").feature("lngr1").set("smooth", "internal");
    model.result("pg11").feature("lngr1").set("data", "parent");
    model.result("pg11").feature("lngr1").selection().geom("geom1", 1);
    model.result("pg11").feature("lngr1").selection().set(1, 2, 3, 4, 5);
    model.result().create("pg12", "PlotGroup1D");
    model.result("pg12").label("\u52bf\u80fd (schr) 1");
    model.result("pg12").set("data", "dset5");
    model.result("pg12").set("showlooplevelinput", new String[]{"off", "off", "off"});
    model.result("pg12").feature().create("lngr1", "LineGraph");
    model.result("pg12").feature("lngr1").set("expr", "schr.V_psi");
    model.result("pg12").feature("lngr1").set("unit", "eV");
    model.result("pg12").feature("lngr1").set("xdata", "expr");
    model.result("pg12").feature("lngr1").set("xdataexpr", "X");
    model.result("pg12").feature("lngr1").set("smooth", "everywhere");
    model.result("pg12").feature("lngr1").set("data", "parent");
    model.result("pg12").feature("lngr1").selection().geom("geom1", 1);
    model.result("pg12").feature("lngr1").selection().set(1, 2, 3, 4, 5);
    model.result().create("pg13", "PlotGroup1D");
    model.result("pg13").label("\u6709\u6548\u8d28\u91cf (schr) 1");
    model.result("pg13").set("data", "dset5");
    model.result("pg13").set("showlooplevelinput", new String[]{"off", "off", "off"});
    model.result("pg13").feature().create("lngr1", "LineGraph");
    model.result("pg13").feature("lngr1").set("expr", "schr.meff_psiXX/me_const");
    model.result("pg13").feature("lngr1").set("xdata", "expr");
    model.result("pg13").feature("lngr1").set("xdataexpr", "X");
    model.result("pg13").feature("lngr1").set("smooth", "everywhere");
    model.result("pg13").feature("lngr1").set("data", "parent");
    model.result("pg13").feature("lngr1").selection().geom("geom1", 1);
    model.result("pg13").feature("lngr1").selection().set(1, 2, 3, 4, 5);
    model.result("pg9").run();
    model.result().remove("pg9");
    model.result("pg10").run();
    model.result("pg11").run();
    model.result().remove("pg11");
    model.result().remove("pg12");
    model.result().remove("pg13");
    model.result("pg10").run();
    model.result("pg10").label("\u5171\u632f\u96a7\u7a7f\u6c47\u603b\u56fe");
    model.result("pg10").set("titletype", "manual");
    model.result("pg10").set("title", "\u5171\u632f\u96a7\u7a7f\u6761\u4ef6\u7684\u6c47\u603b\u56fe");
    model.result("pg10").set("xlabelactive", true);
    model.result("pg10").set("xlabel", "X (nm)");
    model.result("pg10").set("ylabelactive", true);
    model.result("pg10").set("ylabel", "\u80fd\u91cf (eV)");
    model.result("pg10").set("showlegends", false);
    model.result("pg10").run();
    model.result().numerical("gev2").setIndex("expr", "real(schr.Ei)/E_anal-1", 2);
    model.result().numerical("gev2").setIndex("descr", "\u5b9e\u90e8\u8bef\u5dee", 2);
    model.result().numerical("gev2").setIndex("expr", "imag(schr.Ei)/E_anal", 3);
    model.result().numerical("gev2")
         .setIndex("descr", "\u865a\u90e8\u8bef\u5dee\uff08\u7cbe\u786e\u865a\u90e8\u4e3a\u96f6\uff09", 3);
    model.result().table().create("tbl2", "Table");
    model.result().table("tbl2").comments("\u7279\u5f81\u503c 1");
    model.result().numerical("gev2").set("table", "tbl2");
    model.result().numerical("gev2").setResult();

    model.component("comp1").physics("schr").prop("ModelProperties").set("E", "E0");
    model.component("comp1").physics("schr").create("open3", "OpenBoundary", 0);
    model.component("comp1").physics("schr").feature("open3")
         .label("\u7528\u4e8e\u900f\u5c04\u4e0e\u80fd\u91cf\u7814\u7a76\u7684\u5f00\u653e\u8fb9\u754c 3");
    model.component("comp1").physics("schr").feature("open3").selection().set(1);
    model.component("comp1").physics("schr").feature("open3").set("incomingWave", true);
    model.component("comp1").physics("schr").feature("open3").set("psi0", "psi0");

    model.study().create("std4");
    model.study("std4").create("stat", "Stationary");
    model.study("std4").feature("stat").setSolveFor("/physics/schr", true);
    model.study("std4").feature("stat").set("useadvanceddisable", true);
    model.study("std4").feature("stat").set("disabledphysics", new String[]{"schr/init2"});
    model.study("std4").feature("stat").set("useparam", true);
    model.study("std4").feature("stat").setIndex("pname", "lmbd0", 0);
    model.study("std4").feature("stat").setIndex("plistarr", "", 0);
    model.study("std4").feature("stat").setIndex("punit", "J", 0);
    model.study("std4").feature("stat").setIndex("pname", "lmbd0", 0);
    model.study("std4").feature("stat").setIndex("plistarr", "", 0);
    model.study("std4").feature("stat").setIndex("punit", "J", 0);
    model.study("std4").feature("stat").setIndex("pname", "E0", 0);
    model.study("std4").feature("stat")
         .setIndex("plistarr", "E1anal*(1-0.5*10^range(0,-0.2,-3)) E1anal E1anal+0.5*(E2anal-E1anal)*10^range(-3,0.2,-0.1) E2anal-0.5*(E2anal-E1anal)*10^range(0,-0.2,-3) E2anal  E2anal+0.5*(E3anal-E2anal)*10^range(-3,0.2,-0.1) E3anal-0.5*(E3anal-E2anal)*10^range(0,-0.2,-3) E3anal E3anal*(1+0.1*10^range(-3,0.2,0))", 0);
    model.study("std4").label("\u7814\u7a76 4 \u900f\u5c04 vs. \u80fd\u91cf");
    model.study("std4").createAutoSequences("all");

    model.sol("sol12").runAll();

    model.result().create("pg11", "PlotGroup1D");
    model.result("pg11").label("\u6ce2\u51fd\u6570 (schr) 1");
    model.result("pg11").set("data", "dset6");
    model.result("pg11").set("showlooplevelinput", new String[]{"off", "off", "off"});
    model.result("pg11").feature().create("lngr1", "LineGraph");
    model.result("pg11").feature("lngr1").label("\u5b9e\u90e8");
    model.result("pg11").feature("lngr1").set("expr", "psi");
    model.result("pg11").feature("lngr1").set("xdata", "expr");
    model.result("pg11").feature("lngr1").set("xdataexpr", "X");
    model.result("pg11").feature("lngr1").set("smooth", "internal");
    model.result("pg11").feature("lngr1").set("data", "parent");
    model.result("pg11").feature("lngr1").selection().geom("geom1", 1);
    model.result("pg11").feature("lngr1").selection().set(1, 2, 3, 4, 5);
    model.result("pg11").feature().create("lngr2", "LineGraph");
    model.result("pg11").feature("lngr2").label("\u865a\u90e8");
    model.result("pg11").feature("lngr2").set("expr", "imag(psi)");
    model.result("pg11").feature("lngr2").set("xdata", "expr");
    model.result("pg11").feature("lngr2").set("xdataexpr", "X");
    model.result("pg11").feature("lngr2").set("linestyle", "dashed");
    model.result("pg11").feature("lngr2").set("linecolor", "cyclereset");
    model.result("pg11").feature("lngr2").set("smooth", "internal");
    model.result("pg11").feature("lngr2").set("data", "parent");
    model.result("pg11").feature("lngr2").selection().geom("geom1", 1);
    model.result("pg11").feature("lngr2").selection().set(1, 2, 3, 4, 5);
    model.result().create("pg12", "PlotGroup1D");
    model.result("pg12").label("\u52bf\u80fd\u3001\u80fd\u91cf\u548c\u6ce2\u51fd\u6570 (schr)");
    model.result("pg12").set("data", "dset6");
    model.result("pg12").set("showlooplevelinput", new String[]{"off", "off", "off"});
    model.result("pg12").feature().create("lngr1", "LineGraph");
    model.result("pg12").feature("lngr1").label("\u52bf\u80fd");
    model.result("pg12").feature("lngr1").set("expr", "schr.V_psi");
    model.result("pg12").feature("lngr1").set("unit", "eV");
    model.result("pg12").feature("lngr1").set("xdata", "expr");
    model.result("pg12").feature("lngr1").set("xdataexpr", "X");
    model.result("pg12").feature("lngr1").set("linecolor", "black");
    model.result("pg12").feature("lngr1").set("smooth", "everywhere");
    model.result("pg12").feature("lngr1").set("data", "parent");
    model.result("pg12").feature("lngr1").selection().geom("geom1", 1);
    model.result("pg12").feature("lngr1").selection().set(1, 2, 3, 4, 5);
    model.result("pg12").feature().create("lngr2", "LineGraph");
    model.result("pg12").feature("lngr2").label("\u5b9e\u90e8");
    model.result("pg12").feature("lngr2").set("expr", "psi*0.1[eV]/schr.plot_fac+schr.E");
    model.result("pg12").feature("lngr2").set("unit", "eV");
    model.result("pg12").feature("lngr2").set("xdata", "expr");
    model.result("pg12").feature("lngr2").set("xdataexpr", "X");
    model.result("pg12").feature("lngr2").set("legend", true);
    model.result("pg12").feature("lngr2").set("smooth", "internal");
    model.result("pg12").feature("lngr2").set("data", "parent");
    model.result("pg12").feature("lngr2").selection().geom("geom1", 1);
    model.result("pg12").feature("lngr2").selection().set(1, 2, 3, 4, 5);
    model.result("pg12").feature().create("lngr3", "LineGraph");
    model.result("pg12").feature("lngr3").label("\u865a\u90e8");
    model.result("pg12").feature("lngr3").set("expr", "imag(psi)*0.1[eV]/schr.plot_fac+schr.E");
    model.result("pg12").feature("lngr3").set("unit", "eV");
    model.result("pg12").feature("lngr3").set("xdata", "expr");
    model.result("pg12").feature("lngr3").set("xdataexpr", "X");
    model.result("pg12").feature("lngr3").set("linestyle", "dashed");
    model.result("pg12").feature("lngr3").set("linecolor", "cyclereset");
    model.result("pg12").feature("lngr3").set("smooth", "internal");
    model.result("pg12").feature("lngr3").set("data", "parent");
    model.result("pg12").feature("lngr3").selection().geom("geom1", 1);
    model.result("pg12").feature("lngr3").selection().set(1, 2, 3, 4, 5);
    model.result("pg12").feature().create("lngr4", "LineGraph");
    model.result("pg12").feature("lngr4").label("\u80fd\u91cf");
    model.result("pg12").feature("lngr4").set("expr", "schr.E");
    model.result("pg12").feature("lngr4").set("unit", "eV");
    model.result("pg12").feature("lngr4").set("xdata", "expr");
    model.result("pg12").feature("lngr4").set("xdataexpr", "X");
    model.result("pg12").feature("lngr4").set("linestyle", "dotted");
    model.result("pg12").feature("lngr4").set("linecolor", "black");
    model.result("pg12").feature("lngr4").set("smooth", "internal");
    model.result("pg12").feature("lngr4").set("data", "parent");
    model.result("pg12").feature("lngr4").selection().geom("geom1", 1);
    model.result("pg12").feature("lngr4").selection().set(1, 2, 3, 4, 5);
    model.result().create("pg13", "PlotGroup1D");
    model.result("pg13").label("\u6982\u7387\u5bc6\u5ea6 (schr) 2");
    model.result("pg13").set("data", "dset6");
    model.result("pg13").set("showlooplevelinput", new String[]{"off", "off", "off"});
    model.result("pg13").feature().create("lngr1", "LineGraph");
    model.result("pg13").feature("lngr1").set("expr", "schr.Pr");
    model.result("pg13").feature("lngr1").set("xdata", "expr");
    model.result("pg13").feature("lngr1").set("xdataexpr", "X");
    model.result("pg13").feature("lngr1").set("smooth", "internal");
    model.result("pg13").feature("lngr1").set("data", "parent");
    model.result("pg13").feature("lngr1").selection().geom("geom1", 1);
    model.result("pg13").feature("lngr1").selection().set(1, 2, 3, 4, 5);
    model.result().create("pg14", "PlotGroup1D");
    model.result("pg14").label("\u52bf\u80fd (schr) 1");
    model.result("pg14").set("data", "dset6");
    model.result("pg14").set("showlooplevelinput", new String[]{"off", "off", "off"});
    model.result("pg14").feature().create("lngr1", "LineGraph");
    model.result("pg14").feature("lngr1").set("expr", "schr.V_psi");
    model.result("pg14").feature("lngr1").set("unit", "eV");
    model.result("pg14").feature("lngr1").set("xdata", "expr");
    model.result("pg14").feature("lngr1").set("xdataexpr", "X");
    model.result("pg14").feature("lngr1").set("smooth", "everywhere");
    model.result("pg14").feature("lngr1").set("data", "parent");
    model.result("pg14").feature("lngr1").selection().geom("geom1", 1);
    model.result("pg14").feature("lngr1").selection().set(1, 2, 3, 4, 5);
    model.result().create("pg15", "PlotGroup1D");
    model.result("pg15").label("\u6709\u6548\u8d28\u91cf (schr) 1");
    model.result("pg15").set("data", "dset6");
    model.result("pg15").set("showlooplevelinput", new String[]{"off", "off", "off"});
    model.result("pg15").feature().create("lngr1", "LineGraph");
    model.result("pg15").feature("lngr1").set("expr", "schr.meff_psiXX/me_const");
    model.result("pg15").feature("lngr1").set("xdata", "expr");
    model.result("pg15").feature("lngr1").set("xdataexpr", "X");
    model.result("pg15").feature("lngr1").set("smooth", "everywhere");
    model.result("pg15").feature("lngr1").set("data", "parent");
    model.result("pg15").feature("lngr1").selection().geom("geom1", 1);
    model.result("pg15").feature("lngr1").selection().set(1, 2, 3, 4, 5);
    model.result("pg11").run();
    model.result().remove("pg11");
    model.result("pg12").run();
    model.result("pg13").run();
    model.result().remove("pg13");
    model.result().remove("pg14");
    model.result().remove("pg15");
    model.result("pg12").run();
    model.result("pg12").label("\u900f\u5c04\u6c47\u603b\u56fe");
    model.result("pg12").setIndex("looplevelinput", "manualindices", 0);
    model.result("pg12").setIndex("looplevelindices", "17 33 49 65 81", 0);
    model.result("pg12").set("titletype", "manual");
    model.result("pg12").set("title", "\u6563\u5c04\u95ee\u9898\u6c47\u603b\u56fe");
    model.result("pg12").set("xlabelactive", true);
    model.result("pg12").set("xlabel", "X (nm)");
    model.result("pg12").set("ylabelactive", true);
    model.result("pg12").set("ylabel", "\u80fd\u91cf (eV)");
    model.result("pg12").set("showlegends", false);
    model.result("pg12").run();
    model.result().create("pg13", "PlotGroup1D");
    model.result("pg13").run();
    model.result("pg13").label("\u53cd\u5c04\u548c\u900f\u5c04 vs. \u80fd\u91cf");
    model.result("pg13").set("data", "dset6");
    model.result("pg13").create("glob1", "Global");
    model.result("pg13").feature("glob1").set("markerpos", "datapoints");
    model.result("pg13").feature("glob1").set("linewidth", "preference");
    model.result("pg13").feature("glob1").setIndex("expr", "abs(schr.open3.int(psi/schr.psiI)-1)^2", 0);
    model.result("pg13").feature("glob1").setIndex("descr", "\u53cd\u5c04\u7cfb\u6570", 0);
    model.result("pg13").feature("glob1").setIndex("expr", "abs(schr.open1.int(psi)/psi0)^2", 1);
    model.result("pg13").feature("glob1").setIndex("descr", "\u900f\u5c04\u7cfb\u6570", 1);
    model.result("pg13").feature("glob1").set("xdataparamunit", "eV");
    model.result("pg13").run();
    model.result("pg13").set("ylog", true);
    model.result("pg13").run();
    model.result("pg13").set("titletype", "manual");
    model.result("pg13")
         .set("title", "\u53cd\u5c04\u548c\u900f\u5c04\u7cfb\u6570\u4e0e\u80fd\u6e90\u7684\u5173\u7cfb");
    model.result("pg13").set("xlabelactive", true);
    model.result("pg13").set("xlabel", "\u80fd\u91cf (eV)");
    model.result("pg13").set("ylabelactive", true);
    model.result("pg13").set("ylabel", "\u53cd\u5c04\u548c\u900f\u5c04\u7cfb\u6570");
    model.result("pg13").set("legendpos", "lowerright");
    model.result().table().create("tbl3", "Table");
    model.result().table("tbl3").label("\u89e3\u6790\u900f\u5c04\u7cfb\u6570");
    model.result().table("tbl3").importData("double_barrier_1d_anal.csv");
    model.result().table("tbl3").setIndex("headers", "E0 (eV)", 0, 1);
    model.result().table("tbl3").setIndex("headers", "\u89e3\u6790\u900f\u5c04\u7cfb\u6570", 1, 1);
    model.result().create("pg14", "PlotGroup1D");
    model.result("pg14").set("data", "none");
    model.result("pg14").create("tblp1", "Table");
    model.result("pg14").feature("tblp1").set("source", "table");
    model.result("pg14").feature("tblp1").set("table", "tbl3");
    model.result("pg14").feature("tblp1").set("linewidth", "preference");
    model.result("pg14").feature("tblp1").set("markerpos", "datapoints");
    model.result("pg14").run();
    model.result("pg13").run();
    model.result("pg13").feature().copy("tblp1", "pg14/tblp1");
    model.result("pg13").run();
    model.result("pg14").run();
    model.result().remove("pg14");
    model.result("pg13").run();
    model.result("pg13").feature("tblp1").set("linestyle", "none");
    model.result("pg13").feature("tblp1").set("linemarker", "circle");
    model.result("pg13").feature("tblp1").set("legend", true);
    model.result("pg13").run();

    model.study("std1").feature("eigv").set("useadvanceddisable", true);
    model.study("std1").feature("eigv")
         .set("disabledphysics", new String[]{"schr/init2", "schr/open2", "schr/open3"});
    model.study("std2").feature("time").set("useadvanceddisable", true);
    model.study("std2").feature("time").set("disabledphysics", new String[]{"schr/open2", "schr/open3"});
    model.study("std3").feature("eigv").set("disabledphysics", new String[]{"schr/init2", "schr/open3"});

    model.title("\u53cc\u52bf\u5792 - \u4e00\u7ef4");

    model
         .description("\u53cc\u52bf\u5792\u7ed3\u6784\u4e4b\u6240\u4ee5\u53d7\u5230\u5173\u6ce8\uff0c\u662f\u7531\u4e8e\u8be5\u7ed3\u6784\u53ef\u7528\u4e8e\u5171\u632f\u96a7\u7a7f\u4e8c\u6781\u7ba1\u7b49\u534a\u5bfc\u4f53\u5668\u4ef6\u3002\n\n\u8fd9\u4e00\u9a8c\u8bc1\u793a\u4f8b\u6f14\u793a\u5728\u859b\u5b9a\u8c14\u65b9\u7a0b \u63a5\u53e3\u4e2d\u8bbe\u7f6e\u7b80\u5355\u7684\u4e00\u7ef4 GaAs/AlGaAs \u53cc\u52bf\u5792\u7ed3\u6784\uff0c\u5206\u6790\u4e86\u51c6\u675f\u7f1a\u6001\u53ca\u5176\u65f6\u95f4\u6f14\u5316\u3001\u5171\u632f\u96a7\u7a7f\u73b0\u8c61\u4ee5\u53ca\u900f\u5c04\u968f\u80fd\u91cf\u53d8\u5316\u7684\u60c5\u51b5\u3002\u5bf9\u4e8e\u51c6\u675f\u7f1a\u6001\u548c\u5171\u632f\u96a7\u7a7f\u6761\u4ef6\u4e0b\u8ba1\u7b97\u7684\u7279\u5f81\u80fd\u91cf\u4ee5\u53ca\u8ba1\u7b97\u7684\u900f\u5c04\u7cfb\u6570\uff0c\u6a21\u578b\u7ed3\u679c\u4e0e\u89e3\u6790\u7ed3\u679c\u975e\u5e38\u4e00\u81f4\u3002");

    model.label("double_barrier_1d.mph");

    return model;
  }

  public static void main(String[] args) {
    Model model = run();
    run2(model);
  }

}
