/*
 * sliding_wedge.java
 */

import com.comsol.model.*;
import com.comsol.model.util.*;

/** Model exported on Apr 30 2026, 13:26 by COMSOL 6.3.0.290. */
public class sliding_wedge {

  public static Model run() {
    Model model = ModelUtil.create("Model");

    model
         .modelPath("D:\\Program Files\\COMSOL\\COMSOL63\\Multiphysics\\applications\\Structural_Mechanics_Module\\Verification_Examples");

    model.component().create("comp1", true);

    model.component("comp1").geom().create("geom1", 2);

    model.component("comp1").mesh().create("mesh1");

    model.component("comp1").physics().create("solid", "SolidMechanics", "geom1");

    model.study().create("std1");
    model.study("std1").create("stat", "Stationary");
    model.study("std1").feature("stat").setSolveFor("/physics/solid", true);

    model.param().set("G", "3058[N]");
    model.param().descr("G", "\u91cd\u529b\u8f7d\u8377");
    model.param().set("F", "1500[N]");
    model.param().descr("F", "\u4f5c\u7528\u529b");
    model.param().set("K", "0[N/m]");
    model.param().descr("K", "\u5f39\u7c27\u521a\u5ea6");
    model.param().set("mu", "0");
    model.param().descr("mu", "\u6469\u64e6\u7cfb\u6570");
    model.param().set("para", "0");
    model.param().descr("para", "\u8ba1\u7b97\u53c2\u6570");

    model.component("comp1").geom("geom1").create("pol1", "Polygon");
    model.component("comp1").geom("geom1").feature("pol1").set("source", "table");
    model.component("comp1").geom("geom1").feature("pol1").setIndex("table", 0, 0, 0);
    model.component("comp1").geom("geom1").feature("pol1").setIndex("table", 0, 0, 1);
    model.component("comp1").geom("geom1").feature("pol1").setIndex("table", 6, 1, 0);
    model.component("comp1").geom("geom1").feature("pol1").setIndex("table", 0, 1, 1);
    model.component("comp1").geom("geom1").feature("pol1").setIndex("table", 6, 2, 0);
    model.component("comp1").geom("geom1").feature("pol1").setIndex("table", 1.3, 2, 1);
    model.component("comp1").geom("geom1").feature("pol1").setIndex("table", 0, 3, 0);
    model.component("comp1").geom("geom1").feature("pol1").setIndex("table", 0.7, 3, 1);
    model.component("comp1").geom("geom1").runPre("fin");
    model.component("comp1").geom("geom1").create("r1", "Rectangle");
    model.component("comp1").geom("geom1").feature("r1").set("size", new double[]{4, 1.2});
    model.component("comp1").geom("geom1").feature("r1").set("pos", new double[]{1, 0.8});
    model.component("comp1").geom("geom1").run("r1");
    model.component("comp1").geom("geom1").create("copy1", "Copy");
    model.component("comp1").geom("geom1").feature("copy1").selection("input").set("pol1");
    model.component("comp1").geom("geom1").run("copy1");
    model.component("comp1").geom("geom1").create("dif1", "Difference");
    model.component("comp1").geom("geom1").feature("dif1").selection("input").set("r1");
    model.component("comp1").geom("geom1").feature("dif1").selection("input2").set("copy1");
    model.component("comp1").geom("geom1").run("dif1");
    model.component("comp1").geom("geom1").feature("fin").set("action", "assembly");
    model.component("comp1").geom("geom1").feature("fin").set("pairtype", "contact");
    model.component("comp1").geom("geom1").run("fin");

    model.component("comp1").material().create("mat1", "Common");
    model.component("comp1").material("mat1").propertyGroup()
         .create("Enu", "Enu", "Young's_modulus_and_Poisson's_ratio");
    model.component("comp1").material("mat1").propertyGroup("Enu").set("E", new String[]{"206[GPa]"});
    model.component("comp1").material("mat1").propertyGroup("Enu").set("nu", new String[]{"0.3"});
    model.component("comp1").material("mat1").propertyGroup("def").set("density", new String[]{"6000[kg/m^3]"});

    model.component("comp1").physics("solid").feature("dcnt1").create("fric1", "Friction", 1);
    model.component("comp1").physics("solid").feature("dcnt1").feature("fric1").set("mu_fric", "mu");
    model.component("comp1").physics("solid").create("bl1", "BodyLoad", 2);
    model.component("comp1").physics("solid").feature("bl1").selection().set(2);
    model.component("comp1").physics("solid").feature("bl1").set("forceType", "TotalForce");
    model.component("comp1").physics("solid").feature("bl1").set("force", new String[]{"0", "-G*para", "0"});
    model.component("comp1").physics("solid").create("spf1", "SpringFoundation1", 1);
    model.component("comp1").physics("solid").feature("spf1").selection().set(5);
    model.component("comp1").physics("solid").feature("spf1").set("SpringType", "kTot");
    model.component("comp1").physics("solid").feature("spf1")
         .set("kTot", new String[]{"K", "0", "0", "0", "0", "0", "0", "0", "K"});
    model.component("comp1").physics("solid").create("bndl1", "BoundaryLoad", 1);
    model.component("comp1").physics("solid").feature("bndl1").selection().set(5);
    model.component("comp1").physics("solid").feature("bndl1").set("forceType", "TotalForce");
    model.component("comp1").physics("solid").feature("bndl1").set("force", new String[]{"F*para", "0", "0"});
    model.component("comp1").physics("solid").create("fix1", "Fixed", 1);
    model.component("comp1").physics("solid").feature("fix1").selection().set(2);

    model.component("comp1").mesh("mesh1").create("map1", "Map");
    model.component("comp1").mesh("mesh1").feature("map1").create("dis1", "Distribution");
    model.component("comp1").mesh("mesh1").feature("map1").feature("dis1").selection().set(1, 5);
    model.component("comp1").mesh("mesh1").feature("map1").feature("dis1").set("numelem", 10);
    model.component("comp1").mesh("mesh1").feature("map1").create("dis2", "Distribution");
    model.component("comp1").mesh("mesh1").feature("map1").feature("dis2").selection().set(2);
    model.component("comp1").mesh("mesh1").feature("map1").feature("dis2").set("numelem", 60);
    model.component("comp1").mesh("mesh1").feature("map1").create("dis3", "Distribution");
    model.component("comp1").mesh("mesh1").feature("map1").feature("dis3").selection().set(7);
    model.component("comp1").mesh("mesh1").feature("map1").feature("dis3").set("numelem", 40);
    model.component("comp1").mesh("mesh1").run();

    model.study("std1").create("param", "Parametric");
    model.study("std1").feature("param").setIndex("pname", "G", 0);
    model.study("std1").feature("param").setIndex("plistarr", "", 0);
    model.study("std1").feature("param").setIndex("punit", "N", 0);
    model.study("std1").feature("param").setIndex("pname", "G", 0);
    model.study("std1").feature("param").setIndex("plistarr", "", 0);
    model.study("std1").feature("param").setIndex("punit", "N", 0);
    model.study("std1").feature("param").setIndex("pname", "mu", 0);
    model.study("std1").feature("param").setIndex("plistarr", "0 0.1 0.2", 0);
    model.study("std1").feature("param").setIndex("pname", "G", 1);
    model.study("std1").feature("param").setIndex("plistarr", "", 1);
    model.study("std1").feature("param").setIndex("punit", "N", 1);
    model.study("std1").feature("param").setIndex("pname", "G", 1);
    model.study("std1").feature("param").setIndex("plistarr", "", 1);
    model.study("std1").feature("param").setIndex("punit", "N", 1);
    model.study("std1").feature("param").setIndex("pname", "K", 1);
    model.study("std1").feature("param").setIndex("plistarr", "1194 882 563.9", 1);
    model.study("std1").feature("stat").set("useparam", true);
    model.study("std1").feature("stat").setIndex("pname", "G", 0);
    model.study("std1").feature("stat").setIndex("plistarr", "", 0);
    model.study("std1").feature("stat").setIndex("punit", "N", 0);
    model.study("std1").feature("stat").setIndex("pname", "G", 0);
    model.study("std1").feature("stat").setIndex("plistarr", "", 0);
    model.study("std1").feature("stat").setIndex("punit", "N", 0);
    model.study("std1").feature("stat").setIndex("pname", "para", 0);
    model.study("std1").feature("stat").setIndex("plistarr", "1e-3 1", 0);
    model.study("std1").feature("stat").set("usestol", true);
    model.study("std1").feature("stat").set("stol", "1e-6");
    model.study("std1").showAutoSequences("all");

    model.sol("sol1").feature("s1").feature("p1").set("paramtuning", true);
    model.sol("sol1").feature("s1").feature("p1").set("pinitstep", "1e-2");
    model.sol("sol1").feature("s1").feature("p1").set("pminstep", "1e-6");
    model.sol("sol1").feature("s1").feature("p1").set("porder", "linear");
    model.sol("sol1").feature("s1").feature("fc1").set("dtech", "const");

    model.study("std1").label("\u7814\u7a76 1\uff1a\u7f5a\u51fd\u6570");
    model.study("std1").createAutoSequences("all");

    model.sol().create("sol2");
    model.sol("sol2").study("std1");
    model.sol("sol2").label("\u53c2\u6570\u5316\u89e3 1");

    model.batch("p1").feature("so1").set("psol", "sol2");
    model.batch("p1").run("compute");

    model.result().create("pg1", "PlotGroup2D");
    model.result("pg1").set("data", "dset2");
    model.result("pg1").setIndex("looplevel", 2, 0);
    model.result("pg1").setIndex("looplevel", 3, 1);
    model.result("pg1").label("\u5e94\u529b (solid)");
    model.result("pg1").set("frametype", "spatial");
    model.result("pg1").create("surf1", "Surface");
    model.result("pg1").feature("surf1").set("expr", new String[]{"solid.misesGp"});
    model.result("pg1").feature("surf1").set("threshold", "manual");
    model.result("pg1").feature("surf1").set("thresholdvalue", 0.2);
    model.result("pg1").feature("surf1").set("colortable", "Rainbow");
    model.result("pg1").feature("surf1").set("colortabletrans", "none");
    model.result("pg1").feature("surf1").set("colorscalemode", "linear");
    model.result("pg1").feature("surf1").set("resolution", "normal");
    model.result("pg1").feature("surf1").set("colortable", "Prism");
    model.result("pg1").feature("surf1").create("def", "Deform");
    model.result("pg1").feature("surf1").feature("def").set("scaleactive", true);
    model.result("pg1").feature("surf1").feature("def").set("scale", "1");
    model.result("pg1").feature("surf1").feature("def").set("expr", new String[]{"u", "v"});
    model.result("pg1").feature("surf1").feature("def").set("descr", "\u4f4d\u79fb\u573a");
    model.result("pg1").run();
    model.result("pg1").label("\u4f4d\u79fb\uff1a\u7f5a\u51fd\u6570");
    model.result("pg1").run();
    model.result("pg1").feature("surf1").set("expr", "u");
    model.result("pg1").feature("surf1").set("descr", "\u4f4d\u79fb\u573a\uff0cX \u5206\u91cf");
    model.result("pg1").feature("surf1").set("colortable", "RainbowLight");
    model.result("pg1").run();
    model.result().create("pg2", "PlotGroup2D");
    model.result("pg2").set("data", "dset2");
    model.result("pg2").setIndex("looplevel", 2, 0);
    model.result("pg2").setIndex("looplevel", 3, 1);
    model.result("pg2").label("\u63a5\u89e6\u529b (solid)");
    model.result("pg2").set("showlegends", true);
    model.result("pg2").set("titletype", "label");
    model.result("pg2").set("frametype", "spatial");
    model.result("pg2").set("showlegendsunit", true);
    model.result("pg2").create("surf1", "Surface");
    model.result("pg2").feature("surf1").set("expr", new String[]{"1"});
    model.result("pg2").feature("surf1").label("\u7070\u8272\u8868\u9762");
    model.result("pg2").feature("surf1").set("coloring", "uniform");
    model.result("pg2").feature("surf1").set("color", "gray");
    model.result("pg2").feature("surf1").create("def", "Deform");
    model.result("pg2").feature("surf1").feature("def").set("expr", new String[]{"u", "v"});
    model.result("pg2").feature("surf1").feature("def").set("descr", "\u4f4d\u79fb\u573a");
    model.result("pg2").feature("surf1").feature("def").set("scaleactive", true);
    model.result("pg2").feature("surf1").feature("def").set("scale", 1);
    model.result("pg2").feature("surf1").create("sel1", "Selection");
    model.result("pg2").feature("surf1").feature("sel1").selection().geom("geom1", 2);
    model.result("pg2").feature("surf1").feature("sel1").selection().set(1, 2);
    model.result("pg2").create("arwl1", "ArrowLine");
    model.result("pg2").feature("arwl1").set("arrowbase", "head");
    model.result("pg2").feature("arwl1").set("expr", new String[]{"solid.dcnt1.Tnx", "solid.dcnt1.Tny"});
    model.result("pg2").feature("arwl1").set("placement", "gausspoints");
    model.result("pg2").feature("arwl1").set("gporder", 4);
    model.result("pg2").feature("arwl1").label("\u63a5\u89e6 1, \u538b\u529b");
    model.result("pg2").feature("arwl1").set("inheritplot", "none");
    model.result("pg2").feature("arwl1").set("color", "green");
    model.result("pg2").feature("arwl1").create("col", "Color");
    model.result("pg2").feature("arwl1").feature("col").set("colortable", "Rainbow");
    model.result("pg2").feature("arwl1").feature("col").set("colortabletrans", "none");
    model.result("pg2").feature("arwl1").feature("col").set("colorscalemode", "linear");
    model.result("pg2").feature("arwl1").feature("col").set("colordata", "arrowlength");
    model.result("pg2").feature("arwl1").feature("col").set("coloring", "gradient");
    model.result("pg2").feature("arwl1").feature("col").set("topcolor", "green");
    model.result("pg2").feature("arwl1").feature("col").set("bottomcolor", "custom");
    model.result("pg2").feature("arwl1").feature("col")
         .set("custombottomcolor", new double[]{0.509804, 0.54902, 0.509804});
    model.result("pg2").feature("arwl1").create("def", "Deform");
    model.result("pg2").feature("arwl1").feature("def").set("expr", new String[]{"u", "v"});
    model.result("pg2").feature("arwl1").feature("def").set("descr", "\u4f4d\u79fb\u573a");
    model.result("pg2").feature("arwl1").feature("def").set("scaleactive", true);
    model.result("pg2").feature("arwl1").feature("def").set("scale", 1);
    model.result("pg2").feature().move("surf1", 1);
    model.result("pg2").set("legendpos", "rightdouble");
    model.result("pg2").create("arwl2", "ArrowLine");
    model.result("pg2").feature("arwl2").set("arrowbase", "tail");
    model.result("pg2").feature("arwl2").set("expr", new String[]{"solid.dcnt1.Ttx", "solid.dcnt1.Tty"});
    model.result("pg2").feature("arwl2").set("placement", "gausspoints");
    model.result("pg2").feature("arwl2").set("gporder", 4);
    model.result("pg2").feature("arwl2").label("\u63a5\u89e6 1, \u6469\u64e6\u529b");
    model.result("pg2").feature("arwl2").set("inheritplot", "none");
    model.result("pg2").feature("arwl2").set("color", "magenta");
    model.result("pg2").feature("arwl2").create("col", "Color");
    model.result("pg2").feature("arwl2").feature("col").set("colortable", "Rainbow");
    model.result("pg2").feature("arwl2").feature("col").set("colortabletrans", "none");
    model.result("pg2").feature("arwl2").feature("col").set("colorscalemode", "linear");
    model.result("pg2").feature("arwl2").feature("col").set("colordata", "arrowlength");
    model.result("pg2").feature("arwl2").feature("col").set("coloring", "gradient");
    model.result("pg2").feature("arwl2").feature("col").set("topcolor", "magenta");
    model.result("pg2").feature("arwl2").feature("col").set("bottomcolor", "custom");
    model.result("pg2").feature("arwl2").feature("col")
         .set("custombottomcolor", new double[]{0.54902, 0.509804, 0.54902});
    model.result("pg2").feature("arwl2").create("def", "Deform");
    model.result("pg2").feature("arwl2").feature("def").set("expr", new String[]{"u", "v"});
    model.result("pg2").feature("arwl2").feature("def").set("descr", "\u4f4d\u79fb\u573a");
    model.result("pg2").feature("arwl2").feature("def").set("scaleactive", true);
    model.result("pg2").feature("arwl2").feature("def").set("scale", 1);
    model.result("pg2").feature().move("surf1", 2);
    model.result("pg2").label("\u63a5\u89e6\u529b (solid)");
    model.result().create("pg3", "PlotGroup2D");
    model.result("pg3").set("data", "dset2");
    model.result("pg3").setIndex("looplevel", 2, 0);
    model.result("pg3").setIndex("looplevel", 3, 1);
    model.result("pg3").label("\u4f53\u79ef\u8f7d\u8377 (solid)");
    model.result("pg3").set("showlegends", true);
    model.result("pg3").set("titletype", "label");
    model.result("pg3").set("frametype", "spatial");
    model.result("pg3").set("showlegendsunit", true);
    model.result("pg3").create("surf1", "Surface");
    model.result("pg3").feature("surf1").set("expr", new String[]{"1"});
    model.result("pg3").feature("surf1").label("\u7070\u8272\u8868\u9762");
    model.result("pg3").feature("surf1").set("coloring", "uniform");
    model.result("pg3").feature("surf1").set("color", "gray");
    model.result("pg3").feature("surf1").set("inheritcolor", false);
    model.result("pg3").feature("surf1").set("inheritrange", false);
    model.result("pg3").feature("surf1").set("inheritheightscale", false);
    model.result("pg3").feature("surf1").create("def", "Deform");
    model.result("pg3").feature("surf1").feature("def").set("expr", new String[]{"u", "v"});
    model.result("pg3").feature("surf1").feature("def").set("descr", "\u4f4d\u79fb\u573a");
    model.result("pg3").feature("surf1").feature("def").set("scaleactive", true);
    model.result("pg3").feature("surf1").feature("def").set("scale", 1);
    model.result("pg3").feature("surf1").create("sel1", "Selection");
    model.result("pg3").feature("surf1").feature("sel1").selection().geom("geom1", 2);
    model.result("pg3").feature("surf1").feature("sel1").selection().set(1, 2);
    model.result("pg3").create("arws1", "ArrowSurface");
    model.result("pg3").feature("arws1").set("expr", new String[]{"solid.bl1.fvx", "solid.bl1.fvy"});
    model.result("pg3").feature("arws1").set("placement", "gausspoints");
    model.result("pg3").feature("arws1").set("arrowbase", "tail");
    model.result("pg3").feature("arws1").label("\u4f53\u8f7d\u8377 1");
    model.result("pg3").feature("arws1").set("inheritplot", "none");
    model.result("pg3").feature("arws1").create("col", "Color");
    model.result("pg3").feature("arws1").feature("col").set("colortable", "Rainbow");
    model.result("pg3").feature("arws1").feature("col").set("colortabletrans", "none");
    model.result("pg3").feature("arws1").feature("col").set("colorscalemode", "linear");
    model.result("pg3").feature("arws1").feature("col").set("colordata", "arrowlength");
    model.result("pg3").feature("arws1").feature("col").set("coloring", "gradient");
    model.result("pg3").feature("arws1").feature("col").set("topcolor", "red");
    model.result("pg3").feature("arws1").feature("col").set("bottomcolor", "custom");
    model.result("pg3").feature("arws1").feature("col")
         .set("custombottomcolor", new double[]{0.5882353186607361, 0.5137255191802979, 0.5176470875740051});
    model.result("pg3").feature("arws1").set("color", "magenta");
    model.result("pg3").feature("arws1").create("def", "Deform");
    model.result("pg3").feature("arws1").feature("def").set("expr", new String[]{"u", "v"});
    model.result("pg3").feature("arws1").feature("def").set("descr", "\u4f4d\u79fb\u573a");
    model.result("pg3").feature("arws1").feature("def").set("scaleactive", true);
    model.result("pg3").feature("arws1").feature("def").set("scale", 1);
    model.result("pg3").feature().move("surf1", 1);
    model.result("pg3").label("\u4f53\u79ef\u8f7d\u8377 (solid)");

    model.nodeGroup().create("dset2solidlgrp", "Results");
    model.nodeGroup("dset2solidlgrp").label("\u5916\u52a0\u8f7d\u8377 (solid)");
    model.nodeGroup("dset2solidlgrp").set("type", "plotgroup");
    model.nodeGroup("dset2solidlgrp").placeAfter("plotgroup", "pg3");
    model.nodeGroup("dset2solidlgrp").label("\u5916\u52a0\u8f7d\u8377 (solid)");
    model.nodeGroup("dset2solidlgrp").placeAfter("plotgroup", "pg3");

    model.result().create("pg4", "PlotGroup2D");
    model.result("pg4").set("data", "dset2");
    model.result("pg4").setIndex("looplevel", 2, 0);
    model.result("pg4").setIndex("looplevel", 3, 1);
    model.result("pg4").label("\u8fb9\u754c\u8f7d\u8377 (solid)");
    model.result("pg4").set("showlegends", true);
    model.result("pg4").set("titletype", "label");
    model.result("pg4").set("frametype", "spatial");
    model.result("pg4").set("showlegendsunit", true);
    model.result("pg4").create("surf1", "Surface");
    model.result("pg4").feature("surf1").set("expr", new String[]{"1"});
    model.result("pg4").feature("surf1").label("\u7070\u8272\u8868\u9762");
    model.result("pg4").feature("surf1").set("coloring", "uniform");
    model.result("pg4").feature("surf1").set("color", "gray");
    model.result("pg4").feature("surf1").set("inheritcolor", false);
    model.result("pg4").feature("surf1").set("inheritrange", false);
    model.result("pg4").feature("surf1").set("inheritheightscale", false);
    model.result("pg4").feature("surf1").create("def", "Deform");
    model.result("pg4").feature("surf1").feature("def").set("expr", new String[]{"u", "v"});
    model.result("pg4").feature("surf1").feature("def").set("descr", "\u4f4d\u79fb\u573a");
    model.result("pg4").feature("surf1").feature("def").set("scaleactive", true);
    model.result("pg4").feature("surf1").feature("def").set("scale", 1);
    model.result("pg4").feature("surf1").create("sel1", "Selection");
    model.result("pg4").feature("surf1").feature("sel1").selection().geom("geom1", 2);
    model.result("pg4").feature("surf1").feature("sel1").selection().set(1, 2);
    model.result("pg4").create("arwl1", "ArrowLine");
    model.result("pg4").feature("arwl1").set("expr", new String[]{"solid.bndl1.fax", "solid.bndl1.fay"});
    model.result("pg4").feature("arwl1").set("placement", "gausspoints");
    model.result("pg4").feature("arwl1").set("arrowbase", "tail");
    model.result("pg4").feature("arwl1").label("\u8fb9\u754c\u8f7d\u8377 1");
    model.result("pg4").feature("arwl1").set("inheritplot", "none");
    model.result("pg4").feature("arwl1").create("col", "Color");
    model.result("pg4").feature("arwl1").feature("col").set("colortable", "Rainbow");
    model.result("pg4").feature("arwl1").feature("col").set("colortabletrans", "none");
    model.result("pg4").feature("arwl1").feature("col").set("colorscalemode", "linear");
    model.result("pg4").feature("arwl1").feature("col").set("colordata", "arrowlength");
    model.result("pg4").feature("arwl1").feature("col").set("coloring", "gradient");
    model.result("pg4").feature("arwl1").feature("col").set("topcolor", "red");
    model.result("pg4").feature("arwl1").feature("col").set("bottomcolor", "custom");
    model.result("pg4").feature("arwl1").feature("col")
         .set("custombottomcolor", new double[]{0.5882353186607361, 0.5137255191802979, 0.5176470875740051});
    model.result("pg4").feature("arwl1").set("color", "red");
    model.result("pg4").feature("arwl1").create("def", "Deform");
    model.result("pg4").feature("arwl1").feature("def").set("expr", new String[]{"u", "v"});
    model.result("pg4").feature("arwl1").feature("def").set("descr", "\u4f4d\u79fb\u573a");
    model.result("pg4").feature("arwl1").feature("def").set("scaleactive", true);
    model.result("pg4").feature("arwl1").feature("def").set("scale", 1);
    model.result("pg4").feature().move("surf1", 1);
    model.result("pg4").label("\u8fb9\u754c\u8f7d\u8377 (solid)");

    model.nodeGroup("dset2solidlgrp").add("plotgroup", "pg3");
    model.nodeGroup("dset2solidlgrp").add("plotgroup", "pg4");

    model.result("pg2").run();
    model.result("pg2").label("\u63a5\u89e6\uff1a\u7f5a\u51fd\u6570");
    model.result("pg2").run();
    model.result("pg2").run();
    model.result().numerical().create("pev1", "EvalPoint");
    model.result().numerical("pev1").label("\u70b9\u8ba1\u7b97\uff1a\u7f5a\u51fd\u6570");
    model.result().numerical("pev1").set("data", "dset2");
    model.result().numerical("pev1").setIndex("looplevelinput", "last", 0);
    model.result().numerical("pev1").set("tablecols", "level2");
    model.result().numerical("pev1").selection().set(8);
    model.result().numerical("pev1").set("expr", new String[]{"u"});
    model.result().numerical("pev1").set("descr", new String[]{"\u4f4d\u79fb\u573a\uff0cX \u5206\u91cf"});
    model.result().numerical("pev1").set("unit", new String[]{"m"});
    model.result().table().create("tbl1", "Table");
    model.result().table("tbl1").comments("\u70b9\u8ba1\u7b97\uff1a\u7f5a\u51fd\u6570");
    model.result().numerical("pev1").set("table", "tbl1");
    model.result().numerical("pev1").setResult();

    model.component("comp1").physics("solid").feature().duplicate("dcnt2", "dcnt1");
    model.component("comp1").physics("solid").feature("dcnt2").set("pairSelection", "list");
    model.component("comp1").physics("solid").feature("dcnt2").set("pairs", new String[]{"ap1"});
    model.component("comp1").physics("solid").feature("dcnt2").set("ContactMethodCtrl", "AugmentedLagrange");
    model.component("comp1").physics("solid").feature().duplicate("dcnt3", "dcnt2");
    model.component("comp1").physics("solid").feature("dcnt3").set("SolutionMethod", "coupled");

    model.study().create("std2");
    model.study("std2").create("stat", "Stationary");
    model.study("std2").feature("stat").setSolveFor("/physics/solid", true);
    model.study("std2").create("param", "Parametric");
    model.study("std2").feature("param").setIndex("pname", "G", 0);
    model.study("std2").feature("param").setIndex("plistarr", "", 0);
    model.study("std2").feature("param").setIndex("punit", "N", 0);
    model.study("std2").feature("param").setIndex("pname", "G", 0);
    model.study("std2").feature("param").setIndex("plistarr", "", 0);
    model.study("std2").feature("param").setIndex("punit", "N", 0);
    model.study("std2").feature("param").setIndex("pname", "mu", 0);
    model.study("std2").feature("param").setIndex("plistarr", "0 0.1 0.2", 0);
    model.study("std2").feature("param").setIndex("pname", "G", 1);
    model.study("std2").feature("param").setIndex("plistarr", "", 1);
    model.study("std2").feature("param").setIndex("punit", "N", 1);
    model.study("std2").feature("param").setIndex("pname", "G", 1);
    model.study("std2").feature("param").setIndex("plistarr", "", 1);
    model.study("std2").feature("param").setIndex("punit", "N", 1);
    model.study("std2").feature("param").setIndex("pname", "K", 1);
    model.study("std2").feature("param").setIndex("plistarr", "1194 882 563.9", 1);
    model.study("std2").feature("stat").set("useadvanceddisable", true);
    model.study("std2").feature("stat").set("disabledphysics", new String[]{"solid/dcnt3"});
    model.study("std2").feature("stat").set("useparam", true);
    model.study("std2").feature("stat").setIndex("pname", "G", 0);
    model.study("std2").feature("stat").setIndex("plistarr", "", 0);
    model.study("std2").feature("stat").setIndex("punit", "N", 0);
    model.study("std2").feature("stat").setIndex("pname", "G", 0);
    model.study("std2").feature("stat").setIndex("plistarr", "", 0);
    model.study("std2").feature("stat").setIndex("punit", "N", 0);
    model.study("std2").feature("stat").setIndex("pname", "para", 0);
    model.study("std2").feature("stat").setIndex("plistarr", "1e-3 1", 0);
    model.study("std2").label("\u7814\u7a76 2\uff1a\u589e\u5e7f\u62c9\u683c\u6717\u65e5\uff0c\u5206\u79bb");
    model.study("std2").showAutoSequences("all");

    model.sol("sol6").feature("v1").feature("comp1_solid_Tt_ap1").set("scaleval", 100);
    model.sol("sol6").feature("v1").feature("comp1_solid_Tn_ap1").set("scaleval", 1000);
    model.sol("sol6").feature("s1").feature("p1").set("paramtuning", true);
    model.sol("sol6").feature("s1").feature("p1").set("pinitstep", 0.1);
    model.sol("sol6").feature("s1").feature("p1").set("pmaxstep", 1);

    model.study("std2").createAutoSequences("all");

    model.sol().create("sol7");
    model.sol("sol7").study("std2");
    model.sol("sol7").label("\u53c2\u6570\u5316\u89e3 2");

    model.batch("p2").feature("so1").set("psol", "sol7");
    model.batch("p2").run("compute");

    model.result().create("pg5", "PlotGroup2D");
    model.result("pg5").set("data", "dset4");
    model.result("pg5").setIndex("looplevel", 2, 0);
    model.result("pg5").setIndex("looplevel", 3, 1);
    model.result("pg5").label("\u5e94\u529b (solid)");
    model.result("pg5").set("frametype", "spatial");
    model.result("pg5").create("surf1", "Surface");
    model.result("pg5").feature("surf1").set("expr", new String[]{"solid.misesGp"});
    model.result("pg5").feature("surf1").set("threshold", "manual");
    model.result("pg5").feature("surf1").set("thresholdvalue", 0.2);
    model.result("pg5").feature("surf1").set("colortable", "Rainbow");
    model.result("pg5").feature("surf1").set("colortabletrans", "none");
    model.result("pg5").feature("surf1").set("colorscalemode", "linear");
    model.result("pg5").feature("surf1").set("resolution", "normal");
    model.result("pg5").feature("surf1").set("colortable", "Prism");
    model.result("pg5").feature("surf1").create("def", "Deform");
    model.result("pg5").feature("surf1").feature("def").set("scaleactive", true);
    model.result("pg5").feature("surf1").feature("def").set("scale", "1");
    model.result("pg5").feature("surf1").feature("def").set("expr", new String[]{"u", "v"});
    model.result("pg5").feature("surf1").feature("def").set("descr", "\u4f4d\u79fb\u573a");
    model.result("pg5").run();

    model.study().create("std3");
    model.study("std3").create("stat", "Stationary");
    model.study("std3").feature("stat").setSolveFor("/physics/solid", true);
    model.study("std3").create("param", "Parametric");
    model.study("std3").feature("param").setIndex("pname", "G", 0);
    model.study("std3").feature("param").setIndex("plistarr", "", 0);
    model.study("std3").feature("param").setIndex("punit", "N", 0);
    model.study("std3").feature("param").setIndex("pname", "G", 0);
    model.study("std3").feature("param").setIndex("plistarr", "", 0);
    model.study("std3").feature("param").setIndex("punit", "N", 0);
    model.study("std3").feature("param").setIndex("pname", "mu", 0);
    model.study("std3").feature("param").setIndex("plistarr", "0 0.1 0.2", 0);
    model.study("std3").feature("param").setIndex("pname", "G", 1);
    model.study("std3").feature("param").setIndex("plistarr", "", 1);
    model.study("std3").feature("param").setIndex("punit", "N", 1);
    model.study("std3").feature("param").setIndex("pname", "G", 1);
    model.study("std3").feature("param").setIndex("plistarr", "", 1);
    model.study("std3").feature("param").setIndex("punit", "N", 1);
    model.study("std3").feature("param").setIndex("pname", "K", 1);
    model.study("std3").feature("param").setIndex("plistarr", "1194 882 563.9", 1);
    model.study("std3").feature("stat").set("useparam", true);
    model.study("std3").feature("stat").setIndex("pname", "G", 0);
    model.study("std3").feature("stat").setIndex("plistarr", "", 0);
    model.study("std3").feature("stat").setIndex("punit", "N", 0);
    model.study("std3").feature("stat").setIndex("pname", "G", 0);
    model.study("std3").feature("stat").setIndex("plistarr", "", 0);
    model.study("std3").feature("stat").setIndex("punit", "N", 0);
    model.study("std3").feature("stat").setIndex("pname", "para", 0);
    model.study("std3").feature("stat").setIndex("plistarr", "1e-3 1", 0);
    model.study("std3").label("\u7814\u7a76 3\uff1a\u589e\u5e7f\u62c9\u683c\u6717\u65e5\uff0c\u8026\u5408");
    model.study("std3").showAutoSequences("all");

    model.sol("sol11").feature("v1").feature("comp1_solid_Tt_ap1").set("scaleval", 100);
    model.sol("sol11").feature("v1").feature("comp1_solid_Tn_ap1").set("scaleval", 1000);
    model.sol("sol11").feature("s1").feature("p1").set("paramtuning", true);
    model.sol("sol11").feature("s1").feature("p1").set("pinitstep", 0.1);

    return model;
  }

  public static Model run2(Model model) {
    model.sol("sol11").feature("s1").feature("p1").set("pmaxstep", 1);
    model.sol("sol11").feature("s1").feature("fc1").set("dtech", "const");

    model.study("std3").createAutoSequences("all");

    model.sol().create("sol12");
    model.sol("sol12").study("std3");
    model.sol("sol12").label("\u53c2\u6570\u5316\u89e3 3");

    model.batch("p3").feature("so1").set("psol", "sol12");
    model.batch("p3").run("compute");

    model.result().create("pg6", "PlotGroup2D");
    model.result("pg6").set("data", "dset6");
    model.result("pg6").setIndex("looplevel", 2, 0);
    model.result("pg6").setIndex("looplevel", 3, 1);
    model.result("pg6").label("\u5e94\u529b (solid) 1");
    model.result("pg6").set("frametype", "spatial");
    model.result("pg6").create("surf1", "Surface");
    model.result("pg6").feature("surf1").set("expr", new String[]{"solid.misesGp"});
    model.result("pg6").feature("surf1").set("threshold", "manual");
    model.result("pg6").feature("surf1").set("thresholdvalue", 0.2);
    model.result("pg6").feature("surf1").set("colortable", "Rainbow");
    model.result("pg6").feature("surf1").set("colortabletrans", "none");
    model.result("pg6").feature("surf1").set("colorscalemode", "linear");
    model.result("pg6").feature("surf1").set("resolution", "normal");
    model.result("pg6").feature("surf1").set("colortable", "Prism");
    model.result("pg6").feature("surf1").create("def", "Deform");
    model.result("pg6").feature("surf1").feature("def").set("scaleactive", true);
    model.result("pg6").feature("surf1").feature("def").set("scale", "1");
    model.result("pg6").feature("surf1").feature("def").set("expr", new String[]{"u", "v"});
    model.result("pg6").feature("surf1").feature("def").set("descr", "\u4f4d\u79fb\u573a");
    model.result("pg6").run();
    model.result("pg5").run();
    model.result("pg5").label("\u4f4d\u79fb\uff1a\u589e\u5e7f\u62c9\u683c\u6717\u65e5\uff0c\u5206\u79bb");
    model.result("pg5").run();
    model.result("pg5").feature("surf1").set("expr", "u");
    model.result("pg5").feature("surf1").set("descr", "\u4f4d\u79fb\u573a\uff0cX \u5206\u91cf");
    model.result("pg5").feature("surf1").set("colortable", "RainbowLight");
    model.result("pg5").run();
    model.result().create("pg7", "PlotGroup2D");
    model.result("pg7").set("data", "dset4");
    model.result("pg7").setIndex("looplevel", 2, 0);
    model.result("pg7").setIndex("looplevel", 3, 1);
    model.result("pg7").label("\u63a5\u89e6\u529b (solid)");
    model.result("pg7").set("showlegends", true);
    model.result("pg7").set("titletype", "label");
    model.result("pg7").set("frametype", "spatial");
    model.result("pg7").set("showlegendsunit", true);
    model.result("pg7").create("surf1", "Surface");
    model.result("pg7").feature("surf1").set("expr", new String[]{"1"});
    model.result("pg7").feature("surf1").label("\u7070\u8272\u8868\u9762");
    model.result("pg7").feature("surf1").set("coloring", "uniform");
    model.result("pg7").feature("surf1").set("color", "gray");
    model.result("pg7").feature("surf1").create("def", "Deform");
    model.result("pg7").feature("surf1").feature("def").set("expr", new String[]{"u", "v"});
    model.result("pg7").feature("surf1").feature("def").set("descr", "\u4f4d\u79fb\u573a");
    model.result("pg7").feature("surf1").feature("def").set("scaleactive", true);
    model.result("pg7").feature("surf1").feature("def").set("scale", 1);
    model.result("pg7").feature("surf1").create("sel1", "Selection");
    model.result("pg7").feature("surf1").feature("sel1").selection().geom("geom1", 2);
    model.result("pg7").feature("surf1").feature("sel1").selection().set(1, 2);
    model.result("pg7").create("arwl1", "ArrowLine");
    model.result("pg7").feature("arwl1").set("arrowbase", "head");
    model.result("pg7").feature("arwl1").set("expr", new String[]{"solid.dcnt2.Tnx", "solid.dcnt2.Tny"});
    model.result("pg7").feature("arwl1").set("placement", "gausspoints");
    model.result("pg7").feature("arwl1").set("gporder", 4);
    model.result("pg7").feature("arwl1").label("\u63a5\u89e6 2, \u538b\u529b");
    model.result("pg7").feature("arwl1").set("inheritplot", "none");
    model.result("pg7").feature("arwl1").set("color", "green");
    model.result("pg7").feature("arwl1").create("col", "Color");
    model.result("pg7").feature("arwl1").feature("col").set("colortable", "Rainbow");
    model.result("pg7").feature("arwl1").feature("col").set("colortabletrans", "none");
    model.result("pg7").feature("arwl1").feature("col").set("colorscalemode", "linear");
    model.result("pg7").feature("arwl1").feature("col").set("colordata", "arrowlength");
    model.result("pg7").feature("arwl1").feature("col").set("coloring", "gradient");
    model.result("pg7").feature("arwl1").feature("col").set("topcolor", "green");
    model.result("pg7").feature("arwl1").feature("col").set("bottomcolor", "custom");
    model.result("pg7").feature("arwl1").feature("col")
         .set("custombottomcolor", new double[]{0.509804, 0.54902, 0.509804});
    model.result("pg7").feature("arwl1").create("def", "Deform");
    model.result("pg7").feature("arwl1").feature("def").set("expr", new String[]{"u", "v"});
    model.result("pg7").feature("arwl1").feature("def").set("descr", "\u4f4d\u79fb\u573a");
    model.result("pg7").feature("arwl1").feature("def").set("scaleactive", true);
    model.result("pg7").feature("arwl1").feature("def").set("scale", 1);
    model.result("pg7").feature().move("surf1", 1);
    model.result("pg7").set("legendpos", "rightdouble");
    model.result("pg7").create("arwl2", "ArrowLine");
    model.result("pg7").feature("arwl2").set("arrowbase", "tail");
    model.result("pg7").feature("arwl2").set("expr", new String[]{"solid.dcnt2.Ttx", "solid.dcnt2.Tty"});
    model.result("pg7").feature("arwl2").set("placement", "gausspoints");
    model.result("pg7").feature("arwl2").set("gporder", 4);
    model.result("pg7").feature("arwl2").label("\u63a5\u89e6 2, \u6469\u64e6\u529b");
    model.result("pg7").feature("arwl2").set("inheritplot", "none");
    model.result("pg7").feature("arwl2").set("color", "magenta");
    model.result("pg7").feature("arwl2").create("col", "Color");
    model.result("pg7").feature("arwl2").feature("col").set("colortable", "Rainbow");
    model.result("pg7").feature("arwl2").feature("col").set("colortabletrans", "none");
    model.result("pg7").feature("arwl2").feature("col").set("colorscalemode", "linear");
    model.result("pg7").feature("arwl2").feature("col").set("colordata", "arrowlength");
    model.result("pg7").feature("arwl2").feature("col").set("coloring", "gradient");
    model.result("pg7").feature("arwl2").feature("col").set("topcolor", "magenta");
    model.result("pg7").feature("arwl2").feature("col").set("bottomcolor", "custom");
    model.result("pg7").feature("arwl2").feature("col")
         .set("custombottomcolor", new double[]{0.54902, 0.509804, 0.54902});
    model.result("pg7").feature("arwl2").create("def", "Deform");
    model.result("pg7").feature("arwl2").feature("def").set("expr", new String[]{"u", "v"});
    model.result("pg7").feature("arwl2").feature("def").set("descr", "\u4f4d\u79fb\u573a");
    model.result("pg7").feature("arwl2").feature("def").set("scaleactive", true);
    model.result("pg7").feature("arwl2").feature("def").set("scale", 1);
    model.result("pg7").feature().move("surf1", 2);
    model.result("pg7").label("\u63a5\u89e6\u529b (solid)");
    model.result("pg7").run();
    model.result("pg7").label("\u63a5\u89e6\uff1a\u589e\u5e7f\u62c9\u683c\u6717\u65e5\uff0c\u5206\u79bb");
    model.result("pg7").run();
    model.result("pg7").run();
    model.result().numerical().duplicate("pev2", "pev1");
    model.result().numerical("pev2")
         .label("\u70b9\u8ba1\u7b97\uff1a\u589e\u5e7f\u62c9\u683c\u6717\u65e5\uff0c\u5206\u79bb");
    model.result().numerical("pev2").set("data", "dset4");
    model.result().table().create("tbl2", "Table");
    model.result().table("tbl2")
         .comments("\u70b9\u8ba1\u7b97\uff1a\u589e\u5e7f\u62c9\u683c\u6717\u65e5\uff0c\u5206\u79bb");
    model.result().numerical("pev2").set("table", "tbl2");
    model.result().numerical("pev2").setResult();
    model.result("pg6").run();
    model.result("pg6").label("\u4f4d\u79fb\uff1a\u589e\u5e7f\u62c9\u683c\u6717\u65e5\uff0c\u8026\u5408");
    model.result("pg6").run();
    model.result("pg6").feature("surf1").set("expr", "u");
    model.result("pg6").feature("surf1").set("descr", "\u4f4d\u79fb\u573a\uff0cX \u5206\u91cf");
    model.result("pg6").feature("surf1").set("colortable", "RainbowLight");
    model.result("pg6").run();
    model.result().create("pg8", "PlotGroup2D");
    model.result("pg8").set("data", "dset6");
    model.result("pg8").setIndex("looplevel", 2, 0);
    model.result("pg8").setIndex("looplevel", 3, 1);
    model.result("pg8").label("\u63a5\u89e6\u529b (solid)");
    model.result("pg8").set("showlegends", true);
    model.result("pg8").set("titletype", "label");
    model.result("pg8").set("frametype", "spatial");
    model.result("pg8").set("showlegendsunit", true);
    model.result("pg8").create("surf1", "Surface");
    model.result("pg8").feature("surf1").set("expr", new String[]{"1"});
    model.result("pg8").feature("surf1").label("\u7070\u8272\u8868\u9762");
    model.result("pg8").feature("surf1").set("coloring", "uniform");
    model.result("pg8").feature("surf1").set("color", "gray");
    model.result("pg8").feature("surf1").create("def", "Deform");
    model.result("pg8").feature("surf1").feature("def").set("expr", new String[]{"u", "v"});
    model.result("pg8").feature("surf1").feature("def").set("descr", "\u4f4d\u79fb\u573a");
    model.result("pg8").feature("surf1").feature("def").set("scaleactive", true);
    model.result("pg8").feature("surf1").feature("def").set("scale", 1);
    model.result("pg8").feature("surf1").create("sel1", "Selection");
    model.result("pg8").feature("surf1").feature("sel1").selection().geom("geom1", 2);
    model.result("pg8").feature("surf1").feature("sel1").selection().set(1, 2);
    model.result("pg8").create("arwl1", "ArrowLine");
    model.result("pg8").feature("arwl1").set("arrowbase", "head");
    model.result("pg8").feature("arwl1").set("expr", new String[]{"solid.dcnt3.Tnx", "solid.dcnt3.Tny"});
    model.result("pg8").feature("arwl1").set("placement", "gausspoints");
    model.result("pg8").feature("arwl1").set("gporder", 4);
    model.result("pg8").feature("arwl1").label("\u63a5\u89e6 3, \u538b\u529b");
    model.result("pg8").feature("arwl1").set("inheritplot", "none");
    model.result("pg8").feature("arwl1").set("color", "green");
    model.result("pg8").feature("arwl1").create("col", "Color");
    model.result("pg8").feature("arwl1").feature("col").set("colortable", "Rainbow");
    model.result("pg8").feature("arwl1").feature("col").set("colortabletrans", "none");
    model.result("pg8").feature("arwl1").feature("col").set("colorscalemode", "linear");
    model.result("pg8").feature("arwl1").feature("col").set("colordata", "arrowlength");
    model.result("pg8").feature("arwl1").feature("col").set("coloring", "gradient");
    model.result("pg8").feature("arwl1").feature("col").set("topcolor", "green");
    model.result("pg8").feature("arwl1").feature("col").set("bottomcolor", "custom");
    model.result("pg8").feature("arwl1").feature("col")
         .set("custombottomcolor", new double[]{0.509804, 0.54902, 0.509804});
    model.result("pg8").feature("arwl1").create("def", "Deform");
    model.result("pg8").feature("arwl1").feature("def").set("expr", new String[]{"u", "v"});
    model.result("pg8").feature("arwl1").feature("def").set("descr", "\u4f4d\u79fb\u573a");
    model.result("pg8").feature("arwl1").feature("def").set("scaleactive", true);
    model.result("pg8").feature("arwl1").feature("def").set("scale", 1);
    model.result("pg8").feature().move("surf1", 1);
    model.result("pg8").set("legendpos", "rightdouble");
    model.result("pg8").create("arwl2", "ArrowLine");
    model.result("pg8").feature("arwl2").set("arrowbase", "tail");
    model.result("pg8").feature("arwl2").set("expr", new String[]{"solid.dcnt3.Ttx", "solid.dcnt3.Tty"});
    model.result("pg8").feature("arwl2").set("placement", "gausspoints");
    model.result("pg8").feature("arwl2").set("gporder", 4);
    model.result("pg8").feature("arwl2").label("\u63a5\u89e6 3, \u6469\u64e6\u529b");
    model.result("pg8").feature("arwl2").set("inheritplot", "none");
    model.result("pg8").feature("arwl2").set("color", "magenta");
    model.result("pg8").feature("arwl2").create("col", "Color");
    model.result("pg8").feature("arwl2").feature("col").set("colortable", "Rainbow");
    model.result("pg8").feature("arwl2").feature("col").set("colortabletrans", "none");
    model.result("pg8").feature("arwl2").feature("col").set("colorscalemode", "linear");
    model.result("pg8").feature("arwl2").feature("col").set("colordata", "arrowlength");
    model.result("pg8").feature("arwl2").feature("col").set("coloring", "gradient");
    model.result("pg8").feature("arwl2").feature("col").set("topcolor", "magenta");
    model.result("pg8").feature("arwl2").feature("col").set("bottomcolor", "custom");
    model.result("pg8").feature("arwl2").feature("col")
         .set("custombottomcolor", new double[]{0.54902, 0.509804, 0.54902});
    model.result("pg8").feature("arwl2").create("def", "Deform");
    model.result("pg8").feature("arwl2").feature("def").set("expr", new String[]{"u", "v"});
    model.result("pg8").feature("arwl2").feature("def").set("descr", "\u4f4d\u79fb\u573a");
    model.result("pg8").feature("arwl2").feature("def").set("scaleactive", true);
    model.result("pg8").feature("arwl2").feature("def").set("scale", 1);
    model.result("pg8").feature().move("surf1", 2);
    model.result("pg8").label("\u63a5\u89e6\u529b (solid)");
    model.result("pg8").run();
    model.result("pg8").label("\u63a5\u89e6\uff1a\u589e\u5e7f\u62c9\u683c\u6717\u65e5\uff0c\u8026\u5408");
    model.result("pg8").run();
    model.result("pg8").run();
    model.result().numerical().duplicate("pev3", "pev1");
    model.result().numerical("pev3")
         .label("\u70b9\u8ba1\u7b97\uff1a\u589e\u5e7f\u62c9\u683c\u6717\u65e5\uff0c\u8026\u5408");
    model.result().numerical("pev3").set("data", "dset6");
    model.result().table().create("tbl3", "Table");
    model.result().table("tbl3")
         .comments("\u70b9\u8ba1\u7b97\uff1a\u589e\u5e7f\u62c9\u683c\u6717\u65e5\uff0c\u8026\u5408");
    model.result().numerical("pev3").set("table", "tbl3");
    model.result().numerical("pev3").setResult();

    model.component("comp1").physics("solid").feature().duplicate("dcnt4", "dcnt3");
    model.component("comp1").physics("solid").feature("dcnt4").set("ContactMethodCtrl", "Nitsche");

    model.study().create("std4");
    model.study("std4").create("stat", "Stationary");
    model.study("std4").feature("stat").setSolveFor("/physics/solid", true);
    model.study("std4").create("param", "Parametric");
    model.study("std4").feature("param").setIndex("pname", "G", 0);
    model.study("std4").feature("param").setIndex("plistarr", "", 0);
    model.study("std4").feature("param").setIndex("punit", "N", 0);
    model.study("std4").feature("param").setIndex("pname", "G", 0);
    model.study("std4").feature("param").setIndex("plistarr", "", 0);
    model.study("std4").feature("param").setIndex("punit", "N", 0);
    model.study("std4").feature("param").setIndex("pname", "mu", 0);
    model.study("std4").feature("param").setIndex("plistarr", "0 0.1 0.2", 0);
    model.study("std4").feature("param").setIndex("pname", "G", 1);
    model.study("std4").feature("param").setIndex("plistarr", "", 1);
    model.study("std4").feature("param").setIndex("punit", "N", 1);
    model.study("std4").feature("param").setIndex("pname", "G", 1);
    model.study("std4").feature("param").setIndex("plistarr", "", 1);
    model.study("std4").feature("param").setIndex("punit", "N", 1);
    model.study("std4").feature("param").setIndex("pname", "K", 1);
    model.study("std4").feature("param").setIndex("plistarr", "1194 882 563.9", 1);
    model.study("std4").feature("stat").set("useparam", true);
    model.study("std4").feature("stat").setIndex("pname", "G", 0);
    model.study("std4").feature("stat").setIndex("plistarr", "", 0);
    model.study("std4").feature("stat").setIndex("punit", "N", 0);
    model.study("std4").feature("stat").setIndex("pname", "G", 0);
    model.study("std4").feature("stat").setIndex("plistarr", "", 0);
    model.study("std4").feature("stat").setIndex("punit", "N", 0);
    model.study("std4").feature("stat").setIndex("pname", "para", 0);
    model.study("std4").feature("stat").setIndex("plistarr", "1e-3 1", 0);
    model.study("std4").feature("stat").set("usestol", true);
    model.study("std4").feature("stat").set("stol", "1e-6");
    model.study("std4").showAutoSequences("all");

    model.sol("sol16").feature("s1").feature("p1").set("paramtuning", true);
    model.sol("sol16").feature("s1").feature("p1").set("pinitstep", "1e-2");
    model.sol("sol16").feature("s1").feature("p1").set("pminstep", "1e-6");
    model.sol("sol16").feature("s1").feature("p1").set("porder", "linear");
    model.sol("sol16").feature("s1").feature("fc1").set("dtech", "const");

    model.study("std4").label("\u7814\u7a76 4\uff1aNitsche");
    model.study("std4").createAutoSequences("all");

    model.sol().create("sol17");
    model.sol("sol17").study("std4");
    model.sol("sol17").label("\u53c2\u6570\u5316\u89e3 4");

    model.batch("p4").feature("so1").set("psol", "sol17");
    model.batch("p4").run("compute");

    model.result().create("pg9", "PlotGroup2D");
    model.result("pg9").set("data", "dset8");
    model.result("pg9").setIndex("looplevel", 2, 0);
    model.result("pg9").setIndex("looplevel", 3, 1);
    model.result("pg9").label("\u5e94\u529b (solid)");
    model.result("pg9").set("frametype", "spatial");
    model.result("pg9").create("surf1", "Surface");
    model.result("pg9").feature("surf1").set("expr", new String[]{"solid.misesGp"});
    model.result("pg9").feature("surf1").set("threshold", "manual");
    model.result("pg9").feature("surf1").set("thresholdvalue", 0.2);
    model.result("pg9").feature("surf1").set("colortable", "Rainbow");
    model.result("pg9").feature("surf1").set("colortabletrans", "none");
    model.result("pg9").feature("surf1").set("colorscalemode", "linear");
    model.result("pg9").feature("surf1").set("resolution", "normal");
    model.result("pg9").feature("surf1").set("colortable", "Prism");
    model.result("pg9").feature("surf1").create("def", "Deform");
    model.result("pg9").feature("surf1").feature("def").set("scaleactive", true);
    model.result("pg9").feature("surf1").feature("def").set("scale", "1");
    model.result("pg9").feature("surf1").feature("def").set("expr", new String[]{"u", "v"});
    model.result("pg9").feature("surf1").feature("def").set("descr", "\u4f4d\u79fb\u573a");
    model.result("pg9").run();
    model.result("pg9").label("\u4f4d\u79fb\uff1aNitsche");
    model.result("pg9").run();
    model.result("pg9").feature("surf1").set("expr", "u");
    model.result("pg9").feature("surf1").set("descr", "\u4f4d\u79fb\u573a\uff0cX \u5206\u91cf");
    model.result("pg9").feature("surf1").set("colortable", "RainbowLight");
    model.result("pg9").run();
    model.result().create("pg10", "PlotGroup2D");
    model.result("pg10").set("data", "dset8");
    model.result("pg10").setIndex("looplevel", 2, 0);
    model.result("pg10").setIndex("looplevel", 3, 1);
    model.result("pg10").label("\u63a5\u89e6\u529b (solid)");
    model.result("pg10").set("showlegends", true);
    model.result("pg10").set("titletype", "label");
    model.result("pg10").set("frametype", "spatial");
    model.result("pg10").set("showlegendsunit", true);
    model.result("pg10").create("surf1", "Surface");
    model.result("pg10").feature("surf1").set("expr", new String[]{"1"});
    model.result("pg10").feature("surf1").label("\u7070\u8272\u8868\u9762");
    model.result("pg10").feature("surf1").set("coloring", "uniform");
    model.result("pg10").feature("surf1").set("color", "gray");
    model.result("pg10").feature("surf1").create("def", "Deform");
    model.result("pg10").feature("surf1").feature("def").set("expr", new String[]{"u", "v"});
    model.result("pg10").feature("surf1").feature("def").set("descr", "\u4f4d\u79fb\u573a");
    model.result("pg10").feature("surf1").feature("def").set("scaleactive", true);
    model.result("pg10").feature("surf1").feature("def").set("scale", 1);
    model.result("pg10").feature("surf1").create("sel1", "Selection");
    model.result("pg10").feature("surf1").feature("sel1").selection().geom("geom1", 2);
    model.result("pg10").feature("surf1").feature("sel1").selection().set(1, 2);
    model.result("pg10").create("arwl1", "ArrowLine");
    model.result("pg10").feature("arwl1").set("arrowbase", "head");
    model.result("pg10").feature("arwl1").set("expr", new String[]{"solid.dcnt4.Tnx", "solid.dcnt4.Tny"});
    model.result("pg10").feature("arwl1").set("placement", "gausspoints");
    model.result("pg10").feature("arwl1").set("gporder", 8);
    model.result("pg10").feature("arwl1").label("\u63a5\u89e6 4, \u538b\u529b");
    model.result("pg10").feature("arwl1").set("inheritplot", "none");
    model.result("pg10").feature("arwl1").set("color", "green");
    model.result("pg10").feature("arwl1").create("col", "Color");
    model.result("pg10").feature("arwl1").feature("col").set("colortable", "Rainbow");
    model.result("pg10").feature("arwl1").feature("col").set("colortabletrans", "none");
    model.result("pg10").feature("arwl1").feature("col").set("colorscalemode", "linear");
    model.result("pg10").feature("arwl1").feature("col").set("colordata", "arrowlength");
    model.result("pg10").feature("arwl1").feature("col").set("coloring", "gradient");
    model.result("pg10").feature("arwl1").feature("col").set("topcolor", "green");
    model.result("pg10").feature("arwl1").feature("col").set("bottomcolor", "custom");
    model.result("pg10").feature("arwl1").feature("col")
         .set("custombottomcolor", new double[]{0.509804, 0.54902, 0.509804});
    model.result("pg10").feature("arwl1").create("def", "Deform");
    model.result("pg10").feature("arwl1").feature("def").set("expr", new String[]{"u", "v"});
    model.result("pg10").feature("arwl1").feature("def").set("descr", "\u4f4d\u79fb\u573a");
    model.result("pg10").feature("arwl1").feature("def").set("scaleactive", true);
    model.result("pg10").feature("arwl1").feature("def").set("scale", 1);
    model.result("pg10").feature().move("surf1", 1);
    model.result("pg10").set("legendpos", "rightdouble");
    model.result("pg10").create("arwl2", "ArrowLine");
    model.result("pg10").feature("arwl2").set("arrowbase", "tail");
    model.result("pg10").feature("arwl2").set("expr", new String[]{"solid.dcnt4.Ttx", "solid.dcnt4.Tty"});
    model.result("pg10").feature("arwl2").set("placement", "gausspoints");
    model.result("pg10").feature("arwl2").set("gporder", 8);
    model.result("pg10").feature("arwl2").label("\u63a5\u89e6 4, \u6469\u64e6\u529b");
    model.result("pg10").feature("arwl2").set("inheritplot", "none");
    model.result("pg10").feature("arwl2").set("color", "magenta");
    model.result("pg10").feature("arwl2").create("col", "Color");
    model.result("pg10").feature("arwl2").feature("col").set("colortable", "Rainbow");
    model.result("pg10").feature("arwl2").feature("col").set("colortabletrans", "none");
    model.result("pg10").feature("arwl2").feature("col").set("colorscalemode", "linear");
    model.result("pg10").feature("arwl2").feature("col").set("colordata", "arrowlength");
    model.result("pg10").feature("arwl2").feature("col").set("coloring", "gradient");
    model.result("pg10").feature("arwl2").feature("col").set("topcolor", "magenta");
    model.result("pg10").feature("arwl2").feature("col").set("bottomcolor", "custom");
    model.result("pg10").feature("arwl2").feature("col")
         .set("custombottomcolor", new double[]{0.54902, 0.509804, 0.54902});
    model.result("pg10").feature("arwl2").create("def", "Deform");
    model.result("pg10").feature("arwl2").feature("def").set("expr", new String[]{"u", "v"});
    model.result("pg10").feature("arwl2").feature("def").set("descr", "\u4f4d\u79fb\u573a");
    model.result("pg10").feature("arwl2").feature("def").set("scaleactive", true);
    model.result("pg10").feature("arwl2").feature("def").set("scale", 1);
    model.result("pg10").feature().move("surf1", 2);
    model.result("pg10").label("\u63a5\u89e6\u529b (solid)");
    model.result("pg10").run();
    model.result("pg10").label("\u63a5\u89e6\uff1aNitsche");
    model.result("pg10").run();
    model.result("pg10").run();
    model.result().numerical().duplicate("pev4", "pev1");
    model.result().numerical("pev4").label("\u70b9\u8ba1\u7b97\uff1aNitsche");
    model.result().numerical("pev4").set("data", "dset8");
    model.result().table().create("tbl4", "Table");
    model.result().table("tbl4").comments("\u70b9\u8ba1\u7b97\uff1aNitsche");
    model.result().numerical("pev4").set("table", "tbl4");
    model.result().numerical("pev4").setResult();

    model.study("std1").feature("stat").set("useadvanceddisable", true);
    model.study("std1").feature("stat")
         .set("disabledphysics", new String[]{"solid/dcnt2", "solid/dcnt3", "solid/dcnt4"});
    model.study("std2").feature("stat").set("disabledphysics", new String[]{"solid/dcnt3", "solid/dcnt4"});
    model.study("std3").feature("stat").set("useadvanceddisable", true);
    model.study("std3").feature("stat").set("disabledphysics", new String[]{"solid/dcnt4"});

    model.result("pg1").run();

    model.title("\u6ed1\u52a8\u6954\u5757");

    model
         .description("\u627f\u53d7\u91cd\u529b\u8f7d\u8377\u7684\u63a5\u89e6\u5668\u6954\u5757\u7531\u4e8e\u8fb9\u754c\u8f7d\u8377\u800c\u88ab\u8feb\u5728\u76ee\u6807\u6954\u5757\u8868\u9762\u6ed1\u52a8\u3002\u5de6\u4fa7\u5782\u76f4\u8fb9\u754c\u4e0e\u5730\u9762\u901a\u8fc7\u6c34\u5e73\u7ebf\u6027\u5f39\u7c27\u8fde\u63a5\u3002\u8fd9\u662f\u4e00\u4e2a\u6d89\u53ca\u63a5\u89e6\u9762\u79ef\u6052\u5b9a\u7684\u63a5\u89e6\u538b\u529b\u548c\u6469\u64e6\u529b\u8ba1\u7b97\u7684\u5927\u578b\u6ed1\u52a8\u57fa\u51c6\u95ee\u9898\uff0c\u901a\u8fc7\u7f5a\u51fd\u6570\u6cd5\u3001\u589e\u5e7f\u62c9\u683c\u6717\u65e5\u65b9\u6cd5\u548c Nitsche \u65b9\u6cd5\u8fdb\u884c\u6c42\u89e3\u3002");

    model.mesh().clearMeshes();

    model.sol("sol1").clearSolutionData();
    model.sol("sol2").clearSolutionData();
    model.sol("sol3").clearSolutionData();
    model.sol("sol4").clearSolutionData();
    model.sol("sol5").clearSolutionData();
    model.sol("sol6").clearSolutionData();
    model.sol("sol7").clearSolutionData();
    model.sol("sol8").clearSolutionData();
    model.sol("sol9").clearSolutionData();
    model.sol("sol10").clearSolutionData();
    model.sol("sol11").clearSolutionData();
    model.sol("sol12").clearSolutionData();
    model.sol("sol13").clearSolutionData();
    model.sol("sol14").clearSolutionData();
    model.sol("sol15").clearSolutionData();
    model.sol("sol16").clearSolutionData();
    model.sol("sol17").clearSolutionData();
    model.sol("sol18").clearSolutionData();
    model.sol("sol19").clearSolutionData();
    model.sol("sol20").clearSolutionData();

    model.label("sliding_wedge.mph");

    return model;
  }

  public static void main(String[] args) {
    Model model = run();
    run2(model);
  }

}
