/*
 * double_gauss_lens_geom_sequence.java
 */

import com.comsol.model.*;
import com.comsol.model.util.*;

/** Model exported on Apr 30 2026, 12:16 by COMSOL 6.3.0.290. */
public class double_gauss_lens_geom_sequence {

  public static Model run() {
    Model model = ModelUtil.create("Model");

    model
         .modelPath("D:\\Program Files\\COMSOL\\COMSOL63\\Multiphysics\\applications\\Ray_Optics_Module\\Lenses_Cameras_and_Telescopes");

    model.component().create("comp1", true);

    model.component("comp1").geom().create("geom1", 3);
    model.component("comp1").geom("geom1").geomRep("comsol");

    model.component("comp1").mesh().create("mesh1");
    model.component("comp1").mesh("mesh1").contribute("geom/detail", true);

//    To import content from file, use:
//    model.param().loadFile("FILENAME");
    model.param().set("nix", "0", "\u5168\u5c40\u5149\u8f74\uff0cx \u5206\u91cf");
    model.param().set("niy", "0", "\u5168\u5c40\u5149\u8f74\uff0cy \u5206\u91cf");
    model.param().set("niz", "1", "\u5168\u5c40\u5149\u8f74\uff0cz \u5206\u91cf");
    model.param().set("R1_1", "75.050[mm]", "L1\uff0c\u8868\u9762 1 \u7684\u66f2\u7387\u534a\u5f84");
    model.param().set("R2_1", "270.700[mm]", "L1\uff0c\u8868\u9762 2 \u7684\u66f2\u7387\u534a\u5f84");
    model.param().set("Tc_1", "9.000[mm]", "L1 \u4e2d\u5fc3\u539a\u5ea6");
    model.param().set("d0_1", "68.500[mm]", "L1\uff0c\u5916\u5f84");
    model.param().set("d1_1", "0", "L1\uff0c\u8868\u9762 1 \u7684\u76f4\u5f84");
    model.param().set("d2_1", "67.500[mm]", "L1\uff0c\u8868\u9762 2 \u7684\u76f4\u5f84");
    model.param().set("d1_clear_1", "66.000[mm]", "L1\uff0c\u8868\u9762 1 \u7684\u901a\u5149\u5b54\u5f84");
    model.param().set("d2_clear_1", "66.000[mm]", "L1\uff0c\u8868\u9762 2 \u7684\u901a\u5149\u5b54\u5f84");
    model.param().set("T_1", "0.100[mm]", "L1 \u5230 L2 \u7684\u95f4\u8ddd");
    model.param().set("R1_2", "39.270[mm]", "L2\uff0c\u8868\u9762 1 \u7684\u66f2\u7387\u534a\u5f84");
    model.param().set("R2_2", "0", "L2\uff0c\u8868\u9762 2 \u7684\u66f2\u7387\u534a\u5f84");
    model.param().set("Tc_2", "16.510[mm]", "L2 \u4e2d\u5fc3\u539a\u5ea6");
    model.param().set("d0_2", "56.500[mm]", "L2\uff0c\u5916\u5f84");
    model.param().set("d1_2", "0", "L2\uff0c\u8868\u9762 1 \u7684\u76f4\u5f84");
    model.param().set("d2_2", "50.000[mm]", "L2\uff0c\u8868\u9762 2 \u7684\u76f4\u5f84");
    model.param().set("d1_clear_2", "55.000[mm]", "L2\uff0c\u8868\u9762 1 \u7684\u901a\u5149\u5b54\u5f84");
    model.param().set("d2_clear_2", "49.000[mm]", "L2\uff0c\u8868\u9762 2 \u7684\u901a\u5149\u5b54\u5f84");
    model.param().set("T_2", "0.000[mm]", "L2 \u5230 L3 \u7684\u95f4\u8ddd");
    model.param().set("R1_3", "0", "L3\uff0c\u8868\u9762 1 \u7684\u66f2\u7387\u534a\u5f84");
    model.param().set("R2_3", "25.650[mm]", "L3\uff0c\u8868\u9762 2 \u7684\u66f2\u7387\u534a\u5f84");
    model.param().set("Tc_3", "2.000[mm]", "L3 \u4e2d\u5fc3\u539a\u5ea6");
    model.param().set("d0_3", "51.000[mm]", "L3\uff0c\u5916\u5f84");
    model.param().set("d1_3", "0", "L3\uff0c\u8868\u9762 1 \u7684\u76f4\u5f84");
    model.param().set("d2_3", "40.000[mm]", "L3\uff0c\u8868\u9762 2 \u7684\u76f4\u5f84");
    model.param().set("d1_clear_3", "49.000[mm]", "L3\uff0c\u8868\u9762 1 \u7684\u901a\u5149\u5b54\u5f84");
    model.param().set("d2_clear_3", "39.000[mm]", "L3\uff0c\u8868\u9762 2 \u7684\u901a\u5149\u5b54\u5f84");
    model.param().set("T_3", "10.990[mm]", "L3 \u5230\u5149\u9611\u7684\u95f4\u8ddd");
    model.param().set("Tc_4", "0.000[mm]", "\u5149\u9611\u4e2d\u5fc3\u539a\u5ea6");
    model.param().set("d0_S", "60.000[mm]", "\u5149\u9611\u6700\u5927\u76f4\u5f84");
    model.param().set("d1_S", "37.200[mm]", "\u5149\u9611\u5b54\u5f84");
    model.param().set("T_4", "13.000[mm]", "\u5149\u9611\u5230 L4 \u7684\u95f4\u8ddd");
    model.param().set("R1_5", "-31.870[mm]", "L4\uff0c\u8868\u9762 1 \u7684\u66f2\u7387\u534a\u5f84");
    model.param().set("R2_5", "0", "L4\uff0c\u8868\u9762 2 \u7684\u66f2\u7387\u534a\u5f84");
    model.param().set("Tc_5", "7.030[mm]", "L4 \u4e2d\u5fc3\u539a\u5ea6");
    model.param().set("d0_5", "44.000[mm]", "L4\uff0c\u5916\u5f84");
    model.param().set("d1_5", "38.000[mm]", "L4\uff0c\u8868\u9762 1 \u7684\u76f4\u5f84");
    model.param().set("d2_5", "0", "L4\uff0c\u8868\u9762 2 \u7684\u76f4\u5f84");
    model.param().set("d1_clear_5", "37.000[mm]", "L4\uff0c\u8868\u9762 1 \u7684\u901a\u5149\u5b54\u5f84");
    model.param().set("d2_clear_5", "42.000[mm]", "L4\uff0c\u8868\u9762 2 \u7684\u901a\u5149\u5b54\u5f84");
    model.param().set("T_5", "0.000[mm]", "L4 \u5230 L5 \u7684\u95f4\u8ddd");
    model.param().set("R1_6", "0", "L5\uff0c\u8868\u9762 1 \u7684\u66f2\u7387\u534a\u5f84");
    model.param().set("R2_6", "-43.510[mm]", "L5\uff0c\u8868\u9762 2 \u7684\u66f2\u7387\u534a\u5f84");
    model.param().set("Tc_6", "8.980[mm]", "L5 \u4e2d\u5fc3\u539a\u5ea6");
    model.param().set("d0_6", "44.000[mm]", "L5\uff0c\u5916\u5f84");
    model.param().set("d1_6", "0", "L5\uff0c\u8868\u9762 1 \u7684\u76f4\u5f84");
    model.param().set("d2_6", "0", "L5\uff0c\u8868\u9762 2 \u7684\u76f4\u5f84");
    model.param().set("d1_clear_6", "42.000[mm]", "L5\uff0c\u8868\u9762 1 \u7684\u901a\u5149\u5b54\u5f84");
    model.param().set("d2_clear_6", "42.000[mm]", "L5\uff0c\u8868\u9762 2 \u7684\u901a\u5149\u5b54\u5f84");
    model.param().set("T_6", "0.100[mm]", "L5 \u5230 L6 \u7684\u95f4\u8ddd");
    model.param().set("R1_7", "221.140[mm]", "L6\uff0c\u8868\u9762 1 \u7684\u66f2\u7387\u534a\u5f84");
    model.param().set("R2_7", "-88.790[mm]", "L6\uff0c\u8868\u9762 2 \u7684\u66f2\u7387\u534a\u5f84");
    model.param().set("Tc_7", "7.980[mm]", "L6 \u4e2d\u5fc3\u539a\u5ea6");
    model.param().set("d0_7", "47.000[mm]", "L6\uff0c\u5916\u5f84");
    model.param().set("d1_7", "0", "L6\uff0c\u8868\u9762 1 \u7684\u76f4\u5f84");
    model.param().set("d2_7", "0", "L6\uff0c\u8868\u9762 2 \u7684\u76f4\u5f84");
    model.param().set("d1_clear_7", "46.000[mm]", "L6\uff0c\u8868\u9762 1 \u7684\u901a\u5149\u5b54\u5f84");
    model.param().set("d2_clear_7", "46.000[mm]", "L6\uff0c\u8868\u9762 2 \u7684\u901a\u5149\u5b54\u5f84");
    model.param().set("T_7", "61.418[mm]", "L6 \u5230\u68c0\u6d4b\u5668\u7684\u95f4\u8ddd");
    model.param().set("d0_D", "85.000[mm]", "\u68c0\u6d4b\u5668\u76f4\u5f84");

    model.component("comp1").geom("geom1").label("\u53cc\u9ad8\u65af\u900f\u955c\u51e0\u4f55\u5e8f\u5217");
    model.component("comp1").geom("geom1").lengthUnit("mm");
    model.geom()
         .load(new String[]{"part1"}, "Ray_Optics_Module\\3D\\Spherical_Lenses\\spherical_lens_3d.mph", new String[]{"part1"});
    model.component("comp1").geom("geom1").create("pi1", "PartInstance");
    model.component("comp1").geom("geom1").feature("pi1").set("selkeepnoncontr", false);
    model.component("comp1").geom("geom1").feature("pi1").set("part", "part1");
    model.component("comp1").geom("geom1").feature("pi1").label("\u900f\u955c 1");
    model.component("comp1").geom("geom1").feature("pi1").setEntry("inputname", "R1", "R1");
    model.component("comp1").geom("geom1").feature("pi1").setEntry("inputname", "R2", "R2");
    model.component("comp1").geom("geom1").feature("pi1").setEntry("inputname", "Tc", "Tc");
    model.component("comp1").geom("geom1").feature("pi1").setEntry("inputname", "d0", "d0");
    model.component("comp1").geom("geom1").feature("pi1").setEntry("inputname", "d1", "d1");
    model.component("comp1").geom("geom1").feature("pi1").setEntry("inputname", "d2", "d2");
    model.component("comp1").geom("geom1").feature("pi1").setEntry("inputname", "d1_clear", "d1_clear");
    model.component("comp1").geom("geom1").feature("pi1").setEntry("inputname", "d2_clear", "d2_clear");
    model.component("comp1").geom("geom1").feature("pi1").setEntry("inputname", "nix", "nix");
    model.component("comp1").geom("geom1").feature("pi1").setEntry("inputname", "niy", "niy");
    model.component("comp1").geom("geom1").feature("pi1").setEntry("inputname", "niz", "niz");
    model.component("comp1").geom("geom1").feature("pi1").setEntry("inputname", "n_extra_r", "n_extra_r");
    model.component("comp1").geom("geom1").feature("pi1").setEntry("inputname", "n_extra_a", "n_extra_a");
    model.component("comp1").geom("geom1").feature("pi1").setEntry("inputexpr", "R1", "R1_1");
    model.component("comp1").geom("geom1").feature("pi1").setEntry("inputexpr", "R2", "R2_1");
    model.component("comp1").geom("geom1").feature("pi1").setEntry("inputexpr", "Tc", "Tc_1");
    model.component("comp1").geom("geom1").feature("pi1").setEntry("inputexpr", "d0", "d0_1");
    model.component("comp1").geom("geom1").feature("pi1").setEntry("inputexpr", "d1", "d1_1");
    model.component("comp1").geom("geom1").feature("pi1").setEntry("inputexpr", "d2", "d2_1");
    model.component("comp1").geom("geom1").feature("pi1").setEntry("inputexpr", "d1_clear", "d1_clear_1");
    model.component("comp1").geom("geom1").feature("pi1").setEntry("inputexpr", "d2_clear", "d2_clear_1");
    model.component("comp1").geom("geom1").feature("pi1").setEntry("inputexpr", "nix", "nix");
    model.component("comp1").geom("geom1").feature("pi1").setEntry("inputexpr", "niy", "niy");
    model.component("comp1").geom("geom1").feature("pi1").setEntry("inputexpr", "niz", "niz");
    model.component("comp1").geom("geom1").feature("pi1").setEntry("inputexpr", "n_extra_r", "0");
    model.component("comp1").geom("geom1").feature("pi1").setEntry("inputexpr", "n_extra_a", "0");
    model.component("comp1").geom("geom1").run("pi1");
    model.component("comp1").geom("geom1").selection().create("csel1", "CumulativeSelection");
    model.component("comp1").geom("geom1").selection("csel1").label("\u900f\u955c\u6750\u6599 1");
    model.component("comp1").geom("geom1").selection().create("csel2", "CumulativeSelection");
    model.component("comp1").geom("geom1").selection("csel2").label("\u900f\u955c\u6750\u6599 2");
    model.component("comp1").geom("geom1").selection().create("csel3", "CumulativeSelection");
    model.component("comp1").geom("geom1").selection("csel3").label("\u900f\u955c\u6750\u6599 3");
    model.component("comp1").geom("geom1").selection().create("csel4", "CumulativeSelection");
    model.component("comp1").geom("geom1").selection("csel4").label("\u900f\u955c\u5916\u90e8");
    model.component("comp1").geom("geom1").selection().create("csel5", "CumulativeSelection");
    model.component("comp1").geom("geom1").selection("csel5").label("\u901a\u5149\u5b54\u5f84");
    model.component("comp1").geom("geom1").selection().create("csel6", "CumulativeSelection");
    model.component("comp1").geom("geom1").selection("csel6").label("\u969c\u788d\u7269");
    model.component("comp1").geom("geom1").selection().create("csel7", "CumulativeSelection");
    model.component("comp1").geom("geom1").selection("csel7").label("\u5b54\u5f84\u5149\u9611");
    model.component("comp1").geom("geom1").selection().create("csel8", "CumulativeSelection");
    model.component("comp1").geom("geom1").selection("csel8").label("\u50cf\u5e73\u9762");
    model.component("comp1").geom("geom1").feature("pi1").setEntry("selcontributetodom", "pi1_sel1", "csel1");
    model.component("comp1").geom("geom1").feature("pi1").setEntry("selcontributetobnd", "pi1_sel2", "csel4");
    model.component("comp1").geom("geom1").feature("pi1").setEntry("selcontributetobnd", "pi1_sel3", "csel5");
    model.component("comp1").geom("geom1").feature("pi1").setEntry("selcontributetobnd", "pi1_sel4", "csel5");
    model.component("comp1").geom("geom1").feature("pi1").setEntry("selcontributetobnd", "pi1_sel5", "csel6");
    model.component("comp1").geom("geom1").feature("pi1").setEntry("selcontributetobnd", "pi1_sel6", "csel6");
    model.component("comp1").geom("geom1").feature("pi1").setEntry("selcontributetobnd", "pi1_sel7", "csel6");
    model.component("comp1").geom("geom1").create("pi2", "PartInstance");
    model.component("comp1").geom("geom1").feature("pi2").set("selkeepnoncontr", false);
    model.component("comp1").geom("geom1").feature("pi2").set("part", "part1");
    model.component("comp1").geom("geom1").feature("pi2").label("\u900f\u955c 2");
    model.component("comp1").geom("geom1").feature("pi2").setEntry("inputname", "R1", "R1");
    model.component("comp1").geom("geom1").feature("pi2").setEntry("inputname", "R2", "R2");
    model.component("comp1").geom("geom1").feature("pi2").setEntry("inputname", "Tc", "Tc");
    model.component("comp1").geom("geom1").feature("pi2").setEntry("inputname", "d0", "d0");
    model.component("comp1").geom("geom1").feature("pi2").setEntry("inputname", "d1", "d1");
    model.component("comp1").geom("geom1").feature("pi2").setEntry("inputname", "d2", "d2");
    model.component("comp1").geom("geom1").feature("pi2").setEntry("inputname", "d1_clear", "d1_clear");
    model.component("comp1").geom("geom1").feature("pi2").setEntry("inputname", "d2_clear", "d2_clear");
    model.component("comp1").geom("geom1").feature("pi2").setEntry("inputname", "nix", "nix");
    model.component("comp1").geom("geom1").feature("pi2").setEntry("inputname", "niy", "niy");
    model.component("comp1").geom("geom1").feature("pi2").setEntry("inputname", "niz", "niz");
    model.component("comp1").geom("geom1").feature("pi2").setEntry("inputname", "n_extra_r", "n_extra_r");
    model.component("comp1").geom("geom1").feature("pi2").setEntry("inputname", "n_extra_a", "n_extra_a");
    model.component("comp1").geom("geom1").feature("pi2").setEntry("inputexpr", "R1", "R1_2");
    model.component("comp1").geom("geom1").feature("pi2").setEntry("inputexpr", "R2", "R2_2");
    model.component("comp1").geom("geom1").feature("pi2").setEntry("inputexpr", "Tc", "Tc_2");
    model.component("comp1").geom("geom1").feature("pi2").setEntry("inputexpr", "d0", "d0_2");
    model.component("comp1").geom("geom1").feature("pi2").setEntry("inputexpr", "d1", "d1_2");
    model.component("comp1").geom("geom1").feature("pi2").setEntry("inputexpr", "d2", "d2_2");
    model.component("comp1").geom("geom1").feature("pi2").setEntry("inputexpr", "d1_clear", "d1_clear_2");
    model.component("comp1").geom("geom1").feature("pi2").setEntry("inputexpr", "d2_clear", "d2_clear_2");
    model.component("comp1").geom("geom1").feature("pi2").setEntry("inputexpr", "nix", "0");
    model.component("comp1").geom("geom1").feature("pi2").setEntry("inputexpr", "niy", "0");
    model.component("comp1").geom("geom1").feature("pi2").setEntry("inputexpr", "niz", "1");
    model.component("comp1").geom("geom1").feature("pi2").setEntry("inputexpr", "n_extra_r", "0");
    model.component("comp1").geom("geom1").feature("pi2").setEntry("inputexpr", "n_extra_a", "0");
    model.component("comp1").geom("geom1").feature("pi2").set("workplanesrc", "pi1");
    model.component("comp1").geom("geom1").feature("pi2").set("workplane", "wp2");
    model.component("comp1").geom("geom1").feature("pi2").set("displ", new String[]{"0", "0", "T_1"});
    model.component("comp1").geom("geom1").feature("pi2").setEntry("selcontributetodom", "pi2_sel1", "csel2");
    model.component("comp1").geom("geom1").feature("pi2").setEntry("selcontributetobnd", "pi2_sel2", "csel4");
    model.component("comp1").geom("geom1").feature("pi2").setEntry("selcontributetobnd", "pi2_sel3", "csel5");
    model.component("comp1").geom("geom1").feature("pi2").setEntry("selcontributetobnd", "pi2_sel4", "csel5");
    model.component("comp1").geom("geom1").feature("pi2").setEntry("selcontributetobnd", "pi2_sel5", "csel6");
    model.component("comp1").geom("geom1").feature("pi2").setEntry("selcontributetobnd", "pi2_sel6", "csel6");
    model.component("comp1").geom("geom1").feature("pi2").setEntry("selcontributetobnd", "pi2_sel7", "csel6");
    model.component("comp1").geom("geom1").run("pi2");
    model.component("comp1").geom("geom1").create("pi3", "PartInstance");
    model.component("comp1").geom("geom1").feature("pi3").set("selkeepnoncontr", false);
    model.component("comp1").geom("geom1").feature("pi3").set("part", "part1");
    model.component("comp1").geom("geom1").feature("pi3").label("\u900f\u955c 3");
    model.component("comp1").geom("geom1").feature("pi3").setEntry("inputname", "R1", "R1");
    model.component("comp1").geom("geom1").feature("pi3").setEntry("inputname", "R2", "R2");
    model.component("comp1").geom("geom1").feature("pi3").setEntry("inputname", "Tc", "Tc");
    model.component("comp1").geom("geom1").feature("pi3").setEntry("inputname", "d0", "d0");
    model.component("comp1").geom("geom1").feature("pi3").setEntry("inputname", "d1", "d1");
    model.component("comp1").geom("geom1").feature("pi3").setEntry("inputname", "d2", "d2");
    model.component("comp1").geom("geom1").feature("pi3").setEntry("inputname", "d1_clear", "d1_clear");
    model.component("comp1").geom("geom1").feature("pi3").setEntry("inputname", "d2_clear", "d2_clear");
    model.component("comp1").geom("geom1").feature("pi3").setEntry("inputname", "nix", "nix");
    model.component("comp1").geom("geom1").feature("pi3").setEntry("inputname", "niy", "niy");
    model.component("comp1").geom("geom1").feature("pi3").setEntry("inputname", "niz", "niz");
    model.component("comp1").geom("geom1").feature("pi3").setEntry("inputname", "n_extra_r", "n_extra_r");
    model.component("comp1").geom("geom1").feature("pi3").setEntry("inputname", "n_extra_a", "n_extra_a");
    model.component("comp1").geom("geom1").feature("pi3").setEntry("inputexpr", "R1", "R1_3");
    model.component("comp1").geom("geom1").feature("pi3").setEntry("inputexpr", "R2", "R2_3");
    model.component("comp1").geom("geom1").feature("pi3").setEntry("inputexpr", "Tc", "Tc_3");
    model.component("comp1").geom("geom1").feature("pi3").setEntry("inputexpr", "d0", "d0_3");
    model.component("comp1").geom("geom1").feature("pi3").setEntry("inputexpr", "d1", "d1_3");
    model.component("comp1").geom("geom1").feature("pi3").setEntry("inputexpr", "d2", "d2_3");
    model.component("comp1").geom("geom1").feature("pi3").setEntry("inputexpr", "d1_clear", "d1_clear_3");
    model.component("comp1").geom("geom1").feature("pi3").setEntry("inputexpr", "d2_clear", "d2_clear_3");
    model.component("comp1").geom("geom1").feature("pi3").setEntry("inputexpr", "nix", "0");
    model.component("comp1").geom("geom1").feature("pi3").setEntry("inputexpr", "niy", "0");
    model.component("comp1").geom("geom1").feature("pi3").setEntry("inputexpr", "niz", "1");
    model.component("comp1").geom("geom1").feature("pi3").setEntry("inputexpr", "n_extra_r", "0");
    model.component("comp1").geom("geom1").feature("pi3").setEntry("inputexpr", "n_extra_a", "0");
    model.component("comp1").geom("geom1").feature("pi3").set("workplanesrc", "pi2");
    model.component("comp1").geom("geom1").feature("pi3").set("workplane", "wp2");
    model.component("comp1").geom("geom1").feature("pi3").set("displ", new String[]{"0", "0", "T_2"});
    model.component("comp1").geom("geom1").feature("pi3").setEntry("selcontributetodom", "pi3_sel1", "csel3");
    model.component("comp1").geom("geom1").feature("pi3").setEntry("selcontributetobnd", "pi3_sel2", "csel4");
    model.component("comp1").geom("geom1").feature("pi3").setEntry("selcontributetobnd", "pi3_sel3", "csel5");
    model.component("comp1").geom("geom1").feature("pi3").setEntry("selcontributetobnd", "pi3_sel4", "csel5");
    model.component("comp1").geom("geom1").feature("pi3").setEntry("selcontributetobnd", "pi3_sel5", "csel6");
    model.component("comp1").geom("geom1").feature("pi3").setEntry("selcontributetobnd", "pi3_sel6", "csel6");
    model.component("comp1").geom("geom1").feature("pi3").setEntry("selcontributetobnd", "pi3_sel7", "csel6");
    model.geom()
         .load(new String[]{"part2"}, "Ray_Optics_Module\\3D\\Apertures_and_Obstructions\\circular_planar_annulus.mph", new String[]{"part1"});
    model.component("comp1").geom("geom1").run("pi3");
    model.component("comp1").geom("geom1").create("pi4", "PartInstance");
    model.component("comp1").geom("geom1").feature("pi4").set("selkeepnoncontr", false);
    model.component("comp1").geom("geom1").feature("pi4").set("part", "part2");
    model.component("comp1").geom("geom1").feature("pi4").label("\u5149\u9611");
    model.component("comp1").geom("geom1").feature("pi4").setEntry("inputexpr", "d0", "d0_S");
    model.component("comp1").geom("geom1").feature("pi4").setEntry("inputexpr", "d1", "d1_S");
    model.component("comp1").geom("geom1").feature("pi4").set("workplanesrc", "pi3");
    model.component("comp1").geom("geom1").feature("pi4").set("workplane", "wp2");
    model.component("comp1").geom("geom1").feature("pi4").set("displ", new String[]{"0", "0", "T_3+Tc_4"});
    model.component("comp1").geom("geom1").feature("pi4").setEntry("selcontributetobnd", "pi4_sel1", "csel7");
    model.component("comp1").geom("geom1").run("pi4");
    model.component("comp1").geom("geom1").create("pi5", "PartInstance");
    model.component("comp1").geom("geom1").feature("pi5").set("selkeepnoncontr", false);
    model.component("comp1").geom("geom1").feature("pi5").set("part", "part1");
    model.component("comp1").geom("geom1").feature("pi5").label("\u900f\u955c 4");
    model.component("comp1").geom("geom1").feature("pi5").setEntry("inputname", "R1", "R1");
    model.component("comp1").geom("geom1").feature("pi5").setEntry("inputname", "R2", "R2");
    model.component("comp1").geom("geom1").feature("pi5").setEntry("inputname", "Tc", "Tc");
    model.component("comp1").geom("geom1").feature("pi5").setEntry("inputname", "d0", "d0");
    model.component("comp1").geom("geom1").feature("pi5").setEntry("inputname", "d1", "d1");
    model.component("comp1").geom("geom1").feature("pi5").setEntry("inputname", "d2", "d2");
    model.component("comp1").geom("geom1").feature("pi5").setEntry("inputname", "d1_clear", "d1_clear");
    model.component("comp1").geom("geom1").feature("pi5").setEntry("inputname", "d2_clear", "d2_clear");
    model.component("comp1").geom("geom1").feature("pi5").setEntry("inputname", "nix", "nix");
    model.component("comp1").geom("geom1").feature("pi5").setEntry("inputname", "niy", "niy");
    model.component("comp1").geom("geom1").feature("pi5").setEntry("inputname", "niz", "niz");
    model.component("comp1").geom("geom1").feature("pi5").setEntry("inputname", "n_extra_r", "n_extra_r");
    model.component("comp1").geom("geom1").feature("pi5").setEntry("inputname", "n_extra_a", "n_extra_a");
    model.component("comp1").geom("geom1").feature("pi5").setEntry("inputexpr", "R1", "R1_5");
    model.component("comp1").geom("geom1").feature("pi5").setEntry("inputexpr", "R2", "R2_5");
    model.component("comp1").geom("geom1").feature("pi5").setEntry("inputexpr", "Tc", "Tc_5");
    model.component("comp1").geom("geom1").feature("pi5").setEntry("inputexpr", "d0", "d0_5");
    model.component("comp1").geom("geom1").feature("pi5").setEntry("inputexpr", "d1", "d1_5");
    model.component("comp1").geom("geom1").feature("pi5").setEntry("inputexpr", "d2", "d2_5");
    model.component("comp1").geom("geom1").feature("pi5").setEntry("inputexpr", "d1_clear", "d1_clear_5");
    model.component("comp1").geom("geom1").feature("pi5").setEntry("inputexpr", "d2_clear", "d2_clear_5");
    model.component("comp1").geom("geom1").feature("pi5").setEntry("inputexpr", "nix", "0");
    model.component("comp1").geom("geom1").feature("pi5").setEntry("inputexpr", "niy", "0");
    model.component("comp1").geom("geom1").feature("pi5").setEntry("inputexpr", "niz", "1");
    model.component("comp1").geom("geom1").feature("pi5").setEntry("inputexpr", "n_extra_r", "0");
    model.component("comp1").geom("geom1").feature("pi5").setEntry("inputexpr", "n_extra_a", "0");
    model.component("comp1").geom("geom1").feature("pi5").set("workplanesrc", "pi4");
    model.component("comp1").geom("geom1").feature("pi5").set("workplane", "wp1");
    model.component("comp1").geom("geom1").feature("pi5").set("displ", new String[]{"0", "0", "T_4"});
    model.component("comp1").geom("geom1").feature("pi5").setEntry("selcontributetodom", "pi5_sel1", "csel3");
    model.component("comp1").geom("geom1").feature("pi5").setEntry("selcontributetobnd", "pi5_sel2", "csel4");
    model.component("comp1").geom("geom1").feature("pi5").setEntry("selcontributetobnd", "pi5_sel3", "csel5");
    model.component("comp1").geom("geom1").feature("pi5").setEntry("selcontributetobnd", "pi5_sel4", "csel5");
    model.component("comp1").geom("geom1").feature("pi5").setEntry("selcontributetobnd", "pi5_sel5", "csel6");
    model.component("comp1").geom("geom1").feature("pi5").setEntry("selcontributetobnd", "pi5_sel6", "csel6");
    model.component("comp1").geom("geom1").feature("pi5").setEntry("selcontributetobnd", "pi5_sel7", "csel6");
    model.component("comp1").geom("geom1").run("pi5");
    model.component("comp1").geom("geom1").create("pi6", "PartInstance");
    model.component("comp1").geom("geom1").feature("pi6").set("selkeepnoncontr", false);
    model.component("comp1").geom("geom1").feature("pi6").set("part", "part1");
    model.component("comp1").geom("geom1").feature("pi6").label("\u900f\u955c 5");
    model.component("comp1").geom("geom1").feature("pi6").setEntry("inputname", "R1", "R1");
    model.component("comp1").geom("geom1").feature("pi6").setEntry("inputname", "R2", "R2");
    model.component("comp1").geom("geom1").feature("pi6").setEntry("inputname", "Tc", "Tc");
    model.component("comp1").geom("geom1").feature("pi6").setEntry("inputname", "d0", "d0");
    model.component("comp1").geom("geom1").feature("pi6").setEntry("inputname", "d1", "d1");
    model.component("comp1").geom("geom1").feature("pi6").setEntry("inputname", "d2", "d2");
    model.component("comp1").geom("geom1").feature("pi6").setEntry("inputname", "d1_clear", "d1_clear");
    model.component("comp1").geom("geom1").feature("pi6").setEntry("inputname", "d2_clear", "d2_clear");
    model.component("comp1").geom("geom1").feature("pi6").setEntry("inputname", "nix", "nix");
    model.component("comp1").geom("geom1").feature("pi6").setEntry("inputname", "niy", "niy");
    model.component("comp1").geom("geom1").feature("pi6").setEntry("inputname", "niz", "niz");
    model.component("comp1").geom("geom1").feature("pi6").setEntry("inputname", "n_extra_r", "n_extra_r");
    model.component("comp1").geom("geom1").feature("pi6").setEntry("inputname", "n_extra_a", "n_extra_a");
    model.component("comp1").geom("geom1").feature("pi6").setEntry("inputexpr", "R1", "R1_6");
    model.component("comp1").geom("geom1").feature("pi6").setEntry("inputexpr", "R2", "R2_6");
    model.component("comp1").geom("geom1").feature("pi6").setEntry("inputexpr", "Tc", "Tc_6");
    model.component("comp1").geom("geom1").feature("pi6").setEntry("inputexpr", "d0", "d0_6");
    model.component("comp1").geom("geom1").feature("pi6").setEntry("inputexpr", "d1", "d1_6");
    model.component("comp1").geom("geom1").feature("pi6").setEntry("inputexpr", "d2", "d2_6");
    model.component("comp1").geom("geom1").feature("pi6").setEntry("inputexpr", "d1_clear", "d1_clear_6");
    model.component("comp1").geom("geom1").feature("pi6").setEntry("inputexpr", "d2_clear", "d2_clear_6");
    model.component("comp1").geom("geom1").feature("pi6").setEntry("inputexpr", "nix", "0");
    model.component("comp1").geom("geom1").feature("pi6").setEntry("inputexpr", "niy", "0");
    model.component("comp1").geom("geom1").feature("pi6").setEntry("inputexpr", "niz", "1");
    model.component("comp1").geom("geom1").feature("pi6").setEntry("inputexpr", "n_extra_r", "0");
    model.component("comp1").geom("geom1").feature("pi6").setEntry("inputexpr", "n_extra_a", "0");
    model.component("comp1").geom("geom1").feature("pi6").set("workplanesrc", "pi5");
    model.component("comp1").geom("geom1").feature("pi6").set("workplane", "wp2");
    model.component("comp1").geom("geom1").feature("pi6").set("displ", new String[]{"0", "0", "T_5"});
    model.component("comp1").geom("geom1").feature("pi6").setEntry("selcontributetodom", "pi6_sel1", "csel1");
    model.component("comp1").geom("geom1").feature("pi6").setEntry("selcontributetobnd", "pi6_sel2", "csel4");
    model.component("comp1").geom("geom1").feature("pi6").setEntry("selcontributetobnd", "pi6_sel3", "csel5");
    model.component("comp1").geom("geom1").feature("pi6").setEntry("selcontributetobnd", "pi6_sel4", "csel5");
    model.component("comp1").geom("geom1").feature("pi6").setEntry("selcontributetobnd", "pi6_sel5", "csel6");
    model.component("comp1").geom("geom1").feature("pi6").setEntry("selcontributetobnd", "pi6_sel6", "csel6");
    model.component("comp1").geom("geom1").feature("pi6").setEntry("selcontributetobnd", "pi6_sel7", "csel6");
    model.component("comp1").geom("geom1").run("pi6");
    model.component("comp1").geom("geom1").create("pi7", "PartInstance");
    model.component("comp1").geom("geom1").feature("pi7").set("selkeepnoncontr", false);
    model.component("comp1").geom("geom1").feature("pi7").set("part", "part1");
    model.component("comp1").geom("geom1").feature("pi7").label("\u900f\u955c 6");
    model.component("comp1").geom("geom1").feature("pi7").setEntry("inputname", "R1", "R1");
    model.component("comp1").geom("geom1").feature("pi7").setEntry("inputname", "R2", "R2");
    model.component("comp1").geom("geom1").feature("pi7").setEntry("inputname", "Tc", "Tc");
    model.component("comp1").geom("geom1").feature("pi7").setEntry("inputname", "d0", "d0");
    model.component("comp1").geom("geom1").feature("pi7").setEntry("inputname", "d1", "d1");
    model.component("comp1").geom("geom1").feature("pi7").setEntry("inputname", "d2", "d2");
    model.component("comp1").geom("geom1").feature("pi7").setEntry("inputname", "d1_clear", "d1_clear");
    model.component("comp1").geom("geom1").feature("pi7").setEntry("inputname", "d2_clear", "d2_clear");
    model.component("comp1").geom("geom1").feature("pi7").setEntry("inputname", "nix", "nix");
    model.component("comp1").geom("geom1").feature("pi7").setEntry("inputname", "niy", "niy");
    model.component("comp1").geom("geom1").feature("pi7").setEntry("inputname", "niz", "niz");
    model.component("comp1").geom("geom1").feature("pi7").setEntry("inputname", "n_extra_r", "n_extra_r");
    model.component("comp1").geom("geom1").feature("pi7").setEntry("inputname", "n_extra_a", "n_extra_a");
    model.component("comp1").geom("geom1").feature("pi7").setEntry("inputexpr", "R1", "R1_7");
    model.component("comp1").geom("geom1").feature("pi7").setEntry("inputexpr", "R2", "R2_7");
    model.component("comp1").geom("geom1").feature("pi7").setEntry("inputexpr", "Tc", "Tc_7");
    model.component("comp1").geom("geom1").feature("pi7").setEntry("inputexpr", "d0", "d0_7");
    model.component("comp1").geom("geom1").feature("pi7").setEntry("inputexpr", "d1", "d1_7");
    model.component("comp1").geom("geom1").feature("pi7").setEntry("inputexpr", "d2", "d2_7");
    model.component("comp1").geom("geom1").feature("pi7").setEntry("inputexpr", "d1_clear", "d1_clear_7");
    model.component("comp1").geom("geom1").feature("pi7").setEntry("inputexpr", "d2_clear", "d2_clear_7");
    model.component("comp1").geom("geom1").feature("pi7").setEntry("inputexpr", "nix", "0");
    model.component("comp1").geom("geom1").feature("pi7").setEntry("inputexpr", "niy", "0");
    model.component("comp1").geom("geom1").feature("pi7").setEntry("inputexpr", "niz", "1");
    model.component("comp1").geom("geom1").feature("pi7").setEntry("inputexpr", "n_extra_r", "0");
    model.component("comp1").geom("geom1").feature("pi7").setEntry("inputexpr", "n_extra_a", "0");
    model.component("comp1").geom("geom1").feature("pi7").set("workplanesrc", "pi6");
    model.component("comp1").geom("geom1").feature("pi7").set("workplane", "wp2");
    model.component("comp1").geom("geom1").feature("pi7").set("displ", new String[]{"0", "0", "T_6"});
    model.component("comp1").geom("geom1").feature("pi7").setEntry("selcontributetodom", "pi7_sel1", "csel2");

    return model;
  }

  public static Model run2(Model model) {
    model.component("comp1").geom("geom1").feature("pi7").setEntry("selcontributetobnd", "pi7_sel2", "csel4");
    model.component("comp1").geom("geom1").feature("pi7").setEntry("selcontributetobnd", "pi7_sel3", "csel5");
    model.component("comp1").geom("geom1").feature("pi7").setEntry("selcontributetobnd", "pi7_sel4", "csel5");
    model.component("comp1").geom("geom1").feature("pi7").setEntry("selcontributetobnd", "pi7_sel5", "csel6");
    model.component("comp1").geom("geom1").feature("pi7").setEntry("selcontributetobnd", "pi7_sel6", "csel6");
    model.component("comp1").geom("geom1").feature("pi7").setEntry("selcontributetobnd", "pi7_sel7", "csel6");
    model.component("comp1").geom("geom1").run("pi7");
    model.component("comp1").geom("geom1").create("pi8", "PartInstance");
    model.component("comp1").geom("geom1").feature("pi8").set("selkeepnoncontr", false);
    model.component("comp1").geom("geom1").feature("pi8").set("part", "part2");
    model.component("comp1").geom("geom1").feature("pi8").label("\u50cf");
    model.component("comp1").geom("geom1").feature("pi8").setEntry("inputexpr", "d0", "d0_D");
    model.component("comp1").geom("geom1").feature("pi8").setEntry("inputexpr", "d1", 0);
    model.component("comp1").geom("geom1").feature("pi8").set("workplanesrc", "pi7");
    model.component("comp1").geom("geom1").feature("pi8").set("workplane", "wp2");
    model.component("comp1").geom("geom1").feature("pi8").set("displ", new String[]{"0", "0", "T_7"});
    model.component("comp1").geom("geom1").feature("pi8").setEntry("selcontributetobnd", "pi8_sel1", "csel8");
    model.component("comp1").geom("geom1").runPre("fin");

    model.title(null);

    model.description("");

    model.label("double_gauss_lens_geom_sequence.mph");

    return model;
  }

  public static void main(String[] args) {
    Model model = run();
    run2(model);
  }

}
