/*
 * petzval_lens_optimization_geom_sequence.java
 */

import com.comsol.model.*;
import com.comsol.model.util.*;

/** Model exported on Apr 30 2026, 12:19 by COMSOL 6.3.0.290. */
public class petzval_lens_optimization_geom_sequence {

  public static Model run() {
    Model model = ModelUtil.create("Model");

    model
         .modelPath("D:\\Program Files\\COMSOL\\COMSOL63\\Multiphysics\\applications\\Ray_Optics_Module\\Lenses_Cameras_and_Telescopes");

    model.component().create("comp1", true);

    model.component("comp1").geom().create("geom1", 3);
    model.component("comp1").geom("geom1").geomRep("comsol");

    model.component("comp1").mesh().create("mesh1");
    model.component("comp1").mesh("mesh1").contribute("geom/detail", true);

//    To import content from file, use:
//    model.param().loadFile("FILENAME");
    model.param().set("nix", "0", "\u5168\u5c40\u5149\u8f74\uff0cx \u5206\u91cf");
    model.param().set("niy", "0", "\u5168\u5c40\u5149\u8f74\uff0cy \u5206\u91cf");
    model.param().set("niz", "1", "\u5168\u5c40\u5149\u8f74\uff0cz \u5206\u91cf");
    model.param().set("R1_1", "99.56266[mm]", "L1\uff0c\u8868\u9762 1 \u7684\u66f2\u7387\u534a\u5f84");
    model.param().set("R2_1", "-86.84002[mm]", "L1\uff0c\u8868\u9762 2 \u7684\u66f2\u7387\u534a\u5f84");
    model.param().set("Tc_1", "13.000[mm]", "L1 \u4e2d\u5fc3\u539a\u5ea6");
    model.param().set("d0_1", "58.000[mm]", "L1\uff0c\u5916\u5f84");
    model.param().set("d1_1", "0", "L1\uff0c\u8868\u9762 1 \u7684\u76f4\u5f84");
    model.param().set("d2_1", "0", "L1\uff0c\u8868\u9762 2 \u7684\u76f4\u5f84");
    model.param().set("d1_clear_1", "2*28.478[mm]", "L1\uff0c\u8868\u9762 1 \u7684\u901a\u5149\u5b54\u5f84");
    model.param().set("d2_clear_1", "2*26.267[mm]", "L1\uff0c\u8868\u9762 2 \u7684\u901a\u5149\u5b54\u5f84");
    model.param().set("T_1", "0.000[mm]", "L1 \u5230 L2 \u7684\u95f4\u8ddd");
    model.param().set("R1_2", "R2_1", "L2\uff0c\u8868\u9762 1 \u7684\u66f2\u7387\u534a\u5f84");
    model.param().set("R2_2", "-1187.63858[mm]", "L2\uff0c\u8868\u9762 2 \u7684\u66f2\u7387\u534a\u5f84");
    model.param().set("Tc_2", "4.000[mm]", "L2 \u4e2d\u5fc3\u539a\u5ea6");
    model.param().set("d0_2", "58.000[mm]", "L2\uff0c\u5916\u5f84");
    model.param().set("d1_2", "0", "L2\uff0c\u8868\u9762 1 \u7684\u76f4\u5f84");
    model.param().set("d2_2", "0", "L2\uff0c\u8868\u9762 2 \u7684\u76f4\u5f84");
    model.param().set("d1_clear_2", "d2_clear_1", "L2\uff0c\u8868\u9762 1 \u7684\u901a\u5149\u5b54\u5f84");
    model.param().set("d2_clear_2", "2*20.020[mm]", "L2\uff0c\u8868\u9762 2 \u7684\u901a\u5149\u5b54\u5f84");
    model.param().set("T_2", "40.000[mm]", "L2 \u5230\u5149\u9611\u7684\u95f4\u8ddd");
    model.param().set("Tc_3", "0", "\u5149\u9611\u4e2d\u5fc3\u539a\u5ea6");
    model.param().set("d0_S", "d0_1", "\u5149\u9611\u6700\u5927\u76f4\u5f84");
    model.param().set("d1_S", "2*16.631[mm]", "\u5149\u9611\u5b54\u5f84");
    model.param().set("T_3", "40.000[mm]", "\u5149\u9611\u5230 L3 \u7684\u95f4\u8ddd");
    model.param().set("R1_4", "57.47191[mm]", "L3\uff0c\u8868\u9762 1 \u7684\u66f2\u7387\u534a\u5f84");
    model.param().set("R2_4", "-54.61865[mm]", "L3\uff0c\u8868\u9762 2 \u7684\u66f2\u7387\u534a\u5f84");
    model.param().set("Tc_4", "12.000[mm]", "L3 \u4e2d\u5fc3\u539a\u5ea6");
    model.param().set("d0_4", "45.000[mm]", "L3\uff0c\u5916\u5f84");
    model.param().set("d1_4", "0", "L3\uff0c\u8868\u9762 1 \u7684\u76f4\u5f84");
    model.param().set("d2_4", "0", "L3\uff0c\u8868\u9762 2 \u7684\u76f4\u5f84");
    model.param().set("d1_clear_4", "2*20.543[mm]", "L3\uff0c\u8868\u9762 1 \u7684\u901a\u5149\u5b54\u5f84");
    model.param().set("d2_clear_4", "2*20.074[mm]", "L3\uff0c\u8868\u9762 2 \u7684\u901a\u5149\u5b54\u5f84");
    model.param().set("T_4", "0.000[mm]", "L3 \u5230 L4 \u7684\u95f4\u8ddd");
    model.param().set("R1_5", "R2_4", "L4\uff0c\u8868\u9762 1 \u7684\u66f2\u7387\u534a\u5f84");
    model.param().set("R2_5", "-614.68633[mm]", "L4\uff0c\u8868\u9762 2 \u7684\u66f2\u7387\u534a\u5f84");
    model.param().set("Tc_5", "3.000[mm]", "L4 \u4e2d\u5fc3\u539a\u5ea6");
    model.param().set("d0_5", "45.000[mm]", "L4\uff0c\u5916\u5f84");
    model.param().set("d1_5", "0", "L4\uff0c\u8868\u9762 1 \u7684\u76f4\u5f84");
    model.param().set("d2_5", "0", "L4\uff0c\u8868\u9762 2 \u7684\u76f4\u5f84");
    model.param().set("d1_clear_5", "d2_clear_4", "L4\uff0c\u8868\u9762 1 \u7684\u901a\u5149\u5b54\u5f84");
    model.param().set("d2_clear_5", "2*16.492[mm]", "L4\uff0c\u8868\u9762 2 \u7684\u901a\u5149\u5b54\u5f84");
    model.param().set("T_5", "46.82210[mm]", "L4 \u5230 L5 \u7684\u95f4\u8ddd");
    model.param().set("R1_6", "-38.17110[mm]", "L5\uff0c\u8868\u9762 1 \u7684\u66f2\u7387\u534a\u5f84");
    model.param().set("R2_6", "0", "L5\uff0c\u8868\u9762 2 \u7684\u66f2\u7387\u534a\u5f84");
    model.param().set("Tc_6", "2.000[mm]", "L5 \u4e2d\u5fc3\u539a\u5ea6");
    model.param().set("d0_6", "42.500[mm]", "L5\uff0c\u5916\u5f84");
    model.param().set("d1_6", "40.000[mm]", "L5\uff0c\u8868\u9762 1 \u7684\u76f4\u5f84");
    model.param().set("d2_6", "0", "L5\uff0c\u8868\u9762 2 \u7684\u76f4\u5f84");
    model.param().set("d1_clear_6", "2*17.297[mm]", "L5\uff0c\u8868\u9762 1 \u7684\u901a\u5149\u5b54\u5f84");
    model.param().set("d2_clear_6", "2*18.940[mm]", "L5\uff0c\u8868\u9762 2 \u7684\u901a\u5149\u5b54\u5f84");
    model.param()
         .set("T_6", "1.9548[mm]", "L5 \u5230\u68c0\u6d4b\u5668\u7684\u95f4\u8ddd\uff08\u5df2\u8c03\u6574\uff09");
    model.param().set("d0_D", "2*17.904[mm]", "\u68c0\u6d4b\u5668\u76f4\u5f84");

    model.component("comp1").geom("geom1").label("Petzval \u900f\u955c\u51e0\u4f55\u5e8f\u5217");
    model.component("comp1").geom("geom1").lengthUnit("mm");
    model.geom()
         .load(new String[]{"part1"}, "Ray_Optics_Module\\3D\\Spherical_Lenses\\spherical_lens_3d.mph", new String[]{"part1"});
    model.component("comp1").geom("geom1").create("pi1", "PartInstance");
    model.component("comp1").geom("geom1").feature("pi1").set("selkeepnoncontr", false);
    model.component("comp1").geom("geom1").feature("pi1").set("part", "part1");
    model.component("comp1").geom("geom1").feature("pi1").label("\u900f\u955c 1");
    model.component("comp1").geom("geom1").feature("pi1").setEntry("inputname", "R1", "R1");
    model.component("comp1").geom("geom1").feature("pi1").setEntry("inputname", "R2", "R2");
    model.component("comp1").geom("geom1").feature("pi1").setEntry("inputname", "Tc", "Tc");
    model.component("comp1").geom("geom1").feature("pi1").setEntry("inputname", "d0", "d0");
    model.component("comp1").geom("geom1").feature("pi1").setEntry("inputname", "d1", "d1");
    model.component("comp1").geom("geom1").feature("pi1").setEntry("inputname", "d2", "d2");
    model.component("comp1").geom("geom1").feature("pi1").setEntry("inputname", "d1_clear", "d1_clear");
    model.component("comp1").geom("geom1").feature("pi1").setEntry("inputname", "d2_clear", "d2_clear");
    model.component("comp1").geom("geom1").feature("pi1").setEntry("inputname", "nix", "nix");
    model.component("comp1").geom("geom1").feature("pi1").setEntry("inputname", "niy", "niy");
    model.component("comp1").geom("geom1").feature("pi1").setEntry("inputname", "niz", "niz");
    model.component("comp1").geom("geom1").feature("pi1").setEntry("inputname", "n_extra_r", "n_extra_r");
    model.component("comp1").geom("geom1").feature("pi1").setEntry("inputname", "n_extra_a", "n_extra_a");
    model.component("comp1").geom("geom1").feature("pi1").setEntry("inputexpr", "R1", "R1_1");
    model.component("comp1").geom("geom1").feature("pi1").setEntry("inputexpr", "R2", "R2_1");
    model.component("comp1").geom("geom1").feature("pi1").setEntry("inputexpr", "Tc", "Tc_1");
    model.component("comp1").geom("geom1").feature("pi1").setEntry("inputexpr", "d0", "d0_1");
    model.component("comp1").geom("geom1").feature("pi1").setEntry("inputexpr", "d1", "d1_1");
    model.component("comp1").geom("geom1").feature("pi1").setEntry("inputexpr", "d2", "d2_1");
    model.component("comp1").geom("geom1").feature("pi1").setEntry("inputexpr", "d1_clear", "d1_clear_1");
    model.component("comp1").geom("geom1").feature("pi1").setEntry("inputexpr", "d2_clear", "d2_clear_1");
    model.component("comp1").geom("geom1").feature("pi1").setEntry("inputexpr", "nix", "nix");
    model.component("comp1").geom("geom1").feature("pi1").setEntry("inputexpr", "niy", "niy");
    model.component("comp1").geom("geom1").feature("pi1").setEntry("inputexpr", "niz", "niz");
    model.component("comp1").geom("geom1").feature("pi1").setEntry("inputexpr", "n_extra_r", "0");
    model.component("comp1").geom("geom1").feature("pi1").setEntry("inputexpr", "n_extra_a", "0");
    model.component("comp1").geom("geom1").run("pi1");
    model.component("comp1").geom("geom1").selection().create("csel1", "CumulativeSelection");
    model.component("comp1").geom("geom1").selection("csel1").label("\u900f\u955c\u6750\u6599 1");
    model.component("comp1").geom("geom1").selection().create("csel2", "CumulativeSelection");
    model.component("comp1").geom("geom1").selection("csel2").label("\u900f\u955c\u6750\u6599 2");
    model.component("comp1").geom("geom1").selection().create("csel3", "CumulativeSelection");
    model.component("comp1").geom("geom1").selection("csel3").label("\u900f\u955c\u6750\u6599 3");
    model.component("comp1").geom("geom1").selection().create("csel4", "CumulativeSelection");
    model.component("comp1").geom("geom1").selection("csel4").label("\u900f\u955c\u6750\u6599 4");
    model.component("comp1").geom("geom1").selection().create("csel5", "CumulativeSelection");
    model.component("comp1").geom("geom1").selection("csel5").label("\u900f\u955c\u5916\u90e8");
    model.component("comp1").geom("geom1").selection().create("csel6", "CumulativeSelection");
    model.component("comp1").geom("geom1").selection("csel6").label("\u901a\u5149\u5b54\u5f84");
    model.component("comp1").geom("geom1").selection().create("csel7", "CumulativeSelection");
    model.component("comp1").geom("geom1").selection("csel7").label("\u969c\u788d\u7269");
    model.component("comp1").geom("geom1").selection().create("csel8", "CumulativeSelection");
    model.component("comp1").geom("geom1").selection("csel8").label("\u5b54\u5f84\u5149\u9611");
    model.component("comp1").geom("geom1").selection().create("csel9", "CumulativeSelection");
    model.component("comp1").geom("geom1").selection("csel9").label("\u50cf\u5e73\u9762");
    model.component("comp1").geom("geom1").feature("pi1").setEntry("selcontributetodom", "pi1_sel1", "csel1");
    model.component("comp1").geom("geom1").feature("pi1").setEntry("selcontributetobnd", "pi1_sel2", "csel5");
    model.component("comp1").geom("geom1").feature("pi1").setEntry("selcontributetobnd", "pi1_sel3", "csel6");
    model.component("comp1").geom("geom1").feature("pi1").setEntry("selcontributetobnd", "pi1_sel4", "csel6");
    model.component("comp1").geom("geom1").feature("pi1").setEntry("selcontributetobnd", "pi1_sel5", "csel7");
    model.component("comp1").geom("geom1").feature("pi1").setEntry("selcontributetobnd", "pi1_sel6", "csel7");
    model.component("comp1").geom("geom1").feature("pi1").setEntry("selcontributetobnd", "pi1_sel7", "csel7");
    model.component("comp1").geom("geom1").create("pi2", "PartInstance");
    model.component("comp1").geom("geom1").feature("pi2").set("selkeepnoncontr", false);
    model.component("comp1").geom("geom1").feature("pi2").set("part", "part1");
    model.component("comp1").geom("geom1").feature("pi2").label("\u900f\u955c 2");
    model.component("comp1").geom("geom1").feature("pi2").setEntry("inputname", "R1", "R1");
    model.component("comp1").geom("geom1").feature("pi2").setEntry("inputname", "R2", "R2");
    model.component("comp1").geom("geom1").feature("pi2").setEntry("inputname", "Tc", "Tc");
    model.component("comp1").geom("geom1").feature("pi2").setEntry("inputname", "d0", "d0");
    model.component("comp1").geom("geom1").feature("pi2").setEntry("inputname", "d1", "d1");
    model.component("comp1").geom("geom1").feature("pi2").setEntry("inputname", "d2", "d2");
    model.component("comp1").geom("geom1").feature("pi2").setEntry("inputname", "d1_clear", "d1_clear");
    model.component("comp1").geom("geom1").feature("pi2").setEntry("inputname", "d2_clear", "d2_clear");
    model.component("comp1").geom("geom1").feature("pi2").setEntry("inputname", "nix", "nix");
    model.component("comp1").geom("geom1").feature("pi2").setEntry("inputname", "niy", "niy");
    model.component("comp1").geom("geom1").feature("pi2").setEntry("inputname", "niz", "niz");
    model.component("comp1").geom("geom1").feature("pi2").setEntry("inputname", "n_extra_r", "n_extra_r");
    model.component("comp1").geom("geom1").feature("pi2").setEntry("inputname", "n_extra_a", "n_extra_a");
    model.component("comp1").geom("geom1").feature("pi2").setEntry("inputexpr", "R1", "R1_2");
    model.component("comp1").geom("geom1").feature("pi2").setEntry("inputexpr", "R2", "R2_2");
    model.component("comp1").geom("geom1").feature("pi2").setEntry("inputexpr", "Tc", "Tc_2");
    model.component("comp1").geom("geom1").feature("pi2").setEntry("inputexpr", "d0", "d0_2");
    model.component("comp1").geom("geom1").feature("pi2").setEntry("inputexpr", "d1", "d1_2");
    model.component("comp1").geom("geom1").feature("pi2").setEntry("inputexpr", "d2", "d2_2");
    model.component("comp1").geom("geom1").feature("pi2").setEntry("inputexpr", "d1_clear", "d1_clear_2");
    model.component("comp1").geom("geom1").feature("pi2").setEntry("inputexpr", "d2_clear", "d2_clear_2");
    model.component("comp1").geom("geom1").feature("pi2").setEntry("inputexpr", "nix", "0");
    model.component("comp1").geom("geom1").feature("pi2").setEntry("inputexpr", "niy", "0");
    model.component("comp1").geom("geom1").feature("pi2").setEntry("inputexpr", "niz", "1");
    model.component("comp1").geom("geom1").feature("pi2").setEntry("inputexpr", "n_extra_r", "0");
    model.component("comp1").geom("geom1").feature("pi2").setEntry("inputexpr", "n_extra_a", "0");
    model.component("comp1").geom("geom1").feature("pi2").set("workplanesrc", "pi1");
    model.component("comp1").geom("geom1").feature("pi2").set("workplane", "wp2");
    model.component("comp1").geom("geom1").feature("pi2").set("displ", new String[]{"0", "0", "T_1"});
    model.component("comp1").geom("geom1").feature("pi2").setEntry("selcontributetodom", "pi2_sel1", "csel2");
    model.component("comp1").geom("geom1").feature("pi2").setEntry("selcontributetobnd", "pi2_sel2", "csel5");
    model.component("comp1").geom("geom1").feature("pi2").setEntry("selcontributetobnd", "pi2_sel3", "csel6");
    model.component("comp1").geom("geom1").feature("pi2").setEntry("selcontributetobnd", "pi2_sel4", "csel6");
    model.component("comp1").geom("geom1").feature("pi2").setEntry("selcontributetobnd", "pi2_sel5", "csel7");
    model.component("comp1").geom("geom1").feature("pi2").setEntry("selcontributetobnd", "pi2_sel6", "csel7");
    model.component("comp1").geom("geom1").feature("pi2").setEntry("selcontributetobnd", "pi2_sel7", "csel7");
    model.geom()
         .load(new String[]{"part2"}, "Ray_Optics_Module\\3D\\Apertures_and_Obstructions\\circular_planar_annulus.mph", new String[]{"part1"});
    model.component("comp1").geom("geom1").run("pi2");
    model.component("comp1").geom("geom1").create("pi3", "PartInstance");
    model.component("comp1").geom("geom1").feature("pi3").set("selkeepnoncontr", false);
    model.component("comp1").geom("geom1").feature("pi3").set("part", "part2");
    model.component("comp1").geom("geom1").feature("pi3").label("\u5149\u9611");
    model.component("comp1").geom("geom1").feature("pi3").setEntry("inputexpr", "d0", "d0_S");
    model.component("comp1").geom("geom1").feature("pi3").setEntry("inputexpr", "d1", "d1_S");
    model.component("comp1").geom("geom1").feature("pi3").set("workplanesrc", "pi2");
    model.component("comp1").geom("geom1").feature("pi3").set("workplane", "wp2");
    model.component("comp1").geom("geom1").feature("pi3").set("displ", new String[]{"0", "0", "T_2+Tc_3"});
    model.component("comp1").geom("geom1").feature("pi3").setEntry("selcontributetobnd", "pi3_sel1", "csel8");
    model.component("comp1").geom("geom1").run("pi3");
    model.component("comp1").geom("geom1").create("pi4", "PartInstance");
    model.component("comp1").geom("geom1").feature("pi4").set("selkeepnoncontr", false);
    model.component("comp1").geom("geom1").feature("pi4").set("part", "part1");
    model.component("comp1").geom("geom1").feature("pi4").label("\u900f\u955c 3");
    model.component("comp1").geom("geom1").feature("pi4").setEntry("inputname", "R1", "R1");
    model.component("comp1").geom("geom1").feature("pi4").setEntry("inputname", "R2", "R2");
    model.component("comp1").geom("geom1").feature("pi4").setEntry("inputname", "Tc", "Tc");
    model.component("comp1").geom("geom1").feature("pi4").setEntry("inputname", "d0", "d0");
    model.component("comp1").geom("geom1").feature("pi4").setEntry("inputname", "d1", "d1");
    model.component("comp1").geom("geom1").feature("pi4").setEntry("inputname", "d2", "d2");
    model.component("comp1").geom("geom1").feature("pi4").setEntry("inputname", "d1_clear", "d1_clear");
    model.component("comp1").geom("geom1").feature("pi4").setEntry("inputname", "d2_clear", "d2_clear");
    model.component("comp1").geom("geom1").feature("pi4").setEntry("inputname", "nix", "nix");
    model.component("comp1").geom("geom1").feature("pi4").setEntry("inputname", "niy", "niy");
    model.component("comp1").geom("geom1").feature("pi4").setEntry("inputname", "niz", "niz");
    model.component("comp1").geom("geom1").feature("pi4").setEntry("inputname", "n_extra_r", "n_extra_r");
    model.component("comp1").geom("geom1").feature("pi4").setEntry("inputname", "n_extra_a", "n_extra_a");
    model.component("comp1").geom("geom1").feature("pi4").setEntry("inputexpr", "R1", "R1_4");
    model.component("comp1").geom("geom1").feature("pi4").setEntry("inputexpr", "R2", "R2_4");
    model.component("comp1").geom("geom1").feature("pi4").setEntry("inputexpr", "Tc", "Tc_4");
    model.component("comp1").geom("geom1").feature("pi4").setEntry("inputexpr", "d0", "d0_4");
    model.component("comp1").geom("geom1").feature("pi4").setEntry("inputexpr", "d1", "d1_4");
    model.component("comp1").geom("geom1").feature("pi4").setEntry("inputexpr", "d2", "d2_4");
    model.component("comp1").geom("geom1").feature("pi4").setEntry("inputexpr", "d1_clear", "d1_clear_4");
    model.component("comp1").geom("geom1").feature("pi4").setEntry("inputexpr", "d2_clear", "d2_clear_4");
    model.component("comp1").geom("geom1").feature("pi4").setEntry("inputexpr", "nix", "0");
    model.component("comp1").geom("geom1").feature("pi4").setEntry("inputexpr", "niy", "0");
    model.component("comp1").geom("geom1").feature("pi4").setEntry("inputexpr", "niz", "1");
    model.component("comp1").geom("geom1").feature("pi4").setEntry("inputexpr", "n_extra_r", "0");
    model.component("comp1").geom("geom1").feature("pi4").setEntry("inputexpr", "n_extra_a", "0");
    model.component("comp1").geom("geom1").feature("pi4").set("workplanesrc", "pi3");
    model.component("comp1").geom("geom1").feature("pi4").set("workplane", "wp1");
    model.component("comp1").geom("geom1").feature("pi4").set("displ", new String[]{"0", "0", "T_3"});
    model.component("comp1").geom("geom1").feature("pi4").setEntry("selcontributetodom", "pi4_sel1", "csel3");
    model.component("comp1").geom("geom1").feature("pi4").setEntry("selcontributetobnd", "pi4_sel2", "csel5");
    model.component("comp1").geom("geom1").feature("pi4").setEntry("selcontributetobnd", "pi4_sel3", "csel6");
    model.component("comp1").geom("geom1").feature("pi4").setEntry("selcontributetobnd", "pi4_sel4", "csel6");
    model.component("comp1").geom("geom1").feature("pi4").setEntry("selcontributetobnd", "pi4_sel5", "csel7");
    model.component("comp1").geom("geom1").feature("pi4").setEntry("selcontributetobnd", "pi4_sel6", "csel7");
    model.component("comp1").geom("geom1").feature("pi4").setEntry("selcontributetobnd", "pi4_sel7", "csel7");
    model.component("comp1").geom("geom1").run("pi4");
    model.component("comp1").geom("geom1").create("pi5", "PartInstance");
    model.component("comp1").geom("geom1").feature("pi5").set("selkeepnoncontr", false);
    model.component("comp1").geom("geom1").feature("pi5").set("part", "part1");
    model.component("comp1").geom("geom1").feature("pi5").label("\u900f\u955c 4");
    model.component("comp1").geom("geom1").feature("pi5").setEntry("inputname", "R1", "R1");
    model.component("comp1").geom("geom1").feature("pi5").setEntry("inputname", "R2", "R2");
    model.component("comp1").geom("geom1").feature("pi5").setEntry("inputname", "Tc", "Tc");
    model.component("comp1").geom("geom1").feature("pi5").setEntry("inputname", "d0", "d0");
    model.component("comp1").geom("geom1").feature("pi5").setEntry("inputname", "d1", "d1");
    model.component("comp1").geom("geom1").feature("pi5").setEntry("inputname", "d2", "d2");
    model.component("comp1").geom("geom1").feature("pi5").setEntry("inputname", "d1_clear", "d1_clear");
    model.component("comp1").geom("geom1").feature("pi5").setEntry("inputname", "d2_clear", "d2_clear");
    model.component("comp1").geom("geom1").feature("pi5").setEntry("inputname", "nix", "nix");
    model.component("comp1").geom("geom1").feature("pi5").setEntry("inputname", "niy", "niy");
    model.component("comp1").geom("geom1").feature("pi5").setEntry("inputname", "niz", "niz");
    model.component("comp1").geom("geom1").feature("pi5").setEntry("inputname", "n_extra_r", "n_extra_r");
    model.component("comp1").geom("geom1").feature("pi5").setEntry("inputname", "n_extra_a", "n_extra_a");
    model.component("comp1").geom("geom1").feature("pi5").setEntry("inputexpr", "R1", "R1_5");
    model.component("comp1").geom("geom1").feature("pi5").setEntry("inputexpr", "R2", "R2_5");
    model.component("comp1").geom("geom1").feature("pi5").setEntry("inputexpr", "Tc", "Tc_5");
    model.component("comp1").geom("geom1").feature("pi5").setEntry("inputexpr", "d0", "d0_5");
    model.component("comp1").geom("geom1").feature("pi5").setEntry("inputexpr", "d1", "d1_5");
    model.component("comp1").geom("geom1").feature("pi5").setEntry("inputexpr", "d2", "d2_5");
    model.component("comp1").geom("geom1").feature("pi5").setEntry("inputexpr", "d1_clear", "d1_clear_5");
    model.component("comp1").geom("geom1").feature("pi5").setEntry("inputexpr", "d2_clear", "d2_clear_5");
    model.component("comp1").geom("geom1").feature("pi5").setEntry("inputexpr", "nix", "0");
    model.component("comp1").geom("geom1").feature("pi5").setEntry("inputexpr", "niy", "0");
    model.component("comp1").geom("geom1").feature("pi5").setEntry("inputexpr", "niz", "1");
    model.component("comp1").geom("geom1").feature("pi5").setEntry("inputexpr", "n_extra_r", "0");
    model.component("comp1").geom("geom1").feature("pi5").setEntry("inputexpr", "n_extra_a", "0");
    model.component("comp1").geom("geom1").feature("pi5").set("workplanesrc", "pi4");
    model.component("comp1").geom("geom1").feature("pi5").set("workplane", "wp2");
    model.component("comp1").geom("geom1").feature("pi5").set("displ", new String[]{"0", "0", "T_4"});
    model.component("comp1").geom("geom1").feature("pi5").setEntry("selcontributetodom", "pi5_sel1", "csel4");
    model.component("comp1").geom("geom1").feature("pi5").setEntry("selcontributetobnd", "pi5_sel2", "csel5");
    model.component("comp1").geom("geom1").feature("pi5").setEntry("selcontributetobnd", "pi5_sel3", "csel6");
    model.component("comp1").geom("geom1").feature("pi5").setEntry("selcontributetobnd", "pi5_sel4", "csel6");
    model.component("comp1").geom("geom1").feature("pi5").setEntry("selcontributetobnd", "pi5_sel5", "csel7");
    model.component("comp1").geom("geom1").feature("pi5").setEntry("selcontributetobnd", "pi5_sel6", "csel7");
    model.component("comp1").geom("geom1").feature("pi5").setEntry("selcontributetobnd", "pi5_sel7", "csel7");
    model.component("comp1").geom("geom1").run("pi5");
    model.component("comp1").geom("geom1").create("pi6", "PartInstance");
    model.component("comp1").geom("geom1").feature("pi6").set("selkeepnoncontr", false);
    model.component("comp1").geom("geom1").feature("pi6").set("part", "part1");
    model.component("comp1").geom("geom1").feature("pi6").label("\u900f\u955c 5");
    model.component("comp1").geom("geom1").feature("pi6").setEntry("inputname", "R1", "R1");
    model.component("comp1").geom("geom1").feature("pi6").setEntry("inputname", "R2", "R2");
    model.component("comp1").geom("geom1").feature("pi6").setEntry("inputname", "Tc", "Tc");
    model.component("comp1").geom("geom1").feature("pi6").setEntry("inputname", "d0", "d0");
    model.component("comp1").geom("geom1").feature("pi6").setEntry("inputname", "d1", "d1");
    model.component("comp1").geom("geom1").feature("pi6").setEntry("inputname", "d2", "d2");
    model.component("comp1").geom("geom1").feature("pi6").setEntry("inputname", "d1_clear", "d1_clear");
    model.component("comp1").geom("geom1").feature("pi6").setEntry("inputname", "d2_clear", "d2_clear");
    model.component("comp1").geom("geom1").feature("pi6").setEntry("inputname", "nix", "nix");
    model.component("comp1").geom("geom1").feature("pi6").setEntry("inputname", "niy", "niy");
    model.component("comp1").geom("geom1").feature("pi6").setEntry("inputname", "niz", "niz");
    model.component("comp1").geom("geom1").feature("pi6").setEntry("inputname", "n_extra_r", "n_extra_r");
    model.component("comp1").geom("geom1").feature("pi6").setEntry("inputname", "n_extra_a", "n_extra_a");
    model.component("comp1").geom("geom1").feature("pi6").setEntry("inputexpr", "R1", "R1_6");
    model.component("comp1").geom("geom1").feature("pi6").setEntry("inputexpr", "R2", "R2_6");
    model.component("comp1").geom("geom1").feature("pi6").setEntry("inputexpr", "Tc", "Tc_6");
    model.component("comp1").geom("geom1").feature("pi6").setEntry("inputexpr", "d0", "d0_6");
    model.component("comp1").geom("geom1").feature("pi6").setEntry("inputexpr", "d1", "d1_6");
    model.component("comp1").geom("geom1").feature("pi6").setEntry("inputexpr", "d2", "d2_6");
    model.component("comp1").geom("geom1").feature("pi6").setEntry("inputexpr", "d1_clear", "d1_clear_6");
    model.component("comp1").geom("geom1").feature("pi6").setEntry("inputexpr", "d2_clear", "d2_clear_6");
    model.component("comp1").geom("geom1").feature("pi6").setEntry("inputexpr", "nix", "0");
    model.component("comp1").geom("geom1").feature("pi6").setEntry("inputexpr", "niy", "0");
    model.component("comp1").geom("geom1").feature("pi6").setEntry("inputexpr", "niz", "1");
    model.component("comp1").geom("geom1").feature("pi6").setEntry("inputexpr", "n_extra_r", "0");
    model.component("comp1").geom("geom1").feature("pi6").setEntry("inputexpr", "n_extra_a", "0");
    model.component("comp1").geom("geom1").feature("pi6").set("workplanesrc", "pi5");
    model.component("comp1").geom("geom1").feature("pi6").set("workplane", "wp2");
    model.component("comp1").geom("geom1").feature("pi6").set("displ", new String[]{"0", "0", "T_5"});
    model.component("comp1").geom("geom1").feature("pi6").setEntry("selcontributetodom", "pi6_sel1", "csel4");
    model.component("comp1").geom("geom1").feature("pi6").setEntry("selcontributetobnd", "pi6_sel2", "csel5");
    model.component("comp1").geom("geom1").feature("pi6").setEntry("selcontributetobnd", "pi6_sel3", "csel6");
    model.component("comp1").geom("geom1").feature("pi6").setEntry("selcontributetobnd", "pi6_sel4", "csel6");
    model.component("comp1").geom("geom1").feature("pi6").setEntry("selcontributetobnd", "pi6_sel5", "csel7");
    model.component("comp1").geom("geom1").feature("pi6").setEntry("selcontributetobnd", "pi6_sel6", "csel7");
    model.component("comp1").geom("geom1").feature("pi6").setEntry("selcontributetobnd", "pi6_sel7", "csel7");
    model.geom()
         .load(new String[]{"part3"}, "Ray_Optics_Module\\3D\\Apertures_and_Obstructions\\rectangular_planar_annulus.mph", new String[]{"part1"});
    model.component("comp1").geom("geom1").run("pi6");
    model.component("comp1").geom("geom1").create("pi7", "PartInstance");
    model.component("comp1").geom("geom1").feature("pi7").set("selkeepnoncontr", false);
    model.component("comp1").geom("geom1").feature("pi7").set("part", "part3");
    model.component("comp1").geom("geom1").feature("pi7").label("\u50cf");
    model.component("comp1").geom("geom1").feature("pi7").setEntry("inputexpr", "w0", "d0_D");
    model.component("comp1").geom("geom1").feature("pi7").setEntry("inputexpr", "h0", "d0_D");
    model.component("comp1").geom("geom1").feature("pi7").setEntry("inputexpr", "w1", 0);
    model.component("comp1").geom("geom1").feature("pi7").setEntry("inputexpr", "h1", 0);
    model.component("comp1").geom("geom1").feature("pi7").setEntry("inputexpr", "nwx", 1);
    model.component("comp1").geom("geom1").feature("pi7").setEntry("inputexpr", "nwy", 0);
    model.component("comp1").geom("geom1").feature("pi7").set("workplanesrc", "pi6");
    model.component("comp1").geom("geom1").feature("pi7").set("workplane", "wp2");
    model.component("comp1").geom("geom1").feature("pi7").set("displ", new String[]{"0", "0", "T_6"});
    model.component("comp1").geom("geom1").feature("pi7").setEntry("selcontributetobnd", "pi7_sel1", "csel9");
    model.component("comp1").geom("geom1").runPre("fin");
    model.component("comp1").geom("geom1").create("sel1", "ExplicitSelection");
    model.component("comp1").geom("geom1").feature("sel1").label("\u6240\u6709\u900f\u955c");
    model.component("comp1").geom("geom1").feature("sel1").selection("selection").set("pi1", 1);
    model.component("comp1").geom("geom1").feature("sel1").selection("selection").set("pi2", 1);
    model.component("comp1").geom("geom1").feature("sel1").selection("selection").set("pi4", 1);
    model.component("comp1").geom("geom1").feature("sel1").selection("selection").set("pi5", 1);
    model.component("comp1").geom("geom1").feature("sel1").selection("selection").set("pi6", 1);
    model.component("comp1").geom("geom1").run("sel1");
    model.component("comp1").geom("geom1").create("pi8", "PartInstance");
    model.component("comp1").geom("geom1").feature("pi8").set("selkeepnoncontr", false);
    model.component("comp1").geom("geom1").feature("pi8").set("part", "part2");
    model.component("comp1").geom("geom1").feature("pi8").label("\u7b2c 1 \u7ec4\u5b54\u5f84");
    model.component("comp1").geom("geom1").feature("pi8").setEntry("inputexpr", "d0", "1.25*d0_1");
    model.component("comp1").geom("geom1").feature("pi8").setEntry("inputexpr", "d1", "d0_1");
    model.component("comp1").geom("geom1").feature("pi8").set("workplanesrc", "pi1");
    model.component("comp1").geom("geom1").feature("pi8").set("workplane", "wp3");
    model.component("comp1").geom("geom1").feature("pi8").setEntry("selcontributetobnd", "pi8_sel1", "csel7");
    model.component("comp1").geom("geom1").run("pi8");
    model.component("comp1").geom("geom1").create("pi9", "PartInstance");
    model.component("comp1").geom("geom1").feature("pi9").set("selkeepnoncontr", false);
    model.component("comp1").geom("geom1").feature("pi9").set("part", "part2");
    model.component("comp1").geom("geom1").feature("pi9").label("\u7b2c 2 \u7ec4\u5b54\u5f84");
    model.component("comp1").geom("geom1").feature("pi9").setEntry("inputexpr", "d0", "1.25*d0_4");
    model.component("comp1").geom("geom1").feature("pi9").setEntry("inputexpr", "d1", "d0_4");
    model.component("comp1").geom("geom1").feature("pi9").set("workplanesrc", "pi4");
    model.component("comp1").geom("geom1").feature("pi9").set("workplane", "wp3");

    return model;
  }

  public static Model run2(Model model) {
    model.component("comp1").geom("geom1").feature("pi9").setEntry("selcontributetobnd", "pi9_sel1", "csel7");
    model.component("comp1").geom("geom1").run("pi9");
    model.component("comp1").geom("geom1").create("pi10", "PartInstance");
    model.component("comp1").geom("geom1").feature("pi10").set("selkeepnoncontr", false);
    model.component("comp1").geom("geom1").feature("pi10").set("part", "part2");
    model.component("comp1").geom("geom1").feature("pi10").label("\u7b2c 3 \u7ec4\u5b54\u5f84");
    model.component("comp1").geom("geom1").feature("pi10").setEntry("inputexpr", "d0", "1.25*d0_6");
    model.component("comp1").geom("geom1").feature("pi10").setEntry("inputexpr", "d1", "d0_6");
    model.component("comp1").geom("geom1").feature("pi10").set("workplanesrc", "pi6");
    model.component("comp1").geom("geom1").feature("pi10").set("workplane", "wp3");
    model.component("comp1").geom("geom1").feature("pi10").setEntry("selcontributetobnd", "pi10_sel1", "csel7");
    model.component("comp1").geom("geom1").run("fin");

    model.title(null);

    model.description("");

    model.label("petzval_lens_optimization_geom_sequence.mph");

    return model;
  }

  public static void main(String[] args) {
    Model model = run();
    run2(model);
  }

}
