/*
 * thin_domain.java
 */

import com.comsol.model.*;
import com.comsol.model.util.*;

/** Model exported on Apr 30 2026, 09:31 by COMSOL 6.3.0.290. */
public class thin_domain {

  public static Model run() {
    Model model = ModelUtil.create("Model");

    model
         .modelPath("D:\\Program Files\\COMSOL\\COMSOL63\\Multiphysics\\applications\\Chemical_Reaction_Engineering_Module\\Tutorials");

    model.component().create("comp1", true);

    model.component("comp1").geom().create("geom1", 2);

    model.component("comp1").mesh().create("mesh1");

    model.component("comp1").physics().create("tcs", "ConcentratedSpecies", "geom1");
    model.component("comp1").physics("tcs").field("massfraction").field("wA_2D");
    model.component("comp1").physics("tcs").field("massfraction").component(new String[]{"wA_2D", "wB_2D", "wC_2D"});
    model.component("comp1").physics().create("spf", "LaminarFlow", "geom1");

    model.study().create("std1");
    model.study("std1").create("stat", "Stationary");
    model.study("std1").feature("stat").setSolveFor("/physics/tcs", true);
    model.study("std1").feature("stat").setSolveFor("/physics/spf", true);

//    To import content from file, use:
//    model.param().loadFile("FILENAME");
    model.param().set("dz", "2[mm]", "\u9762\u5916\u539a\u5ea6");
    model.param().set("L", "10[cm]", "\u57df\u7684\u8fb9\u957f");
    model.param().set("W", "5[cm]", "\u57df\u7684\u8fb9\u5bbd");
    model.param().set("u0", "10[mm/s]", "\u5165\u53e3\u6d41\u4f53\u901f\u5ea6");
    model.param().set("rho", "1000[kg/m^3]", "\u6d41\u4f53\u5bc6\u5ea6");
    model.param().set("visc", "1e-3[s*Pa]", "\u6d41\u4f53\u52a8\u529b\u9ecf\u5ea6");
    model.param().set("kcw", "1e-3[kg/(m^2*s)]", "\u8d28\u91cf\u4f20\u9012\u7cfb\u6570");
    model.param().set("wA_in", "0.1", "\u7269\u8d28 A \u5165\u53e3\u8d28\u91cf\u5206\u6570");
    model.param().set("wB_in", "0.2", "\u7269\u8d28 B \u5165\u53e3\u8d28\u91cf\u5206\u6570");
    model.param().set("wC_in", "1-wA_in-wB_in", "\u7269\u8d28 C \u5165\u53e3\u8d28\u91cf\u5206\u6570");
    model.param().set("wA_wall", "0.30", "\u7269\u8d28 A \u754c\u9762\u8d28\u91cf\u5206\u6570");
    model.param().set("MW", "0.032[kg/mol]", "\u5206\u5b50\u91cf");

    model.component("comp1").geom("geom1").create("r1", "Rectangle");
    model.component("comp1").geom("geom1").feature("r1").set("size", new String[]{"L", "W/2"});
    model.component("comp1").geom("geom1").run("r1");
    model.component("comp1").geom("geom1").run();

    model.component("comp1").physics("tcs").prop("dz").set("dz", "dz");
    model.component("comp1").physics("tcs").prop("SpeciesProperties").set("FromMassConstraint", 3);
    model.component("comp1").physics("tcs").feature("sp1").setIndex("M_wA_2D", "MW", 0);
    model.component("comp1").physics("tcs").feature("sp1").setIndex("M_wB_2D", "MW", 0);
    model.component("comp1").physics("tcs").feature("sp1").setIndex("M_wC_2D", "MW", 0);
    model.component("comp1").physics("tcs").create("sym1", "Symmetry", 1);
    model.component("comp1").physics("tcs").feature("sym1").selection().set(2);
    model.component("comp1").physics("tcs").create("in1", "Inflow", 1);
    model.component("comp1").physics("tcs").feature("in1").setIndex("wbnd", "wA_in", 0);
    model.component("comp1").physics("tcs").feature("in1").setIndex("wbnd", "wB_in", 1);
    model.component("comp1").physics("tcs").feature("in1").selection().set(1);
    model.component("comp1").physics("tcs").create("out1", "Outflow", 1);
    model.component("comp1").physics("tcs").feature("out1").selection().set(4);
    model.component("comp1").physics("tcs").create("opf1", "OutOfPlaneFlux", 2);
    model.component("comp1").physics("tcs").feature("opf1").setIndex("speciesUp", true, 0);
    model.component("comp1").physics("tcs").feature("opf1").setIndex("j0_u", "kcw*(wA_wall-wA_2D)", 0);
    model.component("comp1").physics("tcs").feature("opf1").selection().set(1);
    model.component("comp1").physics("spf").prop("PhysicalModelProperty")
         .set("Compressibility", "CompressibleMALT03");
    model.component("comp1").physics("spf").prop("PhysicalModelProperty").set("ShallowChannelProperty", true);
    model.component("comp1").physics("spf").prop("PhysicalModelProperty").set("dz", "dz");
    model.component("comp1").physics("spf").feature("fp1").set("mu_mat", "userdef");
    model.component("comp1").physics("spf").feature("fp1").set("mu", "visc");
    model.component("comp1").physics("spf").create("sym1", "Symmetry", 1);
    model.component("comp1").physics("spf").feature("sym1").selection().set(2);
    model.component("comp1").physics("spf").create("inl1", "InletBoundary", 1);
    model.component("comp1").physics("spf").feature("inl1").selection().set(1);
    model.component("comp1").physics("spf").feature("inl1").set("BoundaryCondition", "FullyDevelopedFlow");
    model.component("comp1").physics("spf").feature("inl1").set("Uavfdf", "u0");
    model.component("comp1").physics("spf").create("out1", "OutletBoundary", 1);
    model.component("comp1").physics("spf").feature("out1").selection().set(4);

    model.component("comp1").multiphysics().create("nirf1", "NonIsothermalReactingFlow", 2);

    model.component("comp1").mesh("mesh1").automatic(false);
    model.component("comp1").mesh("mesh1").feature().remove("size1");
    model.component("comp1").mesh("mesh1").feature().remove("cr1");
    model.component("comp1").mesh("mesh1").feature().remove("ftri1");
    model.component("comp1").mesh("mesh1").create("map1", "Map");
    model.component("comp1").mesh("mesh1").feature().move("map1", 1);
    model.component("comp1").mesh("mesh1").feature("map1").create("dis1", "Distribution");
    model.component("comp1").mesh("mesh1").feature("map1").feature("dis1").selection().set(2, 3);
    model.component("comp1").mesh("mesh1").feature("map1").feature("dis1").set("type", "predefined");
    model.component("comp1").mesh("mesh1").feature("map1").feature("dis1").set("elemcount", 40);
    model.component("comp1").mesh("mesh1").feature("map1").feature("dis1").set("elemratio", 10);
    model.component("comp1").mesh("mesh1").feature("map1").feature("dis1").set("symmetric", true);
    model.component("comp1").mesh("mesh1").run("map1");
    model.component("comp1").mesh("mesh1").feature("map1").create("dis2", "Distribution");
    model.component("comp1").mesh("mesh1").feature("map1").feature("dis2").selection().set(1, 4);
    model.component("comp1").mesh("mesh1").feature("map1").feature("dis2").set("type", "predefined");
    model.component("comp1").mesh("mesh1").feature("map1").feature("dis2").set("elemcount", 20);
    model.component("comp1").mesh("mesh1").feature("map1").feature("dis2").set("elemratio", 5);
    model.component("comp1").mesh("mesh1").feature("map1").feature("dis2").set("reverse", true);
    model.component("comp1").mesh("mesh1").run("map1");
    model.component("comp1").mesh("mesh1").feature("bl1").feature("blp1").set("blnlayers", 12);
    model.component("comp1").mesh("mesh1").feature("bl1").feature("blp1").set("blhminfact", 1);
    model.component("comp1").mesh("mesh1").feature("bl1").set("smoothtransition", false);
    model.component("comp1").mesh("mesh1").run("bl1");

    model.study("std1").create("param", "Parametric");
    model.study("std1").feature("param").setIndex("pname", "dz", 0);
    model.study("std1").feature("param").setIndex("plistarr", "", 0);
    model.study("std1").feature("param").setIndex("punit", "m", 0);
    model.study("std1").feature("param").setIndex("pname", "dz", 0);
    model.study("std1").feature("param").setIndex("plistarr", "", 0);
    model.study("std1").feature("param").setIndex("punit", "m", 0);
    model.study("std1").feature("param").setIndex("plistarr", "1, 2, 5", 0);
    model.study("std1").feature("param").setIndex("punit", "mm", 0);
    model.study("std1").createAutoSequences("all");

    model.sol("sol1").runAll();

    model.result().create("pg1", "PlotGroup2D");
    model.result("pg1").set("data", "dset1");
    model.result("pg1").setIndex("looplevel", 3, 0);
    model.result("pg1").label("\u6d53\u5ea6, A_2D (tcs)");
    model.result("pg1").set("titletype", "custom");
    model.result("pg1").set("prefixintitle", "");
    model.result("pg1").set("expressionintitle", false);
    model.result("pg1").set("typeintitle", false);
    model.result("pg1").create("surf1", "Surface");
    model.result("pg1").feature("surf1").set("expr", new String[]{"tcs.c_wA_2D"});
    model.result("pg1").feature("surf1").set("colortable", "Prism");
    model.result("pg1").set("typeintitle", true);
    model.result("pg1").create("arws1", "ArrowSurface");
    model.result("pg1").feature("arws1").set("expr", new String[]{"tcs.tflux_wA_2Dx", "tcs.tflux_wA_2Dy"});
    model.result("pg1").feature("arws1").set("xnumber", 10);
    model.result("pg1").feature("arws1").set("ynumber", 10);
    model.result("pg1").feature("arws1").set("color", "black");
    model.result("pg1").feature("arws1").create("sel1", "Selection");
    model.result("pg1").feature("arws1").feature("sel1").selection().set(1);
    model.result().create("pg2", "PlotGroup2D");
    model.result("pg2").set("data", "dset1");
    model.result("pg2").setIndex("looplevel", 3, 0);
    model.result("pg2").label("\u6d53\u5ea6, B_2D (tcs)");
    model.result("pg2").set("titletype", "custom");
    model.result("pg2").set("prefixintitle", "");
    model.result("pg2").set("expressionintitle", false);
    model.result("pg2").set("typeintitle", false);
    model.result("pg2").create("surf1", "Surface");
    model.result("pg2").feature("surf1").set("expr", new String[]{"tcs.c_wB_2D"});
    model.result("pg2").feature("surf1").set("colortable", "Prism");
    model.result("pg2").set("typeintitle", true);
    model.result("pg2").create("arws1", "ArrowSurface");
    model.result("pg2").feature("arws1").set("expr", new String[]{"tcs.tflux_wB_2Dx", "tcs.tflux_wB_2Dy"});
    model.result("pg2").feature("arws1").set("xnumber", 10);
    model.result("pg2").feature("arws1").set("ynumber", 10);
    model.result("pg2").feature("arws1").set("color", "black");
    model.result("pg2").feature("arws1").create("sel1", "Selection");
    model.result("pg2").feature("arws1").feature("sel1").selection().set(1);
    model.result().create("pg3", "PlotGroup2D");
    model.result("pg3").set("data", "dset1");
    model.result("pg3").setIndex("looplevel", 3, 0);
    model.result("pg3").label("\u6d53\u5ea6, C_2D (tcs)");
    model.result("pg3").set("titletype", "custom");
    model.result("pg3").set("prefixintitle", "");
    model.result("pg3").set("expressionintitle", false);
    model.result("pg3").set("typeintitle", false);
    model.result("pg3").create("surf1", "Surface");
    model.result("pg3").feature("surf1").set("expr", new String[]{"tcs.c_wC_2D"});
    model.result("pg3").feature("surf1").set("colortable", "Prism");
    model.result("pg3").set("typeintitle", true);
    model.result("pg3").create("arws1", "ArrowSurface");
    model.result("pg3").feature("arws1").set("expr", new String[]{"tcs.tflux_wC_2Dx", "tcs.tflux_wC_2Dy"});
    model.result("pg3").feature("arws1").set("xnumber", 10);
    model.result("pg3").feature("arws1").set("ynumber", 10);
    model.result("pg3").feature("arws1").set("color", "black");
    model.result("pg3").feature("arws1").create("sel1", "Selection");
    model.result("pg3").feature("arws1").feature("sel1").selection().set(1);
    model.result().dataset("dset1").set("geom", "geom1");
    model.result().create("pg4", "PlotGroup2D");
    model.result("pg4").label("\u901f\u5ea6 (spf)");
    model.result("pg4").set("frametype", "spatial");
    model.result("pg4").feature().create("surf1", "Surface");
    model.result("pg4").feature("surf1").label("\u8868\u9762");
    model.result("pg4").feature("surf1").set("showsolutionparams", "on");
    model.result("pg4").feature("surf1").set("expr", "spf.U");
    model.result("pg4").feature("surf1").set("colortable", "Rainbow");
    model.result("pg4").feature("surf1").set("smooth", "internal");
    model.result("pg4").feature("surf1").set("showsolutionparams", "on");
    model.result("pg4").feature("surf1").set("data", "parent");
    model.result().create("pg5", "PlotGroup2D");
    model.result("pg5").label("\u538b\u529b (spf)");
    model.result("pg5").set("frametype", "spatial");
    model.result("pg5").feature().create("con1", "Contour");
    model.result("pg5").feature("con1").label("\u7b49\u503c\u7ebf");
    model.result("pg5").feature("con1").set("showsolutionparams", "on");
    model.result("pg5").feature("con1").set("expr", "p");
    model.result("pg5").feature("con1").set("number", 40);
    model.result("pg5").feature("con1").set("levelrounding", false);
    model.result("pg5").feature("con1").set("colortable", "Rainbow");
    model.result("pg5").feature("con1").set("smooth", "internal");
    model.result("pg5").feature("con1").set("showsolutionparams", "on");
    model.result("pg5").feature("con1").set("data", "parent");
    model.result("pg1").run();
    model.result().remove("pg1");
    model.result().remove("pg2");
    model.result().remove("pg3");
    model.result("pg4").run();
    model.result().create("pg6", "PlotGroup2D");
    model.result("pg6").set("data", "dset1");
    model.result("pg6").setIndex("looplevel", 3, 0);
    model.result("pg6").set("titletype", "manual");
    model.result("pg6")
         .set("title", "\u8868\u9762: \u6d53\u5ea6 (mol/m<sup>3</sup>) \u9762\u7bad\u5934: \u603b\u901a\u91cf");
    model.result("pg6").set("showlegendsunit", true);
    model.result("pg6").set("showlegendstitle", true);
    model.result("pg6").label("\u7ed8\u56fe\u9635\u5217: \u6d53\u5ea6, A_2D, B_2D, C_2D (tcs)");
    model.result("pg6").set("plotarrayenable", true);
    model.result("pg6").set("arrayshape", "linear");
    model.result("pg6").set("legendpos", "rightdouble");
    model.result("pg6").set("arrayaxis", "y");
    model.result("pg6").set("relpadding", 0.5);
    model.result("pg6").create("surf1", "Surface");
    model.result("pg6").feature("surf1").set("expr", new String[]{"tcs.c_wA_2D"});
    model.result("pg6").feature("surf1").set("colortable", "Cynanthus");
    model.result("pg6").feature("surf1").label("\u8868\u9762, A_2D");
    model.result("pg6").feature("surf1").set("legendtitle", "A_2D");
    model.result("pg6").feature("surf1").set("manualindexing", true);
    model.result("pg6").feature("surf1").set("arrayindex", 0);
    model.result("pg6").create("arws1", "ArrowSurface");
    model.result("pg6").feature("arws1").set("expr", new String[]{"tcs.tflux_wA_2Dx", "tcs.tflux_wA_2Dy"});
    model.result("pg6").feature("arws1").set("xnumber", 7);
    model.result("pg6").feature("arws1").set("ynumber", 7);
    model.result("pg6").feature("arws1").set("color", "black");
    model.result("pg6").feature("arws1").create("sel1", "Selection");
    model.result("pg6").feature("arws1").feature("sel1").selection().set(1);
    model.result("pg6").feature("arws1").label("\u603b\u901a\u91cf, A_2D");
    model.result("pg6").feature("arws1").set("manualindexing", true);
    model.result("pg6").feature("arws1").set("arrayindex", 0);
    model.result("pg6").create("ann1", "Annotation");
    model.result("pg6").feature("ann1").set("showpoint", false);
    model.result("pg6").feature("ann1").set("text", "A_2D");
    model.result("pg6").feature("ann1").label("A_2D");
    model.result("pg6").feature("ann1").set("posxexpr", 0);
    model.result("pg6").feature("ann1").set("posyexpr", 0);
    model.result("pg6").feature("ann1").set("manualindexing", true);
    model.result("pg6").feature("ann1").set("arrayindex", 0);
    model.result("pg6").create("surf2", "Surface");
    model.result("pg6").feature("surf2").set("expr", new String[]{"tcs.c_wB_2D"});
    model.result("pg6").feature("surf2").set("colortable", "Baptisia");
    model.result("pg6").feature("surf2").label("\u8868\u9762, B_2D");
    model.result("pg6").feature("surf2").set("legendtitle", "B_2D");
    model.result("pg6").feature("surf2").set("manualindexing", true);
    model.result("pg6").feature("surf2").set("arrayindex", 1);
    model.result("pg6").create("arws2", "ArrowSurface");
    model.result("pg6").feature("arws2").set("expr", new String[]{"tcs.tflux_wB_2Dx", "tcs.tflux_wB_2Dy"});
    model.result("pg6").feature("arws2").set("xnumber", 7);
    model.result("pg6").feature("arws2").set("ynumber", 7);
    model.result("pg6").feature("arws2").set("color", "black");
    model.result("pg6").feature("arws2").create("sel1", "Selection");
    model.result("pg6").feature("arws2").feature("sel1").selection().set(1);
    model.result("pg6").feature("arws2").label("\u603b\u901a\u91cf, B_2D");
    model.result("pg6").feature("arws2").set("manualindexing", true);
    model.result("pg6").feature("arws2").set("arrayindex", 1);
    model.result("pg6").create("ann2", "Annotation");
    model.result("pg6").feature("ann2").set("showpoint", false);
    model.result("pg6").feature("ann2").set("text", "B_2D");
    model.result("pg6").feature("ann2").label("B_2D");
    model.result("pg6").feature("ann2").set("posxexpr", 0);
    model.result("pg6").feature("ann2").set("posyexpr", 0);
    model.result("pg6").feature("ann2").set("manualindexing", true);
    model.result("pg6").feature("ann2").set("arrayindex", 1);
    model.result("pg6").create("surf3", "Surface");
    model.result("pg6").feature("surf3").set("expr", new String[]{"tcs.c_wC_2D"});
    model.result("pg6").feature("surf3").set("colortable", "Arctium");
    model.result("pg6").feature("surf3").label("\u8868\u9762, C_2D");
    model.result("pg6").feature("surf3").set("legendtitle", "C_2D");
    model.result("pg6").feature("surf3").set("manualindexing", true);
    model.result("pg6").feature("surf3").set("arrayindex", 2);
    model.result("pg6").create("arws3", "ArrowSurface");
    model.result("pg6").feature("arws3").set("expr", new String[]{"tcs.tflux_wC_2Dx", "tcs.tflux_wC_2Dy"});
    model.result("pg6").feature("arws3").set("xnumber", 7);
    model.result("pg6").feature("arws3").set("ynumber", 7);
    model.result("pg6").feature("arws3").set("color", "black");
    model.result("pg6").feature("arws3").create("sel1", "Selection");
    model.result("pg6").feature("arws3").feature("sel1").selection().set(1);
    model.result("pg6").feature("arws3").label("\u603b\u901a\u91cf, C_2D");
    model.result("pg6").feature("arws3").set("manualindexing", true);
    model.result("pg6").feature("arws3").set("arrayindex", 2);
    model.result("pg6").create("ann3", "Annotation");
    model.result("pg6").feature("ann3").set("showpoint", false);
    model.result("pg6").feature("ann3").set("text", "C_2D");
    model.result("pg6").feature("ann3").label("C_2D");
    model.result("pg6").feature("ann3").set("posxexpr", 0);
    model.result("pg6").feature("ann3").set("posyexpr", 0);
    model.result("pg6").feature("ann3").set("manualindexing", true);
    model.result("pg6").feature("ann3").set("arrayindex", 2);
    model.result("pg6").label("\u7ed8\u56fe\u9635\u5217: \u6d53\u5ea6, A_2D, B_2D, C_2D (tcs)");
    model.result("pg6").run();
    model.result("pg6").setIndex("looplevel", 2, 0);
    model.result("pg6").set("titletype", "none");
    model.result("pg6").feature("arws1").set("arraydim", "1");
    model.result("pg6").run();
    model.result("pg6").feature().remove("arws1");
    model.result("pg6").feature().remove("arws2");
    model.result("pg6").feature().remove("arws3");
    model.result("pg6").feature("ann1").set("arraydim", "1");
    model.result("pg6").run();
    model.result("pg6").create("con1", "Contour");
    model.result("pg6").feature("con1").set("arraydim", "1");
    model.result("pg6").feature("con1").set("expr", "tcs.c_wA_2D");
    model.result("pg6").feature("con1").set("number", 10);
    model.result("pg6").feature("con1").set("coloring", "uniform");
    model.result("pg6").feature("con1").set("color", "white");
    model.result("pg6").feature("con1").set("colorlegend", false);
    model.result("pg6").feature("con1").set("manualindexing", true);
    model.result("pg6").create("con2", "Contour");
    model.result("pg6").feature("con2").set("arraydim", "1");
    model.result("pg6").feature("con2").set("expr", "tcs.c_wB_2D");
    model.result("pg6").feature("con2").set("number", 10);
    model.result("pg6").feature("con2").set("coloring", "uniform");
    model.result("pg6").feature("con2").set("color", "white");
    model.result("pg6").feature("con2").set("colorlegend", false);
    model.result("pg6").feature("con2").set("manualindexing", true);
    model.result("pg6").feature("con2").set("arrayindex", 1);
    model.result("pg6").create("con3", "Contour");
    model.result("pg6").feature("con3").set("arraydim", "1");
    model.result("pg6").feature("con3").set("expr", "tcs.c_wC_2D");
    model.result("pg6").feature("con3").set("number", 10);
    model.result("pg6").feature("con3").set("coloring", "uniform");
    model.result("pg6").feature("con3").set("color", "white");
    model.result("pg6").feature("con3").set("colorlegend", false);
    model.result("pg6").feature("con3").set("manualindexing", true);
    model.result("pg6").feature("con3").set("arrayindex", 2);
    model.result("pg6").run();
    model.result("pg6").set("legendpos", "right");

    model.component("comp1").view("view1").set("showgrid", false);

    model.result("pg6").run();
    model.result("pg6").feature("ann1").set("arraydim", "1");
    model.result("pg6").run();
    model.result("pg6").feature("ann1").active(false);
    model.result("pg6").feature("ann2").active(false);
    model.result("pg6").feature("ann3").active(false);
    model.result("pg6").feature("ann1").active(true);
    model.result("pg6").feature("ann2").active(true);
    model.result("pg6").feature("ann3").active(true);
    model.result().create("pg7", "PlotGroup1D");
    model.result("pg7").run();
    model.result("pg7").setIndex("looplevelinput", "manual", 0);
    model.result("pg7").setIndex("looplevel", new int[]{2}, 0);
    model.result("pg7").set("titletype", "none");
    model.result("pg7").set("showgrid", false);
    model.result("pg7").create("lngr1", "LineGraph");
    model.result("pg7").feature("lngr1").set("markerpos", "datapoints");
    model.result("pg7").feature("lngr1").set("linewidth", "preference");
    model.result("pg7").feature("lngr1").selection().set(2);
    model.result("pg7").feature("lngr1").set("expr", "tcs.c_wA_2D");
    model.result("pg7").feature("lngr1").set("xdata", "expr");
    model.result("pg7").feature("lngr1").set("xdataexpr", "x");
    model.result("pg7").feature("lngr1").set("linestyle", "dashed");
    model.result("pg7").feature("lngr1").set("legend", true);
    model.result("pg7").feature("lngr1").set("autosolution", false);
    model.result("pg7").create("lngr2", "LineGraph");
    model.result("pg7").feature("lngr2").set("markerpos", "datapoints");
    model.result("pg7").feature("lngr2").set("linewidth", "preference");
    model.result("pg7").feature("lngr2").selection().set(2);
    model.result("pg7").feature("lngr2").set("expr", "tcs.c_wB_2D");
    model.result("pg7").feature("lngr2").set("xdata", "expr");
    model.result("pg7").feature("lngr2").set("xdataexpr", "x");
    model.result("pg7").feature("lngr2").set("linestyle", "dashed");
    model.result("pg7").feature("lngr2").set("legend", true);
    model.result("pg7").feature("lngr2").set("autosolution", false);
    model.result("pg7").create("lngr3", "LineGraph");
    model.result("pg7").feature("lngr3").set("markerpos", "datapoints");
    model.result("pg7").feature("lngr3").set("linewidth", "preference");
    model.result("pg7").feature("lngr3").selection().set(2);
    model.result("pg7").feature("lngr3").set("expr", "tcs.c_wC_2D");
    model.result("pg7").feature("lngr3").set("xdata", "expr");
    model.result("pg7").feature("lngr3").set("xdataexpr", "x");
    model.result("pg7").feature("lngr3").set("linestyle", "dashed");
    model.result("pg7").feature("lngr3").set("legend", true);
    model.result("pg7").feature("lngr3").set("autosolution", false);
    model.result("pg7").run();
    model.result().evaluationGroup().create("eg1", "EvaluationGroup");
    model.result().evaluationGroup("eg1").set("data", "dset1");
    model.result().evaluationGroup("eg1").label("\u8d28\u91cf\u5e73\u8861, A_2D (tcs)");
    model.result().evaluationGroup("eg1").create("int1", "IntLine");
    model.result().evaluationGroup("eg1").feature("int1").set("intsurface", true);
    model.result().evaluationGroup("eg1").feature("int1").selection().all();
    model.result().evaluationGroup("eg1").feature("int1").set("expr", new String[]{"tcs.ntflux_wA_2D"});
    model.result().evaluationGroup("eg1").feature("int1").set("descr", "\u603b\u901a\u91cf\uff0c\u6d41\u5165");
    model.result().evaluationGroup("eg1").feature("int1").selection().set(1);
    model.result().evaluationGroup("eg1").feature("int1").label("\u603b\u901a\u91cf\uff0c\u6d41\u5165");
    model.result().evaluationGroup("eg1").create("int2", "IntLine");
    model.result().evaluationGroup("eg1").feature("int2").set("intsurface", true);
    model.result().evaluationGroup("eg1").feature("int2").selection().all();
    model.result().evaluationGroup("eg1").feature("int2").set("expr", new String[]{"tcs.ntflux_wA_2D"});
    model.result().evaluationGroup("eg1").feature("int2").set("descr", "\u603b\u901a\u91cf\uff0c\u6d41\u51fa");
    model.result().evaluationGroup("eg1").feature("int2").selection().set(4);
    model.result().evaluationGroup("eg1").feature("int2").label("\u603b\u901a\u91cf\uff0c\u6d41\u51fa");
    model.result().evaluationGroup("eg1").create("int3", "IntSurface");
    model.result().evaluationGroup("eg1").feature("int3").label("\u603b\u901f\u7387\u8868\u8fbe\u5f0f");
    model.result().evaluationGroup("eg1").feature("int3").set("intvolume", true);
    model.result().evaluationGroup("eg1").feature("int3").set("expr", new String[]{"tcs.R_wA_2D"});
    model.result().evaluationGroup("eg1").feature("int3").set("descr", "\u603b\u901f\u7387\u8868\u8fbe\u5f0f");
    model.result().evaluationGroup("eg1").feature("int3").selection().set(1);
    model.result().evaluationGroup("eg1").create("int4", "IntLine");
    model.result().evaluationGroup("eg1").feature("int4").set("intsurface", true);
    model.result().evaluationGroup("eg1").feature("int4").selection().all();
    model.result().evaluationGroup("eg1").feature("int4").set("expr", new String[]{"tcs.ntflux_wA_2D"});
    model.result().evaluationGroup("eg1").feature("int4")
         .set("descr", "\u603b\u901a\u91cf\uff0c\u6240\u6709\u8fb9\u754c");
    model.result().evaluationGroup("eg1").feature("int4").selection().set(1, 2, 3, 4);
    model.result().evaluationGroup("eg1").feature("int4").label("\u603b\u901a\u91cf\uff0c\u6240\u6709\u8fb9\u754c");
    model.result().evaluationGroup("eg1").set("type", "general");
    model.result().evaluationGroup("eg1").set("generalexpr", "-int4+int3");
    model.result().evaluationGroup("eg1").set("keepchildnodes", true);
    model.result().evaluationGroup("eg1").set("generalheader", "\u8d28\u91cf\u5e73\u8861");
    model.result().evaluationGroup("eg1").label("\u8d28\u91cf\u5e73\u8861, A_2D (tcs)");
    model.result().evaluationGroup().create("eg2", "EvaluationGroup");
    model.result().evaluationGroup("eg2").set("data", "dset1");
    model.result().evaluationGroup("eg2").label("\u8d28\u91cf\u5e73\u8861, B_2D (tcs)");
    model.result().evaluationGroup("eg2").create("int1", "IntLine");
    model.result().evaluationGroup("eg2").feature("int1").set("intsurface", true);
    model.result().evaluationGroup("eg2").feature("int1").selection().all();
    model.result().evaluationGroup("eg2").feature("int1").set("expr", new String[]{"tcs.ntflux_wB_2D"});
    model.result().evaluationGroup("eg2").feature("int1").set("descr", "\u603b\u901a\u91cf\uff0c\u6d41\u5165");
    model.result().evaluationGroup("eg2").feature("int1").selection().set(1);
    model.result().evaluationGroup("eg2").feature("int1").label("\u603b\u901a\u91cf\uff0c\u6d41\u5165");
    model.result().evaluationGroup("eg2").create("int2", "IntLine");
    model.result().evaluationGroup("eg2").feature("int2").set("intsurface", true);
    model.result().evaluationGroup("eg2").feature("int2").selection().all();
    model.result().evaluationGroup("eg2").feature("int2").set("expr", new String[]{"tcs.ntflux_wB_2D"});
    model.result().evaluationGroup("eg2").feature("int2").set("descr", "\u603b\u901a\u91cf\uff0c\u6d41\u51fa");
    model.result().evaluationGroup("eg2").feature("int2").selection().set(4);
    model.result().evaluationGroup("eg2").feature("int2").label("\u603b\u901a\u91cf\uff0c\u6d41\u51fa");
    model.result().evaluationGroup("eg2").create("int3", "IntSurface");
    model.result().evaluationGroup("eg2").feature("int3").label("\u603b\u901f\u7387\u8868\u8fbe\u5f0f");
    model.result().evaluationGroup("eg2").feature("int3").set("intvolume", true);
    model.result().evaluationGroup("eg2").feature("int3").set("expr", new String[]{"tcs.R_wB_2D"});
    model.result().evaluationGroup("eg2").feature("int3").set("descr", "\u603b\u901f\u7387\u8868\u8fbe\u5f0f");
    model.result().evaluationGroup("eg2").feature("int3").selection().set(1);
    model.result().evaluationGroup("eg2").create("int4", "IntLine");
    model.result().evaluationGroup("eg2").feature("int4").set("intsurface", true);
    model.result().evaluationGroup("eg2").feature("int4").selection().all();
    model.result().evaluationGroup("eg2").feature("int4").set("expr", new String[]{"tcs.ntflux_wB_2D"});
    model.result().evaluationGroup("eg2").feature("int4")
         .set("descr", "\u603b\u901a\u91cf\uff0c\u6240\u6709\u8fb9\u754c");
    model.result().evaluationGroup("eg2").feature("int4").selection().set(1, 2, 3, 4);
    model.result().evaluationGroup("eg2").feature("int4").label("\u603b\u901a\u91cf\uff0c\u6240\u6709\u8fb9\u754c");
    model.result().evaluationGroup("eg2").set("type", "general");
    model.result().evaluationGroup("eg2").set("generalexpr", "-int4+int3");
    model.result().evaluationGroup("eg2").set("keepchildnodes", true);
    model.result().evaluationGroup("eg2").set("generalheader", "\u8d28\u91cf\u5e73\u8861");
    model.result().evaluationGroup("eg2").label("\u8d28\u91cf\u5e73\u8861, B_2D (tcs)");
    model.result().evaluationGroup("eg1").set("generalexpr", "(-int4+int3)/int1");
    model.result().evaluationGroup("eg1").run();
    model.result().evaluationGroup("eg2").set("generalexpr", "(-int4+int3)/int1");
    model.result().evaluationGroup("eg2").run();

    model.component().create("comp2", true);

    model.component("comp2").geom().create("geom2", 3);
    model.component("comp2").geom("geom2").geomRep("comsol");

    model.component("comp2").mesh().create("mesh2");
    model.component("comp2").mesh("mesh2").contribute("geom/detail", true);

    model.component("comp2").geom("geom2").create("blk1", "Block");
    model.component("comp2").geom("geom2").feature("blk1").set("size", new String[]{"L", "W/2", "dz"});
    model.component("comp2").geom("geom2").run("blk1");
    model.component("comp2").geom("geom2").run("fin");

    model.component("comp2").physics().create("tcs2", "ConcentratedSpecies", "geom2");

    model.study("std1").feature("stat").setSolveFor("/physics/tcs2", false);

    model.component("comp2").physics().create("spf2", "LaminarFlow", "geom2");

    model.study("std1").feature("stat").setSolveFor("/physics/spf2", false);

    model.component("comp2").physics("tcs2").field("massfraction").component(new String[]{"w1", "w2", "w3"});
    model.component("comp2").physics("tcs2").field("massfraction").component(1, "wA_3D");
    model.component("comp2").physics("tcs2").field("massfraction").component(2, "wB_3D");
    model.component("comp2").physics("tcs2").field("massfraction").component(3, "wC_3D");
    model.component("comp2").physics("tcs2").prop("SpeciesProperties").set("FromMassConstraint", 3);

    return model;
  }

  public static Model run2(Model model) {
    model.component("comp2").physics("tcs2").feature("sp1").setIndex("M_wA_3D", "MW", 0);
    model.component("comp2").physics("tcs2").feature("sp1").setIndex("M_wB_3D", "MW", 0);
    model.component("comp2").physics("tcs2").feature("sp1").setIndex("M_wC_3D", "MW", 0);
    model.component("comp2").physics("tcs2").create("sym1", "Symmetry", 2);
    model.component("comp2").physics("tcs2").feature("sym1").selection().set(2);
    model.component("comp2").physics("tcs2").create("in1", "Inflow", 2);
    model.component("comp2").physics("tcs2").feature("in1").setIndex("wbnd", "wA_in", 0);
    model.component("comp2").physics("tcs2").feature("in1").setIndex("wbnd", "wB_in", 1);
    model.component("comp2").physics("tcs2").feature("in1").selection().set(1);
    model.component("comp2").physics("tcs2").create("out1", "Outflow", 2);
    model.component("comp2").physics("tcs2").feature("out1").selection().set(6);
    model.component("comp2").physics("tcs2").create("flux1", "FluxBoundary", 2);
    model.component("comp2").physics("tcs2").feature("flux1").selection().set(4);
    model.component("comp2").physics("tcs2").feature("flux1").set("uStefanActive", true);
    model.component("comp2").physics("tcs2").feature("flux1").setIndex("species", true, 0);
    model.component("comp2").physics("tcs2").feature("flux1").setIndex("item.j0", "kcw*(wA_wall-wA_3D)", 0);
    model.component("comp2").physics("spf2").prop("PhysicalModelProperty")
         .set("Compressibility", "CompressibleMALT03");
    model.component("comp2").physics("spf2").feature("fp1").set("mu_mat", "userdef");
    model.component("comp2").physics("spf2").feature("fp1").set("mu", "visc");
    model.component("comp2").physics("spf2").create("sym1", "Symmetry", 2);
    model.component("comp2").physics("spf2").feature("sym1").selection().set(2);
    model.component("comp2").physics("spf2").create("inl1", "InletBoundary", 2);
    model.component("comp2").physics("spf2").feature("inl1").set("BoundaryCondition", "FullyDevelopedFlow");
    model.component("comp2").physics("spf2").feature("inl1").set("Uavfdf", "u0");
    model.component("comp2").physics("spf2").feature("inl1").selection().set(1);
    model.component("comp2").physics("spf2").create("out1", "OutletBoundary", 2);
    model.component("comp2").physics("spf2").feature("out1").set("NormalFlow", true);
    model.component("comp2").physics("spf2").feature("out1").selection().set(6);

    model.component("comp2").multiphysics().create("nirf2", "NonIsothermalReactingFlow", 3);

    model.component("comp2").mesh("mesh2").automatic(false);
    model.component("comp2").mesh("mesh2").feature().remove("size1");
    model.component("comp2").mesh("mesh2").feature().remove("size2");
    model.component("comp2").mesh("mesh2").feature().remove("cr1");
    model.component("comp2").mesh("mesh2").feature().remove("ftet1");
    model.component("comp2").mesh("mesh2").create("map1", "Map");
    model.component("comp2").mesh("mesh2").feature().move("map1", 1);
    model.component("comp2").mesh("mesh2").feature("map1").create("dis1", "Distribution");
    model.component("comp2").mesh("mesh2").feature("map1").feature("dis1").selection().set(5, 8);
    model.component("comp2").mesh("mesh2").feature("map1").feature("dis1").set("type", "predefined");
    model.component("comp2").mesh("mesh2").feature("map1").feature("dis1").set("elemcount", 40);
    model.component("comp2").mesh("mesh2").feature("map1").feature("dis1").set("elemratio", 10);
    model.component("comp2").mesh("mesh2").feature("map1").feature("dis1").set("symmetric", true);
    model.component("comp2").mesh("mesh2").run("map1");
    model.component("comp2").mesh("mesh2").feature("map1").selection().set(4);
    model.component("comp2").mesh("mesh2").feature("map1").feature().duplicate("dis2", "dis1");
    model.component("comp2").mesh("mesh2").feature("map1").feature("dis2").selection().set(4, 11);
    model.component("comp2").mesh("mesh2").feature("map1").feature("dis2").set("elemcount", 20);
    model.component("comp2").mesh("mesh2").feature("map1").feature("dis2").set("elemratio", 5);
    model.component("comp2").mesh("mesh2").feature("map1").feature("dis2").set("symmetric", false);
    model.component("comp2").mesh("mesh2").run("map1");
    model.component("comp2").mesh("mesh2").create("swe1", "Sweep");
    model.component("comp2").mesh("mesh2").feature("swe1").create("dis1", "Distribution");
    model.component("comp2").mesh("mesh2").feature("swe1").feature("dis1").set("type", "predefined");
    model.component("comp2").mesh("mesh2").feature("swe1").feature("dis1").set("elemcount", 6);
    model.component("comp2").mesh("mesh2").feature("swe1").feature("dis1").set("elemratio", 2);
    model.component("comp2").mesh("mesh2").feature("swe1").feature("dis1").set("symmetric", true);
    model.component("comp2").mesh("mesh2").feature("bl1").selection().geom("geom2");
    model.component("comp2").mesh("mesh2").feature("bl1").feature("blp1").selection().set(2);
    model.component("comp2").mesh("mesh2").feature("bl1").set("smoothtransition", false);
    model.component("comp2").mesh("mesh2").run();

    model.study().create("std2");
    model.study("std2").create("stat", "Stationary");
    model.study("std2").feature("stat").setSolveFor("/physics/tcs", false);
    model.study("std2").feature("stat").setSolveFor("/physics/spf", false);
    model.study("std2").feature("stat").setSolveFor("/physics/tcs2", true);
    model.study("std2").feature("stat").setSolveFor("/physics/spf2", true);
    model.study("std2").feature("stat").setSolveFor("/multiphysics/nirf1", false);
    model.study("std2").feature("stat").setSolveFor("/multiphysics/nirf2", true);
    model.study("std2").create("param", "Parametric");
    model.study("std2").feature("param").setIndex("pname", "dz", 0);
    model.study("std2").feature("param").setIndex("plistarr", "", 0);
    model.study("std2").feature("param").setIndex("punit", "m", 0);
    model.study("std2").feature("param").setIndex("pname", "dz", 0);
    model.study("std2").feature("param").setIndex("plistarr", "", 0);
    model.study("std2").feature("param").setIndex("punit", "m", 0);
    model.study("std2").feature("param").setIndex("plistarr", "1, 2, 5", 0);
    model.study("std2").feature("param").setIndex("punit", "mm", 0);
    model.study("std2").createAutoSequences("all");

    model.sol().create("sol3");
    model.sol("sol3").study("std2");
    model.sol("sol3").label("\u53c2\u6570\u5316\u89e3 1");

    model.batch("p1").feature("so1").set("psol", "sol3");
    model.batch("p1").run("compute");

    model.result().create("pg8", "PlotGroup3D");
    model.result("pg8").set("data", "dset5");
    model.result("pg8").setIndex("looplevel", 3, 0);
    model.result("pg8").label("\u6d53\u5ea6, A_3D, \u6d41\u7ebf (tcs2)");
    model.result("pg8").set("titletype", "custom");
    model.result("pg8").set("typeintitle", true);
    model.result("pg8").set("prefixintitle", "");
    model.result("pg8").create("str1", "Streamline");
    model.result("pg8").feature("str1")
         .set("expr", new String[]{"tcs2.tflux_wA_3Dx", "tcs2.tflux_wA_3Dy", "tcs2.tflux_wA_3Dz"});
    model.result("pg8").feature("str1").set("posmethod", "start");
    model.result("pg8").feature("str1").set("pointtype", "arrow");
    model.result("pg8").feature("str1").set("arrowlength", "logarithmic");
    model.result("pg8").feature("str1").set("color", "gray");
    model.result("pg8").feature("str1").create("col", "Color");
    model.result("pg8").feature("str1").feature("col").set("expr", "root.comp2.tcs2.c_wA_3D");
    model.result("pg8").feature("str1").feature("col").set("colortable", "Prism");
    model.result("pg8").feature("str1").feature("col").set("titletype", "custom");
    model.result("pg8").feature("str1").set("linetype", "ribbon");
    model.result().create("pg9", "PlotGroup3D");
    model.result("pg9").set("data", "dset5");
    model.result("pg9").setIndex("looplevel", 3, 0);
    model.result("pg9").label("\u6d53\u5ea6, A_3D, \u8868\u9762 (tcs2)");
    model.result("pg9").set("titletype", "custom");
    model.result("pg9").set("prefixintitle", "");
    model.result("pg9").set("expressionintitle", false);
    model.result("pg9").set("typeintitle", false);
    model.result("pg9").create("surf1", "Surface");
    model.result("pg9").feature("surf1").set("expr", new String[]{"tcs2.c_wA_3D"});
    model.result("pg9").feature("surf1").set("colortable", "Prism");
    model.result().create("pg10", "PlotGroup3D");
    model.result("pg10").set("data", "dset5");
    model.result("pg10").setIndex("looplevel", 3, 0);
    model.result("pg10").label("\u6d53\u5ea6, B_3D, \u6d41\u7ebf (tcs2)");
    model.result("pg10").set("titletype", "custom");
    model.result("pg10").set("typeintitle", true);
    model.result("pg10").set("prefixintitle", "");
    model.result("pg10").create("str1", "Streamline");
    model.result("pg10").feature("str1")
         .set("expr", new String[]{"tcs2.tflux_wB_3Dx", "tcs2.tflux_wB_3Dy", "tcs2.tflux_wB_3Dz"});
    model.result("pg10").feature("str1").set("posmethod", "start");
    model.result("pg10").feature("str1").set("pointtype", "arrow");
    model.result("pg10").feature("str1").set("arrowlength", "logarithmic");
    model.result("pg10").feature("str1").set("color", "gray");
    model.result("pg10").feature("str1").create("col", "Color");
    model.result("pg10").feature("str1").feature("col").set("expr", "root.comp2.tcs2.c_wB_3D");
    model.result("pg10").feature("str1").feature("col").set("colortable", "Prism");
    model.result("pg10").feature("str1").feature("col").set("titletype", "custom");
    model.result("pg10").feature("str1").set("linetype", "ribbon");
    model.result().create("pg11", "PlotGroup3D");
    model.result("pg11").set("data", "dset5");
    model.result("pg11").setIndex("looplevel", 3, 0);
    model.result("pg11").label("\u6d53\u5ea6, B_3D, \u8868\u9762 (tcs2)");
    model.result("pg11").set("titletype", "custom");
    model.result("pg11").set("prefixintitle", "");
    model.result("pg11").set("expressionintitle", false);
    model.result("pg11").set("typeintitle", false);
    model.result("pg11").create("surf1", "Surface");
    model.result("pg11").feature("surf1").set("expr", new String[]{"tcs2.c_wB_3D"});
    model.result("pg11").feature("surf1").set("colortable", "Prism");
    model.result().create("pg12", "PlotGroup3D");
    model.result("pg12").set("data", "dset5");
    model.result("pg12").setIndex("looplevel", 3, 0);
    model.result("pg12").label("\u6d53\u5ea6, C_3D, \u6d41\u7ebf (tcs2)");
    model.result("pg12").set("titletype", "custom");
    model.result("pg12").set("typeintitle", true);
    model.result("pg12").set("prefixintitle", "");
    model.result("pg12").create("str1", "Streamline");
    model.result("pg12").feature("str1")
         .set("expr", new String[]{"tcs2.tflux_wC_3Dx", "tcs2.tflux_wC_3Dy", "tcs2.tflux_wC_3Dz"});
    model.result("pg12").feature("str1").set("posmethod", "start");
    model.result("pg12").feature("str1").set("pointtype", "arrow");
    model.result("pg12").feature("str1").set("arrowlength", "logarithmic");
    model.result("pg12").feature("str1").set("color", "gray");
    model.result("pg12").feature("str1").create("col", "Color");
    model.result("pg12").feature("str1").feature("col").set("expr", "root.comp2.tcs2.c_wC_3D");
    model.result("pg12").feature("str1").feature("col").set("colortable", "Prism");
    model.result("pg12").feature("str1").feature("col").set("titletype", "custom");
    model.result("pg12").feature("str1").set("linetype", "ribbon");
    model.result().create("pg13", "PlotGroup3D");
    model.result("pg13").set("data", "dset5");
    model.result("pg13").setIndex("looplevel", 3, 0);
    model.result("pg13").label("\u6d53\u5ea6, C_3D, \u8868\u9762 (tcs2)");
    model.result("pg13").set("titletype", "custom");
    model.result("pg13").set("prefixintitle", "");
    model.result("pg13").set("expressionintitle", false);
    model.result("pg13").set("typeintitle", false);
    model.result("pg13").create("surf1", "Surface");
    model.result("pg13").feature("surf1").set("expr", new String[]{"tcs2.c_wC_3D"});
    model.result("pg13").feature("surf1").set("colortable", "Prism");
    model.result().dataset("dset5").set("geom", "geom2");
    model.result().create("pg14", "PlotGroup3D");
    model.result("pg14").label("\u901f\u5ea6 (spf2)");
    model.result("pg14").set("data", "dset5");
    model.result("pg14").setIndex("looplevel", 3, 0);
    model.result("pg14").set("frametype", "spatial");
    model.result("pg14").feature().create("slc1", "Slice");
    model.result("pg14").feature("slc1").label("\u5207\u9762");
    model.result("pg14").feature("slc1").set("showsolutionparams", "on");
    model.result("pg14").feature("slc1").set("expr", "spf2.U");
    model.result("pg14").feature("slc1").set("colortable", "Rainbow");
    model.result("pg14").feature("slc1").set("smooth", "internal");
    model.result("pg14").feature("slc1").set("showsolutionparams", "on");
    model.result("pg14").feature("slc1").set("data", "parent");
    model.result().dataset().create("surf1", "Surface");
    model.result().dataset("surf1").label("\u5916\u58c1");
    model.result().dataset("surf1").set("data", "dset5");
    model.result().dataset("surf1").selection().geom("geom2", 2);
    model.result().dataset("surf1").selection().set(3, 4, 5);
    model.result().create("pg15", "PlotGroup3D");
    model.result("pg15").label("\u538b\u529b (spf2)");
    model.result("pg15").set("data", "surf1");
    model.result("pg15").setIndex("looplevel", 3, 0);
    model.result("pg15").set("frametype", "spatial");
    model.result("pg15").feature().create("surf1", "Surface");
    model.result("pg15").feature("surf1").label("\u8868\u9762");
    model.result("pg15").feature("surf1").set("showsolutionparams", "on");
    model.result("pg15").feature("surf1").set("expr", "p2");
    model.result("pg15").feature("surf1").set("colortable", "Dipole");
    model.result("pg15").feature("surf1").set("smooth", "internal");
    model.result("pg15").feature("surf1").set("showsolutionparams", "on");
    model.result("pg15").feature("surf1").set("data", "parent");
    model.result("pg15").feature("surf1").feature().create("tran1", "Transparency");
    model.result("pg8").run();
    model.result("pg4").run();
    model.result("pg4").run();
    model.result("pg4").feature("surf1").set("colortable", "Metasepia");
    model.result("pg4").feature("surf1").set("colortabletrans", "reverse");
    model.result("pg5").run();
    model.result("pg5").feature("con1").set("contourtype", "filled");
    model.result("pg5").feature("con1").set("colortable", "Agama");
    model.result("pg14").run();
    model.result("pg14").run();
    model.result("pg14").feature("slc1").set("colortable", "Metasepia");
    model.result("pg14").feature("slc1").set("colortabletrans", "reverse");
    model.result("pg15").run();
    model.result("pg15").run();
    model.result("pg15").feature("surf1").set("colortable", "Agama");
    model.result("pg15").feature("surf1").set("colortabletype", "discrete");
    model.result("pg8").run();
    model.result().remove("pg8");
    model.result().remove("pg9");
    model.result().remove("pg10");
    model.result().remove("pg11");
    model.result().remove("pg12");
    model.result().remove("pg13");
    model.result("pg14").run();
    model.result().create("pg16", "PlotGroup3D");
    model.result("pg16").set("data", "dset5");
    model.result("pg16").setIndex("looplevel", 3, 0);
    model.result("pg16").set("titletype", "manual");
    model.result("pg16").set("title", "\u8868\u9762: \u6d53\u5ea6 (mol/m<sup>3</sup>)");
    model.result("pg16").set("legendpos", "rightdouble");
    model.result("pg16").set("showlegendsunit", true);
    model.result("pg16").set("showlegendstitle", true);
    model.result("pg16").label("\u7ed8\u56fe\u9635\u5217: \u6d53\u5ea6, A_3D, B_3D, C_3D (tcs2)");
    model.result("pg16").set("plotarrayenable", true);
    model.result("pg16").set("arrayshape", "linear");
    model.result("pg16").set("arrayaxis", "z");
    model.result("pg16").set("relpadding", 1);
    model.result("pg16").create("surf1", "Surface");
    model.result("pg16").feature("surf1").set("expr", new String[]{"tcs2.c_wA_3D"});
    model.result("pg16").feature("surf1").set("colortable", "Cynanthus");
    model.result("pg16").feature("surf1").label("\u8868\u9762, A_3D");
    model.result("pg16").feature("surf1").set("legendtitle", "A_3D");
    model.result("pg16").feature("surf1").set("manualindexing", true);
    model.result("pg16").feature("surf1").set("arrayindex", 0);
    model.result("pg16").create("ann1", "Annotation");
    model.result("pg16").feature("ann1").set("showpoint", false);
    model.result("pg16").feature("ann1").set("text", "A_3D");
    model.result("pg16").feature("ann1").label("A_3D");
    model.result("pg16").feature("ann1").set("posxexpr", 0);
    model.result("pg16").feature("ann1").set("posyexpr", 0.025);
    model.result("pg16").feature("ann1").set("poszexpr", 0);
    model.result("pg16").feature("ann1").set("anchorpoint", "upperright");
    model.result("pg16").feature("ann1").set("manualindexing", true);
    model.result("pg16").feature("ann1").set("arrayindex", 0);
    model.result("pg16").create("surf2", "Surface");
    model.result("pg16").feature("surf2").set("expr", new String[]{"tcs2.c_wB_3D"});
    model.result("pg16").feature("surf2").set("colortable", "Baptisia");
    model.result("pg16").feature("surf2").label("\u8868\u9762, B_3D");
    model.result("pg16").feature("surf2").set("legendtitle", "B_3D");
    model.result("pg16").feature("surf2").set("manualindexing", true);
    model.result("pg16").feature("surf2").set("arrayindex", 1);
    model.result("pg16").create("ann2", "Annotation");
    model.result("pg16").feature("ann2").set("showpoint", false);
    model.result("pg16").feature("ann2").set("text", "B_3D");
    model.result("pg16").feature("ann2").label("B_3D");
    model.result("pg16").feature("ann2").set("posxexpr", 0);
    model.result("pg16").feature("ann2").set("posyexpr", 0.025);
    model.result("pg16").feature("ann2").set("poszexpr", 0);
    model.result("pg16").feature("ann2").set("anchorpoint", "upperright");
    model.result("pg16").feature("ann2").set("manualindexing", true);
    model.result("pg16").feature("ann2").set("arrayindex", 1);
    model.result("pg16").create("surf3", "Surface");
    model.result("pg16").feature("surf3").set("expr", new String[]{"tcs2.c_wC_3D"});
    model.result("pg16").feature("surf3").set("colortable", "Arctium");
    model.result("pg16").feature("surf3").label("\u8868\u9762, C_3D");
    model.result("pg16").feature("surf3").set("legendtitle", "C_3D");
    model.result("pg16").feature("surf3").set("manualindexing", true);
    model.result("pg16").feature("surf3").set("arrayindex", 2);
    model.result("pg16").create("ann3", "Annotation");
    model.result("pg16").feature("ann3").set("showpoint", false);
    model.result("pg16").feature("ann3").set("text", "C_3D");
    model.result("pg16").feature("ann3").label("C_3D");
    model.result("pg16").feature("ann3").set("posxexpr", 0);
    model.result("pg16").feature("ann3").set("posyexpr", 0.025);
    model.result("pg16").feature("ann3").set("poszexpr", 0);
    model.result("pg16").feature("ann3").set("anchorpoint", "upperright");
    model.result("pg16").feature("ann3").set("manualindexing", true);
    model.result("pg16").feature("ann3").set("arrayindex", 2);
    model.result("pg16").label("\u7ed8\u56fe\u9635\u5217: \u6d53\u5ea6, A_3D, B_3D, C_3D (tcs2)");
    model.result("pg16").run();
    model.result("pg16").setIndex("looplevel", 2, 0);
    model.result("pg16").set("titletype", "none");
    model.result("pg16").set("legendpos", "right");
    model.result("pg16").set("arrayaxis", "y");
    model.result("pg16").set("relpadding", 0.3);
    model.result("pg16").create("con1", "Contour");
    model.result("pg16").feature("con1").set("arraydim", "1");
    model.result("pg16").feature("con1").set("expr", "tcs2.c_wA_3D");
    model.result("pg16").feature("con1").set("number", 10);
    model.result("pg16").feature("con1").set("coloring", "uniform");
    model.result("pg16").feature("con1").set("color", "white");
    model.result("pg16").feature("con1").set("colorlegend", false);
    model.result("pg16").feature("con1").set("manualindexing", true);
    model.result("pg16").feature("con1").set("arrayindex", 2);
    model.result("pg16").create("con2", "Contour");
    model.result("pg16").feature("con2").set("arraydim", "1");
    model.result("pg16").feature("con2").set("expr", "tcs2.c_wB_3D");
    model.result("pg16").feature("con2").set("number", 10);
    model.result("pg16").feature("con2").set("coloring", "uniform");
    model.result("pg16").feature("con2").set("color", "white");
    model.result("pg16").feature("con2").set("colorlegend", false);
    model.result("pg16").feature("con2").set("manualindexing", true);
    model.result("pg16").feature("con2").set("arrayindex", 1);
    model.result("pg16").create("con3", "Contour");
    model.result("pg16").feature("con3").set("arraydim", "1");
    model.result("pg16").feature("con3").set("expr", "tcs2.c_wC_3D");
    model.result("pg16").feature("con3").set("number", 10);
    model.result("pg16").feature("con3").set("coloring", "uniform");
    model.result("pg16").feature("con3").set("color", "white");
    model.result("pg16").feature("con3").set("colorlegend", false);
    model.result("pg16").feature("con3").set("manualindexing", true);
    model.result("pg16").run();

    model.component("comp2").view("view2").set("showgrid", false);

    model.result("pg16").run();
    model.result("pg16").set("showlegends", false);
    model.result("pg16").feature("ann1").set("arraydim", "1");
    model.result("pg16").run();
    model.result("pg16").feature("ann1").active(false);
    model.result("pg16").feature("ann2").active(false);
    model.result("pg16").feature("ann3").active(false);
    model.result("pg16").feature("ann1").active(true);
    model.result("pg16").feature("ann2").active(true);
    model.result("pg16").feature("ann3").active(true);
    model.result("pg16").run();
    model.result().create("pg17", "PlotGroup3D");
    model.result("pg17").run();
    model.result("pg17").set("data", "none");
    model.result("pg17").set("titletype", "none");
    model.result("pg17").set("view", "view2");
    model.result("pg17").set("showlegendsunit", true);
    model.result("pg17").set("plotarrayenable", true);
    model.result("pg17").set("arrayaxis", "y");
    model.result("pg17").create("vol1", "Volume");
    model.result("pg17").feature("vol1").set("arraydim", "1");
    model.result("pg17").feature("vol1").set("data", "dset5");
    model.result("pg17").feature("vol1").setIndex("looplevel", 1, 0);
    model.result("pg17").feature("vol1").set("expr", "tcs2.c_wA_3D");
    model.result("pg17").feature("vol1").set("rangecoloractive", true);
    model.result("pg17").feature("vol1").set("rangecolormin", 4);
    model.result("pg17").feature("vol1").set("rangecolormax", 12);
    model.result("pg17").feature("vol1").set("colortable", "Cynanthus");
    model.result("pg17").feature("vol1").set("manualindexing", true);
    model.result("pg17").create("con1", "Contour");
    model.result("pg17").feature("con1").set("arraydim", "1");
    model.result("pg17").feature("con1").set("data", "dset5");
    model.result("pg17").feature("con1").setIndex("looplevel", 1, 0);
    model.result("pg17").feature("con1").set("expr", "tcs2.c_wA_3D");
    model.result("pg17").feature("con1").set("number", 10);
    model.result("pg17").feature("con1").set("coloring", "uniform");
    model.result("pg17").feature("con1").set("color", "white");
    model.result("pg17").feature("con1").set("colorlegend", false);
    model.result("pg17").feature("con1").set("manualindexing", true);
    model.result("pg17").create("vol2", "Volume");
    model.result("pg17").feature("vol2").set("arraydim", "1");
    model.result("pg17").feature("vol2").set("data", "dset5");
    model.result("pg17").feature("vol2").setIndex("looplevel", 2, 0);
    model.result("pg17").feature("vol2").set("expr", "tcs2.c_wA_3D");
    model.result("pg17").feature("vol2").set("rangecoloractive", true);
    model.result("pg17").feature("vol2").set("rangecolormin", 4);
    model.result("pg17").feature("vol2").set("rangecolormax", 12);
    model.result("pg17").feature("vol2").set("colortable", "Cynanthus");
    model.result("pg17").feature("vol2").set("colorlegend", false);
    model.result("pg17").feature("vol2").set("manualindexing", true);
    model.result("pg17").feature("vol2").set("arrayindex", 1);
    model.result("pg17").create("con2", "Contour");
    model.result("pg17").feature("con2").set("arraydim", "1");
    model.result("pg17").feature("con2").set("data", "dset5");
    model.result("pg17").feature("con2").setIndex("looplevel", 2, 0);
    model.result("pg17").feature("con2").set("expr", "tcs2.c_wA_3D");
    model.result("pg17").feature("con2").set("number", 10);
    model.result("pg17").feature("con2").set("coloring", "uniform");
    model.result("pg17").feature("con2").set("color", "white");
    model.result("pg17").feature("con2").set("colorlegend", false);
    model.result("pg17").feature("con2").set("manualindexing", true);
    model.result("pg17").feature("con2").set("arrayindex", 1);
    model.result("pg17").create("vol3", "Volume");
    model.result("pg17").feature("vol3").set("arraydim", "1");
    model.result("pg17").feature("vol3").set("data", "dset5");
    model.result("pg17").feature("vol3").set("expr", "tcs2.c_wA_3D");
    model.result("pg17").feature("vol3").set("rangecoloractive", true);
    model.result("pg17").feature("vol3").set("rangecolormin", 4);
    model.result("pg17").feature("vol3").set("rangecolormax", 12);
    model.result("pg17").feature("vol3").set("colortable", "Cynanthus");
    model.result("pg17").feature("vol3").set("colorlegend", false);
    model.result("pg17").feature("vol3").set("manualindexing", true);
    model.result("pg17").feature("vol3").set("arrayindex", 2);
    model.result("pg17").create("con3", "Contour");
    model.result("pg17").feature("con3").set("arraydim", "1");
    model.result("pg17").feature("con3").set("data", "dset5");
    model.result("pg17").feature("con3").set("expr", "tcs2.c_wA_3D");
    model.result("pg17").feature("con3").set("number", 10);
    model.result("pg17").feature("con3").set("coloring", "uniform");
    model.result("pg17").feature("con3").set("color", "white");
    model.result("pg17").feature("con3").set("colorlegend", false);
    model.result("pg17").feature("con3").set("manualindexing", true);
    model.result("pg17").feature("con3").set("arrayindex", 2);
    model.result("pg17").run();
    model.result("pg7").run();
    model.result("pg7").create("lngr4", "LineGraph");
    model.result("pg7").feature("lngr4").set("markerpos", "datapoints");
    model.result("pg7").feature("lngr4").set("linewidth", "preference");
    model.result("pg7").feature("lngr4").set("data", "dset5");
    model.result("pg7").feature("lngr4").setIndex("looplevelinput", "manual", 0);
    model.result("pg7").feature("lngr4").setIndex("looplevel", new int[]{2}, 0);
    model.result("pg7").feature("lngr4").selection().set(3, 5);
    model.result("pg7").feature("lngr4").set("expr", "tcs2.c_wA_3D");
    model.result("pg7").feature("lngr4").set("xdata", "expr");
    model.result("pg7").feature("lngr4").set("xdataexpr", "x");
    model.result("pg7").feature("lngr4").set("linecolor", "cyclereset");
    model.result("pg7").create("lngr5", "LineGraph");
    model.result("pg7").feature("lngr5").set("markerpos", "datapoints");
    model.result("pg7").feature("lngr5").set("linewidth", "preference");
    model.result("pg7").feature("lngr5").set("data", "dset5");
    model.result("pg7").feature("lngr5").setIndex("looplevelinput", "manual", 0);
    model.result("pg7").feature("lngr5").setIndex("looplevel", new int[]{2}, 0);
    model.result("pg7").feature("lngr5").selection().set(3, 5);
    model.result("pg7").feature("lngr5").set("expr", "tcs2.c_wB_3D");
    model.result("pg7").feature("lngr5").set("xdata", "expr");
    model.result("pg7").feature("lngr5").set("xdataexpr", "x");
    model.result("pg7").create("lngr6", "LineGraph");
    model.result("pg7").feature("lngr6").set("markerpos", "datapoints");
    model.result("pg7").feature("lngr6").set("linewidth", "preference");
    model.result("pg7").feature("lngr6").set("data", "dset5");
    model.result("pg7").feature("lngr6").setIndex("looplevelinput", "manual", 0);
    model.result("pg7").feature("lngr6").setIndex("looplevel", new int[]{2}, 0);
    model.result("pg7").feature("lngr6").selection().set(3, 5);
    model.result("pg7").feature("lngr6").set("expr", "tcs2.c_wC_3D");
    model.result("pg7").feature("lngr6").set("xdata", "expr");
    model.result("pg7").feature("lngr6").set("xdataexpr", "x");
    model.result("pg7").run();
    model.result().create("pg18", "PlotGroup1D");
    model.result("pg18").run();
    model.result("pg18").set("data", "none");
    model.result("pg18").set("showgrid", false);
    model.result("pg18").create("lngr1", "LineGraph");
    model.result("pg18").feature("lngr1").set("markerpos", "datapoints");
    model.result("pg18").feature("lngr1").set("linewidth", "preference");
    model.result("pg18").feature("lngr1").set("data", "dset1");
    model.result("pg18").feature("lngr1").selection().set(2);
    model.result("pg18").feature("lngr1").set("expr", "tcs.c_wA_2D");
    model.result("pg18").feature("lngr1").set("xdata", "expr");
    model.result("pg18").feature("lngr1").set("xdataexpr", "x");
    model.result("pg18").feature("lngr1").set("linestyle", "dashed");
    model.result("pg18").create("lngr2", "LineGraph");
    model.result("pg18").feature("lngr2").set("markerpos", "datapoints");
    model.result("pg18").feature("lngr2").set("linewidth", "preference");
    model.result("pg18").feature("lngr2").set("data", "dset5");
    model.result("pg18").feature("lngr2").selection().set(3, 5);
    model.result("pg18").feature("lngr2").set("expr", "tcs2.c_wA_3D");
    model.result("pg18").feature("lngr2").set("xdata", "expr");
    model.result("pg18").feature("lngr2").set("xdataexpr", "x");
    model.result("pg18").feature("lngr2").set("linecolor", "cyclereset");
    model.result("pg18").feature("lngr2").set("legend", true);
    model.result("pg18").run();
    model.result("pg18").run();
    model.result("pg18").set("titletype", "none");
    model.result("pg18").set("legendpos", "lowerright");
    model.result().evaluationGroup().create("eg3", "EvaluationGroup");
    model.result().evaluationGroup("eg3").set("data", "dset5");
    model.result().evaluationGroup("eg3").label("\u8d28\u91cf\u5e73\u8861, A_3D (tcs2)");
    model.result().evaluationGroup("eg3").create("int1", "IntSurface");
    model.result().evaluationGroup("eg3").feature("int1").set("intvolume", true);
    model.result().evaluationGroup("eg3").feature("int1").selection().all();
    model.result().evaluationGroup("eg3").feature("int1").set("expr", new String[]{"tcs2.ntflux_wA_3D"});
    model.result().evaluationGroup("eg3").feature("int1").set("descr", "\u603b\u901a\u91cf\uff0c\u6d41\u5165");
    model.result().evaluationGroup("eg3").feature("int1").selection().set(1);
    model.result().evaluationGroup("eg3").feature("int1").label("\u603b\u901a\u91cf\uff0c\u6d41\u5165");
    model.result().evaluationGroup("eg3").create("int2", "IntSurface");

    return model;
  }

  public static Model run3(Model model) {
    model.result().evaluationGroup("eg3").feature("int2").set("intvolume", true);
    model.result().evaluationGroup("eg3").feature("int2").selection().all();
    model.result().evaluationGroup("eg3").feature("int2").set("expr", new String[]{"tcs2.ntflux_wA_3D"});
    model.result().evaluationGroup("eg3").feature("int2").set("descr", "\u603b\u901a\u91cf\uff0c\u6d41\u51fa");
    model.result().evaluationGroup("eg3").feature("int2").selection().set(6);
    model.result().evaluationGroup("eg3").feature("int2").label("\u603b\u901a\u91cf\uff0c\u6d41\u51fa");
    model.result().evaluationGroup("eg3").create("int3", "IntVolume");
    model.result().evaluationGroup("eg3").feature("int3").label("\u603b\u901f\u7387\u8868\u8fbe\u5f0f");
    model.result().evaluationGroup("eg3").feature("int3").set("expr", new String[]{"tcs2.R_wA_3D"});
    model.result().evaluationGroup("eg3").feature("int3").set("descr", "\u603b\u901f\u7387\u8868\u8fbe\u5f0f");
    model.result().evaluationGroup("eg3").feature("int3").selection().set(1);
    model.result().evaluationGroup("eg3").create("int4", "IntSurface");
    model.result().evaluationGroup("eg3").feature("int4").set("intvolume", true);
    model.result().evaluationGroup("eg3").feature("int4").selection().all();
    model.result().evaluationGroup("eg3").feature("int4").set("expr", new String[]{"tcs2.ntflux_wA_3D"});
    model.result().evaluationGroup("eg3").feature("int4")
         .set("descr", "\u603b\u901a\u91cf\uff0c\u6240\u6709\u8fb9\u754c");
    model.result().evaluationGroup("eg3").feature("int4").selection().set(1, 2, 3, 4, 5, 6);
    model.result().evaluationGroup("eg3").feature("int4").label("\u603b\u901a\u91cf\uff0c\u6240\u6709\u8fb9\u754c");
    model.result().evaluationGroup("eg3").set("type", "general");
    model.result().evaluationGroup("eg3").set("generalexpr", "-int4+int3");
    model.result().evaluationGroup("eg3").set("keepchildnodes", true);
    model.result().evaluationGroup("eg3").set("generalheader", "\u8d28\u91cf\u5e73\u8861");
    model.result().evaluationGroup("eg3").label("\u8d28\u91cf\u5e73\u8861, A_3D (tcs2)");
    model.result().evaluationGroup().create("eg4", "EvaluationGroup");
    model.result().evaluationGroup("eg4").set("data", "dset5");
    model.result().evaluationGroup("eg4").label("\u8d28\u91cf\u5e73\u8861, B_3D (tcs2)");
    model.result().evaluationGroup("eg4").create("int1", "IntSurface");
    model.result().evaluationGroup("eg4").feature("int1").set("intvolume", true);
    model.result().evaluationGroup("eg4").feature("int1").selection().all();
    model.result().evaluationGroup("eg4").feature("int1").set("expr", new String[]{"tcs2.ntflux_wB_3D"});
    model.result().evaluationGroup("eg4").feature("int1").set("descr", "\u603b\u901a\u91cf\uff0c\u6d41\u5165");
    model.result().evaluationGroup("eg4").feature("int1").selection().set(1);
    model.result().evaluationGroup("eg4").feature("int1").label("\u603b\u901a\u91cf\uff0c\u6d41\u5165");
    model.result().evaluationGroup("eg4").create("int2", "IntSurface");
    model.result().evaluationGroup("eg4").feature("int2").set("intvolume", true);
    model.result().evaluationGroup("eg4").feature("int2").selection().all();
    model.result().evaluationGroup("eg4").feature("int2").set("expr", new String[]{"tcs2.ntflux_wB_3D"});
    model.result().evaluationGroup("eg4").feature("int2").set("descr", "\u603b\u901a\u91cf\uff0c\u6d41\u51fa");
    model.result().evaluationGroup("eg4").feature("int2").selection().set(6);
    model.result().evaluationGroup("eg4").feature("int2").label("\u603b\u901a\u91cf\uff0c\u6d41\u51fa");
    model.result().evaluationGroup("eg4").create("int3", "IntVolume");
    model.result().evaluationGroup("eg4").feature("int3").label("\u603b\u901f\u7387\u8868\u8fbe\u5f0f");
    model.result().evaluationGroup("eg4").feature("int3").set("expr", new String[]{"tcs2.R_wB_3D"});
    model.result().evaluationGroup("eg4").feature("int3").set("descr", "\u603b\u901f\u7387\u8868\u8fbe\u5f0f");
    model.result().evaluationGroup("eg4").feature("int3").selection().set(1);
    model.result().evaluationGroup("eg4").create("int4", "IntSurface");
    model.result().evaluationGroup("eg4").feature("int4").set("intvolume", true);
    model.result().evaluationGroup("eg4").feature("int4").selection().all();
    model.result().evaluationGroup("eg4").feature("int4").set("expr", new String[]{"tcs2.ntflux_wB_3D"});
    model.result().evaluationGroup("eg4").feature("int4")
         .set("descr", "\u603b\u901a\u91cf\uff0c\u6240\u6709\u8fb9\u754c");
    model.result().evaluationGroup("eg4").feature("int4").selection().set(1, 2, 3, 4, 5, 6);
    model.result().evaluationGroup("eg4").feature("int4").label("\u603b\u901a\u91cf\uff0c\u6240\u6709\u8fb9\u754c");
    model.result().evaluationGroup("eg4").set("type", "general");
    model.result().evaluationGroup("eg4").set("generalexpr", "-int4+int3");
    model.result().evaluationGroup("eg4").set("keepchildnodes", true);
    model.result().evaluationGroup("eg4").set("generalheader", "\u8d28\u91cf\u5e73\u8861");
    model.result().evaluationGroup("eg4").label("\u8d28\u91cf\u5e73\u8861, B_3D (tcs2)");
    model.result().evaluationGroup("eg3").set("generalexpr", "(-int4+int3)/int1");
    model.result().evaluationGroup("eg3").run();
    model.result().evaluationGroup("eg4").set("generalexpr", "(-int4+int3)/int1");
    model.result().evaluationGroup("eg4").run();
    model.result("pg4").run();

    model.nodeGroup().create("grp1", "Results");
    model.nodeGroup("grp1").set("type", "plotgroup");
    model.nodeGroup("grp1").add("plotgroup", "pg4");
    model.nodeGroup("grp1").add("plotgroup", "pg5");
    model.nodeGroup("grp1").add("plotgroup", "pg6");

    model.result("pg14").run();

    model.nodeGroup().create("grp2", "Results");
    model.nodeGroup("grp2").set("type", "plotgroup");
    model.nodeGroup("grp2").placeAfter("plotgroup", "pg7");
    model.nodeGroup("grp2").add("plotgroup", "pg14");
    model.nodeGroup("grp2").add("plotgroup", "pg15");
    model.nodeGroup("grp2").add("plotgroup", "pg16");
    model.nodeGroup("grp2").add("plotgroup", "pg17");

    model.result("pg7").run();

    model.nodeGroup("grp2").add("plotgroup", "pg7");
    model.nodeGroup("grp2").remove("plotgroup", "pg7", false);
    model.nodeGroup().create("grp3", "Results");
    model.nodeGroup("grp3").set("type", "plotgroup");
    model.nodeGroup().move("grp3", 2);
    model.nodeGroup("grp3").add("plotgroup", "pg7");
    model.nodeGroup("grp3").add("plotgroup", "pg18");
    model.nodeGroup().create("grp4", "Results");
    model.nodeGroup("grp4").set("type", "evaluationgroup");
    model.nodeGroup("grp4").add("evaluationgroup", "eg1");
    model.nodeGroup("grp4").add("evaluationgroup", "eg2");
    model.nodeGroup("grp4").add("evaluationgroup", "eg3");
    model.nodeGroup("grp4").add("evaluationgroup", "eg4");

    model.result().create("pg19", "PlotGroup3D");

    model.nodeGroup("grp3").add("plotgroup", "pg19");

    model.result("pg19").run();
    model.result("pg19").set("data", "none");
    model.result("pg19").set("titletype", "none");
    model.result("pg19").set("showlegends", false);
    model.result("pg19").set("plotarrayenable", true);
    model.result("pg19").set("arrayaxis", "y");
    model.result("pg19").create("vol1", "Volume");
    model.result("pg19").feature("vol1").set("arraydim", "1");
    model.result("pg19").feature("vol1").set("data", "dset5");
    model.result("pg19").feature("vol1").set("expr", "wC_3D");
    model.result("pg19").feature("vol1").set("colortable", "Arctium");
    model.result("pg19").feature("vol1").set("colortabletype", "discrete");
    model.result("pg19").feature("vol1").set("manualindexing", true);
    model.result("pg19").feature("vol1").set("arrayindex", 1);
    model.result("pg19").create("surf1", "Surface");
    model.result("pg19").feature("surf1").set("arraydim", "1");
    model.result("pg19").feature("surf1").set("data", "dset1");
    model.result("pg19").feature("surf1").set("expr", "wC_2D");
    model.result("pg19").feature("surf1").set("colortable", "Arctium");
    model.result("pg19").feature("surf1").set("colortabletype", "discrete");
    model.result("pg19").run();
    model.result("pg19").feature("surf1").set("manualindexing", true);
    model.result("pg19").run();

    model.view("view3").set("showgrid", false);

    model.result("pg19").run();

    model.title("\u8584\u57df\u4e2d\u7684\u6a2a\u6d41\u8d28\u91cf\u4f20\u9012");

    model
         .description("\u672c\u6a21\u578b\u6f14\u793a\u5982\u4f55\u4f7f\u7528\u201c\u9762\u5916\u901a\u91cf\u201d\u7279\u5f81\u901a\u8fc7\u4e8c\u7ef4\u6a21\u578b\u6765\u8fd1\u4f3c\u6a21\u62df\u8584\u57df\u4e2d\u7684\u8d28\u91cf\u4f20\u9012\uff0c\u7136\u540e\u901a\u8fc7\u8d28\u91cf\u5b88\u6052\u8ba1\u7b97\u5bf9\u4e8c\u7ef4\u8fd1\u4f3c\u7684\u7ed3\u679c\u8fdb\u884c\u9a8c\u8bc1\uff0c\u5e76\u901a\u8fc7\u6c42\u89e3\u7b49\u6548\u7684\u4e09\u7ef4\u6a21\u578b\u8fdb\u884c\u786e\u8ba4\u3002\u6b64\u5916\uff0c\u6a21\u578b\u4e2d\u8fd8\u6f14\u793a\u4e86\u9762\u5916\u539a\u5ea6\u5bf9\u4e8c\u7ef4\u8fd1\u4f3c\u76f8\u5bf9\u8bef\u5dee\u7684\u5f71\u54cd\uff0c\u5e76\u6307\u51fa\u4e86\u8fd9\u79cd\u65b9\u6cd5\u5728\u51cf\u5c11\u8ba1\u7b97\u65f6\u95f4\u4e0a\u7684\u6f5c\u529b\u3002");

    model.label("thin_domain.mph");

    return model;
  }

  public static void main(String[] args) {
    Model model = run();
    model = run2(model);
    run3(model);
  }

}
