/*
 * hydrogen_global_model.java
 */

import com.comsol.model.*;
import com.comsol.model.util.*;

/** Model exported on Apr 30 2026, 12:04 by COMSOL 6.3.0.290. */
public class hydrogen_global_model {

  public static Model run() {
    Model model = ModelUtil.create("Model");

    model.component().create("comp1", true);

    model.component("comp1").geom().create("geom1", 2);
    model.component("comp1").geom("geom1").axisymmetric(true);

    model.component("comp1").mesh().create("mesh1");

    model.component("comp1").physics().create("plas", "ColdPlasma", "geom1");

    model.study().create("std1");
    model.study("std1").create("stat", "Stationary");
    model.study("std1").feature("stat").setSolveFor("/physics/plas", true);

    model.component("comp1").geom("geom1").lengthUnit("cm");

    model.param().set("W", "2.5[cm]");
    model.param().descr("W", "\u7b49\u79bb\u5b50\u4f53\u5bbd\u5ea6");
    model.param().set("H", "3[cm]");
    model.param().descr("H", "\u7b49\u79bb\u5b50\u4f53\u9ad8\u5ea6");
    model.param().set("Wg", "5[cm]");
    model.param().descr("Wg", "\u4f20\u70ed\u5bbd\u5ea6");
    model.param().set("Hg", "6[cm]");
    model.param().descr("Hg", "\u4f20\u70ed\u9ad8\u5ea6");
    model.param().set("p0", "5[kPa]");
    model.param().descr("p0", "\u538b\u529b");
    model.param().set("pw", "300[W]");
    model.param().descr("pw", "\u529f\u7387");
    model.param().set("Qs", "500");
    model.param().descr("Qs", "\u8d28\u91cf\u6d41");
    model.param().set("pd", "pw/Vol");
    model.param().descr("pd", "\u529f\u7387\u5bc6\u5ea6");
    model.param().set("Vol", "(pi*W^2*H)");
    model.param().descr("Vol", "\u7b49\u79bb\u5b50\u4f53\u4f53\u79ef");
    model.param().set("f0", "2.45e9[Hz]");
    model.param().descr("f0", "\u6fc0\u53d1\u9891\u7387");
    model.param().set("w0", "f0*2*pi");
    model.param().descr("w0", "\u89d2\u9891\u7387");
    model.param().set("hl_ions", "0.05");
    model.param().descr("hl_ions", "\u79bb\u5b50\u6821\u6b63\u56e0\u5b50");

    model.component("comp1").variable().create("var1");

    model.component("comp1").geom("geom1").run();

    model.component("comp1").variable("var1").set("Lamb_diff", "((pi/H)^2+(2.405/W)^2)^-0.5");
    model.component("comp1").variable("var1").descr("Lamb_diff", "\u7269\u8d28\u7684\u6269\u6563\u957f\u5ea6");
    model.component("comp1").variable("var1").set("Lamb_diff_heat", "((pi/Hg)^2+(2.405/Wg)^2)^-0.5");
    model.component("comp1").variable("var1").descr("Lamb_diff_heat", "\u70ed\u91cf\u7684\u6269\u6563\u957f\u5ea6");

    model.component("comp1").func().create("int1", "Interpolation");
    model.component("comp1").func("int1").set("funcname", "pfnc");
    model.component("comp1").func("int1").setIndex("table", 300, 0, 0);
    model.component("comp1").func("int1").setIndex("table", 1400, 0, 1);
    model.component("comp1").func("int1").setIndex("table", 600, 1, 0);
    model.component("comp1").func("int1").setIndex("table", 2500, 1, 1);
    model.component("comp1").func("int1").setIndex("table", 1000, 2, 0);
    model.component("comp1").func("int1").setIndex("table", 5200, 2, 1);
    model.component("comp1").func("int1").setIndex("table", 1500, 3, 0);
    model.component("comp1").func("int1").setIndex("table", 8400, 3, 1);
    model.component("comp1").func("int1").setIndex("table", 2000, 4, 0);
    model.component("comp1").func("int1").setIndex("table", 11000, 4, 1);
    model.component("comp1").func("int1").set("extrap", "linear");
    model.component("comp1").func("int1").setIndex("fununit", "Pa", 0);
    model.component("comp1").func("int1").setIndex("argunit", "W", 0);

    model.component("comp1").geom("geom1").create("r1", "Rectangle");
    model.component("comp1").geom("geom1").feature("r1").set("size", new String[]{"W", "H"});
    model.component("comp1").geom("geom1").runPre("fin");
    model.component("comp1").geom("geom1").run();

    model.component("comp1").physics("plas").prop("DiffusionModel").set("DiffusionModel", "GlobalModel");
    model.component("comp1").physics("plas").prop("HeavySpeciesEnergyBalance")
         .set("includeHeavySpeciesEnergyEquation", true);
    model.component("comp1").physics("plas").prop("Reactor").set("ReactorType", "ConstantPressure");
    model.component("comp1").physics("plas").feature("pes1").set("pAgm", "pfnc(pw)");
    model.component("comp1").physics("plas").feature("pes1").set("sccmmfr", "Qs");
    model.component("comp1").physics("plas").feature("pes1").set("Pgm", "pw");
    model.component("comp1").physics("plas").feature("pes1").set("EpsilonI", "10[V]");
    model.component("comp1").physics("plas").feature("pes1").set("LambdaEffs", "Lamb_diff_heat");

    model.modelPath("Z:\\build\\patch\\daily\\locales\\zh_CN\\applications.compact\\Plasma_Module\\Global_Modeling");

    model.component("comp1").physics("plas").create("rg1", "ReactionGroup", 2);
    model.component("comp1").physics("plas").feature("rg1").set("reactionGroupType", "ElectronImpactReactions");
    model.component("comp1").physics("plas").feature("rg1").set("Filepath", "H2_plasma_chemistry_import_H.txt");
    model.component("comp1").physics("plas").feature("rg1").runCommand("importData");
    model.component("comp1").physics("plas").feature("rg1").label("H - Electron Impact Reactions");
    model.component("comp1").physics("plas").create("rg2", "ReactionGroup", 2);
    model.component("comp1").physics("plas").feature("rg2").set("reactionGroupType", "HeavySpeciesReactions");
    model.component("comp1").physics("plas").feature("rg2").set("Filepath", "H2_plasma_chemistry_import_H.txt");
    model.component("comp1").physics("plas").feature("rg2").runCommand("importData");
    model.component("comp1").physics("plas").feature().remove("rg2");
    model.component("comp1").physics("plas").create("rg2", "ReactionGroup", 2);
    model.component("comp1").physics("plas").feature("rg2").set("reactionGroupType", "ElectronImpactReactions");
    model.component("comp1").physics("plas").feature("rg2").set("Filepath", "H2_plasma_chemistry_import_H2.txt");
    model.component("comp1").physics("plas").feature("rg2").runCommand("importData");
    model.component("comp1").physics("plas").feature("rg2").label("H2 - Electron Impact Reactions");
    model.component("comp1").physics("plas").create("rg3", "ReactionGroup", 2);
    model.component("comp1").physics("plas").feature("rg3").set("reactionGroupType", "HeavySpeciesReactions");
    model.component("comp1").physics("plas").feature("rg3").set("Filepath", "H2_plasma_chemistry_import_H2.txt");
    model.component("comp1").physics("plas").feature("rg3").runCommand("importData");
    model.component("comp1").physics("plas").feature().remove("rg3");
    model.component("comp1").physics("plas").create("rg3", "ReactionGroup", 2);
    model.component("comp1").physics("plas").feature("rg3").set("reactionGroupType", "ElectronImpactReactions");
    model.component("comp1").physics("plas").feature("rg3").set("Filepath", "H2_plasma_chemistry_import_mixed.txt");
    model.component("comp1").physics("plas").feature("rg3").runCommand("importData");
    model.component("comp1").physics("plas").feature().remove("rg3");
    model.component("comp1").physics("plas").create("rg3", "ReactionGroup", 2);
    model.component("comp1").physics("plas").feature("rg3").set("reactionGroupType", "HeavySpeciesReactions");
    model.component("comp1").physics("plas").feature("rg3").set("Filepath", "H2_plasma_chemistry_import_mixed.txt");
    model.component("comp1").physics("plas").feature("rg3").runCommand("importData");
    model.component("comp1").physics("plas").feature("rg3").label("Mixed - Heavy Species Reactions");
    model.component("comp1").physics("plas").create("sr1", "SurfaceReaction", 1);
    model.component("comp1").physics("plas").feature("sr1").set("formula", "H=>0.5H2");
    model.component("comp1").physics("plas").feature("sr1").set("gammaf", "0.02");
    model.component("comp1").physics("plas").feature("sr1").set("gammai", "0.0");
    model.component("comp1").physics("plas").feature("sr1").set("ebari", "0.0");
    model.component("comp1").physics("plas").create("sr2", "SurfaceReaction", 1);
    model.component("comp1").physics("plas").feature("sr2").set("formula", "Hn2=>H");
    model.component("comp1").physics("plas").feature("sr2").set("gammaf", "1");
    model.component("comp1").physics("plas").feature("sr2").set("gammai", "0.0");
    model.component("comp1").physics("plas").feature("sr2").set("ebari", "0.0");
    model.component("comp1").physics("plas").create("sr3", "SurfaceReaction", 1);
    model.component("comp1").physics("plas").feature("sr3").set("formula", "Hn3=>H");
    model.component("comp1").physics("plas").feature("sr3").set("gammaf", "1");
    model.component("comp1").physics("plas").feature("sr3").set("gammai", "0.0");
    model.component("comp1").physics("plas").feature("sr3").set("ebari", "0.0");
    model.component("comp1").physics("plas").create("sr4", "SurfaceReaction", 1);
    model.component("comp1").physics("plas").feature("sr4").set("formula", "H+=>H");
    model.component("comp1").physics("plas").feature("sr4").set("gammaf", "1");
    model.component("comp1").physics("plas").feature("sr4").set("gammai", "0.0");
    model.component("comp1").physics("plas").feature("sr4").set("ebari", "0.0");
    model.component("comp1").physics("plas").create("sr5", "SurfaceReaction", 1);
    model.component("comp1").physics("plas").feature("sr5").set("formula", "H2+=>H2");
    model.component("comp1").physics("plas").feature("sr5").set("gammaf", "1");
    model.component("comp1").physics("plas").feature("sr5").set("gammai", "0.0");
    model.component("comp1").physics("plas").feature("sr5").set("ebari", "0.0");
    model.component("comp1").physics("plas").create("sr6", "SurfaceReaction", 1);
    model.component("comp1").physics("plas").feature("sr6").set("formula", "H3+=>H2+H");
    model.component("comp1").physics("plas").feature("sr6").set("gammaf", "1");
    model.component("comp1").physics("plas").feature("sr6").set("gammai", "0.0");
    model.component("comp1").physics("plas").feature("sr6").set("ebari", "0.0");
    model.component("comp1").physics("plas").feature("H").set("M", "0.00101");
    model.component("comp1").physics("plas").feature("H").set("sigma", "2.050e-10");
    model.component("comp1").physics("plas").feature("H").set("epsilonkb", "145.000");
    model.component("comp1").physics("plas").feature("H").set("mu", "0.000");
    model.component("comp1").physics("plas").feature("Hn2").set("M", "0.00101");
    model.component("comp1").physics("plas").feature("Hn2").set("sigma", "2.050e-10");
    model.component("comp1").physics("plas").feature("Hn2").set("epsilonkb", "145.000");
    model.component("comp1").physics("plas").feature("Hn2").set("mu", "0.000");
    model.component("comp1").physics("plas").feature("Hn3").set("M", "0.00101");
    model.component("comp1").physics("plas").feature("Hn3").set("sigma", "2.050e-10");
    model.component("comp1").physics("plas").feature("Hn3").set("epsilonkb", "145.000");
    model.component("comp1").physics("plas").feature("Hn3").set("mu", "0.000");
    model.component("comp1").physics("plas").feature("H_1p").set("M", "0.00101");
    model.component("comp1").physics("plas").feature("H_1p").set("sigma", "2.050e-10");
    model.component("comp1").physics("plas").feature("H_1p").set("epsilonkb", "145.000");
    model.component("comp1").physics("plas").feature("H_1p").set("mu", "0.000");
    model.component("comp1").physics("plas").feature("H2").set("M", "0.00202");
    model.component("comp1").physics("plas").feature("H2").set("sigma", "2.920e-10");
    model.component("comp1").physics("plas").feature("H2").set("epsilonkb", "38.0000");
    model.component("comp1").physics("plas").feature("H2").set("mu", "0.000");
    model.component("comp1").physics("plas").feature("H2_1p").set("M", "0.00202");
    model.component("comp1").physics("plas").feature("H2_1p").set("sigma", "2.920e-10");
    model.component("comp1").physics("plas").feature("H2_1p").set("epsilonkb", "38.0000");
    model.component("comp1").physics("plas").feature("H2_1p").set("mu", "0.000");
    model.component("comp1").physics("plas").feature("H3_1p").set("M", "0.00303");
    model.component("comp1").physics("plas").feature("H3_1p").set("sigma", "2.920e-10");
    model.component("comp1").physics("plas").feature("H3_1p").set("epsilonkb", "38.0000");
    model.component("comp1").physics("plas").feature("H3_1p").set("mu", "0.000");
    model.component("comp1").physics("plas").feature("H").set("Tlo", "200");
    model.component("comp1").physics("plas").feature("H").set("Tmid", "1000");
    model.component("comp1").physics("plas").feature("H").set("Thi", "3500");
    model.component("comp1").physics("plas").feature("H").set("aLo1", "2.50000000E00");
    model.component("comp1").physics("plas").feature("H").set("aLo2", "7.05332819E-13");
    model.component("comp1").physics("plas").feature("H").set("aLo3", "-1.99591964E-15");
    model.component("comp1").physics("plas").feature("H").set("aLo4", "2.30081632E-18");
    model.component("comp1").physics("plas").feature("H").set("aLo5", "-9.27732332E-22");
    model.component("comp1").physics("plas").feature("H").set("aLo6", "2.54736599E04");
    model.component("comp1").physics("plas").feature("H").set("aLo7", "-4.46682853E-01");
    model.component("comp1").physics("plas").feature("H").set("aHi1", "2.50000001E00");
    model.component("comp1").physics("plas").feature("H").set("aHi2", "-2.30842973E-11");
    model.component("comp1").physics("plas").feature("H").set("aHi3", "1.61561948E-14");
    model.component("comp1").physics("plas").feature("H").set("aHi4", "-4.73515235E-18");
    model.component("comp1").physics("plas").feature("H").set("aHi5", "4.98197357E-22");
    model.component("comp1").physics("plas").feature("H").set("aHi6", "2.54736599E04");
    model.component("comp1").physics("plas").feature("H").set("aHi7", "-4.46682914E-01");
    model.component("comp1").physics("plas").feature("H").set("hadd", "0");
    model.component("comp1").physics("plas").feature("Hn2").set("Tlo", "200");
    model.component("comp1").physics("plas").feature("Hn2").set("Tmid", "1000");
    model.component("comp1").physics("plas").feature("Hn2").set("Thi", "3500");
    model.component("comp1").physics("plas").feature("Hn2").set("aLo1", "2.50000000E00");
    model.component("comp1").physics("plas").feature("Hn2").set("aLo2", "7.05332819E-13");
    model.component("comp1").physics("plas").feature("Hn2").set("aLo3", "-1.99591964E-15");
    model.component("comp1").physics("plas").feature("Hn2").set("aLo4", "2.30081632E-18");
    model.component("comp1").physics("plas").feature("Hn2").set("aLo5", "-9.27732332E-22");
    model.component("comp1").physics("plas").feature("Hn2").set("aLo6", "2.54736599E04");
    model.component("comp1").physics("plas").feature("Hn2").set("aLo7", "-4.46682853E-01");
    model.component("comp1").physics("plas").feature("Hn2").set("aHi1", "2.50000001E00");
    model.component("comp1").physics("plas").feature("Hn2").set("aHi2", "-2.30842973E-11");
    model.component("comp1").physics("plas").feature("Hn2").set("aHi3", "1.61561948E-14");
    model.component("comp1").physics("plas").feature("Hn2").set("aHi4", "-4.73515235E-18");
    model.component("comp1").physics("plas").feature("Hn2").set("aHi5", "4.98197357E-22");
    model.component("comp1").physics("plas").feature("Hn2").set("aHi6", "2.54736599E04");
    model.component("comp1").physics("plas").feature("Hn2").set("aHi7", "-4.46682914E-01");
    model.component("comp1").physics("plas").feature("Hn2").set("hadd", "10.2043");
    model.component("comp1").physics("plas").feature("Hn3").set("Tlo", "200");
    model.component("comp1").physics("plas").feature("Hn3").set("Tmid", "1000");
    model.component("comp1").physics("plas").feature("Hn3").set("Thi", "3500");
    model.component("comp1").physics("plas").feature("Hn3").set("aLo1", "2.50000000E00");
    model.component("comp1").physics("plas").feature("Hn3").set("aLo2", "7.05332819E-13");
    model.component("comp1").physics("plas").feature("Hn3").set("aLo3", "-1.99591964E-15");
    model.component("comp1").physics("plas").feature("Hn3").set("aLo4", "2.30081632E-18");
    model.component("comp1").physics("plas").feature("Hn3").set("aLo5", "-9.27732332E-22");
    model.component("comp1").physics("plas").feature("Hn3").set("aLo6", "2.54736599E04");
    model.component("comp1").physics("plas").feature("Hn3").set("aLo7", "-4.46682853E-01");
    model.component("comp1").physics("plas").feature("Hn3").set("aHi1", "2.50000001E00");
    model.component("comp1").physics("plas").feature("Hn3").set("aHi2", "-2.30842973E-11");
    model.component("comp1").physics("plas").feature("Hn3").set("aHi3", "1.61561948E-14");
    model.component("comp1").physics("plas").feature("Hn3").set("aHi4", "-4.73515235E-18");
    model.component("comp1").physics("plas").feature("Hn3").set("aHi5", "4.98197357E-22");
    model.component("comp1").physics("plas").feature("Hn3").set("aHi6", "2.54736599E04");
    model.component("comp1").physics("plas").feature("Hn3").set("aHi7", "-4.46682914E-01");
    model.component("comp1").physics("plas").feature("Hn3").set("hadd", "12.0939");
    model.component("comp1").physics("plas").feature("H_1p").set("Tlo", "200");
    model.component("comp1").physics("plas").feature("H_1p").set("Tmid", "1000");
    model.component("comp1").physics("plas").feature("H_1p").set("Thi", "3500");
    model.component("comp1").physics("plas").feature("H_1p").set("aLo1", "2.50000000E00");
    model.component("comp1").physics("plas").feature("H_1p").set("aLo2", "7.05332819E-13");
    model.component("comp1").physics("plas").feature("H_1p").set("aLo3", "-1.99591964E-15");
    model.component("comp1").physics("plas").feature("H_1p").set("aLo4", "2.30081632E-18");
    model.component("comp1").physics("plas").feature("H_1p").set("aLo5", "-9.27732332E-22");
    model.component("comp1").physics("plas").feature("H_1p").set("aLo6", "2.54736599E04");
    model.component("comp1").physics("plas").feature("H_1p").set("aLo7", "-4.46682853E-01");
    model.component("comp1").physics("plas").feature("H_1p").set("aHi1", "2.50000001E00");
    model.component("comp1").physics("plas").feature("H_1p").set("aHi2", "-2.30842973E-11");
    model.component("comp1").physics("plas").feature("H_1p").set("aHi3", "1.61561948E-14");
    model.component("comp1").physics("plas").feature("H_1p").set("aHi4", "-4.73515235E-18");
    model.component("comp1").physics("plas").feature("H_1p").set("aHi5", "4.98197357E-22");
    model.component("comp1").physics("plas").feature("H_1p").set("aHi6", "2.54736599E04");
    model.component("comp1").physics("plas").feature("H_1p").set("aHi7", "-4.46682914E-01");
    model.component("comp1").physics("plas").feature("H_1p").set("hadd", "1.360570e+1");
    model.component("comp1").physics("plas").feature("H2").set("Tlo", "200");
    model.component("comp1").physics("plas").feature("H2").set("Tmid", "1000");
    model.component("comp1").physics("plas").feature("H2").set("Thi", "3500");
    model.component("comp1").physics("plas").feature("H2").set("aLo1", "2.34433112E00");
    model.component("comp1").physics("plas").feature("H2").set("aLo2", "7.98052075E-03");
    model.component("comp1").physics("plas").feature("H2").set("aLo3", "-1.94781510E-05");
    model.component("comp1").physics("plas").feature("H2").set("aLo4", "2.01572094E-08");
    model.component("comp1").physics("plas").feature("H2").set("aLo5", "-7.37611761E-12");
    model.component("comp1").physics("plas").feature("H2").set("aLo6", "-9.17935173E02");
    model.component("comp1").physics("plas").feature("H2").set("aLo7", "6.83010238E-01");
    model.component("comp1").physics("plas").feature("H2").set("aHi1", "3.33727920E00");
    model.component("comp1").physics("plas").feature("H2").set("aHi2", "-4.94024731E-05");
    model.component("comp1").physics("plas").feature("H2").set("aHi3", "4.99456778E-07");
    model.component("comp1").physics("plas").feature("H2").set("aHi4", "-1.79566394E-10");
    model.component("comp1").physics("plas").feature("H2").set("aHi5", "2.00255376E-14");
    model.component("comp1").physics("plas").feature("H2").set("aHi6", "-9.50158922E02");
    model.component("comp1").physics("plas").feature("H2").set("aHi7", "-3.20502331E001");
    model.component("comp1").physics("plas").feature("H2").set("hadd", "0");
    model.component("comp1").physics("plas").feature("H2_1p").set("Tlo", "200");
    model.component("comp1").physics("plas").feature("H2_1p").set("Tmid", "1000");
    model.component("comp1").physics("plas").feature("H2_1p").set("Thi", "3500");
    model.component("comp1").physics("plas").feature("H2_1p").set("aLo1", "2.34433112E00");
    model.component("comp1").physics("plas").feature("H2_1p").set("aLo2", "7.98052075E-03");
    model.component("comp1").physics("plas").feature("H2_1p").set("aLo3", "-1.94781510E-05");
    model.component("comp1").physics("plas").feature("H2_1p").set("aLo4", "2.01572094E-08");
    model.component("comp1").physics("plas").feature("H2_1p").set("aLo5", "-7.37611761E-12");
    model.component("comp1").physics("plas").feature("H2_1p").set("aLo6", "-9.17935173E02");
    model.component("comp1").physics("plas").feature("H2_1p").set("aLo7", "6.83010238E-01");
    model.component("comp1").physics("plas").feature("H2_1p").set("aHi1", "3.33727920E00");
    model.component("comp1").physics("plas").feature("H2_1p").set("aHi2", "-4.94024731E-05");
    model.component("comp1").physics("plas").feature("H2_1p").set("aHi3", "4.99456778E-07");
    model.component("comp1").physics("plas").feature("H2_1p").set("aHi4", "-1.79566394E-10");
    model.component("comp1").physics("plas").feature("H2_1p").set("aHi5", "2.00255376E-14");
    model.component("comp1").physics("plas").feature("H2_1p").set("aHi6", "-9.50158922E02");
    model.component("comp1").physics("plas").feature("H2_1p").set("aHi7", "-3.20502331E001");
    model.component("comp1").physics("plas").feature("H2_1p").set("hadd", "1.540000e+1");
    model.component("comp1").physics("plas").feature("H3_1p").set("Tlo", "200");
    model.component("comp1").physics("plas").feature("H3_1p").set("Tmid", "1000");
    model.component("comp1").physics("plas").feature("H3_1p").set("Thi", "3500");
    model.component("comp1").physics("plas").feature("H3_1p").set("aLo1", "2.34433112E00");
    model.component("comp1").physics("plas").feature("H3_1p").set("aLo2", "7.98052075E-03");
    model.component("comp1").physics("plas").feature("H3_1p").set("aLo3", "-1.94781510E-05");
    model.component("comp1").physics("plas").feature("H3_1p").set("aLo4", "2.01572094E-08");
    model.component("comp1").physics("plas").feature("H3_1p").set("aLo5", "-7.37611761E-12");
    model.component("comp1").physics("plas").feature("H3_1p").set("aLo6", "-9.17935173E02");
    model.component("comp1").physics("plas").feature("H3_1p").set("aLo7", "6.83010238E-01");
    model.component("comp1").physics("plas").feature("H3_1p").set("aHi1", "3.33727920E00");
    model.component("comp1").physics("plas").feature("H3_1p").set("aHi2", "-4.94024731E-05");
    model.component("comp1").physics("plas").feature("H3_1p").set("aHi3", "4.99456778E-07");
    model.component("comp1").physics("plas").feature("H3_1p").set("aHi4", "-1.79566394E-10");
    model.component("comp1").physics("plas").feature("H3_1p").set("aHi5", "2.00255376E-14");
    model.component("comp1").physics("plas").feature("H3_1p").set("aHi6", "-9.50158922E02");
    model.component("comp1").physics("plas").feature("H3_1p").set("aHi7", "-3.20502331E001");
    model.component("comp1").physics("plas").feature("H3_1p").set("hadd", "1.540000e+1");
    model.component("comp1").physics("plas").feature("H2").set("FromMassConstraint", true);
    model.component("comp1").physics("plas").feature("H2").set("xfeed", 1);

    model.nodeGroup().create("grp1", "Physics", "plas");
    model.nodeGroup("grp1").placeAfter("rg3");
    model.nodeGroup("grp1").add("e");
    model.nodeGroup("grp1").add("H");
    model.nodeGroup("grp1").add("Hn2");
    model.nodeGroup("grp1").add("Hn3");
    model.nodeGroup("grp1").add("H_1p");
    model.nodeGroup("grp1").add("H2");
    model.nodeGroup("grp1").add("H2_1p");
    model.nodeGroup("grp1").add("H3_1p");

    model.component("comp1").physics("plas").feature("sr1").selection().set(2);
    model.component("comp1").physics("plas").feature("sr1").set("SpecifyReactionUsing", "UseStickingDiffusion");
    model.component("comp1").physics("plas").feature("sr1").set("LambdaDiff", "Lamb_diff");
    model.component("comp1").physics("plas").feature("sr2").selection().all();
    model.component("comp1").physics("plas").feature("sr2").set("SpecifyReactionUsing", "UseStickingDiffusion");
    model.component("comp1").physics("plas").feature("sr2").set("LambdaDiff", "Lamb_diff");
    model.component("comp1").physics("plas").feature("sr3").selection().all();
    model.component("comp1").physics("plas").feature("sr3").set("SpecifyReactionUsing", "UseStickingDiffusion");
    model.component("comp1").physics("plas").feature("sr3").set("LambdaDiff", "Lamb_diff");
    model.component("comp1").physics("plas").feature("sr4").selection().all();
    model.component("comp1").physics("plas").feature("sr4").set("SpecifyReactionUsing", "UseBohm");
    model.component("comp1").physics("plas").feature("sr4").set("hl", "hl_ions");
    model.component("comp1").physics("plas").feature("sr5").selection().all();
    model.component("comp1").physics("plas").feature("sr5").set("SpecifyReactionUsing", "UseBohm");
    model.component("comp1").physics("plas").feature("sr5").set("hl", "hl_ions");
    model.component("comp1").physics("plas").feature("sr6").selection().all();
    model.component("comp1").physics("plas").feature("sr6").set("SpecifyReactionUsing", "UseBohm");
    model.component("comp1").physics("plas").feature("sr6").set("hl", "hl_ions");

    model.nodeGroup().create("grp2", "Physics", "plas");
    model.nodeGroup("grp2").placeAfter("rg3");
    model.nodeGroup("grp2").add("sr1");
    model.nodeGroup("grp2").add("sr2");
    model.nodeGroup("grp2").add("sr3");
    model.nodeGroup("grp2").add("sr4");
    model.nodeGroup("grp2").add("sr5");
    model.nodeGroup("grp2").add("sr6");

    model.component("comp1").mesh("mesh1").autoMeshSize(9);

    model.study("std1").setGenPlots(false);
    model.study("std1").feature("stat").set("useparam", true);
    model.study("std1").feature("stat").setIndex("pname", "W", 0);
    model.study("std1").feature("stat").setIndex("plistarr", "", 0);
    model.study("std1").feature("stat").setIndex("punit", "m", 0);
    model.study("std1").feature("stat").setIndex("pname", "W", 0);
    model.study("std1").feature("stat").setIndex("plistarr", "", 0);
    model.study("std1").feature("stat").setIndex("punit", "m", 0);
    model.study("std1").feature("stat").setIndex("pname", "pw", 0);
    model.study("std1").feature("stat").setIndex("plistarr", "range(300,200,2000)", 0);
    model.study("std1").feature("stat").set("pcontinuationmode", "no");
    model.study("std1").feature("stat").set("preusesol", "yes");
    model.study("std1").createAutoSequences("all");

    model.sol("sol1").runAll();

    model.result().create("pg1", "PlotGroup1D");
    model.result("pg1").run();
    model.result("pg1").label("\u6c14\u4f53\u6e29\u5ea6\u548c H \u6469\u5c14\u5206\u6570");
    model.result("pg1").create("glob1", "Global");
    model.result("pg1").feature("glob1").set("markerpos", "datapoints");
    model.result("pg1").feature("glob1").set("linewidth", "preference");
    model.result("pg1").feature("glob1").setIndex("expr", "plas.T", 0);
    model.result("pg1").feature("glob1").set("xdata", "expr");
    model.result("pg1").feature("glob1").set("xdataexpr", "pw/plas.Vol_gm");
    model.result("pg1").feature("glob1").set("xdataunit", "W/cm^3");
    model.result("pg1").feature().duplicate("glob2", "glob1");
    model.result("pg1").run();
    model.result("pg1").feature("glob2").setIndex("expr", "plas.x_wH", 0);
    model.result("pg1").run();
    model.result("pg1").set("titletype", "label");
    model.result("pg1").set("xlabelactive", true);
    model.result("pg1").set("xlabel", "\u529f\u7387\u5bc6\u5ea6 (W/cm<sup>3</sup>)");
    model.result("pg1").set("twoyaxes", true);
    model.result("pg1").setIndex("plotonsecyaxis", true, 1, 1);
    model.result("pg1").set("legendpos", "upperleft");
    model.result().create("pg2", "PlotGroup1D");
    model.result("pg2").run();
    model.result("pg2").label("\u79bb\u5b50\u5bc6\u5ea6");
    model.result("pg2").create("glob1", "Global");
    model.result("pg2").feature("glob1").set("markerpos", "datapoints");
    model.result("pg2").feature("glob1").set("linewidth", "preference");
    model.result("pg2").feature("glob1").setIndex("expr", "plas.n_wH_1p", 0);
    model.result("pg2").feature("glob1").setIndex("unit", "1/cm^3", 0);
    model.result("pg2").feature("glob1").setIndex("expr", "plas.n_wH2_1p", 1);
    model.result("pg2").feature("glob1").setIndex("unit", "1/cm^3", 1);
    model.result("pg2").feature("glob1").setIndex("expr", "plas.n_wH3_1p", 2);
    model.result("pg2").feature("glob1").setIndex("unit", "1/cm^3", 2);
    model.result("pg2").feature("glob1").set("xdata", "expr");
    model.result("pg2").feature("glob1").set("xdataexpr", "pw/plas.Vol_gm");
    model.result("pg2").feature("glob1").set("xdataunit", "W/cm^3");
    model.result("pg2").feature("glob1").set("autodescr", false);
    model.result("pg2").feature("glob1").set("autoexpr", true);
    model.result("pg2").run();
    model.result("pg2").run();
    model.result("pg2").set("titletype", "label");
    model.result("pg2").set("xlabelactive", true);
    model.result("pg2").set("xlabel", "\u529f\u7387\u5bc6\u5ea6 (W/cm<sup>3</sup>)");
    model.result("pg2").set("ylog", true);
    model.result("pg2").set("axislimits", true);
    model.result("pg2").set("ymin", "1e4");
    model.result("pg2").set("ymax", "2e12");
    model.result("pg2").set("legendpos", "middleright");
    model.result().create("pg3", "PlotGroup1D");
    model.result("pg3").run();
    model.result("pg3").label("\u7535\u5b50\u6e29\u5ea6");
    model.result("pg3").create("glob1", "Global");
    model.result("pg3").feature("glob1").set("markerpos", "datapoints");
    model.result("pg3").feature("glob1").set("linewidth", "preference");
    model.result("pg3").feature("glob1").setIndex("expr", "plas.Te", 0);
    model.result("pg3").feature("glob1").setIndex("descr", "\u9ea6\u514b\u65af\u97e6", 0);
    model.result("pg3").feature("glob1").set("xdata", "expr");
    model.result("pg3").feature("glob1").set("xdataexpr", "pw/plas.Vol_gm");
    model.result("pg3").feature("glob1").set("xdataunit", "W/cm^3");
    model.result("pg3").run();
    model.result("pg3").run();
    model.result("pg3").set("titletype", "label");
    model.result("pg3").set("xlabelactive", true);
    model.result("pg3").set("xlabel", "\u529f\u7387\u5bc6\u5ea6 (W/cm<sup>3</sup>)");
    model.result("pg3").set("ylabelactive", true);
    model.result("pg3").set("ylabel", "\u7535\u5b50\u6e29\u5ea6 (eV)");
    model.result("pg3").set("axislimits", true);
    model.result("pg3").set("ymin", 0);
    model.result("pg3").set("ymax", 2);
    model.result("pg3").run();
    model.result().create("pg4", "PlotGroup1D");
    model.result("pg4").run();
    model.result("pg4").label("\u4e2d\u6027\u5bc6\u5ea6");
    model.result("pg4").create("glob1", "Global");
    model.result("pg4").feature("glob1").set("markerpos", "datapoints");
    model.result("pg4").feature("glob1").set("linewidth", "preference");
    model.result("pg4").feature("glob1").setIndex("expr", "plas.n_wH", 0);
    model.result("pg4").feature("glob1").setIndex("expr", "plas.n_wH2", 1);
    model.result("pg4").feature("glob1").setIndex("expr", "plas.n_wHn2", 2);
    model.result("pg4").feature("glob1").setIndex("expr", "plas.n_wHn3", 3);

    return model;
  }

  public static Model run2(Model model) {
    model.result("pg4").feature("glob1").set("xdata", "expr");
    model.result("pg4").feature("glob1").set("xdataexpr", "pw/plas.Vol_gm");
    model.result("pg4").feature("glob1").set("xdataunit", "W/cm^3");
    model.result("pg4").feature("glob1").set("autodescr", false);
    model.result("pg4").feature("glob1").set("autoexpr", true);
    model.result("pg4").run();
    model.result("pg4").run();
    model.result("pg4").set("titletype", "label");
    model.result("pg4").set("xlabelactive", true);
    model.result("pg4").set("xlabel", "\u529f\u7387\u5bc6\u5ea6 (W/cm<sup>3</sup>)");
    model.result("pg4").set("ylog", true);
    model.result("pg4").set("legendpos", "middleright");
    model.result().create("pg5", "PlotGroup1D");
    model.result("pg5").run();
    model.result("pg5").label("\u76f8\u5bf9\u7535\u79bb\u7387");
    model.result("pg5").create("glob1", "Global");
    model.result("pg5").feature("glob1").set("markerpos", "datapoints");
    model.result("pg5").feature("glob1").set("linewidth", "preference");
    model.result("pg5").feature("glob1")
         .setIndex("expr", "(plas.r_rg3_1+plas.r_rg3_2)/(plas.r_rg3_1+plas.r_rg3_2+plas.r_rg3_3+plas.r_rg2_21+plas.r_rg1_7)", 0);
    model.result("pg5").feature("glob1").setIndex("descr", "Hn2,3+H2=>H3++e", 0);
    model.result("pg5").feature("glob1")
         .setIndex("expr", "(plas.r_rg3_3+plas.r_rg2_21)/(plas.r_rg3_1+plas.r_rg3_2+plas.r_rg3_3+plas.r_rg2_21+plas.r_rg1_7)", 1);
    model.result("pg5").feature("glob1").setIndex("descr", "e+H2=>2e+H2+ &  H2+H2+=>H3++H", 1);
    model.result("pg5").feature("glob1")
         .setIndex("expr", "plas.r_rg1_7/(plas.r_rg3_1+plas.r_rg3_2+plas.r_rg3_3+plas.r_rg2_21+plas.r_rg1_7)", 2);
    model.result("pg5").feature("glob1").setIndex("descr", "e+H=>H++2e", 2);
    model.result("pg5").feature("glob1").set("xdata", "expr");
    model.result("pg5").feature("glob1").set("xdataexpr", "pw/plas.Vol_gm");
    model.result("pg5").feature("glob1").set("xdataunit", "W/cm^3");
    model.result("pg5").feature("glob1").set("autosolution", false);
    model.result("pg5").run();
    model.result("pg5").run();
    model.result("pg5").set("titletype", "label");
    model.result("pg5").set("xlabelactive", true);
    model.result("pg5").set("xlabel", "\u529f\u7387\u5bc6\u5ea6 (W/cm<sup>3</sup>)");
    model.result("pg5").set("ylabelactive", true);
    model.result("pg5").set("ylabel", "\u76f8\u5bf9\u7535\u79bb\u7387");
    model.result("pg5").set("ylog", true);
    model.result("pg5").set("axislimits", true);
    model.result("pg5").set("ymin", "1e-5");
    model.result("pg5").set("ymax", 10);
    model.result("pg5").set("legendpos", "lowerleft");

    model.component("comp1").physics("plas").prop("EEDFSettings").set("eedf", "BoltzmannTwoTerm");
    model.component("comp1").physics("plas").prop("EEDFSettings").set("oscillating", true);
    model.component("comp1").physics("plas").prop("EEDFSettings").set("omegaN", "w0/plas.Nn");
    model.component("comp1").physics("plas").prop("EEDFSettings").set("emax", "50[V]");

    model.study().create("std2");
    model.study("std2").create("edfi", "EEDFInitialization");
    model.study("std2").feature("edfi").set("plotgroup", "Default");
    model.study("std2").feature("edfi").set("solnum", "auto");
    model.study("std2").feature("edfi").set("notsolnum", "auto");
    model.study("std2").feature("edfi").set("outputmap", new String[]{});
    model.study("std2").feature("edfi").set("ngenAUX", "1");
    model.study("std2").feature("edfi").set("goalngenAUX", "1");
    model.study("std2").feature("edfi").set("ngenAUX", "1");
    model.study("std2").feature("edfi").set("goalngenAUX", "1");
    model.study("std2").feature("edfi").setSolveFor("/physics/plas", true);
    model.study().create("std3");
    model.study("std3").create("stat", "Stationary");
    model.study("std3").feature("stat").setSolveFor("/physics/plas", true);
    model.study("std2").createAutoSequences("all");

    model.sol("sol2").runAll();

    model.result().dataset().create("dset3", "Solution");
    model.result().dataset("dset3").set("solution", "sol2");
    model.result().dataset("dset3").set("geom", "plas_eedf_xdim");
    model.result().create("pg6", "PlotGroup1D");
    model.result("pg6").set("data", "dset3");
    model.result("pg6").set("ylog", true);
    model.result("pg6").set("xlabelactive", true);
    model.result("pg6").set("ylabelactive", true);
    model.result("pg6").set("xlabel", "Scaled energy coordinate at reactor center");
    model.result("pg6").set("ylabel", "EEDF at reactor center");
    model.result("pg6").set("titletype", "label");
    model.result("pg6").create("lngr1", "LineGraph");
    model.result("pg6").feature("lngr1").set("xdata", "expr");
    model.result("pg6").feature("lngr1").set("xdataexpr", new String[]{"plas.xeedf"});
    model.result("pg6").feature("lngr1").selection().all();
    model.result("pg6").feature("lngr1").label("Two-term Boltzmann");
    model.result("pg6").feature("lngr1").set("legend", true);
    model.result("pg6").feature("lngr1").set("autosolution", false);
    model.result("pg6").feature("lngr1").set("autoplotlabel", true);
    model.result("pg6").feature("lngr1").set("expr", new String[]{"plas.fcap"});
    model.result("pg6").create("lngr2", "LineGraph");
    model.result("pg6").feature("lngr2").set("xdata", "expr");
    model.result("pg6").feature("lngr2").set("xdataexpr", new String[]{"plas.xeedf"});
    model.result("pg6").feature("lngr2").selection().all();
    model.result("pg6").feature("lngr2").set("expr", new String[]{"plas.fmax"});
    model.result("pg6").feature("lngr2").label("Maxwellian");
    model.result("pg6").feature("lngr2").set("legend", true);
    model.result("pg6").feature("lngr2").set("autosolution", false);
    model.result("pg6").feature("lngr2").set("autoplotlabel", true);
    model.result("pg6").create("lngr3", "LineGraph");
    model.result("pg6").feature("lngr3").set("xdata", "expr");
    model.result("pg6").feature("lngr3").set("xdataexpr", new String[]{"plas.xeedf"});
    model.result("pg6").feature("lngr3").selection().all();
    model.result("pg6").feature("lngr3").set("expr", new String[]{"plas.fdruy"});
    model.result("pg6").feature("lngr3").label("Druyvesteyn");
    model.result("pg6").feature("lngr3").set("legend", true);
    model.result("pg6").feature("lngr3").set("autosolution", false);
    model.result("pg6").feature("lngr3").set("autoplotlabel", true);
    model.result("pg6").create("lngr4", "LineGraph");
    model.result("pg6").feature("lngr4").set("xdata", "expr");
    model.result("pg6").feature("lngr4").set("xdataexpr", new String[]{"plas.xeedf"});
    model.result("pg6").feature("lngr4").selection().all();
    model.result("pg6").feature("lngr4").set("expr", new String[]{"plas.fgen"});
    model.result("pg6").feature("lngr4").label("Generalized (g=3)");
    model.result("pg6").feature("lngr4").set("legend", true);
    model.result("pg6").feature("lngr4").set("autosolution", false);
    model.result("pg6").feature("lngr4").set("autoplotlabel", true);
    model.result("pg6").label("\u7535\u5b50\u80fd\u91cf\u5206\u5e03\u51fd\u6570 (plas)");
    model.result("pg6").run();
    model.result("pg6").label("EEDF \u521d\u59cb\u5316");

    model.study("std3").feature("stat").set("useinitsol", true);
    model.study("std3").feature("stat").set("initmethod", "sol");
    model.study("std3").feature("stat").set("initstudy", "std2");
    model.study("std3").feature("stat").set("useparam", true);
    model.study("std3").feature("stat").setIndex("pname", "W", 0);
    model.study("std3").feature("stat").setIndex("plistarr", "", 0);
    model.study("std3").feature("stat").setIndex("punit", "m", 0);
    model.study("std3").feature("stat").setIndex("pname", "W", 0);
    model.study("std3").feature("stat").setIndex("plistarr", "", 0);
    model.study("std3").feature("stat").setIndex("punit", "m", 0);
    model.study("std3").feature("stat").setIndex("pname", "pw", 0);
    model.study("std3").feature("stat").setIndex("plistarr", "range(300,200,2000)", 0);
    model.study("std3").feature("stat").set("pcontinuationmode", "no");
    model.study("std3").feature("stat").set("preusesol", "yes");
    model.study("std3").setGenPlots(false);
    model.study("std3").createAutoSequences("all");

    model.sol("sol3").runAll();

    model.study("std3").label("\u73bb\u5c14\u5179\u66fc EEDF");
    model.study("std2").label("\u521d\u59cb\u5316 EEDF");
    model.study("std1").label("\u9ea6\u514b\u65af\u97e6 EEDF");

    model.result("pg1").run();
    model.result("pg1").feature().duplicate("glob3", "glob1");
    model.result("pg1").run();
    model.result("pg1").feature("glob3").set("data", "dset4");
    model.result("pg1").feature("glob3").set("linestyle", "dashed");
    model.result("pg1").feature("glob3").set("linecolor", "cyclereset");
    model.result("pg1").feature("glob3").set("legend", false);
    model.result("pg1").run();
    model.result("pg1").feature().duplicate("glob4", "glob2");
    model.result("pg1").run();
    model.result("pg1").feature("glob4").set("data", "dset4");
    model.result("pg1").feature("glob4").set("linestyle", "dashed");
    model.result("pg1").feature("glob4").set("legend", false);
    model.result("pg2").run();
    model.result("pg2").feature().duplicate("glob2", "glob1");
    model.result("pg2").run();
    model.result("pg2").feature("glob2").set("data", "dset4");
    model.result("pg2").feature("glob2").set("linestyle", "dashed");
    model.result("pg2").feature("glob2").set("linecolor", "cyclereset");
    model.result("pg2").feature("glob2").set("legend", false);
    model.result("pg2").run();
    model.result("pg3").run();
    model.result("pg3").feature().duplicate("glob2", "glob1");
    model.result("pg3").run();
    model.result("pg3").feature("glob2").set("data", "dset4");
    model.result("pg3").feature("glob2").setIndex("descr", "\u73bb\u5c14\u5179\u66fc", 0);
    model.result("pg3").run();
    model.result("pg4").run();
    model.result("pg4").feature().duplicate("glob2", "glob1");
    model.result("pg4").run();
    model.result("pg4").feature("glob2").set("data", "dset4");
    model.result("pg4").feature("glob2").set("linestyle", "dashed");
    model.result("pg4").feature("glob2").set("linecolor", "cyclereset");
    model.result("pg4").feature("glob2").set("legend", false);
    model.result("pg5").run();
    model.result("pg5").feature().duplicate("glob2", "glob1");
    model.result("pg5").run();
    model.result("pg5").feature("glob2").set("data", "dset4");
    model.result("pg5").feature("glob2").set("linestyle", "dashed");
    model.result("pg5").feature("glob2").set("linecolor", "cyclereset");
    model.result("pg5").feature("glob2").set("legend", false);
    model.result().dataset().duplicate("dset5", "dset4");
    model.result().dataset("dset5").set("comp", "plas_eedf_xdim");
    model.result().create("pg7", "PlotGroup1D");
    model.result("pg7").run();
    model.result("pg7").set("data", "dset5");
    model.result("pg7").label("EEDF \u73bb\u5c14\u5179\u66fc");
    model.result("pg7").create("lngr1", "LineGraph");
    model.result("pg7").feature("lngr1").set("markerpos", "datapoints");
    model.result("pg7").feature("lngr1").set("linewidth", "preference");
    model.result("pg7").feature("lngr1").selection().all();
    model.result("pg7").feature("lngr1").set("expr", "plas.fcap");
    model.result("pg7").feature("lngr1").set("xdata", "expr");
    model.result("pg7").feature("lngr1").set("xdataexpr", "plas.xeedf");
    model.result("pg7").feature("lngr1").set("legend", true);
    model.result("pg7").feature("lngr1").set("legendmethod", "evaluated");
    model.result("pg7").feature("lngr1").set("legendpattern", "eval(plas.Pgm/plas.Vol_gm, W/cm^3) W/cm<sup>3</sup>");
    model.result("pg7").run();
    model.result("pg7").feature().duplicate("lngr2", "lngr1");
    model.result("pg7").run();
    model.result("pg7").feature("lngr2").set("data", "dset5");
    model.result("pg7").feature("lngr2").setIndex("looplevelinput", "last", 0);
    model.result("pg7").feature("lngr2").set("expr", "plas.fmax");
    model.result("pg7").feature("lngr2").set("linecolor", "black");
    model.result("pg7").feature("lngr2").set("legendmethod", "manual");
    model.result("pg7").feature("lngr2").setIndex("legends", "\u9ea6\u514b\u65af\u97e6", 0);
    model.result("pg7").run();
    model.result("pg7").set("titletype", "label");
    model.result("pg7").set("xlabelactive", true);
    model.result("pg7").set("xlabel", "\u80fd\u91cf (eV)");
    model.result("pg7").set("ylabelactive", true);
    model.result("pg7").set("ylabel", "EEDF (eV <sup>-3/2</sup>)");
    model.result("pg7").set("ylog", true);
    model.result("pg7").set("axislimits", true);
    model.result("pg7").set("xmin", 0);
    model.result("pg7").set("xmax", 25);
    model.result("pg7").set("ymin", "1e-9");
    model.result("pg7").set("ymax", 2);
    model.result("pg7").run();
    model.result("pg1").run();
    model.result("pg2").run();
    model.result("pg3").run();
    model.result("pg4").run();
    model.result("pg5").run();
    model.result("pg7").run();

    model.title("\u6c22\u5168\u5c40\u6a21\u578b\u4e0e\u4e24\u9879\u73bb\u5c14\u5179\u66fc\u65b9\u7a0b\u8026\u5408");

    model
         .description("\u672c\u4f8b\u4f7f\u7528\u5168\u5c40\u6a21\u578b\u6765\u7814\u7a76\u4e2d\u7b49\u538b\u529b\u4e0b\u7684\u6c22\u7b49\u79bb\u5b50\u4f53\u53cd\u5e94\u5668\uff0c\u5176\u4e2d\u5305\u542b\u91cd\u7269\u8d28\u70ed\u65b9\u7a0b\u3002\u5728\u7b2c\u4e00\u90e8\u5206\u7684\u7814\u7a76\u4e2d\uff0c\u6211\u4eec\u4f7f\u7528\u4e86\u9ea6\u514b\u65af\u97e6\u7535\u5b50\u80fd\u91cf\u5206\u5e03\u51fd\u6570\uff1b\u800c\u5728\u7b2c\u4e8c\u90e8\u5206\u4e2d\uff0c\u5219\u91c7\u7528\u4e24\u9879\u8fd1\u4f3c\u7684\u73bb\u5c14\u5179\u66fc\u65b9\u7a0b\u6765\u81ea\u6d3d\u5730\u6c42\u89e3\u5168\u5c40\u6a21\u578b\u3002");

    model.mesh().clearMeshes();

    model.sol("sol1").clearSolutionData();
    model.sol("sol2").clearSolutionData();
    model.sol("sol3").clearSolutionData();

    model.label("hydrogen_global_model.mph");

    return model;
  }

  public static void main(String[] args) {
    Model model = run();
    run2(model);
  }

}
