/*
 * sf6_argon_global_model.java
 */

import com.comsol.model.*;
import com.comsol.model.util.*;

/** Model exported on Apr 30 2026, 12:05 by COMSOL 6.3.0.290. */
public class sf6_argon_global_model {

  public static Model run() {
    Model model = ModelUtil.create("Model");

    model.component().create("comp1", true);

    model.component("comp1").geom().create("geom1", 2);
    model.component("comp1").geom("geom1").axisymmetric(true);

    model.component("comp1").mesh().create("mesh1");

    model.component("comp1").physics().create("plas", "ColdPlasma", "geom1");

    model.study().create("std1");
    model.study("std1").create("stat", "Stationary");
    model.study("std1").feature("stat").setSolveFor("/physics/plas", true);

    model.param().set("Qfeed", "100");
    model.param().descr("Qfeed", "Feed mass flow in SCCM");
    model.param().set("Temp", "315[K]");
    model.param().descr("Temp", "Gas temperature");
    model.param().set("pA", "20[mTorr]");
    model.param().descr("pA", "Gas pressure");
    model.param().set("Pinp", "2000[W]");
    model.param().descr("Pinp", "Power input from source");
    model.param().set("abs_to_inp", "0.5");
    model.param().descr("abs_to_inp", "Power absorption ratio");
    model.param().set("Pabs", "Pinp*abs_to_inp");
    model.param().descr("Pabs", "Power absorbed by plasma");
    model.param().set("xAr", "0.1");
    model.param().descr("xAr", "Argon mole fraction");
    model.param().set("width", "19[cm]");
    model.param().descr("width", "Chamber radius");
    model.param().set("height", "17[cm]");
    model.param().descr("height", "Chamber height");
    model.param().set("lambda_diff", "((pi/height)^2+(2.405/width)^2)^-0.5");
    model.param().descr("lambda_diff", "Diffusion length for heat");

    model.component("comp1").geom("geom1").lengthUnit("cm");
    model.component("comp1").geom("geom1").create("r1", "Rectangle");
    model.component("comp1").geom("geom1").feature("r1").set("size", new String[]{"width", "height"});
    model.component("comp1").geom("geom1").runPre("fin");
    model.component("comp1").geom("geom1").run();

    model.component("comp1").physics("plas").prop("DiffusionModel").set("DiffusionModel", "GlobalModel");
    model.component("comp1").physics("plas").prop("Reactor").set("ReactorType", "ConstantPressure");
    model.component("comp1").physics("plas").prop("TransportSettings").set("calcThermo", true);
    model.component("comp1").physics("plas").prop("HeavySpeciesEnergyBalance")
         .set("includeHeavySpeciesEnergyEquation", true);
    model.component("comp1").physics("plas").feature("pes1").set("Tgm0", "Temp");
    model.component("comp1").physics("plas").feature("pes1").set("pAgm", "pA");
    model.component("comp1").physics("plas").feature("pes1").set("sccmmfr", "Qfeed");
    model.component("comp1").physics("plas").feature("pes1").set("Tfeed", "Temp");
    model.component("comp1").physics("plas").feature("pes1").set("Pgm", "Pabs");
    model.component("comp1").physics("plas").feature("pes1").set("EpsilonE", "2*plas.Te");
    model.component("comp1").physics("plas").feature("pes1").set("EpsilonI", "10[V]");
    model.component("comp1").physics("plas").feature("pes1").set("Ts", "Temp");
    model.component("comp1").physics("plas").feature("pes1").set("LambdaEffs", "lambda_diff");

    model.modelPath("Z:\\build\\patch\\daily\\locales\\zh_CN\\applications.compact\\Plasma_Module\\Global_Modeling");

    model.component("comp1").physics("plas").create("rg1", "ReactionGroup", 2);
    model.component("comp1").physics("plas").feature("rg1").set("reactionGroupType", "ElectronImpactReactions");
    model.component("comp1").physics("plas").feature("rg1")
         .set("Filepath", "SF6_Ar_plasma_chemistry_import_SF6.txt");
    model.component("comp1").physics("plas").feature("rg1").runCommand("importData");
    model.component("comp1").physics("plas").feature("rg1").label("SF6 - Electron Impact Reactions");
    model.component("comp1").physics("plas").create("rg2", "ReactionGroup", 2);
    model.component("comp1").physics("plas").feature("rg2").set("reactionGroupType", "HeavySpeciesReactions");
    model.component("comp1").physics("plas").feature("rg2")
         .set("Filepath", "SF6_Ar_plasma_chemistry_import_SF6.txt");
    model.component("comp1").physics("plas").feature("rg2").runCommand("importData");
    model.component("comp1").physics("plas").feature().remove("rg2");
    model.component("comp1").physics("plas").create("rg2", "ReactionGroup", 2);
    model.component("comp1").physics("plas").feature("rg2").set("reactionGroupType", "ElectronImpactReactions");
    model.component("comp1").physics("plas").feature("rg2").set("Filepath", "SF6_Ar_plasma_chemistry_import_F2.txt");
    model.component("comp1").physics("plas").feature("rg2").runCommand("importData");
    model.component("comp1").physics("plas").feature("rg2").label("F2 - Electron Impact Reactions");
    model.component("comp1").physics("plas").create("rg3", "ReactionGroup", 2);
    model.component("comp1").physics("plas").feature("rg3").set("reactionGroupType", "HeavySpeciesReactions");
    model.component("comp1").physics("plas").feature("rg3").set("Filepath", "SF6_Ar_plasma_chemistry_import_F2.txt");
    model.component("comp1").physics("plas").feature("rg3").runCommand("importData");
    model.component("comp1").physics("plas").feature().remove("rg3");
    model.component("comp1").physics("plas").create("rg3", "ReactionGroup", 2);
    model.component("comp1").physics("plas").feature("rg3").set("reactionGroupType", "ElectronImpactReactions");
    model.component("comp1").physics("plas").feature("rg3").set("Filepath", "SF6_Ar_plasma_chemistry_import_Ar.txt");
    model.component("comp1").physics("plas").feature("rg3").runCommand("importData");
    model.component("comp1").physics("plas").feature("rg3").label("Ar - Electron Impact Reactions");
    model.component("comp1").physics("plas").create("rg4", "ReactionGroup", 2);
    model.component("comp1").physics("plas").feature("rg4").set("reactionGroupType", "HeavySpeciesReactions");
    model.component("comp1").physics("plas").feature("rg4").set("Filepath", "SF6_Ar_plasma_chemistry_import_Ar.txt");
    model.component("comp1").physics("plas").feature("rg4").runCommand("importData");
    model.component("comp1").physics("plas").feature().remove("rg4");
    model.component("comp1").physics("plas").create("rg4", "ReactionGroup", 2);
    model.component("comp1").physics("plas").feature("rg4").set("reactionGroupType", "ElectronImpactReactions");
    model.component("comp1").physics("plas").feature("rg4")
         .set("Filepath", "SF6_Ar_plasma_chemistry_import_ion-ion_reactions.txt");
    model.component("comp1").physics("plas").feature("rg4").runCommand("importData");
    model.component("comp1").physics("plas").feature().remove("rg4");
    model.component("comp1").physics("plas").create("rg4", "ReactionGroup", 2);
    model.component("comp1").physics("plas").feature("rg4").set("reactionGroupType", "HeavySpeciesReactions");
    model.component("comp1").physics("plas").feature("rg4")
         .set("Filepath", "SF6_Ar_plasma_chemistry_import_ion-ion_reactions.txt");
    model.component("comp1").physics("plas").feature("rg4").runCommand("importData");
    model.component("comp1").physics("plas").feature("rg4").label("Ion-Ion - Heavy Species Reactions");
    model.component("comp1").physics("plas").create("rg5", "ReactionGroup", 2);
    model.component("comp1").physics("plas").feature("rg5").set("reactionGroupType", "ElectronImpactReactions");
    model.component("comp1").physics("plas").feature("rg5")
         .set("Filepath", "SF6_Ar_plasma_chemistry_import_neutral-neutral_reactions.txt");
    model.component("comp1").physics("plas").feature("rg5").runCommand("importData");
    model.component("comp1").physics("plas").feature().remove("rg5");
    model.component("comp1").physics("plas").create("rg5", "ReactionGroup", 2);
    model.component("comp1").physics("plas").feature("rg5").set("reactionGroupType", "HeavySpeciesReactions");
    model.component("comp1").physics("plas").feature("rg5")
         .set("Filepath", "SF6_Ar_plasma_chemistry_import_neutral-neutral_reactions.txt");
    model.component("comp1").physics("plas").feature("rg5").runCommand("importData");
    model.component("comp1").physics("plas").feature("rg5").label("Neutral-Neutral - Heavy Species Reactions");
    model.component("comp1").physics("plas").create("sr1", "SurfaceReaction", 1);
    model.component("comp1").physics("plas").feature("sr1").set("formula", "F=>0.5F2");
    model.component("comp1").physics("plas").feature("sr1").set("gammaf", "0.500");
    model.component("comp1").physics("plas").feature("sr1").set("gammai", "0");
    model.component("comp1").physics("plas").feature("sr1").set("ebari", "0");
    model.component("comp1").physics("plas").create("sr2", "SurfaceReaction", 1);
    model.component("comp1").physics("plas").feature("sr2").set("formula", "SF5+=>SF5");
    model.component("comp1").physics("plas").feature("sr2").set("gammaf", "1.000");
    model.component("comp1").physics("plas").feature("sr2").set("gammai", "0.02");
    model.component("comp1").physics("plas").feature("sr2").set("ebari", "5.8");
    model.component("comp1").physics("plas").create("sr3", "SurfaceReaction", 1);
    model.component("comp1").physics("plas").feature("sr3").set("formula", "SF4+=>SF4");
    model.component("comp1").physics("plas").feature("sr3").set("gammaf", "1.000");
    model.component("comp1").physics("plas").feature("sr3").set("gammai", "0.02");
    model.component("comp1").physics("plas").feature("sr3").set("ebari", "5.8");
    model.component("comp1").physics("plas").create("sr4", "SurfaceReaction", 1);
    model.component("comp1").physics("plas").feature("sr4").set("formula", "SF3+=>SF3");
    model.component("comp1").physics("plas").feature("sr4").set("gammaf", "1.000");
    model.component("comp1").physics("plas").feature("sr4").set("gammai", "0.02");
    model.component("comp1").physics("plas").feature("sr4").set("ebari", "5.8");
    model.component("comp1").physics("plas").create("sr5", "SurfaceReaction", 1);
    model.component("comp1").physics("plas").feature("sr5").set("formula", "SF2+=>SF2");
    model.component("comp1").physics("plas").feature("sr5").set("gammaf", "1.000");
    model.component("comp1").physics("plas").feature("sr5").set("gammai", "0.02");
    model.component("comp1").physics("plas").feature("sr5").set("ebari", "5.8");
    model.component("comp1").physics("plas").create("sr6", "SurfaceReaction", 1);
    model.component("comp1").physics("plas").feature("sr6").set("formula", "SF+=>SF");
    model.component("comp1").physics("plas").feature("sr6").set("gammaf", "1.000");
    model.component("comp1").physics("plas").feature("sr6").set("gammai", "0.02");
    model.component("comp1").physics("plas").feature("sr6").set("ebari", "5.8");
    model.component("comp1").physics("plas").create("sr7", "SurfaceReaction", 1);
    model.component("comp1").physics("plas").feature("sr7").set("formula", "S+=>S");
    model.component("comp1").physics("plas").feature("sr7").set("gammaf", "1.000");
    model.component("comp1").physics("plas").feature("sr7").set("gammai", "0.02");
    model.component("comp1").physics("plas").feature("sr7").set("ebari", "5.8");
    model.component("comp1").physics("plas").create("sr8", "SurfaceReaction", 1);
    model.component("comp1").physics("plas").feature("sr8").set("formula", "F2+=>F2");
    model.component("comp1").physics("plas").feature("sr8").set("gammaf", "1.000");
    model.component("comp1").physics("plas").feature("sr8").set("gammai", "0.02");
    model.component("comp1").physics("plas").feature("sr8").set("ebari", "5.8");
    model.component("comp1").physics("plas").create("sr9", "SurfaceReaction", 1);
    model.component("comp1").physics("plas").feature("sr9").set("formula", "F+=>F");
    model.component("comp1").physics("plas").feature("sr9").set("gammaf", "1.000");
    model.component("comp1").physics("plas").feature("sr9").set("gammai", "0.02");
    model.component("comp1").physics("plas").feature("sr9").set("ebari", "5.8");
    model.component("comp1").physics("plas").create("sr10", "SurfaceReaction", 1);
    model.component("comp1").physics("plas").feature("sr10").set("formula", "Ar+=>Ar");
    model.component("comp1").physics("plas").feature("sr10").set("gammaf", "1.000");
    model.component("comp1").physics("plas").feature("sr10").set("gammai", "0.07");
    model.component("comp1").physics("plas").feature("sr10").set("ebari", "5.8");
    model.component("comp1").physics("plas").create("sr11", "SurfaceReaction", 1);
    model.component("comp1").physics("plas").feature("sr11").set("formula", "Ars=>Ar");
    model.component("comp1").physics("plas").feature("sr11").set("gammaf", "1.000");
    model.component("comp1").physics("plas").feature("sr11").set("gammai", "0.07");
    model.component("comp1").physics("plas").feature("sr11").set("ebari", "5.8");
    model.component("comp1").physics("plas").feature("SF6_1m").set("PresetSpeciesData", "SF6");
    model.component("comp1").physics("plas").feature("SF6").set("PresetSpeciesData", "SF6");
    model.component("comp1").physics("plas").feature("F2_1p").set("PresetSpeciesData", "F2");
    model.component("comp1").physics("plas").feature("F2_1m").set("PresetSpeciesData", "F2");
    model.component("comp1").physics("plas").feature("F2").set("PresetSpeciesData", "F2");
    model.component("comp1").physics("plas").feature("F_1p").set("PresetSpeciesData", "F");
    model.component("comp1").physics("plas").feature("F_1m").set("PresetSpeciesData", "F");
    model.component("comp1").physics("plas").feature("F").set("PresetSpeciesData", "F");
    model.component("comp1").physics("plas").feature("Ar").set("PresetSpeciesData", "Ar");
    model.component("comp1").physics("plas").feature("Ars").set("PresetSpeciesData", "Ar");
    model.component("comp1").physics("plas").feature("Ar_1p").set("PresetSpeciesData", "Ar");
    model.component("comp1").physics("plas").feature("SF5_1p").set("M", "0.1270");
    model.component("comp1").physics("plas").feature("SF5_1p").set("sigma", "4.082[angstrom]");
    model.component("comp1").physics("plas").feature("SF5_1p").set("epsilonkb", "206.90");
    model.component("comp1").physics("plas").feature("SF5_1p").set("mu", "0.000");
    model.component("comp1").physics("plas").feature("SF5_1m").set("M", "0.1270");
    model.component("comp1").physics("plas").feature("SF5_1m").set("sigma", "4.082[angstrom]");
    model.component("comp1").physics("plas").feature("SF5_1m").set("epsilonkb", "206.90");
    model.component("comp1").physics("plas").feature("SF5_1m").set("mu", "0.000");
    model.component("comp1").physics("plas").feature("SF5").set("M", "0.1270");
    model.component("comp1").physics("plas").feature("SF5").set("sigma", "4.082[angstrom]");
    model.component("comp1").physics("plas").feature("SF5").set("epsilonkb", "206.90");
    model.component("comp1").physics("plas").feature("SF5").set("mu", "0.000");
    model.component("comp1").physics("plas").feature("SF4_1p").set("M", "0.1080");
    model.component("comp1").physics("plas").feature("SF4_1p").set("sigma", "4.082[angstrom]");
    model.component("comp1").physics("plas").feature("SF4_1p").set("epsilonkb", "206.90");
    model.component("comp1").physics("plas").feature("SF4_1p").set("mu", "0.000");
    model.component("comp1").physics("plas").feature("SF4_1m").set("M", "0.1080");
    model.component("comp1").physics("plas").feature("SF4_1m").set("sigma", "4.082[angstrom]");
    model.component("comp1").physics("plas").feature("SF4_1m").set("epsilonkb", "206.90");
    model.component("comp1").physics("plas").feature("SF4_1m").set("mu", "0.000");
    model.component("comp1").physics("plas").feature("SF4").set("M", "0.1080");
    model.component("comp1").physics("plas").feature("SF4").set("sigma", "4.082[angstrom]");
    model.component("comp1").physics("plas").feature("SF4").set("epsilonkb", "206.90");
    model.component("comp1").physics("plas").feature("SF4").set("mu", "0.000");
    model.component("comp1").physics("plas").feature("SF3_1p").set("M", "0.0890");
    model.component("comp1").physics("plas").feature("SF3_1p").set("sigma", "4.082[angstrom]");
    model.component("comp1").physics("plas").feature("SF3_1p").set("epsilonkb", "206.90");
    model.component("comp1").physics("plas").feature("SF3_1p").set("mu", "0.000");
    model.component("comp1").physics("plas").feature("SF3_1m").set("M", "0.0890");
    model.component("comp1").physics("plas").feature("SF3_1m").set("sigma", "4.082[angstrom]");
    model.component("comp1").physics("plas").feature("SF3_1m").set("epsilonkb", "206.90");
    model.component("comp1").physics("plas").feature("SF3_1m").set("mu", "0.000");
    model.component("comp1").physics("plas").feature("SF3").set("M", "0.0890");
    model.component("comp1").physics("plas").feature("SF3").set("sigma", "4.082[angstrom]");
    model.component("comp1").physics("plas").feature("SF3").set("epsilonkb", "206.90");
    model.component("comp1").physics("plas").feature("SF3").set("mu", "0.000");
    model.component("comp1").physics("plas").feature("SF2_1p").set("M", "0.0700");
    model.component("comp1").physics("plas").feature("SF2_1p").set("sigma", "4.082[angstrom]");
    model.component("comp1").physics("plas").feature("SF2_1p").set("epsilonkb", "206.90");
    model.component("comp1").physics("plas").feature("SF2_1p").set("mu", "0.000");
    model.component("comp1").physics("plas").feature("SF2_1m").set("M", "0.0700");
    model.component("comp1").physics("plas").feature("SF2_1m").set("sigma", "4.082[angstrom]");
    model.component("comp1").physics("plas").feature("SF2_1m").set("epsilonkb", "206.90");
    model.component("comp1").physics("plas").feature("SF2_1m").set("mu", "0.000");
    model.component("comp1").physics("plas").feature("SF2").set("M", "0.0700");
    model.component("comp1").physics("plas").feature("SF2").set("sigma", "4.082[angstrom]");
    model.component("comp1").physics("plas").feature("SF2").set("epsilonkb", "206.90");
    model.component("comp1").physics("plas").feature("SF2").set("mu", "0.000");
    model.component("comp1").physics("plas").feature("SF_1p").set("M", "0.0510");
    model.component("comp1").physics("plas").feature("SF_1p").set("sigma", "4.082[angstrom]");
    model.component("comp1").physics("plas").feature("SF_1p").set("epsilonkb", "206.90");
    model.component("comp1").physics("plas").feature("SF_1p").set("mu", "0.000");
    model.component("comp1").physics("plas").feature("SF").set("M", "0.0510");
    model.component("comp1").physics("plas").feature("SF").set("sigma", "4.082[angstrom]");
    model.component("comp1").physics("plas").feature("SF").set("epsilonkb", "206.90");
    model.component("comp1").physics("plas").feature("SF").set("mu", "0.000");
    model.component("comp1").physics("plas").feature("S_1p").set("M", "0.0320");
    model.component("comp1").physics("plas").feature("S_1p").set("sigma", "4.082[angstrom]");
    model.component("comp1").physics("plas").feature("S_1p").set("epsilonkb", "206.90");
    model.component("comp1").physics("plas").feature("S_1p").set("mu", "0.000");
    model.component("comp1").physics("plas").feature("S").set("M", "0.0320");
    model.component("comp1").physics("plas").feature("S").set("sigma", "4.082[angstrom]");
    model.component("comp1").physics("plas").feature("S").set("epsilonkb", "206.90");
    model.component("comp1").physics("plas").feature("S").set("mu", "0.000");
    model.component("comp1").physics("plas").feature("SF5_1p").set("Tlo", "200");
    model.component("comp1").physics("plas").feature("SF5_1p").set("Tmid", "1000");
    model.component("comp1").physics("plas").feature("SF5_1p").set("Thi", "6000");
    model.component("comp1").physics("plas").feature("SF5_1p").set("aLo1", "-3.84810931");
    model.component("comp1").physics("plas").feature("SF5_1p").set("aLo2", "0.0833564911");
    model.component("comp1").physics("plas").feature("SF5_1p").set("aLo3", "-1.32150474E-4");
    model.component("comp1").physics("plas").feature("SF5_1p").set("aLo4", "9.99672449E-8");
    model.component("comp1").physics("plas").feature("SF5_1p").set("aLo5", "-2.93723522E-11");
    model.component("comp1").physics("plas").feature("SF5_1p").set("aLo6", "-148233.041");
    model.component("comp1").physics("plas").feature("SF5_1p").set("aLo7", "37.2013304");
    model.component("comp1").physics("plas").feature("SF5_1p").set("aHi1", "15.5707503");
    model.component("comp1").physics("plas").feature("SF5_1p").set("aHi2", "0.00356270519");
    model.component("comp1").physics("plas").feature("SF5_1p").set("aHi3", "-1.40710159E-6");
    model.component("comp1").physics("plas").feature("SF5_1p").set("aHi4", "2.41523478E-10");
    model.component("comp1").physics("plas").feature("SF5_1p").set("aHi5", "-1.50764818E-14");
    model.component("comp1").physics("plas").feature("SF5_1p").set("aHi6", "-152276.157");
    model.component("comp1").physics("plas").feature("SF5_1p").set("aHi7", "-56.6147112");
    model.component("comp1").physics("plas").feature("SF5_1p").set("hadd", "11.2");
    model.component("comp1").physics("plas").feature("SF5_1m").set("Tlo", "200");
    model.component("comp1").physics("plas").feature("SF5_1m").set("Tmid", "1000");
    model.component("comp1").physics("plas").feature("SF5_1m").set("Thi", "6000");
    model.component("comp1").physics("plas").feature("SF5_1m").set("aLo1", "-3.84810931");
    model.component("comp1").physics("plas").feature("SF5_1m").set("aLo2", "0.0833564911");
    model.component("comp1").physics("plas").feature("SF5_1m").set("aLo3", "-1.32150474E-4");
    model.component("comp1").physics("plas").feature("SF5_1m").set("aLo4", "9.99672449E-8");
    model.component("comp1").physics("plas").feature("SF5_1m").set("aLo5", "-2.93723522E-11");
    model.component("comp1").physics("plas").feature("SF5_1m").set("aLo6", "-148233.041");
    model.component("comp1").physics("plas").feature("SF5_1m").set("aLo7", "37.2013304");
    model.component("comp1").physics("plas").feature("SF5_1m").set("aHi1", "15.5707503");
    model.component("comp1").physics("plas").feature("SF5_1m").set("aHi2", "0.00356270519");
    model.component("comp1").physics("plas").feature("SF5_1m").set("aHi3", "-1.40710159E-6");
    model.component("comp1").physics("plas").feature("SF5_1m").set("aHi4", "2.41523478E-10");
    model.component("comp1").physics("plas").feature("SF5_1m").set("aHi5", "-1.50764818E-14");
    model.component("comp1").physics("plas").feature("SF5_1m").set("aHi6", "-152276.157");
    model.component("comp1").physics("plas").feature("SF5_1m").set("aHi7", "-56.6147112");
    model.component("comp1").physics("plas").feature("SF5_1m").set("hadd", "0");
    model.component("comp1").physics("plas").feature("SF5").set("Tlo", "200");
    model.component("comp1").physics("plas").feature("SF5").set("Tmid", "1000");
    model.component("comp1").physics("plas").feature("SF5").set("Thi", "6000");
    model.component("comp1").physics("plas").feature("SF5").set("aLo1", "-3.84810931");
    model.component("comp1").physics("plas").feature("SF5").set("aLo2", "0.0833564911");
    model.component("comp1").physics("plas").feature("SF5").set("aLo3", "-1.32150474E-4");
    model.component("comp1").physics("plas").feature("SF5").set("aLo4", "9.99672449E-8");
    model.component("comp1").physics("plas").feature("SF5").set("aLo5", "-2.93723522E-11");
    model.component("comp1").physics("plas").feature("SF5").set("aLo6", "-148233.041");
    model.component("comp1").physics("plas").feature("SF5").set("aLo7", "37.2013304");
    model.component("comp1").physics("plas").feature("SF5").set("aHi1", "15.5707503");
    model.component("comp1").physics("plas").feature("SF5").set("aHi2", "0.00356270519");
    model.component("comp1").physics("plas").feature("SF5").set("aHi3", "-1.40710159E-6");
    model.component("comp1").physics("plas").feature("SF5").set("aHi4", "2.41523478E-10");
    model.component("comp1").physics("plas").feature("SF5").set("aHi5", "-1.50764818E-14");
    model.component("comp1").physics("plas").feature("SF5").set("aHi6", "-152276.157");
    model.component("comp1").physics("plas").feature("SF5").set("aHi7", "-56.6147112");
    model.component("comp1").physics("plas").feature("SF5").set("hadd", "0");
    model.component("comp1").physics("plas").feature("SF4_1p").set("Tlo", "200");
    model.component("comp1").physics("plas").feature("SF4_1p").set("Tmid", "1000");
    model.component("comp1").physics("plas").feature("SF4_1p").set("Thi", "6000");
    model.component("comp1").physics("plas").feature("SF4_1p").set("aLo1", "-3.84810931");
    model.component("comp1").physics("plas").feature("SF4_1p").set("aLo2", "0.0833564911");
    model.component("comp1").physics("plas").feature("SF4_1p").set("aLo3", "-1.32150474E-4");
    model.component("comp1").physics("plas").feature("SF4_1p").set("aLo4", "9.99672449E-8");
    model.component("comp1").physics("plas").feature("SF4_1p").set("aLo5", "-2.93723522E-11");
    model.component("comp1").physics("plas").feature("SF4_1p").set("aLo6", "-148233.041");
    model.component("comp1").physics("plas").feature("SF4_1p").set("aLo7", "37.2013304");
    model.component("comp1").physics("plas").feature("SF4_1p").set("aHi1", "15.5707503");
    model.component("comp1").physics("plas").feature("SF4_1p").set("aHi2", "0.00356270519");
    model.component("comp1").physics("plas").feature("SF4_1p").set("aHi3", "-1.40710159E-6");
    model.component("comp1").physics("plas").feature("SF4_1p").set("aHi4", "2.41523478E-10");
    model.component("comp1").physics("plas").feature("SF4_1p").set("aHi5", "-1.50764818E-14");
    model.component("comp1").physics("plas").feature("SF4_1p").set("aHi6", "-152276.157");
    model.component("comp1").physics("plas").feature("SF4_1p").set("aHi7", "-56.6147112");
    model.component("comp1").physics("plas").feature("SF4_1p").set("hadd", "12.03");
    model.component("comp1").physics("plas").feature("SF4_1m").set("Tlo", "200");
    model.component("comp1").physics("plas").feature("SF4_1m").set("Tmid", "1000");
    model.component("comp1").physics("plas").feature("SF4_1m").set("Thi", "6000");
    model.component("comp1").physics("plas").feature("SF4_1m").set("aLo1", "-3.84810931");
    model.component("comp1").physics("plas").feature("SF4_1m").set("aLo2", "0.0833564911");
    model.component("comp1").physics("plas").feature("SF4_1m").set("aLo3", "-1.32150474E-4");
    model.component("comp1").physics("plas").feature("SF4_1m").set("aLo4", "9.99672449E-8");
    model.component("comp1").physics("plas").feature("SF4_1m").set("aLo5", "-2.93723522E-11");
    model.component("comp1").physics("plas").feature("SF4_1m").set("aLo6", "-148233.041");
    model.component("comp1").physics("plas").feature("SF4_1m").set("aLo7", "37.2013304");
    model.component("comp1").physics("plas").feature("SF4_1m").set("aHi1", "15.5707503");
    model.component("comp1").physics("plas").feature("SF4_1m").set("aHi2", "0.00356270519");
    model.component("comp1").physics("plas").feature("SF4_1m").set("aHi3", "-1.40710159E-6");
    model.component("comp1").physics("plas").feature("SF4_1m").set("aHi4", "2.41523478E-10");
    model.component("comp1").physics("plas").feature("SF4_1m").set("aHi5", "-1.50764818E-14");
    model.component("comp1").physics("plas").feature("SF4_1m").set("aHi6", "-152276.157");
    model.component("comp1").physics("plas").feature("SF4_1m").set("aHi7", "-56.6147112");
    model.component("comp1").physics("plas").feature("SF4_1m").set("hadd", "0");
    model.component("comp1").physics("plas").feature("SF4").set("Tlo", "200");
    model.component("comp1").physics("plas").feature("SF4").set("Tmid", "1000");
    model.component("comp1").physics("plas").feature("SF4").set("Thi", "6000");
    model.component("comp1").physics("plas").feature("SF4").set("aLo1", "-3.84810931");
    model.component("comp1").physics("plas").feature("SF4").set("aLo2", "0.0833564911");
    model.component("comp1").physics("plas").feature("SF4").set("aLo3", "-1.32150474E-4");
    model.component("comp1").physics("plas").feature("SF4").set("aLo4", "9.99672449E-8");
    model.component("comp1").physics("plas").feature("SF4").set("aLo5", "-2.93723522E-11");
    model.component("comp1").physics("plas").feature("SF4").set("aLo6", "-148233.041");
    model.component("comp1").physics("plas").feature("SF4").set("aLo7", "37.2013304");
    model.component("comp1").physics("plas").feature("SF4").set("aHi1", "15.5707503");
    model.component("comp1").physics("plas").feature("SF4").set("aHi2", "0.00356270519");
    model.component("comp1").physics("plas").feature("SF4").set("aHi3", "-1.40710159E-6");
    model.component("comp1").physics("plas").feature("SF4").set("aHi4", "2.41523478E-10");
    model.component("comp1").physics("plas").feature("SF4").set("aHi5", "-1.50764818E-14");
    model.component("comp1").physics("plas").feature("SF4").set("aHi6", "-152276.157");
    model.component("comp1").physics("plas").feature("SF4").set("aHi7", "-56.6147112");
    model.component("comp1").physics("plas").feature("SF4").set("hadd", "0");
    model.component("comp1").physics("plas").feature("SF3_1p").set("Tlo", "200");
    model.component("comp1").physics("plas").feature("SF3_1p").set("Tmid", "1000");
    model.component("comp1").physics("plas").feature("SF3_1p").set("Thi", "6000");
    model.component("comp1").physics("plas").feature("SF3_1p").set("aLo1", "-3.84810931");
    model.component("comp1").physics("plas").feature("SF3_1p").set("aLo2", "0.0833564911");
    model.component("comp1").physics("plas").feature("SF3_1p").set("aLo3", "-1.32150474E-4");
    model.component("comp1").physics("plas").feature("SF3_1p").set("aLo4", "9.99672449E-8");
    model.component("comp1").physics("plas").feature("SF3_1p").set("aLo5", "-2.93723522E-11");
    model.component("comp1").physics("plas").feature("SF3_1p").set("aLo6", "-148233.041");
    model.component("comp1").physics("plas").feature("SF3_1p").set("aLo7", "37.2013304");
    model.component("comp1").physics("plas").feature("SF3_1p").set("aHi1", "15.5707503");
    model.component("comp1").physics("plas").feature("SF3_1p").set("aHi2", "0.00356270519");
    model.component("comp1").physics("plas").feature("SF3_1p").set("aHi3", "-1.40710159E-6");
    model.component("comp1").physics("plas").feature("SF3_1p").set("aHi4", "2.41523478E-10");
    model.component("comp1").physics("plas").feature("SF3_1p").set("aHi5", "-1.50764818E-14");
    model.component("comp1").physics("plas").feature("SF3_1p").set("aHi6", "-152276.157");
    model.component("comp1").physics("plas").feature("SF3_1p").set("aHi7", "-56.6147112");
    model.component("comp1").physics("plas").feature("SF3_1p").set("hadd", "11");
    model.component("comp1").physics("plas").feature("SF3_1m").set("Tlo", "200");
    model.component("comp1").physics("plas").feature("SF3_1m").set("Tmid", "1000");
    model.component("comp1").physics("plas").feature("SF3_1m").set("Thi", "6000");
    model.component("comp1").physics("plas").feature("SF3_1m").set("aLo1", "-3.84810931");
    model.component("comp1").physics("plas").feature("SF3_1m").set("aLo2", "0.0833564911");
    model.component("comp1").physics("plas").feature("SF3_1m").set("aLo3", "-1.32150474E-4");
    model.component("comp1").physics("plas").feature("SF3_1m").set("aLo4", "9.99672449E-8");
    model.component("comp1").physics("plas").feature("SF3_1m").set("aLo5", "-2.93723522E-11");
    model.component("comp1").physics("plas").feature("SF3_1m").set("aLo6", "-148233.041");
    model.component("comp1").physics("plas").feature("SF3_1m").set("aLo7", "37.2013304");
    model.component("comp1").physics("plas").feature("SF3_1m").set("aHi1", "15.5707503");
    model.component("comp1").physics("plas").feature("SF3_1m").set("aHi2", "0.00356270519");
    model.component("comp1").physics("plas").feature("SF3_1m").set("aHi3", "-1.40710159E-6");

    return model;
  }

  public static Model run2(Model model) {
    model.component("comp1").physics("plas").feature("SF3_1m").set("aHi4", "2.41523478E-10");
    model.component("comp1").physics("plas").feature("SF3_1m").set("aHi5", "-1.50764818E-14");
    model.component("comp1").physics("plas").feature("SF3_1m").set("aHi6", "-152276.157");
    model.component("comp1").physics("plas").feature("SF3_1m").set("aHi7", "-56.6147112");
    model.component("comp1").physics("plas").feature("SF3_1m").set("hadd", "0");
    model.component("comp1").physics("plas").feature("SF3").set("Tlo", "200");
    model.component("comp1").physics("plas").feature("SF3").set("Tmid", "1000");
    model.component("comp1").physics("plas").feature("SF3").set("Thi", "6000");
    model.component("comp1").physics("plas").feature("SF3").set("aLo1", "-3.84810931");
    model.component("comp1").physics("plas").feature("SF3").set("aLo2", "0.0833564911");
    model.component("comp1").physics("plas").feature("SF3").set("aLo3", "-1.32150474E-4");
    model.component("comp1").physics("plas").feature("SF3").set("aLo4", "9.99672449E-8");
    model.component("comp1").physics("plas").feature("SF3").set("aLo5", "-2.93723522E-11");
    model.component("comp1").physics("plas").feature("SF3").set("aLo6", "-148233.041");
    model.component("comp1").physics("plas").feature("SF3").set("aLo7", "37.2013304");
    model.component("comp1").physics("plas").feature("SF3").set("aHi1", "15.5707503");
    model.component("comp1").physics("plas").feature("SF3").set("aHi2", "0.00356270519");
    model.component("comp1").physics("plas").feature("SF3").set("aHi3", "-1.40710159E-6");
    model.component("comp1").physics("plas").feature("SF3").set("aHi4", "2.41523478E-10");
    model.component("comp1").physics("plas").feature("SF3").set("aHi5", "-1.50764818E-14");
    model.component("comp1").physics("plas").feature("SF3").set("aHi6", "-152276.157");
    model.component("comp1").physics("plas").feature("SF3").set("aHi7", "-56.6147112");
    model.component("comp1").physics("plas").feature("SF3").set("hadd", "0");
    model.component("comp1").physics("plas").feature("SF2_1p").set("Tlo", "200");
    model.component("comp1").physics("plas").feature("SF2_1p").set("Tmid", "1000");
    model.component("comp1").physics("plas").feature("SF2_1p").set("Thi", "6000");
    model.component("comp1").physics("plas").feature("SF2_1p").set("aLo1", "-3.84810931");
    model.component("comp1").physics("plas").feature("SF2_1p").set("aLo2", "0.0833564911");
    model.component("comp1").physics("plas").feature("SF2_1p").set("aLo3", "-1.32150474E-4");
    model.component("comp1").physics("plas").feature("SF2_1p").set("aLo4", "9.99672449E-8");
    model.component("comp1").physics("plas").feature("SF2_1p").set("aLo5", "-2.93723522E-11");
    model.component("comp1").physics("plas").feature("SF2_1p").set("aLo6", "-148233.041");
    model.component("comp1").physics("plas").feature("SF2_1p").set("aLo7", "37.2013304");
    model.component("comp1").physics("plas").feature("SF2_1p").set("aHi1", "15.5707503");
    model.component("comp1").physics("plas").feature("SF2_1p").set("aHi2", "0.00356270519");
    model.component("comp1").physics("plas").feature("SF2_1p").set("aHi3", "-1.40710159E-6");
    model.component("comp1").physics("plas").feature("SF2_1p").set("aHi4", "2.41523478E-10");
    model.component("comp1").physics("plas").feature("SF2_1p").set("aHi5", "-1.50764818E-14");
    model.component("comp1").physics("plas").feature("SF2_1p").set("aHi6", "-152276.157");
    model.component("comp1").physics("plas").feature("SF2_1p").set("aHi7", "-56.6147112");
    model.component("comp1").physics("plas").feature("SF2_1p").set("hadd", "10.08");
    model.component("comp1").physics("plas").feature("SF2_1m").set("Tlo", "200");
    model.component("comp1").physics("plas").feature("SF2_1m").set("Tmid", "1000");
    model.component("comp1").physics("plas").feature("SF2_1m").set("Thi", "6000");
    model.component("comp1").physics("plas").feature("SF2_1m").set("aLo1", "-3.84810931");
    model.component("comp1").physics("plas").feature("SF2_1m").set("aLo2", "0.0833564911");
    model.component("comp1").physics("plas").feature("SF2_1m").set("aLo3", "-1.32150474E-4");
    model.component("comp1").physics("plas").feature("SF2_1m").set("aLo4", "9.99672449E-8");
    model.component("comp1").physics("plas").feature("SF2_1m").set("aLo5", "-2.93723522E-11");
    model.component("comp1").physics("plas").feature("SF2_1m").set("aLo6", "-148233.041");
    model.component("comp1").physics("plas").feature("SF2_1m").set("aLo7", "37.2013304");
    model.component("comp1").physics("plas").feature("SF2_1m").set("aHi1", "15.5707503");
    model.component("comp1").physics("plas").feature("SF2_1m").set("aHi2", "0.00356270519");
    model.component("comp1").physics("plas").feature("SF2_1m").set("aHi3", "-1.40710159E-6");
    model.component("comp1").physics("plas").feature("SF2_1m").set("aHi4", "2.41523478E-10");
    model.component("comp1").physics("plas").feature("SF2_1m").set("aHi5", "-1.50764818E-14");
    model.component("comp1").physics("plas").feature("SF2_1m").set("aHi6", "-152276.157");
    model.component("comp1").physics("plas").feature("SF2_1m").set("aHi7", "-56.6147112");
    model.component("comp1").physics("plas").feature("SF2_1m").set("hadd", "0");
    model.component("comp1").physics("plas").feature("SF2").set("Tlo", "200");
    model.component("comp1").physics("plas").feature("SF2").set("Tmid", "1000");
    model.component("comp1").physics("plas").feature("SF2").set("Thi", "6000");
    model.component("comp1").physics("plas").feature("SF2").set("aLo1", "-3.84810931");
    model.component("comp1").physics("plas").feature("SF2").set("aLo2", "0.0833564911");
    model.component("comp1").physics("plas").feature("SF2").set("aLo3", "-1.32150474E-4");
    model.component("comp1").physics("plas").feature("SF2").set("aLo4", "9.99672449E-8");
    model.component("comp1").physics("plas").feature("SF2").set("aLo5", "-2.93723522E-11");
    model.component("comp1").physics("plas").feature("SF2").set("aLo6", "-148233.041");
    model.component("comp1").physics("plas").feature("SF2").set("aLo7", "37.2013304");
    model.component("comp1").physics("plas").feature("SF2").set("aHi1", "15.5707503");
    model.component("comp1").physics("plas").feature("SF2").set("aHi2", "0.00356270519");
    model.component("comp1").physics("plas").feature("SF2").set("aHi3", "-1.40710159E-6");
    model.component("comp1").physics("plas").feature("SF2").set("aHi4", "2.41523478E-10");
    model.component("comp1").physics("plas").feature("SF2").set("aHi5", "-1.50764818E-14");
    model.component("comp1").physics("plas").feature("SF2").set("aHi6", "-152276.157");
    model.component("comp1").physics("plas").feature("SF2").set("aHi7", "-56.6147112");
    model.component("comp1").physics("plas").feature("SF2").set("hadd", "0");
    model.component("comp1").physics("plas").feature("SF_1p").set("Tlo", "200");
    model.component("comp1").physics("plas").feature("SF_1p").set("Tmid", "1000");
    model.component("comp1").physics("plas").feature("SF_1p").set("Thi", "6000");
    model.component("comp1").physics("plas").feature("SF_1p").set("aLo1", "-3.84810931");
    model.component("comp1").physics("plas").feature("SF_1p").set("aLo2", "0.0833564911");
    model.component("comp1").physics("plas").feature("SF_1p").set("aLo3", "-1.32150474E-4");
    model.component("comp1").physics("plas").feature("SF_1p").set("aLo4", "9.99672449E-8");
    model.component("comp1").physics("plas").feature("SF_1p").set("aLo5", "-2.93723522E-11");
    model.component("comp1").physics("plas").feature("SF_1p").set("aLo6", "-148233.041");
    model.component("comp1").physics("plas").feature("SF_1p").set("aLo7", "37.2013304");
    model.component("comp1").physics("plas").feature("SF_1p").set("aHi1", "15.5707503");
    model.component("comp1").physics("plas").feature("SF_1p").set("aHi2", "0.00356270519");
    model.component("comp1").physics("plas").feature("SF_1p").set("aHi3", "-1.40710159E-6");
    model.component("comp1").physics("plas").feature("SF_1p").set("aHi4", "2.41523478E-10");
    model.component("comp1").physics("plas").feature("SF_1p").set("aHi5", "-1.50764818E-14");
    model.component("comp1").physics("plas").feature("SF_1p").set("aHi6", "-152276.157");
    model.component("comp1").physics("plas").feature("SF_1p").set("aHi7", "-56.6147112");
    model.component("comp1").physics("plas").feature("SF_1p").set("hadd", "10.09");
    model.component("comp1").physics("plas").feature("SF").set("Tlo", "200");
    model.component("comp1").physics("plas").feature("SF").set("Tmid", "1000");
    model.component("comp1").physics("plas").feature("SF").set("Thi", "6000");
    model.component("comp1").physics("plas").feature("SF").set("aLo1", "-3.84810931");
    model.component("comp1").physics("plas").feature("SF").set("aLo2", "0.0833564911");
    model.component("comp1").physics("plas").feature("SF").set("aLo3", "-1.32150474E-4");
    model.component("comp1").physics("plas").feature("SF").set("aLo4", "9.99672449E-8");
    model.component("comp1").physics("plas").feature("SF").set("aLo5", "-2.93723522E-11");
    model.component("comp1").physics("plas").feature("SF").set("aLo6", "-148233.041");
    model.component("comp1").physics("plas").feature("SF").set("aLo7", "37.2013304");
    model.component("comp1").physics("plas").feature("SF").set("aHi1", "15.5707503");
    model.component("comp1").physics("plas").feature("SF").set("aHi2", "0.00356270519");
    model.component("comp1").physics("plas").feature("SF").set("aHi3", "-1.40710159E-6");
    model.component("comp1").physics("plas").feature("SF").set("aHi4", "2.41523478E-10");
    model.component("comp1").physics("plas").feature("SF").set("aHi5", "-1.50764818E-14");
    model.component("comp1").physics("plas").feature("SF").set("aHi6", "-152276.157");
    model.component("comp1").physics("plas").feature("SF").set("aHi7", "-56.6147112");
    model.component("comp1").physics("plas").feature("SF").set("hadd", "0");
    model.component("comp1").physics("plas").feature("S_1p").set("Tlo", "200");
    model.component("comp1").physics("plas").feature("S_1p").set("Tmid", "1000");
    model.component("comp1").physics("plas").feature("S_1p").set("Thi", "6000");
    model.component("comp1").physics("plas").feature("S_1p").set("aLo1", "-3.84810931");
    model.component("comp1").physics("plas").feature("S_1p").set("aLo2", "0.0833564911");
    model.component("comp1").physics("plas").feature("S_1p").set("aLo3", "-1.32150474E-4");
    model.component("comp1").physics("plas").feature("S_1p").set("aLo4", "9.99672449E-8");
    model.component("comp1").physics("plas").feature("S_1p").set("aLo5", "-2.93723522E-11");
    model.component("comp1").physics("plas").feature("S_1p").set("aLo6", "-148233.041");
    model.component("comp1").physics("plas").feature("S_1p").set("aLo7", "37.2013304");
    model.component("comp1").physics("plas").feature("S_1p").set("aHi1", "15.5707503");
    model.component("comp1").physics("plas").feature("S_1p").set("aHi2", "0.00356270519");
    model.component("comp1").physics("plas").feature("S_1p").set("aHi3", "-1.40710159E-6");
    model.component("comp1").physics("plas").feature("S_1p").set("aHi4", "2.41523478E-10");
    model.component("comp1").physics("plas").feature("S_1p").set("aHi5", "-1.50764818E-14");
    model.component("comp1").physics("plas").feature("S_1p").set("aHi6", "-152276.157");
    model.component("comp1").physics("plas").feature("S_1p").set("aHi7", "-56.6147112");
    model.component("comp1").physics("plas").feature("S_1p").set("hadd", "10.09");
    model.component("comp1").physics("plas").feature("S").set("Tlo", "200");
    model.component("comp1").physics("plas").feature("S").set("Tmid", "1000");
    model.component("comp1").physics("plas").feature("S").set("Thi", "6000");
    model.component("comp1").physics("plas").feature("S").set("aLo1", "-3.84810931");
    model.component("comp1").physics("plas").feature("S").set("aLo2", "0.0833564911");
    model.component("comp1").physics("plas").feature("S").set("aLo3", "-1.32150474E-4");
    model.component("comp1").physics("plas").feature("S").set("aLo4", "9.99672449E-8");
    model.component("comp1").physics("plas").feature("S").set("aLo5", "-2.93723522E-11");
    model.component("comp1").physics("plas").feature("S").set("aLo6", "-148233.041");
    model.component("comp1").physics("plas").feature("S").set("aLo7", "37.2013304");
    model.component("comp1").physics("plas").feature("S").set("aHi1", "15.5707503");
    model.component("comp1").physics("plas").feature("S").set("aHi2", "0.00356270519");
    model.component("comp1").physics("plas").feature("S").set("aHi3", "-1.40710159E-6");
    model.component("comp1").physics("plas").feature("S").set("aHi4", "2.41523478E-10");
    model.component("comp1").physics("plas").feature("S").set("aHi5", "-1.50764818E-14");
    model.component("comp1").physics("plas").feature("S").set("aHi6", "-152276.157");
    model.component("comp1").physics("plas").feature("S").set("aHi7", "-56.6147112");
    model.component("comp1").physics("plas").feature("S").set("hadd", "0");
    model.component("comp1").physics("plas").feature("SF6").set("FromMassConstraint", true);
    model.component("comp1").physics("plas").feature("SF6").set("xfeed", "1-xAr");
    model.component("comp1").physics("plas").feature("Ar").set("xfeed", "xAr");
    model.component("comp1").physics("plas").feature("F2_1p").set("hadd", 15.69);
    model.component("comp1").physics("plas").feature("F_1p").set("hadd", 17.687);
    model.component("comp1").physics("plas").feature("Ars").set("hadd", "11.50");
    model.component("comp1").physics("plas").feature("Ar_1p").set("hadd", "15.80");

    model.nodeGroup().create("grp1", "Physics", "plas");
    model.nodeGroup("grp1").placeAfter("rg5");
    model.nodeGroup("grp1").add("e");
    model.nodeGroup("grp1").add("SF6");
    model.nodeGroup("grp1").add("SF5_1p");
    model.nodeGroup("grp1").add("F");
    model.nodeGroup("grp1").add("SF4_1p");
    model.nodeGroup("grp1").add("SF3_1p");
    model.nodeGroup("grp1").add("SF2_1p");
    model.nodeGroup("grp1").add("F2");
    model.nodeGroup("grp1").add("SF_1p");
    model.nodeGroup("grp1").add("S_1p");
    model.nodeGroup("grp1").add("F2_1m");
    model.nodeGroup("grp1").add("SF4");
    model.nodeGroup("grp1").add("F_1m");
    model.nodeGroup("grp1").add("SF5");
    model.nodeGroup("grp1").add("SF2_1m");
    model.nodeGroup("grp1").add("SF3_1m");
    model.nodeGroup("grp1").add("SF4_1m");
    model.nodeGroup("grp1").add("SF5_1m");
    model.nodeGroup("grp1").add("SF6_1m");
    model.nodeGroup("grp1").add("SF");
    model.nodeGroup("grp1").add("SF2");
    model.nodeGroup("grp1").add("SF3");
    model.nodeGroup("grp1").add("S");
    model.nodeGroup("grp1").add("F2_1p");
    model.nodeGroup("grp1").add("F_1p");
    model.nodeGroup("grp1").add("Ar");
    model.nodeGroup("grp1").add("Ars");
    model.nodeGroup("grp1").add("Ar_1p");

    model.component("comp1").physics("plas").feature("sr1").selection().all();
    model.component("comp1").physics("plas").feature("sr2").selection().all();
    model.component("comp1").physics("plas").feature("sr2").set("SpecifyReactionUsing", "UseBohm");
    model.component("comp1").physics("plas").feature("sr2").set("hl", 0.25);
    model.component("comp1").physics("plas").feature("sr3").selection().all();
    model.component("comp1").physics("plas").feature("sr3").set("SpecifyReactionUsing", "UseBohm");
    model.component("comp1").physics("plas").feature("sr3").set("hl", 0.25);
    model.component("comp1").physics("plas").feature("sr4").selection().all();
    model.component("comp1").physics("plas").feature("sr4").set("SpecifyReactionUsing", "UseBohm");
    model.component("comp1").physics("plas").feature("sr4").set("hl", 0.25);
    model.component("comp1").physics("plas").feature("sr5").selection().all();
    model.component("comp1").physics("plas").feature("sr5").set("SpecifyReactionUsing", "UseBohm");
    model.component("comp1").physics("plas").feature("sr5").set("hl", 0.25);
    model.component("comp1").physics("plas").feature("sr6").selection().all();
    model.component("comp1").physics("plas").feature("sr6").set("SpecifyReactionUsing", "UseBohm");
    model.component("comp1").physics("plas").feature("sr6").set("hl", 0.25);
    model.component("comp1").physics("plas").feature("sr7").selection().all();
    model.component("comp1").physics("plas").feature("sr7").set("SpecifyReactionUsing", "UseBohm");
    model.component("comp1").physics("plas").feature("sr7").set("hl", 0.25);
    model.component("comp1").physics("plas").feature("sr8").selection().all();
    model.component("comp1").physics("plas").feature("sr8").set("SpecifyReactionUsing", "UseBohm");
    model.component("comp1").physics("plas").feature("sr8").set("hl", 0.25);
    model.component("comp1").physics("plas").feature("sr9").selection().all();
    model.component("comp1").physics("plas").feature("sr9").set("SpecifyReactionUsing", "UseBohm");
    model.component("comp1").physics("plas").feature("sr9").set("hl", 0.25);
    model.component("comp1").physics("plas").feature("sr10").selection().all();
    model.component("comp1").physics("plas").feature("sr10").set("SpecifyReactionUsing", "UseBohm");
    model.component("comp1").physics("plas").feature("sr10").set("hl", 0.25);
    model.component("comp1").physics("plas").feature("sr11").selection().all();

    model.nodeGroup().create("grp2", "Physics", "plas");
    model.nodeGroup("grp2").placeAfter("rg5");
    model.nodeGroup("grp2").add("sr1");
    model.nodeGroup("grp2").add("sr2");
    model.nodeGroup("grp2").add("sr3");
    model.nodeGroup("grp2").add("sr4");
    model.nodeGroup("grp2").add("sr5");
    model.nodeGroup("grp2").add("sr6");
    model.nodeGroup("grp2").add("sr7");
    model.nodeGroup("grp2").add("sr8");
    model.nodeGroup("grp2").add("sr9");
    model.nodeGroup("grp2").add("sr10");
    model.nodeGroup("grp2").add("sr11");

    model.study("std1").setGenPlots(false);
    model.study("std1").createAutoSequences("all");

    model.sol("sol1").runAll();

    model.result().numerical().create("gev1", "EvalGlobal");
    model.result().numerical("gev1").setIndex("expr", "plas.n_wSF6", 0);
    model.result().numerical("gev1").setIndex("descr", "SF6", 0);
    model.result().numerical("gev1").setIndex("expr", "plas.n_wSF5", 1);
    model.result().numerical("gev1").setIndex("descr", "SF5", 1);
    model.result().numerical("gev1").setIndex("expr", "plas.n_wSF4", 2);
    model.result().numerical("gev1").setIndex("descr", "SF4", 2);
    model.result().numerical("gev1").setIndex("expr", "plas.n_wSF3", 3);
    model.result().numerical("gev1").setIndex("descr", "SF3", 3);
    model.result().numerical("gev1").setIndex("expr", "plas.n_wSF2", 4);
    model.result().numerical("gev1").setIndex("descr", "SF2", 4);
    model.result().numerical("gev1").setIndex("expr", "plas.n_wSF", 5);
    model.result().numerical("gev1").setIndex("descr", "SF", 5);
    model.result().numerical("gev1").setIndex("expr", "plas.n_wS", 6);
    model.result().numerical("gev1").setIndex("descr", "S", 6);
    model.result().numerical("gev1").setIndex("expr", "plas.n_wF", 7);
    model.result().numerical("gev1").setIndex("descr", "F", 7);
    model.result().numerical("gev1").setIndex("expr", "plas.n_wF2", 8);
    model.result().numerical("gev1").setIndex("descr", "F2", 8);
    model.result().numerical("gev1").setIndex("expr", "plas.n_wSF5_1p", 9);
    model.result().numerical("gev1").setIndex("descr", "SF5+", 9);
    model.result().numerical("gev1").setIndex("expr", "plas.n_wSF4_1p", 10);
    model.result().numerical("gev1").setIndex("descr", "SF4+", 10);
    model.result().numerical("gev1").setIndex("expr", "plas.n_wSF3_1p", 11);
    model.result().numerical("gev1").setIndex("descr", "SF3+", 11);
    model.result().numerical("gev1").setIndex("expr", "plas.n_wSF2_1p", 12);
    model.result().numerical("gev1").setIndex("descr", "SF2+", 12);
    model.result().numerical("gev1").setIndex("expr", "plas.n_wSF_1p", 13);
    model.result().numerical("gev1").setIndex("descr", "SF+", 13);
    model.result().numerical("gev1").setIndex("expr", "plas.n_wS_1p", 14);
    model.result().numerical("gev1").setIndex("descr", "S+", 14);
    model.result().numerical("gev1").setIndex("expr", "plas.n_wF_1p", 15);
    model.result().numerical("gev1").setIndex("descr", "F+", 15);
    model.result().numerical("gev1").setIndex("expr", "plas.n_wF2_1p", 16);
    model.result().numerical("gev1").setIndex("descr", "F2+", 16);
    model.result().numerical("gev1").setIndex("expr", "plas.n_wSF6_1m", 17);
    model.result().numerical("gev1").setIndex("descr", "SF6-", 17);
    model.result().numerical("gev1").setIndex("expr", "plas.n_wSF5_1m", 18);
    model.result().numerical("gev1").setIndex("descr", "SF5-", 18);
    model.result().numerical("gev1").setIndex("expr", "plas.n_wSF4_1m", 19);
    model.result().numerical("gev1").setIndex("descr", "SF4-", 19);
    model.result().numerical("gev1").setIndex("expr", "plas.n_wSF3_1m", 20);
    model.result().numerical("gev1").setIndex("descr", "SF3-", 20);
    model.result().numerical("gev1").setIndex("expr", "plas.n_wSF2_1m", 21);
    model.result().numerical("gev1").setIndex("descr", "SF2-", 21);
    model.result().numerical("gev1").setIndex("expr", "plas.n_wF_1m", 22);
    model.result().numerical("gev1").setIndex("descr", "F-", 22);
    model.result().numerical("gev1").setIndex("expr", "plas.n_wF2_1m", 23);
    model.result().numerical("gev1").setIndex("descr", "F2-", 23);
    model.result().numerical("gev1").setIndex("expr", "plas.ne", 24);
    model.result().numerical("gev1").setIndex("descr", "e", 24);
    model.result().table().create("tbl1", "Table");
    model.result().table("tbl1").comments("\u5168\u5c40\u8ba1\u7b97 1");
    model.result().numerical("gev1").set("table", "tbl1");
    model.result().numerical("gev1").setResult();

    model.study().create("std2");
    model.study("std2").create("stat", "Stationary");
    model.study("std2").feature("stat").setSolveFor("/physics/plas", true);
    model.study("std2").setGenPlots(false);
    model.study("std2").feature("stat").set("useinitsol", true);
    model.study("std2").feature("stat").set("initmethod", "sol");
    model.study("std2").feature("stat").set("initstudy", "std1");
    model.study("std2").feature("stat").set("useparam", true);
    model.study("std2").feature("stat").setIndex("pname", "Qfeed", 0);
    model.study("std2").feature("stat").setIndex("plistarr", "", 0);
    model.study("std2").feature("stat").setIndex("punit", "", 0);
    model.study("std2").feature("stat").setIndex("pname", "Qfeed", 0);
    model.study("std2").feature("stat").setIndex("plistarr", "", 0);
    model.study("std2").feature("stat").setIndex("punit", "", 0);
    model.study("std2").feature("stat").setIndex("pname", "Pinp", 0);
    model.study("std2").feature("stat").setIndex("plistarr", "range(2000,-100,300)", 0);
    model.study("std2").createAutoSequences("all");

    model.sol("sol2").runAll();

    model.result().create("pg1", "PlotGroup1D");
    model.result("pg1").run();
    model.result("pg1").set("data", "dset2");
    model.result("pg1").set("titletype", "none");
    model.result("pg1").set("xlabelactive", true);
    model.result("pg1").set("ylabelactive", true);
    model.result("pg1").set("ylog", true);
    model.result("pg1").set("legendpos", "middleright");
    model.result("pg1").create("glob1", "Global");
    model.result("pg1").feature("glob1").set("markerpos", "datapoints");
    model.result("pg1").feature("glob1").set("linewidth", "preference");
    model.result("pg1").feature("glob1").setIndex("expr", "plas.n_wSF6", 0);
    model.result("pg1").feature("glob1").setIndex("descr", "SF6", 0);
    model.result("pg1").feature("glob1").setIndex("expr", "plas.n_wSF5", 1);
    model.result("pg1").feature("glob1").setIndex("descr", "SF5", 1);
    model.result("pg1").feature("glob1").setIndex("expr", "plas.n_wSF4", 2);
    model.result("pg1").feature("glob1").setIndex("descr", "SF4", 2);
    model.result("pg1").feature("glob1").setIndex("expr", "plas.n_wSF3", 3);
    model.result("pg1").feature("glob1").setIndex("descr", "SF3", 3);
    model.result("pg1").feature("glob1").setIndex("expr", "plas.n_wSF2", 4);
    model.result("pg1").feature("glob1").setIndex("descr", "SF2", 4);
    model.result("pg1").feature("glob1").setIndex("expr", "plas.n_wSF", 5);
    model.result("pg1").feature("glob1").setIndex("descr", "SF", 5);
    model.result("pg1").feature("glob1").setIndex("expr", "plas.n_wS", 6);
    model.result("pg1").feature("glob1").setIndex("descr", "S", 6);
    model.result("pg1").feature("glob1").setIndex("expr", "plas.n_wF2", 7);
    model.result("pg1").feature("glob1").setIndex("descr", "F2", 7);
    model.result("pg1").feature("glob1").setIndex("expr", "plas.n_wF", 8);
    model.result("pg1").feature("glob1").setIndex("descr", "F", 8);
    model.result("pg1").feature("glob1").setIndex("expr", "plas.n_wAr", 9);
    model.result("pg1").feature("glob1").setIndex("descr", "Ar", 9);
    model.result("pg1").feature("glob1").setIndex("expr", "plas.n_wArs", 10);
    model.result("pg1").feature("glob1").setIndex("descr", "Ars", 10);
    model.result("pg1").feature("glob1").set("autosolution", false);
    model.result("pg1").run();
    model.result("pg1").run();
    model.result().duplicate("pg2", "pg1");
    model.result("pg2").run();
    model.result("pg2").set("legendpos", "lowerright");
    model.result("pg2").run();
    model.result("pg2").feature("glob1").set("expr", new String[]{});
    model.result("pg2").feature("glob1").set("descr", new String[]{});
    model.result("pg2").feature("glob1").setIndex("expr", "plas.n_wSF5_1p", 0);
    model.result("pg2").feature("glob1").setIndex("descr", "SF5+", 0);
    model.result("pg2").feature("glob1").setIndex("expr", "plas.n_wSF4_1p", 1);
    model.result("pg2").feature("glob1").setIndex("descr", "SF4+", 1);
    model.result("pg2").feature("glob1").setIndex("expr", "plas.n_wSF3_1p", 2);
    model.result("pg2").feature("glob1").setIndex("descr", "SF3+", 2);
    model.result("pg2").feature("glob1").setIndex("expr", "plas.n_wSF2_1p", 3);
    model.result("pg2").feature("glob1").setIndex("descr", "SF2+", 3);
    model.result("pg2").feature("glob1").setIndex("expr", "plas.n_wSF_1p", 4);
    model.result("pg2").feature("glob1").setIndex("descr", "SF+", 4);
    model.result("pg2").feature("glob1").setIndex("expr", "plas.n_wS_1p", 5);
    model.result("pg2").feature("glob1").setIndex("descr", "S+", 5);
    model.result("pg2").feature("glob1").setIndex("expr", "plas.n_wF2_1p", 6);
    model.result("pg2").feature("glob1").setIndex("descr", "F2+", 6);
    model.result("pg2").feature("glob1").setIndex("expr", "plas.n_wF_1p", 7);
    model.result("pg2").feature("glob1").setIndex("descr", "F+", 7);
    model.result("pg2").feature("glob1").setIndex("expr", "plas.n_wAr_1p", 8);
    model.result("pg2").feature("glob1").setIndex("descr", "Ar+", 8);
    model.result("pg2").run();
    model.result("pg2").run();
    model.result().duplicate("pg3", "pg2");
    model.result("pg3").run();
    model.result("pg3").set("legendpos", "middleright");
    model.result("pg3").run();
    model.result("pg3").feature("glob1").set("expr", new String[]{});
    model.result("pg3").feature("glob1").set("descr", new String[]{});
    model.result("pg3").feature("glob1").setIndex("expr", "plas.ne", 0);
    model.result("pg3").feature("glob1").setIndex("descr", "e", 0);
    model.result("pg3").feature("glob1").setIndex("expr", "plas.n_wF2_1m", 1);
    model.result("pg3").feature("glob1").setIndex("descr", "F2-", 1);
    model.result("pg3").feature("glob1").setIndex("expr", "plas.n_wF_1m", 2);
    model.result("pg3").feature("glob1").setIndex("descr", "F-", 2);
    model.result("pg3").feature("glob1").setIndex("expr", "plas.n_wSF2_1m", 3);
    model.result("pg3").feature("glob1").setIndex("descr", "SF2-", 3);
    model.result("pg3").feature("glob1").setIndex("expr", "plas.n_wSF3_1m", 4);
    model.result("pg3").feature("glob1").setIndex("descr", "SF3-", 4);
    model.result("pg3").feature("glob1").setIndex("expr", "plas.n_wSF4_1m", 5);
    model.result("pg3").feature("glob1").setIndex("descr", "SF4-", 5);
    model.result("pg3").feature("glob1").setIndex("expr", "plas.n_wSF5_1m", 6);
    model.result("pg3").feature("glob1").setIndex("descr", "SF5-", 6);
    model.result("pg3").feature("glob1").setIndex("expr", "plas.n_wSF6_1m", 7);
    model.result("pg3").feature("glob1").setIndex("descr", "SF6-", 7);
    model.result("pg3").run();
    model.result().create("pg4", "PlotGroup1D");
    model.result("pg4").run();
    model.result("pg4").set("data", "dset2");
    model.result("pg4").set("titletype", "none");
    model.result("pg4").set("xlabelactive", true);
    model.result("pg4").set("showlegends", false);
    model.result("pg4").create("glob1", "Global");
    model.result("pg4").feature("glob1").set("markerpos", "datapoints");
    model.result("pg4").feature("glob1").set("linewidth", "preference");
    model.result("pg4").feature("glob1").setIndex("expr", "plas.Te", 0);
    model.result("pg4").run();
    model.result("pg4").run();
    model.result().duplicate("pg5", "pg4");
    model.result("pg5").run();
    model.result("pg5").set("twoyaxes", true);
    model.result("pg5").set("ylabelactive", true);
    model.result("pg5").set("yseclabelactive", true);
    model.result("pg5").set("showlegends", true);
    model.result("pg5").set("legendpos", "middleright");
    model.result("pg5").create("glob2", "Global");
    model.result("pg5").feature("glob2").set("markerpos", "datapoints");
    model.result("pg5").feature("glob2").set("linewidth", "preference");
    model.result("pg5").feature("glob2").set("plotonsecyaxis", true);
    model.result("pg5").feature("glob2").setIndex("expr", "plas.nm/plas.ne", 0);
    model.result("pg5").feature("glob2").setIndex("descr", "Electronegativity", 0);
    model.result("pg5").run();
    model.result("pg5").feature("glob1").set("expr", new String[]{});
    model.result("pg5").feature("glob1").set("descr", new String[]{});
    model.result("pg5").feature("glob1").setIndex("expr", "plas.np", 0);
    model.result("pg5").feature("glob1").setIndex("expr", "plas.nm", 1);
    model.result("pg5").feature("glob1").setIndex("expr", "plas.ne", 2);
    model.result("pg5").run();
    model.result("pg5").set("ylog", true);
    model.result("pg4").run();
    model.result().duplicate("pg6", "pg4");
    model.result("pg6").run();
    model.result("pg6").run();
    model.result("pg6").feature("glob1").set("expr", new String[]{});
    model.result("pg6").feature("glob1").set("descr", new String[]{});
    model.result("pg6").feature("glob1").setIndex("expr", "plas.T", 0);
    model.result("pg6").run();
    model.result("pg1").run();

    model.nodeGroup().create("grp3", "Results");
    model.nodeGroup("grp3").set("type", "plotgroup");
    model.nodeGroup("grp3").add("plotgroup", "pg1");
    model.nodeGroup("grp3").add("plotgroup", "pg2");
    model.nodeGroup("grp3").add("plotgroup", "pg3");
    model.nodeGroup("grp3").add("plotgroup", "pg4");
    model.nodeGroup("grp3").add("plotgroup", "pg5");
    model.nodeGroup("grp3").add("plotgroup", "pg6");

    model.study().create("std3");
    model.study("std3").create("stat", "Stationary");
    model.study("std3").feature("stat").setSolveFor("/physics/plas", true);
    model.study("std3").setGenPlots(false);
    model.study("std3").feature("stat").set("useinitsol", true);
    model.study("std3").feature("stat").set("initmethod", "sol");

    return model;
  }

  public static Model run3(Model model) {
    model.study("std3").feature("stat").set("initstudy", "std2");
    model.study("std3").feature("stat").set("solnum", 1);
    model.study("std3").feature("stat").set("useparam", true);
    model.study("std3").feature("stat").setIndex("pname", "Qfeed", 0);
    model.study("std3").feature("stat").setIndex("plistarr", "", 0);
    model.study("std3").feature("stat").setIndex("punit", "", 0);
    model.study("std3").feature("stat").setIndex("pname", "Qfeed", 0);
    model.study("std3").feature("stat").setIndex("plistarr", "", 0);
    model.study("std3").feature("stat").setIndex("punit", "", 0);
    model.study("std3").feature("stat").setIndex("pname", "xAr", 0);
    model.study("std3").feature("stat").setIndex("plistarr", "range(0.1,0.1,0.9)", 0);
    model.study("std3").createAutoSequences("all");

    model.sol("sol3").runAll();

    model.nodeGroup().duplicate("grp4", "grp3");

    model.result("pg7").run();
    model.result("pg7").set("data", "dset3");
    model.result("pg7").run();
    model.result("pg7").set("legendpos", "lowerleft");
    model.result("pg8").run();
    model.result("pg8").set("data", "dset3");
    model.result("pg8").run();
    model.result("pg8").set("legendpos", "lowerleft");
    model.result("pg9").run();
    model.result("pg9").set("data", "dset3");
    model.result("pg9").run();
    model.result("pg10").run();
    model.result("pg10").set("data", "dset3");
    model.result("pg10").run();
    model.result("pg11").run();
    model.result("pg11").set("data", "dset3");
    model.result("pg11").run();
    model.result("pg11").set("legendpos", "middleleft");
    model.result("pg12").run();
    model.result("pg12").set("data", "dset3");
    model.result("pg12").run();
    model.result("pg3").run();
    model.result("pg4").run();
    model.result("pg6").run();
    model.result("pg8").run();
    model.result("pg11").run();

    model.title("SF6/\u6c29\u7b49\u79bb\u5b50\u4f53\u5168\u5c40\u6a21\u578b");

    model
         .description("\u672c\u4f8b\u4f7f\u7528\u5168\u5c40\u6a21\u578b\u7814\u7a76\u4e2d\u7b49\u538b\u529b\u4e0b\u7684 SF6/\u6c29\u7b49\u79bb\u5b50\u4f53\u53cd\u5e94\u5668\uff0c\u5176\u4e2d\u5305\u542b\u91cd\u7269\u8d28\u70ed\u65b9\u7a0b\uff0c\u8ba1\u7b97\u4e86\u8f93\u5165\u529f\u7387\u548c\u6c29\u6469\u5c14\u5206\u6570\u7684\u53c2\u6570\u5316\u626b\u63cf\u3002");

    model.mesh().clearMeshes();

    model.sol("sol1").clearSolutionData();
    model.sol("sol2").clearSolutionData();
    model.sol("sol3").clearSolutionData();

    model.label("sf6_argon_global_model.mph");

    return model;
  }

  public static void main(String[] args) {
    Model model = run();
    model = run2(model);
    run3(model);
  }

}
