/*
 * laminated_shell_material_characteristics.java
 */

import com.comsol.model.*;
import com.comsol.model.util.*;

/** Model exported on Apr 30 2026, 09:36 by COMSOL 6.3.0.290. */
public class laminated_shell_material_characteristics {

  public static Model run() {
    Model model = ModelUtil.create("Model");

    model
         .modelPath("D:\\Program Files\\COMSOL\\COMSOL63\\Multiphysics\\applications\\Composite_Materials_Module\\Verification_Examples");

    model.component().create("comp1", true);

    model.component("comp1").geom().create("geom1", 3);
    model.component("comp1").geom("geom1").geomRep("comsol");

    model.component("comp1").mesh().create("mesh1");
    model.component("comp1").mesh("mesh1").contribute("geom/detail", true);

    model.component("comp1").physics().create("shell", "Shell", "geom1");

    model.study().create("std1");
    model.study("std1").create("stat", "Stationary");
    model.study("std1").feature("stat").setSolveFor("/physics/shell", true);

//    To import content from file, use:
//    model.param().loadFile("FILENAME");
    model.param().set("th", "1e-4[m]", "\u5c42\u539a\u5ea6");
    model.param().set("E1", "213[GPa]", "\u8584\u5c42\u6768\u6c0f\u6a21\u91cf\uff0c11 \u65b9\u5411");
    model.param().set("E2", "8.2[GPa]", "\u8584\u5c42\u6768\u6c0f\u6a21\u91cf\uff0c22 \u65b9\u5411");
    model.param().set("nu12", "0.3", "\u8584\u5c42\u6cca\u677e\u6bd4\uff0c12 \u65b9\u5411");
    model.param().set("nu23", "0", "\u8584\u5c42\u6cca\u677e\u6bd4\uff0c23 \u65b9\u5411");
    model.param().set("G", "3.2[GPa]", "\u8584\u5c42\u526a\u5207\u6a21\u91cf");
    model.param().set("alpha1", "1.3e-6[1/K]", "\u8584\u5c42\u70ed\u81a8\u80c0\u7cfb\u6570\uff0c11 \u65b9\u5411");
    model.param().set("alpha2", "27e-6[1/K]", "\u8584\u5c42\u70ed\u81a8\u80c0\u7cfb\u6570\uff0c22 \u65b9\u5411");
    model.param().set("alpha3", "alpha2", "\u8584\u5c42\u70ed\u81a8\u80c0\u7cfb\u6570\uff0c33 \u65b9\u5411");
    model.param().set("Fi", "5e-3[N]", "\u9762\u5185\u8f7d\u8377");
    model.param().set("Fo", "2[N]", "\u9762\u5916\u8f7d\u8377");
    model.param().set("M", "5e-3[N*m]", "\u529b\u77e9\u8f7d\u8377");

    model.group().create("lg1", "LoadGroup");
    model.group("lg1").label("\u5355\u5143 N1 \u7684\u8f7d\u8377\u7ec4");
    model.group().create("lg2", "LoadGroup");
    model.group("lg2").label("\u5355\u5143 N2 \u7684\u8f7d\u8377\u7ec4");
    model.group().create("lg3", "LoadGroup");
    model.group("lg3").label("\u5355\u5143 N12 \u7684\u8f7d\u8377\u7ec4");
    model.group().create("lg4", "LoadGroup");
    model.group("lg4").label("\u5355\u5143 M1 \u7684\u8f7d\u8377\u7ec4");
    model.group().create("lg5", "LoadGroup");
    model.group("lg5").label("\u5355\u5143 M2 \u7684\u8f7d\u8377\u7ec4");
    model.group().create("lg6", "LoadGroup");
    model.group("lg6").label("\u5355\u5143 M12 \u7684\u8f7d\u8377\u7ec4");

    model.nodeGroup().create("grp1", "GlobalDefinitions");
    model.nodeGroup("grp1").set("type", "group");
    model.nodeGroup("grp1").add("group", "lg1");
    model.nodeGroup("grp1").add("group", "lg2");
    model.nodeGroup("grp1").add("group", "lg3");
    model.nodeGroup("grp1").add("group", "lg4");
    model.nodeGroup("grp1").add("group", "lg5");
    model.nodeGroup("grp1").add("group", "lg6");
    model.nodeGroup("grp1").label("\u5355\u4f4d\u8f7d\u8377\u7684\u8f7d\u8377\u7ec4");

    model.group().create("lg7", "LoadGroup");
    model.group("lg7").label("\u5355\u4f4d\u6e29\u5dee\u7684\u8f7d\u8377\u7ec4");
    model.group().create("lg8", "LoadGroup");
    model.group("lg8").label("\u5355\u4f4d\u6e29\u5ea6\u68af\u5ea6\u7684\u8f7d\u8377\u7ec4");

    model.nodeGroup().create("grp2", "GlobalDefinitions");
    model.nodeGroup("grp2").set("type", "group");
    model.nodeGroup().move("grp2", 1);
    model.nodeGroup("grp2").add("group", "lg7");
    model.nodeGroup("grp2").add("group", "lg8");
    model.nodeGroup("grp2").label("\u70ed\u8f7d\u8377\u7684\u8f7d\u8377\u7ec4");

    model.group().create("cg1", "ConstraintGroup");
    model.group("cg1").label("\u5355\u5143 N1\u3001N2\u3001N12\u3001M1 \u548c M2 \u7684\u7ea6\u675f\u7ec4");
    model.group().create("cg2", "ConstraintGroup");
    model.group("cg2").label("\u5355\u5143 N1 \u548c M1 \u7684\u7ea6\u675f\u7ec4");
    model.group().create("cg3", "ConstraintGroup");
    model.group("cg3").label("\u5355\u5143 N2 \u548c M2 \u7684\u7ea6\u675f\u7ec4");
    model.group().create("cg4", "ConstraintGroup");
    model.group("cg4").label("\u5355\u5143 N12 \u7684\u7ea6\u675f\u7ec4");
    model.group().create("cg5", "ConstraintGroup");
    model.group("cg5").label("\u5355\u5143 M12 \u7684\u7ea6\u675f\u7ec4");

    model.nodeGroup().create("grp3", "GlobalDefinitions");
    model.nodeGroup("grp3").set("type", "group");
    model.nodeGroup().move("grp3", 2);
    model.nodeGroup("grp3").add("group", "cg1");
    model.nodeGroup("grp3").add("group", "cg2");
    model.nodeGroup("grp3").add("group", "cg3");
    model.nodeGroup("grp3").add("group", "cg4");
    model.nodeGroup("grp3").add("group", "cg5");
    model.nodeGroup("grp3").label("\u5355\u5143\u8f7d\u8377\u7684\u7ea6\u675f\u7ec4");

    model.group().create("cg6", "ConstraintGroup");
    model.group("cg6").label("\u70ed\u8f7d\u8377\u7684\u7ea6\u675f\u7ec4");

    model.material().create("mat1", "Common", "");
    model.material().create("lmat1", "LayeredMaterial", "");
    model.material("lmat1").setIndex("rotation", 0, 0);
    model.material("lmat1").setIndex("thickness", "th", 0);
    model.material("lmat1").setIndex("meshPoints", 1, 0);
    model.material("lmat1").setIndex("layername", "\u5c42 2", 1);
    model.material("lmat1").setIndex("link", "mat1", 1);
    model.material("lmat1").setIndex("rotation", 0, 1);
    model.material("lmat1").setIndex("thickness", "th", 1);
    model.material("lmat1").setIndex("meshPoints", 1, 1);
    model.material("lmat1").setIndex("tag", "lmat1_2", 1);
    model.material("lmat1").setIndex("layername", "\u5c42 2", 1);
    model.material("lmat1").setIndex("link", "mat1", 1);
    model.material("lmat1").setIndex("rotation", 0, 1);
    model.material("lmat1").setIndex("thickness", "th", 1);
    model.material("lmat1").setIndex("meshPoints", 1, 1);
    model.material("lmat1").setIndex("tag", "lmat1_2", 1);
    model.material("lmat1").setIndex("layername", "\u5c42 3", 2);
    model.material("lmat1").setIndex("link", "mat1", 2);
    model.material("lmat1").setIndex("rotation", 0, 2);
    model.material("lmat1").setIndex("thickness", "th", 2);
    model.material("lmat1").setIndex("meshPoints", 1, 2);
    model.material("lmat1").setIndex("tag", "lmat1_3", 2);
    model.material("lmat1").setIndex("layername", "\u5c42 3", 2);
    model.material("lmat1").setIndex("link", "mat1", 2);
    model.material("lmat1").setIndex("rotation", 0, 2);
    model.material("lmat1").setIndex("thickness", "th", 2);
    model.material("lmat1").setIndex("meshPoints", 1, 2);
    model.material("lmat1").setIndex("tag", "lmat1_3", 2);
    model.material("lmat1").setIndex("layername", "\u5c42 4", 3);
    model.material("lmat1").setIndex("link", "mat1", 3);
    model.material("lmat1").setIndex("rotation", 0, 3);
    model.material("lmat1").setIndex("thickness", "th", 3);
    model.material("lmat1").setIndex("meshPoints", 1, 3);
    model.material("lmat1").setIndex("tag", "lmat1_4", 3);
    model.material("lmat1").setIndex("layername", "\u5c42 4", 3);
    model.material("lmat1").setIndex("link", "mat1", 3);
    model.material("lmat1").setIndex("rotation", 0, 3);
    model.material("lmat1").setIndex("thickness", "th", 3);
    model.material("lmat1").setIndex("meshPoints", 1, 3);
    model.material("lmat1").setIndex("tag", "lmat1_4", 3);
    model.material("lmat1").setIndex("rotation", 60, 1);
    model.material("lmat1").setIndex("rotation", -60, 2);
    model.material("lmat1").label("\u591a\u5c42\u6750\u6599\uff1a[0/60/-60/0]_s");

    model.component("comp1").geom("geom1").create("wp1", "WorkPlane");
    model.component("comp1").geom("geom1").feature("wp1").set("unite", true);
    model.component("comp1").geom("geom1").feature("wp1").geom().create("sq1", "Square");
    model.component("comp1").geom("geom1").feature("wp1").geom().feature("sq1").set("size", "1e-2");
    model.component("comp1").geom("geom1").feature("wp1").geom().run("sq1");
    model.component("comp1").geom("geom1").run();

    model.component("comp1").material().create("llmat1", "LayeredMaterialLink");
    model.component("comp1").material("llmat1").set("transform", "symmetry");
    model.component("comp1").material("llmat1").set("widthRatio", 0.5);

    model.component("comp1").coordSystem("sys1").set("mastercoordsystcomp", "1");

    model.component("comp1").physics("shell").prop("ShapeProperty").set("order_displacement", 1);
    model.component("comp1").physics("shell").create("llem1", "LayeredElastic", 2);
    model.component("comp1").physics("shell").feature("llem1").selection().set(1);
    model.component("comp1").physics("shell").feature("llem1").set("SolidModel", "Orthotropic");
    model.component("comp1").physics("shell").feature("llem1").set("TransverseIsotropic", true);
    model.component("comp1").physics("shell").feature("llem1").create("lte1", "LayeredThermalExpansion", 2);
    model.component("comp1").physics("shell").feature("llem1").feature("lte1")
         .label("\u5355\u4f4d\u6e29\u5dee\u7684\u70ed\u81a8\u80c0");
    model.component("comp1").physics("shell").feature("llem1").feature("lte1")
         .set("minput_temperature_src", "userdef");
    model.component("comp1").physics("shell").feature("llem1").feature("lte1")
         .set("minput_temperature", "293.15[K] +1[K]");
    model.component("comp1").physics("shell").feature("llem1").feature("lte1").set("loadGroup", "lg7");
    model.component("comp1").physics("shell").feature("llem1").create("lte2", "LayeredThermalExpansion", 2);
    model.component("comp1").physics("shell").feature("llem1").feature("lte2")
         .label("\u5355\u4f4d\u6e29\u5ea6\u68af\u5ea6\u7684\u70ed\u81a8\u80c0");
    model.component("comp1").physics("shell").feature("llem1").feature("lte2").set("ThermalBendingSel", "TempGrad");
    model.component("comp1").physics("shell").feature("llem1").feature("lte2").set("TGrad", "1[K/m]");
    model.component("comp1").physics("shell").feature("llem1").feature("lte2").set("loadGroup", "lg8");

    model.material("mat1").propertyGroup()
         .create("TransverseIsotropic", "TransverseIsotropic", "Transversely_isotropic");
    model.material("mat1").propertyGroup("TransverseIsotropic").set("Evect", new String[]{"E1", "E2"});
    model.material("mat1").propertyGroup("TransverseIsotropic").set("nuvect", new String[]{"nu12", "nu23"});
    model.material("mat1").propertyGroup("TransverseIsotropic").set("Gvect1", new String[]{"G"});
    model.material("mat1").propertyGroup("def").set("density", new String[]{"1"});
    model.material("mat1").propertyGroup("def")
         .set("thermalexpansioncoefficient", new String[]{"alpha1", "alpha2", "alpha3"});

    model.component("comp1").physics("shell").create("fix1", "Fixed", 0);
    model.component("comp1").physics("shell").feature("fix1")
         .label("\u5355\u5143 N1\u3001N2\u3001N12\u3001M1 \u548c M2 \u7684\u56fa\u5b9a\u7ea6\u675f");
    model.component("comp1").physics("shell").feature("fix1").selection().set(1);
    model.component("comp1").physics("shell").feature("fix1").set("constraintGroup", "cg1");
    model.component("comp1").physics("shell").create("disp1", "Displacement0", 0);
    model.component("comp1").physics("shell").feature("disp1")
         .label("\u5355\u5143 N1 \u548c M1 \u7684\u6307\u5b9a\u4f4d\u79fb/\u65cb\u8f6c");
    model.component("comp1").physics("shell").feature("disp1").selection().set(2);
    model.component("comp1").physics("shell").feature("disp1").setIndex("Direction", "prescribed", 0);
    model.component("comp1").physics("shell").feature("disp1").set("constraintGroup", "cg2");
    model.component("comp1").physics("shell").feature().duplicate("disp2", "disp1");
    model.component("comp1").physics("shell").feature("disp2")
         .label("\u5355\u5143 N2 \u548c M2 \u7684\u6307\u5b9a\u4f4d\u79fb/\u65cb\u8f6c");
    model.component("comp1").physics("shell").feature("disp2").selection().set(3);
    model.component("comp1").physics("shell").feature("disp2").setIndex("Direction", "prescribed", 1);
    model.component("comp1").physics("shell").feature("disp2").setIndex("Direction", "free", 0);
    model.component("comp1").physics("shell").feature("disp2").set("constraintGroup", "cg3");
    model.component("comp1").physics("shell").feature().duplicate("disp3", "disp2");
    model.component("comp1").physics("shell").feature("disp3")
         .label("\u5355\u5143 N12 \u7684\u6307\u5b9a\u4f4d\u79fb/\u65cb\u8f6c (1)");
    model.component("comp1").physics("shell").feature("disp3").selection().set(2);
    model.component("comp1").physics("shell").feature("disp3").setIndex("Direction", "prescribed", 0);
    model.component("comp1").physics("shell").feature("disp3").set("constraintGroup", "cg4");
    model.component("comp1").physics("shell").feature().duplicate("disp4", "disp3");
    model.component("comp1").physics("shell").feature("disp4")
         .label("\u5355\u5143 N12 \u7684\u6307\u5b9a\u4f4d\u79fb/\u65cb\u8f6c (2)");
    model.component("comp1").physics("shell").feature("disp4").selection().set(3);
    model.component("comp1").physics("shell").feature("disp4").setIndex("Direction", "free", 1);
    model.component("comp1").physics("shell").feature().duplicate("disp5", "disp4");
    model.component("comp1").physics("shell").feature("disp5")
         .label("\u5355\u5143 M12 \u7684\u6307\u5b9a\u4f4d\u79fb/\u65cb\u8f6c (1)");
    model.component("comp1").physics("shell").feature("disp5").selection().set(1);
    model.component("comp1").physics("shell").feature("disp5").setIndex("Direction", "prescribed", 1);
    model.component("comp1").physics("shell").feature("disp5").setIndex("Direction", "prescribed", 2);
    model.component("comp1").physics("shell").feature("disp5").set("RotationType", "RotationGroup");
    model.component("comp1").physics("shell").feature("disp5").setIndex("FreeRotationAround", true, 0);
    model.component("comp1").physics("shell").feature("disp5").set("constraintGroup", "cg5");
    model.component("comp1").physics("shell").feature().duplicate("disp6", "disp5");
    model.component("comp1").physics("shell").feature("disp6")
         .label("\u5355\u5143 M12 \u7684\u6307\u5b9a\u4f4d\u79fb/\u65cb\u8f6c (2)");
    model.component("comp1").physics("shell").feature("disp6").selection().set(4);
    model.component("comp1").physics("shell").feature("disp6").set("RotationType", "FreeGroup");
    model.component("comp1").physics("shell").feature("disp6").setIndex("Direction", "free", 0);
    model.component("comp1").physics("shell").feature("disp6").setIndex("Direction", "free", 2);
    model.component("comp1").physics("shell").feature().duplicate("disp7", "disp6");
    model.component("comp1").physics("shell").feature("disp7")
         .label("\u5355\u5143 M12 \u7684\u6307\u5b9a\u4f4d\u79fb/\u65cb\u8f6c (3)");
    model.component("comp1").physics("shell").feature("disp7").selection().set(2);
    model.component("comp1").physics("shell").feature("disp7").setIndex("Direction", "free", 1);
    model.component("comp1").physics("shell").feature("disp7").setIndex("Direction", "prescribed", 2);
    model.component("comp1").physics("shell").feature().duplicate("disp8", "disp7");
    model.component("comp1").physics("shell").feature("disp8")
         .label("\u5355\u4f4d\u6e29\u5ea6\u53d8\u5316\u7684\u6307\u5b9a\u4f4d\u79fb/\u65cb\u8f6c (1)");
    model.component("comp1").physics("shell").feature("disp8").selection().set(1);
    model.component("comp1").physics("shell").feature("disp8").setIndex("Direction", "prescribed", 0);
    model.component("comp1").physics("shell").feature("disp8").setIndex("Direction", "prescribed", 1);
    model.component("comp1").physics("shell").feature("disp8").set("constraintGroup", "cg6");
    model.component("comp1").physics("shell").feature().duplicate("disp9", "disp8");
    model.component("comp1").physics("shell").feature("disp9")
         .label("\u5355\u4f4d\u6e29\u5ea6\u53d8\u5316\u7684\u6307\u5b9a\u4f4d\u79fb/\u65cb\u8f6c (2)");
    model.component("comp1").physics("shell").feature("disp9").selection().set(3);
    model.component("comp1").physics("shell").feature("disp9").setIndex("Direction", "free", 0);
    model.component("comp1").physics("shell").feature("disp9").setIndex("Direction", "free", 1);
    model.component("comp1").physics("shell").feature().duplicate("disp10", "disp9");
    model.component("comp1").physics("shell").feature("disp10")
         .label("\u5355\u4f4d\u6e29\u5ea6\u53d8\u5316\u7684\u6307\u5b9a\u4f4d\u79fb/\u65cb\u8f6c (3)");
    model.component("comp1").physics("shell").feature("disp10").selection().set(2);
    model.component("comp1").physics("shell").feature("disp10").setIndex("Direction", "prescribed", 0);

    model.nodeGroup().create("grp4", "Physics", "shell");
    model.nodeGroup("grp4").placeAfter("llem1");
    model.nodeGroup("grp4").add("fix1");
    model.nodeGroup("grp4").add("disp1");
    model.nodeGroup("grp4").add("disp2");
    model.nodeGroup("grp4").add("disp3");
    model.nodeGroup("grp4").add("disp4");
    model.nodeGroup("grp4").add("disp5");
    model.nodeGroup("grp4").add("disp6");
    model.nodeGroup("grp4").add("disp7");
    model.nodeGroup("grp4").add("disp8");
    model.nodeGroup("grp4").add("disp9");
    model.nodeGroup("grp4").add("disp10");
    model.nodeGroup("grp4").label("\u7ea6\u675f");

    model.component("comp1").physics("shell").create("pl1", "PointLoad", 0);
    model.component("comp1").physics("shell").feature("pl1").label("\u5355\u5143 N1 \u7684\u70b9\u8f7d\u8377");
    model.component("comp1").physics("shell").feature("pl1").selection().set(3, 4);
    model.component("comp1").physics("shell").feature("pl1").set("forcePoint", new String[]{"Fi", "0", "0"});
    model.component("comp1").physics("shell").feature("pl1").set("loadGroup", "lg1");
    model.component("comp1").physics("shell").feature().duplicate("pl2", "pl1");
    model.component("comp1").physics("shell").feature("pl2").label("\u5355\u5143 N2 \u7684\u70b9\u8f7d\u8377");
    model.component("comp1").physics("shell").feature("pl2").selection().set(2, 4);
    model.component("comp1").physics("shell").feature("pl2").set("forcePoint", new String[]{"0", "Fi", "0"});
    model.component("comp1").physics("shell").feature("pl2").set("loadGroup", "lg2");
    model.component("comp1").physics("shell").feature().duplicate("pl3", "pl2");
    model.component("comp1").physics("shell").feature("pl3").label("\u5355\u5143 N12 \u7684\u70b9\u8f7d\u8377 (1)");
    model.component("comp1").physics("shell").feature("pl3").set("forcePoint", new String[]{"Fi", "0", "0"});
    model.component("comp1").physics("shell").feature("pl3").set("loadGroup", "lg3");
    model.component("comp1").physics("shell").feature().duplicate("pl4", "pl3");
    model.component("comp1").physics("shell").feature("pl4").label("\u5355\u5143 N12 \u7684\u70b9\u8f7d\u8377 (2)");
    model.component("comp1").physics("shell").feature("pl4").selection().set(3, 4);
    model.component("comp1").physics("shell").feature("pl4").set("forcePoint", new String[]{"0", "Fi", "0"});
    model.component("comp1").physics("shell").feature().duplicate("pl5", "pl4");
    model.component("comp1").physics("shell").feature("pl5").label("\u5355\u5143 M1 \u7684\u70b9\u8f7d\u8377 (1)");
    model.component("comp1").physics("shell").feature("pl5").selection().set(1, 2);
    model.component("comp1").physics("shell").feature("pl5").set("forcePoint", new int[]{0, 0, 0});
    model.component("comp1").physics("shell").feature("pl5").set("momentPoint", new String[]{"0", "-M", "0"});
    model.component("comp1").physics("shell").feature("pl5").set("loadGroup", "lg4");
    model.component("comp1").physics("shell").feature().duplicate("pl6", "pl5");
    model.component("comp1").physics("shell").feature("pl6").label("\u5355\u5143 M1 \u7684\u70b9\u8f7d\u8377 (2)");
    model.component("comp1").physics("shell").feature("pl6").selection().set(3, 4);
    model.component("comp1").physics("shell").feature("pl6").set("momentPoint", new String[]{"0", "M", "0"});
    model.component("comp1").physics("shell").feature().duplicate("pl7", "pl6");
    model.component("comp1").physics("shell").feature("pl7").label("\u5355\u5143 M2 \u7684\u70b9\u8f7d\u8377 (1)");
    model.component("comp1").physics("shell").feature("pl7").selection().set(1, 3);
    model.component("comp1").physics("shell").feature("pl7").set("momentPoint", new String[]{"M", "0", "0"});
    model.component("comp1").physics("shell").feature("pl7").set("loadGroup", "lg5");
    model.component("comp1").physics("shell").feature().duplicate("pl8", "pl7");
    model.component("comp1").physics("shell").feature("pl8").label("\u5355\u5143 M2 \u7684\u70b9\u8f7d\u8377 (2)");
    model.component("comp1").physics("shell").feature("pl8").selection().set(2, 4);
    model.component("comp1").physics("shell").feature("pl8").set("momentPoint", new String[]{"-M", "0", "0"});
    model.component("comp1").physics("shell").feature().duplicate("pl9", "pl8");
    model.component("comp1").physics("shell").feature("pl9").label("\u5355\u5143 M12 \u7684\u70b9\u8f7d\u8377 (1)");
    model.component("comp1").physics("shell").feature("pl9").selection().set(3);
    model.component("comp1").physics("shell").feature("pl9").set("forcePoint", new String[]{"0", "0", "Fo"});
    model.component("comp1").physics("shell").feature("pl9").set("momentPoint", new int[]{0, 0, 0});
    model.component("comp1").physics("shell").feature("pl9").set("loadGroup", "lg6");
    model.component("comp1").physics("shell").feature().duplicate("pl10", "pl9");
    model.component("comp1").physics("shell").feature("pl10").label("\u5355\u5143 M12 \u7684\u70b9\u8f7d\u8377 (2)");
    model.component("comp1").physics("shell").feature("pl10").selection().set(4);
    model.component("comp1").physics("shell").feature("pl10").set("forcePoint", new String[]{"0", "0", "-Fo"});

    model.nodeGroup().create("grp5", "Physics", "shell");
    model.nodeGroup("grp5").placeAfter("llem1");
    model.nodeGroup("grp5").add("pl1");
    model.nodeGroup("grp5").add("pl2");
    model.nodeGroup("grp5").add("pl3");
    model.nodeGroup("grp5").add("pl4");
    model.nodeGroup("grp5").add("pl5");
    model.nodeGroup("grp5").add("pl6");
    model.nodeGroup("grp5").add("pl7");
    model.nodeGroup("grp5").add("pl8");
    model.nodeGroup("grp5").add("pl9");
    model.nodeGroup("grp5").add("pl10");
    model.nodeGroup("grp5").label("\u8f7d\u8377");

    model.component("comp1").mesh("mesh1").create("map1", "Map");
    model.component("comp1").mesh("mesh1").feature("map1").selection().all();
    model.component("comp1").mesh("mesh1").feature("map1").create("dis1", "Distribution");
    model.component("comp1").mesh("mesh1").feature("map1").feature("dis1").selection().all();
    model.component("comp1").mesh("mesh1").feature("map1").feature("dis1").set("numelem", 1);
    model.component("comp1").mesh("mesh1").run();

    model.study("std1").setGenPlots(false);
    model.study("std1").feature("stat").set("useloadcase", true);
    model.study("std1").feature("stat").setIndex("loadcase", "\u8f7d\u8377\u5de5\u51b5 1", 0);
    model.study("std1").feature("stat").setIndex("loadgroup", false, 0, 0);
    model.study("std1").feature("stat").setIndex("loadgroupweight", "1.0", 0, 0);
    model.study("std1").feature("stat").setIndex("loadgroup", false, 0, 1);
    model.study("std1").feature("stat").setIndex("loadgroupweight", "1.0", 0, 1);
    model.study("std1").feature("stat").setIndex("loadgroup", false, 0, 2);
    model.study("std1").feature("stat").setIndex("loadgroupweight", "1.0", 0, 2);
    model.study("std1").feature("stat").setIndex("loadgroup", false, 0, 3);
    model.study("std1").feature("stat").setIndex("loadgroupweight", "1.0", 0, 3);
    model.study("std1").feature("stat").setIndex("loadgroup", false, 0, 4);
    model.study("std1").feature("stat").setIndex("loadgroupweight", "1.0", 0, 4);
    model.study("std1").feature("stat").setIndex("loadgroup", false, 0, 5);
    model.study("std1").feature("stat").setIndex("loadgroupweight", "1.0", 0, 5);
    model.study("std1").feature("stat").setIndex("loadgroup", false, 0, 6);
    model.study("std1").feature("stat").setIndex("loadgroupweight", "1.0", 0, 6);
    model.study("std1").feature("stat").setIndex("loadgroup", false, 0, 7);
    model.study("std1").feature("stat").setIndex("loadgroupweight", "1.0", 0, 7);
    model.study("std1").feature("stat").setIndex("constraintgroup", false, 0, 0);
    model.study("std1").feature("stat").setIndex("constraintgroup", false, 0, 1);
    model.study("std1").feature("stat").setIndex("constraintgroup", false, 0, 2);
    model.study("std1").feature("stat").setIndex("constraintgroup", false, 0, 3);
    model.study("std1").feature("stat").setIndex("constraintgroup", false, 0, 4);
    model.study("std1").feature("stat").setIndex("constraintgroup", false, 0, 5);
    model.study("std1").feature("stat").setIndex("loadcase", "\u8f7d\u8377\u5de5\u51b5 1", 0);
    model.study("std1").feature("stat").setIndex("loadgroup", false, 0, 0);
    model.study("std1").feature("stat").setIndex("loadgroupweight", "1.0", 0, 0);
    model.study("std1").feature("stat").setIndex("loadgroup", false, 0, 1);
    model.study("std1").feature("stat").setIndex("loadgroupweight", "1.0", 0, 1);
    model.study("std1").feature("stat").setIndex("loadgroup", false, 0, 2);
    model.study("std1").feature("stat").setIndex("loadgroupweight", "1.0", 0, 2);
    model.study("std1").feature("stat").setIndex("loadgroup", false, 0, 3);
    model.study("std1").feature("stat").setIndex("loadgroupweight", "1.0", 0, 3);
    model.study("std1").feature("stat").setIndex("loadgroup", false, 0, 4);
    model.study("std1").feature("stat").setIndex("loadgroupweight", "1.0", 0, 4);
    model.study("std1").feature("stat").setIndex("loadgroup", false, 0, 5);
    model.study("std1").feature("stat").setIndex("loadgroupweight", "1.0", 0, 5);
    model.study("std1").feature("stat").setIndex("loadgroup", false, 0, 6);
    model.study("std1").feature("stat").setIndex("loadgroupweight", "1.0", 0, 6);
    model.study("std1").feature("stat").setIndex("loadgroup", false, 0, 7);
    model.study("std1").feature("stat").setIndex("loadgroupweight", "1.0", 0, 7);
    model.study("std1").feature("stat").setIndex("constraintgroup", false, 0, 0);
    model.study("std1").feature("stat").setIndex("constraintgroup", false, 0, 1);
    model.study("std1").feature("stat").setIndex("constraintgroup", false, 0, 2);
    model.study("std1").feature("stat").setIndex("constraintgroup", false, 0, 3);
    model.study("std1").feature("stat").setIndex("constraintgroup", false, 0, 4);
    model.study("std1").feature("stat").setIndex("constraintgroup", false, 0, 5);
    model.study("std1").feature("stat").setIndex("loadcase", "\u5355\u5143 N1 \u7684\u8f7d\u8377\u5de5\u51b5", 0);
    model.study("std1").feature("stat").setIndex("loadgroup", true, 0, 0);
    model.study("std1").feature("stat").setIndex("constraintgroup", true, 0, 0);
    model.study("std1").feature("stat").setIndex("constraintgroup", true, 0, 1);
    model.study("std1").feature("stat").setIndex("loadcase", "\u8f7d\u8377\u5de5\u51b5 1", 1);
    model.study("std1").feature("stat").setIndex("loadgroup", false, 1, 0);
    model.study("std1").feature("stat").setIndex("loadgroupweight", "1.0", 1, 0);
    model.study("std1").feature("stat").setIndex("loadgroup", false, 1, 1);
    model.study("std1").feature("stat").setIndex("loadgroupweight", "1.0", 1, 1);
    model.study("std1").feature("stat").setIndex("loadgroup", false, 1, 2);
    model.study("std1").feature("stat").setIndex("loadgroupweight", "1.0", 1, 2);
    model.study("std1").feature("stat").setIndex("loadgroup", false, 1, 3);
    model.study("std1").feature("stat").setIndex("loadgroupweight", "1.0", 1, 3);
    model.study("std1").feature("stat").setIndex("loadgroup", false, 1, 4);
    model.study("std1").feature("stat").setIndex("loadgroupweight", "1.0", 1, 4);
    model.study("std1").feature("stat").setIndex("loadgroup", false, 1, 5);
    model.study("std1").feature("stat").setIndex("loadgroupweight", "1.0", 1, 5);
    model.study("std1").feature("stat").setIndex("loadgroup", false, 1, 6);
    model.study("std1").feature("stat").setIndex("loadgroupweight", "1.0", 1, 6);
    model.study("std1").feature("stat").setIndex("loadgroup", false, 1, 7);
    model.study("std1").feature("stat").setIndex("loadgroupweight", "1.0", 1, 7);
    model.study("std1").feature("stat").setIndex("constraintgroup", false, 1, 0);
    model.study("std1").feature("stat").setIndex("constraintgroup", false, 1, 1);
    model.study("std1").feature("stat").setIndex("constraintgroup", false, 1, 2);
    model.study("std1").feature("stat").setIndex("constraintgroup", false, 1, 3);
    model.study("std1").feature("stat").setIndex("constraintgroup", false, 1, 4);
    model.study("std1").feature("stat").setIndex("constraintgroup", false, 1, 5);
    model.study("std1").feature("stat").setIndex("loadcase", "\u8f7d\u8377\u5de5\u51b5 1", 1);
    model.study("std1").feature("stat").setIndex("loadgroup", false, 1, 0);
    model.study("std1").feature("stat").setIndex("loadgroupweight", "1.0", 1, 0);
    model.study("std1").feature("stat").setIndex("loadgroup", false, 1, 1);
    model.study("std1").feature("stat").setIndex("loadgroupweight", "1.0", 1, 1);
    model.study("std1").feature("stat").setIndex("loadgroup", false, 1, 2);
    model.study("std1").feature("stat").setIndex("loadgroupweight", "1.0", 1, 2);
    model.study("std1").feature("stat").setIndex("loadgroup", false, 1, 3);
    model.study("std1").feature("stat").setIndex("loadgroupweight", "1.0", 1, 3);
    model.study("std1").feature("stat").setIndex("loadgroup", false, 1, 4);
    model.study("std1").feature("stat").setIndex("loadgroupweight", "1.0", 1, 4);
    model.study("std1").feature("stat").setIndex("loadgroup", false, 1, 5);
    model.study("std1").feature("stat").setIndex("loadgroupweight", "1.0", 1, 5);
    model.study("std1").feature("stat").setIndex("loadgroup", false, 1, 6);
    model.study("std1").feature("stat").setIndex("loadgroupweight", "1.0", 1, 6);
    model.study("std1").feature("stat").setIndex("loadgroup", false, 1, 7);
    model.study("std1").feature("stat").setIndex("loadgroupweight", "1.0", 1, 7);
    model.study("std1").feature("stat").setIndex("constraintgroup", false, 1, 0);
    model.study("std1").feature("stat").setIndex("constraintgroup", false, 1, 1);
    model.study("std1").feature("stat").setIndex("constraintgroup", false, 1, 2);
    model.study("std1").feature("stat").setIndex("constraintgroup", false, 1, 3);
    model.study("std1").feature("stat").setIndex("constraintgroup", false, 1, 4);
    model.study("std1").feature("stat").setIndex("constraintgroup", false, 1, 5);
    model.study("std1").feature("stat").setIndex("loadcase", "\u5355\u5143 N2 \u7684\u8f7d\u8377\u5de5\u51b5", 1);
    model.study("std1").feature("stat").setIndex("loadgroup", true, 1, 1);
    model.study("std1").feature("stat").setIndex("constraintgroup", true, 1, 0);
    model.study("std1").feature("stat").setIndex("constraintgroup", true, 1, 2);
    model.study("std1").feature("stat").setIndex("loadcase", "\u8f7d\u8377\u5de5\u51b5 1", 2);
    model.study("std1").feature("stat").setIndex("loadgroup", false, 2, 0);
    model.study("std1").feature("stat").setIndex("loadgroupweight", "1.0", 2, 0);
    model.study("std1").feature("stat").setIndex("loadgroup", false, 2, 1);
    model.study("std1").feature("stat").setIndex("loadgroupweight", "1.0", 2, 1);
    model.study("std1").feature("stat").setIndex("loadgroup", false, 2, 2);
    model.study("std1").feature("stat").setIndex("loadgroupweight", "1.0", 2, 2);
    model.study("std1").feature("stat").setIndex("loadgroup", false, 2, 3);
    model.study("std1").feature("stat").setIndex("loadgroupweight", "1.0", 2, 3);

    return model;
  }

  public static Model run2(Model model) {
    model.study("std1").feature("stat").setIndex("loadgroup", false, 2, 4);
    model.study("std1").feature("stat").setIndex("loadgroupweight", "1.0", 2, 4);
    model.study("std1").feature("stat").setIndex("loadgroup", false, 2, 5);
    model.study("std1").feature("stat").setIndex("loadgroupweight", "1.0", 2, 5);
    model.study("std1").feature("stat").setIndex("loadgroup", false, 2, 6);
    model.study("std1").feature("stat").setIndex("loadgroupweight", "1.0", 2, 6);
    model.study("std1").feature("stat").setIndex("loadgroup", false, 2, 7);
    model.study("std1").feature("stat").setIndex("loadgroupweight", "1.0", 2, 7);
    model.study("std1").feature("stat").setIndex("constraintgroup", false, 2, 0);
    model.study("std1").feature("stat").setIndex("constraintgroup", false, 2, 1);
    model.study("std1").feature("stat").setIndex("constraintgroup", false, 2, 2);
    model.study("std1").feature("stat").setIndex("constraintgroup", false, 2, 3);
    model.study("std1").feature("stat").setIndex("constraintgroup", false, 2, 4);
    model.study("std1").feature("stat").setIndex("constraintgroup", false, 2, 5);
    model.study("std1").feature("stat").setIndex("loadcase", "\u8f7d\u8377\u5de5\u51b5 1", 2);
    model.study("std1").feature("stat").setIndex("loadgroup", false, 2, 0);
    model.study("std1").feature("stat").setIndex("loadgroupweight", "1.0", 2, 0);
    model.study("std1").feature("stat").setIndex("loadgroup", false, 2, 1);
    model.study("std1").feature("stat").setIndex("loadgroupweight", "1.0", 2, 1);
    model.study("std1").feature("stat").setIndex("loadgroup", false, 2, 2);
    model.study("std1").feature("stat").setIndex("loadgroupweight", "1.0", 2, 2);
    model.study("std1").feature("stat").setIndex("loadgroup", false, 2, 3);
    model.study("std1").feature("stat").setIndex("loadgroupweight", "1.0", 2, 3);
    model.study("std1").feature("stat").setIndex("loadgroup", false, 2, 4);
    model.study("std1").feature("stat").setIndex("loadgroupweight", "1.0", 2, 4);
    model.study("std1").feature("stat").setIndex("loadgroup", false, 2, 5);
    model.study("std1").feature("stat").setIndex("loadgroupweight", "1.0", 2, 5);
    model.study("std1").feature("stat").setIndex("loadgroup", false, 2, 6);
    model.study("std1").feature("stat").setIndex("loadgroupweight", "1.0", 2, 6);
    model.study("std1").feature("stat").setIndex("loadgroup", false, 2, 7);
    model.study("std1").feature("stat").setIndex("loadgroupweight", "1.0", 2, 7);
    model.study("std1").feature("stat").setIndex("constraintgroup", false, 2, 0);
    model.study("std1").feature("stat").setIndex("constraintgroup", false, 2, 1);
    model.study("std1").feature("stat").setIndex("constraintgroup", false, 2, 2);
    model.study("std1").feature("stat").setIndex("constraintgroup", false, 2, 3);
    model.study("std1").feature("stat").setIndex("constraintgroup", false, 2, 4);
    model.study("std1").feature("stat").setIndex("constraintgroup", false, 2, 5);
    model.study("std1").feature("stat").setIndex("loadcase", "\u5355\u5143 N12 \u7684\u8f7d\u8377\u5de5\u51b5", 2);
    model.study("std1").feature("stat").setIndex("loadgroup", true, 2, 2);
    model.study("std1").feature("stat").setIndex("constraintgroup", true, 2, 0);
    model.study("std1").feature("stat").setIndex("constraintgroup", true, 2, 3);
    model.study("std1").feature("stat").setIndex("loadcase", "\u8f7d\u8377\u5de5\u51b5 1", 3);
    model.study("std1").feature("stat").setIndex("loadgroup", false, 3, 0);
    model.study("std1").feature("stat").setIndex("loadgroupweight", "1.0", 3, 0);
    model.study("std1").feature("stat").setIndex("loadgroup", false, 3, 1);
    model.study("std1").feature("stat").setIndex("loadgroupweight", "1.0", 3, 1);
    model.study("std1").feature("stat").setIndex("loadgroup", false, 3, 2);
    model.study("std1").feature("stat").setIndex("loadgroupweight", "1.0", 3, 2);
    model.study("std1").feature("stat").setIndex("loadgroup", false, 3, 3);
    model.study("std1").feature("stat").setIndex("loadgroupweight", "1.0", 3, 3);
    model.study("std1").feature("stat").setIndex("loadgroup", false, 3, 4);
    model.study("std1").feature("stat").setIndex("loadgroupweight", "1.0", 3, 4);
    model.study("std1").feature("stat").setIndex("loadgroup", false, 3, 5);
    model.study("std1").feature("stat").setIndex("loadgroupweight", "1.0", 3, 5);
    model.study("std1").feature("stat").setIndex("loadgroup", false, 3, 6);
    model.study("std1").feature("stat").setIndex("loadgroupweight", "1.0", 3, 6);
    model.study("std1").feature("stat").setIndex("loadgroup", false, 3, 7);
    model.study("std1").feature("stat").setIndex("loadgroupweight", "1.0", 3, 7);
    model.study("std1").feature("stat").setIndex("constraintgroup", false, 3, 0);
    model.study("std1").feature("stat").setIndex("constraintgroup", false, 3, 1);
    model.study("std1").feature("stat").setIndex("constraintgroup", false, 3, 2);
    model.study("std1").feature("stat").setIndex("constraintgroup", false, 3, 3);
    model.study("std1").feature("stat").setIndex("constraintgroup", false, 3, 4);
    model.study("std1").feature("stat").setIndex("constraintgroup", false, 3, 5);
    model.study("std1").feature("stat").setIndex("loadcase", "\u8f7d\u8377\u5de5\u51b5 1", 3);
    model.study("std1").feature("stat").setIndex("loadgroup", false, 3, 0);
    model.study("std1").feature("stat").setIndex("loadgroupweight", "1.0", 3, 0);
    model.study("std1").feature("stat").setIndex("loadgroup", false, 3, 1);
    model.study("std1").feature("stat").setIndex("loadgroupweight", "1.0", 3, 1);
    model.study("std1").feature("stat").setIndex("loadgroup", false, 3, 2);
    model.study("std1").feature("stat").setIndex("loadgroupweight", "1.0", 3, 2);
    model.study("std1").feature("stat").setIndex("loadgroup", false, 3, 3);
    model.study("std1").feature("stat").setIndex("loadgroupweight", "1.0", 3, 3);
    model.study("std1").feature("stat").setIndex("loadgroup", false, 3, 4);
    model.study("std1").feature("stat").setIndex("loadgroupweight", "1.0", 3, 4);
    model.study("std1").feature("stat").setIndex("loadgroup", false, 3, 5);
    model.study("std1").feature("stat").setIndex("loadgroupweight", "1.0", 3, 5);
    model.study("std1").feature("stat").setIndex("loadgroup", false, 3, 6);
    model.study("std1").feature("stat").setIndex("loadgroupweight", "1.0", 3, 6);
    model.study("std1").feature("stat").setIndex("loadgroup", false, 3, 7);
    model.study("std1").feature("stat").setIndex("loadgroupweight", "1.0", 3, 7);
    model.study("std1").feature("stat").setIndex("constraintgroup", false, 3, 0);
    model.study("std1").feature("stat").setIndex("constraintgroup", false, 3, 1);
    model.study("std1").feature("stat").setIndex("constraintgroup", false, 3, 2);
    model.study("std1").feature("stat").setIndex("constraintgroup", false, 3, 3);
    model.study("std1").feature("stat").setIndex("constraintgroup", false, 3, 4);
    model.study("std1").feature("stat").setIndex("constraintgroup", false, 3, 5);
    model.study("std1").feature("stat").setIndex("loadcase", "\u5355\u5143 M1 \u7684\u8f7d\u8377\u5de5\u51b5", 3);
    model.study("std1").feature("stat").setIndex("loadgroup", true, 3, 3);
    model.study("std1").feature("stat").setIndex("constraintgroup", true, 3, 0);
    model.study("std1").feature("stat").setIndex("constraintgroup", true, 3, 1);
    model.study("std1").feature("stat").setIndex("loadcase", "\u8f7d\u8377\u5de5\u51b5 1", 4);
    model.study("std1").feature("stat").setIndex("loadgroup", false, 4, 0);
    model.study("std1").feature("stat").setIndex("loadgroupweight", "1.0", 4, 0);
    model.study("std1").feature("stat").setIndex("loadgroup", false, 4, 1);
    model.study("std1").feature("stat").setIndex("loadgroupweight", "1.0", 4, 1);
    model.study("std1").feature("stat").setIndex("loadgroup", false, 4, 2);
    model.study("std1").feature("stat").setIndex("loadgroupweight", "1.0", 4, 2);
    model.study("std1").feature("stat").setIndex("loadgroup", false, 4, 3);
    model.study("std1").feature("stat").setIndex("loadgroupweight", "1.0", 4, 3);
    model.study("std1").feature("stat").setIndex("loadgroup", false, 4, 4);
    model.study("std1").feature("stat").setIndex("loadgroupweight", "1.0", 4, 4);
    model.study("std1").feature("stat").setIndex("loadgroup", false, 4, 5);
    model.study("std1").feature("stat").setIndex("loadgroupweight", "1.0", 4, 5);
    model.study("std1").feature("stat").setIndex("loadgroup", false, 4, 6);
    model.study("std1").feature("stat").setIndex("loadgroupweight", "1.0", 4, 6);
    model.study("std1").feature("stat").setIndex("loadgroup", false, 4, 7);
    model.study("std1").feature("stat").setIndex("loadgroupweight", "1.0", 4, 7);
    model.study("std1").feature("stat").setIndex("constraintgroup", false, 4, 0);
    model.study("std1").feature("stat").setIndex("constraintgroup", false, 4, 1);
    model.study("std1").feature("stat").setIndex("constraintgroup", false, 4, 2);
    model.study("std1").feature("stat").setIndex("constraintgroup", false, 4, 3);
    model.study("std1").feature("stat").setIndex("constraintgroup", false, 4, 4);
    model.study("std1").feature("stat").setIndex("constraintgroup", false, 4, 5);
    model.study("std1").feature("stat").setIndex("loadcase", "\u8f7d\u8377\u5de5\u51b5 1", 4);
    model.study("std1").feature("stat").setIndex("loadgroup", false, 4, 0);
    model.study("std1").feature("stat").setIndex("loadgroupweight", "1.0", 4, 0);
    model.study("std1").feature("stat").setIndex("loadgroup", false, 4, 1);
    model.study("std1").feature("stat").setIndex("loadgroupweight", "1.0", 4, 1);
    model.study("std1").feature("stat").setIndex("loadgroup", false, 4, 2);
    model.study("std1").feature("stat").setIndex("loadgroupweight", "1.0", 4, 2);
    model.study("std1").feature("stat").setIndex("loadgroup", false, 4, 3);
    model.study("std1").feature("stat").setIndex("loadgroupweight", "1.0", 4, 3);
    model.study("std1").feature("stat").setIndex("loadgroup", false, 4, 4);
    model.study("std1").feature("stat").setIndex("loadgroupweight", "1.0", 4, 4);
    model.study("std1").feature("stat").setIndex("loadgroup", false, 4, 5);
    model.study("std1").feature("stat").setIndex("loadgroupweight", "1.0", 4, 5);
    model.study("std1").feature("stat").setIndex("loadgroup", false, 4, 6);
    model.study("std1").feature("stat").setIndex("loadgroupweight", "1.0", 4, 6);
    model.study("std1").feature("stat").setIndex("loadgroup", false, 4, 7);
    model.study("std1").feature("stat").setIndex("loadgroupweight", "1.0", 4, 7);
    model.study("std1").feature("stat").setIndex("constraintgroup", false, 4, 0);
    model.study("std1").feature("stat").setIndex("constraintgroup", false, 4, 1);
    model.study("std1").feature("stat").setIndex("constraintgroup", false, 4, 2);
    model.study("std1").feature("stat").setIndex("constraintgroup", false, 4, 3);
    model.study("std1").feature("stat").setIndex("constraintgroup", false, 4, 4);
    model.study("std1").feature("stat").setIndex("constraintgroup", false, 4, 5);
    model.study("std1").feature("stat").setIndex("loadcase", "\u5355\u5143 M2 \u7684\u8f7d\u8377\u5de5\u51b5", 4);
    model.study("std1").feature("stat").setIndex("loadgroup", true, 4, 4);
    model.study("std1").feature("stat").setIndex("constraintgroup", true, 4, 0);
    model.study("std1").feature("stat").setIndex("constraintgroup", true, 4, 2);
    model.study("std1").feature("stat").setIndex("loadcase", "\u8f7d\u8377\u5de5\u51b5 1", 5);
    model.study("std1").feature("stat").setIndex("loadgroup", false, 5, 0);
    model.study("std1").feature("stat").setIndex("loadgroupweight", "1.0", 5, 0);
    model.study("std1").feature("stat").setIndex("loadgroup", false, 5, 1);
    model.study("std1").feature("stat").setIndex("loadgroupweight", "1.0", 5, 1);
    model.study("std1").feature("stat").setIndex("loadgroup", false, 5, 2);
    model.study("std1").feature("stat").setIndex("loadgroupweight", "1.0", 5, 2);
    model.study("std1").feature("stat").setIndex("loadgroup", false, 5, 3);
    model.study("std1").feature("stat").setIndex("loadgroupweight", "1.0", 5, 3);
    model.study("std1").feature("stat").setIndex("loadgroup", false, 5, 4);
    model.study("std1").feature("stat").setIndex("loadgroupweight", "1.0", 5, 4);
    model.study("std1").feature("stat").setIndex("loadgroup", false, 5, 5);
    model.study("std1").feature("stat").setIndex("loadgroupweight", "1.0", 5, 5);
    model.study("std1").feature("stat").setIndex("loadgroup", false, 5, 6);
    model.study("std1").feature("stat").setIndex("loadgroupweight", "1.0", 5, 6);
    model.study("std1").feature("stat").setIndex("loadgroup", false, 5, 7);
    model.study("std1").feature("stat").setIndex("loadgroupweight", "1.0", 5, 7);
    model.study("std1").feature("stat").setIndex("constraintgroup", false, 5, 0);
    model.study("std1").feature("stat").setIndex("constraintgroup", false, 5, 1);
    model.study("std1").feature("stat").setIndex("constraintgroup", false, 5, 2);
    model.study("std1").feature("stat").setIndex("constraintgroup", false, 5, 3);
    model.study("std1").feature("stat").setIndex("constraintgroup", false, 5, 4);
    model.study("std1").feature("stat").setIndex("constraintgroup", false, 5, 5);
    model.study("std1").feature("stat").setIndex("loadcase", "\u8f7d\u8377\u5de5\u51b5 1", 5);
    model.study("std1").feature("stat").setIndex("loadgroup", false, 5, 0);
    model.study("std1").feature("stat").setIndex("loadgroupweight", "1.0", 5, 0);
    model.study("std1").feature("stat").setIndex("loadgroup", false, 5, 1);
    model.study("std1").feature("stat").setIndex("loadgroupweight", "1.0", 5, 1);
    model.study("std1").feature("stat").setIndex("loadgroup", false, 5, 2);
    model.study("std1").feature("stat").setIndex("loadgroupweight", "1.0", 5, 2);
    model.study("std1").feature("stat").setIndex("loadgroup", false, 5, 3);
    model.study("std1").feature("stat").setIndex("loadgroupweight", "1.0", 5, 3);
    model.study("std1").feature("stat").setIndex("loadgroup", false, 5, 4);
    model.study("std1").feature("stat").setIndex("loadgroupweight", "1.0", 5, 4);
    model.study("std1").feature("stat").setIndex("loadgroup", false, 5, 5);
    model.study("std1").feature("stat").setIndex("loadgroupweight", "1.0", 5, 5);
    model.study("std1").feature("stat").setIndex("loadgroup", false, 5, 6);
    model.study("std1").feature("stat").setIndex("loadgroupweight", "1.0", 5, 6);
    model.study("std1").feature("stat").setIndex("loadgroup", false, 5, 7);
    model.study("std1").feature("stat").setIndex("loadgroupweight", "1.0", 5, 7);
    model.study("std1").feature("stat").setIndex("constraintgroup", false, 5, 0);
    model.study("std1").feature("stat").setIndex("constraintgroup", false, 5, 1);
    model.study("std1").feature("stat").setIndex("constraintgroup", false, 5, 2);
    model.study("std1").feature("stat").setIndex("constraintgroup", false, 5, 3);
    model.study("std1").feature("stat").setIndex("constraintgroup", false, 5, 4);
    model.study("std1").feature("stat").setIndex("constraintgroup", false, 5, 5);
    model.study("std1").feature("stat").setIndex("loadcase", "\u5355\u5143 M12 \u7684\u8f7d\u8377\u5de5\u51b5", 5);
    model.study("std1").feature("stat").setIndex("loadgroup", true, 5, 5);
    model.study("std1").feature("stat").setIndex("constraintgroup", true, 5, 4);
    model.study("std1").feature("stat").setIndex("loadcase", "\u8f7d\u8377\u5de5\u51b5 1", 6);
    model.study("std1").feature("stat").setIndex("loadgroup", false, 6, 0);
    model.study("std1").feature("stat").setIndex("loadgroupweight", "1.0", 6, 0);
    model.study("std1").feature("stat").setIndex("loadgroup", false, 6, 1);
    model.study("std1").feature("stat").setIndex("loadgroupweight", "1.0", 6, 1);
    model.study("std1").feature("stat").setIndex("loadgroup", false, 6, 2);
    model.study("std1").feature("stat").setIndex("loadgroupweight", "1.0", 6, 2);
    model.study("std1").feature("stat").setIndex("loadgroup", false, 6, 3);
    model.study("std1").feature("stat").setIndex("loadgroupweight", "1.0", 6, 3);
    model.study("std1").feature("stat").setIndex("loadgroup", false, 6, 4);
    model.study("std1").feature("stat").setIndex("loadgroupweight", "1.0", 6, 4);
    model.study("std1").feature("stat").setIndex("loadgroup", false, 6, 5);
    model.study("std1").feature("stat").setIndex("loadgroupweight", "1.0", 6, 5);
    model.study("std1").feature("stat").setIndex("loadgroup", false, 6, 6);
    model.study("std1").feature("stat").setIndex("loadgroupweight", "1.0", 6, 6);
    model.study("std1").feature("stat").setIndex("loadgroup", false, 6, 7);
    model.study("std1").feature("stat").setIndex("loadgroupweight", "1.0", 6, 7);
    model.study("std1").feature("stat").setIndex("constraintgroup", false, 6, 0);
    model.study("std1").feature("stat").setIndex("constraintgroup", false, 6, 1);
    model.study("std1").feature("stat").setIndex("constraintgroup", false, 6, 2);
    model.study("std1").feature("stat").setIndex("constraintgroup", false, 6, 3);
    model.study("std1").feature("stat").setIndex("constraintgroup", false, 6, 4);
    model.study("std1").feature("stat").setIndex("constraintgroup", false, 6, 5);
    model.study("std1").feature("stat").setIndex("loadcase", "\u8f7d\u8377\u5de5\u51b5 1", 6);
    model.study("std1").feature("stat").setIndex("loadgroup", false, 6, 0);
    model.study("std1").feature("stat").setIndex("loadgroupweight", "1.0", 6, 0);
    model.study("std1").feature("stat").setIndex("loadgroup", false, 6, 1);
    model.study("std1").feature("stat").setIndex("loadgroupweight", "1.0", 6, 1);
    model.study("std1").feature("stat").setIndex("loadgroup", false, 6, 2);
    model.study("std1").feature("stat").setIndex("loadgroupweight", "1.0", 6, 2);
    model.study("std1").feature("stat").setIndex("loadgroup", false, 6, 3);
    model.study("std1").feature("stat").setIndex("loadgroupweight", "1.0", 6, 3);
    model.study("std1").feature("stat").setIndex("loadgroup", false, 6, 4);
    model.study("std1").feature("stat").setIndex("loadgroupweight", "1.0", 6, 4);
    model.study("std1").feature("stat").setIndex("loadgroup", false, 6, 5);
    model.study("std1").feature("stat").setIndex("loadgroupweight", "1.0", 6, 5);
    model.study("std1").feature("stat").setIndex("loadgroup", false, 6, 6);
    model.study("std1").feature("stat").setIndex("loadgroupweight", "1.0", 6, 6);
    model.study("std1").feature("stat").setIndex("loadgroup", false, 6, 7);
    model.study("std1").feature("stat").setIndex("loadgroupweight", "1.0", 6, 7);
    model.study("std1").feature("stat").setIndex("constraintgroup", false, 6, 0);
    model.study("std1").feature("stat").setIndex("constraintgroup", false, 6, 1);
    model.study("std1").feature("stat").setIndex("constraintgroup", false, 6, 2);
    model.study("std1").feature("stat").setIndex("constraintgroup", false, 6, 3);
    model.study("std1").feature("stat").setIndex("constraintgroup", false, 6, 4);
    model.study("std1").feature("stat").setIndex("constraintgroup", false, 6, 5);
    model.study("std1").feature("stat")
         .setIndex("loadcase", "\u5355\u4f4d\u6e29\u5ea6\u53d8\u5316\u7684\u8f7d\u8377\u5de5\u51b5", 6);
    model.study("std1").feature("stat").setIndex("loadgroup", true, 6, 6);
    model.study("std1").feature("stat").setIndex("constraintgroup", true, 6, 5);
    model.study("std1").feature("stat").setIndex("loadcase", "\u8f7d\u8377\u5de5\u51b5 1", 7);
    model.study("std1").feature("stat").setIndex("loadgroup", false, 7, 0);
    model.study("std1").feature("stat").setIndex("loadgroupweight", "1.0", 7, 0);
    model.study("std1").feature("stat").setIndex("loadgroup", false, 7, 1);
    model.study("std1").feature("stat").setIndex("loadgroupweight", "1.0", 7, 1);
    model.study("std1").feature("stat").setIndex("loadgroup", false, 7, 2);
    model.study("std1").feature("stat").setIndex("loadgroupweight", "1.0", 7, 2);
    model.study("std1").feature("stat").setIndex("loadgroup", false, 7, 3);
    model.study("std1").feature("stat").setIndex("loadgroupweight", "1.0", 7, 3);
    model.study("std1").feature("stat").setIndex("loadgroup", false, 7, 4);
    model.study("std1").feature("stat").setIndex("loadgroupweight", "1.0", 7, 4);
    model.study("std1").feature("stat").setIndex("loadgroup", false, 7, 5);
    model.study("std1").feature("stat").setIndex("loadgroupweight", "1.0", 7, 5);
    model.study("std1").feature("stat").setIndex("loadgroup", false, 7, 6);
    model.study("std1").feature("stat").setIndex("loadgroupweight", "1.0", 7, 6);
    model.study("std1").feature("stat").setIndex("loadgroup", false, 7, 7);
    model.study("std1").feature("stat").setIndex("loadgroupweight", "1.0", 7, 7);
    model.study("std1").feature("stat").setIndex("constraintgroup", false, 7, 0);
    model.study("std1").feature("stat").setIndex("constraintgroup", false, 7, 1);
    model.study("std1").feature("stat").setIndex("constraintgroup", false, 7, 2);
    model.study("std1").feature("stat").setIndex("constraintgroup", false, 7, 3);
    model.study("std1").feature("stat").setIndex("constraintgroup", false, 7, 4);
    model.study("std1").feature("stat").setIndex("constraintgroup", false, 7, 5);
    model.study("std1").feature("stat").setIndex("loadcase", "\u8f7d\u8377\u5de5\u51b5 1", 7);
    model.study("std1").feature("stat").setIndex("loadgroup", false, 7, 0);
    model.study("std1").feature("stat").setIndex("loadgroupweight", "1.0", 7, 0);
    model.study("std1").feature("stat").setIndex("loadgroup", false, 7, 1);
    model.study("std1").feature("stat").setIndex("loadgroupweight", "1.0", 7, 1);
    model.study("std1").feature("stat").setIndex("loadgroup", false, 7, 2);
    model.study("std1").feature("stat").setIndex("loadgroupweight", "1.0", 7, 2);
    model.study("std1").feature("stat").setIndex("loadgroup", false, 7, 3);
    model.study("std1").feature("stat").setIndex("loadgroupweight", "1.0", 7, 3);
    model.study("std1").feature("stat").setIndex("loadgroup", false, 7, 4);
    model.study("std1").feature("stat").setIndex("loadgroupweight", "1.0", 7, 4);
    model.study("std1").feature("stat").setIndex("loadgroup", false, 7, 5);
    model.study("std1").feature("stat").setIndex("loadgroupweight", "1.0", 7, 5);
    model.study("std1").feature("stat").setIndex("loadgroup", false, 7, 6);
    model.study("std1").feature("stat").setIndex("loadgroupweight", "1.0", 7, 6);
    model.study("std1").feature("stat").setIndex("loadgroup", false, 7, 7);
    model.study("std1").feature("stat").setIndex("loadgroupweight", "1.0", 7, 7);
    model.study("std1").feature("stat").setIndex("constraintgroup", false, 7, 0);
    model.study("std1").feature("stat").setIndex("constraintgroup", false, 7, 1);
    model.study("std1").feature("stat").setIndex("constraintgroup", false, 7, 2);
    model.study("std1").feature("stat").setIndex("constraintgroup", false, 7, 3);
    model.study("std1").feature("stat").setIndex("constraintgroup", false, 7, 4);
    model.study("std1").feature("stat").setIndex("constraintgroup", false, 7, 5);
    model.study("std1").feature("stat")
         .setIndex("loadcase", "\u5355\u4f4d\u6e29\u5ea6\u68af\u5ea6\u7684\u8f7d\u8377\u5de5\u51b5", 7);
    model.study("std1").feature("stat").setIndex("loadgroup", true, 7, 7);
    model.study("std1").feature("stat").setIndex("constraintgroup", true, 7, 5);
    model.study("std1").createAutoSequences("all");

    model.sol("sol1").runAll();

    model.result().evaluationGroup().create("eg1", "EvaluationGroup");
    model.result().evaluationGroup("eg1").setIndex("looplevelinput", "first", 0);
    model.result().evaluationGroup("eg1").set("includeparameters", false);
    model.result().evaluationGroup("eg1").label("\u62c9\u4f38\u67d4\u5ea6\u77e9\u9635");
    model.result().evaluationGroup("eg1").create("gpev1", "EvalPointMatrix");
    model.result().evaluationGroup("eg1").feature("gpev1").selection().set(3);
    model.result().evaluationGroup("eg1").feature("gpev1").set("expr", "shell.Da");
    model.result().evaluationGroup("eg1").feature("gpev1").set("descr", "\u62c9\u4f38\u67d4\u5ea6\u77e9\u9635");
    model.result().evaluationGroup("eg1").run();
    model.result().evaluationGroup().duplicate("eg2", "eg1");
    model.result().evaluationGroup("eg2").label("\u5f2f\u66f2\u62c9\u4f38\u67d4\u5ea6\u77e9\u9635");
    model.result().evaluationGroup("eg2").feature("gpev1").set("expr", "shell.Db");
    model.result().evaluationGroup("eg2").feature("gpev1")
         .set("descr", "\u5f2f\u66f2\u62c9\u4f38\u67d4\u5ea6\u77e9\u9635");
    model.result().evaluationGroup("eg2").run();
    model.result().evaluationGroup().duplicate("eg3", "eg2");
    model.result().evaluationGroup("eg3").label("\u5f2f\u66f2\u67d4\u5ea6\u77e9\u9635");
    model.result().evaluationGroup("eg3").feature("gpev1").set("expr", "shell.Dd");
    model.result().evaluationGroup("eg3").feature("gpev1").set("descr", "\u5f2f\u66f2\u67d4\u5ea6\u77e9\u9635");
    model.result().evaluationGroup("eg3").run();
    model.result().evaluationGroup().duplicate("eg4", "eg3");
    model.result().evaluationGroup("eg4").label("\u526a\u5207\u67d4\u5ea6\u77e9\u9635");
    model.result().evaluationGroup("eg4").feature("gpev1").set("expr", "shell.Das");
    model.result().evaluationGroup("eg4").feature("gpev1").set("descr", "\u526a\u5207\u67d4\u5ea6\u77e9\u9635");
    model.result().evaluationGroup("eg4").run();
    model.result().evaluationGroup().duplicate("eg5", "eg4");
    model.result().evaluationGroup("eg5").label("\u62c9\u4f38\u521a\u5ea6\u77e9\u9635");
    model.result().evaluationGroup("eg5").feature("gpev1").set("expr", "shell.DA");
    model.result().evaluationGroup("eg5").feature("gpev1").set("descr", "\u62c9\u4f38\u521a\u5ea6\u77e9\u9635");
    model.result().evaluationGroup("eg5").run();
    model.result().evaluationGroup().duplicate("eg6", "eg5");
    model.result().evaluationGroup("eg6").label("\u5f2f\u66f2\u62c9\u4f38\u521a\u5ea6\u77e9\u9635");
    model.result().evaluationGroup("eg6").feature("gpev1").set("expr", "shell.DB");
    model.result().evaluationGroup("eg6").feature("gpev1")
         .set("descr", "\u5f2f\u66f2\u62c9\u4f38\u521a\u5ea6\u77e9\u9635");
    model.result().evaluationGroup("eg6").run();
    model.result().evaluationGroup().duplicate("eg7", "eg6");
    model.result().evaluationGroup("eg7").label("\u5f2f\u66f2\u521a\u5ea6\u77e9\u9635");
    model.result().evaluationGroup("eg7").feature("gpev1").set("expr", "shell.DD");
    model.result().evaluationGroup("eg7").feature("gpev1").set("descr", "\u5f2f\u66f2\u521a\u5ea6\u77e9\u9635");
    model.result().evaluationGroup("eg7").run();
    model.result().evaluationGroup().duplicate("eg8", "eg7");
    model.result().evaluationGroup("eg8").label("\u526a\u5207\u521a\u5ea6\u77e9\u9635");
    model.result().evaluationGroup("eg8").feature("gpev1").set("expr", "shell.DAs");
    model.result().evaluationGroup("eg8").feature("gpev1").set("descr", "\u526a\u5207\u521a\u5ea6\u77e9\u9635");
    model.result().evaluationGroup("eg8").run();

    model.nodeGroup().create("grp6", "Results");
    model.nodeGroup("grp6").set("type", "evaluationgroup");
    model.nodeGroup("grp6").add("evaluationgroup", "eg1");
    model.nodeGroup("grp6").add("evaluationgroup", "eg2");
    model.nodeGroup("grp6").add("evaluationgroup", "eg3");
    model.nodeGroup("grp6").add("evaluationgroup", "eg4");
    model.nodeGroup("grp6").add("evaluationgroup", "eg5");
    model.nodeGroup("grp6").add("evaluationgroup", "eg6");
    model.nodeGroup("grp6").add("evaluationgroup", "eg7");
    model.nodeGroup("grp6").add("evaluationgroup", "eg8");
    model.nodeGroup("grp6").label("\u67d4\u5ea6\u548c\u521a\u5ea6\u77e9\u9635");

    model.result().dataset().create("lshl1", "LayeredMaterial");
    model.result().dataset().create("cpt1", "CutPoint3D");
    model.result().dataset("cpt1").set("data", "lshl1");
    model.result().dataset("cpt1").set("pointx", "1e-2");
    model.result().dataset("cpt1").set("pointy", 0);
    model.result().dataset("cpt1").set("pointz", 0);
    model.result().evaluationGroup().create("eg9", "EvaluationGroup");
    model.result().evaluationGroup("eg9").label("\u5355\u5143 N1 \u7684\u4e2d\u9762\u5e94\u53d8");
    model.result().evaluationGroup("eg9").set("data", "cpt1");
    model.result().evaluationGroup("eg9").setIndex("looplevelinput", "manual", 0);
    model.result().evaluationGroup("eg9").setIndex("looplevel", new int[]{1}, 0);
    model.result().evaluationGroup("eg9").set("transpose", true);
    model.result().evaluationGroup("eg9").set("includeparameters", false);
    model.result().evaluationGroup("eg9").create("pev1", "EvalPoint");
    model.result().evaluationGroup("eg9").feature("pev1").setIndex("expr", "shell.eml11", 0);
    model.result().evaluationGroup("eg9").feature("pev1")
         .setIndex("descr", "\u5e94\u53d8\u5f20\u91cf\u819c\u90e8\u5206\uff08\u5c40\u90e8\uff09\uff0c11 \u5206\u91cf", 0);
    model.result().evaluationGroup("eg9").feature("pev1").setIndex("expr", "shell.eml22", 1);
    model.result().evaluationGroup("eg9").feature("pev1")
         .setIndex("descr", "\u5e94\u53d8\u5f20\u91cf\u819c\u90e8\u5206\uff08\u5c40\u90e8\uff09\uff0c22 \u5206\u91cf", 1);
    model.result().evaluationGroup("eg9").feature("pev1").setIndex("expr", "2*shell.eml12", 2);
    model.result().evaluationGroup("eg9").feature("pev1")
         .setIndex("descr", "\u5e94\u53d8\u5f20\u91cf\u819c\u90e8\u5206\uff08\u5c40\u90e8\uff09\uff0c12 \u5206\u91cf", 2);
    model.result().evaluationGroup("eg9").feature("pev1").setIndex("expr", "shell.ebl11", 3);
    model.result().evaluationGroup("eg9").feature("pev1")
         .setIndex("descr", "\u5e94\u53d8\u5f20\u91cf\u5f2f\u66f2\u90e8\u5206\uff08\u5c40\u90e8\uff09\uff0c11 \u5206\u91cf", 3);
    model.result().evaluationGroup("eg9").feature("pev1").setIndex("expr", "shell.ebl22", 4);
    model.result().evaluationGroup("eg9").feature("pev1")
         .setIndex("descr", "\u5e94\u53d8\u5f20\u91cf\u5f2f\u66f2\u90e8\u5206\uff08\u5c40\u90e8\uff09\uff0c22 \u5206\u91cf", 4);
    model.result().evaluationGroup("eg9").feature("pev1").setIndex("expr", "2*shell.ebl12", 5);
    model.result().evaluationGroup("eg9").feature("pev1")
         .setIndex("descr", "\u5e94\u53d8\u5f20\u91cf\u5f2f\u66f2\u90e8\u5206\uff08\u5c40\u90e8\uff09\uff0c12 \u5206\u91cf", 5);
    model.result().evaluationGroup("eg9").feature("pev1").setIndex("expr", "shell.Nl11", 6);
    model.result().evaluationGroup("eg9").run();
    model.result().evaluationGroup().duplicate("eg10", "eg9");
    model.result().evaluationGroup("eg10").label("\u5355\u5143 N2 \u7684\u4e2d\u9762\u5e94\u53d8");
    model.result().evaluationGroup("eg10").setIndex("looplevel", new int[]{2}, 0);
    model.result().evaluationGroup("eg10").feature("pev1").setIndex("expr", "shell.Nl22", 6);
    model.result().evaluationGroup("eg10").run();
    model.result().evaluationGroup().duplicate("eg11", "eg10");
    model.result().evaluationGroup("eg11").label("\u5355\u5143 N12 \u7684\u4e2d\u9762\u5e94\u53d8");
    model.result().evaluationGroup("eg11").setIndex("looplevel", new int[]{3}, 0);
    model.result().evaluationGroup("eg11").feature("pev1").setIndex("expr", "shell.Nl12", 6);
    model.result().evaluationGroup("eg11").run();
    model.result().evaluationGroup().duplicate("eg12", "eg11");
    model.result().evaluationGroup("eg12").label("\u5355\u5143 M1 \u7684\u4e2d\u9762\u5e94\u53d8");
    model.result().evaluationGroup("eg12").setIndex("looplevel", new int[]{4}, 0);
    model.result().evaluationGroup("eg12").feature("pev1").setIndex("expr", "shell.Ml11", 6);
    model.result().evaluationGroup("eg12").run();
    model.result().evaluationGroup().duplicate("eg13", "eg12");

    return model;
  }

  public static Model run3(Model model) {
    model.result().evaluationGroup("eg13").label("\u5355\u5143 M2 \u7684\u4e2d\u9762\u5e94\u53d8");
    model.result().evaluationGroup("eg13").setIndex("looplevel", new int[]{5}, 0);
    model.result().evaluationGroup("eg13").feature("pev1").setIndex("expr", "shell.Ml22", 6);
    model.result().evaluationGroup("eg13").run();
    model.result().evaluationGroup().duplicate("eg14", "eg13");
    model.result().evaluationGroup("eg14").label("\u5355\u5143 M12 \u7684\u4e2d\u9762\u5e94\u53d8");
    model.result().evaluationGroup("eg14").setIndex("looplevel", new int[]{6}, 0);
    model.result().evaluationGroup("eg14").feature("pev1").setIndex("expr", "shell.Ml12", 6);
    model.result().evaluationGroup("eg14").run();
    model.result().evaluationGroup().duplicate("eg15", "eg14");
    model.result().evaluationGroup("eg15").label("\u5355\u4f4d\u6e29\u5dee\u7684\u4e2d\u9762\u5e94\u53d8");
    model.result().evaluationGroup("eg15").setIndex("looplevel", new int[]{7}, 0);
    model.result().evaluationGroup("eg15").feature("pev1").setIndex("expr", "", 6);
    model.result().evaluationGroup("eg15").run();
    model.result().evaluationGroup().duplicate("eg16", "eg15");
    model.result().evaluationGroup("eg16")
         .label("\u5355\u4f4d\u6e29\u5ea6\u68af\u5ea6\u7684\u4e2d\u9762\u5e94\u53d8");
    model.result().evaluationGroup("eg16").setIndex("looplevel", new int[]{8}, 0);
    model.result().evaluationGroup("eg16").run();

    model.nodeGroup().create("grp7", "Results");
    model.nodeGroup("grp7").set("type", "evaluationgroup");
    model.nodeGroup().move("grp7", 6);
    model.nodeGroup("grp7").add("evaluationgroup", "eg9");
    model.nodeGroup("grp7").add("evaluationgroup", "eg10");
    model.nodeGroup("grp7").add("evaluationgroup", "eg11");
    model.nodeGroup("grp7").add("evaluationgroup", "eg12");
    model.nodeGroup("grp7").add("evaluationgroup", "eg13");
    model.nodeGroup("grp7").add("evaluationgroup", "eg14");
    model.nodeGroup("grp7").add("evaluationgroup", "eg15");
    model.nodeGroup("grp7").add("evaluationgroup", "eg16");
    model.nodeGroup("grp7").label("\u4e2d\u9762\u5e94\u53d8");

    model.title("\u5c42\u538b\u590d\u5408\u58f3\u7684\u6750\u6599\u7279\u6027");

    model
         .description("\u8fd9\u662f\u4e00\u4e2a\u57fa\u51c6\u6a21\u578b\uff0c\u5176\u4e2d\u7684\u5c42\u538b\u590d\u5408\u58f3\u7531\u516b\u4e2a\u5177\u6709\u4e0d\u540c\u65b9\u5411\u7684\u6b63\u4ea4\u5404\u5411\u5f02\u6027\u5c42\u7ec4\u6210\uff0c\u5e76\u53d7\u5230\u5355\u4f4d\u8f7d\u8377\u4e0e\u5355\u4f4d\u6e29\u5ea6\u53d8\u5316\u7684\u4f5c\u7528\u3002\u5176\u4e2d\u5c06\u67d4\u5ea6\u3001\u521a\u5ea6\u77e9\u9635\u548c\u4e2d\u9762\u5e94\u53d8\u4e0e\u57fa\u51c6\u6a21\u578b\u4e2d\u7ed9\u51fa\u7684\u7406\u8bba\u548c\u6570\u503c\u7ed3\u679c\u8fdb\u884c\u6bd4\u8f83\u3002");

    model.label("laminated_shell_material_characteristics.mph");

    return model;
  }

  public static void main(String[] args) {
    Model model = run();
    model = run2(model);
    run3(model);
  }

}
