/*
 * gyroscope_mixed_formulation.java
 */

import com.comsol.model.*;
import com.comsol.model.util.*;

/** Model exported on Apr 30 2026, 11:03 by COMSOL 6.3.0.290. */
public class gyroscope_mixed_formulation {

  public static Model run() {
    Model model = ModelUtil.create("Model");

    model.modelPath("D:\\Program Files\\COMSOL\\COMSOL63\\Multiphysics\\applications\\MEMS_Module\\Sensors");

    model.component().create("comp1", true);

    model.component("comp1").geom().create("geom1", 3);
    model.component("comp1").geom("geom1").geomRep("comsol");

    model.component("comp1").mesh().create("mesh1");
    model.component("comp1").mesh("mesh1").contribute("geom/detail", true);

    model.component("comp1").physics().create("es", "Electrostatics", "geom1");
    model.component("comp1").physics("es").prop("ShapeProperty").set("order_electricpotential", "2m");
    model.component("comp1").physics("es").create("ccns1", "ChargeConservationSolid");
    model.component("comp1").physics("es").feature("ccns1").selection().all();
    model.component("comp1").physics().create("solid", "SolidMechanics", "geom1");

    model.component("comp1").multiphysics().create("eme1", "ElectromechanicalForces", 3);
    model.component("comp1").multiphysics("eme1").set("Solid_physics", "solid");
    model.component("comp1").multiphysics("eme1").set("Electrostatics_physics", "es");

    model.component("comp1").common().create("free1", "DeformingDomain");
    model.component("comp1").common("free1").set("smoothingType", "hyperelastic");
    model.component("comp1").common("free1").selection().set();
    model.component("comp1").common().create("sym1", "Symmetry");
    model.component("comp1").common("sym1").selection().set();

    model.study().create("std1");
    model.study("std1").create("stat", "Stationary");
    model.study("std1").feature("stat").setSolveFor("/physics/es", true);
    model.study("std1").feature("stat").setSolveFor("/physics/solid", true);
    model.study("std1").feature("stat").setSolveFor("/multiphysics/eme1", true);

    model.component("comp1").geom("geom1").lengthUnit("\u00b5m");

    model.param().set("Vcomb", "20[V]");
    model.param().set("V_ac", "1.5[V]");
    model.param().set("Vbase", "5[V]");
    model.param().set("Q", "500");
    model.param().set("t_anchor", "2[um]");
    model.param().set("mf", "10");
    model.param().set("Omega", "0[deg/s]");

    model.component("comp1").geom("geom1").create("imp1", "Import");
    model.component("comp1").geom("geom1").feature("imp1")
         .set("filename", "gyroscope_mixed_formulation_geometry.mphbin");
    model.component("comp1").geom("geom1").feature("imp1").importData();

    model.component("comp1").view("view1").set("renderwireframe", true);

    model.component("comp1").selection().create("box1", "Box");

    model.component("comp1").geom("geom1").run();

    model.component("comp1").selection("box1").set("entitydim", 2);
    model.component("comp1").selection("box1").set("zmax", "-t_anchor");
    model.component("comp1").selection("box1").set("condition", "inside");
    model.component("comp1").selection().create("sel1", "Explicit");
    model.component("comp1").selection("sel1").geom(2);
    model.component("comp1").selection("sel1").set(146, 813);
    model.component("comp1").selection().create("sel2", "Explicit");
    model.component("comp1").selection("sel2").geom(2);
    model.component("comp1").selection("sel2").set(1, 2, 4, 5, 216, 217, 218, 219, 1036, 1037, 1038);
    model.component("comp1").selection().create("sel3", "Explicit");
    model.component("comp1").selection("sel3").set(22, 23, 88, 89);
    model.component("comp1").selection().create("sel4", "Explicit");
    model.component("comp1").selection("sel4")
         .set(14, 15, 16, 17, 18, 19, 20, 21, 30, 31, 32, 33, 34, 35, 36, 37, 72, 73, 74, 75, 76, 77, 78, 79, 94, 95, 96, 97, 98, 99, 100, 101);
    model.component("comp1").selection().create("sel5", "Explicit");
    model.component("comp1").selection("sel5")
         .set(2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113);
    model.component("comp1").selection().create("sel6", "Explicit");
    model.component("comp1").selection("sel6")
         .set(38, 39, 40, 41, 42, 43, 44, 45, 46, 55, 56, 57, 59, 60, 61, 63, 64, 65, 66, 67, 68, 69, 70, 71);
    model.component("comp1").selection().create("sel7", "Explicit");
    model.component("comp1").selection("sel7")
         .set(24, 25, 26, 27, 28, 29, 47, 48, 49, 50, 51, 52, 53, 54, 58, 62, 80, 81, 82, 83, 84, 85, 86, 87, 90, 91, 92, 93);
    model.component("comp1").selection().create("sel8", "Explicit");
    model.component("comp1").selection("sel8").all();
    model.component("comp1").selection().create("uni1", "Union");
    model.component("comp1").selection("uni1").set("input", new String[]{"sel5", "sel6"});
    model.component("comp1").selection().create("uni2", "Union");
    model.component("comp1").selection("uni2").set("input", new String[]{"sel4", "sel5", "sel6"});
    model.component("comp1").selection().create("uni3", "Union");
    model.component("comp1").selection("uni3").set("input", new String[]{"sel3", "sel4", "sel5", "sel6", "sel7"});
    model.component("comp1").selection().create("uni4", "Union");
    model.component("comp1").selection("uni4").set("input", new String[]{"sel3", "sel4", "sel7"});
    model.component("comp1").selection().create("dif1", "Difference");
    model.component("comp1").selection("dif1").set("add", new String[]{"sel8"});
    model.component("comp1").selection("dif1").set("subtract", new String[]{"uni3"});

    model.component("comp1").cpl().create("intop1", "Integration");
    model.component("comp1").cpl("intop1").set("axisym", true);
    model.component("comp1").cpl("intop1").selection().geom("geom1", 0);
    model.component("comp1").cpl("intop1").selection().set(164);
    model.component("comp1").cpl().create("intop2", "Integration");
    model.component("comp1").cpl("intop2").set("axisym", true);
    model.component("comp1").cpl("intop2").selection().geom("geom1", 0);
    model.component("comp1").cpl("intop2").selection().set(759);
    model.component("comp1").cpl().create("intop3", "Integration");
    model.component("comp1").cpl("intop3").set("axisym", true);
    model.component("comp1").cpl("intop3").selection().geom("geom1", 2);
    model.component("comp1").cpl("intop3").selection().set(149, 816);
    model.component("comp1").cpl().create("aveop1", "Average");
    model.component("comp1").cpl("aveop1").set("axisym", true);
    model.component("comp1").cpl("aveop1").selection().geom("geom1", 2);
    model.component("comp1").cpl("aveop1").selection().set(149, 816);

    model.component("comp1").material().create("mat1", "Common");
    model.component("comp1").material("mat1").propertyGroup()
         .create("Enu", "Enu", "Young's modulus and Poisson's ratio");
    model.component("comp1").material("mat1").label("Si - Polycrystalline silicon");
    model.component("comp1").material("mat1").set("family", "custom");
    model.component("comp1").material("mat1").set("customspecular", new double[]{0.7843137254901961, 1, 1});
    model.component("comp1").material("mat1").set("diffuse", "custom");
    model.component("comp1").material("mat1")
         .set("customdiffuse", new double[]{0.6666666666666666, 0.6666666666666666, 0.7058823529411765});
    model.component("comp1").material("mat1").set("ambient", "custom");
    model.component("comp1").material("mat1")
         .set("customambient", new double[]{0.6666666666666666, 0.6666666666666666, 0.7058823529411765});
    model.component("comp1").material("mat1").set("noise", true);
    model.component("comp1").material("mat1").set("fresnel", 0.7);
    model.component("comp1").material("mat1").set("roughness", 0.5);
    model.component("comp1").material("mat1").set("diffusewrap", 0);
    model.component("comp1").material("mat1").set("reflectance", 0);
    model.component("comp1").material("mat1").propertyGroup("def").label("Basic");
    model.component("comp1").material("mat1").propertyGroup("def")
         .set("thermalexpansioncoefficient", new String[]{"2.6e-6[1/K]", "0", "0", "0", "2.6e-6[1/K]", "0", "0", "0", "2.6e-6[1/K]"});
    model.component("comp1").material("mat1").propertyGroup("def").set("heatcapacity", "678[J/(kg*K)]");
    model.component("comp1").material("mat1").propertyGroup("def")
         .set("relpermittivity", new String[]{"4.5", "0", "0", "0", "4.5", "0", "0", "0", "4.5"});
    model.component("comp1").material("mat1").propertyGroup("def").set("density", "2320[kg/m^3]");
    model.component("comp1").material("mat1").propertyGroup("def")
         .set("thermalconductivity", new String[]{"34[W/(m*K)]", "0", "0", "0", "34[W/(m*K)]", "0", "0", "0", "34[W/(m*K)]"});
    model.component("comp1").material("mat1").propertyGroup("Enu").label("Young's modulus and Poisson's ratio");
    model.component("comp1").material("mat1").propertyGroup("Enu").set("E", "160e9[Pa]");
    model.component("comp1").material("mat1").propertyGroup("Enu").set("nu", "0.22");
    model.component("comp1").material("mat1").selection().named("uni3");

    model.component("comp1").common("free1").selection().named("dif1");
    model.component("comp1").common("sym1").active(false);

    model.component("comp1").physics("es").feature("ccns1").selection().named("uni3");
    model.component("comp1").physics("es").create("term1", "DomainTerminal", 3);
    model.component("comp1").physics("es").feature("term1").selection().named("uni4");
    model.component("comp1").physics("es").feature("term1").set("TerminalType", "Voltage");
    model.component("comp1").physics("es").feature("term1").set("V0", 0);
    model.component("comp1").physics("es").feature().duplicate("term2", "term1");
    model.component("comp1").physics("es").feature("term2").selection().named("sel5");
    model.component("comp1").physics("es").feature("term2").set("V0", "Vcomb");
    model.component("comp1").physics("es").feature("term2").create("hp1", "HarmonicPerturbation", 3);
    model.component("comp1").physics("es").feature("term2").feature("hp1").set("V0", "V_ac");
    model.component("comp1").physics("es").feature("term2").feature("hp1").selection().named("sel5");
    model.component("comp1").physics("es").feature().duplicate("term3", "term2");
    model.component("comp1").physics("es").feature("term3").selection().named("sel6");
    model.component("comp1").physics("es").feature("term3").feature("hp1").selection().named("sel6");
    model.component("comp1").physics("es").feature("term3").feature("hp1").set("V0", "-V_ac");
    model.component("comp1").physics("es").create("term4", "Terminal", 2);
    model.component("comp1").physics("es").feature("term4").selection().named("sel1");
    model.component("comp1").physics("es").feature("term4").set("TerminalType", "Voltage");
    model.component("comp1").physics("es").feature("term4").set("V0", "Vbase");
    model.component("comp1").physics("es").create("gnd1", "Ground", 2);
    model.component("comp1").physics("es").feature("gnd1").selection().named("sel2");
    model.component("comp1").physics("solid").selection().named("uni3");
    model.component("comp1").physics("solid").feature("lemm1").create("dmp1", "Damping", 3);
    model.component("comp1").physics("solid").feature("lemm1").feature("dmp1")
         .set("DampingType", "IsotropicLossFactor");
    model.component("comp1").physics("solid").feature("lemm1").feature("dmp1").set("eta_s_mat", "userdef");
    model.component("comp1").physics("solid").feature("lemm1").feature("dmp1").set("eta_s", "1/Q");
    model.component("comp1").physics("solid").create("fix1", "Fixed", 2);
    model.component("comp1").physics("solid").feature("fix1").selection().named("box1");
    model.component("comp1").physics("solid").create("rotf1", "RotatingFrame", 3);
    model.component("comp1").physics("solid").feature("rotf1").set("Ovm", "Omega");
    model.component("comp1").physics("solid").feature("rotf1").set("AxisOfRotation", "yAxis");
    model.component("comp1").physics("solid").feature("rotf1").set("CoriolisForce", true);

    model.component("comp1").mesh("mesh1").create("ftet1", "FreeTet");
    model.component("comp1").mesh("mesh1").feature("ftet1").selection().geom("geom1");
    model.component("comp1").mesh("mesh1").feature("ftet1").create("size1", "Size");
    model.component("comp1").mesh("mesh1").feature("ftet1").feature("size1").selection().geom("geom1", 3);
    model.component("comp1").mesh("mesh1").feature("ftet1").feature("size1").selection().named("sel7");
    model.component("comp1").mesh("mesh1").feature("ftet1").feature("size1").set("custom", true);
    model.component("comp1").mesh("mesh1").feature("ftet1").feature("size1").set("hmaxactive", true);
    model.component("comp1").mesh("mesh1").feature("ftet1").feature("size1").set("hmax", "mf");
    model.component("comp1").mesh("mesh1").feature("ftet1").feature("size1").set("hminactive", true);
    model.component("comp1").mesh("mesh1").feature("ftet1").feature("size1").set("hmin", "mf/5");
    model.component("comp1").mesh("mesh1").feature("ftet1").feature().duplicate("size2", "size1");
    model.component("comp1").mesh("mesh1").feature("ftet1").feature("size2").selection().named("sel3");
    model.component("comp1").mesh("mesh1").feature("ftet1").feature("size2").set("hmax", "mf*4");
    model.component("comp1").mesh("mesh1").feature("ftet1").feature("size2").set("hmin", "mf*4/5");
    model.component("comp1").mesh("mesh1").feature("ftet1").feature().duplicate("size3", "size2");
    model.component("comp1").mesh("mesh1").feature("ftet1").feature("size3").selection().named("uni2");
    model.component("comp1").mesh("mesh1").feature("ftet1").create("size4", "Size");
    model.component("comp1").mesh("mesh1").feature("ftet1").feature("size4").selection().geom("geom1", 3);
    model.component("comp1").mesh("mesh1").feature("ftet1").feature("size4").selection().named("dif1");

    model.study("std1").createAutoSequences("all");

    model.sol("sol1").runAll();

    model.result().create("pg1", "PlotGroup3D");
    model.result("pg1").label("\u7535\u52bf (es)");
    model.result("pg1").set("frametype", "spatial");
    model.result("pg1").set("showlegendsmaxmin", true);
    model.result("pg1").feature().create("mslc1", "Multislice");
    model.result("pg1").feature("mslc1").set("showsolutionparams", "on");
    model.result("pg1").feature("mslc1").set("solutionparams", "parent");
    model.result("pg1").feature("mslc1").set("multiplanexmethod", "coord");
    model.result("pg1").feature("mslc1").set("xcoord", "es.CPx");
    model.result("pg1").feature("mslc1").set("multiplaneymethod", "coord");
    model.result("pg1").feature("mslc1").set("ycoord", "es.CPy");
    model.result("pg1").feature("mslc1").set("multiplanezmethod", "coord");
    model.result("pg1").feature("mslc1").set("zcoord", "es.CPz");
    model.result("pg1").feature("mslc1").set("colortable", "Dipole");
    model.result("pg1").feature("mslc1").set("showsolutionparams", "on");
    model.result("pg1").feature("mslc1").set("data", "parent");
    model.result("pg1").feature().create("strmsl1", "StreamlineMultislice");
    model.result("pg1").feature("strmsl1").set("showsolutionparams", "on");
    model.result("pg1").feature("strmsl1").set("solutionparams", "parent");
    model.result("pg1").feature("strmsl1").set("multiplanexmethod", "coord");
    model.result("pg1").feature("strmsl1").set("xcoord", "es.CPx");
    model.result("pg1").feature("strmsl1").set("multiplaneymethod", "coord");
    model.result("pg1").feature("strmsl1").set("ycoord", "es.CPy");
    model.result("pg1").feature("strmsl1").set("multiplanezmethod", "coord");
    model.result("pg1").feature("strmsl1").set("zcoord", "es.CPz");
    model.result("pg1").feature("strmsl1").set("titletype", "none");
    model.result("pg1").feature("strmsl1").set("posmethod", "uniform");
    model.result("pg1").feature("strmsl1").set("udist", 0.02);
    model.result("pg1").feature("strmsl1").set("maxlen", 0.4);
    model.result("pg1").feature("strmsl1").set("maxsteps", 5000);
    model.result("pg1").feature("strmsl1").set("maxtime", Double.POSITIVE_INFINITY);
    model.result("pg1").feature("strmsl1").set("inheritcolor", false);
    model.result("pg1").feature("strmsl1").set("showsolutionparams", "on");
    model.result("pg1").feature("strmsl1").set("maxtime", Double.POSITIVE_INFINITY);
    model.result("pg1").feature("strmsl1").set("showsolutionparams", "on");
    model.result("pg1").feature("strmsl1").set("maxtime", Double.POSITIVE_INFINITY);
    model.result("pg1").feature("strmsl1").set("showsolutionparams", "on");
    model.result("pg1").feature("strmsl1").set("maxtime", Double.POSITIVE_INFINITY);
    model.result("pg1").feature("strmsl1").set("showsolutionparams", "on");
    model.result("pg1").feature("strmsl1").set("maxtime", Double.POSITIVE_INFINITY);
    model.result("pg1").feature("strmsl1").set("data", "parent");
    model.result("pg1").feature("strmsl1").set("inheritplot", "mslc1");
    model.result("pg1").feature("strmsl1").feature().create("col1", "Color");
    model.result("pg1").feature("strmsl1").feature("col1").set("colortable", "DipoleDark");
    model.result("pg1").feature("strmsl1").feature("col1").set("colorlegend", false);
    model.result("pg1").feature("strmsl1").feature().create("filt1", "Filter");
    model.result("pg1").feature("strmsl1").feature("filt1").set("expr", "!isScalingSystemDomain");
    model.result().create("pg2", "PlotGroup3D");
    model.result("pg2").label("\u7535\u573a (es)");
    model.result("pg2").set("frametype", "spatial");
    model.result("pg2").set("showlegendsmaxmin", true);
    model.result("pg2").feature().create("mslc1", "Multislice");
    model.result("pg2").feature("mslc1").set("showsolutionparams", "on");
    model.result("pg2").feature("mslc1").set("solutionparams", "parent");
    model.result("pg2").feature("mslc1").set("expr", "es.normE");
    model.result("pg2").feature("mslc1").set("multiplanexmethod", "coord");
    model.result("pg2").feature("mslc1").set("xcoord", "es.CPx");
    model.result("pg2").feature("mslc1").set("multiplaneymethod", "coord");
    model.result("pg2").feature("mslc1").set("ycoord", "es.CPy");
    model.result("pg2").feature("mslc1").set("multiplanezmethod", "coord");
    model.result("pg2").feature("mslc1").set("zcoord", "es.CPz");
    model.result("pg2").feature("mslc1").set("colortable", "Prism");
    model.result("pg2").feature("mslc1").set("colortabletrans", "nonlinear");
    model.result("pg2").feature("mslc1").set("colorcalibration", -0.8);
    model.result("pg2").feature("mslc1").set("showsolutionparams", "on");
    model.result("pg2").feature("mslc1").set("data", "parent");
    model.result("pg2").feature().create("strmsl1", "StreamlineMultislice");
    model.result("pg2").feature("strmsl1").set("showsolutionparams", "on");
    model.result("pg2").feature("strmsl1").set("solutionparams", "parent");
    model.result("pg2").feature("strmsl1").set("multiplanexmethod", "coord");
    model.result("pg2").feature("strmsl1").set("xcoord", "es.CPx");
    model.result("pg2").feature("strmsl1").set("multiplaneymethod", "coord");
    model.result("pg2").feature("strmsl1").set("ycoord", "es.CPy");
    model.result("pg2").feature("strmsl1").set("multiplanezmethod", "coord");
    model.result("pg2").feature("strmsl1").set("zcoord", "es.CPz");
    model.result("pg2").feature("strmsl1").set("titletype", "none");
    model.result("pg2").feature("strmsl1").set("posmethod", "uniform");
    model.result("pg2").feature("strmsl1").set("udist", 0.02);
    model.result("pg2").feature("strmsl1").set("maxlen", 0.4);
    model.result("pg2").feature("strmsl1").set("maxsteps", 5000);
    model.result("pg2").feature("strmsl1").set("maxtime", Double.POSITIVE_INFINITY);
    model.result("pg2").feature("strmsl1").set("inheritcolor", false);
    model.result("pg2").feature("strmsl1").set("showsolutionparams", "on");
    model.result("pg2").feature("strmsl1").set("maxtime", Double.POSITIVE_INFINITY);
    model.result("pg2").feature("strmsl1").set("showsolutionparams", "on");
    model.result("pg2").feature("strmsl1").set("maxtime", Double.POSITIVE_INFINITY);
    model.result("pg2").feature("strmsl1").set("showsolutionparams", "on");
    model.result("pg2").feature("strmsl1").set("maxtime", Double.POSITIVE_INFINITY);
    model.result("pg2").feature("strmsl1").set("showsolutionparams", "on");
    model.result("pg2").feature("strmsl1").set("maxtime", Double.POSITIVE_INFINITY);
    model.result("pg2").feature("strmsl1").set("data", "parent");
    model.result("pg2").feature("strmsl1").set("inheritplot", "mslc1");
    model.result("pg2").feature("strmsl1").feature().create("col1", "Color");
    model.result("pg2").feature("strmsl1").feature("col1").set("expr", "es.normE");
    model.result("pg2").feature("strmsl1").feature("col1").set("colortable", "PrismDark");
    model.result("pg2").feature("strmsl1").feature("col1").set("colorlegend", false);
    model.result("pg2").feature("strmsl1").feature("col1").set("colortabletrans", "nonlinear");
    model.result("pg2").feature("strmsl1").feature("col1").set("colorcalibration", -0.8);
    model.result("pg2").feature("strmsl1").feature().create("filt1", "Filter");
    model.result("pg2").feature("strmsl1").feature("filt1").set("expr", "!isScalingSystemDomain");
    model.result().create("pg3", "PlotGroup3D");
    model.result("pg3").set("data", "dset1");
    model.result("pg3").label("\u4f4d\u79fb (solid)");
    model.result("pg3").set("frametype", "spatial");
    model.result("pg3").create("vol1", "Volume");
    model.result("pg3").feature("vol1").set("expr", new String[]{"solid.disp"});
    model.result("pg3").feature("vol1").set("threshold", "manual");
    model.result("pg3").feature("vol1").set("thresholdvalue", 0.2);
    model.result("pg3").feature("vol1").set("colortable", "Rainbow");
    model.result("pg3").feature("vol1").set("colortabletrans", "none");
    model.result("pg3").feature("vol1").set("colorscalemode", "linear");
    model.result("pg3").feature("vol1").set("resolution", "custom");
    model.result("pg3").feature("vol1").set("refine", 2);
    model.result("pg3").feature("vol1").set("colortable", "SpectrumLight");
    model.result().create("pg4", "PlotGroup3D");
    model.result("pg4").set("data", "dset1");
    model.result("pg4").label("\u52a8\u7f51\u683c");
    model.result("pg4").create("mesh1", "Mesh");
    model.result("pg4").feature("mesh1").set("meshdomain", "volume");
    model.result("pg4").feature("mesh1").set("colortable", "TrafficFlow");
    model.result("pg4").feature("mesh1").set("colortabletrans", "nonlinear");
    model.result("pg4").feature("mesh1").set("nonlinearcolortablerev", true);
    model.result("pg4").feature("mesh1").create("sel1", "MeshSelection");
    model.result("pg4").feature("mesh1").feature("sel1").selection()
         .set(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113);
    model.result("pg4").feature("mesh1").set("qualmeasure", "custom");
    model.result("pg4").feature("mesh1").set("qualexpr", "comp1.spatial.relVol");
    model.result("pg4").feature("mesh1").set("colorrangeunitinterval", false);
    model.result("pg1").run();
    model.result("pg3").run();
    model.result("pg3").run();
    model.result("pg3").feature("vol1").create("def1", "Deform");
    model.result("pg3").run();

    model.study().create("std2");
    model.study("std2").create("stat", "Stationary");
    model.study("std2").feature("stat").set("plotgroup", "Default");
    model.study("std2").feature("stat").set("outputmap", new String[]{});
    model.study("std2").feature("stat").set("ngenAUX", "1");
    model.study("std2").feature("stat").set("goalngenAUX", "1");
    model.study("std2").feature("stat").set("ngenAUX", "1");
    model.study("std2").feature("stat").set("goalngenAUX", "1");
    model.study("std2").feature("stat").setSolveFor("/physics/es", true);
    model.study("std2").feature("stat").setSolveFor("/physics/solid", true);
    model.study("std2").feature("stat").setSolveFor("/multiphysics/eme1", true);
    model.study("std2").create("eig", "Eigenfrequency");
    model.study("std2").feature("eig").set("plotgroup", "Default");
    model.study("std2").feature("eig").set("storefact", false);
    model.study("std2").feature("eig").set("outputmap", new String[]{});
    model.study("std2").feature("eig").set("filtereigdescription", new String[]{"Damped natural frequency"});
    model.study("std2").feature("eig").set("ngenAUX", "1");
    model.study("std2").feature("eig").set("goalngenAUX", "1");
    model.study("std2").feature("eig").set("ngenAUX", "1");
    model.study("std2").feature("eig").set("goalngenAUX", "1");
    model.study("std2").feature("eig").setSolveFor("/physics/es", true);
    model.study("std2").feature("eig").setSolveFor("/physics/solid", true);
    model.study("std2").feature("eig").setSolveFor("/multiphysics/eme1", true);

    model.component("comp1").common().create("mpf1", "ParticipationFactors");

    model.study("std2").createAutoSequences("all");

    model.sol("sol2").runAll();

    model.result().create("pg5", "PlotGroup3D");
    model.result("pg5").label("\u7535\u52bf (es) 1");
    model.result("pg5").set("data", "dset2");
    model.result("pg5").setIndex("looplevel", 1, 0);
    model.result("pg5").set("frametype", "spatial");
    model.result("pg5").set("showlegendsmaxmin", true);
    model.result("pg5").feature().create("mslc1", "Multislice");
    model.result("pg5").feature("mslc1").set("showsolutionparams", "on");
    model.result("pg5").feature("mslc1").set("solutionparams", "parent");
    model.result("pg5").feature("mslc1").set("evalmethodactive", "off");
    model.result("pg5").feature("mslc1").set("multiplanexmethod", "coord");
    model.result("pg5").feature("mslc1").set("xcoord", "es.CPx");
    model.result("pg5").feature("mslc1").set("multiplaneymethod", "coord");
    model.result("pg5").feature("mslc1").set("ycoord", "es.CPy");
    model.result("pg5").feature("mslc1").set("multiplanezmethod", "coord");
    model.result("pg5").feature("mslc1").set("zcoord", "es.CPz");
    model.result("pg5").feature("mslc1").set("colortable", "Dipole");
    model.result("pg5").feature("mslc1").set("showsolutionparams", "on");
    model.result("pg5").feature("mslc1").set("evalmethodactive", "off");
    model.result("pg5").feature("mslc1").set("showsolutionparams", "on");
    model.result("pg5").feature("mslc1").set("evalmethodactive", "off");
    model.result("pg5").feature("mslc1").set("showsolutionparams", "on");
    model.result("pg5").feature("mslc1").set("evalmethodactive", "off");
    model.result("pg5").feature("mslc1").set("showsolutionparams", "on");
    model.result("pg5").feature("mslc1").set("evalmethodactive", "off");
    model.result("pg5").feature("mslc1").set("data", "parent");
    model.result("pg5").feature().create("strmsl1", "StreamlineMultislice");
    model.result("pg5").feature("strmsl1").set("showsolutionparams", "on");
    model.result("pg5").feature("strmsl1").set("solutionparams", "parent");
    model.result("pg5").feature("strmsl1").set("evalmethodactive", "off");
    model.result("pg5").feature("strmsl1").set("multiplanexmethod", "coord");
    model.result("pg5").feature("strmsl1").set("xcoord", "es.CPx");
    model.result("pg5").feature("strmsl1").set("multiplaneymethod", "coord");
    model.result("pg5").feature("strmsl1").set("ycoord", "es.CPy");
    model.result("pg5").feature("strmsl1").set("multiplanezmethod", "coord");
    model.result("pg5").feature("strmsl1").set("zcoord", "es.CPz");
    model.result("pg5").feature("strmsl1").set("titletype", "none");
    model.result("pg5").feature("strmsl1").set("posmethod", "uniform");
    model.result("pg5").feature("strmsl1").set("udist", 0.02);
    model.result("pg5").feature("strmsl1").set("maxlen", 0.4);
    model.result("pg5").feature("strmsl1").set("maxsteps", 5000);
    model.result("pg5").feature("strmsl1").set("maxtime", Double.POSITIVE_INFINITY);
    model.result("pg5").feature("strmsl1").set("inheritcolor", false);
    model.result("pg5").feature("strmsl1").set("showsolutionparams", "on");
    model.result("pg5").feature("strmsl1").set("evalmethodactive", "off");
    model.result("pg5").feature("strmsl1").set("maxtime", Double.POSITIVE_INFINITY);
    model.result("pg5").feature("strmsl1").set("showsolutionparams", "on");
    model.result("pg5").feature("strmsl1").set("evalmethodactive", "off");
    model.result("pg5").feature("strmsl1").set("maxtime", Double.POSITIVE_INFINITY);
    model.result("pg5").feature("strmsl1").set("showsolutionparams", "on");
    model.result("pg5").feature("strmsl1").set("evalmethodactive", "off");
    model.result("pg5").feature("strmsl1").set("maxtime", Double.POSITIVE_INFINITY);
    model.result("pg5").feature("strmsl1").set("showsolutionparams", "on");
    model.result("pg5").feature("strmsl1").set("evalmethodactive", "off");
    model.result("pg5").feature("strmsl1").set("maxtime", Double.POSITIVE_INFINITY);
    model.result("pg5").feature("strmsl1").set("data", "parent");
    model.result("pg5").feature("strmsl1").set("inheritplot", "mslc1");
    model.result("pg5").feature("strmsl1").feature().create("col1", "Color");
    model.result("pg5").feature("strmsl1").feature("col1").set("evalmethodactive", "off");
    model.result("pg5").feature("strmsl1").feature("col1").set("colortable", "DipoleDark");
    model.result("pg5").feature("strmsl1").feature("col1").set("colorlegend", false);
    model.result("pg5").feature("strmsl1").feature().create("filt1", "Filter");
    model.result("pg5").feature("strmsl1").feature("filt1").set("expr", "!isScalingSystemDomain");
    model.result().create("pg6", "PlotGroup3D");
    model.result("pg6").label("\u7535\u573a (es) 1");
    model.result("pg6").set("data", "dset2");
    model.result("pg6").setIndex("looplevel", 1, 0);
    model.result("pg6").set("frametype", "spatial");
    model.result("pg6").set("showlegendsmaxmin", true);
    model.result("pg6").feature().create("mslc1", "Multislice");
    model.result("pg6").feature("mslc1").set("showsolutionparams", "on");
    model.result("pg6").feature("mslc1").set("solutionparams", "parent");
    model.result("pg6").feature("mslc1").set("expr", "es.normE");
    model.result("pg6").feature("mslc1").set("evalmethodactive", "off");
    model.result("pg6").feature("mslc1").set("multiplanexmethod", "coord");
    model.result("pg6").feature("mslc1").set("xcoord", "es.CPx");
    model.result("pg6").feature("mslc1").set("multiplaneymethod", "coord");
    model.result("pg6").feature("mslc1").set("ycoord", "es.CPy");
    model.result("pg6").feature("mslc1").set("multiplanezmethod", "coord");
    model.result("pg6").feature("mslc1").set("zcoord", "es.CPz");
    model.result("pg6").feature("mslc1").set("colortable", "Prism");
    model.result("pg6").feature("mslc1").set("colortabletrans", "nonlinear");
    model.result("pg6").feature("mslc1").set("colorcalibration", -0.8);
    model.result("pg6").feature("mslc1").set("showsolutionparams", "on");
    model.result("pg6").feature("mslc1").set("evalmethodactive", "off");
    model.result("pg6").feature("mslc1").set("showsolutionparams", "on");
    model.result("pg6").feature("mslc1").set("evalmethodactive", "off");
    model.result("pg6").feature("mslc1").set("showsolutionparams", "on");
    model.result("pg6").feature("mslc1").set("evalmethodactive", "off");
    model.result("pg6").feature("mslc1").set("showsolutionparams", "on");
    model.result("pg6").feature("mslc1").set("evalmethodactive", "off");

    return model;
  }

  public static Model run2(Model model) {
    model.result("pg6").feature("mslc1").set("data", "parent");
    model.result("pg6").feature().create("strmsl1", "StreamlineMultislice");
    model.result("pg6").feature("strmsl1").set("showsolutionparams", "on");
    model.result("pg6").feature("strmsl1").set("solutionparams", "parent");
    model.result("pg6").feature("strmsl1").set("evalmethodactive", "off");
    model.result("pg6").feature("strmsl1").set("multiplanexmethod", "coord");
    model.result("pg6").feature("strmsl1").set("xcoord", "es.CPx");
    model.result("pg6").feature("strmsl1").set("multiplaneymethod", "coord");
    model.result("pg6").feature("strmsl1").set("ycoord", "es.CPy");
    model.result("pg6").feature("strmsl1").set("multiplanezmethod", "coord");
    model.result("pg6").feature("strmsl1").set("zcoord", "es.CPz");
    model.result("pg6").feature("strmsl1").set("titletype", "none");
    model.result("pg6").feature("strmsl1").set("posmethod", "uniform");
    model.result("pg6").feature("strmsl1").set("udist", 0.02);
    model.result("pg6").feature("strmsl1").set("maxlen", 0.4);
    model.result("pg6").feature("strmsl1").set("maxsteps", 5000);
    model.result("pg6").feature("strmsl1").set("maxtime", Double.POSITIVE_INFINITY);
    model.result("pg6").feature("strmsl1").set("inheritcolor", false);
    model.result("pg6").feature("strmsl1").set("showsolutionparams", "on");
    model.result("pg6").feature("strmsl1").set("evalmethodactive", "off");
    model.result("pg6").feature("strmsl1").set("maxtime", Double.POSITIVE_INFINITY);
    model.result("pg6").feature("strmsl1").set("showsolutionparams", "on");
    model.result("pg6").feature("strmsl1").set("evalmethodactive", "off");
    model.result("pg6").feature("strmsl1").set("maxtime", Double.POSITIVE_INFINITY);
    model.result("pg6").feature("strmsl1").set("showsolutionparams", "on");
    model.result("pg6").feature("strmsl1").set("evalmethodactive", "off");
    model.result("pg6").feature("strmsl1").set("maxtime", Double.POSITIVE_INFINITY);
    model.result("pg6").feature("strmsl1").set("showsolutionparams", "on");
    model.result("pg6").feature("strmsl1").set("evalmethodactive", "off");
    model.result("pg6").feature("strmsl1").set("maxtime", Double.POSITIVE_INFINITY);
    model.result("pg6").feature("strmsl1").set("data", "parent");
    model.result("pg6").feature("strmsl1").set("inheritplot", "mslc1");
    model.result("pg6").feature("strmsl1").feature().create("col1", "Color");
    model.result("pg6").feature("strmsl1").feature("col1").set("expr", "es.normE");
    model.result("pg6").feature("strmsl1").feature("col1").set("evalmethodactive", "off");
    model.result("pg6").feature("strmsl1").feature("col1").set("colortable", "PrismDark");
    model.result("pg6").feature("strmsl1").feature("col1").set("colorlegend", false);
    model.result("pg6").feature("strmsl1").feature("col1").set("colortabletrans", "nonlinear");
    model.result("pg6").feature("strmsl1").feature("col1").set("colorcalibration", -0.8);
    model.result("pg6").feature("strmsl1").feature().create("filt1", "Filter");
    model.result("pg6").feature("strmsl1").feature("filt1").set("expr", "!isScalingSystemDomain");
    model.result().dataset("dset2").set("frametype", "spatial");
    model.result().create("pg7", "PlotGroup3D");
    model.result("pg7").set("data", "dset2");
    model.result("pg7").setIndex("looplevel", 1, 0);
    model.result("pg7").set("frametype", "spatial");
    model.result("pg7").label("\u632f\u578b (solid)");
    model.result("pg7").set("showlegends", false);
    model.result("pg7").create("surf1", "Surface");
    model.result("pg7").feature("surf1").set("expr", new String[]{"solid.disp"});
    model.result("pg7").feature("surf1").set("threshold", "manual");
    model.result("pg7").feature("surf1").set("thresholdvalue", 0.2);
    model.result("pg7").feature("surf1").set("colortable", "Rainbow");
    model.result("pg7").feature("surf1").set("colortabletrans", "none");
    model.result("pg7").feature("surf1").set("colorscalemode", "linear");
    model.result("pg7").feature("surf1").set("colortable", "AuroraBorealis");
    model.result("pg7").feature("surf1").create("def", "Deform");
    model.result("pg7").feature("surf1").feature("def").set("expr", new String[]{"u", "v", "w"});
    model.result("pg7").feature("surf1").feature("def").set("descr", "\u4f4d\u79fb\u573a");
    model.result().evaluationGroup().create("std2EvgFrq", "EvaluationGroup");
    model.result().evaluationGroup("std2EvgFrq").set("data", "dset2");
    model.result().evaluationGroup("std2EvgFrq").label("\u7279\u5f81\u9891\u7387 (\u7814\u7a76 2)");
    model.result().evaluationGroup("std2EvgFrq").create("gev1", "EvalGlobal");
    model.result().evaluationGroup("std2EvgFrq").feature("gev1").setIndex("expr", "2*pi*freq", 0);
    model.result().evaluationGroup("std2EvgFrq").feature("gev1").setIndex("unit", "rad/s", 0);
    model.result().evaluationGroup("std2EvgFrq").feature("gev1").setIndex("descr", "\u89d2\u9891\u7387", 0);
    model.result().evaluationGroup("std2EvgFrq").feature("gev1").setIndex("expr", "imag(freq)/abs(freq)", 1);
    model.result().evaluationGroup("std2EvgFrq").feature("gev1").setIndex("unit", "1", 1);
    model.result().evaluationGroup("std2EvgFrq").feature("gev1").setIndex("descr", "\u963b\u5c3c\u6bd4", 1);
    model.result().evaluationGroup("std2EvgFrq").feature("gev1").setIndex("expr", "abs(freq)/imag(freq)/2", 2);
    model.result().evaluationGroup("std2EvgFrq").feature("gev1").setIndex("unit", "1", 2);
    model.result().evaluationGroup("std2EvgFrq").feature("gev1").setIndex("descr", "\u54c1\u8d28\u56e0\u5b50", 2);
    model.result().evaluationGroup("std2EvgFrq").run();
    model.result().create("pg8", "PlotGroup3D");
    model.result("pg8").set("data", "dset2");
    model.result("pg8").setIndex("looplevel", 1, 0);
    model.result("pg8").label("\u52a8\u7f51\u683c 1");
    model.result("pg8").create("mesh1", "Mesh");
    model.result("pg8").feature("mesh1").set("meshdomain", "volume");
    model.result("pg8").feature("mesh1").set("colortable", "TrafficFlow");
    model.result("pg8").feature("mesh1").set("colortabletrans", "nonlinear");
    model.result("pg8").feature("mesh1").set("nonlinearcolortablerev", true);
    model.result("pg8").feature("mesh1").create("sel1", "MeshSelection");
    model.result("pg8").feature("mesh1").feature("sel1").selection()
         .set(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113);
    model.result("pg8").feature("mesh1").set("qualmeasure", "custom");
    model.result("pg8").feature("mesh1").set("qualexpr", "comp1.spatial.relVol");
    model.result("pg8").feature("mesh1").set("colorrangeunitinterval", false);
    model.result().evaluationGroup().create("std2mpf1", "EvaluationGroup");
    model.result().evaluationGroup("std2mpf1").set("data", "dset2");
    model.result().evaluationGroup("std2mpf1").label("\u53c2\u4e0e\u56e0\u5b50 (\u7814\u7a76 2)");
    model.result().evaluationGroup("std2mpf1").create("gev1", "EvalGlobal");
    model.result().evaluationGroup("std2mpf1").feature("gev1").setIndex("expr", "mpf1.pfLnormX", 0);
    model.result().evaluationGroup("std2mpf1").feature("gev1").setIndex("unit", "1", 0);
    model.result().evaluationGroup("std2mpf1").feature("gev1")
         .setIndex("descr", "\u53c2\u4e0e\u56e0\u5b50\uff0c\u5f52\u4e00\u5316\uff0cX \u5e73\u79fb", 0);
    model.result().evaluationGroup("std2mpf1").feature("gev1").setIndex("expr", "mpf1.pfLnormY", 1);
    model.result().evaluationGroup("std2mpf1").feature("gev1").setIndex("unit", "1", 1);
    model.result().evaluationGroup("std2mpf1").feature("gev1")
         .setIndex("descr", "\u53c2\u4e0e\u56e0\u5b50\uff0c\u5f52\u4e00\u5316\uff0cY \u5e73\u79fb", 1);
    model.result().evaluationGroup("std2mpf1").feature("gev1").setIndex("expr", "mpf1.pfLnormZ", 2);
    model.result().evaluationGroup("std2mpf1").feature("gev1").setIndex("unit", "1", 2);
    model.result().evaluationGroup("std2mpf1").feature("gev1")
         .setIndex("descr", "\u53c2\u4e0e\u56e0\u5b50\uff0c\u5f52\u4e00\u5316\uff0cZ \u5e73\u79fb", 2);
    model.result().evaluationGroup("std2mpf1").feature("gev1").setIndex("expr", "mpf1.pfRnormX", 3);
    model.result().evaluationGroup("std2mpf1").feature("gev1").setIndex("unit", "1", 3);
    model.result().evaluationGroup("std2mpf1").feature("gev1")
         .setIndex("descr", "\u53c2\u4e0e\u56e0\u5b50\uff0c\u5f52\u4e00\u5316\uff0cX \u65cb\u8f6c", 3);
    model.result().evaluationGroup("std2mpf1").feature("gev1").setIndex("expr", "mpf1.pfRnormY", 4);
    model.result().evaluationGroup("std2mpf1").feature("gev1").setIndex("unit", "1", 4);
    model.result().evaluationGroup("std2mpf1").feature("gev1")
         .setIndex("descr", "\u53c2\u4e0e\u56e0\u5b50\uff0c\u5f52\u4e00\u5316\uff0cY \u65cb\u8f6c", 4);
    model.result().evaluationGroup("std2mpf1").feature("gev1").setIndex("expr", "mpf1.pfRnormZ", 5);
    model.result().evaluationGroup("std2mpf1").feature("gev1").setIndex("unit", "1", 5);
    model.result().evaluationGroup("std2mpf1").feature("gev1")
         .setIndex("descr", "\u53c2\u4e0e\u56e0\u5b50\uff0c\u5f52\u4e00\u5316\uff0cZ \u65cb\u8f6c", 5);
    model.result().evaluationGroup("std2mpf1").feature("gev1").setIndex("expr", "mpf1.mEffLX", 6);
    model.result().evaluationGroup("std2mpf1").feature("gev1").setIndex("unit", "kg", 6);
    model.result().evaluationGroup("std2mpf1").feature("gev1")
         .setIndex("descr", "\u6709\u6548\u6a21\u6001\u8d28\u91cf\uff0cX \u5e73\u79fb", 6);
    model.result().evaluationGroup("std2mpf1").feature("gev1").setIndex("expr", "mpf1.mEffLY", 7);
    model.result().evaluationGroup("std2mpf1").feature("gev1").setIndex("unit", "kg", 7);
    model.result().evaluationGroup("std2mpf1").feature("gev1")
         .setIndex("descr", "\u6709\u6548\u6a21\u6001\u8d28\u91cf\uff0cY \u5e73\u79fb", 7);
    model.result().evaluationGroup("std2mpf1").feature("gev1").setIndex("expr", "mpf1.mEffLZ", 8);
    model.result().evaluationGroup("std2mpf1").feature("gev1").setIndex("unit", "kg", 8);
    model.result().evaluationGroup("std2mpf1").feature("gev1")
         .setIndex("descr", "\u6709\u6548\u6a21\u6001\u8d28\u91cf\uff0cZ \u5e73\u79fb", 8);
    model.result().evaluationGroup("std2mpf1").feature("gev1").setIndex("expr", "mpf1.mEffRX", 9);
    model.result().evaluationGroup("std2mpf1").feature("gev1").setIndex("unit", "kg*m^2", 9);
    model.result().evaluationGroup("std2mpf1").feature("gev1")
         .setIndex("descr", "\u6709\u6548\u6a21\u6001\u8d28\u91cf\uff0cX \u65cb\u8f6c", 9);
    model.result().evaluationGroup("std2mpf1").feature("gev1").setIndex("expr", "mpf1.mEffRY", 10);
    model.result().evaluationGroup("std2mpf1").feature("gev1").setIndex("unit", "kg*m^2", 10);
    model.result().evaluationGroup("std2mpf1").feature("gev1")
         .setIndex("descr", "\u6709\u6548\u6a21\u6001\u8d28\u91cf\uff0cY \u65cb\u8f6c", 10);
    model.result().evaluationGroup("std2mpf1").feature("gev1").setIndex("expr", "mpf1.mEffRZ", 11);
    model.result().evaluationGroup("std2mpf1").feature("gev1").setIndex("unit", "kg*m^2", 11);
    model.result().evaluationGroup("std2mpf1").feature("gev1")
         .setIndex("descr", "\u6709\u6548\u6a21\u6001\u8d28\u91cf\uff0cZ \u65cb\u8f6c", 11);
    model.result().evaluationGroup("std2mpf1").run();
    model.result("pg5").run();
    model.result("pg7").run();
    model.result("pg7").stepNext(0);
    model.result("pg7").run();
    model.result("pg7").stepNext(0);
    model.result("pg7").run();
    model.result("pg7").stepNext(0);
    model.result("pg7").run();
    model.result("pg7").stepNext(0);
    model.result("pg7").run();

    model.study().create("std3");
    model.study("std3").create("stat", "Stationary");
    model.study("std3").feature("stat").set("plotgroup", "Default");
    model.study("std3").feature("stat").set("outputmap", new String[]{});
    model.study("std3").feature("stat").set("ngenAUX", "1");
    model.study("std3").feature("stat").set("goalngenAUX", "1");
    model.study("std3").feature("stat").set("ngenAUX", "1");
    model.study("std3").feature("stat").set("goalngenAUX", "1");
    model.study("std3").feature("stat").setSolveFor("/physics/es", true);
    model.study("std3").feature("stat").setSolveFor("/physics/solid", true);
    model.study("std3").feature("stat").setSolveFor("/multiphysics/eme1", true);
    model.study("std3").create("frlin", "Frequencylinearized");
    model.study("std3").feature("frlin").set("plotgroup", "Default");
    model.study("std3").feature("frlin").set("outputmap", new String[]{});
    model.study("std3").feature("frlin").set("ngenAUX", "1");
    model.study("std3").feature("frlin").set("goalngenAUX", "1");
    model.study("std3").feature("frlin").set("ngenAUX", "1");
    model.study("std3").feature("frlin").set("goalngenAUX", "1");
    model.study("std3").feature("frlin").setSolveFor("/physics/es", true);
    model.study("std3").feature("frlin").setSolveFor("/physics/solid", true);
    model.study("std3").feature("frlin").setSolveFor("/multiphysics/eme1", true);
    model.study("std3").feature("frlin").set("plist", 36130);
    model.study("std3").feature("frlin").set("useparam", true);
    model.study("std3").feature("frlin").setIndex("pname_aux", "Vcomb", 0);
    model.study("std3").feature("frlin").setIndex("plistarr_aux", "", 0);
    model.study("std3").feature("frlin").setIndex("punit_aux", "V", 0);
    model.study("std3").feature("frlin").setIndex("pname_aux", "Vcomb", 0);
    model.study("std3").feature("frlin").setIndex("plistarr_aux", "", 0);
    model.study("std3").feature("frlin").setIndex("punit_aux", "V", 0);
    model.study("std3").feature("frlin").setIndex("pname_aux", "Omega", 0);
    model.study("std3").feature("frlin").setIndex("plistarr_aux", "0 100", 0);
    model.study("std3").feature("frlin").setIndex("punit_aux", "deg/s", 0);
    model.study("std3").showAutoSequences("all");

    model.sol("sol4").feature("s2").feature("aDef").set("nullfun", "flspnull");

    model.study("std3").createAutoSequences("all");

    model.sol("sol4").runAll();

    model.result().create("pg9", "PlotGroup3D");
    model.result("pg9").label("\u7535\u52bf (es) 2");
    model.result("pg9").set("data", "dset4");
    model.result("pg9").setIndex("looplevel", 2, 0);
    model.result("pg9").setIndex("looplevel", 1, 1);
    model.result("pg9").set("frametype", "spatial");
    model.result("pg9").set("showlegendsmaxmin", true);
    model.result("pg9").feature().create("mslc1", "Multislice");
    model.result("pg9").feature("mslc1").set("showsolutionparams", "on");
    model.result("pg9").feature("mslc1").set("solutionparams", "parent");
    model.result("pg9").feature("mslc1").set("evalmethodactive", "off");
    model.result("pg9").feature("mslc1").set("multiplanexmethod", "coord");
    model.result("pg9").feature("mslc1").set("xcoord", "es.CPx");
    model.result("pg9").feature("mslc1").set("multiplaneymethod", "coord");
    model.result("pg9").feature("mslc1").set("ycoord", "es.CPy");
    model.result("pg9").feature("mslc1").set("multiplanezmethod", "coord");
    model.result("pg9").feature("mslc1").set("zcoord", "es.CPz");
    model.result("pg9").feature("mslc1").set("colortable", "Dipole");
    model.result("pg9").feature("mslc1").set("showsolutionparams", "on");
    model.result("pg9").feature("mslc1").set("evalmethodactive", "off");
    model.result("pg9").feature("mslc1").set("showsolutionparams", "on");
    model.result("pg9").feature("mslc1").set("evalmethodactive", "off");
    model.result("pg9").feature("mslc1").set("showsolutionparams", "on");
    model.result("pg9").feature("mslc1").set("evalmethodactive", "off");
    model.result("pg9").feature("mslc1").set("showsolutionparams", "on");
    model.result("pg9").feature("mslc1").set("evalmethodactive", "off");
    model.result("pg9").feature("mslc1").set("data", "parent");
    model.result("pg9").feature().create("strmsl1", "StreamlineMultislice");
    model.result("pg9").feature("strmsl1").set("showsolutionparams", "on");
    model.result("pg9").feature("strmsl1").set("solutionparams", "parent");
    model.result("pg9").feature("strmsl1").set("evalmethodactive", "off");
    model.result("pg9").feature("strmsl1").set("multiplanexmethod", "coord");
    model.result("pg9").feature("strmsl1").set("xcoord", "es.CPx");
    model.result("pg9").feature("strmsl1").set("multiplaneymethod", "coord");
    model.result("pg9").feature("strmsl1").set("ycoord", "es.CPy");
    model.result("pg9").feature("strmsl1").set("multiplanezmethod", "coord");
    model.result("pg9").feature("strmsl1").set("zcoord", "es.CPz");
    model.result("pg9").feature("strmsl1").set("titletype", "none");
    model.result("pg9").feature("strmsl1").set("posmethod", "uniform");
    model.result("pg9").feature("strmsl1").set("udist", 0.02);
    model.result("pg9").feature("strmsl1").set("maxlen", 0.4);
    model.result("pg9").feature("strmsl1").set("maxsteps", 5000);
    model.result("pg9").feature("strmsl1").set("maxtime", Double.POSITIVE_INFINITY);
    model.result("pg9").feature("strmsl1").set("inheritcolor", false);
    model.result("pg9").feature("strmsl1").set("showsolutionparams", "on");
    model.result("pg9").feature("strmsl1").set("evalmethodactive", "off");
    model.result("pg9").feature("strmsl1").set("maxtime", Double.POSITIVE_INFINITY);
    model.result("pg9").feature("strmsl1").set("showsolutionparams", "on");
    model.result("pg9").feature("strmsl1").set("evalmethodactive", "off");
    model.result("pg9").feature("strmsl1").set("maxtime", Double.POSITIVE_INFINITY);
    model.result("pg9").feature("strmsl1").set("showsolutionparams", "on");
    model.result("pg9").feature("strmsl1").set("evalmethodactive", "off");
    model.result("pg9").feature("strmsl1").set("maxtime", Double.POSITIVE_INFINITY);
    model.result("pg9").feature("strmsl1").set("showsolutionparams", "on");
    model.result("pg9").feature("strmsl1").set("evalmethodactive", "off");
    model.result("pg9").feature("strmsl1").set("maxtime", Double.POSITIVE_INFINITY);
    model.result("pg9").feature("strmsl1").set("data", "parent");
    model.result("pg9").feature("strmsl1").set("inheritplot", "mslc1");
    model.result("pg9").feature("strmsl1").feature().create("col1", "Color");
    model.result("pg9").feature("strmsl1").feature("col1").set("evalmethodactive", "off");
    model.result("pg9").feature("strmsl1").feature("col1").set("colortable", "DipoleDark");
    model.result("pg9").feature("strmsl1").feature("col1").set("colorlegend", false);
    model.result("pg9").feature("strmsl1").feature().create("filt1", "Filter");
    model.result("pg9").feature("strmsl1").feature("filt1").set("expr", "!isScalingSystemDomain");
    model.result().create("pg10", "PlotGroup3D");
    model.result("pg10").label("\u7535\u573a (es) 2");
    model.result("pg10").set("data", "dset4");
    model.result("pg10").setIndex("looplevel", 2, 0);
    model.result("pg10").setIndex("looplevel", 1, 1);
    model.result("pg10").set("frametype", "spatial");
    model.result("pg10").set("showlegendsmaxmin", true);
    model.result("pg10").feature().create("mslc1", "Multislice");
    model.result("pg10").feature("mslc1").set("showsolutionparams", "on");
    model.result("pg10").feature("mslc1").set("solutionparams", "parent");
    model.result("pg10").feature("mslc1").set("expr", "es.normE");
    model.result("pg10").feature("mslc1").set("evalmethodactive", "off");
    model.result("pg10").feature("mslc1").set("multiplanexmethod", "coord");
    model.result("pg10").feature("mslc1").set("xcoord", "es.CPx");
    model.result("pg10").feature("mslc1").set("multiplaneymethod", "coord");
    model.result("pg10").feature("mslc1").set("ycoord", "es.CPy");
    model.result("pg10").feature("mslc1").set("multiplanezmethod", "coord");
    model.result("pg10").feature("mslc1").set("zcoord", "es.CPz");
    model.result("pg10").feature("mslc1").set("colortable", "Prism");
    model.result("pg10").feature("mslc1").set("colortabletrans", "nonlinear");
    model.result("pg10").feature("mslc1").set("colorcalibration", -0.8);
    model.result("pg10").feature("mslc1").set("showsolutionparams", "on");
    model.result("pg10").feature("mslc1").set("evalmethodactive", "off");
    model.result("pg10").feature("mslc1").set("showsolutionparams", "on");
    model.result("pg10").feature("mslc1").set("evalmethodactive", "off");
    model.result("pg10").feature("mslc1").set("showsolutionparams", "on");
    model.result("pg10").feature("mslc1").set("evalmethodactive", "off");
    model.result("pg10").feature("mslc1").set("showsolutionparams", "on");
    model.result("pg10").feature("mslc1").set("evalmethodactive", "off");
    model.result("pg10").feature("mslc1").set("data", "parent");
    model.result("pg10").feature().create("strmsl1", "StreamlineMultislice");
    model.result("pg10").feature("strmsl1").set("showsolutionparams", "on");
    model.result("pg10").feature("strmsl1").set("solutionparams", "parent");
    model.result("pg10").feature("strmsl1").set("evalmethodactive", "off");
    model.result("pg10").feature("strmsl1").set("multiplanexmethod", "coord");
    model.result("pg10").feature("strmsl1").set("xcoord", "es.CPx");
    model.result("pg10").feature("strmsl1").set("multiplaneymethod", "coord");
    model.result("pg10").feature("strmsl1").set("ycoord", "es.CPy");
    model.result("pg10").feature("strmsl1").set("multiplanezmethod", "coord");
    model.result("pg10").feature("strmsl1").set("zcoord", "es.CPz");
    model.result("pg10").feature("strmsl1").set("titletype", "none");
    model.result("pg10").feature("strmsl1").set("posmethod", "uniform");
    model.result("pg10").feature("strmsl1").set("udist", 0.02);
    model.result("pg10").feature("strmsl1").set("maxlen", 0.4);
    model.result("pg10").feature("strmsl1").set("maxsteps", 5000);
    model.result("pg10").feature("strmsl1").set("maxtime", Double.POSITIVE_INFINITY);
    model.result("pg10").feature("strmsl1").set("inheritcolor", false);
    model.result("pg10").feature("strmsl1").set("showsolutionparams", "on");
    model.result("pg10").feature("strmsl1").set("evalmethodactive", "off");
    model.result("pg10").feature("strmsl1").set("maxtime", Double.POSITIVE_INFINITY);
    model.result("pg10").feature("strmsl1").set("showsolutionparams", "on");
    model.result("pg10").feature("strmsl1").set("evalmethodactive", "off");
    model.result("pg10").feature("strmsl1").set("maxtime", Double.POSITIVE_INFINITY);
    model.result("pg10").feature("strmsl1").set("showsolutionparams", "on");
    model.result("pg10").feature("strmsl1").set("evalmethodactive", "off");
    model.result("pg10").feature("strmsl1").set("maxtime", Double.POSITIVE_INFINITY);
    model.result("pg10").feature("strmsl1").set("showsolutionparams", "on");
    model.result("pg10").feature("strmsl1").set("evalmethodactive", "off");
    model.result("pg10").feature("strmsl1").set("maxtime", Double.POSITIVE_INFINITY);
    model.result("pg10").feature("strmsl1").set("data", "parent");
    model.result("pg10").feature("strmsl1").set("inheritplot", "mslc1");
    model.result("pg10").feature("strmsl1").feature().create("col1", "Color");
    model.result("pg10").feature("strmsl1").feature("col1").set("expr", "es.normE");
    model.result("pg10").feature("strmsl1").feature("col1").set("evalmethodactive", "off");
    model.result("pg10").feature("strmsl1").feature("col1").set("colortable", "PrismDark");
    model.result("pg10").feature("strmsl1").feature("col1").set("colorlegend", false);
    model.result("pg10").feature("strmsl1").feature("col1").set("colortabletrans", "nonlinear");
    model.result("pg10").feature("strmsl1").feature("col1").set("colorcalibration", -0.8);
    model.result("pg10").feature("strmsl1").feature().create("filt1", "Filter");
    model.result("pg10").feature("strmsl1").feature("filt1").set("expr", "!isScalingSystemDomain");
    model.result().dataset("dset4").set("frametype", "spatial");
    model.result().create("pg11", "PlotGroup3D");
    model.result("pg11").set("data", "dset4");
    model.result("pg11").setIndex("looplevel", 2, 0);
    model.result("pg11").setIndex("looplevel", 1, 1);
    model.result("pg11").set("frametype", "spatial");
    model.result("pg11").label("\u4f4d\u79fb (solid) 1");
    model.result("pg11").set("frametype", "spatial");
    model.result("pg11").create("vol1", "Volume");
    model.result("pg11").feature("vol1").set("expr", new String[]{"solid.disp"});
    model.result("pg11").feature("vol1").set("threshold", "manual");
    model.result("pg11").feature("vol1").set("thresholdvalue", 0.2);
    model.result("pg11").feature("vol1").set("colortable", "Rainbow");
    model.result("pg11").feature("vol1").set("colortabletrans", "none");
    model.result("pg11").feature("vol1").set("colorscalemode", "linear");
    model.result("pg11").feature("vol1").set("resolution", "custom");
    model.result("pg11").feature("vol1").set("refine", 2);
    model.result("pg11").feature("vol1").set("colortable", "SpectrumLight");
    model.result().create("pg12", "PlotGroup3D");
    model.result("pg12").set("data", "dset4");
    model.result("pg12").setIndex("looplevel", 2, 0);
    model.result("pg12").setIndex("looplevel", 1, 1);
    model.result("pg12").label("\u52a8\u7f51\u683c 2");
    model.result("pg12").create("mesh1", "Mesh");
    model.result("pg12").feature("mesh1").set("meshdomain", "volume");
    model.result("pg12").feature("mesh1").set("colortable", "TrafficFlow");
    model.result("pg12").feature("mesh1").set("colortabletrans", "nonlinear");
    model.result("pg12").feature("mesh1").set("nonlinearcolortablerev", true);
    model.result("pg12").feature("mesh1").create("sel1", "MeshSelection");
    model.result("pg12").feature("mesh1").feature("sel1").selection()
         .set(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113);
    model.result("pg12").feature("mesh1").set("qualmeasure", "custom");
    model.result("pg12").feature("mesh1").set("qualexpr", "comp1.spatial.relVol");
    model.result("pg12").feature("mesh1").set("colorrangeunitinterval", false);
    model.result("pg9").run();
    model.result("pg11").run();
    model.result().duplicate("pg13", "pg11");
    model.result("pg13").run();
    model.result("pg13").set("titletype", "manual");
    model.result("pg13").set("frametype", "material");
    model.result("pg13").set("showlegendsmaxmin", true);
    model.result("pg13").run();
    model.result("pg13").feature("vol1").set("expr", "imag(u)");
    model.result("pg13").feature("vol1").create("def1", "Deform");
    model.result("pg13").run();
    model.result("pg13").feature("vol1").feature("def1").set("expr", new String[]{"imag(u)", "imag(v)", "w"});
    model.result("pg13").feature("vol1").feature("def1").setIndex("expr", "imag(w)", 2);
    model.result("pg13").run();
    model.result("pg13").run();
    model.result("pg11").run();
    model.result().duplicate("pg14", "pg11");
    model.result("pg14").run();
    model.result("pg14").setIndex("looplevel", 1, 0);
    model.result("pg14").set("frametype", "material");
    model.result("pg14").set("showlegendsmaxmin", true);
    model.result("pg14").run();
    model.result("pg14").feature("vol1").set("expr", "w");
    model.result("pg14").feature("vol1").create("def1", "Deform");
    model.result("pg14").run();
    model.result("pg14").feature("vol1").feature("def1").set("expr", new String[]{"u", "v", "w*1e3"});
    model.result("pg14").run();
    model.result("pg14").run();
    model.result().duplicate("pg15", "pg14");
    model.result("pg15").run();
    model.result("pg15").setIndex("looplevel", 2, 0);
    model.result("pg15").run();
    model.result().dataset().create("join1", "Join");
    model.result().dataset("join1").set("data", "dset4");
    model.result().dataset("join1").set("solutions", "one");
    model.result().dataset("join1").set("data2", "dset4");
    model.result().dataset("join1").set("solutions2", "one");
    model.result().dataset("join1").set("solnum2", 1);
    model.result("pg15").run();
    model.result().duplicate("pg16", "pg15");
    model.result("pg16").run();
    model.result("pg16").set("data", "join1");
    model.result("pg16").run();

    model.title("\u5fae\u673a\u68b0\u9640\u87ba\u4eea");

    model
         .description("\u672c\u6559\u7a0b\u6f14\u793a\u4e00\u6b3e\u9640\u87ba\u4eea\u7684\u5de5\u4f5c\u539f\u7406\uff0c\u5176\u8bbe\u8ba1\u6e90\u81ea Veryst Engineering, LLC. \u7684 James Ransley \u535a\u58eb\u3002\u672c\u6a21\u578b\u5c06\u201c\u9759\u7535\u201d\u63a5\u53e3\u4e2d\u7684\u201c\u673a\u7535\u201d\u8026\u5408\u4e0e\u6df7\u5408\u6709\u9650\u5143\u516c\u5f0f\u7ed3\u5408\u4f7f\u7528\uff0c\u6a21\u578b\u51e0\u4f55\u4e3a\u5b8c\u5168\u53c2\u6570\u5316\u7684\u51e0\u4f55\uff0c\u5e76\u5e7f\u6cdb\u4f7f\u7528\u4e86\u5404\u79cd\u9009\u62e9\u7279\u5f81\u3002");

    model.mesh().clearMeshes();

    model.sol("sol1").clearSolutionData();
    model.sol("sol2").clearSolutionData();
    model.sol("sol3").clearSolutionData();
    model.sol("sol4").clearSolutionData();
    model.sol("sol5").clearSolutionData();

    model.label("gyroscope_mixed_formulation.mph");

    return model;
  }

  public static void main(String[] args) {
    Model model = run();
    run2(model);
  }

}
