/*
 * surface_micromachined_accelerometer_geom_subsequence.java
 */

import com.comsol.model.*;
import com.comsol.model.util.*;

/** Model exported on Apr 30 2026, 11:05 by COMSOL 6.3.0.290. */
public class surface_micromachined_accelerometer_geom_subsequence {

  public static Model run() {
    Model model = ModelUtil.create("Model");

    model.modelPath("D:\\Program Files\\COMSOL\\COMSOL63\\Multiphysics\\applications\\MEMS_Module\\Sensors");

    model.geom().create("part1", "Part", 3);
    model.geom("part1").geomRep("comsol");
    model.geom("part1").label("\u5e26\u53c9\u6307\u7684\u68c0\u6d4b\u8d28\u91cf\u5757");
    model.geom("part1").inputParam().set("l_PM", "440[um]");
    model.geom("part1").inputParam().descr("l_PM", "\u68c0\u6d4b\u8d28\u91cf\u5757\u957f\u5ea6");
    model.geom("part1").inputParam().set("w_PM", "100[um]");
    model.geom("part1").inputParam().descr("w_PM", "\u68c0\u6d4b\u8d28\u91cf\u5757\u5168\u5bbd");
    model.geom("part1").inputParam().set("t_PM", "2[um]");
    model.geom("part1").inputParam().descr("t_PM", "\u68c0\u6d4b\u8d28\u91cf\u5757\u539a\u5ea6");
    model.geom("part1").inputParam().set("l_f", "114[um]");
    model.geom("part1").inputParam().descr("l_f", "\u53c9\u6307\u957f\u5ea6");
    model.geom("part1").inputParam().set("w_f", "4[um]");
    model.geom("part1").inputParam().descr("w_f", "\u53c9\u6307\u5bbd\u5ea6");
    model.geom("part1").inputParam().set("n_st", "3");
    model.geom("part1").inputParam().descr("n_st", "\u81ea\u68c0\u53c9\u6307\u6570");
    model.geom("part1").inputParam().set("n_f", "7");
    model.geom("part1").inputParam().descr("n_f", "\u611f\u5e94\u53c9\u6307\u6570");
    model.geom("part1").inputParam().set("g_f", "1[um]");
    model.geom("part1").inputParam().descr("g_f", "\u611f\u5e94\u53c9\u6307\u4e4b\u95f4\u7684\u95f4\u9699");
    model.geom("part1").inputParam().set("g_st", "3[um]");
    model.geom("part1").inputParam().descr("g_st", "\u81ea\u68c0\u53c9\u6307\u4e4b\u95f4\u7684\u95f4\u9699");
    model.geom("part1").inputParam().set("x_st", "14[um]");
    model.geom("part1").inputParam().descr("x_st", "\u81ea\u68c0\u53c9\u6307\u7684\u8d77\u59cb\u4f4d\u7f6e");
    model.geom("part1").inputParam().set("x_f", "173[um]");
    model.geom("part1").inputParam().descr("x_f", "\u611f\u5e94\u53c9\u6307\u7684\u8d77\u59cb\u4f4d\u7f6e");
    model.geom("part1").inputParam().set("w_eh", "2[um]");
    model.geom("part1").inputParam().descr("w_eh", "\u523b\u8680\u5b54\u5927\u5c0f");
    model.geom("part1").inputParam().set("p_eh", "20[um]");
    model.geom("part1").inputParam().descr("p_eh", "\u523b\u8680\u5b54\u5468\u671f");
    model.geom("part1").localParam().set("n_eh", "floor((l_PM-4*w_eh)/p_eh)+1");
    model.geom("part1").localParam().descr("n_eh", "\u6cbf\u957f\u5ea6\u65b9\u5411\u7684\u523b\u8680\u5b54\u6570");
    model.geom("part1").localParam().set("m_eh", "floor((w_PM-4*w_eh)/2/p_eh)+1");
    model.geom("part1").localParam().descr("m_eh", "\u6cbf\u534a\u5bbd\u65b9\u5411\u7684\u523b\u8680\u5b54\u6570");
    model.geom("part1").localParam().set("x_eh", "(l_PM-(n_eh-1)*p_eh)/2");
    model.geom("part1").localParam().descr("x_eh", "\u7b2c\u4e00\u4e2a\u523b\u8680\u5b54\u7684\u4f4d\u7f6e");
    model.geom("part1").create("wp1", "WorkPlane");
    model.geom("part1").feature("wp1").set("unite", true);
    model.geom("part1").feature("wp1").geom().create("r1", "Rectangle");
    model.geom("part1").feature("wp1").geom().feature("r1").label("\u68c0\u6d4b\u8d28\u91cf\u5757");
    model.geom("part1").feature("wp1").geom().feature("r1").set("size", new String[]{"l_PM/2", "w_PM/2"});
    model.geom("part1").feature("wp1").geom().run("r1");
    model.geom("part1").feature("wp1").geom().create("r2", "Rectangle");
    model.geom("part1").feature("wp1").geom().feature("r2").label("\u81ea\u68c0\u53c9\u6307");
    model.geom("part1").feature("wp1").geom().feature("r2").set("size", new String[]{"w_f", "l_f"});
    model.geom("part1").feature("wp1").geom().feature("r2").set("pos", new String[]{"x_st", "w_PM/2"});
    model.geom("part1").feature("wp1").geom().run("r2");
    model.geom("part1").feature("wp1").geom().create("arr1", "Array");
    model.geom("part1").feature("wp1").geom().feature("arr1").label("\u81ea\u68c0\u53c9\u6307\u9635\u5217");
    model.geom("part1").feature("wp1").geom().feature("arr1").selection("input").set("r2");
    model.geom("part1").feature("wp1").geom().feature("arr1").set("type", "linear");
    model.geom("part1").feature("wp1").geom().feature("arr1").set("linearsize", "n_st");
    model.geom("part1").feature("wp1").geom().feature("arr1").set("displ", new String[]{"3*w_f+2*g_f+g_st", "0"});
    model.geom("part1").feature("wp1").geom().run("arr1");
    model.geom("part1").feature("wp1").geom().create("mir1", "Mirror");
    model.geom("part1").feature("wp1").geom().feature("mir1").selection("input").set("arr1(1)", "r1");
    model.geom("part1").feature("wp1").geom().feature("mir1").set("pos", new String[]{"l_PM/2", "0"});
    model.geom("part1").feature("wp1").geom().run("mir1");
    model.geom("part1").feature("wp1").geom().feature("mir1").set("keep", true);
    model.geom("part1").feature("wp1").geom().run("mir1");
    model.geom("part1").feature("wp1").geom().create("arr2", "Array");
    model.geom("part1").feature("wp1").geom().feature("arr2").selection("input").set("mir1(1)");
    model.geom("part1").feature("wp1").geom().feature("arr2").set("type", "linear");
    model.geom("part1").feature("wp1").geom().feature("arr2").set("linearsize", "n_st");
    model.geom("part1").feature("wp1").geom().feature("arr2").set("displ", new String[]{"-(3*w_f+2*g_f+g_st)", "0"});
    model.geom("part1").feature("wp1").geom().run("arr2");
    model.geom("part1").feature("wp1").geom().create("r3", "Rectangle");
    model.geom("part1").feature("wp1").geom().feature("r3").label("\u611f\u5e94\u53c9\u6307");
    model.geom("part1").feature("wp1").geom().feature("r3").set("size", new String[]{"w_f", "l_f"});
    model.geom("part1").feature("wp1").geom().feature("r3").set("pos", new String[]{"x_f", "w_PM/2"});
    model.geom("part1").feature("wp1").geom().feature("arr1").label("\u81ea\u68c0\u53c9\u6307\u9635\u5217 1");
    model.geom("part1").feature("wp1").geom().feature("arr2").label("\u81ea\u68c0\u53c9\u6307\u9635\u5217 2");
    model.geom("part1").feature("wp1").geom().run("r3");
    model.geom("part1").feature("wp1").geom().create("arr3", "Array");
    model.geom("part1").feature("wp1").geom().feature("arr3").label("\u611f\u5e94\u53c9\u6307\u9635\u5217");
    model.geom("part1").feature("wp1").geom().feature("arr3").selection("input").set("r3");
    model.geom("part1").feature("wp1").geom().feature("arr3").set("type", "linear");
    model.geom("part1").feature("wp1").geom().feature("arr3").set("linearsize", "n_f");
    model.geom("part1").feature("wp1").geom().feature("arr3").set("displ", new String[]{"3*(w_f+g_f)", "0"});
    model.geom("part1").feature("wp1").geom().run("arr3");
    model.geom("part1").feature("wp1").geom().create("uni1", "Union");
    model.geom("part1").feature("wp1").geom().feature("uni1").label("\u5408\u5e76\u53c9\u6307");
    model.geom("part1").feature("wp1").geom().feature("uni1").selection("input")
         .set("arr1", "arr2", "arr3", "mir1(2)", "r1");
    model.geom("part1").feature("wp1").geom().feature("uni1").set("intbnd", false);
    model.geom("part1").feature("wp1").geom().run("uni1");
    model.geom("part1").feature("wp1").geom().create("r4", "Rectangle");
    model.geom("part1").feature("wp1").geom().feature("r4").label("\u523b\u8680\u5b54");
    model.geom("part1").feature("wp1").geom().feature("r4").set("size", new String[]{"w_eh", "w_eh"});
    model.geom("part1").feature("wp1").geom().feature("r4").set("pos", new String[]{"x_eh", "0"});
    model.geom("part1").feature("wp1").geom().run("r4");
    model.geom("part1").feature("wp1").geom().create("arr4", "Array");
    model.geom("part1").feature("wp1").geom().feature("arr4").selection("input").set("r4");
    model.geom("part1").feature("wp1").geom().feature("arr4").set("fullsize", new String[]{"n_eh", "m_eh"});
    model.geom("part1").feature("wp1").geom().feature("arr4").set("displ", new String[]{"p_eh", "p_eh"});
    model.geom("part1").feature("wp1").geom().run("arr4");
    model.geom("part1").feature("wp1").geom().feature("r4").set("base", "center");
    model.geom("part1").feature("wp1").geom().run("arr4");
    model.geom("part1").feature("wp1").geom().create("dif1", "Difference");
    model.geom("part1").feature("wp1").geom().feature("dif1").selection("input").set("uni1");
    model.geom("part1").feature("wp1").geom().feature("dif1").selection("input2").set("arr4");
    model.geom("part1").feature("wp1").geom().run("dif1");
    model.geom("part1").run("wp1");
    model.geom("part1").feature().create("ext1", "Extrude");
    model.geom("part1").feature("ext1").label("\u62c9\u4f38\u7845");
    model.geom("part1").feature("ext1").setIndex("distance", "t_PM", 0);
    model.geom("part1").selection().create("csel1", "CumulativeSelection");
    model.geom("part1").selection("csel1").label("\u68c0\u6d4b\u8d28\u91cf\u5757 + \u53c9\u6307\u5e8f\u5217");
    model.geom("part1").feature("ext1").set("contributeto", "csel1");
    model.geom("part1").run("ext1");
    model.geom().create("part2", "Part", 3);
    model.geom("part2").geomRep("comsol");
    model.geom("part2").label("\u5f39\u7c27\u548c\u951a");
    model.geom("part2").inputParam().set("mirror", "1");
    model.geom("part2").inputParam().descr("mirror", "0\uff1a\u65e0\u955c\u50cf\uff0c1\uff1a\u955c\u50cf");
    model.geom("part2").inputParam().set("l_sp", "320[um]");
    model.geom("part2").inputParam().descr("l_sp", "\u5f39\u7c27\u957f\u5ea6");
    model.geom("part2").inputParam().set("w_sp", "2.5[um]");
    model.geom("part2").inputParam().descr("w_sp", "\u5f39\u7c27\u5bbd\u5ea6");
    model.geom("part2").inputParam().set("g_sp", "1.25[um]");
    model.geom("part2").inputParam().descr("g_sp", "\u5f39\u7c27\u95f4\u9699");
    model.geom("part2").inputParam().set("w_sp_conn", "4[um]");
    model.geom("part2").inputParam().descr("w_sp_conn", "\u5f39\u7c27\u63a5\u5934\u5bbd\u5ea6");
    model.geom("part2").inputParam().set("w_f", "4[um]");
    model.geom("part2").inputParam().descr("w_f", "\u9632\u62a4\u53c9\u6307\u5bbd\u5ea6");
    model.geom("part2").inputParam().set("l_anch_base", "17[um]");
    model.geom("part2").inputParam().descr("l_anch_base", "\u951a\u5e95\u5ea7\u957f\u5ea6");
    model.geom("part2").inputParam().set("w_anch_base", "17[um]");
    model.geom("part2").inputParam().descr("w_anch_base", "\u951a\u5e95\u5ea7\u5bbd\u5ea6");
    model.geom("part2").inputParam().set("r_anch", "3[um]");
    model.geom("part2").inputParam().descr("r_anch", "\u951a\u534a\u5f84");
    model.geom("part2").inputParam().set("x_anch", "12[um]");
    model.geom("part2").inputParam().descr("x_anch", "\u951a\u4f4d\u7f6e");
    model.geom("part2").inputParam().set("t_sp", "2[um]");
    model.geom("part2").inputParam().descr("t_sp", "\u5f39\u7c27\u539a\u5ea6");
    model.geom("part2").inputParam().set("t_anch", "1.6[um]");
    model.geom("part2").inputParam().descr("t_anch", "\u951a\u539a\u5ea6");
    model.geom("part2").inputParam().set("x_sp", "0[um]");
    model.geom("part2").inputParam().descr("x_sp", "\u4f4d\u7f6e");
    model.geom("part2").lengthUnit("\u00b5m");
    model.geom("part1").lengthUnit("\u00b5m");
    model.geom("part2").localParam().set("w_sp_anch", "l_anch_base+2*(w_f+w_sp)+3*g_sp");
    model.geom("part2").localParam().descr("w_sp_anch", "\u603b\u5bbd\u5ea6");
    model.geom("part2").create("wp1", "WorkPlane");
    model.geom("part2").feature("wp1").set("unite", true);
    model.geom("part2").feature("wp1").geom().create("r1", "Rectangle");
    model.geom("part2").feature("wp1").geom().feature("r1").label("\u6574\u4f53\u8f6e\u5ed3");
    model.geom("part2").feature("wp1").geom().feature("r1").set("size", new String[]{"w_sp_anch", "l_sp/2"});
    model.geom("part2").feature("wp1").geom().feature("r1").set("pos", new String[]{"-mirror*w_sp_anch", "0"});
    model.geom("part2").feature("wp1").geom().run("r1");
    model.geom("part2").feature("wp1").geom().create("r2", "Rectangle");
    model.geom("part2").feature("wp1").geom().feature("r2").label("\u8981\u79fb\u9664\u7684\u77e9\u5f62");
    model.geom("part2").feature("wp1").geom().feature("r2").set("size", new String[]{"l_anch_base", "1"});
    model.geom("part2").feature("wp1").geom().feature("r2").setIndex("size", "l_sp/2-w_anch_base/2", 1);
    model.geom("part2").feature("wp1").geom().feature("r2").set("pos", new String[]{"-mirror*l_anch_base", "0"});
    model.geom("part2").feature("wp1").geom().feature("r2").setIndex("pos", "w_anch_base/2", 1);
    model.geom("part2").feature("wp1").geom().run("r2");
    model.geom("part2").feature("wp1").geom().create("r3", "Rectangle");
    model.geom("part2").feature("wp1").geom().feature("r3").label("\u8981\u79fb\u9664\u7684\u77e9\u5f62 1");
    model.geom("part2").feature("wp1").geom().feature("r3")
         .set("size", new String[]{"g_sp", "l_sp/2-w_anch_base/2"});
    model.geom("part2").feature("wp1").geom().feature("r3")
         .set("pos", new String[]{"l_anch_base+w_f-mirror*(2*(l_anch_base+w_f)+g_sp)", "0"});
    model.geom("part2").feature("wp1").geom().feature("r3").setIndex("pos", "w_anch_base/2", 1);
    model.geom("part2").feature("wp1").geom().run("r3");
    model.geom("part2").feature("wp1").geom().create("r4", "Rectangle");
    model.geom("part2").feature("wp1").geom().feature("r4").label("\u8981\u79fb\u9664\u7684\u77e9\u5f62 2");
    model.geom("part2").feature("wp1").geom().feature("r4")
         .set("size", new String[]{"g_sp", "l_sp/2-w_anch_base/2"});
    model.geom("part2").feature("wp1").geom().feature("r4")
         .set("pos", new String[]{"l_anch_base+w_f+2*(w_sp+g_sp)-mirror*((l_anch_base+w_f+2*(w_sp+g_sp))*2+g_sp)", "0"});
    model.geom("part2").feature("wp1").geom().feature("r4").setIndex("pos", "w_anch_base/2", 1);
    model.geom("part2").feature("wp1").geom().run("r4");
    model.geom("part2").feature("wp1").geom().create("r5", "Rectangle");
    model.geom("part2").feature("wp1").geom().feature("r5").label("\u8981\u79fb\u9664\u7684\u77e9\u5f62 3");
    model.geom("part2").feature("wp1").geom().feature("r5").set("size", new String[]{"g_sp", "l_sp/2-w_sp_conn"});
    model.geom("part2").feature("wp1").geom().feature("r5")
         .set("pos", new String[]{"l_anch_base+w_f+g_sp+w_sp-mirror*(2*(l_anch_base+w_f+g_sp+w_sp)+g_sp)", "0"});
    model.geom("part2").feature("wp1").geom().run("r5");
    model.geom("part2").feature("wp1").geom().create("dif1", "Difference");
    model.geom("part2").feature("wp1").geom().feature("dif1").selection("input").set("r1");
    model.geom("part2").feature("wp1").geom().feature("dif1").selection("input2").set("r2", "r3", "r4", "r5");
    model.geom("part2").run("wp1");
    model.geom("part2").feature().create("ext1", "Extrude");
    model.geom("part2").feature("ext1").set("workplane", "wp1");
    model.geom("part2").feature("ext1").selection("input").set("wp1");
    model.geom("part2").feature("ext1").label("\u62c9\u4f38\u5f39\u7c27");
    model.geom("part2").feature("ext1").setIndex("distance", "t_sp", 0);
    model.geom("part2").run("ext1");
    model.geom("part2").create("wp2", "WorkPlane");
    model.geom("part2").feature("wp2").set("unite", true);
    model.geom("part2").feature("wp2").label("\u951a\u7684\u5de5\u4f5c\u5e73\u9762");
    model.geom("part2").feature("wp2").geom().create("c1", "Circle");
    model.geom("part2").feature("wp2").geom().feature("c1").set("r", "r_anch");
    model.geom("part2").feature("wp2").geom().feature("c1").set("angle", 180);
    model.geom("part2").feature("wp2").geom().feature("c1").set("pos", new String[]{"x_anch-mirror*2*x_anch", "0"});
    model.geom("part2").feature("wp2").geom().run("c1");
    model.geom("part2").run("wp2");
    model.geom("part2").feature().create("ext2", "Extrude");
    model.geom("part2").feature("ext2").set("workplane", "wp1");
    model.geom("part2").feature("ext2").selection("input").set();
    model.geom("part2").feature("ext2").set("workplane", "wp2");
    model.geom("part2").feature("ext2").selection("input").set("wp2");
    model.geom("part2").feature("ext2").label("\u62c9\u4f38\u951a");
    model.geom("part2").feature("ext2").setIndex("distance", "-t_anch", 0);
    model.geom("part2").run("ext2");
    model.geom("part2").create("uni1", "Union");
    model.geom("part2").feature("uni1").label("\u5f39\u7c27\u548c\u951a");
    model.geom("part2").feature("uni1").selection("input").set("ext1", "ext2");
    model.geom("part2").run("uni1");
    model.geom("part2").create("mov1", "Move");
    model.geom("part2").feature("mov1").selection("input").set("uni1");
    model.geom("part2").feature("mov1").set("displx", "-w_sp_anch+mirror*w_sp_anch*2+x_sp");
    model.geom("part2").run("mov1");
    model.geom("part2").selection().create("csel1", "CumulativeSelection");
    model.geom("part2").selection("csel1").label("\u5f39\u7c27 + \u951a");
    model.geom("part2").feature("mov1").set("contributeto", "csel1");
    model.geom().create("part3", "Part", 3);
    model.geom("part3").geomRep("comsol");
    model.geom("part3").label("\u7535\u6781\u9635\u5217");
    model.geom("part3").inputParam().set("LH", "1");
    model.geom("part3").inputParam().descr("LH", "0: RH, 1: LH");
    model.geom("part3").inputParam().set("l_e", "120[um]");
    model.geom("part3").inputParam().descr("l_e", "\u7535\u6781\u957f\u5ea6");
    model.geom("part3").inputParam().set("w_e", "4[um]");
    model.geom("part3").inputParam().descr("w_e", "\u7535\u6781\u5bbd\u5ea6");
    model.geom("part3").inputParam().set("l_p", "16[um]");
    model.geom("part3").inputParam().descr("l_p", "\u57ab\u957f");
    model.geom("part3").inputParam().set("w_p", "8[um]");
    model.geom("part3").inputParam().descr("w_p", "\u57ab\u5bbd");
    model.geom("part3").inputParam().set("r_an", "2[um]");
    model.geom("part3").inputParam().descr("r_an", "\u951a\u534a\u5f84");
    model.geom("part3").inputParam().set("t_e", "2[um]");
    model.geom("part3").inputParam().descr("t_e", "\u7535\u6781\u539a\u5ea6");
    model.geom("part3").inputParam().set("t_an", "1.6[um]");
    model.geom("part3").inputParam().descr("t_an", "\u951a\u539a\u5ea6");
    model.geom("part3").inputParam().set("n_e", "3");
    model.geom("part3").inputParam().descr("n_e", "\u7535\u6781\u6570");
    model.geom("part3").inputParam().set("p_e", "15[um]");
    model.geom("part3").inputParam().descr("p_e", "\u5468\u671f");
    model.geom("part3").inputParam().set("x_e", "0[um]");
    model.geom("part3").inputParam().descr("x_e", "x \u4f4d\u7f6e");
    model.geom("part3").inputParam().set("y_e", "0[um]");
    model.geom("part3").inputParam().descr("y_e", "y \u4f4d\u7f6e");
    model.geom("part3").lengthUnit("\u00b5m");
    model.geom("part3").create("wp1", "WorkPlane");
    model.geom("part3").feature("wp1").set("unite", true);
    model.geom("part3").feature("wp1").geom().create("r1", "Rectangle");
    model.geom("part3").feature("wp1").geom().feature("r1").set("size", new String[]{"w_e", "l_e"});
    model.geom("part3").feature("wp1").geom().run("r1");
    model.geom("part3").feature("wp1").geom().create("r2", "Rectangle");
    model.geom("part3").feature("wp1").geom().feature("r2").set("size", new String[]{"w_p", "l_p"});
    model.geom("part3").feature("wp1").geom().feature("r2").set("pos", new String[]{"LH*(-w_p+w_e)", "0"});
    model.geom("part3").feature("wp1").geom().feature("r2").setIndex("pos", "l_e", 1);
    model.geom("part3").feature("wp1").geom().run("r2");
    model.geom("part3").feature("wp1").geom().create("uni1", "Union");
    model.geom("part3").feature("wp1").geom().feature("uni1").selection("input").set("r1", "r2");
    model.geom("part3").feature("wp1").geom().feature("uni1").set("intbnd", false);
    model.geom("part3").feature("wp1").geom().feature("r1").label("\u7535\u6781");
    model.geom("part3").feature("wp1").geom().feature("r2").label("\u57ab");
    model.geom("part3").feature("wp1").geom().run("r2");
    model.geom("part3").feature("wp1").geom().run("uni1");
    model.geom("part3").run("wp1");
    model.geom("part3").feature().create("ext1", "Extrude");
    model.geom("part3").feature("ext1").setIndex("distance", "t_e", 0);
    model.geom("part3").run("ext1");
    model.geom("part3").create("wp2", "WorkPlane");
    model.geom("part3").feature("wp2").set("unite", true);
    model.geom("part3").feature("wp2").geom().create("c1", "Circle");
    model.geom("part3").feature("wp2").geom().run("c1");
    model.geom("part3").feature("wp2").geom().feature("c1").set("r", "r_an");
    model.geom("part3").feature("wp2").geom().feature("c1").set("pos", new String[]{"w_p/2+LH*(-w_p+w_e)", "0"});
    model.geom("part3").feature("wp2").geom().feature("c1").setIndex("pos", "l_e+l_p/2", 1);
    model.geom("part3").feature("wp2").geom().run("c1");
    model.geom("part3").run("wp2");
    model.geom("part3").feature().create("ext2", "Extrude");
    model.geom("part3").feature("ext2").setIndex("distance", "-t_an", 0);
    model.geom("part3").run("ext2");
    model.geom("part3").feature("ext2").label("\u62c9\u4f38\u951a");
    model.geom("part3").feature("ext1").label("\u62c9\u4f38\u7535\u6781");
    model.geom("part3").create("uni1", "Union");
    model.geom("part3").feature("uni1").selection("input").set("ext1", "ext2");
    model.geom("part3").run("uni1");
    model.geom("part3").feature("uni1").label("\u7535\u6781 + \u951a");
    model.geom("part3").create("mov1", "Move");
    model.geom("part3").feature("mov1").selection("input").set("uni1");
    model.geom("part3").feature("mov1").set("displx", "x_e");
    model.geom("part3").feature("mov1").set("disply", "y_e");
    model.geom("part3").run("mov1");
    model.geom("part3").create("arr1", "Array");
    model.geom("part3").feature("arr1").selection("input").set("mov1");
    model.geom("part3").feature("arr1").set("type", "linear");
    model.geom("part3").feature("arr1").set("linearsize", "n_e");
    model.geom("part3").feature("arr1").set("displ", new String[]{"p_e", "0", "0"});
    model.geom("part3").selection().create("csel1", "CumulativeSelection");
    model.geom("part3").selection("csel1").label("\u7535\u6781\u9635\u5217");
    model.geom("part3").feature("arr1").set("contributeto", "csel1");
    model.geom("part3").run("arr1");

    model.title(null);

    model.description("");

    model.label("surface_micromachined_accelerometer_geom_subsequence.mph");

    return model;
  }

  public static void main(String[] args) {
    run();
  }

}
